From return_0_17192523066_17180402725@BarraRossaRistorante.fbmta.com Fri Nov 11 17:02:13 2016
Received: from mta0227.fbmta.com ([74.209.250.227]:3668)
	by ecbiz209.inmotionhosting.com with esmtp (Exim 4.87)
	(envelope-from <return_0_17192523066_17180402725@BarraRossaRistorante.fbmta.com>)
	id 1c5Jtl-000u9O-RK
	for kyle@kylefisher.com; Fri, 11 Nov 2016 17:02:13 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; s=2010_1; d=fbmta.com;
 h=Message-ID:List-Unsubscribe:MIME-Version:From:To:Reply-To:Date:Subject:Content-Type; i=BarraRossaRistorante@BarraRossaRistorante.fbmta.com;
 bh=gahZgHhrhVmOhWcKOP5+R8eRkMc=;
 b=azDRhH2FlOSCVT4APvzeGBV9V8dkB//hgoS9jOSrOwqoEWuGNLSvX+VEiN1V/bXaM1wDirOpOv7k
   hngQBGpyIfGL39TkWwE9riJSwGtBl+Ghz9V4l7TAuONheA1Fm8Z7UKhsXUnWf/PvyyWcPh9IEPrF
   oPcc7llF+YPEq7N6bFo=
Message-ID: <RkJNAAAAAAQAwRU6AAAABAAIJCU_fMr20@BarraRossaRistorante.fbmta.com>
Require-Recipient-Valid-Since: kyle@kylefisher.com; Sun, 26 Jan 2014
 14:18:00 -0500
List-Unsubscribe: <mailto:unsubscribe_0_17192523066_17180402725@BarraRossaRistorante.fbmta.com?subject=Unsubscribe>
x-job: 017179870648_017180402725
x-virtual-mta: 74.209.250.227
X-Mailer: Fishbowl 9.0.107.0
MIME-Version: 1.0
From: "Barra Rossa Ristorante"
 <BarraRossaRistorante@BarraRossaRistorante.fbmta.com>
To: kyle@kylefisher.com
Reply-To: cschultheis@davemagrogangroup.com
Date: 11 Nov 2016 17:02:14 -0500
Subject: Come In & Try Our New Prix Fixe Menu!
Content-Type: multipart/alternative;
 boundary=--boundary_358761806_6b9f676f-094a-48f9-8a20-8858408d3ba9


----boundary_358761806_6b9f676f-094a-48f9-8a20-8858408d3ba9
Content-Type: text/plain; charset=iso-8859-1
Content-Transfer-Encoding: quoted-printable

=0D=0A=0D=0A=0D=0AView Online (http://BarraRossaRistorante.fbmta.=
com/a/1/17192523066/17181760289/default.aspx?_u=3DaHR0cDovL0JhcnJ=
hUm9zc2FSaXN0b3JhbnRlLmZibXRhLmNvbS9tZW1iZXJzL1ZpZXdNYWlsaW5nLmFz=
cHg_TWFpbGluZ0lEPTE3MTgwNDAyNzI1JlN0b3JlQ29kZT0wMDI1&_X=3DK_5jOhX=
BADwh0) =0D=0A=0D=0A=0D=0ABarra Rossa Ristorante Philadelphia=0D=0A=
929 Walnut St=0D=0APhiladelphia,=0D=0APA 19107=0D=0AP: 215-644-90=
74=0D=0A=0D=0Aphiladelphia@barrarossa.com (mailto:philadelphia@ba=
rrarossa.com) =0D=0Ahttp://barrarossa.com (http://BarraRossaRisto=
rante.fbmta.com/a/1/17192523066/17181760294/default.aspx?_u=3DaHR=
0cDovL2JhcnJhcm9zc2EuY29t0) =0D=0A=0D=0A=0D=0AVisit http://BarraR=
ossaRistorante.fbmta.com/a/1/17192523066/17181760295/default.aspx=
?_u=3DaHR0cDovL0JhcnJhUm9zc2FSaXN0b3JhbnRlLmZibXRhLmNvbS9tZW1iZXJ=
zL1Vuc3Vic2NyaWJlLmFzcHg_TWVtYmVyPWY3MjllZjU0MTJjZTRlM2ZhMWMxZTkz=
NDNhNzZhN2FiJk1haWxpbmc9MTcxODA0MDI3MjU1 to unsubscribe. Visit ht=
tp://BarraRossaRistorante.fbmta.com/a/1/17192523066/17181760297/d=
efault.aspx?Member=3Df729ef5412ce4e3fa1c1e9343a76a7ab to update y=
our profile. =0D=0A=0D=0A=0D=0AThis email was sent because you jo=
ined our email club while visiting one=0D=0Aof our establishments=
 or through our website. Your email address will=0D=0Anot be shar=
ed with anyone. You can take your name out of the email club=0D=0A=
at any time by clicking the unsubscribe link in this email and yo=
u will=0D=0Abe removed from our list immediately. You joined our =
list using=0D=0Akyle@kylefisher.com. Barra Rossa Ristorante, 18 W=
est Gay St., West Chester,=0D=0APA 19380
----boundary_358761806_6b9f676f-094a-48f9-8a20-8858408d3ba9
Content-Type: text/html; charset=iso-8859-1
Content-Transfer-Encoding: quoted-printable

<html xmlns:Indy=3D"urn:indy-scripts"><head></head><body><br />=0D=0A=
<style type=3D"text/css" media=3D"all">=0D=0A    .ExternalClass {=
 width:100%; text-align:center !important; }=0D=0A</style><div cl=
ass=3D"outerWrapper" align=3D"center"><table id=3D"viewOnlineLink=
" width=3D"650"><tr><td style=3D"font-size:11px;font-family:Verda=
na;padding-bottom:3px;text-align:right;"><a style=3D"color:#00000=
0;" href=3D"http://BarraRossaRistorante.fbmta.com/a/1/17192523066=
/17181760289/default.aspx?_u=3DaHR0cDovL0JhcnJhUm9zc2FSaXN0b3Jhbn=
RlLmZibXRhLmNvbS9tZW1iZXJzL1ZpZXdNYWlsaW5nLmFzcHg_TWFpbGluZ0lEPTE=
3MTgwNDAyNzI1JlN0b3JlQ29kZT0wMDI1&_X=3DK_5jOhXBADwh0">=0D=0A     =
                   View Online                  =0D=0A           =
         </a></td></tr></table><table width=3D"650" border=3D"0">=
<tr><td align=3D"left"><table width=3D"95%" align=3D"center" clas=
s=3D"layoutTable"><tbody><tr class=3D"editorContentBlock"><td ali=
gn=3D"center" style=3D"padding-top: 10px; padding-bottom: 10px;">=
<div editable=3D"true" class=3D"align ng-scope" image-editor=3D"t=
rue" style=3D"margin:0px auto;float:none;"><a href=3D"http://Barr=
aRossaRistorante.fbmta.com/a/0/17192523066/17181760292/default.as=
px" data-editor-url=3D"http://barrarossa.com"><img data-align-ena=
bled=3D"true" width=3D"616" height=3D"96" data-file-width=3D"4402=
" data-file-height=3D"690" data-file-id=3D"2184459" src=3D"http:/=
/assets.fbmta.com/localimages/Messages/01077834/barra_rossa_RWP_F=
inal01.png" data-map=3D"false" border=3D"0" style=3D"display: blo=
ck" /></a></div></td></tr><tr class=3D"editorContentBlock"><td al=
ign=3D"center" style=3D"padding-top: 10px; padding-bottom: 10px;"=
><div editable=3D"true" class=3D"align ng-scope" image-editor=3D"=
true" style=3D"margin:0px auto;float:none;"><img data-align-enabl=
ed=3D"true" width=3D"600" height=3D"600" data-file-width=3D"600" =
data-file-height=3D"600" data-file-id=3D"2322290" src=3D"http://a=
ssets.fbmta.com/localimages/Messages/01077834/Barra_PHL_Prix_Fixe=
_600x600_110.jpg" data-map=3D"false" border=3D"0" style=3D"displa=
y: block" /></div></td></tr></tbody></table></td></tr></table><ta=
ble width=3D"650" border=3D"0" cellpadding=3D"0" cellspacing=3D"0=
"><tr><td width=3D"650" height=3D"30" bgcolor=3D"#FFFFFF" backgro=
und=3D"http://assets.fbmta.com/localimages/Designs/00004042/1.jpg=
?e=3D827255949"><table width=3D"650" cellpadding=3D"0" cellspacin=
g=3D"0"><tr><td align=3D"center"><IMG SRC=3D"http://assets.fbmta.=
com/localimages/Clients/00008237/barra_rossa_RWP_Final-01.jpg?e=3D=
827255949" ALT=3D"Stella Rossa Ristorante" WIDTH=3D"150" HEIGHT=3D=
"24" BORDER=3D"0" style=3D"display: block"></td><td><table id=3D"=
addressBlock"><tr><td align=3D"left"><SPAN style=3D"font-family:A=
rial, Helvetica, sans-serif; font-size:8pt; ">Barra Rossa Ristora=
nte Philadelphia<br/>929 Walnut St<br/>Philadelphia, PA 19107<br/=
>P: 215-644-9074<br/></SPAN><br><A href=3D"mailto:philadelphia@ba=
rrarossa.com"><FONT style=3D"color:Black; font-family:Arial, Helv=
etica, sans-serif; font-size:8pt; text-decoration:underline; ">ph=
iladelphia@barrarossa.com</FONT></A><br><A href=3D"http://BarraRo=
ssaRistorante.fbmta.com/a/0/17192523066/17181760294/default.aspx?=
_u=3DaHR0cDovL2JhcnJhcm9zc2EuY29t0"><FONT style=3D"color:Black; f=
ont-family:Arial, Helvetica, sans-serif; font-size:8pt; text-deco=
ration:underline; ">http://barrarossa.com</FONT></A><br></td></tr=
></table></td></tr></table></td></tr></table><table width=3D"650"=
 border=3D"0" cellpadding=3D"0" cellspacing=3D"0"><tr><td><br><ta=
ble width=3D"100%" border=3D"0"><tr><td align=3D"center" NOWRAP><=
style type=3D"text/css">=0D=0A                    a:link {color: =
#000000}     /* unvisited link */=0D=0A                    a:visi=
ted {color: #000000}  /* visited link */=0D=0A                   =
 a:hover {color: #000000}   /* mouse over link */=0D=0A          =
          a:active {color: #000000}=0D=0A                </style>=
<a href=3D"http://BarraRossaRistorante.fbmta.com/a/1/17192523066/=
17181760295/default.aspx?_u=3DaHR0cDovL0JhcnJhUm9zc2FSaXN0b3JhbnR=
lLmZibXRhLmNvbS9tZW1iZXJzL1Vuc3Vic2NyaWJlLmFzcHg_TWVtYmVyPWY3Mjll=
ZjU0MTJjZTRlM2ZhMWMxZTkzNDNhNzZhN2FiJk1haWxpbmc9MTcxODA0MDI3MjU1"=
><span style=3D"color:#000000; background-color:#FFFFFF;font: 11p=
x Verdana;text-decoration:underline;">Unsubscribe</span></a>=0A<s=
pan style=3D'text-decoration:none;'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp=
;</span> <a href=3D"http://BarraRossaRistorante.fbmta.com/a/1/171=
92523066/17181760297/default.aspx?Member=3Df729ef5412ce4e3fa1c1e9=
343a76a7ab"><span style=3D"color:#000000; background-color:#FFFFF=
F;font: 11px Verdana;text-decoration:underline;">Update Your Prof=
ile</span></a>=0A<span style=3D'text-decoration:none;'>&nbsp;&nbs=
p;&nbsp;&nbsp;&nbsp;</span> </td></tr><tr><td><hr noshade width=3D=
"100%" style=3D"margin:0px"></td></tr></table><table cellpadding=3D=
"10"><tr><td valign=3D"top"><img src=3D"http://www.fishbowl.com/p=
oweredby.gif" style=3D"display: block"></td><td align=3D"left"><D=
IV style=3D"font-family:Arial, Helvetica, sans-serif; font-size:7=
pt; ">This email was sent because you joined our email club while=
 visiting one of our establishments or through our website. Your =
email address will not be shared with anyone. You can take your n=
ame out of the email club at any time by clicking the unsubscribe=
 link in this email and you will be removed from our list immedia=
tely. You joined our list using kyle@kylefisher.com. Barra Rossa =
Ristorante, 18 West Gay St., West Chester, PA 19380</DIV></td></t=
r></table></td></tr></table></div><style type=3D"text/css">=0D=0A=
                #outerWrapper a:link { color:Black;  } #outerWrap=
per a:visited {color:Black; } #outerWrapper a:hover { color:Black=
; } #outerWrapper a:active { color:Black; }=0D=0A            </st=
yle><img height=3D"1" src=3D"http://BarraRossaRistorante.fbmta.co=
m/a/17192523066/17180402725/default.gif" /></body></html>
----boundary_358761806_6b9f676f-094a-48f9-8a20-8858408d3ba9--



