From newsdigest_i_bounces@insideapple.apple.com Sat Nov 12 07:43:30 2016
Received: from msbadger0910.apple.com ([17.254.6.215]:11247)
	by ecbiz209.inmotionhosting.com with esmtps (TLSv1:DHE-RSA-AES256-SHA:256)
	(Exim 4.87)
	(envelope-from <newsdigest_i_bounces@insideapple.apple.com>)
	id 1c5Xec-001wVY-Aw
	for kyle@kylefisher.com; Sat, 12 Nov 2016 07:43:30 -0500
DKIM-Signature: v=1; a=rsa-sha1; d=insideapple.apple.com; s=insideapple2048; c=relaxed/simple;
	q=dns/txt; i=@insideapple.apple.com; t=1478954609;
	h=From:Subject:Date:To:MIME-Version:Content-Type;
	bh=YMd+jJS8UKgFMdfDDkDJ0cqEe2U=;
	b=m7uo8jKQzGl1Ve3QMcTAbap0o3NvmUIGwH11fI1Itv4Zd75D4d+YLRohltGdpL3g
	R6nZ6EaoyE1acvEXeHf5cbxyR8VQt9sZs0acjI/ru6/T6qpGsX+4fktD0EFWMm9I
	SwmyAgAAbruHYFlD6sUkN9moI3N8m5Ej98xehddu6nKy7lIKo9q1t6d+L8L3VjjN
	Zo+/3LWjgYsWVTnQuAElsU/PMb6g8X9O2RlqwqkmzVkuz0vcXYBAb4UggBAo9zdW
	xZ7pJp01YlPFdCqi2ZeZcZXMU0kKFMho3IOq2wHTavh0zQix1IWTJu0FucCCwBuB
	kTloKfWG/4bH+op59aHvgw==;
Date: Sat, 12 Nov 2016 12:43:29 +0000
From: Apple News <newsdigest@insideapple.apple.com>
To: kyle@kylefisher.com
Message-ID: <1111267515.39677084.1478954609343.JavaMail.cboxp@coldbay.apple.com>
Subject: Need to De-Stress? Try This Easy Technique
MIME-Version: 1.0
Content-Type: multipart/alternative; 
	boundary="----=_Part_39677082_1968148227.1478954609343"
X-Broadcast-Id: 145229
List-Unsubscribe: <http://mynews.apple.com/subscriptions?v=2&la=en_us&a=0uTcvmUjXMXJl8KqyvmiQl3BK3rnt2BA%2F2zG6jBTVj0brYdcZfOEEMt4JTAHyQUUlsGZpSfrOR0Ju2w5DebDaQM29rogM8Ov56c2ahZ8v2GSmqXAcF3x1ZgkKXmpf1Iqcg1q4NKNSNKCAUAOgYllWA%3D%3D>
X-Sent-To: kyle@kylefisher.com,2,NtPBS7LcxdpF3z0QwVwFi89VLzyHfbpvdZ4MvntoHOKkpDVsi9VO%2FK7BcW9htvISVUkHEQc0ozTQ9oUoaVjm%2F2P7U4pKil0YZ1jdAGMen2o%3D

------=_Part_39677082_1968148227.1478954609343
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline

Apple News Spotlight
Five stories to read this weekend, chosen by our editors.=20

How Trump Won
Most polls didn't predict Donald Trump would become the next president. But=
 his data team saw a different American electorate, and they were right.
http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnA=
gWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI4g0G0C8k

Just Breathe. You'll Feel Better.
After an exceptionally stressful election season, these controlled breathin=
g exercises can help settle your mind.
http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnA=
gWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI6j1u0L6p

An Age-Old Thanksgiving Dilemma
To stuff or not to stuff your bird? Consider the taste and food safety impl=
ications before you decide.
http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnA=
gWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI4R3w3d3M

The Waiting Game
Here's why waiting for email replies can drive you nuts =E2=80=94 and what =
you should do about it.
http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnA=
gWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI6K7x7K0h

A Journey Through Cancer and Back
When she was 25, How I Met Your Mother star Cobie Smulders was treated for =
cancer. Now, she's opening up about the battle.
http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnA=
gWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI6X8b6q1T

FEATURED CHANNELS

The Economist
http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnA=
gWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI6t3u6Q6v
CNN
http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnA=
gWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI4J4w8R2M
Science of Us
http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnA=
gWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI4R3G2W2N

Like what you're seeing here? Follow @AppleNews on Twitter for our selectio=
ns throughout the week:
http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnA=
gWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI4W7w4G1v

Copyright =C2=A9 2016 Apple Inc. 1 Infinite Loop, Cupertino, CA 95014

Privacy Policy
http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnA=
gWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI6e8i6r3v

Terms & Conditions
http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnA=
gWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI6e5u2G0k

Support
http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnA=
gWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI4g1E0p3C

Account
http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnA=
gWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI4g1q1K8M

Unsubscribe
http://mynews.apple.com/subscriptions?v=3D2&la=3Den_us&a=3D0uTcvmUjXMXJl8Kq=
yvmiQl3BK3rnt2BA%2F2zG6jBTVj0brYdcZfOEEMt4JTAHyQUUlsGZpSfrOR0Ju2w5DebDaQM29=
rogM8Ov56c2ahZ8v2GSmqXAcF3x1ZgkKXmpf1Iqcg1q4NKNSNKCAUAOgYllWA%3D%3D
------=_Part_39677082_1968148227.1478954609343
Content-Type: text/X-watch-html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline

<html><body>Plus: How Trump's data team saw a different America, solving a =
Thanksgiving dilemma, and more.</body></html>
------=_Part_39677082_1968148227.1478954609343
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.=
w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
=09<title>
=09=09Need to De-Stress? Try This Easy Technique
=09</title>
<meta name=3D"viewport" content=3D"width=3Ddevice-width" />
<meta http-equiv=3D"content-type" content=3D"text/html;charset=3Dutf-8" />
<meta http-equiv=3D"X-UA-Compatible" content=3D"IE=3Dedge" />
<style type=3D"text/css">
body { background-color:#ffffff;-webkit-font-smoothing: antialiased}
a,a.appl-link,a.appl-link:link {text-decoration:none;}
a.appl-link:hover {text-decoration:underline;}
.appl_lowbrow a,#appl-footer a,a {color:inherit;}

* {font-family: -apple-system, helvetica Neue, Helvetica, Lucida Grande, Ar=
ial,Verdana,sans-serif!important;}

@media only screen and (max-device-width: 768px) {
.appl_lowbrow,#appl-footer {-webkit-text-size-adjust:110%;}
.appl_lowbrow a,#appl-footer a, a { color:inherit; }
* { text-rendering:optimizelegibility; }
}

</style>=20

<style type=3D"text/css">
/* Mobile Styles */
@media only screen and (max-width: 480px) {
=09body{}
=09*[class~=3Dappl_desktop]{display:none!important; }
=09div[class~=3Dappl_mobile] *{ box-sizing:border-box; text-align:center;}
=09div[class~=3Dappl_mobile]{ height:auto!important; display:block!importan=
t;max-height:none!important; line-height:100%!important; overflow:visible!i=
mportant; width:auto!important;max-width:none!important;background-color:#f=
ff!important; font-family:-apple-system, helvetica Neue, Helvetica,Lucida G=
rande, Arial,Verdana,sans-serif;}
=09
=09
=09*[class~=3Dappl_pad], section[class~=3Dappl_channels] h3{ width:100%; pa=
dding:0 30px;}
=09section{width:100%; margin:0;padding:0 15px; -webkit-text-size-adjust:no=
ne; text-rendering:optimizelegibility; }
=09section.appl_100 {padding:0;}
=09section img {margin:0;max-width:100%!important}
=09section p, section a{font-family:-apple-system, Helvetica Neue,Helvetica=
, Arial, Verdana,sans-serif!important; font-weight:400; letter-spacing:0px;=
}

=09section[class~=3Daapl_logo]{ padding-top:30px!important; padding-bottom:=
14px!important; text-align:center!important;padding-left:5px;padding-right:=
5px }
=09img[class~=3Dappl_logo_img1]{width:90%!important;max-width:250px!Importa=
nt }
=09section[class~=3Dappl_headline]{ background-color:#ffffff; text-align:ce=
nter;
=09=09background-image:url('http://a1.phobos.apple.com/us/r30/Features49/v4=
/0b/81/f4/0b81f467-5e54-344d-a480-075e5298b59f/mza_7216647646932315487.jpg'=
);
=09=09background-repeat:repeat-x; background-size:400px auto; padding-top:4=
px; padding-bottom:10px; position:relative}
=09section[class~=3Dappl_headline] img {height:42px!Important;}
=09
=09section[class~=3Dappl_headline] p { font-size:18px!important; font-weigh=
t:300!important; line-height:1.4em}
=09
=09section h3=09{ margin:15px 0 0 0!important;}
=09section h3, section h3 a { font-size:23px; font-weight:700!important ; l=
ine-height:1.1em;}
=09section[class~=3Dappl_articles] { padding-top:0px;padding-bottom:5px;ove=
rflow:auto; width:100%;  }
=09section[class~=3Dappl_articles] p { font-size:16px;letter-spacing:0px!Im=
portant; line-height:1.35em; margin:10px 10px 7px 0!important; font-weight:=
400; color:#888;}
=09section[class~=3Dappl_articles] a.appl_articles_img{ display:block; widt=
h:100%; margin-top:5px;}
=09section[class~=3Dappl_articles] a.appl_articles_img img{ width:100%!impo=
rtant;height:auto!important}
=09section[class~=3Dappl_articles] div.appl_articles_cpy {border-top:1px so=
lid #e5e5e5; padding:20px 0; width:100%;text-align:left;}
=09section[class~=3Dappl_articles] div.appl_articles_cpy *{text-align:left;=
}
=09section[class~=3Dappl_articles] a.appl_source img{ width:auto!important;=
height:14px!important}
=09
=09
=09section[class~=3Dappl_channels]{ border-top:1px solid #e5e5e5; padding:2=
5px 0 25px;}
=09section[class~=3Dappl_channels] h3 { text-align:center; padding-top:0px;=
margin-top:0!important;margin-bottom:22px!important; font-weight:700!import=
ant; font-size:15px!important; letter-spacing:1.75px!important; line-height=
:1.3em;}
=09section[class~=3Dappl_channels] div { padding-left:6px;padding-right:6px=
;}
=09section[class~=3Dappl_channels] td { width:30%; }
=09section[class~=3Dappl_channels] td img{ width:98%; }
=09
=09section[class~=3Dappl_btm_cta]{  padding:0 0 25px;}
=09section[class~=3Dappl_btm_cta] * { font-size:17px!important;line-height:=
1.34em;}
=09
=09section[class~=3Dappl_footer]{ margin-top:0px;padding-top:20px!important=
; background-color:#f2f2f2;}
=09section[class~=3Dappl_footer] * {font-size:11px;line-height:1.25em;;font=
-weight:400; }
=09section[class~=3Dappl_footer] p, section[class~=3Dappl_footer] a {color:=
#666666!important;line-height:1.65em;letter-spacing:0!important}
=09section[class~=3Dappl_footer] p {margin:0 0 16px 0!important; text-align=
:center;}

=09div[class~=3Dappl_lowbrow_2]{padding-top:15px!important;padding-bottom:2=
0px;}
=09div[class~=3Dappl_lowbrow_2],
=09div[class~=3Dappl_lowbrow_2] a,
=09div[class~=3Dappl_lowbrow_1],
=09div[class~=3Dappl_lowbrow_1] a{color:#666!important}
=09
=09div[class~=3Dappl_shareicons]{padding-top:20px!important;padding-bottom:=
10px;}=09/*new*/
=09div[class~=3Dappl_shareicons] img{display:inline-block; boder:0}
}=09

/* 6 */
=09@media only screen and (max-width : 400px){
=09*[class~=3Dappl_pad], section[class~=3Dappl_channels] h3{ padding:0 25px=
;} /*new*/
=09}
/* iphone 5  */
=09@media only screen and (max-width : 320px){
=09=09*[class~=3Dappl_pad], section[class~=3Dappl_channels] h3{ width:100%;=
 padding:0 20px;} /*new*/
=09}
</style>=20








</head>
<body rightmargin=3D"0" leftmargin=3D"0" bgcolor=3D"#f2f2f2" style=3D"margi=
n:0;padding:0;">
=09<div style=3D"display:none;  max-height:0; max-width:0;width:0;height:0;=
 overflow:hidden;font-size:1px;color:#ffffff;">
=09=09Plus: How Trump's data team saw a different America, solving a Thanks=
giving dilemma, and more. <img src=3D"http://c.apple.com/img/APPLE_EMAIL_LI=
NK/spacer2.gif?v=3D2&a=3Dcc0V%2B8%2F%2FoWzjlQP1j7GxTDvJjsEdu5n4ZPbkBdJbnLpM=
Gd1dn%2FM5X%2FGs3FCCYx3GWYykz4GcNSZU%2BzfK22dfNe5We2D5zBIk2pTqo54Bb%2Fs%3D"=
 alt=3D"" width=3D"1" height=3D"1" >
=09</div>



<!-- mobile -->
<!--[if !mso]><!-->
<div style=3D"display:none;  max-height:0; max-width:0;width:0;height:0; ov=
erflow:hidden;" class=3D"appl_mobile">
<!-- TOP GRAPHIC MOBILE LINK -->
=09<section class=3D"aapl_logo appl_100">
=09=09<img src=3D"http://a1.phobos.apple.com/us/r30/Features49/v4/27/be/2f/=
27be2f2c-2786-67d4-9d80-50be200631d5/mza_372288440911797029.png" width=3D""=
 style=3D"display:block; margin:0 auto; border:0" alt=3D"NEWS SPOTLIGHT" cl=
ass=3D"appl_logo_img1" />
=09</section>
=09

=09<section class=3D"appl_headline appl_pad">
=09=09=09=09
=09=09=09<img src=3D"http://a1.phobos.apple.com/au/r30/Features71/v4/30/45/=
32/304532b2-cd72-b60d-610a-ba8442ccb813/mza_7250720696669947953.png" height=
=3D"85" style=3D" border:0" alt=3D"" class=3D"" />
=09=09=09=09
=09=09=09=09
<!--Email Subhead-->
=09=09<p>Five stories to read this weekend, chosen by our editors.</p>

=09</section>

=09
<!-- begin article 1-->
=09<section class=3D"appl_pad appl_articles">
=09=09<div class=3D"appl_articles_cpy">
=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzAeni=
JNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI6K7i0U9M"=
 class=3D"appl_articles_img"><img src=3D"http://a1.phobos.apple.com/us/r30/=
Features19/v4/51/e3/95/51e395dc-ee39-6a3b-c369-a55d91228289/mza_83785063472=
51179885.jpg" width=3D"120" height=3D"120" style=3D"display:block; margin:0=
 auto; border:0" alt=3D"Bloomberg Article Image" /></a>
=09=09=09<h3><a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYz=
AeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI4W5w9=
L5M">How Trump Won</a></h3>
=09=09=09<p>
=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzA=
eniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI4Q4n2U=
4T">Most polls didn't predict Donald Trump would become the next president.=
 But his data team saw a different American electorate, and they were right=
.</a>
=09=09=09</p>
=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzAeni=
JNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI4J8V1n0P"=
 style=3D"" class=3D"appl_source">
=09=09=09=09<img class=3D"more" src=3D"http://a1.phobos.apple.com/us/r30/Fe=
atures49/v4/23/6a/ec/236aec25-fabb-995f-4192-acbd08df77f7/mza_2903897529963=
66507.png" height=3D"13"  style=3D"margin:0; border:0" alt=3D"Bloomberg" bo=
rder=3D"0" />
=09=09=09</a>
=09=09</div>
=09=09
=09</section>
<!-- end article 1-->

<!-- begin article 2-->
=09<section class=3D"appl_pad appl_articles">
=09=09<div class=3D"appl_articles_cpy">
=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzAeni=
JNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI4D2l6b5Y"=
 class=3D"appl_articles_img"><img src=3D"http://a1.phobos.apple.com/us/r30/=
Features71/v4/7e/f9/d5/7ef9d5fa-470b-e89e-f74a-12d8bd01a10a/mza_64181802631=
5102181.jpg" width=3D"120" height=3D"120" style=3D"display:block; margin:0 =
auto; border:0" alt=3D"The New York Times Article Image" /></a>
=09=09=09<h3><a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYz=
AeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI6H2x4=
r6Y">Just Breathe. You'll Feel Better.</a></h3>
=09=09=09<p>
=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzA=
eniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI6r6b5K=
1h">After an exceptionally stressful election season, these controlled brea=
thing exercises can help settle your mind.</a>
=09=09=09</p>
=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzAeni=
JNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI6e5c0q5v"=
 style=3D"" class=3D"appl_source">
=09=09=09=09<img class=3D"more" src=3D"http://a1.phobos.apple.com/us/r30/Fe=
atures49/v4/87/57/f3/8757f3a7-bd8f-38ad-677b-057f910a4eed/mza_7300649494896=
287654.png" height=3D"13"  style=3D"margin:0; border:0" alt=3D"The New York=
 Times" border=3D"0" />
=09=09=09</a>
=09=09</div>
=09=09
=09</section>
<!-- end article 2-->

<!-- begin article 3 -->
=09<section class=3D"appl_pad appl_articles">
=09=09<div class=3D"appl_articles_cpy">
=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzAeni=
JNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI6j2d2P4M"=
 class=3D"appl_articles_img"><img src=3D"http://a1.phobos.apple.com/us/r30/=
Features71/v4/03/c4/db/03c4db3b-4d4a-8e22-4a32-cb480bbaa7c3/mza_47930698234=
57326458.jpg" width=3D"120" height=3D"120" style=3D"display:block; margin:0=
 auto; border:0" alt=3D"Epicurious Article Image" /></a>
=09=09=09<h3><a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYz=
AeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI4W2u9=
a0C">An Age-Old Thanksgiving Dilemma</a></h3>
=09=09=09<p>
=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzA=
eniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI4A2L7N=
8T">To stuff or not to stuff your bird? Consider the taste and food safety =
implications before you decide.</a>
=09=09=09</p>
=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzAeni=
JNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI6K5i6K4p"=
 style=3D"" class=3D"appl_source">
=09=09=09=09<img class=3D"more" src=3D"http://a1.phobos.apple.com/us/r30/Fe=
atures49/v4/e1/94/0f/e1940f52-f44c-41e3-3ecd-7a80b7333959/mza_1906260753939=
625652.png" height=3D"13"  style=3D"margin:0; border:0" alt=3D"Epicurious" =
border=3D"0" />
=09=09=09</a>
=09=09</div>
=09</section>
<!-- end article 3-->

<!-- begin article 4-->
=09<section class=3D"appl_pad appl_articles">
=09=09<div class=3D"appl_articles_cpy">
=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzAeni=
JNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI4D3x2E2v"=
 class=3D"appl_articles_img"><img src=3D"http://a1.phobos.apple.com/us/r30/=
Features71/v4/b6/fd/f7/b6fdf780-58f7-86e4-bb65-e3f921523db0/mza_25193976509=
0088349.jpg" width=3D"120" height=3D"120" style=3D"display:block; margin:0 =
auto; border:0" alt=3D"BBC Capital Article Image" /></a>
=09=09=09<h3><a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYz=
AeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI6K6V4=
C1h">The Waiting Game</a></h3>
=09=09=09<p>
=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzA=
eniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI4A7B5G=
2C">Here's why waiting for email replies can drive you nuts &mdash; and wha=
t you should do about it.</a>
=09=09=09</p>
=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzAeni=
JNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI6e0V5X5k"=
 style=3D"" class=3D"appl_source">
=09=09=09=09<img class=3D"more" src=3D"http://a1.phobos.apple.com/us/r30/Fe=
atures49/v4/b3/97/ee/b397ee68-b6ab-2e61-ade5-220c30f633be/mza_1941906498605=
355818.png" height=3D"13"  style=3D"margin:0; border:0" alt=3D"BBC Capital"=
 border=3D"0" />
=09=09=09</a>
=09=09</div>
=09=09
=09</section>
<!-- end article 4-->

<!-- begin article 5-->
=09<section class=3D"appl_pad appl_articles">
=09=09<div class=3D"appl_articles_cpy">
=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzAeni=
JNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI6e3d9y9h"=
 class=3D"appl_articles_img"><img src=3D"http://a1.phobos.apple.com/us/r30/=
Features71/v4/19/58/39/195839b7-e1b6-6b28-1b08-100a4f78a997/mza_78341539133=
40144423.jpg" width=3D"120" height=3D"120" style=3D"display:block; margin:0=
 auto; border:0" alt=3D"Lenny Letter Article Image" /></a>
=09=09=09<h3><a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYz=
AeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI4D0l9=
n4T">A Journey Through Cancer and Back</a></h3>
=09=09=09<p>
=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzA=
eniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI4g7d5d=
6Y">When she was 25, <i>How I Met Your Mother</i> star Cobie Smulders was t=
reated for cancer. Now, she's opening up about the battle.</a>
=09=09=09</p>
=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzAeni=
JNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI6j4E2J2C"=
 style=3D"" class=3D"appl_source">
=09=09=09=09<img class=3D"more" src=3D"http://a1.phobos.apple.com/us/r30/Fe=
atures20/v4/90/05/f9/9005f9be-d6a4-9faa-2e7a-a534af22d970/mza_3059129819754=
907147.png" height=3D"13"  style=3D"margin:0; border:0" alt=3D"Lenny Letter=
c" border=3D"0" />
=09=09=09</a>
=09=09</div>
=09=09
=09</section>
<!-- end article 5-->


<!-- begin 3 featured channels-->
=09<section class=3D"appl_pad appl_channels">
=09=09<h3>FEATURED CHANNELS</h3>
=09=09<div>
=09=09=09<table width=3D"100%" cellspacing=3D"0" cellpadding=3D"0" border=
=3D"0" align=3D"center" class=3D"">
=09=09=09=09<tr>
=09=09=09=09=09<td valign=3D"top" align=3D"left" style=3D"">
=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=
=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3D=
aI4W9L5q4k"><img src=3D"http://a1.phobos.apple.com/us/r30/Features69/v4/af/=
52/84/af5284fd-58b4-c51e-a2da-ef02bc1621bb/mza_3537111386143048258.png" wid=
th=3D"190" style=3D"display:block; margin:0; border:0" alt=3D"The Economist=
" /></a>
=09=09=09=09=09</td>
=09=09=09=09=09<td valign=3D"top" align=3D"center" style=3D"">
=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=
=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3D=
aI6y3I4V3v"><img src=3D"http://a1.phobos.apple.com/us/r30/Features71/v4/3d/=
b2/12/3db21292-7c15-1754-9625-9769ca399388/mza_5592130289466379239.png" wid=
th=3D"190" style=3D"display:block; margin:0; border:0" alt=3D"CNN" /></a>
=09=09=09=09=09</td>
=09=09=09=09=09<td valign=3D"top" align=3D"right" style=3D"">
=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=
=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3D=
aI6K0i0j4M"><img src=3D"http://a1.phobos.apple.com/us/r30/Features69/v4/1a/=
ad/e5/1aade50a-9ff4-708c-e0ee-cf11f1ea600b/mza_895927218659381649.png" widt=
h=3D"190" style=3D"display:block; margin:0; border:0" alt=3D"Science of Us"=
 /></a>
=09=09=09=09=09</td>
=09=09=09=09</tr>
=09=09=09</table>
=09=09</div>
=09</section>
<!-- end 3 featured channels-->

<!-- begin Bottom red Blurb/CTA  -->
=09<section class=3D"appl_btm_cta">
=09=09<div class=3D"appl_pad">
=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzAeni=
JNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI4y1x1k2C"=
>Like what you're seeing here? Follow <b><font color=3D"#FF2D55">@AppleNews=
</font></b> on Twitter for our selections throughout the week.</a>
=09=09</div>
=09</section>


<!-- begin footer -->
=09<section class=3D"appl_pad appl_footer">
=09=09=09
=09=09=09<p>Some content requires specific hardware or software. Internet a=
ccess required; data fees may apply. Content availability is subject to cha=
nge. For more information, <a style=3D"text-decoration:underline;" href=3D"=
http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnA=
gWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI6r0G4G4Y">click&nbsp;here</a>=
.
</p>
=09=09=09
=09=09=09<p>Copyright &copy; 2016 Apple Inc. 1 Infinite Loop, Cupertino, CA=
 95014</p>
=09=09=09
=09=09=09<div class=3D"appl_lowbrow_1">
=09=09
=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzA=
eniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI4A3E0T=
7M" class=3D"appl-link">Privacy Policy</a>
=09=09=09=09 |=20
=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzA=
eniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI6r0G4G=
4Y" class=3D"appl-link">Terms &amp; Conditions</a>
=09=09=09=09=20
=09=09=09=09
=09=09=09=09=09
=09=09=09</div>
=09=09=09=09=09=09
=09=09=09
=09=09=09
=09=09=09<div class=3D"appl_lowbrow_1">
=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzA=
eniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI4D6d4N=
3h" class=3D"appl-link">Support</a>
=09=09=09=09 |=20
=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=3DQqYzA=
eniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3DaI4A3E0x=
0k" class=3D"appl-link">Account</a>
=09=09=09</div>
=09=09=09<div class=3D"appl_lowbrow_2">
=09=09=09=09<a href=3D"http://mynews.apple.com/subscriptions?v=3D2&la=3Den_=
us&a=3D0uTcvmUjXMXJl8KqyvmiQl3BK3rnt2BA%2F2zG6jBTVj1jF%2B4%2FViF%2FFhLTV8w8=
tFGbFiOx4JghQA%2F8suznTk7thUSBXAehhq59%2B%2FGmmTzKFUQWbOK1YpMPofvYthOHQIQvx=
5VXYBSHvNymANp7uB6W9Q%3D%3D" class=3D"appl-link">Unsubscribe</a>
=09=09=09</div>
=09=09=09=09=09
=09</section>
<!-- begin Category header -->

=09
=09
=09=09
</div>
<!--<![endif]-->


<div class=3D"appl_desktop">
<!--[if gte mso 9]>
<table width=3D"680" cellspacing=3D"0" cellpadding=3D"0" border=3D"0" align=
=3D"center" style=3D"margin:0 auto;" class=3D"">
<tr><td align=3D"center" style=3D"border:1px solid #f3f3f3;">
<![endif]-->
=09<table width=3D"100%" cellspacing=3D"0" cellpadding=3D"0" border=3D"0" a=
lign=3D"center" class=3D"appl_body appl_container_full">
=09<tr>
=09=09<td bgcolor=3D"#ffffff" style=3D"min-width:680px;" >
=09=09=09<table width=3D"100%" cellspacing=3D"0" cellpadding=3D"0" border=
=3D"0" align=3D"center" style=3D"margin:0 auto; border-top:0;border-bottom:=
0;" class=3D"">
=09=09=09<tr>
=09=09=09=09<td valign=3D"top" align=3D"center" style=3D"background-color:#=
ffffff;padding-bottom:0" class=3D"appl_content">
=09=09=09=09=09<table width=3D"680" cellspacing=3D"0" cellpadding=3D"0" bor=
der=3D"0" align=3D"center" class=3D"aapl_hero_img">
=09=09=09=09=09=09<tr>
=09=09=09=09=09=09=09<td class=3D"appl_hero_img" valign=3D"top" align=3D"ce=
nter" style=3D"padding-left:8px;padding-top:40px;padding-bottom:8px;">
<!-- TOP GRAPHIC DESKTOP LINK -->
=09=09=09=09=09=09=09=09
=09=09=09=09=09=09=09=09<img src=3D"http://a1.phobos.apple.com/us/r30/Featu=
res49/v4/27/be/2f/27be2f2c-2786-67d4-9d80-50be200631d5/mza_3722884409117970=
29.png" width=3D"320" style=3D"display:block; margin:0; border:0" alt=3D"NE=
WS SPOTLIGHT" class=3D"appl_hero_img1" />
=09=09=09=09=09=09
=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09</tr>
=09=09=09=09=09</table>
=09=09=09=09=09<table width=3D"100%" cellspacing=3D"0" cellpadding=3D"0" bo=
rder=3D"0" align=3D"center" class=3D"aapl_hero_bg">
=09=09=09=09=09=09<tr>
=09=09=09=09=09=09=09<td class=3D"appl_hero_bg" height=3D"181" bgcolor=3D"#=
ffffff" background=3D"http://a1.phobos.apple.com/us/r30/Features49/v4/0b/81=
/f4/0b81f467-5e54-344d-a480-075e5298b59f/mza_7216647646932315487.jpg" valig=
n=3D"top" align=3D"center" style=3D"">

<!-- background for outlook 2007 windows and newer-->
<!--[if gte mso 9]>

<v:rect xmlns:v=3D"urn:schemas-microsoft-com:vml" fill=3D"true" stroke=3D"f=
alse" style=3D"width:680px; height:195; background-repeat:no-repeat; backgr=
ound-position:center top;">
<v:fill type=3D"tile" src=3D"http://a1.phobos.apple.com/us/r30/Features49/v=
4/0b/81/f4/0b81f467-5e54-344d-a480-075e5298b59f/mza_7216647646932315487.jpg=
" color=3D"#ffffff" />
<v:textbox style=3D"mso-fit-shape-to-text:true" inset=3D"0,0,0,0">
<![endif]-->
=09=09=09=09=09=09=09=09
=09=09=09=09=09=09=09=09<table width=3D"600" cellspacing=3D"0" cellpadding=
=3D"0" border=3D"0" align=3D"center" class=3D"">
=09=09=09=09=09=09=09=09=09<tr>
=09=09=09=09=09=09=09=09=09=09<td valign=3D"top" align=3D"center" style=3D"=
padding-top:16px">
=09=09=09=09=09=09=09=09=09=09=09<img src=3D"http://a1.phobos.apple.com/au/=
r30/Features71/v4/30/45/32/304532b2-cd72-b60d-610a-ba8442ccb813/mza_7250720=
696669947953.png" height=3D"50" style=3D"display:block; margin:0 auto; bord=
er:0" alt=3D"" class=3D"" />
=09=09=09=09=09=09=09=09=09=09
=09=09=09=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09=09=09=09</tr>
=09=09=09=09=09=09=09=09=09<tr>
=09=09=09=09=09=09=09=09=09=09<td   valign=3D"top" align=3D"center" style=
=3D"padding-top:16px;padding-bottom:30px;">
=09=09=09=09=09=09=09=09=09

=09=09=09=09=09=09=09=09=09=09=09<span style=3D" color:#000000; font-family=
: -apple-system, helvetica Neue, Helvetica, Lucida Grande, Arial,Verdana,sa=
ns-serif; font-size:22px; line-height:34px; font-weight:300;letter-spacing:=
.8px; text-decoration:none">
=09=09=09=09=09=09=09
=09=09=09=09=09=09=09=09=09=09=09Five stories to read this weekend,<br /> c=
hosen by our editors.

=09=09=09=09=09=09=09=09=09=09=09</span>
=09=09=09=09=09=09=09=09=09=09=09
=09=09=09=09=09=09=09=09=09=09
=09=09=09=09=09=09=09=09=09=09
=09=09=09=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09=09=09=09</tr>
=09=09=09=09=09=09=09=09</table>

<!--[if gte mso 9]>
</v:textbox>
</v:rect>
<![endif]-->

=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09</tr>
=09=09=09=09=09</table>

<!-- begin table containing 1 story across / bordertop / story 1-->
=09=09=09=09=09<table width=3D"600" cellspacing=3D"0" cellpadding=3D"0" bor=
der=3D"0" style=3D"margin:0 auto;  border-top:1px solid #e5e5e5" class=3D""=
>
=09=09=09=09=09=09<tr>
<!-- begin story 1 image -->
=09=09=09=09=09=09=09<td width=3D"190" valign=3D"top" align=3D"center" clas=
s=3D"appl_article_img" style=3D"padding-bottom:15px;padding-top:35px;">
=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3D=
us&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&c=
t=3DaI6K7i0U9M">
=09=09=09=09=09=09=09=09=09<img src=3D"http://a1.phobos.apple.com/us/r30/Fe=
atures19/v4/51/e3/95/51e395dc-ee39-6a3b-c369-a55d91228289/mza_8378506347251=
179885.jpg" width=3D"600" style=3D"display:block; margin:0; border:0" alt=
=3D"Bloomberg Article Image" />
=09=09=09=09=09=09=09=09</a>
=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09</tr>
=09=09=09=09=09=09<tr>
<!-- begin story 1 headline and description -->
=09=09=09=09=09=09=09<td height=3D"104" valign=3D"top" align=3D"left" style=
=3D"" class=3D"appl_story_title">
=09=09=09=09=09=09=09=09<h3 style=3D"margin-top:0;margin-bottom:11px;">
=09=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=
=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGEx=
K&ct=3DaI4W5w9L5M" style=3D"font-family: -apple-system, helvetica Neue, Hel=
vetica, Lucida Grande, Arial,Verdana,sans-serif; font-weight:700; color:#00=
0000; font-size:24px; line-height:28px;letter-spacing:0; text-decoration:no=
ne">How Trump Won</a>
=09=09=09=09=09=09=09=09</h3>
=09=09=09=09=09=09=09=09<p style=3D"margin-top:0; margin-bottom:6px;">
=09=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=
=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGEx=
K&ct=3DaI4Q4n2U4T"style=3D"font-family: -apple-system, helvetica Neue, Helv=
etica, Lucida Grande, Arial,Verdana,sans-serif; font-size:18px ; line-heigh=
t:26px; font-weight:400; color:#808080;letter-spacing:.20px; text-decoratio=
n:none">Most polls didn't predict Donald Trump would become the next presid=
ent. But his data team saw a different American electorate, and they were r=
ight.</a>
=09=09=09=09=09=09=09=09</p>
=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09</tr>
=09=09=09=09=09=09<tr>
<!-- begin story 1 cta -->
=09=09=09=09=09=09=09<td align=3D"left" style=3D"padding-bottom:34px;">
=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3D=
us&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&c=
t=3DaI4J8V1n0P" style=3D"color:#038aca" class=3D"appl-link">
=09=09=09=09=09=09=09=09=09<img class=3D"more" src=3D"http://a1.phobos.appl=
e.com/us/r30/Features49/v4/23/6a/ec/236aec25-fabb-995f-4192-acbd08df77f7/mz=
a_290389752996366507.png" height=3D"18"  style=3D"margin:0; border:0" alt=
=3D"Bloomberg" border=3D"0" />
=09=09=09=09=09=09=09=09</a>
=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09</tr>
=09=09=09=09=09</table>
<!-- end table containing 1 story across / bordertop / story 1-->

<!-- begin table containing 1 story across / bordertop / story 2-->
=09=09=09=09=09<table width=3D"600" cellspacing=3D"0" cellpadding=3D"0" bor=
der=3D"0" style=3D"margin:0 auto; border-top:1px solid #e5e5e5" class=3D"">
=09=09=09=09=09=09<tr>
<!-- begin story 2 image -->
=09=09=09=09=09=09=09<td width=3D"190" valign=3D"top" align=3D"center" clas=
s=3D"appl_article_img" style=3D"padding-bottom:15px;padding-top:35px;">
=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3D=
us&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&c=
t=3DaI4D2l6b5Y">
=09=09=09=09=09=09=09=09=09<img src=3D"http://a1.phobos.apple.com/us/r30/Fe=
atures71/v4/7e/f9/d5/7ef9d5fa-470b-e89e-f74a-12d8bd01a10a/mza_6418180263151=
02181.jpg" width=3D"600" style=3D"display:block; margin:0; border:0" alt=3D=
"The New York Times Article Image" />
=09=09=09=09=09=09=09=09</a>
=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09</tr>
=09=09=09=09=09=09<tr>
<!-- begin story 2 headline and description -->
=09=09=09=09=09=09=09<td height=3D"104" valign=3D"top" align=3D"left" style=
=3D"" class=3D"appl_story_title">
=09=09=09=09=09=09=09=09<h3 style=3D"margin-top:0;margin-bottom:13px;">
=09=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=
=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGEx=
K&ct=3DaI6H2x4r6Y" style=3D"font-family: -apple-system, helvetica Neue, Hel=
vetica, Lucida Grande, Arial,Verdana,sans-serif; font-weight:700; color:#00=
0000; font-size:24px; line-height:28px;letter-spacing:0px; text-decoration:=
none">Just Breathe. You'll Feel Better.</a>
=09=09=09=09=09=09=09=09</h3>
=09=09=09=09=09=09=09=09<p style=3D"margin-top:0; margin-bottom:6px;">
=09=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=
=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGEx=
K&ct=3DaI6r6b5K1h"style=3D"font-family: -apple-system, helvetica Neue, Helv=
etica, Lucida Grande, Arial,Verdana,sans-serif; font-size:18px ; line-heigh=
t:26px; font-weight:400; color:#808080; letter-spacing:.20px;text-decoratio=
n:none">After an exceptionally stressful election season, these controlled =
breathing exercises can help settle your mind.</a>
=09=09=09=09=09=09=09=09</p>
=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09</tr>
=09=09=09=09=09=09<tr>
<!-- begin story 2 cta -->
=09=09=09=09=09=09=09<td align=3D"left" style=3D"padding-bottom:34px;">
=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3D=
us&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&c=
t=3DaI6e5c0q5v" style=3D"color:#038aca" class=3D"appl-link">
=09=09=09=09=09=09=09=09=09<img class=3D"more" src=3D"http://a1.phobos.appl=
e.com/us/r30/Features49/v4/87/57/f3/8757f3a7-bd8f-38ad-677b-057f910a4eed/mz=
a_7300649494896287654.png" height=3D"18"  style=3D"margin:0; border:0" alt=
=3D"The New York Times" border=3D"0" />
=09=09=09=09=09=09=09=09</a>
=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09</tr>
=09=09=09=09=09</table>
<!-- end table containing 1 story across / bordertop / story 2-->


<!-- begin table containing 1 story across / story 3-->
=09=09=09=09=09<table width=3D"600" cellspacing=3D"0" cellpadding=3D"0" bor=
der=3D"0" style=3D"margin:0 auto; border-top:1px solid #e5e5e5" class=3D"">
=09=09=09=09=09=09<tr>
<!-- begin story 3 image -->
=09=09=09=09=09=09=09<td width=3D"190" valign=3D"top" align=3D"center" clas=
s=3D"appl_article_img" style=3D"padding-bottom:15px;padding-top:35px;">
=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3D=
us&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&c=
t=3DaI6j2d2P4M">
=09=09=09=09=09=09=09=09=09<img src=3D"http://a1.phobos.apple.com/us/r30/Fe=
atures71/v4/03/c4/db/03c4db3b-4d4a-8e22-4a32-cb480bbaa7c3/mza_4793069823457=
326458.jpg" width=3D"600" style=3D"display:block; margin:0; border:0" alt=
=3D"Epicurious Article Image" />
=09=09=09=09=09=09=09=09</a>
=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09</tr>
=09=09=09=09=09=09<tr>
<!-- begin story 3 headline and description -->
=09=09=09=09=09=09=09<td height=3D"104" valign=3D"top" align=3D"left" style=
=3D"" class=3D"appl_story_title">
=09=09=09=09=09=09=09=09<h3 style=3D"margin-top:0;margin-bottom:13px;">
=09=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=
=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGEx=
K&ct=3DaI4W2u9a0C" style=3D"font-family: -apple-system, helvetica Neue, Hel=
vetica, Lucida Grande, Arial,Verdana,sans-serif; font-weight:700; color:#00=
0000; font-size:24px; line-height:28px;letter-spacing:0; text-decoration:no=
ne">An Age-Old Thanksgiving Dilemma</a>
=09=09=09=09=09=09=09=09</h3>
=09=09=09=09=09=09=09=09<p style=3D"margin-top:0; margin-bottom:6px;">
=09=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=
=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGEx=
K&ct=3DaI4A2L7N8T"style=3D"font-family: -apple-system, helvetica Neue, Helv=
etica, Lucida Grande, Arial,Verdana,sans-serif; font-size:18px ; line-heigh=
t:26px;  font-weight:400; color:#808080;letter-spacing:.20px; text-decorati=
on:none">To stuff or not to stuff your bird? Consider the taste and food sa=
fety implications before you decide.</a>
=09=09=09=09=09=09=09=09</p>
=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09</tr>
=09=09=09=09=09=09<tr>
<!-- begin story 3 cta -->
=09=09=09=09=09=09=09<td align=3D"left" style=3D"padding-bottom:34px;">
=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3D=
us&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&c=
t=3DaI6K5i6K4p" style=3D"color:#038aca" class=3D"appl-link">
=09=09=09=09=09=09=09=09=09<img class=3D"more" src=3D"http://a1.phobos.appl=
e.com/us/r30/Features49/v4/e1/94/0f/e1940f52-f44c-41e3-3ecd-7a80b7333959/mz=
a_1906260753939625652.png" height=3D"18"  style=3D"margin:0; border:0" alt=
=3D"Epicurious" border=3D"0" />
=09=09=09=09=09=09=09=09</a>
=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09</tr>
=09=09=09=09=09</table>
<!-- end table containing 1 story across / bordertop /  story 3-->

<!-- begin table containing 1 story across / bordertop /  story 4-->
=09=09=09=09=09<table width=3D"600" cellspacing=3D"0" cellpadding=3D"0" bor=
der=3D"0" style=3D"margin:0 auto; border-top:1px solid #e5e5e5" class=3D"">
=09=09=09=09=09=09<tr>
<!-- begin story 4 image -->
=09=09=09=09=09=09=09<td width=3D"190" valign=3D"top" align=3D"center" clas=
s=3D"appl_article_img" style=3D"padding-bottom:15px;padding-top:35px;">
=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3D=
us&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&c=
t=3DaI4D3x2E2v">
=09=09=09=09=09=09=09=09=09<img src=3D"http://a1.phobos.apple.com/us/r30/Fe=
atures71/v4/b6/fd/f7/b6fdf780-58f7-86e4-bb65-e3f921523db0/mza_2519397650900=
88349.jpg" width=3D"600" style=3D"display:block; margin:0; border:0" alt=3D=
"BBC Capital Article Image" />
=09=09=09=09=09=09=09=09</a>
=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09</tr>
=09=09=09=09=09=09<tr>
<!-- begin story 4 headline and description -->
=09=09=09=09=09=09=09<td height=3D"104" valign=3D"top" align=3D"left" style=
=3D"" class=3D"appl_story_title">
=09=09=09=09=09=09=09=09<h3 style=3D"margin-top:0;margin-bottom:13px;">
=09=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=
=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGEx=
K&ct=3DaI6K6V4C1h" style=3D"font-family: -apple-system, helvetica Neue, Hel=
vetica, Lucida Grande, Arial,Verdana,sans-serif; font-weight:700; color:#00=
0000; font-size:24px; line-height:28px;letter-spacing:0; text-decoration:no=
ne">The Waiting Game</a>
=09=09=09=09=09=09=09=09</h3>
=09=09=09=09=09=09=09=09<p style=3D"margin-top:0; margin-bottom:6px;">
=09=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=
=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGEx=
K&ct=3DaI4A7B5G2C"style=3D"font-family: -apple-system, helvetica Neue, Helv=
etica, Lucida Grande, Arial,Verdana,sans-serif; font-size:18px ; line-heigh=
t:26px; font-weight:400; color:#808080; letter-spacing:.20px;text-decoratio=
n:none">Here's why waiting for email replies can drive you nuts &mdash; and=
 what you should do about it.</a>
=09=09=09=09=09=09=09=09</p>
=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09</tr>
=09=09=09=09=09=09<tr>
<!-- begin story 4 cta -->
=09=09=09=09=09=09=09<td align=3D"left" style=3D"padding-bottom:34px;">
=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3D=
us&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&c=
t=3DaI6e0V5X5k" style=3D"color:#038aca" class=3D"appl-link">
=09=09=09=09=09=09=09=09=09<img class=3D"more" src=3D"http://a1.phobos.appl=
e.com/us/r30/Features49/v4/b3/97/ee/b397ee68-b6ab-2e61-ade5-220c30f633be/mz=
a_1941906498605355818.png" height=3D"18"  style=3D"margin:0; border:0" alt=
=3D"BBC Capital" border=3D"0" />
=09=09=09=09=09=09=09=09</a>
=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09</tr>
=09=09=09=09=09</table>
<!-- end table containing 1 story across / bordertop /  story 4-->

<!-- begin table containing 1 story across / bordertop /  story 5-->
=09=09=09=09=09<table width=3D"600" cellspacing=3D"0" cellpadding=3D"0" bor=
der=3D"0" style=3D"margin:0 auto; border-top:1px solid #e5e5e5" class=3D"">
=09=09=09=09=09=09<tr>
<!-- begin story 5 image -->
=09=09=09=09=09=09=09<td width=3D"190" valign=3D"top" align=3D"center" clas=
s=3D"appl_article_img" style=3D"padding-bottom:15px;padding-top:35px;">
=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3D=
us&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&c=
t=3DaI6e3d9y9h">
=09=09=09=09=09=09=09=09=09<img src=3D"http://a1.phobos.apple.com/us/r30/Fe=
atures71/v4/19/58/39/195839b7-e1b6-6b28-1b08-100a4f78a997/mza_7834153913340=
144423.jpg" width=3D"600" style=3D"display:block; margin:0; border:0" alt=
=3D"Lenny Letter Article Image" />
=09=09=09=09=09=09=09=09</a>
=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09</tr>
=09=09=09=09=09=09<tr>
<!-- begin story 5 headline and description -->
=09=09=09=09=09=09=09<td height=3D"104" valign=3D"top" align=3D"left" style=
=3D"" class=3D"appl_story_title">
=09=09=09=09=09=09=09=09<h3 style=3D"margin-top:0;margin-bottom:13px;">
=09=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=
=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGEx=
K&ct=3DaI4D0l9n4T" style=3D"font-family: -apple-system, helvetica Neue, Hel=
vetica, Lucida Grande, Arial,Verdana,sans-serif; font-weight:700; color:#00=
0000; font-size:24px; line-height:28px;letter-spacing:0; text-decoration:no=
ne">A Journey Through Cancer and Back</a>
=09=09=09=09=09=09=09=09</h3>
=09=09=09=09=09=09=09=09<p style=3D"margin-top:0; margin-bottom:6px;">
=09=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=
=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGEx=
K&ct=3DaI4g7d5d6Y"style=3D"font-family: -apple-system, helvetica Neue, Helv=
etica, Lucida Grande, Arial,Verdana,sans-serif; font-size:18px ; line-heigh=
t:26px;  font-weight:400; color:#808080; letter-spacing:.20px; text-decorat=
ion:none">When she was 25, <i>How I Met Your Mother</i> star Cobie Smulders=
 was treated for cancer. Now, she's opening up about the battle.</a>
=09=09=09=09=09=09=09=09</p>
=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09</tr>
=09=09=09=09=09=09<tr>
<!-- begin story 5 cta -->
=09=09=09=09=09=09=09<td align=3D"left" style=3D"padding-bottom:34px;">
=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3D=
us&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&c=
t=3DaI6j4E2J2C" style=3D"color:#038aca" class=3D"appl-link">
=09=09=09=09=09=09=09=09=09<img class=3D"more" src=3D"http://a1.phobos.appl=
e.com/us/r30/Features20/v4/90/05/f9/9005f9be-d6a4-9faa-2e7a-a534af22d970/mz=
a_3059129819754907147.png" height=3D"18"  style=3D"margin:0; border:0" alt=
=3D"Lenny Letter" border=3D"0" />
=09=09=09=09=09=09=09=09</a>
=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09</tr>
=09=09=09=09=09</table>
<!-- end table containing 1 story across / bordertop /  story 5-->


<!-- begin table containing 3 featured channels -->
=09=09=09=09=09<table width=3D"600" cellspacing=3D"0" cellpadding=3D"0" bor=
der=3D"0" align=3D"center" class=3D"">
=09=09=09=09=09=09<tr>
=09=09=09=09=09=09=09<td class=3D"appl_featured_channels"  valign=3D"top" a=
lign=3D"center" style=3D" padding-bottom:0px;border-top:1px solid #e5e5e5; =
border-bottom:0px solid #e5e5e5; ">
=09=09=09=09=09=09=09=09<table width=3D"600" cellspacing=3D"0" cellpadding=
=3D"0" border=3D"0" align=3D"center" class=3D"">
=09=09=09=09=09=09=09=09=09<tr>
=09=09=09=09=09=09=09=09=09=09<td valign=3D"top" align=3D"center" style=3D"=
font-family: -apple-system, helvetica Neue, Helvetica, Lucida Grande, Arial=
,Verdana,sans-serif; font-size:18px;font-weight:700;letter-spacing:3.5px;pa=
dding-top:25px;padding-bottom:25px;">
=09=09=09=09=09=09=09=09=09
=09=09=09=09=09=09=09=09=09FEATURED CHANNELS
=09=09=09=09=09=09=09=09=09=09
=09=09=09=09=09=09=09=09=09=09
=09=09=09=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09=09=09=09</tr>
=09=09=09=09=09=09=09=09</table>
=09=09=09=09=09=09=09=09
=09=09=09=09=09=09=09=09<table width=3D"600" cellspacing=3D"0" cellpadding=
=3D"0" border=3D"0" align=3D"center" class=3D"">
=09=09=09=09=09=09=09=09=09<tr>
=09=09=09=09=09=09=09=09=09=09<td valign=3D"top" align=3D"left" style=3D"">
=09=09=09=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=
=3Den&lc=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJ=
rdPrpGExK&ct=3DaI4W9L5q4k"><img src=3D"http://a1.phobos.apple.com/us/r30/Fe=
atures69/v4/af/52/84/af5284fd-58b4-c51e-a2da-ef02bc1621bb/mza_3537111386143=
048258.png" width=3D"194" style=3D"display:block; margin:0; border:0" alt=
=3D"The Economist" /></a>
=09=09=09=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09=09=09=09=09<td width=3D"9"> </td>
=09=09=09=09=09=09=09=09=09=09<td valign=3D"top" align=3D"left" style=3D"">
=09=09=09=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=
=3Den&lc=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJ=
rdPrpGExK&ct=3DaI6y3I4V3v"><img src=3D"http://a1.phobos.apple.com/us/r30/Fe=
atures71/v4/3d/b2/12/3db21292-7c15-1754-9625-9769ca399388/mza_5592130289466=
379239.png" width=3D"194" style=3D"display:block; margin:0; border:0" alt=
=3D"CNN" /></a>
=09=09=09=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09=09=09=09=09<td width=3D"9"> </td>
=09=09=09=09=09=09=09=09=09=09<td valign=3D"top" align=3D"left" style=3D"">
=09=09=09=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=
=3Den&lc=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJ=
rdPrpGExK&ct=3DaI6K0i0j4M"><img src=3D"http://a1.phobos.apple.com/us/r30/Fe=
atures69/v4/1a/ad/e5/1aade50a-9ff4-708c-e0ee-cf11f1ea600b/mza_8959272186593=
81649.png" width=3D"194" style=3D"display:block; margin:0; border:0" alt=3D=
"Science of Us" /></a>
=09=09=09=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09=09=09=09</tr>
=09=09=09=09=09=09=09=09</table>
=09=09=09=09=09=09=09=09=09
=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09</tr>
=09=09=09=09=09</table>
<!-- end table containing 3 featured channels -->
=09=09=09=09=09
<!-- begin Bottom red Blurb/CTA  -->
=09=09=09=09=09<table width=3D"600" cellspacing=3D"0" cellpadding=3D"0" bor=
der=3D"0" align=3D"center" class=3D"">
=09=09=09=09=09=09<tr>
=09=09=09=09=09=09=09<td class=3D"appl_featured_channels" valign=3D"bottom"=
 align=3D"center" style=3D"">
=09=09=09=09=09=09=09=09=09
=09=09=09=09=09=09=09=09<table width=3D"600" cellspacing=3D"0" cellpadding=
=3D"0" border=3D"0" align=3D"center" class=3D"">
=09=09=09=09=09=09=09=09=09<tr>
=09=09=09=09=09=09=09=09=09=09<td valign=3D"top" align=3D"center" style=3D"=
 padding-top:40px;padding-bottom:40px;">
=09=09=09=09=09=09=09=09=09
=09=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=
=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGEx=
K&ct=3DaI4y1x1k2C" style=3D"font-family: -apple-system, helvetica Neue, Hel=
vetica, Lucida Grande, Arial,Verdana,sans-serif; color:#333333;  font-size:=
20px; line-height:30px;letter-spacing:.25px;text-decoration:none">Like what=
 you're seeing here? Follow <b><font color=3D"#FF2D55">@AppleNews</font></b=
> on Twitter for our selections throughout the week.</a>
=09=09=09=09=09=09=09=09=09=09
=09=09=09=09=09=09=09=09=09=09
=09=09=09=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09=09=09=09</tr>
=09=09=09=09=09=09=09=09</table>
=09=09=09=09=09=09=09=09
=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09</tr>
=09=09=09=09=09</table>
<!-- end Bottom red Blurb/CTA  -->

<!-- Legal Footer -->

=09=09=09=09=09<table width=3D"100%" cellspacing=3D"0" cellpadding=3D"0" bo=
rder=3D"0" align=3D"center" style=3D"margin:0 auto;" class=3D"">
=09=09=09=09=09<tr>
=09=09=09=09=09<td align=3D"center" bgcolor=3D"#f2f2f2" style=3D"padding-to=
p:28px;padding-bottom:60px;">
=09=09=09=09=09=09<table width=3D"600" border=3D"0" cellspacing=3D"0" cellp=
adding=3D"0" align=3D"center" id=3D"appl-footer" class=3D"">
=09=09=09=09=09=09=09<tr>
=09=09=09=09=09=09=09=09<td align=3D"center" style=3D"padding-top:15px;padd=
ing-bottom:30px;" class=3D"appl_footer_text1 appl_footer_text appl_center">
=09=09=09=09=09=09=09=09=09<div style=3D"font-family: -apple-system, helvet=
ica Neue, Helvetica, Lucida Grande, Arial,Verdana,sans-serif;color:#797979;=
font-weight:400;font-size:14px;line-height:22px;">
=09=09=09=09=09=09=09=09=09Some content requires specific hardware or softw=
are. Internet access required; data fees may apply. Content availability is=
 subject to change. For more information, <a style=3D"color:#999999;text-de=
coration:underline;" href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=3Dus&a=
=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGExK&ct=3D=
aI6r0G4G4Y">click here</a>.

=09=09=09=09=09=09=09<br /><br />
=09=09=09=09=09=09=09Copyright &copy; 2016 Apple Inc. 1 Infinite Loop, Cupe=
rtino, CA 95014

=09=09</div>
=09=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09=09</tr>
=09=09=09=09=09=09=09
=09=09=09=09=09=09</table>
=09=09=09=09=09=09<table width=3D"100%" cellspacing=3D"0" cellpadding=3D"0"=
 border=3D"0" align=3D"center">
=09=09=09=09=09=09=09<tr>
=09=09=09=09=09=09=09=09<td align=3D"center" style=3D"font-family: -apple-s=
ystem, helvetica Neue, Helvetica, Lucida Grande, Arial,Verdana,sans-serif;c=
olor:#999999;font-size:14px;line-height:22px;padding-bottom:30px" class=3D"=
appl_lowbrow">
=09=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=
=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGEx=
K&ct=3DaI4A3E0T7M" class=3D"appl-link" style=3D"color:#797979; font-family:=
 helvetica Neue, Helvetica, Lucida Grande, Arial,Verdana,sans-serif;font-si=
ze:14px;line-height:22px;text-decoration:none">Privacy Policy</a>
=09=09=09=09=09=09=09=09=09&nbsp;&nbsp;|&nbsp;&nbsp;
=09=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=
=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGEx=
K&ct=3DaI6r0G4G4Y" class=3D"appl-link" style=3D"color:#797979; font-family:=
 helvetica Neue, Helvetica, Lucida Grande, Arial,Verdana,sans-serif;font-si=
ze:14px;line-height:22px;text-decoration:none">Terms and Conditions</a>
=09=09=09=09=09=09=09=09=09&nbsp;&nbsp;|&nbsp;&nbsp;
=09=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=
=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGEx=
K&ct=3DaI4D6d4N3h" class=3D"appl-link" style=3D"color:#797979; font-family:=
 helvetica Neue, Helvetica, Lucida Grande, Arial,Verdana,sans-serif;font-si=
ze:14px;line-height:22px;text-decoration:none">Support</a>
=09=09=09=09=09=09=09
=09=09=09=09=09=09=09=09=09&nbsp;&nbsp;|&nbsp;&nbsp;
=09=09=09=09=09=09=09=09=09<a href=3D"http://c.apple.com/r?v=3D2&la=3Den&lc=
=3Dus&a=3DQqYzAeniJNKxApET5a8csZLUpLnAgWqr7pZFGfWV2ClP83lJ5%2FnDirJrdPrpGEx=
K&ct=3DaI4A3E0x0k" class=3D"appl-link" style=3D"color:#797979;font-family: =
-apple-system, helvetica Neue, Helvetica, Lucida Grande, Arial,Verdana,sans=
-serif;font-size:14px;line-height:22px;text-decoration:none">Account</a>
=09=09=09=09=09=09=09=09
=09=09=09=09=09=09=09=09
=09=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09=09</tr>
=09=09=09=09=09=09</table>
=09=09=09=09=09=09<table width=3D"100%" cellspacing=3D"0" cellpadding=3D"0"=
 border=3D"0" align=3D"center">
=09=09=09=09=09=09=09<tr>
=09=09=09=09=09=09=09=09<td align=3D"center" style=3D"font-family:Helvetica=
 Neue,Helvetica,Lucida Grande,Arial,sans-serif;color:#999999;font-size:12px=
;line-height:1em;" class=3D"appl_lowbrow">

=09=09=09=09=09=09=09=09=09<a href=3D"http://mynews.apple.com/subscriptions=
?v=3D2&la=3Den_us&a=3D0uTcvmUjXMXJl8KqyvmiQl3BK3rnt2BA%2F2zG6jBTVj1jF%2B4%2=
FViF%2FFhLTV8w8tFGbFiOx4JghQA%2F8suznTk7thUSBXAehhq59%2B%2FGmmTzKFUQWbOK1Yp=
MPofvYthOHQIQvx5VXYBSHvNymANp7uB6W9Q%3D%3D" class=3D"appl-link" style=3D"co=
lor:#797979;font-family: helvetica Neue, Helvetica, Lucida Grande, Arial,Ve=
rdana,sans-serif;font-size:14px;line-height:22px;text-decoration:none">Unsu=
bscribe</a>
=09=09=09=09=09=09=09
=09=09=09=09=09=09=09=09</td>
=09=09=09=09=09=09=09</tr>
=09=09=09=09=09=09</table>
=09=09=09=09
=09=09=09=09
=09=09=09=09
=09=09=09=09=09</td>
=09=09=09=09</tr>

=09=09=09=09</table>

=09=09=09=09</td>
=09=09=09</tr>
=09=09=09</table>







=09=09

=09=09</td>
=09</tr>
=09</table>
=09<!--[if gte mso 9]>
</td></tr></table>
<![endif]-->
</div>
=09<!-- gmail ios fix -->
<div class=3D"appl_desktop" style=3D"white-space:nowrap!important; font:15p=
x courier; color:#000000; line-height:0px;">&nbsp; &nbsp; &nbsp; &nbsp; &nb=
sp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &=
nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </div>
<img src=3D"http://metrics.apple.com/b/ss/appleuscdmclickmap/1/H.4-pdv-2/14=
5229?[AQB]&amp;pageName=3DP0017042-350533&amp;r=3DD%3DReferer&amp;v1=3DD%3D=
User-Agent&amp;v9=3DD%3DpageName&amp;[AQE]" width=3D"1" height=3D"1" alt=3D=
""></body>
</html>

------=_Part_39677082_1968148227.1478954609343--

