From db02.7a011c0@vmail37.mnb.email Fri Nov 11 11:22:59 2016
Received: from vmail37.mnb.email ([67.23.183.180]:32107)
	by ecbiz209.inmotionhosting.com with esmtp (Exim 4.87)
	(envelope-from <db02.7a011c0@vmail37.mnb.email>)
	id 1c5EbT-003CFz-KL
	for kyle@kylefisher.com; Fri, 11 Nov 2016 11:22:59 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=simple/simple; d=mnb.email;
	s=dknewsletter; t=1478881376; bh=EmrDW3/U9NJo9qzkSOO9lGHcTgc=;
	h=Date:From:Reply-To:To:Subject:List-Unsubscribe;
	b=Q4JFy4vHaB7xKC+wd9KOJqSgyuHd75devwPTyXjjtPxy062B215sxC2dHaPz73O6t
	 Kel45dJKMI/SyeHeGh1gacKREykLUvmHFQYHu7OWNI0CY1fWm+KXqT+uAzoJYpvMnB
	 PhNVoMEi6LNNkcV5hTHGaS4AQ2HFXW9Tw9swnHc0=
Date: Fri, 11 Nov 2016 11:22:56 -0500
From: "VirDiKO Global Music Promotion!" <Info@VirDiKO.com>
Reply-To: "VirDiKO Global Music Promotion!" <Info@VirDiKO.com>
To:  <kyle@kylefisher.com>
Subject: =?UTF-8?Q?Eric_Ben=C3=A9t_-_=22INSANE=22_=5BNew_Album_Available_?=
	=?UTF-8?Q?=26_Online_Now=5D__=40VirDiKO_Global_Music_Promo?=
Message-ID: <db02.7a011c0.1dea5b0c@vmail37.mnb.email>
X-MNB-TRACKING: YWtuZTUwNCA6IGt5bGVAa3lsZWZpc2hlci5jb20gOiA1ODI1ZWY5MWIxMDlhMzhiNTYwMDFhOGQ=
X-MNB-SENDID: 5825ef91b109a38b56001a8d
List-Unsubscribe: <mailto:unsubscribe-1146643035-cc3c60209038962a7b319ce2cd4c07db@mynewsletterbuilder.com>
Feedback-ID: 2074796:270178:newsletter:massmail
Content-Type: multipart/alternative;
	boundary="=_5825f0601DEA5B0C7fa464040eb07FA4680C49907a011c0DB02"
MIME-Version: 1.0

This is a multi-part message in MIME format.
--=_5825f0601DEA5B0C7fa464040eb07FA4680C49907a011c0DB02
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline

VirDiKO.....Global Music Promotion To The World's Best DJ's & Entertainment=
 Professionals.
Exclusively for DJ's & Entertainment Industry Professionals!=20

Click the following link to Preview,  Leave Feedback and Download this proj=
ect: http://report.mynewsletterbuilder.com/t.js?s=3D5825ef91b109a38b56001a8=
d&u=3D37207074&v=3D3&key=3D0852&skey=3D03b869d39b&url=3Dhttp%3A%2F%2Fvirdik=
o.com%2Falbum%2Finsane

Artist: Eric Ben=C3=A9t=20
Song Title: INSANE=20
Available Versions: Explicit - Radio=20
BPM: 63 kpbs: 320 Genre: R&B=20
Album: Eric Benet in stores & online now!=20
=20
General Comments: Jordan House/Primary Wave/BMG delivers this Crazy R&B for=
 your female crowd titled "INSANE" Club & Radio versions included. DJ Feedb=
ack Requested and Always Appreciated.=20

=7FContact: Management=20
Label: Jordan House/Primary Wave/BMG=20
City: Milwaukee State: WI
=20
  http://report.mynewsletterbuilder.com/t.js?s=3D5825ef91b109a38b56001a8d&u=
=3D37207074&v=3D3&key=3D0852&skey=3D03b869d39b&url=3Dhttp%3A%2F%2Fvirdiko.c=
om%2Falbum%2Finsane
 http://report.mynewsletterbuilder.com/t.js?s=3D5825ef91b109a38b56001a8d&u=
=3D37207076&v=3D3&key=3D2e0f&skey=3D03b869d39b&url=3Dhttp%3A%2F%2Fericbenet=
.net
 http://report.mynewsletterbuilder.com/t.js?s=3D5825ef91b109a38b56001a8d&u=
=3D37207078&v=3D3&key=3D25e1&skey=3D03b869d39b&url=3Dhttp%3A%2F%2Finstagram=
.com%2Fericebenet
 http://report.mynewsletterbuilder.com/t.js?s=3D5825ef91b109a38b56001a8d&u=
=3D37207080&v=3D3&key=3D1c35&skey=3D03b869d39b&url=3Dhttp%3A%2F%2Ftwitter.c=
om%2Febenet
 http://report.mynewsletterbuilder.com/t.js?s=3D5825ef91b109a38b56001a8d&u=
=3D37207082&v=3D3&key=3D9aab&skey=3D03b869d39b&url=3Dhttp%3A%2F%2Ffacebook.=
com%2Fericbenetmusic

www.VirDiKO.com  =20

VirDiKO......The Professional Way To Get In & Out!!!!!

www.VirDiKO.com  Instagram: VirDiKO  Twitter: @VirDiKO      Facebook: VirDi=
KO     Skype: VirDiKO
Exclusively For Entertainment Professionals Promotion Utilization
VirDiKO Global Music Promotion....Serving The World's Best DJ's!
Virtual Distribution KOmpany (VirDiKO) - 1700 Commerce Street - Dallas - TX=
 - 75202

Subscribe to this newsletter:
https://www.mynewsletterbuilder.com/tools/subscription.php?username=3Dakne5=
04&send_id=3D5825ef91b109a38b56001a8d&l=3Ds&newsletter_id=3D1412779126
Unsubscribe kyle@kylefisher.com:
https://www.mynewsletterbuilder.com/tools/subscription.php?username=3Dakne5=
04&send_id=3D5825ef91b109a38b56001a8d&l=3Du&email=3Dkyle@kylefisher.com
Change your preferences:
https://www.mynewsletterbuilder.com/tools/subscription.php?username=3Dakne5=
04&send_id=3D5825ef91b109a38b56001a8d&l=3Dp&email=3Dkyle@kylefisher.com
Forward to a friend:
https://www.mynewsletterbuilder.com/tools/forward.php?username=3Dakne504&ne=
wsletter_id=3D1412779126&send_id=3D5825ef91b109a38b56001a8d
Report this email as spam:
https://www.mynewsletterbuilder.com/tools/abuse_report.php?username=3Dakne5=
04&send_id=3D5825ef91b109a38b56001a8d&email=3Dkyle@kylefisher.com

This email was sent using MyNewsletterBuilder.com.
--=_5825f0601DEA5B0C7fa464040eb07FA4680C49907a011c0DB02
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline

<table border=3D"7" width=3D"600" cellspacing=3D"0" cellpadding=3D"0" align=
=3D"center" bgcolor=3D"#FFFFFF">
<tbody>
<tr>
<td>
<table width=3D"600" cellspacing=3D"0" cellpadding=3D"5" align=3D"center">
<tbody>
<tr>
<td colspan=3D"2" align=3D"center"><a href=3D"http://report.mynewsletterbui=
lder.com/t.js?s=3D5825ef91b109a38b56001a8d&amp;u=3D37207040&amp;v=3D3&amp;k=
ey=3Dd254&amp;skey=3D03b869d39b&amp;url=3Dhttp%3A%2F%2Fwww.virdiko.com%2Fsh=
op"style=3D"display: block; text-align: center; color: navy; font-weight: b=
old; text-decoration: underline;" > <img src=3D"http://www.VirDiKO.com/imag=
es/VirDiKOTopBannerDEFAULT.jpg" border=3D"0" width=3D"600" height=3D"135" /=
><span style=3D"font-size: 12pt;"><font color=3D"Silver">VirDiKO Music Prom=
otion: Proudly Servicing The World's Best DJ's!</font> </span></a></td>
</tr>
<tr>
<td align=3D"center" valign=3D"top" width=3D"200">
<div p><a href=3D"http://report.mynewsletterbuilder.com/t.js?s=3D5825ef91b1=
09a38b56001a8d&amp;u=3D37207042&amp;v=3D3&amp;key=3D0852&amp;skey=3D03b869d=
39b&amp;url=3Dhttp%3A%2F%2Fvirdiko.com%2Falbum%2Finsane" target=3D"_blank">=
<img src=3D"http://virdiko.com/uploads/thumbs/200x200/uploads/artist/10/lib=
rary/9777/images/eric-bennet-insane-art-cvr2.jpg" border=3D"0" alt=3D"Click=
 to Preview and Download" /></a><br /> <a href=3D"http://report.mynewslette=
rbuilder.com/t.js?s=3D5825ef91b109a38b56001a8d&amp;u=3D37207044&amp;v=3D3&a=
mp;key=3D0852&amp;skey=3D03b869d39b&amp;url=3Dhttp%3A%2F%2Fvirdiko.com%2Fal=
bum%2Finsane" target=3D"_blank"><img src=3D"http://virdiko.com/tracks/10/27=
21_logo_jordan-house-records.jpg" border=3D"0" alt=3D"Click to Preview and =
Download" width=3D"59" height=3D"57" /></a><br /> <a href=3D"http://report.=
mynewsletterbuilder.com/t.js?s=3D5825ef91b109a38b56001a8d&amp;u=3D37207046&=
amp;v=3D3&amp;key=3D0852&amp;skey=3D03b869d39b&amp;url=3Dhttp%3A%2F%2Fvirdi=
ko.com%2Falbum%2Finsane" target=3D"_blank"><img src=3D"http://virdiko.com/i=
mages/PWMLogo.png" border=3D"0" alt=3D"Click to Preview and Download" width=
=3D"100" height=3D"50" /></a></div p>
<div p><a href=3D"http://report.mynewsletterbuilder.com/t.js?s=3D5825ef91b1=
09a38b56001a8d&amp;u=3D37207048&amp;v=3D3&amp;key=3D0852&amp;skey=3D03b869d=
39b&amp;url=3Dhttp%3A%2F%2Fvirdiko.com%2Falbum%2Finsane" target=3D"_blank">=
<img src=3D"http://virdiko.com/images/BMG.jpeg" border=3D"0" alt=3D"Click t=
o Preview and Download" width=3D"100" height=3D"50" /></a><br /> <a href=3D=
"http://report.mynewsletterbuilder.com/t.js?s=3D5825ef91b109a38b56001a8d&am=
p;u=3D37207042&amp;v=3D3&amp;key=3D0852&amp;skey=3D03b869d39b&amp;url=3Dhtt=
p%3A%2F%2Fvirdiko.com%2Falbum%2Finsane" target=3D"_blank"><img src=3D"http:=
//virdiko.com/uploads/thumbs/200x200/uploads/artist/10/library/9777/images/=
eric-bennet-insane-art-cvr2.jpg" border=3D"0" alt=3D"Click to Preview and D=
ownload" /></a></div p>
<div p><a href=3D"http://report.mynewsletterbuilder.com/t.js?s=3D5825ef91b1=
09a38b56001a8d&amp;u=3D37207044&amp;v=3D3&amp;key=3D0852&amp;skey=3D03b869d=
39b&amp;url=3Dhttp%3A%2F%2Fvirdiko.com%2Falbum%2Finsane" target=3D"_blank">=
<img src=3D"http://virdiko.com/tracks/10/2721_logo_jordan-house-records.jpg=
" border=3D"0" alt=3D"Click to Preview and Download" width=3D"59" height=3D=
"57" /></a><br /><a href=3D"http://report.mynewsletterbuilder.com/t.js?s=3D=
5825ef91b109a38b56001a8d&amp;u=3D37207046&amp;v=3D3&amp;key=3D0852&amp;skey=
=3D03b869d39b&amp;url=3Dhttp%3A%2F%2Fvirdiko.com%2Falbum%2Finsane" target=
=3D"_blank"><img src=3D"http://virdiko.com/images/PWMLogo.png" border=3D"0"=
 alt=3D"Click to Preview and Download" width=3D"100" height=3D"50" /></a></=
div p>
<div p><a href=3D"http://report.mynewsletterbuilder.com/t.js?s=3D5825ef91b1=
09a38b56001a8d&amp;u=3D37207048&amp;v=3D3&amp;key=3D0852&amp;skey=3D03b869d=
39b&amp;url=3Dhttp%3A%2F%2Fvirdiko.com%2Falbum%2Finsane" target=3D"_blank">=
<img src=3D"http://virdiko.com/images/BMG.jpeg" border=3D"0" alt=3D"Click t=
o Preview and Download" width=3D"100" height=3D"50" /></a></div p>
</td>
<td style=3D"padding-left: 20px;" valign=3D"top" width=3D"451">
<div><span style=3D"font-size: 12pt;"><span style=3D"font-size: 12pt;"> <sp=
an style=3D"font-family: Helvetica,serif; color: #0b3b17; font-weight: bold=
;">Artist:</span> <span style=3D"color: #000000;"><font face=3D"IMPACT" siz=
e=3D"8" color=3D"Black">Eric Ben&eacute;t</font></span> <br /> <span style=
=3D"font-family: Helvetica,serif; color: #0b3b17; font-weight: bold;">Song =
Title:</span> <span style=3D"color: #000000;"><font face=3D"IMPACT" size=3D=
"9" color=3D"Purple">INSANE</font></span> <br /> <span style=3D"font-family=
: Helvetica,serif; color: #0b3b17; font-weight: bold;">Available Versions:<=
/span> <span style=3D"color: #000000;">Explicit - Radio</span> <br /> <span=
 style=3D"font-family: Helvetica,serif; color: #0b3b17; font-weight: bold;"=
>BPM:</span> <span style=3D"color: #000000;">63</span> <span style=3D"font-=
family: Helvetica,serif; color: #0b3b17; font-weight: bold;">kpbs:</span> <=
span style=3D"color: #000000;">320<span style=3D"font-family: Helvetica,ser=
if; color: #0b3b17; font-weight: bold;"> Genre:</span> <span style=3D"color=
: #000000;">R&amp;B</span> <br /> <span style=3D"font-family: Helvetica,ser=
if; color: #0b3b17; font-weight: bold;">Album:</span> <span style=3D"color:=
 #0000ff;"><strong>Eric Benet in stores &amp; online now!</strong></span>&n=
bsp;<br /></span></span></span>
<div p>&nbsp;</div p>
</div>
<div style=3D"text-align: center;"><a href=3D"http://report.mynewsletterbui=
lder.com/t.js?s=3D5825ef91b109a38b56001a8d&amp;u=3D37207050&amp;v=3D3&amp;k=
ey=3D0852&amp;skey=3D03b869d39b&amp;url=3Dhttp%3A%2F%2Fvirdiko.com%2Falbum%=
2Finsane" target=3D"_blank"><img src=3D"http://www.virdiko.com/images/cdrfv=
flash2013.gif" border=3D"0" alt=3D"" width=3D"390" height=3D"100" /></a><br=
 />
<div p>&nbsp;</div p>
</div>
<div><span style=3D"font-size: 12pt;"><span style=3D"font-size: 12pt;"> <sp=
an style=3D"font-family: Helvetica,serif; color: #0b3b17; font-weight: bold=
;">General Comments:</span> <strong><span style=3D"color: #000000;">Jordan =
House/Primary Wave/BMG delivers this Crazy R&amp;B for your female crowd ti=
tled <span style=3D"color: #800080;">"INSANE"</span> Club &amp; Radio versi=
ons included. DJ Feedback Requested and Always Appreciated.</span> </strong=
><br /></span></span>
<div p><br />=7F<span style=3D"font-size: 12pt;"><span style=3D"font-family=
: Helvetica,serif; color: #0b3b17; font-weight: bold;">Contact:</span> <spa=
n style=3D"color: #000000;">Management</span> <br /> <span style=3D"font-si=
ze: 12pt;"><span style=3D"font-family: Helvetica,serif; color: #0b3b17; fon=
t-weight: bold;">Label:</span> <strong><span style=3D"color: #000000;">Jord=
an House/Primary Wave/BMG</span></strong> <span style=3D"font-size: 12pt;">=
<br /> <span style=3D"font-size: 12pt;"><span style=3D"font-family: Helveti=
ca,serif; color: #0b3b17; font-weight: bold;">City:</span> <span style=3D"c=
olor: #000000;">Milwaukee</span> <span style=3D"font-family: Helvetica,seri=
f; color: #0b3b17; font-weight: bold;">State:</span> <span style=3D"color: =
#000000;">WI</span><br /> </span></span></span></span></div p>
<div p>&nbsp;</div p>
</div>
<div p><span style=3D"font-size: 12pt;"> <img src=3D"http://virdiko.com/ima=
ges/VirDiKO_3D_2013Transparent.gif" border=3D"0" alt=3D"" width=3D"62" heig=
ht=3D"42" /> <span style=3D"font-family: 'Helvetica Neue', Helvetica, Arial=
, sans-serif; color: #000000;"><a href=3D"http://report.mynewsletterbuilder=
.com/t.js?s=3D5825ef91b109a38b56001a8d&amp;u=3D37207052&amp;v=3D3&amp;key=
=3D0852&amp;skey=3D03b869d39b&amp;url=3Dhttp%3A%2F%2Fvirdiko.com%2Falbum%2F=
insane" target=3D"_blank">http://virdiko.com/album/insane</a></span> <br />=
 <img src=3D"http://virdiko.com/images/wwwAniMate.png" border=3D"0" alt=3D"=
" width=3D"62" height=3D"42" /> <a href=3D"http://report.mynewsletterbuilde=
r.com/t.js?s=3D5825ef91b109a38b56001a8d&amp;u=3D37207054&amp;v=3D3&amp;key=
=3D2e0f&amp;skey=3D03b869d39b&amp;url=3Dhttp%3A%2F%2Fericbenet.net" target=
=3D"_blank">http://ericbenet.net</a>&nbsp;<br /> <img src=3D"http://virdiko=
.com/images/Instagram13.png" border=3D"0" alt=3D"" width=3D"62" height=3D"4=
2" /> <a href=3D"http://report.mynewsletterbuilder.com/t.js?s=3D5825ef91b10=
9a38b56001a8d&amp;u=3D37207056&amp;v=3D3&amp;key=3D25e1&amp;skey=3D03b869d3=
9b&amp;url=3Dhttp%3A%2F%2Finstagram.com%2Fericebenet" target=3D"_blank">htt=
p://instagram.com/ericebenet</a>&nbsp;<br /> <img src=3D"http://virdiko.com=
/images/Twitter13.png" border=3D"0" alt=3D"" width=3D"62" height=3D"42" /> =
<a href=3D"http://report.mynewsletterbuilder.com/t.js?s=3D5825ef91b109a38b5=
6001a8d&amp;u=3D37207058&amp;v=3D3&amp;key=3D1c35&amp;skey=3D03b869d39b&amp=
;url=3Dhttp%3A%2F%2Ftwitter.com%2Febenet" target=3D"_blank">http://twitter.=
com/ebenet</a>&nbsp;<br /> <img src=3D"http://virdiko.com/images/Facebook13=
.png" border=3D"0" alt=3D"" width=3D"62" height=3D"42" /> <a href=3D"http:/=
/report.mynewsletterbuilder.com/t.js?s=3D5825ef91b109a38b56001a8d&amp;u=3D3=
7207060&amp;v=3D3&amp;key=3D9aab&amp;skey=3D03b869d39b&amp;url=3Dhttp%3A%2F=
%2Ffacebook.com%2Fericbenetmusic" target=3D"_blank">http://facebook.com/eri=
cbenetmusic</a>&nbsp;<br /> </span></div p>
</td>
</tr>
<tr>
<td colspan=3D"2">
<table border=3D"2" width=3D"600">
<tbody>
<tr>
<td width=3D"150"><a href=3D"http://report.mynewsletterbuilder.com/t.js?s=
=3D5825ef91b109a38b56001a8d&amp;u=3D37207062&amp;v=3D3&amp;key=3D61ef&amp;s=
key=3D03b869d39b&amp;url=3Dhttp%3A%2F%2Fvirdiko.com%2Falbum%2Fbreak-you-off=
" target=3D"_blank"><img src=3D"http://virdiko.com/uploads/artist/10/librar=
y/9702/images/break-you-off-cover-art.jpg" border=3D"0" alt=3D"" width=3D"1=
12" height=3D"156" /></a></td>
<td width=3D"150">=7F <a href=3D"http://report.mynewsletterbuilder.com/t.js=
?s=3D5825ef91b109a38b56001a8d&amp;u=3D37207064&amp;v=3D3&amp;key=3D62a4&amp=
;skey=3D03b869d39b&amp;url=3Dhttp%3A%2F%2Fwww.virdiko.com%2Falbum%2Flil-rid=
a-bonus-track-coast-2-coast" target=3D"_blank"><img src=3D"http://virdiko.c=
om/uploads/artist/10/library/9678/images/mss.jpg" border=3D"0" alt=3D"" wid=
th=3D"112" height=3D"156" /></a></td>
<td width=3D"150">=7F <a href=3D"http://report.mynewsletterbuilder.com/t.js=
?s=3D5825ef91b109a38b56001a8d&amp;u=3D37207066&amp;v=3D3&amp;key=3Def49&amp=
;skey=3D03b869d39b&amp;url=3Dhttp%3A%2F%2FvirdikoGLOBALradio.com" target=3D=
"_blank"><img src=3D"http://virdiko.com/images/VirDiKO_GLOBAL_RADIOwhite.jp=
g" border=3D"0" alt=3D"" width=3D"112" height=3D"156" /></a></td>
<td width=3D"150"><a href=3D"http://report.mynewsletterbuilder.com/t.js?s=
=3D5825ef91b109a38b56001a8d&amp;u=3D37207068&amp;v=3D3&amp;key=3D44da&amp;s=
key=3D03b869d39b&amp;url=3Dhttp%3A%2F%2Fwww.virdiko.com%2Falbum%2Fballing-n=
ow" target=3D"_blank"><img src=3D"http://virdiko.com/uploads/artist/10/libr=
ary/9668/images/dakota-lee-ballin-now-artwork.jpg" border=3D"0" alt=3D"" wi=
dth=3D"112" height=3D"156" /></a></td>
<td width=3D"150"><a href=3D"http://report.mynewsletterbuilder.com/t.js?s=
=3D5825ef91b109a38b56001a8d&amp;u=3D37207070&amp;v=3D3&amp;key=3Dbbf8&amp;s=
key=3D03b869d39b&amp;url=3Dhttp%3A%2F%2Fwww.virdiko.com%2Falbum%2Fgood-life=
-with-u" target=3D"_blank"><img src=3D"http://virdiko.com/uploads/artist/48=
61/library/9649/images/anthony-tony-good-life-with-u.jpg" border=3D"0" alt=
=3D"" width=3D"112" height=3D"156" /></a></td>
</tr>
</tbody>
</table>
=7F
<div p style=3D"text-align: center;"><a href=3D"http://report.mynewsletterb=
uilder.com/t.js?s=3D5825ef91b109a38b56001a8d&amp;u=3D37207072&amp;v=3D3&amp=
;key=3Dac73&amp;skey=3D03b869d39b&amp;url=3Dhttp%3A%2F%2Fwww.VirDiKO.com%2F=
shop" target=3D"_blank"><img src=3D"http://www.virdiko.com/images/Virdiko_6=
00x135_HeadphoneBanner01.gif" border=3D"0" alt=3D"" width=3D"600" height=3D=
"135" /></a></div p>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table><table style=3D"border-spacing: 0; border-collapse: collapse; verti=
cal-align: top; text-align: left; width: 100%; background-color: #FFFFFF; c=
olor: #303030; font-family: 'Helvetica', 'Arial', sans-serif; font-weight: =
normal; line-height: 20px; font-size: 11px; margin: 0; padding: 0; table-la=
yout: fixed;" align=3D"center" bgcolor=3D"#FFFFFF" cellpadding=3D"0" cellsp=
acing=3D"0" border=3D"0">
    <tr align=3D"center" style=3D"vertical-align: top; text-align: center; =
padding: 0;">
		<td align=3D"left" valign=3D"top" style=3D"width: 15px; word-break: break=
-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-col=
lapse: collapse !important; vertical-align: top; text-align: left; font-fam=
ily: 'Helvetica', 'Arial', sans-serif; font-weight: normal; line-height: 20=
px; font-size: 11px; margin: 0; padding: 0;"><img src=3D"http://media.jbane=
twork.com/image/cache/1/0/8/6/2_w15_h15_s1.gif" alt=3D"Please enable images=
" border=3D"0" height=3D"15" style=3D"border: 0 none; display: block; heigh=
t: 15px; width: 15px;" width=3D"15" /></td>
        <td align=3D"center" valign=3D"top" style=3D"word-break: break-word=
; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-collapse=
: collapse !important; vertical-align: top; text-align: center; margin: 0; =
padding: 15px 0;">
            <center>
                <table style=3D"width: 100%; border-spacing: 0; border-coll=
apse: collapse; background-color: #FFFFFF; text-align: center;" align=3D"ce=
nter" bgcolor=3D"#FFFFFF" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
                    <tr style=3D"vertical-align: top; text-align: center; p=
adding: 0;" align=3D"center">
                        <td align=3D"center" valign=3D"top" style=3D"word-b=
reak: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto;=
 border-collapse: collapse !important; vertical-align: top; text-align: cen=
ter; color: #000000; font-family: 'Helvetica', 'Arial', sans-serif; font-we=
ight: normal; mso-line-height-rule: exactly; line-height: 20px; font-size: =
11px; margin: 0; padding: 0 0 10px;">
                        Virtual Distribution KOmpany (VirDiKO) &nbsp;&bull;=
&nbsp; 1700 Commerce Street &nbsp;&bull;&nbsp; Dallas &nbsp;&bull;&nbsp; TX=
 &nbsp;&bull;&nbsp; 75202<p style=3D"margin: 0; padding: 0; text-align: cen=
ter;"><a href=3D"http://www.VirDiKO.com" style=3D"color: #000000; text-deco=
ration: underline;">http://www.VirDiKO.com</a></p></td>
                    </tr>
                    <tr style=3D"vertical-align: top; text-align: center; p=
adding: 0;" align=3D"center">
                        <td align=3D"center" valign=3D"top" style=3D"word-b=
reak: break-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto;=
 border-collapse: collapse !important; vertical-align: top; text-align: cen=
ter; margin: 0; padding: 0;">
                          <table style=3D"border-spacing: 0; border-collaps=
e: collapse; background: #FFFFFF; padding: 0; margin-right:auto; margin-lef=
t:auto;" align=3D"center" bgcolor=3D"#FFFFFF" cellpadding=3D"0" cellspacing=
=3D"0" border=3D"0">
                            <tr style=3D"vertical-align: top; text-align: c=
enter; padding: 0;" align=3D"center">
                                <td align=3D"right" valign=3D"top" style=3D=
"width: 20px; text-align: right;"><img src=3D"http://www.mynewsletterbuilde=
r.com/images/templates/footers/mnb_blue_left.gif" alt=3D"Please enable imag=
es" height=3D"20" style=3D"border: 0 none; display: block; height: 20px; wi=
dth: 20px;" width=3D"20" /></td>
                                <td align=3D"center" valign=3D"middle" styl=
e=3D"background-color: #2C74B1; word-break: break-word; -webkit-hyphens: au=
to; -moz-hyphens: auto; hyphens: auto; border-collapse: collapse !important=
; vertical-align: top; text-align: center; margin: 0; padding: 0;" bgcolor=
=3D"#2C74B1">
                                  <table style=3D"border-spacing: 0; border=
-collapse: collapse; vertical-align: top; background: #2C74B1; padding: 0; =
margin-left:auto; margin-right:auto;" align=3D"center" bgcolor=3D"#2C74B1" =
cellpadding=3D"0" cellspacing=3D"0" border=3D"0">
                                    <tr style=3D"vertical-align: top; text-=
align: center; padding: 0;" align=3D"center">
                                        <td align=3D"center" style=3D"borde=
r-collapse: collapse !important; vertical-align: top; text-align: center; c=
olor: #DDDDDD; font-weight: bold; font-family: 'Helvetica', 'Arial', sans-s=
erif; mso-line-height-rule: exactly; line-height: 18px; font-size: 10px; ma=
rgin: 0; padding: 0;">&nbsp;&nbsp;<a href=3D"https://www.mynewsletterbuilde=
r.com/tools/subscription.php?username=3Dakne504&amp;send_id=3D5825ef91b109a=
38b56001a8d&amp;l=3Ds&amp;newsletter_id=3D1412779126" style=3D"color: #FFFF=
FF; text-decoration: none;">Subscribe</a> &nbsp;&bull;&nbsp; <a href=3D"htt=
ps://www.mynewsletterbuilder.com/tools/subscription.php?username=3Dakne504&=
amp;send_id=3D5825ef91b109a38b56001a8d&amp;l=3Dp&amp;email=3Dkyle@kylefishe=
r.com" style=3D"color: #FFFFFF; text-decoration: none;">Preferences</a> &nb=
sp;&bull;&nbsp; <a href=3D"https://www.mynewsletterbuilder.com/tools/forwar=
d.php?username=3Dakne504&amp;newsletter_id=3D1412779126&amp;send_id=3D5825e=
f91b109a38b56001a8d" style=3D"color: #FFFFFF; text-decoration: none;">Send =
to a Friend</a> &nbsp;&bull;&nbsp; <a href=3D"https://www.mynewsletterbuild=
er.com/tools/subscription.php?username=3Dakne504&amp;send_id=3D5825ef91b109=
a38b56001a8d&amp;l=3Du&amp;email=3Dkyle@kylefisher.com" style=3D"color: #FF=
FFFF; text-decoration: none;">Unsubscribe</a> &nbsp;&bull;&nbsp; <a href=3D=
"https://www.mynewsletterbuilder.com/tools/abuse_report.php?username=3Dakne=
504&amp;send_id=3D5825ef91b109a38b56001a8d&amp;email=3Dkyle@kylefisher.com"=
 style=3D"color: #FFFFFF; text-decoration: none;">Report Spam</a>&nbsp;&nbs=
p;</td>
                                    </tr>
                                </table>
                              </td>
                                <td align=3D"left" valign=3D"top" style=3D"=
width: 20px; text-align: left;"><img src=3D"http://www.mynewsletterbuilder.=
com/images/templates/footers/mnb_blue_right.gif" alt=3D"Please enable image=
s" height=3D"20" style=3D"border: 0 none; display: block; height: 20px; wid=
th: 20px;" width=3D"20" /></td>
                            </tr>
                        </table></td>
                    </tr>
                    <tr align=3D"center" style=3D"vertical-align: top; text=
-align: center; padding: 0;">
                        <td align=3D"center" valign=3D"top" style=3D"border=
-collapse: collapse !important; vertical-align: top; text-align: center; ma=
rgin: 0; padding: 10px 0 0;">
                            <table style=3D"border-spacing: 0; border-colla=
pse: collapse; background-color: #FFFFFF; text-align: center; margin-left:a=
uto; margin-right:auto;" align=3D"center" bgcolor=3D"#FFFFFF" cellpadding=
=3D"0" cellspacing=3D"0" border=3D"0">
                                <tr style=3D"vertical-align: top; text-alig=
n: center; padding: 0;" align=3D"center">
                                    <td align=3D"center" valign=3D"top" sty=
le=3D"border-collapse: collapse !important; vertical-align: top; text-align=
: center; color: #555555; font-family: 'Helvetica', 'Arial', sans-serif; fo=
nt-weight: normal; font-size: 11px; margin: 0; padding: 0;"><a href=3D"http=
://www.mynewsletterbuilder.com/"><img src=3D"http://media.jbanetwork.com/im=
age/cache/1/6/7/6/9/8/4.gif" alt=3D"Powered by MyNewsletterBuilder" border=
=3D"0" height=3D"32" style=3D"border: 0 none; display: block; height: 32px;=
 width: 168px;" title=3D"Powered by MyNewsletterBuilder" width=3D"168" /></=
a>
                                    <br /><img src=3D"https://report.mynews=
letterbuilder.com?send_id=3D5825ef91b109a38b56001a8d&amp;skey=3D03b869d39b"=
 alt=3D"Please enable images" height=3D"1" width=3D"1" border=3D"0" /></td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </center>
        </td>
		<td align=3D"right" valign=3D"top" style=3D"width: 15px; word-break: brea=
k-word; -webkit-hyphens: auto; -moz-hyphens: auto; hyphens: auto; border-co=
llapse: collapse !important; vertical-align: top; text-align: right; font-f=
amily: 'Helvetica', 'Arial', sans-serif; font-weight: normal; line-height: =
20px; font-size: 11px; margin: 0; padding: 0;"><img src=3D"http://media.jba=
network.com/image/cache/1/0/8/6/2_w15_h15_s1.gif" alt=3D"Please enable imag=
es" border=3D"0" height=3D"15" style=3D"border: 0 none; display: block; hei=
ght: 15px; width: 15px;" width=3D"15" /></td>
    </tr>
</table>
<div align=3D"center" style=3D"margin: 10px 0; font-size: 10px;">
		<a href=3D"https://www.facebook.com/dialog/feed?app_id=3D451888128178452&=
link=3Dhttps%3A%2F%2Fwww.mynewsletterbuilder.com%2Femail%2Fnewsletter%2F141=
2779126&redirect_uri=3Dhttps%3A%2F%2Fwww.mynewsletterbuilder.com%2Femail%2F=
newsletter%2F1412779126">
	<img src=3D"https://www.mynewsletterbuilder.com/images/share.png" alt=3D"S=
hare on Facebook" border=3D"0" />
	</a>
	<a href=3D"http://addthis.com/bookmark.php?v=3D250&amp;username=3Dxa-4c3d0=
31130dfb2e3&amp;url=3Dhttps%3A%2F%2Fwww.mynewsletterbuilder.com%2Femail%2Fn=
ewsletter%2F1412779126%2F&amp;title=3DEric+Ben%C3%A9t+-+%22INSANE%22+%5BNew=
+Album+Available+%26+Online+Now%5D++%40VirDiKO+Global+Music+Promo" title=3D=
"Bookmark and Share" target=3D"_blank">
	<img src=3D"https://s7.addthis.com/static/btn/v2/lg-share-en.gif" width=3D=
"125" height=3D"16" alt=3D"Bookmark and Share" style=3D"border:0"/></a>
	&nbsp;
</div>

--=_5825f0601DEA5B0C7fa464040eb07FA4680C49907a011c0DB02--

