From mailnull@amazon.com Sun Nov 13 05:58:00 2016
Received: from autoresponder.amazon.com ([205.251.233.36]:20771)
	by ecbiz209.inmotionhosting.com with esmtps (TLSv1:DHE-RSA-AES256-SHA:256)
	(Exim 4.87)
	(envelope-from <mailnull@amazon.com>)
	id 1c5sU4-001T0F-B1
	for kyle@kylefisher.com; Sun, 13 Nov 2016 05:58:00 -0500
Received: from email-autorespond-60001.pdx1.amazon.com (localhost.localdomain [127.0.0.1])
	by autoresponder.amazon.com (8.13.8/8.13.8) with ESMTP id uADAvx2P020744
	for <kyle@kylefisher.com>; Sun, 13 Nov 2016 10:57:59 GMT
Received: (from mailnull@localhost)
	by email-autorespond-60001.pdx1.amazon.com (8.13.8/8.13.8/Submit) id uADAvxw8020741;
	Sun, 13 Nov 2016 10:57:59 GMT
Date: Sun, 13 Nov 2016 10:57:59 GMT
Subject: Re: Your Amazon.com Order
In-Reply-To: <E1c5sT6-001SDd-Ol@ecbiz209.inmotionhosting.com>
Message-ID: <auto-reply-20652-1479034679@email-autorespond-60001.pdx1.amazon.com>
To: kyle@kylefisher.com
X-Amazon-Auto-Reply: true
From: ship-confirm@amazon.com

Greetings from Amazon.com. 

We're sorry. You replied to a confirmation-only address that cannot
accept incoming e-mail. But that's OK--this automated response will
direct you to the right place at Amazon.com to answer your question or
help you make changes to your order.

To track recent shipments, get updated delivery estimates, or make
changes to any unshipped orders, just log in to Your Account at:

http://www.amazon.com/wheres-my-stuff 

If you need to return an item from your order, visit our online
Returns Center at:

http://www.amazon.com/returns/ 

For answers to questions about our shipping rates, returns policy, and
how to use any of our services, visit:

http://www.amazon.com/help/ 

We hope our online resources meet all your needs. If you've explored
the above links but find you still need to get in touch with us,
please use the e-mail form in our online Help department. 

Thanks for shopping at Amazon.com.


Sincerely, 
Amazon.com Customer Service
http://www.amazon.com/

P.S. You received this message because Amazon.com received
the following message from you:

Date: Sun, 13 Nov 2016 05:57:00 -0500
From: kyle@kylefisher.com
To: ship-confirm@amazon.com
Subject: Your email requires verification verify#SJyS48rrGKR3lcMn4KS0x-1479034620)

The message you sent requires that you verify that you 
are a real live human being and not a spam source.


To complete this verification, simply reply to this message and leave
the subject line intact or click the link below:

http://www.kylefisher.com/cgi-sys/bxd.cgi?a=kyle@kylefisher.com&id=SJyS48rrGKR3lcMn4KS0x-1479034620

The headers of the message sent from your address are shown below:

From mailnull@amazon.com Sun Nov 13 05:57:00 2016
Received: from [72.21.217.134] (port=12352 helo=autoresponder.amazon.com)
	by ecbiz209.inmotionhosting.com with esmtps (TLSv1:DHE-RSA-AES256-SHA:256)
	(Exim 4.87)
	(envelope-from <mailnull@amazon.com>)
	id 1c5sT6-001SDR-Kg
	for kyle@kylefisher.com; Sun, 13 Nov 2016 05:57:00 -0500
Received: from email-autorespond-25001.iad12.amazon.com (localhost.localdomain [127.0.0.1])
	by autoresponder.amazon.com (8.13.8/8.13.8) with ESMTP id uADAv1gF031541
	for <kyle@kylefisher.com>; Sun, 13 Nov 2016 10:57:01 GMT
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=amazon.com;
	s=amazon201209; t=1479034621;
	bh=O7QLbwq3v9ixQECdVuz0KHLhJUQ0hUh0PsiWDkl1Wxw=;
	h=Date:Subject:In-Reply-To:To:From;
	b=Ke6e+rMrrvub9afoJDCXKPnu3s7dqSriP+wwdK0JiIrJKYMNrEDKLiCTNaR6uTGP/
	 QUgTcxZIJCiqmsN9RxvdbiS9XMXVU9iOwgN403JNIacj/RRmXjtUJE5nvp2RO2vX41
	 1C/ACHbJvet5GYGPkhDX8iSYLOjA2b3OEuV0Ono4=
Received: (from mailnull@localhost)
	by email-autorespond-25001.iad12.amazon.com (8.13.8/8.13.8/Submit) id uADAv1vF031539;
	Sun, 13 Nov 2016 10:57:01 GMT
Date: Sun, 13 Nov 2016 10:57:01 GMT
Subject: Re: Your Amazon.com Order
In-Reply-To: <E1c5sS6-001RNW-MB@ecbiz209.inmotionhosting.com>
Message-ID: <auto-reply-31506-1479034620@email-autorespond-25001.iad12.amazon.com>
To: kyle@kylefisher.com
X-Amazon-Auto-Reply: true
From: ship-confirm@amazon.com


