From ee08.82ef35c@vmail10.mnb.email Sat Nov 12 19:12:26 2016
Received: from vmail10.mnb.email ([66.219.28.188]:34174)
	by ecbiz209.inmotionhosting.com with esmtp (Exim 4.87)
	(envelope-from <ee08.82ef35c@vmail10.mnb.email>)
	id 1c5iPK-000HLS-Pr
	for kyle@kylefisher.com; Sat, 12 Nov 2016 19:12:26 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=simple/simple; d=mnb.email;
	s=dknewsletter; t=1478995945; bh=88I0ffUyRDfHvipK8ptpbIQDWMc=;
	h=Date:From:Reply-To:To:Subject:List-Unsubscribe;
	b=a85LQGkawAsuV7OCu3lrZrfdeYpHLZMlKHbWJByz2BzicQs5iP2cCMPgSS/+UYcXh
	 AKt4Hd9I/6LuSPSDSjW39UjcvhjKQ0P2uLcH/4Se5D4chEgvTK57R/ES/GmZS4rwZ3
	 lOar4uDsKcNVqU56j1kf84PaQAL8V3kIrNFtbKGU=
Date: Sat, 12 Nov 2016 19:12:25 -0500
From: "VirDiKO...#1 Trusted Music Source For Professional DJ's" <Info+VirDiKO.com@mnb.email>
Reply-To: "VirDiKO Global Music Promotion!" <Info@VirDiKO.com>
To:  <kyle@kylefisher.com>
Subject: Re: Do You Know These DJ's........Send Your Music!  @VirDiKO
Message-ID: <ee08.82ef35c.1d5457a8@vmail10.mnb.email>
X-MNB-TRACKING: YWtuZTUwNCA6IGt5bGVAa3lsZWZpc2hlci5jb20gOiA1ODI3YWY5MjQwMjIzODk1N2YwMDBjYTc=
X-MNB-SENDID: 5827af92402238957f000ca7
List-Unsubscribe: <mailto:unsubscribe-1146643035-cc3c60209038962a7b319ce2cd4c07db@mynewsletterbuilder.com>
Feedback-ID: 2075154:270178:newsletter:massmail
Content-Type: multipart/alternative;
	boundary="=_5827afe91D5457A87f4bbc0521307F4BAC03C91082ef35cEE08"
MIME-Version: 1.0

This is a multi-part message in MIME format.
--=_5827afe91D5457A87f4bbc0521307F4BAC03C91082ef35cEE08
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline

VirDiKO.....Global Music Promotion To The World's Best DJ's & Entertainment=
 Professionals.
Exclusively for DJ's & Entertainment Industry Professionals!=20

VirDiKO......The Professional Way To Get In & Out!!!!!

www.VirDiKO.com  Instagram: VirDiKO  Twitter: @VirDiKO      Facebook: VirDi=
KO     Skype: VirDiKO
Exclusively For Entertainment Professionals Promotion Utilization
VirDiKO Global Music Promotion....Serving The World's Best DJ's!
Virtual Distribution KOmpany (VirDiKO) - 1700 Commerce Street - Dallas - TX=
 - 75202

Subscribe to this newsletter:
https://www.mynewsletterbuilder.com/tools/subscription.php?username=3Dakne5=
04&send_id=3D5827af92402238957f000ca7&l=3Ds&newsletter_id=3D1412780756
Unsubscribe kyle@kylefisher.com:
https://www.mynewsletterbuilder.com/tools/subscription.php?username=3Dakne5=
04&send_id=3D5827af92402238957f000ca7&l=3Du&email=3Dkyle@kylefisher.com
Change your preferences:
https://www.mynewsletterbuilder.com/tools/subscription.php?username=3Dakne5=
04&send_id=3D5827af92402238957f000ca7&l=3Dp&email=3Dkyle@kylefisher.com
Forward to a friend:
https://www.mynewsletterbuilder.com/tools/forward.php?username=3Dakne504&ne=
wsletter_id=3D1412780756&send_id=3D5827af92402238957f000ca7
Report this email as spam:
https://www.mynewsletterbuilder.com/tools/abuse_report.php?username=3Dakne5=
04&send_id=3D5827af92402238957f000ca7&email=3Dkyle@kylefisher.com

This email was sent using MyNewsletterBuilder.com.
--=_5827afe91D5457A87f4bbc0521307F4BAC03C91082ef35cEE08
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline

<div p>&nbsp;</div p>
<table border=3D"7" width=3D"600" cellspacing=3D"0" cellpadding=3D"0" align=
=3D"center" bgcolor=3D"#ffffff">
<tbody>
<tr>
<td>
<table width=3D"600" cellspacing=3D"0" cellpadding=3D"5" align=3D"center">
<tbody>
<tr>
<td colspan=3D"2" align=3D"center">
<div p><a href=3D"http://report.mynewsletterbuilder.com/t.js?s=3D5827af9240=
2238957f000ca7&amp;u=3D37211500&amp;v=3D3&amp;key=3D4e6d&amp;skey=3D0d138a6=
1dd&amp;url=3Dhttp%3A%2F%2Fwww.virdiko.com"style=3D"display: block; text-al=
ign: center; color: navy; font-weight: bold; text-decoration: underline;"  =
target=3D"_blank"> <img src=3D"http://www.VirDiKO.com/images/VirDiKOTopBann=
erDEFAULT.jpg" border=3D"0" width=3D"600" height=3D"135" /></a></div p>
<div p>&nbsp;</div p>
<div p>&nbsp;</div p>
<div p><span style=3D"font-size: 24px;"><strong>Do You Know These Professio=
nal DJ's</strong></span></div p>
<div p><span style=3D"font-size: 24px;"><strong>......If Not...No Problem..=
WE DO @ VirDiKO</strong></span></div p>
<div p>&nbsp;</div p>
<div p><span style=3D"font-size: 24px;"><strong>Service Your Music To Profe=
ssional DJ's Around The World The Right Way!</strong></span></div p>
<div p><span style=3D"font-size: 18pt; color: #ff0000; font-family: impact,=
 chicago;"><strong>(click images below to Browse &amp; Meet All The DJ's)</=
strong></span></div p>
<div p><a href=3D"http://report.mynewsletterbuilder.com/t.js?s=3D5827af9240=
2238957f000ca7&amp;u=3D37211502&amp;v=3D3&amp;key=3Dc2c3&amp;skey=3D0d138a6=
1dd&amp;url=3Dhttp%3A%2F%2Fwww.virdiko.com%2Fevent%2Fvirdiko-music-dj-mixer=
"style=3D"display: block; text-align: center; color: navy; font-weight: bol=
d; text-decoration: underline;"  target=3D"_blank"><img src=3D"http://www.V=
irDiKO.com/images/DYKTDJ7.png" border=3D"0" width=3D"600" height=3D"135" />=
</a></div p>
<div p><span style=3D"font-size: 14pt; font-family: impact, chicago; color:=
 #ff0000;"><strong>(Here are just few of the DJ's We Are Proud to Service W=
ith Your New Music)</strong></span></div p>
<div p><a href=3D"http://report.mynewsletterbuilder.com/t.js?s=3D5827af9240=
2238957f000ca7&amp;u=3D37211504&amp;v=3D3&amp;key=3D79a9&amp;skey=3D0d138a6=
1dd&amp;url=3Dhttp%3A%2F%2Fwww.virdiko.com%2Fdjs" target=3D"_blank"><strong=
><span style=3D"font-size: 14pt;"><img src=3D"http://www.virdiko.com/images=
/DYKTDJ1.png" border=3D"0" width=3D"411" height=3D"1099" /></span></strong>=
</a></div p>
<div p><a href=3D"http://report.mynewsletterbuilder.com/t.js?s=3D5827af9240=
2238957f000ca7&amp;u=3D37211506&amp;v=3D3&amp;key=3D79a9&amp;skey=3D0d138a6=
1dd&amp;url=3Dhttp%3A%2F%2Fwww.virdiko.com%2Fdjs" target=3D"_blank"><strong=
><span style=3D"font-size: 14pt;"><strong><strong><span style=3D"font-size:=
 14pt;"><img src=3D"http://www.virdiko.com/images/DYKTDJ2.png" border=3D"0"=
 width=3D"411" height=3D"1099" /></span></strong></strong></span></strong><=
/a></div p>
<div p><a href=3D"http://report.mynewsletterbuilder.com/t.js?s=3D5827af9240=
2238957f000ca7&amp;u=3D37211508&amp;v=3D3&amp;key=3D79a9&amp;skey=3D0d138a6=
1dd&amp;url=3Dhttp%3A%2F%2Fwww.virdiko.com%2Fdjs" target=3D"_blank"><strong=
><span style=3D"font-size: 14pt;"><strong><strong><span style=3D"font-size:=
 14pt;"><img src=3D"http://www.virdiko.com/images/DYKTDJ3.png" border=3D"0"=
 width=3D"411" height=3D"1099" /></span></strong></strong></span></strong><=
/a></div p>
<div p><a href=3D"http://report.mynewsletterbuilder.com/t.js?s=3D5827af9240=
2238957f000ca7&amp;u=3D37211510&amp;v=3D3&amp;key=3D79a9&amp;skey=3D0d138a6=
1dd&amp;url=3Dhttp%3A%2F%2Fwww.virdiko.com%2Fdjs" target=3D"_blank"><strong=
><span style=3D"font-size: 14pt;"><strong><strong><span style=3D"font-size:=
 14pt;"><img src=3D"http://www.virdiko.com/images/DYKTDJ4.png" border=3D"0"=
 width=3D"411" height=3D"1099" /></span></strong></strong></span></strong><=
/a></div p>
<div p><a href=3D"http://report.mynewsletterbuilder.com/t.js?s=3D5827af9240=
2238957f000ca7&amp;u=3D37211512&amp;v=3D3&amp;key=3D79a9&amp;skey=3D0d138a6=
1dd&amp;url=3Dhttp%3A%2F%2Fwww.virdiko.com%2Fdjs" target=3D"_blank"><strong=
><span style=3D"font-size: 14pt;"><strong><strong><span style=3D"font-size:=
 14pt;"><img src=3D"http://www.virdiko.com/images/DYKTDJ5.png" border=3D"0"=
 width=3D"411" height=3D"1099" /></span></strong></strong></span></strong><=
/a></div p>
<div p><a href=3D"http://report.mynewsletterbuilder.com/t.js?s=3D5827af9240=
2238957f000ca7&amp;u=3D37211514&amp;v=3D3&amp;key=3D79a9&amp;skey=3D0d138a6=
1dd&amp;url=3Dhttp%3A%2F%2Fwww.virdiko.com%2Fdjs" target=3D"_blank"><strong=
><span style=3D"font-size: 14pt;"><strong><strong><span style=3D"font-size:=
 14pt;"><img src=3D"http://www.virdiko.com/images/DYKTDJ6.png" border=3D"0"=
 width=3D"411" height=3D"1099" /></span></strong></strong></span></strong><=
/a></div p>
<div p>&nbsp;</div p>
<div p>&nbsp;</div p>
<div p>&nbsp;</div p>
<div p><strong><span style=3D"font-size: 18pt;">#SALUTE THE DJ'S</span></st=
rong></div p>
<div p>&nbsp;</div p>
</td>
</tr>
<tr>
<td align=3D"center" valign=3D"top" width=3D"200">&nbsp;</td>
<td style=3D"padding-left: 20px;" valign=3D"top" width=3D"451">
<div p>&nbsp;</div p>
</td>
</tr>
<tr>
<td colspan=3D"2">
<table border=3D"2" width=3D"600">
<tbody>
<tr>
<td width=3D"150"><a href=3D"http://report.mynewsletterbuilder.com/t.js?s=
=3D5827af92402238957f000ca7&amp;u=3D37211516&amp;v=3D3&amp;key=3Dac73&amp;s=
key=3D0d138a61dd&amp;url=3Dhttp%3A%2F%2Fwww.VirDiKO.com%2Fshop" target=3D"_=
blank"><img src=3D"http://www.virdiko.com/uploads/ads/1405699351_VirDiKO-He=
adphones-Photo-1.gif" border=3D"0" alt=3D"" width=3D"112" height=3D"156" />=
</a></td>
<td width=3D"150"><a href=3D"http://report.mynewsletterbuilder.com/t.js?s=
=3D5827af92402238957f000ca7&amp;u=3D37211516&amp;v=3D3&amp;key=3Dac73&amp;s=
key=3D0d138a61dd&amp;url=3Dhttp%3A%2F%2Fwww.VirDiKO.com%2Fshop" target=3D"_=
blank"><img src=3D"http://www.virdiko.com/uploads/ads/1405699351_VirDiKO-He=
adphones-Photo-1.gif" border=3D"0" alt=3D"" width=3D"112" height=3D"156" />=
</a></td>
<td width=3D"150"><a href=3D"http://report.mynewsletterbuilder.com/t.js?s=
=3D5827af92402238957f000ca7&amp;u=3D37211516&amp;v=3D3&amp;key=3Dac73&amp;s=
key=3D0d138a61dd&amp;url=3Dhttp%3A%2F%2Fwww.VirDiKO.com%2Fshop" target=3D"_=
blank"><img src=3D"http://www.virdiko.com/uploads/ads/1405699351_VirDiKO-He=
adphones-Photo-1.gif" border=3D"0" alt=3D"" width=3D"112" height=3D"156" />=
</a></td>
<td width=3D"150"><a href=3D"http://report.mynewsletterbuilder.com/t.js?s=
=3D5827af92402238957f000ca7&amp;u=3D37211516&amp;v=3D3&amp;key=3Dac73&amp;s=
key=3D0d138a61dd&amp;url=3Dhttp%3A%2F%2Fwww.VirDiKO.com%2Fshop" target=3D"_=
blank"><img src=3D"http://www.virdiko.com/uploads/ads/1405699351_VirDiKO-He=
adphones-Photo-1.gif" border=3D"0" alt=3D"" width=3D"112" height=3D"156" />=
</a></td>
<td width=3D"150"><a href=3D"http://report.mynewsletterbuilder.com/t.js?s=
=3D5827af92402238957f000ca7&amp;u=3D37211516&amp;v=3D3&amp;key=3Dac73&amp;s=
key=3D0d138a61dd&amp;url=3Dhttp%3A%2F%2Fwww.VirDiKO.com%2Fshop" target=3D"_=
blank"><img src=3D"http://www.virdiko.com/uploads/ads/1405699351_VirDiKO-He=
adphones-Photo-1.gif" border=3D"0" alt=3D"" width=3D"112" height=3D"156" />=
</a></td>
</tr>
</tbody>
</table>
<div p style=3D"text-align: center;"><a href=3D"http://report.mynewsletterb=
uilder.com/t.js?s=3D5827af92402238957f000ca7&amp;u=3D37211518&amp;v=3D3&amp=
;key=3Dac73&amp;skey=3D0d138a61dd&amp;url=3Dhttp%3A%2F%2Fwww.VirDiKO.com%2F=
shop"style=3D"display: block; text-align: center; color: navy; font-weight:=
 bold; text-decoration: underline;"  target=3D"_blank"><img src=3D"http://w=
ww.VirDiKO.com/images/2016VirDiKOStoreBanner.gif" border=3D"0" width=3D"600=
" height=3D"135" /></a></div p>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table><table style=3D"width: 600px;" align=3D"center" cellpadding=3D"0" c=
ellspacing=3D"0" border=3D"0">
    <tr>
        <td style=3D"padding-top: 15px; padding-bottom: 15px;">
            <table style=3D"width: 600px;" align=3D"center" cellpadding=3D"=
0" cellspacing=3D"0" border=3D"0">
                <tr>
                    <td align=3D"center" style=3D"color: #333333; font-size=
: 10px; font-family: Verdana, Geneva, sans-serif; padding-bottom: 5px;">Vir=
tual Distribution KOmpany (VirDiKO) <span style=3D"font-size: 10px;">&nbsp;=
&bull;&nbsp;</span> 1700 Commerce Street <span style=3D"font-size: 10px;">&=
nbsp;&bull;&nbsp;</span> Dallas <span style=3D"font-size: 10px;">&nbsp;&bul=
l;&nbsp;</span> TX <span style=3D"font-size: 10px;">&nbsp;&bull;&nbsp;</spa=
n> 75202</td>
                </tr>
			                <tr>
                    <td align=3D"center" style=3D"color: #333333; font-size=
: 10px; font-family: Verdana, Geneva, sans-serif; padding-bottom: 10px;"><a=
 href=3D"http://www.VirDiKO.com" style=3D"color: #333333; text-decoration: =
underline;">http://www.VirDiKO.com</a></td>
                </tr>
                            <tr>
                    <td align=3D"center">
                        <table style=3D"width: 440px;" align=3D"center" cel=
lpadding=3D"0" cellspacing=3D"0" border=3D"0">
                            <tr>
                                <td style=3D"width: 20px;" align=3D"right" =
valign=3D"top"><img src=3D"http://www.mynewsletterbuilder.com/images/templa=
tes/footers/mnb_blue_left.gif" alt=3D"" /></td>
                                <td style=3D"width: 400px; background-color=
: #2C74B1;" bgcolor=3D"#2C74B1" align=3D"center" valign=3D"middle">
                                    <table style=3D"width: 100%;" cellpaddi=
ng=3D"0" cellspacing=3D"0" border=3D"0">
                                        <tr>
                                            <td align=3D"center" style=3D"c=
olor: #FFFFFF; font-weight: bold; font-size: 10px; font-family: Verdana, Ge=
neva, sans-serif; padding: 0 5px;"><a href=3D"https://www.mynewsletterbuild=
er.com/tools/subscription.php?username=3Dakne504&amp;send_id=3D5827af924022=
38957f000ca7&amp;l=3Ds&amp;newsletter_id=3D1412780756" style=3D"color: #FFF=
FFF; text-decoration: none;">Subscribe</a> <span style=3D"font-weight: norm=
al; font-size: 6px;">&nbsp;&nbsp;&bull;&nbsp;&nbsp;</span> <a href=3D"https=
://www.mynewsletterbuilder.com/tools/subscription.php?username=3Dakne504&am=
p;send_id=3D5827af92402238957f000ca7&amp;l=3Du&amp;email=3Dkyle@kylefisher.=
com" style=3D"color: #FFFFFF; text-decoration: none;">Unsubscribe</a> <span=
 style=3D"font-weight: normal; font-size: 6px;">&nbsp;&nbsp;&bull;&nbsp;&nb=
sp;</span> <a href=3D"https://www.mynewsletterbuilder.com/tools/subscriptio=
n.php?username=3Dakne504&amp;send_id=3D5827af92402238957f000ca7&amp;l=3Dp&a=
mp;email=3Dkyle@kylefisher.com" style=3D"color: #FFFFFF; text-decoration: n=
one;">Preferences</a> <span style=3D"font-weight: normal; font-size: 6px;">=
&nbsp;&nbsp;&bull;&nbsp;&nbsp;</span> <a href=3D"http://www.mynewsletterbui=
lder.com/tools/forward.php?username=3Dakne504&amp;newsletter_id=3D141278075=
6&amp;send_id=3D5827af92402238957f000ca7" style=3D"color: #FFFFFF; text-dec=
oration: none;">Send to a Friend</a></td>
                                        </tr>
                                    </table>
                                </td>
                                <td style=3D"width: 20px;" align=3D"left" v=
align=3D"top"><img src=3D"http://www.mynewsletterbuilder.com/images/templat=
es/footers/mnb_blue_right.gif" alt=3D"" /></td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td align=3D"center" style=3D"padding-top: 2px; padding=
-bottom: 2px;"><a href=3D"http://www.mynewsletterbuilder.com" target=3D"_bl=
ank"><img src=3D"https://www.mynewsletterbuilder.com/images/templates/foote=
rs/mnb_blue_powered_by.gif" alt=3D"Powered by MyNewsletterBuilder" border=
=3D"0" /></a></td>
                </tr>
                <tr>
                    <td align=3D"center" style=3D"color: #2C74B1; font-weig=
ht: bold; font-size: 10px; font-family: Verdana, Geneva, sans-serif;"><a hr=
ef=3D"https://www.mynewsletterbuilder.com/tools/abuse_report.php?username=
=3Dakne504&amp;send_id=3D5827af92402238957f000ca7&amp;email=3Dkyle@kylefish=
er.com" style=3D"color: #2C74B1; text-decoration: none;">Report Spam</a><br=
 /><img src=3D"https://report.mynewsletterbuilder.com/t.js?send_id=3D5827af=
92402238957f000ca7&amp;skey=3D0d138a61dd" alt=3D"" height=3D"1" width=3D"1"=
 border=3D"0" /></td>
                </tr>
            </table>
        </td>
    </tr>
</table><div align=3D"center" style=3D"margin: 10px 0; font-size: 10px;">
		<a href=3D"https://www.facebook.com/dialog/feed?app_id=3D451888128178452&=
link=3Dhttp://www.mynewsletterbuilder.com/email/newsletter/1412780756&redir=
ect_uri=3Dhttp://www.mynewsletterbuilder.com/email/newsletter/1412780756"><=
img src=3D"https://www.mynewsletterbuilder.com/images/share.png" alt=3D"Sha=
re on Facebook" border=3D"0" /></a>
	<a href=3D"http://addthis.com/bookmark.php?v=3D250&amp;username=3Dxa-4c3d0=
31130dfb2e3&amp;url=3Dhttp%3A%2F%2Fwww.mynewsletterbuilder.com%2Femail%2Fne=
wsletter%2F1412780756%2F&amp;title=3DRe%3A+Do+You+Know+These+DJ%27s........=
Send+Your+Music%21++%40VirDiKO" title=3D"Bookmark and Share" target=3D"_bla=
nk"><img src=3D"https://s7.addthis.com/static/btn/v2/lg-share-en.gif" width=
=3D"125" height=3D"16" alt=3D"Bookmark and Share" style=3D"border:0"/></a>
	&nbsp;
</div>

--=_5827afe91D5457A87f4bbc0521307F4BAC03C91082ef35cEE08--

