From bounce.80592.199946162@bounce.clk20.com Sat Nov 12 14:35:57 2016
Received: from mx5.e1.clk20.com ([68.170.151.48]:17797)
	by ecbiz209.inmotionhosting.com with esmtp (Exim 4.87)
	(envelope-from <bounce.80592.199946162@bounce.clk20.com>)
	id 1c5e5k-0045Cg-Te
	for kyle@kylefisher.com; Sat, 12 Nov 2016 14:35:56 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; s=PMTADKIM; d=e1.clk20.com;
 h=MIME-Version:Date:Message-ID:Content-Type:Reply-To:List-Unsubscribe:From:Subject:To; i=SeeMePDNMagazine@e1.clk20.com;
 bh=Xz2iiCBUV2Z1PkkXOqSeeOUM9ag=;
 b=Ilvi/pt4TS9FaHAAUjyWF+gjngK/430kMWuAKUEzjyLNcOIzTBaQ0+/CrpWFyBpxDOMvoMMTkG5v
   JqoSlXfLPGcZxkyT9i1UKaKJV3Ff8arbp9xBbJQ5LI0sNfDK8kwghVb+CZWkHXpJNXuykYwpD6OM
   oCJCr/NMnjFq4bHjZc0=
Received: from PMTAGEN (192.168.180.190) by mx5.e1.clk20.com id h4tnho20qpof for <kyle@kylefisher.com>; Sat, 12 Nov 2016 14:35:55 -0500 (envelope-from <bounce.80592.199946162@bounce.clk20.com>)
MIME-Version: 1.0
Date: Sat, 12 Nov 2016 14:30:05 -0500
Message-ID: <39CAAEC8DF3A9C4EA6B32AD5B057C994E483E49D@PMTAGEN>
Content-Type: multipart/alternative; boundary="------------020203050100010407010308"
X-Priority: 3 (Normal)
Reply-To: reply@clk20.com
x-cmp: 80592
x-inst: 134237
List-Unsubscribe: <mailto:abuse@e1.clk20.com>
From: "SeeMe | PDN Magazine" <SeeMePDNMagazine@e1.clk20.com>
Subject: Enter One Life before the final deadline on 12/15
x-rec: 199946162
To: kyle@kylefisher.com

--------------020203050100010407010308
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: quoted-printable

ONE LIFE WINNERS ALL HAVE ONE THING IN COMMON=E2=80=94THEY KNOW HOW TO CREA=
TE CAPTIVATING IMAGES.=0A=0AJoin the ranks of the these talented One Life w=
inners by showing us how you best capture people, places, things and ideas.=
 Enter at onelifeawards.com before the final deadline on 12/15.=0A=0ADana S=
alvo. Grand-prize winner. =0A=0ABeth Galton. Category winner: Things.=0A=0A=
Fabrice Fouillet. Category winner: Places.=0A=0ATomaso Baldessarini. Catego=
ry winner: People.=0A=0AFINAL DEADLINE:=0ADecember 15, 2016=0A=0ASUBMIT YOU=
R PHOTOS! - www.onelifeawards.com/?eb6a=0A=0ABROUGHT TO YOU BY: PHOTO+; PDN=
; SeeMe; Rangefinder Magazine=0A=0ASPONSORED BY: B&H; EyeEm =0A=0ALOVE PHOT=
OGRAPHY? Sign up for PDN's newsletter - http://r.clk20.com/s.ashx?ms=3Dclk2=
0com:80592_134237&e=3Dkyle@kylefisher.com&c=3Dt&url=3Dhttp://bit.ly/2cr43Ub=
=0A=0Awww.onelifeawards.com/?eb6a | info@pdncontests.com=0A=0A(c) 2016 Emer=
ald Expositions. All rights reserved.=0A100 Broadway - 14th floor=0ANew Yor=
k, NY 10005=0A=0A=0AThis email is being sent to kyle@kylefisher.com.=0AIf y=
ou no longer wish to receive Photo+ promotional emails, click on this link=
=0Ahttp://o.clk20.com/ro.aspx?e=3Dkyle@kylefisher.com&r=3D199946162&ms=3Dcl=
k20com:80592_134237&l=3Dgeneric=0A=0A
--------------020203050100010407010308
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<!doctype html>=0A<html lang=3D"en">
<!-- rpcampaign: clk20com : clk20com:80592_134237 -->
=0A<head>=0A<meta charset=3D"UTF-8">=0A<title>One Life International Photog=
raphy Competition</title>=0A<link href=3D"https://afeld.github.io/emoji-css=
/emoji.css" rel=3D"stylesheet">=0A<style type=3D"text/css"> =0A@import url(=
https://fonts.googleapis.com/css?family=3DSource+Sans+Pro:400,300,300italic=
,400italic,600,600italic,700,700italic);=0Abody {=0Amargin: 0;=0Acolor: #69=
655c;=0Afont-family: 'Open Sans', Arial, sans-serif;=0Afont-size: 16px;=0Af=
ont-weight: normal;=0Amargin: 0;=0Aline-height: 150%;=0Abackground-color: #=
ffffff;=0A=0A}=0Aa {=0Amargin: 0;=0Acolor: #69655c;=0Afont-family: 'Open Sa=
ns', Arial, sans-serif;=0Afont-size: 16px;=0Afont-weight: normal;=0Amargin:=
 0;=0Atext-decoration: underline;=0A}=0A=0Aimg {=0Adisplay: inline;=0Aborde=
r: 0;=0A}=0Ah1 {=0Acolor: #69655c;=0Afont-family: 'Open Sans', Arial, sans-=
serif;=0Afont-size: 40px;=0Afont-weight: bold;=0Amargin: 0;=0A}=0Ah2 {=0Aco=
lor: #696969;=0Afont-family: 'Open Sans', Arial, sans-serif;=0Afont-size: 2=
0px;=0Aline-height: 140%;=0Amargin-top: 0;=0Amargin-bottom: 0;=0A}=0Ap {=0A=
color: #363636;=0Afont-family: 'Open Sans', Arial, sans-serif;=0Afont-size:=
 100%;=0Aline-height: 150%;=0Amargin-bottom: 0;=0Amargin-top: 0;=0Afont-wei=
ght: normal;=0A}=0Ab {=0Acolor: #363636;=0Afont-family: 'Open Sans', Arial,=
 sans-serif;=0Afont-size: 100%;=0Aline-height: 150%;=0Amargin-bottom: 0;=0A=
margin-top: 0;=0Afont-weight: bold;=0A}=0A=0A.OneLifeLink {=0Acolor: #00000=
0;=0Afont-size: 14px;=0Afont-weight: bold;=0A}=0A.mainContent {=0Aborder-bo=
ttom: 10px solid #e64a33;=0Apadding: 20px;=0A}=0A=0A@media only screen and =
(max-width: 650px) {=0Atable[class=3D"wrapper"] {=0Amax-width: 650px !impor=
tant;=0Awidth: 100% !important;=0A}=0Atd[class=3D"deviceWidth"] {=0Adisplay=
: block !important;=0Apadding: 0 !important;=0Awidth: 100% !important;=0A}=
=0Atd[class=3D"row"] {=0Apadding: 15px 10px !important;=0A}=0A[class=3D"dev=
iceWidth"] p {=0Afont-size: 14px !important;=0A}=0Aa[class=3D"OneLifeLink" =
] {=0Afont-size: 100% !important;=0A}=0Aimg[class=3D"resImage"] {=0Aheight:=
 auto !important;=0Awidth: 100% !important;=0A}=0Aimg[class=3D"button"] {=
=0Aheight: auto !important;=0Awidth: 32% !important;=0A}=0Aimg[class=3D"but=
ton2"] {=0Aheight: auto !important;=0Awidth: 18% !important;=0A}=0A=0A[clas=
s=3D"wrapper"] h1 {=0Afont-size: 24px !important;=0A}=0A[class=3D"deviceWid=
th"] h2 {=0Amargin-top: 15px !important;=0A}=0A}=0A</style>=0A</head>=0A<bo=
dy>=0A<table class=3D"wrapper" align=3D"center" border=3D"0" cellpadding=3D=
"0" cellspacing=3D"0" width=3D"650" style=3D"color: #000000;font-family: 'O=
pen Sans', Arial, sans-serif; font-weight:normal; font-size: 14px;line-heig=
ht: 152%;padding-bottom: 0px;padding-top: 0px; padding-left: 0px; padding-r=
ight: 0px; ">=0A<tr>=0A<td class=3D"row" align=3D"left" width=3D"100%">=0A=
=0A<table class=3D"" align=3D"center" border=3D"0" cellpadding=3D"0" cellsp=
acing=3D"0" width=3D"100%" style=3D"color: #000000;font-family: 'Open Sans'=
, Arial, sans-serif; font-weight:normal; font-size: 14px;line-height: 152%;=
padding-bottom: 0px;padding-top: 0px; padding-left: 0px; padding-right:0px;=
">=0A<tr>=0A<td class=3D"deviceWidth" align=3D"left" width=3D"100%">=0A=0A<=
center>				=0A<p style=3D"color: #000000;font-family: 'Open Sans', Arial, s=
ans-serif; font-weight: normal; font-size: 12px;line-height: 142%;padding-b=
ottom: 0x;padding-top: 0; text-transform: uppercase;">One Life winners all =
have one thing in common&mdash;they know how to create captivating images.=
=0A<br>=0A=0A=0A=0A</p>=0A=0A=0A</center>=0A=0A=0A=0A<table class=3D"" alig=
n=3D"center" border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"100%=
" style=3D"color: #000000;font-family: 'Open Sans', Arial, sans-serif; font=
-weight:normal; font-size: 16px;line-height: 152%;padding-bottom: 0px;margi=
n-top: 9px; padding-left: 0px; padding-right: 0px; background-color: #fffff=
f; ">=0A<tr>=0A<td class=3D"deviceWidth" align=3D"center" width=3D"100%">=
=0A=0A<a class=3D"OneLifeLink"  href=3D"http://r.clk20.com/s.ashx?ms=3Dclk2=
0com:80592_134237&e=3Dkyle@kylefisher.com&c=3Dh&url=3Dhttps%3a%2f%2fwww.one=
lifeawards.com%2f%3feb6a" target=3D"_blank" style=3D"font-size: 16px; color=
: #3ab8e6;  font-weight: bold;text-decoration: underline;font-family: 'Open=
 Sans', Arial, sans-serif;line-height: 150%; padding-bottom: 0px; padding-t=
op: 0;">	=0A=0A<img class=3D"resImage" src=3D"https://www.onelifeawards.com=
/promo/eimages/onelife_eblast6b.png" alt=3D"One Life:  Final Deadline: Dece=
mber 15, 2016" style=3D"max-width: 650px; padding-bottom: 0px; background-c=
olor: #ffffff;border: none;padding-bottom: 0px;display: block;">=0A</a>=0A<=
br>=0A</td>=0A</tr>=0A</table>=0A=0A=0A=0A=0A<table class=3D"" align=3D"cen=
ter" border=3D"0" cellpadding=3D"0" cellspacing=3D"0" width=3D"100%" style=
=3D"color: #000000;font-family: 'Open Sans', Arial, sans-serif; font-weight=
:normal; font-size: 16px;line-height: 152%;padding-bottom: 0px;padding-top:=
 0px; background-color: #ffffff; ">=0A<tr>=0A<td class=3D"deviceWidth" alig=
n=3D"center" width=3D"80%" style=3D"padding-left: 6%; padding-right: 6%;">=
=0A=0A<p style=3D"color: #000000;font-family: 'Open Sans', Arial, sans-seri=
f;font-size: 112%;line-height: 158%;padding-bottom: 6px; padding-top: 6px; =
font-weight: normal; ">=0A	=0AJoin the ranks of the these talented One Life=
 winners by showing us how you best capture people, places, things and idea=
s. Enter at <a class=3D"OneLifeLink"  href=3D"http://r.clk20.com/s.ashx?ms=
=3Dclk20com:80592_134237&e=3Dkyle@kylefisher.com&c=3Dh&url=3Dhttps%3a%2f%2f=
www.onelifeawards.com%2f%3feb6a" target=3D"_blank" style=3D"font-size: 16px=
; color: #3ab8e6;  font-weight: bold;text-decoration: underline;font-family=
: 'Open Sans', Arial, sans-serif;line-height: 150%; padding-bottom: 0px; pa=
dding-top: 0;">onelifeawards.com</a> before the <span style=3D"background-c=
olor: yellow;">final deadline on 12/15</span>.=0A	=0A</p>=0A											=0A	=
																	<br>	=0A																		<br>																												=
												=0A																		<img class=3D"resImage" src=3D"https://www=
=2Eonelifeawards.com//promo/eimages/1_Salvo_Pilar.jpg" width=3D"100%" alt=
=3D"Photo by Dana Salvo" style=3D"padding-bottom: 9px; background-color: #f=
fffff;border: none; display: block;">	=0A																		<p style=3D"colo=
r: #000000;font-family: 'Open Sans', Arial, sans-serif; font-weight:normal;=
 font-size: 14px;line-height: 158%;padding-bottom: 0px;padding-top: 0px;  "=
>=0A																		=0A																		<span style=3D"text-transform: u=
ppercase; font-weight: bold; font-size: 110%;">Dana Salvo</span><br>=0A				=
														<span style=3D"font-weight: normal; text-transform: uppercase=
;">Grand-prize winner</span><br>=0A																	=0A																		<b=
r>					=0A																		</p>		=0A																		<br>=0A													=
					<br>=0A																		=0A																		=0A																		<im=
g class=3D"resImage" src=3D"https://www.onelifeawards.com/promo/eimages/2_B=
eth_Galton.jpg" width=3D"100%" alt=3D"Photo by Beth Galton" style=3D"paddin=
g-bottom: 9px; background-color: #ffffff;border: none; display: block;">	=
=0A																		<p style=3D"color: #000000;font-family: 'Open Sans', A=
rial, sans-serif; font-weight:normal; font-size: 14px;line-height: 158%;pad=
ding-bottom: 0px;padding-top: 0px;  ">=0A																		=0A													=
					<span style=3D"text-transform: uppercase; font-weight: bold; font-size=
: 110%;">Beth Galton</span><br>=0A																		<span style=3D"font-wei=
ght: normal; text-transform: uppercase;"> Category winner: Things</span><br=
>=0A																	=0A																		<br>					=0A																		</p=
>		=0A																		<br>=0A																		<br>=0A																	=
=0A																			<img class=3D"resImage" src=3D"https://www.onelifeawa=
rds.com/promo/eimages/3_Fabrice_Fouillet.jpg" width=3D"100%" alt=3D"Photo b=
y FabriceFouillet" style=3D"padding-bottom: 9px; background-color: #ffffff;=
border: none; display: block;">	=0A																		<p style=3D"color: #00=
0000;font-family: 'Open Sans', Arial, sans-serif; font-weight:normal; font-=
size: 14px;line-height: 158%;padding-bottom: 0px;padding-top: 0px;  ">=0A		=
																=0A																		<span style=3D"text-transform: upperca=
se; font-weight: bold; font-size: 110%;">Fabrice Fouillet</span><br>=0A				=
														<span style=3D"font-weight: normal; text-transform: uppercase=
;">Category winner: Places</span><br>=0A																	=0A															=
			<br>					=0A																		</p>		=0A																		<br>=0A								=
										<br>=0A																		=0A																						<img class=3D"r=
esImage" src=3D"https://www.onelifeawards.com/promo/eimages/4_Tomaso_Baldes=
sarini.jpg" width=3D"100%" alt=3D"Photo by Tomaso Baldessarin" style=3D"pad=
ding-bottom: 9px; background-color: #ffffff;border: none; display: block;">=
	=0A																		<p style=3D"color: #000000;font-family: 'Open Sans', =
Arial, sans-serif; font-weight:normal; font-size: 14px;line-height: 158%;pa=
dding-bottom: 0px;padding-top: 0px;  ">=0A																		=0A												=
						<span style=3D"text-transform: uppercase; font-weight: bold; font-siz=
e: 110%;">Tomaso Baldessarini</span><br>=0A																		<span style=3D=
"font-weight: normal; text-transform: uppercase;">Category winner: People</=
span><br>=0A																	=0A																		<br>					=0A													=
					</p>		=0A																		<br>=0A																		<br>=0A											=
							=0A=0A=0A=0A<table class=3D"" align=3D"center" border=3D"0" cellpadd=
ing=3D"0" cellspacing=3D"0"  style=3D"color: #000000;font-family: 'Open San=
s', Arial, sans-serif; font-weight:normal; font-size: 16px;line-height: 152=
%;padding-bottom: 0px;padding-top: 0px; background-color: #ffffff; ">=0A<tr=
>=0A<td class=3D"deviceWidth" valign=3D"top" align=3D"center" style=3D"padd=
ing:12px 44px; border: 2px #3ab8e6 solid; border-radius: 9px;">=0A=0A<a cla=
ss=3D"OneLifeLink"  href=3D"http://r.clk20.com/s.ashx?ms=3Dclk20com:80592_1=
34237&e=3Dkyle@kylefisher.com&c=3Dh&url=3Dhttps%3a%2f%2fwww.onelifeawards.c=
om%2f%3feb6a" target=3D"_blank" style=3D"color:  #3ab8e6; font-family: 'Ope=
n Sans', Arial, sans-serif;font-size: 110%;line-height: 150%;padding-bottom=
: 0px; padding-top: 0px; font-weight: normal; text-decoration: none;">	=0A<=
p style=3D"color:  #3ab8e6; font-family: 'Open Sans', Arial, sans-serif;fon=
t-size: 112%;line-height: 150%;padding-bottom: 0px; padding-top: 0px; font-=
weight: normal; ">=0ASUBMIT YOUR PHOTOS!=0A</p>=0A</a>=0A</td>=0A</tr>=0A</=
table>=0A<br>=0A<br>=0A=0A<table class=3D"" align=3D"center" border=3D"0" c=
ellpadding=3D"0" cellspacing=3D"0"  width=3D"100%" style=3D"color: #000000;=
font-family: 'Open Sans', Arial, sans-serif; font-weight:normal; font-size:=
 16px;line-height: 152%;padding-bottom: 0px;padding-top: 0px; background-co=
lor: #ffffff; ">=0A<tr>=0A<td class=3D"resImage" valign=3D"top" align=3D"ce=
nter">=0A<span style=3D"font-size: 55%;">=0ABROUGHT TO YOU BY:&nbsp;&nbsp;&=
nbsp;&nbsp;&nbsp;&nbsp;</span>=0A=0A<a class=3D"OneLifeLink"  href=3D"http:=
//r.clk20.com/s.ashx?ms=3Dclk20com:80592_134237&e=3Dkyle@kylefisher.com&c=
=3Dh&url=3Dhttp%3a%2f%2fwww.photoplusgroup.com%2f" target=3D"_blank" height=
=3D"40"  style=3D"color:  #3ab8e6; font-family: 'Open Sans', Arial, sans-se=
rif;font-size: 110%;line-height: 150%;padding-bottom: 0px; padding-top: 0px=
; font-weight: normal; text-decoration: none;">    =0A=0A<img class=3D"" sr=
c=3D"https://www.exposureaward.com/promo/eimages/logo_photoplus_newx2.gif" =
alt=3D"PHOTO+ logo" height=3D"40"  style=3D"vertical-align: middle; padding=
-bottom: 0px; background-color: #ffffff;border: none;padding-bottom: 0px;di=
splay: inline;"></a>=0A<a class=3D"OneLifeLink"  href=3D"http://r.clk20.com=
/s.ashx?ms=3Dclk20com:80592_134237&e=3Dkyle@kylefisher.com&c=3Dh&url=3Dhttp=
%3a%2f%2fwww.pdnonline.com" target=3D"_blank" style=3D"color:  #3ab8e6; fon=
t-family: 'Open Sans', Arial, sans-serif;font-size: 110%;line-height: 150%;=
padding-bottom: 0px; padding-top: 0px; font-weight: normal; text-decoration=
: none;">    =0A=0A<img class=3D"" src=3D"https://www.exposureaward.com/pro=
mo/eimages/logo_pdn_newx2.gif" alt=3D"PDN logo" height=3D"40"    style=3D"v=
ertical-align: middle; padding-bottom: 0px; background-color: #ffffff;borde=
r: none;padding-bottom: 0px;display: inline;"></a>                         =
                                           <a class=3D"OneLifeLink"  href=
=3D"http://r.clk20.com/s.ashx?ms=3Dclk20com:80592_134237&e=3Dkyle@kylefishe=
r.com&c=3Dh&url=3Dhttp%3a%2f%2fwww.see.me%2f" target=3D"_blank" style=3D"co=
lor:  #3ab8e6; font-family: 'Open Sans', Arial, sans-serif;font-size: 110%;=
line-height: 150%;padding-bottom: 0px; padding-top: 0px; font-weight: norma=
l; text-decoration: none;">    =0A=0A<img class=3D"" src=3D"https://www.exp=
osureaward.com/promo/eimages/logo_seeme_newx2.gif" alt=3D"SeeMe logo" heigh=
t=3D"40"  style=3D"vertical-align: middle; padding-bottom: 0px; background-=
color: #ffffff;border: none;padding-bottom: 0px;display: inline;"></a>=0A<a=
 class=3D"OneLifeLink"  href=3D"http://r.clk20.com/s.ashx?ms=3Dclk20com:805=
92_134237&e=3Dkyle@kylefisher.com&c=3Dh&url=3Dhttp%3a%2f%2fwww.rangefindero=
nline.com" target=3D"_blank" style=3D"color:  #3ab8e6; font-family: 'Open S=
ans', Arial, sans-serif;font-size: 110%;line-height: 150%;padding-bottom: 0=
px; padding-top: 0px; font-weight: normal; text-decoration: none;">    =0A=
=0A<img class=3D"" src=3D"https://www.exposureaward.com/promo/eimages/logo_=
rangefinder_newx2.gif" alt=3D"Rangefinder Magazine logo" height=3D"40"  sty=
le=3D"vertical-align: middle; padding-bottom: 0px; background-color: #fffff=
f;border: none;padding-bottom: 0px;display: inline;"></a><br>=0A<br>=0A<spa=
n style=3D"font-size: 55%;">=0ASPONSORED BY:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&=
nbsp;</span>=0A<a class=3D"OneLifeLink"  href=3D"http://r.clk20.com/s.ashx?=
ms=3Dclk20com:80592_134237&e=3Dkyle@kylefisher.com&c=3Dh&url=3Dhttp%3a%2f%2=
fwww.bandh.com" target=3D"_blank" style=3D"color:  #3ab8e6; font-family: 'O=
pen Sans', Arial, sans-serif;font-size: 110%;line-height: 150%;padding-bott=
om: 0px; padding-top: 0px; font-weight: normal; text-decoration: none;">   =
 =0A=0A<img class=3D"" src=3D"https://www.exposureaward.com/promo/eimages/l=
ogo_bandhx2.png" alt=3D"B&H logo" height=3D"40"   style=3D"vertical-align: =
middle; padding-bottom: 0px; background-color: #ffffff;border: none;padding=
-bottom: 0px;display: inline;"></a>=0A<a class=3D"OneLifeLink"  href=3D"htt=
p://r.clk20.com/s.ashx?ms=3Dclk20com:80592_134237&e=3Dkyle@kylefisher.com&c=
=3Dh&url=3Dhttps%3a%2f%2fwww.eyeem.com%2f" target=3D"_blank" style=3D"color=
:  #3ab8e6; font-family: 'Open Sans', Arial, sans-serif;font-size: 110%;lin=
e-height: 150%;padding-bottom: 0px; padding-top: 0px; font-weight: normal; =
text-decoration: none;">    =0A<img class=3D"" src=3D"https://www.exposurea=
ward.com/promo/eimages/spacer32x36.png" alt=3D"spacer" height=3D"36"   styl=
e=3D"vertical-align: middle; padding-bottom: 0px; background-color: #ffffff=
;border: none;padding-bottom: 0px;display: inline;">=0A<img class=3D"" src=
=3D"https://www.exposureaward.com/promo/eimages/logo_EyeEm2.png" alt=3D"Eye=
Em logo" height=3D"108"   style=3D"vertical-align: middle; padding-bottom: =
0px; background-color: #ffffff;border: none;padding-bottom: 0px;display: in=
line;"></a>=0A<br>=0A=0A</td>=0A</tr>=0A</table>=0A=0A=0A<br>=0A<center>=0A=
<p style=3D"color: #000000;font-family: 'Open Sans', Arial, sans-serif;font=
-size: 90%;line-height: 120%;padding-bottom: 6px; padding-top: 0; font-weig=
ht: normal;">=0A<i class=3D"em em-heart"></i>&nbsp;PHOTOGRAPHY? Sign up for=
  <a class=3D"OneLifeLink"  href=3D"http://r.clk20.com/s.ashx?ms=3Dclk20com=
:80592_134237&e=3Dkyle@kylefisher.com&c=3Dh&url=3Dhttp%3a%2f%2fwww.pages04.=
net%2fnielsenphotodistrictnews%2fnewsletters%2fpreferences%3fspMailingID%3d=
50940518%26spUserID%3dMTUzMTM4OTcxNDYyS0%26spJobID%3dODgyMTc2MzA0S0%26spRep=
ortId%3dODgyMTc2MzA0S0+)" target=3D"_blank" style=3D"font-size: 100%; color=
: #3ab8e6;  font-weight: normal;text-decoration: underline;font-family: 'Op=
en Sans', Arial, sans-serif;line-height: 150%; padding-bottom: 0px; padding=
-top: 0;">	=0A<i>PDN</i>'s newsletter</a>.<br>=0A<a class=3D"OneLifeLink"  =
href=3D"http://r.clk20.com/s.ashx?ms=3Dclk20com:80592_134237&e=3Dkyle@kylef=
isher.com&c=3Dh&url=3Dhttps%3a%2f%2fwww.onelifeawards.com%2f%3feb6a" target=
=3D"_blank" style=3D"font-size: 100%; color: #3ab8e6;  font-weight: normal;=
text-decoration: underline;font-family: 'Open Sans', Arial, sans-serif;line=
-height: 150%; padding-bottom: 0px; padding-top: 0;">www.onelifeawards.com<=
/a>&nbsp;&nbsp;|&nbsp;&nbsp;<a class=3D"OneLifeLink"  href=3D"mailto:info@p=
dncontests.com?Subject=3D2016 One Life" target=3D"_blank" style=3D"font-siz=
e: 100%; color: #3ab8e6;  font-weight: normal;text-decoration: underline;fo=
nt-family: 'Open Sans', Arial, sans-serif;line-height: 150%; padding-bottom=
: 0px; padding-top: 0;">	=0Ainfo@pdncontests.com </a></p> =0A=0A=0A<p style=
=3D"color: #000000;font-family: 'Open Sans', Arial, sans-serif;font-size: 9=
0%;line-height: 120%;padding-bottom: 6px; padding-top: 0; font-weight: norm=
al;">=0A&copy; 2016 <a class=3D"OneLifeLink"  href=3D"http://r.clk20.com/s.=
ashx?ms=3Dclk20com:80592_134237&e=3Dkyle@kylefisher.com&c=3Dh&url=3Dhttp%3a=
%2f%2femeraldexpositions.com%2fabout-us%2f" style=3D"font-size: 100%;color:=
 #000000; font-weight: normal;text-decoration: underline;font-family: 'Open=
 Sans', Arial, sans-serif;line-height: 150%;padding-bottom: 6px; padding-to=
p: 0;" >Emerald    Expositions</a>. All rights reserved.<br>=0A100 Broadway=
 - 14th floor<br>=0ANew York, NY  10005<br>=0A</p>=0A=0A</center>=0A=0A</td=
>=0A</tr>=0A</table>=0A</td>=0A</tr>=0A</table>=0A=0A<!-- Begin TemplateTyp=
e:Footer ; org:EXI1 -->=0A<table width=3D"100%" border=3D"0" cellspacing=3D=
"0" cellpadding=3D"0" align=3D"center" >=0A  <tr>=0A    <td align=3D"center=
"><p style=3D"line-height: 1.4; font-family:Arial, Helvetica, sans-serif; f=
ont-size:13px;">=0A<br /><br />=0AThis email is being sent to kyle@kylefish=
er.com. <br /><br />=0A=0AIf you no longer wish to receive Photo+ promotion=
al emails,<br> <a href=3D"http://o.clk20.com/o.aspx?e=3Dkyle@kylefisher.com=
&r=3D199946162&ms=3Dclk20com:80592_134237" style=3D"font-family: Arial, Hel=
vetica, Sans-Serif; font-size:12px;color:#353636;">click on this link.</a>=
=0A<br />=0A</td>=0A  </tr>=0A</table>=0A<!-- END TemplateType:Footer  -->	=
<!-- END TemplateType:Footer  -->=0A<img height=3D'1' width=3D'1' src=3D'ht=
tp://r.clk20.com/i.ashx?ms=3Dclk20com:80592_134237&amp;e=3Dkyle@kylefisher.=
com'>
</body>=0A</html>=0A=0A=0A=0A
--------------020203050100010407010308--


