From bounce-md_30022418.58272f2e.v1-39818ce95c3d48c0a5fcff3886c25209@mandrillapp.com Sat Nov 12 10:03:11 2016
Received: from mail136-16.atl41.mandrillapp.com ([198.2.136.16]:39476)
	by ecbiz209.inmotionhosting.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <bounce-md_30022418.58272f2e.v1-39818ce95c3d48c0a5fcff3886c25209@mandrillapp.com>)
	id 1c5Zpm-0043Wt-WD
	for kyle@kylefisher.com; Sat, 12 Nov 2016 10:03:11 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; s=mandrill; d=culinaryagents.com;
 h=From:Subject:To:Message-Id:Date:MIME-Version:Content-Type; i=no-reply@culinaryagents.com;
 bh=wnNOFFYsFD0E7zsvT90Eb74IEgY=;
 b=Wl1dIE6hiNEYjulT4IfbZDIgkKCKF0j7ZOM9h9W5hBljkfTJm7k4i4sI/z8OmGPPInKFiwiZZkFp
   RRW1bexvZ4yzkBLdmsG1avQUaeau7WZ59hRR3j7QQMbGF+35CcZ+AJt8pWMqzfHuvm/Ed1KmmGMh
   /XFofLYbamn2L1zDVi4=
Received: from pmta04.mandrill.prod.atl01.rsglab.com (127.0.0.1) by mail136-16.atl41.mandrillapp.com id h4sniu1sb1kh for <kyle@kylefisher.com>; Sat, 12 Nov 2016 15:03:10 +0000 (envelope-from <bounce-md_30022418.58272f2e.v1-39818ce95c3d48c0a5fcff3886c25209@mandrillapp.com>)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=mandrillapp.com; 
 i=@mandrillapp.com; q=dns/txt; s=mandrill; t=1478962990; h=From : 
 Subject : To : Message-Id : Date : MIME-Version : Content-Type : From : 
 Subject : Date : X-Mandrill-User : List-Unsubscribe; 
 bh=C5Yr2VBbZux/i/1fnXWYKZmQL5iRPGJfz18LdjRq1ao=; 
 b=SblBMlpoS3s2eUoxLMjrroWa6v28n/F84UXSlspis73kYAB60+/82QDKy8x9V4/Q+dIUxA
 fLC8fcRkszMXkNKafPfThmJohq3oOsdjv0+Fud/aQGhgNi0uKJKi6LkSgdVLyhgMg/k9pbZj
 s4+UISGGvOOZ0Y2eIUIIueXjoCbY8=
From: Culinary Agents <no-reply@culinaryagents.com>
Subject: New Job Matches!
Received: from [54.144.61.50] by mandrillapp.com id 39818ce95c3d48c0a5fcff3886c25209; Sat, 12 Nov 2016 15:03:10 +0000
To: Kyle <kyle@kylefisher.com>
X-Report-Abuse: Please forward a copy of this message, including all headers, to abuse@mandrill.com
X-Report-Abuse: You can also report abuse here: http://mandrillapp.com/contact/abuse?id=30022418.39818ce95c3d48c0a5fcff3886c25209
X-Mandrill-User: md_30022418
Message-Id: <30022418.20161112150310.58272f2e544f03.26738892@mail136-16.atl41.mandrillapp.com>
Date: Sat, 12 Nov 2016 15:03:10 +0000
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="_av-STm0Nxl3tHHYtsYgnsFQzw"

--_av-STm0Nxl3tHHYtsYgnsFQzw
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

 <https://culinaryagents.com>        Hi Kyle Fisher,     Based on your
current professional experience, here are your daily job matches.          
 New matched jobs on November 11                        Server      Naoki
Sushi | Lettuce Entertain You Restaurants      2300 N Lincoln Park W,
Chicago, IL 60614      POSTED ON NOVEMBER 11
<https://culinaryagents.com/jobs/44033-server>                    Server   
  The Blanchard      1935 North Lincoln Park West, Chicago, IL      POSTED
ON NOVEMBER 11 <https://culinaryagents.com/jobs/44041-server>         All
Matched Jobs <https://culinaryagents.com/jobs/matched>         Job Matching
Settings <https://culinaryagents.com/settings?view=3Djobs>         Email
Notification Settings
<https://culinaryagents.com/settings?view=3Dnotifications>             Find
thousands of opportunities on our job board.        See All Jobs
<https://culinaryagents.com/search/jobs>              Copyright =C2=A9 2016
Culinary Agents, All rights reserved. 
 You are receiving this email because with your Culinary Agents' profile,
you opt in to be part of our national job matching pool, and you subscribe
to the daily match emails.     Unsubscribe
<https://culinaryagents.com/settings?view=3Dnotifications>

--_av-STm0Nxl3tHHYtsYgnsFQzw
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 7bit

<!DOCTYPE html>
 <head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta content="telephone=no" name="format-detection">
     <style type="text/css">
        .appleLink a { color:#999999 !important; text-decoration: none !important; }
     </style>
</head>
<body style="margin: 0; padding:0;">
<table cellspacing="0" cellpadding="0" style="width: 100%;">
    <tr>
        <td>
            <center>
            <table cellspacing="0" cellpadding="0" style="text-align: left; width: 430px; margin: auto;">
                
                <tr>
                    <td style="background-color: #00BA57; padding-bottom: 15px; padding-top: 15px; padding-left: 10px;">
                        <a target="_blank" href="http://mandrillapp.com/track/click/30022418/culinaryagents.com?p=eyJzIjoiaEVHcHp5czdxdWw4LWQ1b19WU0xQUVFCSkpBIiwidiI6MSwicCI6IntcInVcIjozMDAyMjQxOCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2N1bGluYXJ5YWdlbnRzLmNvbVwiLFwiaWRcIjpcIjM5ODE4Y2U5NWMzZDQ4YzBhNWZjZmYzODg2YzI1MjA5XCIsXCJ1cmxfaWRzXCI6W1wiNWRlNzFiZTdhM2MwMGNmMDJjYWNiOTQ3Y2M4MjFmNzIwZTc0Mzc1YlwiXX0ifQ"><span><img alt="Culinary Agents" style="height: 30px; width: 179px; font-family: Helvetica; font-size: 20px; color: #FFFFFF; " src="https://s3.amazonaws.com/cuag/email/CulinaryAgetns_logo_30_r%402x.jpg"></img></span></a>
                    </td>
                </tr>
                
                

                <tr>
                    <td>
                        <table cellspacing="0" cellpadding="0">
                            <tr>
                                <td style="padding-left: 10px; padding-top: 36px;">
                                    <span style="font-family:Helvetica; font-size: 14px; color: #999999; line-height: 18px;">Hi Kyle Fisher,</span>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding-left: 10px; padding-top: 18px; padding-bottom:18px;">
                                    <span style="font-family:Helvetica; font-size: 14px; color: #999999; line-height: 18px;">Based on your current professional experience, here are your daily job matches.</span>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td>
                        <table cellspacing="0" cellpadding="0">
                            <tr>
                                <td style="padding-left: 10px; padding-bottom: 12px;">
                                    
                                    <span style="font-family: Helvetica-Bold; font-size: 14px; color: #333333;">
                                        New matched jobs on <span id="date">November 11</span>
                                    </span>
                                    
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                
                <tr>
                    <td>
                        <a href="http://mandrillapp.com/track/click/30022418/culinaryagents.com?p=eyJzIjoidFZYbUxMUTcyeE9zb2p5YklTVUF1a0R0QmFFIiwidiI6MSwicCI6IntcInVcIjozMDAyMjQxOCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2N1bGluYXJ5YWdlbnRzLmNvbVxcXC9qb2JzXFxcLzQ0MDMzLXNlcnZlclwiLFwiaWRcIjpcIjM5ODE4Y2U5NWMzZDQ4YzBhNWZjZmYzODg2YzI1MjA5XCIsXCJ1cmxfaWRzXCI6W1wiZTRjOGM4YThjNDA3NTk0OGI3ZmU2ZGQ5YmVmZjkxM2ExN2FhYjk2MlwiXX0ifQ" target="_blank" style="text-decoration: none;">
                        <table cellspacing="0" cellpadding="0" style="width: 100%; border-top: 1px solid #D9D9D9; border-bottom: 1px solid #D9D9D9;">
                            <tr>
                                <td style="padding-top: 18px; padding-bottom: 18px; padding-left: 10px;">
                                    <table border="0" cellspacing="0" cellpadding="0" style="table-layout: fixed;">
                                        <tr>
                                            <td valign="top" style="height: 70px; width: 70px;">
                                                <span>
                                                
                                                    <img src="https://s3.amazonaws.com/cuag/entities/000/047/252/avatar180-690564cdbfcc9df5c053a601610f29dc-0-3-442-311.jpg" style="height: 70px; width: 70px;"></img>
                                                
                                                </span>
                                            </td>
                                            <td valign="top">
                                                <table border="0" cellspacing="0" cellpadding="0">
                                                    <tr>
                                                        <td style="padding-left: 10px; padding-top: 2px;">
                                                        <span style="font-family: Helvetica-Bold; color: #00BA57; font-size: 14px;">Server</span>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td style="padding-left: 10px; padding-top: 5px;">
                                                        <span style="font-family: Helvetica; font-size: 14px; color: #333333;">
                                                        
                                                            Naoki Sushi
                                                            
                                                            <span style="color: #999999;">| Lettuce Entertain You Restaurants</span></span>
                                                            
                                                         
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td style="padding-left: 10px; padding-top: 5px; ">
                                                            <span style="font-family: Helvetica; font-size: 14px; color: #999999;">
                                                            
                                                                2300 N Lincoln Park W, Chicago, IL 60614
                                                            
                                                            </span>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td style=" -webkit-text-size-adjust: none; padding-left: 10px; padding-top: 8px; ">
                                                        <span style="font-family: Helvetica; font-size: 11px; color: #999999; -webkit-text-size-adjust: none;"><span class="appleLink">POSTED ON NOVEMBER 11</span></span>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                        </a>
                    </td>
                </tr>
                
                <tr>
                    <td>
                        <a href="http://mandrillapp.com/track/click/30022418/culinaryagents.com?p=eyJzIjoiWHdtRDZmY29keEJfMWp0S3pXSzIyWHFuaWtZIiwidiI6MSwicCI6IntcInVcIjozMDAyMjQxOCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2N1bGluYXJ5YWdlbnRzLmNvbVxcXC9qb2JzXFxcLzQ0MDQxLXNlcnZlclwiLFwiaWRcIjpcIjM5ODE4Y2U5NWMzZDQ4YzBhNWZjZmYzODg2YzI1MjA5XCIsXCJ1cmxfaWRzXCI6W1wiZTRjOGM4YThjNDA3NTk0OGI3ZmU2ZGQ5YmVmZjkxM2ExN2FhYjk2MlwiXX0ifQ" target="_blank" style="text-decoration: none;">
                        <table cellspacing="0" cellpadding="0" style="width: 100%; border-top: 1px solid #D9D9D9; border-bottom: 1px solid #D9D9D9;">
                            <tr>
                                <td style="padding-top: 18px; padding-bottom: 18px; padding-left: 10px;">
                                    <table border="0" cellspacing="0" cellpadding="0" style="table-layout: fixed;">
                                        <tr>
                                            <td valign="top" style="height: 70px; width: 70px;">
                                                <span>
                                                
                                                    <img src="https://s3.amazonaws.com/cuag/entities/000/058/727/avatar180-aaa8dbc218ee344ec7e231eda775db32-2-0-747-342.jpg" style="height: 70px; width: 70px;"></img>
                                                
                                                </span>
                                            </td>
                                            <td valign="top">
                                                <table border="0" cellspacing="0" cellpadding="0">
                                                    <tr>
                                                        <td style="padding-left: 10px; padding-top: 2px;">
                                                        <span style="font-family: Helvetica-Bold; color: #00BA57; font-size: 14px;">Server</span>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td style="padding-left: 10px; padding-top: 5px;">
                                                        <span style="font-family: Helvetica; font-size: 14px; color: #333333;">
                                                        
                                                            The Blanchard 
                                                            
                                                         
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td style="padding-left: 10px; padding-top: 5px; ">
                                                            <span style="font-family: Helvetica; font-size: 14px; color: #999999;">
                                                            
                                                                1935 North Lincoln Park West, Chicago, IL
                                                            
                                                            </span>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td style=" -webkit-text-size-adjust: none; padding-left: 10px; padding-top: 8px; ">
                                                        <span style="font-family: Helvetica; font-size: 11px; color: #999999; -webkit-text-size-adjust: none;"><span class="appleLink">POSTED ON NOVEMBER 11</span></span>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                        </a>
                    </td>
                </tr>
                

                <tr>
                    <td>
                        <a href="http://mandrillapp.com/track/click/30022418/culinaryagents.com?p=eyJzIjoiZzg4ajVWVl84aFhfblFNVEEzMkIxT1pBUDNvIiwidiI6MSwicCI6IntcInVcIjozMDAyMjQxOCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2N1bGluYXJ5YWdlbnRzLmNvbVxcXC9qb2JzXFxcL21hdGNoZWRcIixcImlkXCI6XCIzOTgxOGNlOTVjM2Q0OGMwYTVmY2ZmMzg4NmMyNTIwOVwiLFwidXJsX2lkc1wiOltcImU0YzhjOGE4YzQwNzU5NDhiN2ZlNmRkOWJlZmY5MTNhMTdhYWI5NjJcIl19In0" target="_blank" style="text-decoration: none;">
                        <table cellpadding="0" cellspacing="0" style="width: 430px; border-bottom: 1px solid #D9D9D9;">
                            <tr>
                                <td style="padding-top: 12px; padding-bottom: 15px; padding-left: 10px; width: 430px;">

                                <span style="font-family: Helvetica; font-size: 14px; border-bottom: 1px solid #333333; color: #333333;">All Matched Jobs</span>

                                </td>
                            </tr>
                        </table>
                        </a>
                    </td>
                </tr>
                <tr>
                    <td>
                        <a href="http://mandrillapp.com/track/click/30022418/culinaryagents.com?p=eyJzIjoiT2JKWkticHJkVGxGRmVremt1bDhRckFsUTZrIiwidiI6MSwicCI6IntcInVcIjozMDAyMjQxOCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2N1bGluYXJ5YWdlbnRzLmNvbVxcXC9zZXR0aW5ncz92aWV3PWpvYnNcIixcImlkXCI6XCIzOTgxOGNlOTVjM2Q0OGMwYTVmY2ZmMzg4NmMyNTIwOVwiLFwidXJsX2lkc1wiOltcIjEwM2ZjNjgxZTk5NjcxY2I2MDY5NDgxZmY4MDAyYTRiZGIwNGFmYjdcIl19In0" target="_blank" style="text-decoration: none;">
                        <table cellpadding="0" cellspacing="0" style="width: 100%; border-bottom: 1px solid #D9D9D9;">
                            <tr>
                                <td style="padding-top: 12px; padding-bottom: 15px; padding-left: 10px;">
                                    <span style="font-family: Helvetica; font-size: 14px; border-bottom: 1px solid #333333; color: #333333;">Job Matching Settings</span>
                                </td>
                            </tr>
                        </table>
                        </a>
                    </td>
                </tr>
                <tr>
                    <td>
                       <a href="http://mandrillapp.com/track/click/30022418/culinaryagents.com?p=eyJzIjoiMHpkcEp5Y2RjTlo5VTFwdG95Rm9PVVR1cDBzIiwidiI6MSwicCI6IntcInVcIjozMDAyMjQxOCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2N1bGluYXJ5YWdlbnRzLmNvbVxcXC9zZXR0aW5ncz92aWV3PW5vdGlmaWNhdGlvbnNcIixcImlkXCI6XCIzOTgxOGNlOTVjM2Q0OGMwYTVmY2ZmMzg4NmMyNTIwOVwiLFwidXJsX2lkc1wiOltcIjEwM2ZjNjgxZTk5NjcxY2I2MDY5NDgxZmY4MDAyYTRiZGIwNGFmYjdcIl19In0" target="_blank" style="text-decoration: none;">
                        <table cellpadding="0" cellspacing="0" style="width: 100%; ">
                            <tr>
                                <td style="padding-top: 12px; padding-bottom: 15px; padding-left: 10px; width: 430px;">
                                    <span style="font-family: Helvetica; font-size: 14px; border-bottom: 1px solid #333333; color: #333333;">Email Notification Settings</span>
                                </td>
                            </tr>
                        </table>
                        </a>

                        <table cellpadding="0" cellspacing="0">
                            <tr>
                                <td style="padding-top: 21px;"></td>
                            </tr>
                        </table>

                    </td>
                </tr>
                <tr>
                    <td style="background-color: #F0F0F0; padding-bottom: 24px;">
                        <table cellpadding="0" cellspacing="0" style="width: 100%">
                            <tr>
                                <td style="padding-top: 24px; padding-bottom: 12px; text-align: center;">
                                    <span align="center" style="font-family:Helvetica; font-size: 16px; color: #333333;">Find thousands of opportunities on our job board.</span>
                                </td>
                            </tr>
                            <tr>
                                <td style="width: 100%">
                                    <table style="width: 100%; padding-top: 12px;">
                                        <tr>
                                            <td style="text-align:center;">
                                                <a style="text-decoration: none;" href="http://mandrillapp.com/track/click/30022418/culinaryagents.com?p=eyJzIjoiWGtzSnVvVnFZU0lSdjNEclFCSF9jMVVfMk1JIiwidiI6MSwicCI6IntcInVcIjozMDAyMjQxOCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2N1bGluYXJ5YWdlbnRzLmNvbVxcXC9zZWFyY2hcXFwvam9ic1wiLFwiaWRcIjpcIjM5ODE4Y2U5NWMzZDQ4YzBhNWZjZmYzODg2YzI1MjA5XCIsXCJ1cmxfaWRzXCI6W1wiZWM2ZDJiZDFlOWM0ODUzNmJiODBiNGU3MTg3ZDhiZDgyYzgxMDcwNFwiXX0ifQ"><span style="font-family: Helvetica; color: #FFFFFF; font-size: 14px; padding: 8px 12px 8px 12px; background-color: #666666; border-radius: 4px;">See All Jobs</span></a>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>

                
                <tr>
                    <td>
                        <table cellpadding="0" cellspacing="0">
                            <tr>
                                <td style="-webkit-text-size-adjust: none; padding-top: 18px; padding-left: 10px; padding-right: 10px;">
                                    <span style="font-family: Helvetica; font-size: 10px; color: #CCCCCC; -webkit-text-size-adjust: none;">Copyright &copy; 2016 Culinary Agents, All rights reserved.</span>
                                    <br />
                                    <span style="font-family: Helvetica; font-size: 10px; color: #CCCCCC; -webkit-text-size-adjust: none;">You are receiving this email because with your Culinary Agents' profile, you opt in to be part of our national job matching pool, and you subscribe to the daily match emails.</span>

                                </td>
                            </tr>
                            <tr>
                                <td style="-webkit-text-size-adjust: none; padding-top: 18px; padding-left: 10px; padding-right: 10px;">
                                    <span style="-webkit-text-size-adjust: none; font-family:Helvetica; font-size: 10px; color: #666;"><a href="http://mandrillapp.com/track/click/30022418/culinaryagents.com?p=eyJzIjoiMHpkcEp5Y2RjTlo5VTFwdG95Rm9PVVR1cDBzIiwidiI6MSwicCI6IntcInVcIjozMDAyMjQxOCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2N1bGluYXJ5YWdlbnRzLmNvbVxcXC9zZXR0aW5ncz92aWV3PW5vdGlmaWNhdGlvbnNcIixcImlkXCI6XCIzOTgxOGNlOTVjM2Q0OGMwYTVmY2ZmMzg4NmMyNTIwOVwiLFwidXJsX2lkc1wiOltcIjEwM2ZjNjgxZTk5NjcxY2I2MDY5NDgxZmY4MDAyYTRiZGIwNGFmYjdcIl19In0" style="color:#666;">Unsubscribe</a></span>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>

            </table>
            </center>
        </td>
    </tr>
</table>
<img src="http://mandrillapp.com/track/open.php?u=30022418&id=39818ce95c3d48c0a5fcff3886c25209" height="1" width="1"></body>
</html>
--_av-STm0Nxl3tHHYtsYgnsFQzw--


