From bounce-142_HTML-382724067-5673089-1365844-57@bounce.opinion.bankofamerica.com Sat Nov 12 12:11:29 2016
Received: from mta.opinion.bankofamerica.com ([199.122.127.137]:33183)
	by ecbiz209.inmotionhosting.com with esmtp (Exim 4.87)
	(envelope-from <bounce-142_HTML-382724067-5673089-1365844-57@bounce.opinion.bankofamerica.com>)
	id 1c5bpw-001lWL-Ry
	for kyle@kylefisher.com; Sat, 12 Nov 2016 12:11:29 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; s=200608; d=opinion.bankofamerica.com;
 h=From:To:Subject:Date:List-Unsubscribe:MIME-Version:Reply-To:List-ID:Message-ID:Content-Type; i=branchexperiencesurvey@opinion.bankofamerica.com;
 bh=YNgjBHltB9mTKYudvhapI3T3mNc=;
 b=grtiJJhN6kqM1nRDX6/qcQ50bU3KL75hmAyODXWR8mk9jRjXS4SlWdpFYu1CeEzbmpGRhSpFQbv0
   xfaviU66HnLS6enm+6n9m1+dmQR9v1qqpNW8Fk6snFWqYYS7+ovAqT4rjTC/6UA03uaYcaL17JxB
   FUG20MgUq32/fQ96a2o=
DomainKey-Signature: a=rsa-sha1; c=nofws; q=dns; s=200608; d=opinion.bankofamerica.com;
 b=UfE2pFfWTndUKh99YF8BP902/OJEj5KoDw3D/7PANDw4Lig1uV1Af44mhhqovuHRCpeI45ZsV7yK
   A78gTz5+LJCeQRDJQHT4JxmQkp7XScNvkVl87BaActcDVydKKxhPGicwOkxFCDbDOkGP1J+NUxd5
   iLbu2+DotpdDhOuJZdA=;
Received: by mta.opinion.bankofamerica.com id h4t6k2163hsh for <kyle@kylefisher.com>; Sat, 12 Nov 2016 11:11:28 -0600 (envelope-from <bounce-142_HTML-382724067-5673089-1365844-57@bounce.opinion.bankofamerica.com>)
From: "Bank of America Branch Experience Survey" <branchexperiencesurvey@opinion.bankofamerica.com>
To: <kyle@kylefisher.com>
Subject: Reminder - We would like to hear from you about your recent branch experience.
Date: Sat, 12 Nov 2016 11:11:28 -0600
List-Unsubscribe: <mailto:leave-fd541574770b5c392848-fe28177877630679751277-fe891176726704757c-fe90157373610c7971-ff931177@leave.opinion.bankofamerica.com>
MIME-Version: 1.0
Reply-To: "Bank of America Branch Experience Survey" <reply-fe891176726704757c-142_HTML-382724067-1365844-57@opinion.bankofamerica.com>
List-ID: <1365844_5673089.xt.local>
X-CSA-Complaints: whitelistcomplaints@eco.de
x-job: 1365844_5673089
Message-ID: <6a28cc4a-3c78-4b20-9870-2165d52d8358@xtnvmta4360.xt.local>
Content-Type: multipart/alternative;
	boundary="May2bjAQQ36e=_?:"

This is a multi-part message in MIME format.

--May2bjAQQ36e=_?:
Content-Type: text/plain;
	charset="utf-8"
Content-Transfer-Encoding: 8bit



How was your experience?


https://www.bankofamericasurvey.com/26b8d3ca/plat/index.php?ticket=3142mh9zd8yg3 
Start the Survey

 
Approximate time to complete:  Up to 8 minutes 


Dear Kyle A Fisher, 



Thank you for using Bank of America for your banking needs. Your feedback helps us understand how well we are meeting your expectations. 



Bank of America has commissioned MaritzCX, a marketing research firm, to help collect valuable customer feedback about your experience at the Bank of America branch you recently visited. This information will be used to help ensure the best possible experiences for you and other customers.



Please be assured that all your responses will be reported in aggregate, and that your individual responses will be kept confidential. Your responses will not be shared with your Financial Advisor or Branch Management unless mandated by regulatory requirements. At no time will you be asked to discuss account numbers or personal details of your account.



The survey could take up to 8 minutes depending on your responses and is available 24 hours a day until November 15, 2016.


https://www.bankofamericasurvey.com/26b8d3ca/plat/index.php?ticket=3142mh9zd8yg3 

To access the survey, simply click on the "Start the Survey" button above, or copy and paste the following address into your web browser: 
 https://www.bankofamericasurvey.com/26b8d3ca/plat/index.php?ticket=3142mh9zd8yg3


This survey is sent by MaritzCX, a Bank of America business partner, on behalf of Bank of America.



If you have any questions or concerns about the survey, please reply to this email. Please do not include any financially sensitive information, such as an account number, PIN, password, or Online ID.



If you have any questions about your account, please either call the phone number on your account statement or use the 
http://click.opinion.bankofamerica.com/?qs=3b1fdaf26ce40d8c075fd84965eeffb88ab90b43a0fa4960e509286ffccaea5061c6cefe04316491 
Contact Us  page.



To ensure you receive important information and updates regarding your account(s), Bank of America encourages you to review your contact information and establish your contact priorities the next time you are in Online Banking, visit a Banking Center or call Customer Service



For an explanation of how Bank of America keeps your personal information safe, please refer to the Bank of America 
http://click.opinion.bankofamerica.com/?qs=3b1fdaf26ce40d8c6af4051feb859c7300fd0c1e0687cc325825d0bb48761a7c11e47eb03a9f026b 
Privacy Policy. 


If you no longer wish to receive emails for this survey, please click 
http://click.opinion.bankofamerica.com/?qs=3b1fdaf26ce40d8c0d7225f0318e8759b2fae2837ba8eb597c14a51605e351daf001330efe5ef848 
unsubscribe. 

Bank of America Email
 8th Floor-NC 1-002-08-25

101 South Tryon St.
 Charlotte, NC 28255-00001

Please do not send any physical mail to this address, especially mail containing sensitive information.


- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -





--May2bjAQQ36e=_?:
Content-Type: text/html;
	charset="utf-8"
Content-Transfer-Encoding: 8bit

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title></title>
        
            <!--[if gte mso 9]>
                <xml>
                <o:OfficeDocumentSettings>
                <o:AllowPNG/>
                <o:PixelsPerInch>96</o:PixelsPerInch>
                </o:OfficeDocumentSettings>
                </xml>
            <![endif]--> 
        
        <style type="text/css">

            #outlook a {padding:0;} 
            body{width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; margin:0; padding:0;}
            
            .ExternalClass {width:100%;} 
            
            .ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {line-height: 100%;} 
            
            #backgroundTable {margin:0; padding:0; width:100% !important; line-height: 100% !important;}

            img {outline:none; text-decoration:none; -ms-interpolation-mode: bicubic;}
            a img {border:none;}
            .image_fix {display:block;}
            
            p {margin: 1em 0;}
            
            h1, h2, h3, h4, h5, h6 {color: black !important;}
            h1 a, h2 a, h3 a, h4 a, h5 a, h6 a {color: blue !important;}
            h1 a:active, h2 a:active,  h3 a:active, h4 a:active, h5 a:active, h6 a:active {
                color: red !important; 
            }
            h1 a:visited, h2 a:visited,  h3 a:visited, h4 a:visited, h5 a:visited, h6 a:visited {
                color: purple !important; 
            }
            
            table td {border-collapse: collapse;}
            
            table { border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; }
            
            a {color: #0033CC;}
            
            .body{
                font-family:Arial, Helvetica, sans-serif;
                font-size: 16px; 
                line-height: 18px; 
                text-align: left;
            }
            
            .footer{
                font-family:Arial, Helvetica, sans-serif;
                font-size: 12px; 
                line-height: 14px; 
                text-align: left;
            }
            
            .link{
                color: #ffffff;
                font-family: Arial, Helvetica, sans-serif;
                font-size: 14px;
                line-height 14px;
                padding-left: 5px;
                padding-right: 5px;
            }
            
            .mobile {
                border-spacing:0;
                width:0;
                height:0;
                max-height:0;
                display:none;
                overflow:hidden;
                visibility:hidden;
                mso-hide:all;
            }

            .elibom {
                border-spacing:0;
                width:100%;
                height:100%;
                display:block;
                overflow:visible;
                visibility:visible;
                mso-hide:none;
            }

            
            @media screen and (max-width: 439px){
                .header{
                    font-size: 20px !important;
                    width: 100% !important;
                }
                
                .cta_button{
                    width:85% !important;
                    max-width:85% !important;                    
                }
                .body{
                    font-size: 16px !important;
                    line-height: 18px !important;                    
                }
                
                .check {
                    display: none !important;
                }
                
                .url{
                    font-size: 12px !important;
                }

                .mobile {
                    border-spacing:100% !important;
                    width:100% !important;
                    height:100% !important;
                    max-height:100% !important;
                    display:block !important;
                    overflow:visible !important;
                    visibility:visible !important;
                    mso-hide:none !important;
                }
                
                .elibom {
                    border-spacing:0 !important;
                    width:0 !important;
                    height:0 !important;
                    max-height:0 !important;
                    display:none !important;
                    overflow:hidden !important;
                    visibility:hidden !important;
                    mso-hide:all !important;
                }
                .header{
                    font-size: 22px !important;
                    letter-spacing: -.5px !important;                    
                }
                                
          }

        </style>
        
</head>
    <body style="width:100% !important;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
        
        <table cellpadding="0" cellspacing="0" border="0" id="backgroundTable" style="border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;width:100% !important;line-height:100% !important;" >
            <tr>
                <td>
                    
                    <table cellpadding="0" cellspacing="0" border="0" align="center" style="border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt;max-width: 600px;" >
                        <tr>
                            <td width="600" valign="top" align="right" style="padding-top:10px;padding-bottom:25px;padding-right:10px;padding-left:0px; max-width: 600px;" >
                                <img src="http://image.opinion.bankofamerica.com/lib/fe9015737d6c027c71/m/1/boa_logo.gif" border="0" style="display:blockoutline-style:none;text-decoration:none;-ms-interpolation-mode:bicubic;" >
                            </td>
                        </tr>
                        <!--[if t]><![endif]--><!--[if t]><![endif]--><!--[if t]><![endif]-->

                        <!--[if !mso]>
                        <!-- -->
                        <tr>
                            <td class="mobile" width="100%" style="background-color:#E41C39;background-image:url('http://image.opinion.bankofamerica.com/lib/fe971573706d067d71/m/1/background-flag.png');">
                                <div class="mobile" style="width:0;max-height:0;height:0;overflow:hidden;float:none;display:none; padding-bottom: 0;">
                                    <table class="mobile" align="center" height="0" border="0" cellpadding="0" cellspacing="0" style="overflow:hidden;display:none;visibility:hidden;width:0;max-height:0;height:0;">
                                        <tr>
                                            <td class="header" width="100%" height="32" style="background-position:top left;font-size:28px;line-height: 32px;color:#ffffff;font-family:Arial, Helvetica, sans-serif;padding-top:0;padding-bottom:0;padding-right:0;padding-left:15px;font-weight:600px;background-image: repeating-linear-gradient(-25deg, transparent, transparent 65px, #c72032 65px, #c72032 80px);">
                            How was your experience?    
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </td>
                        </tr>
                        <![endif]-->
                        <tr>
                            <td class="elibom">
                                <div class="elibom" style="border-spacing:0; width:100%; height:100%; max-height:100%; display:block; overflow:visible; visibility:visible; mso-hide:none;">
                                    <table class="elibom gradient" width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#E41C39" style="border-spacing:0; width:100%; height:100%; max-height:100%; display:block; overflow:visible; visibility:visible; mso-hide:none; background-image: repeating-linear-gradient(-25deg, transparent, transparent 65px, #c72032 65px, #c72032 80px);">
                                        <tr>
                                            <td class="elibom" width="100%" style="background-image: repeating-linear-gradient(25deg, transparent 0px, transparent 120px, #c72032 120px, #c72032 135px);">
                                                <img src="http://image.opinion.bankofamerica.com/lib/fe971573706d067d71/m/1/boa-header.png" alt="&nbsp;&nbsp;How was your experience?" width="100%" style="display: block; height: auto; font-size:25px;line-height: 1.5em;color:#ffffff;font-family:'Arial Narrow',Arial, Helvetica, sans-serif;"/>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td style="text-align:center;padding-top:10px;padding-bottom:10px;padding-right:0;padding-left:0;">
                                <center>
                                    <div style="margin: 0 auto;">
                                        <!--[if mso]>
<v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word"  href="https://www.bankofamericasurvey.com/26b8d3ca/plat/index.php?ticket=3142mh9zd8yg3" style="height:50px; v-text-anchor:middle; width:250px;" arcsize="15%" stroke="f" fill="t">
<v:fill type="tile" color="#0033CC" />
<w:anchorlock/>
<center style="color:#ffffff;font-family:Arial, Helvetica, sans-serif;font-size:22px;font-weight:normal;">
Start the Survey
</center>
</v:roundrect>
<![endif]-->
                                        <![if !mso]>
                                        <div style="margin: 0 auto;mso-hide:all;">
                                            <table class="cta_button" align="center" cellpadding="0" cellspacing="0" height="50" width="250" style="margin: 0 auto; mso-hide:all; max-width: 250px;">
                                                <tbody>
                                                    <tr>
                                                        <td align="center" bgcolor="#0033CC" width="100%" height="50" style="vertical-align:middle;color: #ffffff; display: block;background-color:#0033CC;mso-hide:all; border-radius: 5px;" >
                                                            <a class="cta_button" href="http://click.opinion.bankofamerica.com/?qs=3b1fdaf26ce40d8cbf6737f351f8a985bc096ad71465cfa7a575fc817002ea1eb76dab8938c5ba16" style="font-size:22px;-webkit-text-size-adjust:none; font-weight: bold; font-family:Arial, Helvetica, sans-serif; text-decoration: none; line-height:50px; width:100%; display:inline-block; border-radius: 0px;" title="Start the Survey">
                                                                <span style="color:#ffffff">Start the Survey</span>
                                                            </a>
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                        <![endif]>
                                    </div>
                                </center>
                            </td>
                        </tr>
                        <tr>
                            <td width="600" style="font-family:Arial, Helvetica, sans-serif; color:#000000; padding-top:0;padding-bottom:20px;padding-right:0;padding-left:0;text-align:center;font-size:16px; max-width: 600px;" > 
                                Approximate time to complete:&nbsp;&nbsp;Up to 8 minutes 
                            </td>
                        </tr>
                        <tr>
                            <td width="600" class="body" style="padding-top:0;padding-bottom:30px;padding-right:10px;padding-left:10px;font-family: Arial, Helvetica, sans-serif;font-size:14px;line-height:16px;text-align:left;max-width: 600px; color:#000000;">
                                Dear Kyle A Fisher, 
<br><br>
Thank you for using Bank of America for your banking needs. Your feedback helps us understand how well we are meeting your expectations. 
                                <br /><br />
Bank of America has commissioned MaritzCX, a marketing research firm, to help collect valuable customer feedback about your experience at the Bank of America branch you recently visited. This information will be used to help ensure the best possible experiences for you and other customers.
<br /><br />
Please be assured that all your responses will be reported in aggregate, and that your individual responses will be kept confidential. Your responses will not be shared with your Financial Advisor or Branch Management unless mandated by regulatory requirements. At no time will you be asked to discuss account numbers or personal details of your account.
<br><br>
The survey could take up to 8 minutes depending on your responses and is available 24 hours a day until November 15, 2016.
                            </td>
                        </tr>
                        <tr>
                            <td bgcolor="#C41230" width="600" style="max-width:600px; width: 600px;">
                                <table border="0" cellspacing="0" cellpadding="0" valign="top" width="100%" align="left" style="border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt;" >
                                    <tr>
                                        <td class="check">
                                            <a href="http://click.opinion.bankofamerica.com/?qs=3b1fdaf26ce40d8cbf6737f351f8a985bc096ad71465cfa7a575fc817002ea1eb76dab8938c5ba16" target="_blank" style="text-decoration: none;"><img src="http://image.opinion.bankofamerica.com/lib/fe971573706d067d71/m/1/JustIcon.png" alt="&#x270E;" width="78" height="84" border="0" style="display:block;padding-top:5px;padding-bottom:5px;padding-right:5px;padding-left:5px;color:#ffffff;font-size:70px;line-height:84px;font-weight:bold;outline-style:none;text-decoration:none;-ms-interpolation-mode:bicubic;vertical-align: center;border: 0;" />
                                                </a>
                                        </td>
                                        <td width="600" class="link" valign="center" style="color:#ffffff;font-family:Arial, Helvetica, sans-serif;font-size:14px; line-height: 14px; padding-left:5px;padding-right:5px; padding-top: 10px; padding-bottom: 10px; max-width: 600px;" >
                                            To access the survey, simply click on the "Start the Survey" button above, or copy and paste the following address into your web browser: <br>
                                            <span height="5" style="display: block; line-height: 5px; font-size: 5px; max-height: 5px; height: 5px;">&nbsp;</span>
                                            
                                            <span class="url" style="font-size:14px;line-height:14px;color:#0000ff; display: block; overflow-wrap: break-word; word-wrap: break-word; -ms-word-break: break-all; word-break: break-word; -ms-hyphens: auto; -moz-hyphens: auto; -webkit-hyphens: auto; hyphens: auto;">https://www.bankofamericasurvey.com/26b8d3ca/plat/index.php?ticket=3142mh9zd8yg3</span>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td width="600" class="body" style="padding-top:20px;padding-bottom:10px;padding-right:10px;padding-left:10px;font-family:Arial, Helvetica, sans-serif;color:#000000;font-size:14px;line-height:16px;text-align:left; max-width: 600px;" >
                                This survey is sent by MaritzCX, a Bank of America business partner, on behalf of Bank of America.
                                <br /><br />
If you have any questions or concerns about the survey, please reply to this email. Please do not include any financially sensitive information, such as an account number, PIN, password, or Online ID.
                                <br /><br />
                                If you have any questions about your account, please either call the phone number on your account statement or use the <a href="http://click.opinion.bankofamerica.com/?qs=3b1fdaf26ce40d8c075fd84965eeffb88ab90b43a0fa4960e509286ffccaea5061c6cefe04316491">Contact Us</a> page.
                                <br /><br />
To ensure you receive important information and updates regarding your account(s), Bank of America encourages you to review your contact information and establish your contact priorities the next time you are in Online Banking, visit a Banking Center or call Customer Service
                                <br /><br />
For an explanation of how Bank of America keeps your personal information safe, please refer to the Bank of America <a href="http://click.opinion.bankofamerica.com/?qs=3b1fdaf26ce40d8c6af4051feb859c7300fd0c1e0687cc325825d0bb48761a7c11e47eb03a9f026b" target="_blank">Privacy Policy.</a>
                                <br /><br />
If you no longer wish to receive emails for this survey, please click <a title="unsubscribe" href="http://click.opinion.bankofamerica.com/?qs=3b1fdaf26ce40d8c0d7225f0318e8759b2fae2837ba8eb597c14a51605e351daf001330efe5ef848" target="_blank">unsubscribe.</a>
                            </td>
                        </tr>
                        <tr>
                            <td width="600" class="footer" style="padding-top:0;padding-bottom:0;padding-right:10px;padding-left:10px;font-family:Arial, Helvetica, sans-serif; color:#333333; font-size:12px;line-height:14px;text-align:center;max-width: 600px;" >
                                Bank of America Email<br> 8th Floor-NC 1-002-08-25<br>
101 South Tryon St.<br> Charlotte, NC 28255-00001<br><br>
<b>Please do not send any physical mail to this address, especially mail containing sensitive information.</b>

                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
        <div style="display:none; white-space:nowrap; font:15px courier; color:#ffffff;">
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
</div>
        <img src="http://click.opinion.bankofamerica.com/open.aspx?ffcb10-fe891176726704757c-fdfa16727563057577137172-fe90157373610c7971-ff68157477-fe28177877630679751277-ff931177" width="1" height="1">
    </body>
</html>
			

--May2bjAQQ36e=_?:--


