From d8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2@bounce.r.groupon.com Sat Nov 12 16:55:11 2016
Received: from mta188s1.r.groupon.com ([50.115.211.188]:7052)
	by ecbiz209.inmotionhosting.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <d8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2@bounce.r.groupon.com>)
	id 1c5gGV-001tKx-4y
	for kyle@kylefisher.com; Sat, 12 Nov 2016 16:55:11 -0500
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=r.groupon.com;
	s=s2048d20160829; t=1478987711;
	bh=PXneJwKCPFEsf1DAEGCWaXzRNjKGfnyCO0qij7CNHsI=;
	h=Date:From:To:Message-ID:Subject:Content-Type;
	b=bgvHE0U0fqh4lRorVL8WV2Ar4YJWQOu1tBZRNPoa4RVN0xG9jhtw6fb2ZnMlqcuVP
	 GuLNSoKrDSlnN+dFO7F6TfTewyXqeHAJzmAAK/tyJYPEPfivJzLHLueQvpPXPd0h8R
	 +LJ2BQHueyM9TVaz1xFDCLf7XjdFa9GCnY/w9SXAMrlThdBW8CSMsCp7dOlnXvf26Z
	 X9pqOewOkaZNQ4o69Vwmob5l1f2BmiFOQ56YkJ9/BX/VglgTTUZ49bxQay93dl+JGm
	 Ap3uPnbwa1a4uSsj88C7Pl/KGm3dSHNXKe2og2daTLMvscvCtHerL83iFO5vqUmDSH
	 xHBVz5Jc6POpg==
Date: Sat, 12 Nov 2016 21:55:10 +0000
From: Groupon Goods <noreply@r.groupon.com>
To: kyle@kylefisher.com
Message-ID: <1991605345.24323372.1478987711009.JavaMail.rocketman@push-dispatcher1>
Subject: Prada Saffiano Leather Handbags, Toker Titanium Herb Grinder, Apple
 Watch Sport & More
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
X-RM-UserHash: d8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2
X-RM-SendId: b5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112
X-RM-SenderScore: 0
X-RM-EmailName: crm_discount_goods_us_im_20161112_NOTFeynman_LowAffinity
X-MSFBL: a3lsZUBreWxlZmlzaGVyLmNvbTpiYXRjaDpiNWFjODlhMC1lMWVlLTRmZWMtYjBmMC03ZGNhNzIxNTg3ZTlfMF8yMDE2MTExMjpudWxsOlVT
List-Unsubscribe: <mailto:d8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2@unsub.r.groupon.com?subject=a3lsZUBreWxlZmlzaGVyLmNvbTpiYXRjaDpiNWFjODlhMC1lMWVlLTRmZWMtYjBmMC03ZGNhNzIxNTg3ZTlfMF8yMDE2MTExMjpudWxsOlVT>
X-RPCampaign: Grouponcrmdiscountgoodsusim20161112NOTFeynmanLowAffinity20161112
X-RPTags: crm_discount_goods_us_im_20161112_NOTFeynman_LowAffinity
X-Recruiting: Interested in headers? Join us: www.groupon.com/techjobs/
List-Id: <crm_discount_goods_us_im_20161112_NOTFeynman_LowAffinity_20161112.groupon>
X-Feedback-ID: r.groupon.com:crm_discount_goods_us_im_20161112_NOTFeynman_LowAffinity:b5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112:groupon

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.=
w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> <html xmlns:v=3D"urn:schemas=
-microsoft-com:vml"> <head> <meta http-equiv=3D"Content-Type" content=3D"te=
xt/html; charset=3DUTF-8"> <meta name=3D"viewport" content=3D"initial-scale=
=3D1.0"> <meta name=3D"format-detection" content=3D"telephone=3Dno"> <title=
>Groupon</title> <style type=3D"text/css"> @media only screen and (max-widt=
h: 480px){ td[class=3D"mobile-padding-container"]{ padding: 10px !important=
; } td[class=3D"mobile-padding"]{ padding: 0 0 0 0 !important; } *[class=3D=
"mobile-padding-font"]{ padding: 0 0 0 0 !important; font-size: 10px !impor=
tant; font-weight:normal !important; } *[class=3D"mobile-padding-font-purch=
ase"]{ padding: 0 0 0 0 !important; font-size: 9px !important; font-weight:=
normal !important; } *[class=3D"mobile-padding-logo"]{ padding: 0 0 0 0 !im=
portant; width: 195px !important; } td[class=3D"header-text"]{ text-align: =
left !important; } img[class=3D"188"]{ width: 144px !important; } td[class=
=3D"floatLeft"]{ float: left !important; width: 100% !important; border: 0p=
x none !important; text-align: left !important; padding: 5px 0 5px 0 !impor=
tant; line-height: 14px !important; } td[class=3D"floatLeft-ship"]{ float: =
left !important; width: 100% !important; border: 0px none !important; text-=
align: left !important; padding: 5px 0 15px 0 !important; line-height: 14px=
 !important; font-size: 13px !important; } td[class=3D"floatLeft-name"]{ fl=
oat: left !important; width: 100% !important; border: 0px none !important; =
text-align: left !important; padding: 5px 0 5px 0 !important; line-height: =
14px !important; font-weight: bold !important; font-size: 13px !important; =
} td[class=3D"floatLeftDeals"]{ float: left !important; width: 100% !import=
ant; text-align: left !important; } img[class=3D"100"]{ width: 100% !import=
ant; } td[class=3D"100"]{ width: 100% !important; } table[class=3D"containe=
r"]{ width: 100% !important; float: none !important; } td[class=3D"border-o=
ff"]{ border-left: none !important; border-right: none !important; border-t=
op: 20px solid #ffffff; } td[class=3D"188"]{ width: 48% !important; } td[cl=
ass=3D"heroPadding"]{ padding: 20px 0 0 0 !important; } table[class=3D"oute=
r_container"]{ width: 100% !important; border-spacing: 0 !important; border=
-collapse: collapse !important; padding: 0 0 0 0 !important; margin-top: 0 =
!important; margin-bottom: 0 !important; margin-left: auto !important; marg=
in-right: auto !important; } table[class=3D"inner_container"]{ width: 100% =
!important; min-width: 100% !important; margin-top: 0 !important; margin-bo=
ttom: 0 !important; margin-left: auto !important; margin-right: auto !impor=
tant; border-spacing: 0 !important; border-collapse: collapse !important; p=
adding: 0 0 0 0 !important; } td[class=3D"inner_container"]{ width: 100% !i=
mportant; margin-top: 0 !important; margin-bottom: 0 !important; margin-lef=
t: auto !important; margin-right: auto !important; background-size: 100% !i=
mportant; } img[class=3D"secondary-100"]{ min-width: 0 !important; width: 1=
00% !important; padding: 0 0 0 0 !important; margin-top: 0 !important; marg=
in-bottom: 0 !important; margin-left: auto !important; margin-right: auto !=
important; } td[class=3D"floatLeft"]{ float: left !important; width: 100% !=
important; border: 0px none !important; text-align: left !important; paddin=
g: 5px 0 5px 0 !important; line-height: 14px !important; } td[class=3D"name=
Font"]{ font-size: 18px !important; line-height: 22px !important; } span[cl=
ass=3D"nameFont"]{ font-size: 18px !important; line-height: 22px !important=
; } td[class=3D"heroNameFont"]{ font-size: 18px !important; line-height: 22=
px !important; } table[class=3D"heroButton"]{ width: 120px !important; } /*=
 Collection widget price left */ td[class=3D"align-left-widget"]{ width: 10=
0% !important; float: left; text-align: left; padding: 0 8px 3px 13px !impo=
rtant; } *[class].banner_mobile { width: 100% !important; max-height: none =
!important; height: auto !important; display:block !important; } *[class].m=
obileHidden { display:none !important; } *[class].logo_mobile { max-height:=
 none !important; height: auto !important; display: block !important; margi=
n: 0 !important; } table[class=3D"display-off"]{ display: none !important; =
} td[class=3D"display-off"]{ display: none !important; } td[class=3D"displa=
y-block"]{ display: block !important; } td[class=3D"sm-mobile-font"]{ font-=
size: 10px !important; } } /* category widget for ios 5 and smaller */ @med=
ia only screen and (min-device-width: 320px) and (max-device-width: 479px) =
{ .three-column .column { width: 95% !important; max-width: 170px !importan=
t; display: inline-block; vertical-align: top; } } /* category widget for 5=
s phones or smaller */ @media only screen and (max-device-width: 320px) { .=
three-column .column { width: 75% !important; max-width: 145px !important; =
display: inline-block; vertical-align: top; } } /* To Hide Extra Nav Cats o=
n tablets */ @media only screen and (min-device-width : 768px) and (max-dev=
ice-width : 1024px) { td[class=3D"display-off"]{ display: none !important; =
} } </style> </head> <body style=3D"margin:0 !important; padding:0 !importa=
nt;"> <div style=3D"display:none; white-space:nowrap; font:15px courier; li=
ne-height:0;"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbs=
p; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &n=
bsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; =
</div> <img src =3D "http://www.groupon.com/analytic/track.gif?p=3D1&utm_do=
main=3Dkylefisher.com&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0=
_20161112&deals=3Db1004410-12d2-11e6-aa3b-00259060b5da,3c66cdc8-75f0-11e6-a=
53e-00259069d7cc,b296c5fc-631c-11e6-9644-00259069d868,0bfed708-686b-11e6-98=
51-00259069d868,4535e218-83fb-11e6-856e-002590604002,51506417-cb99-458d-978=
d-ec03486fbb9d,3e2d14f4-7f2f-11e5-868e-002590980a5a,e9d59326-6a5c-11e6-aa0d=
-00259069d7cc,f2e9ec40-7057-11e6-89e3-00259069d868,35c8d4b9-4864-4bec-5588-=
ab3b7cdb6029,76fa84a4-6adb-11e6-84bb-00259069d7cc,43efa2a6-6291-49ee-a1aa-b=
62a12656eda,78591936-9007-11e6-870d-00259069d868,665ec228-4389-11e6-a5e2-00=
259069d868,454e2e74-29ef-11e6-be37-00259069d868,d65be1f8-3abe-4ea1-8bc8-ae7=
123699f1b,2a629bbe-a410-11e5-bf99-00259098486a,bc44a02c-1e94-4a33-bd24-064e=
21d93a21,503c69bc-8b61-11e6-89fc-00259069d868,57ed4854-7c23-11e6-9cd7-00259=
069d868,c01baab2-73da-4159-b198-b07ca81000cb,01d12c81-7de6-4538-9c50-4c6a3f=
8d876a,d882f950-ca28-45dc-802a-9e2613981798&channel_deals=3Dnull&utm_source=
=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fb=
f5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-0025=
9069d5fe&CID=3DUS&tx=3D0" height=3D"1" width=3D"1" style=3D"display: none !=
important;" /> <img height=3D"1" width=3D"1" src=3D"https://stags.bluekai.c=
om/site/28445?limit=3D1&phint=3Dconsumer_id=3Df79c234c-2539-11e2-82c0-00259=
069d5fe&phint=3Dsource=3Demail" style=3D"display: none !important;" /> <tab=
le cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spac=
ing:0; font-family: Helvetica, Arial, sans-serif; color:#000000; font-weigh=
t: 100; width: 100%; background: #ececec;" align=3D"center"> <tr> <td align=
=3D"center"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 =
none; border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#0=
00000; font-weight: 100; width: 700px; min-width:600px; background: #ffffff=
;" width=3D"700" align=3D"center" class=3D"inner_container"> <tr> <td style=
=3D"padding: 10px 10px 10px 10px;" align=3D"center"> <span style=3D"color: =
#ffffff; font-size: 0px !important;" height=3D"0"> </span> <table cellpaddi=
ng=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-=
family: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; widt=
h: 600px;" width=3D"600" align=3D"center" class=3D"container"> <tr> <td sty=
le=3D"padding: 10px 0 10px 0;"> <table cellpadding=3D"0" cellspacing=3D"0" =
style=3D"width: 257px;" width=3D"257" align=3D"left" class=3D"container"> <=
tr> <td class=3D"mobile-padding-logo" align=3D"left" style=3D"width: 257px;=
"><a href=3D"https://www.groupon.com/goods?utm_source=3Dcrm_im&utm_medium=
=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561e=
d8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=
=3D0&s=3Dheader&c=3Dimage&d=3DGroupon&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f=
0-7dca721587e9_0_20161112" style=3D"font-size: 24px !important; line-height=
: 28px !important; color:#000000 !important; text-decoration: none; font-we=
ight: 100; font-weight: 700;" target=3D"_blank"><img src=3D"https://s3.grou=
poncdn.com/email/images/prom_night/global_images/pn-groupon-logo-green.png"=
 style=3D"display: block; border: none; width: 100%;" /></a> </td> </tr> </=
table> </td> <td align=3D"right" valign=3D"middle" style=3D"padding-left:10=
px;" valign=3D"bottom"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D=
"width: 100px;" width=3D"100" align=3D"right"> <tr> <td class=3D"mobile-pad=
ding" align=3D"right" valign=3D"middle" style=3D"vertical-align: middle;"><=
a href=3D"https://www.facebook.com/groupon" style=3D"color:#0185C6; text-de=
coration:none;" target=3D"_blank"><img src=3D"https://s3.grouponcdn.com/ema=
il/images/mindstorm/social/icon-facebook-white.png" style=3D"display: block=
; border: none; display: inline-block; width: 25px;" /></a>&nbsp;<a href=3D=
"https://www.twitter.com/groupon" style=3D"color:#0185C6; text-decoration:n=
one;" target=3D"_blank"><img src=3D"https://s3.grouponcdn.com/email/images/=
mindstorm/social/icon-twitter-white.png" style=3D"display: block; border: n=
one; display: inline-block; width: 25px;" /></a>&nbsp;<a href=3D"https://ww=
w.pinterest.com/groupon" style=3D"color:#0185C6; text-decoration:none;" tar=
get=3D"_blank"><img src=3D"https://s3.grouponcdn.com/email/images/mindstorm=
/social/icon-pinterest-white.png" style=3D"display: block; border: none; di=
splay: inline-block; width: 25px;" /></a></td> </tr> </table> </td> </tr> <=
tr> <td colspan=3D"2" style=3D"border-top: 1px solid #cccccc;"> <table cell=
padding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; =
font-family: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100;=
 width: 100%;" align=3D"center" class=3D"container"> <tr> <td style=3D"padd=
ing: 10px 0 0 0;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"bord=
er: 0 none; border-spacing:0; font-family: Helvetica, Arial, sans-serif; co=
lor:#000000; font-weight: 100; width: 100%;" align=3D"center" class=3D"cont=
ainer"> <tr> <td colspan=3D"2" class=3D"floatLeft-name" style=3D"width: 40%=
; font-size: 14px; color: #6d6d6d; font-weight: 500;" align=3D"left">For Yo=
u | November 12, 2016</td> </tr> </table> </td> </tr> </table> </td> </tr> =
</table> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none=
; border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#00000=
0; font-weight: 100; width: 100%;" align=3D"center" class=3D"outer_containe=
r"> <tr> <td align=3D"center" style=3D"padding-top: 10px;" class=3D"heroPad=
ding"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; =
border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#000000;=
 font-weight: 100; width: 600px;" align=3D"center" class=3D"inner_container=
"> <tr> <td colspan=3D"2"><a href=3D"https://www.groupon.com/deals/gg-assor=
ted-prada-bags?p=3D1&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8=
bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=
=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton=
&d=3DGoods-PN-Hero&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20=
161112" target=3D"_blank" style=3D"display: block; border: none;"> <table c=
ellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:=
0; font-family: Helvetica, Arial, sans-serif; color:#000000; font-weight: 1=
00; width: 600px;" align=3D"center" class=3D"inner_container"> <tr> <td ali=
gn=3D"center" style=3D"width: 100%; border-top: 1px solid #f2f2f2; border-l=
eft: 1px solid #f2f2f2; border-right: 1px solid #f2f2f2;"> <img src=3D"http=
s://img.grouponcdn.com/deal/4BZWEAjbgm2dEpsa1nkTrKfNaSVi/4B-1400x840/v1/c60=
0x320.jpg" style=3D"display: block; border: none;" class=3D"100" /> </td> <=
/tr> </table> </a></td> </tr> <tr> <td align=3D"left" style=3D"background: =
#ffffff; padding: 15px 5px 15px 15px;"><a href=3D"https://www.groupon.com/d=
eals/gg-assorted-prada-bags?p=3D1&utm_source=3Dcrm_im&utm_medium=3Demail&us=
er=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=
=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Db=
ody&c=3Dbutton&d=3DGoods-PN-Hero&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dc=
a721587e9_0_20161112" target=3D"_blank" style=3D"font-size: 16px !important=
; line-height: 20px !important; color:#000000 !important; text-decoration: =
none; color: #ffffff;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D=
"border: 0 none; border-spacing:0; font-family: Helvetica, Arial, sans-seri=
f; color:#000000; font-weight: 100; width: 100%; background: #ffffff;" alig=
n=3D"center"> <tr> <td class=3D"heroNameFont" style=3D"font-size: 18px; lin=
e-height: 22px; text-decoration: none; color:#333333;" align=3D"left"> Prad=
a Saffiano Leather Handbags </td> </tr> <tr> <td><a href=3D"https://www.gro=
upon.com/deals/gg-assorted-prada-bags?p=3D1&utm_source=3Dcrm_im&utm_medium=
=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561e=
d8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=
=3D0&s=3Dbody&c=3Dlink&d=3DMindstorm-Hero-3&utm_campaign=3Db5ac89a0-e1ee-4f=
ec-b0f0-7dca721587e9_0_20161112" target=3D"_blank" style=3D"font-size: 14px=
 !important; line-height: 18px !important; font-weight: 100; color: #939393=
 !important; text-decoration: none;"> <table cellpadding=3D"0" cellspacing=
=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Helvetica, A=
rial, sans-serif; color:#000000; font-weight: 100; width: 100%;"> <tr> <td =
colspan=3D"2" style=3D"font-size: 14px !important; line-height: 18px !impor=
tant; font-weight: 100; color: #939393 !important; text-decoration: none;" =
class=3D"nameFont" align=3D"left"><font color=3D"#e35205">Over 50 bought &n=
bsp;&nbsp;</font></td> </tr> </table> </a></td> </tr> <tr> <td style=3D"pad=
ding: 3px 0 0 0; background: #ffffff;" align=3D"left"> <table cellpadding=
=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-fa=
mily: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100;"> <tr>=
 <td class=3D"nameFont" align=3D"left" valign=3D"top" style=3D"padding-righ=
t: 5px; padding-right: 5px; font-family: Helvetica, Arial, sans-serif; font=
-size: 16px !important; line-height: 20px !important; text-decoration: line=
-through; color:#848484 !important; font-weight: 100;"> $1350 </td> <td cla=
ss=3D"nameFont" align=3D"left" valign=3D"top" style=3D"font-family: Helveti=
ca, Arial, sans-serif; font-size: 16px !important; line-height: 20px !impor=
tant; font-weight: 300; text-decoration: none; color: #e35205;"> $749.99 </=
td> </tr> </table> </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" v=
align=3D"top" style=3D"font-size: 13px; color: #e35205; text-decoration: no=
ne; font-weight: 500 !important;">Extra $150 Off Ends 11/14</td> </tr> </ta=
ble> </a></td> <td align=3D"right" style=3D"padding: 15px 15px 15px 0; back=
ground: #ffffff;" valign=3D"middle"><a href=3D"https://www.groupon.com/deal=
s/gg-assorted-prada-bags?p=3D1&utm_source=3Dcrm_im&utm_medium=3Demail&user=
=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D=
20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody=
&c=3Dlink&d=3DMindstorm-Hero-3&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca7=
21587e9_0_20161112" target=3D"_blank" style=3D"font-size: 18px !important; =
line-height: 22px !important; color: #000000 !important; text-decoration: n=
one;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"font-family: Ari=
al, Helvetica, sans-serif; font-size:14px !important; line-height:19px !imp=
ortant; color:#333; width:180px; background: #ffffff;" class=3D"heroButton"=
 align=3D"right" valign=3D"bottom"> <tr> <td height=3D"45" bgcolor=3D"#82B5=
48" background=3D"https://s3.grouponcdn.com/email/images/global_buttons/pn-=
gradient-green.jpg" background-repeat=3D"repeat-x" style=3D"height: 45px; t=
ext-align: center;"><a href=3D"https://www.groupon.com/deals/gg-assorted-pr=
ada-bags?p=3D1&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf=
574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79=
c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DG=
oods-PN-Hero&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112=
" style=3D"padding: 10px 0 10px 0; color:#ffffff; font-size:16px; font-weig=
ht: 500; text-decoration:none;">VIEW&nbsp;DEAL</a></td> </tr> </table> </a>=
</td> </tr> </table> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"bo=
rder: 0 none; border-spacing:0; font-family: Helvetica, Arial, sans-serif; =
color:#000000; font-weight: 100; width: 100%; background: #fffffff;" align=
=3D"center"> <tr> <td align=3D"center"> <table cellpadding=3D"0" cellspacin=
g=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Helvetica, =
Arial, sans-serif; color:#000000; font-weight: 100; width: 600px;" align=3D=
"center" class=3D"inner_container"> <tr> <td class=3D"banner_mobile" align=
=3D"center" style=3D"padding-top:10px; display:none; font-size:0; max-heigh=
t:0; line-height:0; mso-hide: all;" align=3D"center"><a href=3D"https://www=
.groupon.com/occasion/doorbusters?utm_source=3Dcrm_im&utm_medium=3Demail&us=
er=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=
=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Db=
ody&c=3Dbanner&d=3Dmiddle-banner&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dc=
a721587e9_0_20161112" style=3D"color:#0185C6; text-decoration:none;" target=
=3D"_blank"><img class=3D"banner_mobile" src=3D"https://img.grouponcdn.com/=
deal/bsagcgu4tggFZE6NF4qjdMfZshp/bs-460x120" style=3D"padding:0px; display:=
none; font-size:0; max-height:0; line-height:0; mso-hide: all;" border=3D"0=
" alt=3D"12 Days of Doorbusters" title=3D"12 Days of Doorbusters" /></a></t=
d> </tr> </table> <table class=3D"display-off" cellpadding=3D"0" cellspacin=
g=3D"0" style=3D"font-family: Arial, Helvetica, sans-serif; font-size:14px =
!important; line-height:19px !important; color:#333; width: 600px;" align=
=3D"center"> <tr> <td align=3D"center" style=3D"padding-top: 3.5%;"><a href=
=3D"https://www.groupon.com/occasion/doorbusters?utm_source=3Dcrm_im&utm_me=
dium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386=
561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DU=
S&tx=3D0&s=3Dbody&c=3Dbanner&d=3Dmiddle-banner&utm_campaign=3Db5ac89a0-e1ee=
-4fec-b0f0-7dca721587e9_0_20161112" style=3D"color:#0185C6; text-decoration=
:none;" target=3D"_blank"><img src=3D"https://img.grouponcdn.com/deal/4EwNB=
XPF49b7bfj9TpX83cAi7rCZ/4E-600x100" style=3D"display: block; border: none; =
font-size:12px; width: 100%; border-bottom: 1px solid #cccccc;" alt=3D"12 D=
ays of Doorbusters" title=3D"https://www.groupon.com/occasion/doorbusters?"=
 /></a></td> </tr> </table> </td> </tr> </table> <table style=3D"width: 10p=
x; background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</table> <table cell=
padding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; =
font-family: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100;=
 width: 600px; background: #FFFFFF" align=3D"center" class=3D"inner_contain=
er"> <tr> <td valign=3D"top" align=3D"left" width=3D"100%" style=3D"width: =
600px;" class=3D"inner_container"> <!--[if (gte mso 9)|(IE)]> <table width=
=3D"600" align=3D"center" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">=
 <tr> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"=
https://www.groupon.com/deals/gg-titanium-herb-grinder-5-piece?p=3D2&utm_so=
urce=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f8=
06fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-=
00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=
=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_blank" style=
=3D"text-decoration:none;"> <table cellpadding=3D"0" cellspacing=3D"0" styl=
e=3D"border: 0 none; border-spacing:0; font-family: Helvetica, Arial, sans-=
serif; color:#000000; font-weight: 100; background: #ffffff; width:290px;" =
valign=3D"top" class=3D"inner_container"align=3D'left'> <tr> <td style=3D"w=
idth:290px;" align=3D"center" valign=3D"top"> <table cellpadding=3D"0" cell=
spacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Helve=
tica, Arial, sans-serif; color:#000000; font-weight: 100; background: #f2f2=
f2; width:100%;"> <tr> <td valign=3D"top" align=3D"center" width=3D"290" st=
yle=3D"width:290px;" class=3D"inner_container"><a href=3D"https://www.group=
on.com/deals/gg-titanium-herb-grinder-5-piece?p=3D2&utm_source=3Dcrm_im&utm=
_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf=
386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=
=3DUS&tx=3D0&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4=
fec-b0f0-7dca721587e9_0_20161112" style=3D"display: block; border: none;" t=
arget=3D"_blank"><img src=3D"https://img.grouponcdn.com/deal/3SEbKfU5zSeSzK=
15LZooFXtgEAga/3S-1400x840/v1/c300x182.jpg" width=3D"290" style=3D"display:=
 block; border: none; width: 290px;" class=3D"secondary-100" alt=3D"Toker T=
itanium Herb Grinder (5-Piece)" /></a></td> </tr> <tr> <td style=3D"padding=
:16px;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none=
; border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#00000=
0; font-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td colspan=3D=
"2" class=3D"nameFont" style=3D"font-size: 14px !important; line-height: 18=
px !important; color:#000000 !important; text-decoration: none; color: #333=
333 !important; width:100%;" align=3D"left" valign=3D"top"> Toker Titanium =
Herb Grinder </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=
=3D"top"><a href=3D"https://www.groupon.com/deals/gg-titanium-herb-grinder-=
5-piece?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf5=
74337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c=
234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DMi=
ndstorm-Hero-3-deals&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_=
20161112" target=3D"_blank" style=3D"font-size: 14px !important; line-heigh=
t: 18px !important; color:#000000 !important; text-decoration: none;"><font=
 color=3D"#e35205">Over 1,000 bought</font></a></td> </tr> <tr> <td width=
=3D"70%" align=3D"left"> <span valign=3D"top" style=3D"padding-right: 5px; =
font-family: Helvetica, Arial, sans-serif; font-size: 16px !important; line=
-height: 20px !important; text-decoration: line-through; color:#848484 !imp=
ortant; font-weight: 100;" class=3D"nameFont">$49.95</span> <span align=3D"=
left" valign=3D"top" style=3D"font-family: Helvetica, Arial, sans-serif; fo=
nt-size: 16px !important; line-height: 20px !important; font-weight: 300; t=
ext-decoration: none; color: #e35205;" class=3D"nameFont">$7.99</span> </td=
> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"top" style=3D"=
font-family: Helvetica, Arial, sans-serif; font-size: 13px; color: #e35205;=
 text-decoration: none; font-weight: 500 !important;">Sale Ends 11/13</td> =
<td width=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" style=
=3D"font-family: Helvetica, Arial, sans-serif; font-size: 13px !important; =
line-height: 17px !important; font-weight: normal; font-weight: 600; color:=
 #0185c6 !important; text-decoration: none; text-align:right; white-space: =
nowrap;"><a href=3D"https://www.groupon.com/deals/gg-titanium-herb-grinder-=
5-piece?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf5=
74337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c=
234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGo=
ods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" targ=
et=3D"_blank" style=3D"text-decoration:none;"><font color=3D"#0185c6">View&=
nbsp;Deal</font></a></td> </tr> </table> </td> </tr> <tr> <td style=3D"widt=
h: 10px; background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> </tr> </=
table> </td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]=
--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https://www.gro=
upon.com/deals/gg-apple-watch-sport-38mm-refurbish?p=3D3&utm_source=3Dcrm_i=
m&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac=
134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe=
&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e=
1ee-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_blank" style=3D"text-deco=
ration:none;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: =
0 none; border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:=
#000000; font-weight: 100; background: #ffffff; width:290px;" valign=3D"top=
" class=3D"inner_container"align=3D'right'> <tr> <td style=3D"width:290px;"=
 align=3D"center" valign=3D"top"> <table cellpadding=3D"0" cellspacing=3D"0=
" style=3D"border: 0 none; border-spacing:0; font-family: Helvetica, Arial,=
 sans-serif; color:#000000; font-weight: 100; background: #f2f2f2; width:10=
0%;"> <tr> <td valign=3D"top" align=3D"center" width=3D"290" style=3D"width=
:290px;" class=3D"inner_container"><a href=3D"https://www.groupon.com/deals=
/gg-apple-watch-sport-38mm-refurbish?p=3D3&utm_source=3Dcrm_im&utm_medium=
=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561e=
d8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=
=3D0&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0=
-7dca721587e9_0_20161112" style=3D"display: block; border: none;" target=3D=
"_blank"><img src=3D"https://img.grouponcdn.com/deal/7uNhFzj1Uqfc3wL2M8cxmh=
PLabP/7u-1800x1080/v1/c300x182.jpg" width=3D"290" style=3D"display: block; =
border: none; width: 290px;" class=3D"secondary-100" alt=3D"Apple Watch Spo=
rt 38mm or 42mm (Refurbished) " /></a></td> </tr> <tr> <td style=3D"padding=
:16px;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none=
; border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#00000=
0; font-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td colspan=3D=
"2" class=3D"nameFont" style=3D"font-size: 14px !important; line-height: 18=
px !important; color:#000000 !important; text-decoration: none; color: #333=
333 !important; width:100%;" align=3D"left" valign=3D"top"> Apple Watch Spo=
rt </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"top"><a=
 href=3D"https://www.groupon.com/deals/gg-apple-watch-sport-38mm-refurbish?=
p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c82=
2070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-253=
9-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DMindstorm-=
Hero-3-deals&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112=
" target=3D"_blank" style=3D"font-size: 14px !important; line-height: 18px =
!important; color:#000000 !important; text-decoration: none;"><font color=
=3D"#e35205">Over 1,000 bought</font></a></td> </tr> <tr> <td width=3D"70%"=
 align=3D"left"> <span valign=3D"top" style=3D"padding-right: 5px; font-fam=
ily: Helvetica, Arial, sans-serif; font-size: 16px !important; line-height:=
 20px !important; text-decoration: line-through; color:#848484 !important; =
font-weight: 100;" class=3D"nameFont">$299</span> <span align=3D"left" vali=
gn=3D"top" style=3D"font-family: Helvetica, Arial, sans-serif; font-size: 1=
6px !important; line-height: 20px !important; font-weight: 300; text-decora=
tion: none; color: #e35205;" class=3D"nameFont">$194.99</span> </td> </tr> =
<tr> <td class=3D"nameFont" align=3D"left" valign=3D"top" style=3D"font-fam=
ily: Helvetica, Arial, sans-serif; font-size: 13px; color: #e35205; text-de=
coration: none; font-weight: 500 !important;">Sale Ends 11/12</td> <td widt=
h=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" style=3D"font-f=
amily: Helvetica, Arial, sans-serif; font-size: 13px !important; line-heigh=
t: 17px !important; font-weight: normal; font-weight: 600; color: #0185c6 !=
important; text-decoration: none; text-align:right; white-space: nowrap;"><=
a href=3D"https://www.groupon.com/deals/gg-apple-watch-sport-38mm-refurbish=
?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c8=
22070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-25=
39-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&=
utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_=
blank" style=3D"text-decoration:none;"><font color=3D"#0185c6">View&nbsp;De=
al</font></a></td> </tr> </table> </td> </tr> <tr> <td style=3D"width: 10px=
; background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> </tr> </table> =
</td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!-=
-[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </tr>=
 </table> <![endif]--> </tr> <tr> <td valign=3D"top" align=3D"left" width=
=3D"100%" style=3D"width: 600px;" class=3D"inner_container"> <!--[if (gte m=
so 9)|(IE)]> <table width=3D"600" align=3D"center" cellpadding=3D"0" cellsp=
acing=3D"0" border=3D"0"> <tr> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td>=
 <![endif]--> <a href=3D"https://www.groupon.com/deals/gg-beats-solo-2?p=3D=
4&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070=
ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11=
e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_c=
ampaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_blank=
" style=3D"text-decoration:none;"> <table cellpadding=3D"0" cellspacing=3D"=
0" style=3D"border: 0 none; border-spacing:0; font-family: Helvetica, Arial=
, sans-serif; color:#000000; font-weight: 100; background: #ffffff; width:2=
90px;" valign=3D"top" class=3D"inner_container"align=3D'left'> <tr> <td sty=
le=3D"width:290px;" align=3D"center" valign=3D"top"> <table cellpadding=3D"=
0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-family=
: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; background=
: #f2f2f2; width:100%;"> <tr> <td valign=3D"top" align=3D"center" width=3D"=
290" style=3D"width:290px;" class=3D"inner_container"><a href=3D"https://ww=
w.groupon.com/deals/gg-beats-solo-2?p=3D4&utm_source=3Dcrm_im&utm_medium=3D=
email&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8c=
d2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D=
0&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7d=
ca721587e9_0_20161112" style=3D"display: block; border: none;" target=3D"_b=
lank"><img src=3D"https://img.grouponcdn.com/deal/mWnYduAspd9fNJuHcgq7/on-1=
560x990/v1/c300x182.jpg" width=3D"290" style=3D"display: block; border: non=
e; width: 290px;" class=3D"secondary-100" alt=3D"Beats by Dr. Dre Solo2 On-=
Ear Headphones " /></a></td> </tr> <tr> <td style=3D"padding:16px;"> <table=
 cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacin=
g:0; font-family: Helvetica, Arial, sans-serif; color:#000000; font-weight:=
 100; background: #f2f2f2; width:100%;"> <tr> <td colspan=3D"2" class=3D"na=
meFont" style=3D"font-size: 14px !important; line-height: 18px !important; =
color:#000000 !important; text-decoration: none; color: #333333 !important;=
 width:100%;" align=3D"left" valign=3D"top"> Beats Solo2 On-Ear Headphones =
</td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"top"><a hr=
ef=3D"https://www.groupon.com/deals/gg-beats-solo-2?p=3D2&utm_source=3Dcrm_=
im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2aca=
c134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5f=
e&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-deals&utm_campai=
gn=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_blank" sty=
le=3D"font-size: 14px !important; line-height: 18px !important; color:#0000=
00 !important; text-decoration: none;"><font color=3D"#e35205">Over 1,000 b=
ought</font></a></td> </tr> <tr> <td width=3D"70%" align=3D"left"> <span va=
lign=3D"top" style=3D"padding-right: 5px; font-family: Helvetica, Arial, sa=
ns-serif; font-size: 16px !important; line-height: 20px !important; text-de=
coration: line-through; color:#848484 !important; font-weight: 100;" class=
=3D"nameFont">$199.99</span> <span align=3D"left" valign=3D"top" style=3D"f=
ont-family: Helvetica, Arial, sans-serif; font-size: 16px !important; line-=
height: 20px !important; font-weight: 300; text-decoration: none; color: #e=
35205;" class=3D"nameFont">$99.99</span> </td> </tr> <tr> <td class=3D"name=
Font" align=3D"left" valign=3D"top" style=3D"font-family: Helvetica, Arial,=
 sans-serif; font-size: 13px; color: #e35205; text-decoration: none; font-w=
eight: 500 !important;">Sale Ends 11/14</td> <td width=3D"30%" class=3D"nam=
eFont" align=3D"right" valign=3D"top" style=3D"font-family: Helvetica, Aria=
l, sans-serif; font-size: 13px !important; line-height: 17px !important; fo=
nt-weight: normal; font-weight: 600; color: #0185c6 !important; text-decora=
tion: none; text-align:right; white-space: nowrap;"><a href=3D"https://www.=
groupon.com/deals/gg-beats-solo-2?p=3D2&utm_source=3Dcrm_im&utm_medium=3Dem=
ail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2=
&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&=
s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dc=
a721587e9_0_20161112" target=3D"_blank" style=3D"text-decoration:none;"><fo=
nt color=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </table> </td> </=
tr> <tr> <td style=3D"width: 10px; background: #ffffff;">&nbsp;&nbsp;&nbsp;=
&nbsp;&nbsp;</td> </tr> </table> </td> </tr> </table> </a> <!--[if (gte mso=
 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> =
<a href=3D"https://www.groupon.com/deals/gg-skeletool?p=3D5&utm_source=3Dcr=
m_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2a=
cac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d=
5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Db5ac89a=
0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_blank" style=3D"text-d=
ecoration:none;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"borde=
r: 0 none; border-spacing:0; font-family: Helvetica, Arial, sans-serif; col=
or:#000000; font-weight: 100; background: #ffffff; width:290px;" valign=3D"=
top" class=3D"inner_container"align=3D'right'> <tr> <td style=3D"width:290p=
x;" align=3D"center" valign=3D"top"> <table cellpadding=3D"0" cellspacing=
=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Helvetica, A=
rial, sans-serif; color:#000000; font-weight: 100; background: #f2f2f2; wid=
th:100%;"> <tr> <td valign=3D"top" align=3D"center" width=3D"290" style=3D"=
width:290px;" class=3D"inner_container"><a href=3D"https://www.groupon.com/=
deals/gg-skeletool?p=3D5&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bf=
d7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D2016111=
2&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dim=
age&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_2016=
1112" style=3D"display: block; border: none;" target=3D"_blank"><img src=3D=
"https://img.grouponcdn.com/deal/ffpU44UXFucioMkGzQZn/U9-700x420/v1/c300x18=
2.jpg" width=3D"290" style=3D"display: block; border: none; width: 290px;" =
class=3D"secondary-100" alt=3D"Leatherman Skeletool" /></a></td> </tr> <tr>=
 <td style=3D"padding:16px;"> <table cellpadding=3D"0" cellspacing=3D"0" st=
yle=3D"border: 0 none; border-spacing:0; font-family: Helvetica, Arial, san=
s-serif; color:#000000; font-weight: 100; background: #f2f2f2; width:100%;"=
> <tr> <td colspan=3D"2" class=3D"nameFont" style=3D"font-size: 14px !impor=
tant; line-height: 18px !important; color:#000000 !important; text-decorati=
on: none; color: #333333 !important; width:100%;" align=3D"left" valign=3D"=
top"> Leatherman Skeletool </td> </tr> <tr> <td class=3D"nameFont" align=3D=
"left" valign=3D"top"><a href=3D"https://www.groupon.com/deals/gg-skeletool=
?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c8=
22070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-25=
39-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DMindstorm=
-Hero-3-deals&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_2016111=
2" target=3D"_blank" style=3D"font-size: 14px !important; line-height: 18px=
 !important; color:#000000 !important; text-decoration: none;"><font color=
=3D"#e35205">Over 600 bought</font></a></td> </tr> <tr> <td width=3D"70%" a=
lign=3D"left"> <span valign=3D"top" style=3D"padding-right: 5px; font-famil=
y: Helvetica, Arial, sans-serif; font-size: 16px !important; line-height: 2=
0px !important; text-decoration: line-through; color:#848484 !important; fo=
nt-weight: 100;" class=3D"nameFont">$70</span> <span align=3D"left" valign=
=3D"top" style=3D"font-family: Helvetica, Arial, sans-serif; font-size: 16p=
x !important; line-height: 20px !important; font-weight: 300; text-decorati=
on: none; color: #e35205;" class=3D"nameFont">$39.99</span> </td> </tr> <tr=
> <td class=3D"nameFont" align=3D"left" valign=3D"top" style=3D"font-family=
: Helvetica, Arial, sans-serif; font-size: 13px; color: #e35205; text-decor=
ation: none; font-weight: 500 !important;">Sale Ends 11/13</td> <td width=
=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" style=3D"font-fa=
mily: Helvetica, Arial, sans-serif; font-size: 13px !important; line-height=
: 17px !important; font-weight: normal; font-weight: 600; color: #0185c6 !i=
mportant; text-decoration: none; text-align:right; white-space: nowrap;"><a=
 href=3D"https://www.groupon.com/deals/gg-skeletool?p=3D2&utm_source=3Dcrm_=
im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2aca=
c134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5f=
e&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Db5ac89a0-=
e1ee-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_blank" style=3D"text-dec=
oration:none;"><font color=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr>=
 </table> </td> </tr> <tr> <td style=3D"width: 10px; background: #ffffff;">=
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> </tr> </table> </td> </tr> </table> </a=
> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> =
</td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </tr> </table> <![endif]--> <=
/tr> <tr> <td valign=3D"top" align=3D"left" width=3D"100%" style=3D"width: =
600px;" class=3D"inner_container"> <!--[if (gte mso 9)|(IE)]> <table width=
=3D"600" align=3D"center" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">=
 <tr> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"=
https://www.groupon.com/deals/gg-j-sport-by-jambu-windham-cold-weather-boot=
?p=3D6&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c8=
22070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-25=
39-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&=
utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_=
blank" style=3D"text-decoration:none;"> <table cellpadding=3D"0" cellspacin=
g=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Helvetica, =
Arial, sans-serif; color:#000000; font-weight: 100; background: #ffffff; wi=
dth:290px;" valign=3D"top" class=3D"inner_container"align=3D'left'> <tr> <t=
d style=3D"width:290px;" align=3D"center" valign=3D"top"> <table cellpaddin=
g=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-f=
amily: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; backg=
round: #f2f2f2; width:100%;"> <tr> <td valign=3D"top" align=3D"center" widt=
h=3D"290" style=3D"width:290px;" class=3D"inner_container"><a href=3D"https=
://www.groupon.com/deals/gg-j-sport-by-jambu-windham-cold-weather-boot?p=3D=
6&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070=
ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11=
e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_ca=
mpaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" style=3D"display:=
 block; border: none;" target=3D"_blank"><img src=3D"https://img.grouponcdn=
.com/deal/3knKeiBgdhmmtdj7nGuHkd3V1WvN/3k-1500x900/v1/c300x182.jpg" width=
=3D"290" style=3D"display: block; border: none; width: 290px;" class=3D"sec=
ondary-100" alt=3D"JSport by Jambu Windham Women's Boots" /></a></td> </tr>=
 <tr> <td style=3D"padding:16px;"> <table cellpadding=3D"0" cellspacing=3D"=
0" style=3D"border: 0 none; border-spacing:0; font-family: Helvetica, Arial=
, sans-serif; color:#000000; font-weight: 100; background: #f2f2f2; width:1=
00%;"> <tr> <td colspan=3D"2" class=3D"nameFont" style=3D"font-size: 14px !=
important; line-height: 18px !important; color:#000000 !important; text-dec=
oration: none; color: #333333 !important; width:100%;" align=3D"left" valig=
n=3D"top"> JSport by Jambu Women's Boots </td> </tr> <tr> <td class=3D"name=
Font" align=3D"left" valign=3D"top"><a href=3D"https://www.groupon.com/deal=
s/gg-j-sport-by-jambu-windham-cold-weather-boot?p=3D2&utm_source=3Dcrm_im&u=
tm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134=
cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CI=
D=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-deals&utm_campaign=
=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_blank" style=
=3D"font-size: 14px !important; line-height: 18px !important; color:#000000=
 !important; text-decoration: none;"><font color=3D"#e35205">Over 1,000 bou=
ght</font></a></td> </tr> <tr> <td width=3D"70%" align=3D"left"> <span vali=
gn=3D"top" style=3D"padding-right: 5px; font-family: Helvetica, Arial, sans=
-serif; font-size: 16px !important; line-height: 20px !important; text-deco=
ration: line-through; color:#848484 !important; font-weight: 100;" class=3D=
"nameFont">$89.95</span> <span align=3D"left" valign=3D"top" style=3D"font-=
family: Helvetica, Arial, sans-serif; font-size: 16px !important; line-heig=
ht: 20px !important; font-weight: 300; text-decoration: none; color: #e3520=
5;" class=3D"nameFont">$34.99</span> </td> </tr> <tr> <td class=3D"nameFont=
" align=3D"left" valign=3D"top" style=3D"font-family: Helvetica, Arial, san=
s-serif; font-size: 13px; color: #e35205; text-decoration: none; font-weigh=
t: 500 !important;">Sale Ends 11/13</td> <td width=3D"30%" class=3D"nameFon=
t" align=3D"right" valign=3D"top" style=3D"font-family: Helvetica, Arial, s=
ans-serif; font-size: 13px !important; line-height: 17px !important; font-w=
eight: normal; font-weight: 600; color: #0185c6 !important; text-decoration=
: none; text-align:right; white-space: nowrap;"><a href=3D"https://www.grou=
pon.com/deals/gg-j-sport-by-jambu-windham-cold-weather-boot?p=3D2&utm_sourc=
e=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806f=
bf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-002=
59069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Db=
5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_blank" style=3D"=
text-decoration:none;"><font color=3D"#0185c6">View&nbsp;Deal</font></a></t=
d> </tr> </table> </td> </tr> <tr> <td style=3D"width: 10px; background: #f=
fffff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> </tr> </table> </td> </tr> </ta=
ble> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)=
|(IE)]> <td> <![endif]--> <a href=3D"https://www.groupon.com/deals/gg-trym-=
ii-modern-hair-clipper-and-trimmer?p=3D7&utm_source=3Dcrm_im&utm_medium=3De=
mail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd=
2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0=
&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7d=
ca721587e9_0_20161112" target=3D"_blank" style=3D"text-decoration:none;"> <=
table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-s=
pacing:0; font-family: Helvetica, Arial, sans-serif; color:#000000; font-we=
ight: 100; background: #ffffff; width:290px;" valign=3D"top" class=3D"inner=
_container"align=3D'right'> <tr> <td style=3D"width:290px;" align=3D"center=
" valign=3D"top"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"borde=
r: 0 none; border-spacing:0; font-family: Helvetica, Arial, sans-serif; col=
or:#000000; font-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td v=
align=3D"top" align=3D"center" width=3D"290" style=3D"width:290px;" class=
=3D"inner_container"><a href=3D"https://www.groupon.com/deals/gg-trym-ii-mo=
dern-hair-clipper-and-trimmer?p=3D7&utm_source=3Dcrm_im&utm_medium=3Demail&=
user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&dat=
e=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3D=
body&c=3Dimage&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca7215=
87e9_0_20161112" style=3D"display: block; border: none;" target=3D"_blank">=
<img src=3D"https://img.grouponcdn.com/deal/acGkwxJ4JiUgjrvzT2fP/jF-960x576=
/v1/c300x182.jpg" width=3D"290" style=3D"display: block; border: none; widt=
h: 290px;" class=3D"secondary-100" alt=3D"Trym II Modern Beard and Hair-Cli=
pper Kit and Nose-Hair Trimmer" /></a></td> </tr> <tr> <td style=3D"padding=
:16px;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none=
; border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#00000=
0; font-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td colspan=3D=
"2" class=3D"nameFont" style=3D"font-size: 14px !important; line-height: 18=
px !important; color:#000000 !important; text-decoration: none; color: #333=
333 !important; width:100%;" align=3D"left" valign=3D"top"> Trym II Modern =
Hair-Clipper Kit </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" val=
ign=3D"top"><a href=3D"https://www.groupon.com/deals/gg-trym-ii-modern-hair=
-clipper-and-trimmer?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8=
bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161=
112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3D=
button&d=3DMindstorm-Hero-3-deals&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7d=
ca721587e9_0_20161112" target=3D"_blank" style=3D"font-size: 14px !importan=
t; line-height: 18px !important; color:#000000 !important; text-decoration:=
 none;"><font color=3D"#e35205">Over 10,000 bought</font></a></td> </tr> <t=
r> <td width=3D"70%" align=3D"left"> <span valign=3D"top" style=3D"padding-=
right: 5px; font-family: Helvetica, Arial, sans-serif; font-size: 16px !imp=
ortant; line-height: 20px !important; text-decoration: line-through; color:=
#848484 !important; font-weight: 100;" class=3D"nameFont">$39.99</span> <sp=
an align=3D"left" valign=3D"top" style=3D"font-family: Helvetica, Arial, sa=
ns-serif; font-size: 16px !important; line-height: 20px !important; font-we=
ight: 300; text-decoration: none; color: #e35205;" class=3D"nameFont">$17.9=
9</span> </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"t=
op" style=3D"font-family: Helvetica, Arial, sans-serif; font-size: 13px; co=
lor: #e35205; text-decoration: none; font-weight: 500 !important;">Sale End=
s 11/13</td> <td width=3D"30%" class=3D"nameFont" align=3D"right" valign=3D=
"top" style=3D"font-family: Helvetica, Arial, sans-serif; font-size: 13px !=
important; line-height: 17px !important; font-weight: normal; font-weight: =
600; color: #0185c6 !important; text-decoration: none; text-align:right; wh=
ite-space: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-trym-ii-mod=
ern-hair-clipper-and-trimmer?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&u=
ser=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=
=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Db=
ody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca7215=
87e9_0_20161112" target=3D"_blank" style=3D"text-decoration:none;"><font co=
lor=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </table> </td> </tr> <=
tr> <td style=3D"width: 10px; background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp=
;&nbsp;</td> </tr> </table> </td> </tr> </table> </a> <!--[if (gte mso 9)|(=
IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--=
[if (gte mso 9)|(IE)]> </tr> </table> <![endif]--> </tr> <tr> <td valign=3D=
"top" align=3D"left" width=3D"100%" style=3D"width: 600px;" class=3D"inner_=
container"> <!--[if (gte mso 9)|(IE)]> <table width=3D"600" align=3D"center=
" cellpadding=3D"0" cellspacing=3D"0" border=3D"0"> <tr> <![endif]--> <!--[=
if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https://www.groupon.com/=
deals/gg-sports-camera?p=3D8&utm_source=3Dcrm_im&utm_medium=3Demail&user=3D=
d8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D201=
61112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=
=3Dbutton&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_=
0_20161112" target=3D"_blank" style=3D"text-decoration:none;"> <table cellp=
adding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; f=
ont-family: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; =
background: #ffffff; width:290px;" valign=3D"top" class=3D"inner_container"=
align=3D'left'> <tr> <td style=3D"width:290px;" align=3D"center" valign=3D"=
top"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; b=
order-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#000000; =
font-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td valign=3D"top=
" align=3D"center" width=3D"290" style=3D"width:290px;" class=3D"inner_cont=
ainer"><a href=3D"https://www.groupon.com/deals/gg-sports-camera?p=3D8&utm_=
source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8=
f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c=
0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=
=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" style=3D"display: block=
; border: none;" target=3D"_blank"><img src=3D"https://img.grouponcdn.com/d=
eal/2TgdkDS3ezYDUq31gTk3ehW2zzhZ/2T-1000x600/v1/c300x182.jpg" width=3D"290"=
 style=3D"display: block; border: none; width: 290px;" class=3D"secondary-1=
00" alt=3D"XtremePro HD 720p Sports Camera Bundle with Mounts & Accessories=
" /></a></td> </tr> <tr> <td style=3D"padding:16px;"> <table cellpadding=3D=
"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-famil=
y: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; backgroun=
d: #f2f2f2; width:100%;"> <tr> <td colspan=3D"2" class=3D"nameFont" style=
=3D"font-size: 14px !important; line-height: 18px !important; color:#000000=
 !important; text-decoration: none; color: #333333 !important; width:100%;"=
 align=3D"left" valign=3D"top"> XtremePro HD 720p Sports Camera </td> </tr>=
 <tr> <td class=3D"nameFont" align=3D"left" valign=3D"top"><a href=3D"https=
://www.groupon.com/deals/gg-sports-camera?p=3D2&utm_source=3Dcrm_im&utm_med=
ium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf3865=
61ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS=
&tx=3D0&s=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-deals&utm_campaign=3Db5ac8=
9a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_blank" style=3D"font=
-size: 14px !important; line-height: 18px !important; color:#000000 !import=
ant; text-decoration: none;"><font color=3D"#e35205">Over 550 bought</font>=
</a></td> </tr> <tr> <td width=3D"70%" align=3D"left"> <span valign=3D"top"=
 style=3D"padding-right: 5px; font-family: Helvetica, Arial, sans-serif; fo=
nt-size: 16px !important; line-height: 20px !important; text-decoration: li=
ne-through; color:#848484 !important; font-weight: 100;" class=3D"nameFont"=
>$329.99</span> <span align=3D"left" valign=3D"top" style=3D"font-family: H=
elvetica, Arial, sans-serif; font-size: 16px !important; line-height: 20px =
!important; font-weight: 300; text-decoration: none; color: #e35205;" class=
=3D"nameFont">$69.99</span> </td> </tr> <tr> <td class=3D"nameFont" align=
=3D"left" valign=3D"top" style=3D"font-family: Helvetica, Arial, sans-serif=
; font-size: 13px; color: #e35205; text-decoration: none; font-weight: 500 =
!important;">Sale Ends 11/12</td> <td width=3D"30%" class=3D"nameFont" alig=
n=3D"right" valign=3D"top" style=3D"font-family: Helvetica, Arial, sans-ser=
if; font-size: 13px !important; line-height: 17px !important; font-weight: =
normal; font-weight: 600; color: #0185c6 !important; text-decoration: none;=
 text-align:right; white-space: nowrap;"><a href=3D"https://www.groupon.com=
/deals/gg-sports-camera?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=
=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D=
20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody=
&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e=
9_0_20161112" target=3D"_blank" style=3D"text-decoration:none;"><font color=
=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </table> </td> </tr> <tr>=
 <td style=3D"width: 10px; background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&n=
bsp;</td> </tr> </table> </td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)=
]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=
=3D"https://www.groupon.com/deals/gg-harman-kardon-onyx-studio-3-wireless-s=
peaker-system?p=3D9&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8b=
f03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=
=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton=
&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_2016111=
2" target=3D"_blank" style=3D"text-decoration:none;"> <table cellpadding=3D=
"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-famil=
y: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; backgroun=
d: #ffffff; width:290px;" valign=3D"top" class=3D"inner_container"align=3D'=
right'> <tr> <td style=3D"width:290px;" align=3D"center" valign=3D"top"> <t=
able cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-sp=
acing:0; font-family: Helvetica, Arial, sans-serif; color:#000000; font-wei=
ght: 100; background: #f2f2f2; width:100%;"> <tr> <td valign=3D"top" align=
=3D"center" width=3D"290" style=3D"width:290px;" class=3D"inner_container">=
<a href=3D"https://www.groupon.com/deals/gg-harman-kardon-onyx-studio-3-wir=
eless-speaker-system?p=3D9&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8=
bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161=
112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3D=
image&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20=
161112" style=3D"display: block; border: none;" target=3D"_blank"><img src=
=3D"https://img.grouponcdn.com/deal/244FBGwqmGS2y45Qz8M2QhXbzpeb/24-960x576=
/v1/c300x182.jpg" width=3D"290" style=3D"display: block; border: none; widt=
h: 290px;" class=3D"secondary-100" alt=3D"Harman Kardon Onyx Studio 3 Wirel=
ess Bluetooth Speaker" /></a></td> </tr> <tr> <td style=3D"padding:16px;"> =
<table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-=
spacing:0; font-family: Helvetica, Arial, sans-serif; color:#000000; font-w=
eight: 100; background: #f2f2f2; width:100%;"> <tr> <td colspan=3D"2" class=
=3D"nameFont" style=3D"font-size: 14px !important; line-height: 18px !impor=
tant; color:#000000 !important; text-decoration: none; color: #333333 !impo=
rtant; width:100%;" align=3D"left" valign=3D"top"> Harman Kardon Bluetooth =
Speaker </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"to=
p"><a href=3D"https://www.groupon.com/deals/gg-harman-kardon-onyx-studio-3-=
wireless-speaker-system?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=
=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D=
20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody=
&c=3Dbutton&d=3DMindstorm-Hero-3-deals&utm_campaign=3Db5ac89a0-e1ee-4fec-b0=
f0-7dca721587e9_0_20161112" target=3D"_blank" style=3D"font-size: 14px !imp=
ortant; line-height: 18px !important; color:#000000 !important; text-decora=
tion: none;"><font color=3D"#e35205">Over 1,000 bought</font></a></td> </tr=
> <tr> <td width=3D"70%" align=3D"left"> <span valign=3D"top" style=3D"padd=
ing-right: 5px; font-family: Helvetica, Arial, sans-serif; font-size: 16px =
!important; line-height: 20px !important; text-decoration: line-through; co=
lor:#848484 !important; font-weight: 100;" class=3D"nameFont">$499.99</span=
> <span align=3D"left" valign=3D"top" style=3D"font-family: Helvetica, Aria=
l, sans-serif; font-size: 16px !important; line-height: 20px !important; fo=
nt-weight: 300; text-decoration: none; color: #e35205;" class=3D"nameFont">=
$129.99</span> </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valig=
n=3D"top" style=3D"font-family: Helvetica, Arial, sans-serif; font-size: 13=
px; color: #e35205; text-decoration: none; font-weight: 500 !important;">Sa=
le Ends 11/12</td> <td width=3D"30%" class=3D"nameFont" align=3D"right" val=
ign=3D"top" style=3D"font-family: Helvetica, Arial, sans-serif; font-size: =
13px !important; line-height: 17px !important; font-weight: normal; font-we=
ight: 600; color: #0185c6 !important; text-decoration: none; text-align:rig=
ht; white-space: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-harma=
n-kardon-onyx-studio-3-wireless-speaker-system?p=3D2&utm_source=3Dcrm_im&ut=
m_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134c=
f386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=
=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-=
4fec-b0f0-7dca721587e9_0_20161112" target=3D"_blank" style=3D"text-decorati=
on:none;"><font color=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </ta=
ble> </td> </tr> <tr> <td style=3D"width: 10px; background: #ffffff;">&nbsp=
;&nbsp;&nbsp;&nbsp;&nbsp;</td> </tr> </table> </td> </tr> </table> </a> <!-=
-[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </td>=
 <![endif]--> <!--[if (gte mso 9)|(IE)]> </tr> </table> <![endif]--> </tr> =
<tr> <td valign=3D"top" align=3D"left" width=3D"100%" style=3D"width: 600px=
;" class=3D"inner_container"> <!--[if (gte mso 9)|(IE)]> <table width=3D"60=
0" align=3D"center" cellpadding=3D"0" cellspacing=3D"0" border=3D"0"> <tr> =
<![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https:=
//www.groupon.com/deals/gg-nfl-round-distressed-sign-3?p=3D10&utm_source=3D=
crm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c=
2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-0025906=
9d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Db5ac8=
9a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_blank" style=3D"text=
-decoration:none;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"bor=
der: 0 none; border-spacing:0; font-family: Helvetica, Arial, sans-serif; c=
olor:#000000; font-weight: 100; background: #ffffff; width:290px;" valign=
=3D"top" class=3D"inner_container"align=3D'left'> <tr> <td style=3D"width:2=
90px;" align=3D"center" valign=3D"top"> <table cellpadding=3D"0" cellspacin=
g=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Helvetica, =
Arial, sans-serif; color:#000000; font-weight: 100; background: #f2f2f2; wi=
dth:100%;"> <tr> <td valign=3D"top" align=3D"center" width=3D"290" style=3D=
"width:290px;" class=3D"inner_container"><a href=3D"https://www.groupon.com=
/deals/gg-nfl-round-distressed-sign-3?p=3D10&utm_source=3Dcrm_im&utm_medium=
=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561e=
d8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=
=3D0&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0=
-7dca721587e9_0_20161112" style=3D"display: block; border: none;" target=3D=
"_blank"><img src=3D"https://img.grouponcdn.com/deal/ivoXuEA1Eh1f397kDc5f/5=
m-960x576/v1/c300x182.jpg" width=3D"290" style=3D"display: block; border: n=
one; width: 290px;" class=3D"secondary-100" alt=3D"NFL Round Distressed Sig=
n" /></a></td> </tr> <tr> <td style=3D"padding:16px;"> <table cellpadding=
=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-fa=
mily: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; backgr=
ound: #f2f2f2; width:100%;"> <tr> <td colspan=3D"2" class=3D"nameFont" styl=
e=3D"font-size: 14px !important; line-height: 18px !important; color:#00000=
0 !important; text-decoration: none; color: #333333 !important; width:100%;=
" align=3D"left" valign=3D"top"> NFL Round Distressed Sign </td> </tr> <tr>=
 <td class=3D"nameFont" align=3D"left" valign=3D"top"><a href=3D"https://ww=
w.groupon.com/deals/gg-nfl-round-distressed-sign-3?p=3D2&utm_source=3Dcrm_i=
m&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac=
134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe=
&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-deals&utm_campaig=
n=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_blank" styl=
e=3D"font-size: 14px !important; line-height: 18px !important; color:#00000=
0 !important; text-decoration: none;"><font color=3D"#e35205">Over 10,000 b=
ought</font></a></td> </tr> <tr> <td width=3D"70%" align=3D"left"> <span va=
lign=3D"top" style=3D"padding-right: 5px; font-family: Helvetica, Arial, sa=
ns-serif; font-size: 16px !important; line-height: 20px !important; text-de=
coration: line-through; color:#848484 !important; font-weight: 100;" class=
=3D"nameFont">$39.99</span> <span align=3D"left" valign=3D"top" style=3D"fo=
nt-family: Helvetica, Arial, sans-serif; font-size: 16px !important; line-h=
eight: 20px !important; font-weight: 300; text-decoration: none; color: #e3=
5205;" class=3D"nameFont">$28.99</span> </td> </tr> <tr> <td class=3D"nameF=
ont" align=3D"left" valign=3D"top" style=3D"font-family: Helvetica, Arial, =
sans-serif; font-size: 13px; color: #e35205; text-decoration: none; font-we=
ight: 500 !important;">Sale Ends 11/12</td> <td width=3D"30%" class=3D"name=
Font" align=3D"right" valign=3D"top" style=3D"font-family: Helvetica, Arial=
, sans-serif; font-size: 13px !important; line-height: 17px !important; fon=
t-weight: normal; font-weight: 600; color: #0185c6 !important; text-decorat=
ion: none; text-align:right; white-space: nowrap;"><a href=3D"https://www.g=
roupon.com/deals/gg-nfl-round-distressed-sign-3?p=3D2&utm_source=3Dcrm_im&u=
tm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134=
cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CI=
D=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee=
-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_blank" style=3D"text-decorat=
ion:none;"><font color=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </t=
able> </td> </tr> <tr> <td style=3D"width: 10px; background: #ffffff;">&nbs=
p;&nbsp;&nbsp;&nbsp;&nbsp;</td> </tr> </table> </td> </tr> </table> </a> <!=
--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td>=
 <![endif]--> <a href=3D"https://www.groupon.com/deals/gg-samsung-galaxy-s5=
-16gb-4g-lte-smartphone-1?p=3D11&utm_source=3Dcrm_im&utm_medium=3Demail&use=
r=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=
=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Db=
ody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca7215=
87e9_0_20161112" target=3D"_blank" style=3D"text-decoration:none;"> <table =
cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing=
:0; font-family: Helvetica, Arial, sans-serif; color:#000000; font-weight: =
100; background: #ffffff; width:290px;" valign=3D"top" class=3D"inner_conta=
iner"align=3D'right'> <tr> <td style=3D"width:290px;" align=3D"center" vali=
gn=3D"top"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 n=
one; border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#00=
0000; font-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td valign=
=3D"top" align=3D"center" width=3D"290" style=3D"width:290px;" class=3D"inn=
er_container"><a href=3D"https://www.groupon.com/deals/gg-samsung-galaxy-s5=
-16gb-4g-lte-smartphone-1?p=3D11&utm_source=3Dcrm_im&utm_medium=3Demail&use=
r=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=
=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Db=
ody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca72158=
7e9_0_20161112" style=3D"display: block; border: none;" target=3D"_blank"><=
img src=3D"https://img.grouponcdn.com/deal/72D2jsUVDMkeiPZCH7Nx/eK-700x420/=
v1/c300x182.jpg" width=3D"290" style=3D"display: block; border: none; width=
: 290px;" class=3D"secondary-100" alt=3D"Samsung Galaxy S5 16GB 4G LTE Smar=
tphone for Verizon (GSM Unlocked)" /></a></td> </tr> <tr> <td style=3D"padd=
ing:16px;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 n=
one; border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#00=
0000; font-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td colspan=
=3D"2" class=3D"nameFont" style=3D"font-size: 14px !important; line-height:=
 18px !important; color:#000000 !important; text-decoration: none; color: #=
333333 !important; width:100%;" align=3D"left" valign=3D"top"> Samsung Gala=
xy S5 16GB </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D=
"top"><a href=3D"https://www.groupon.com/deals/gg-samsung-galaxy-s5-16gb-4g=
-lte-smartphone-1?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd=
7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112=
&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbut=
ton&d=3DMindstorm-Hero-3-deals&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca7=
21587e9_0_20161112" target=3D"_blank" style=3D"font-size: 14px !important; =
line-height: 18px !important; color:#000000 !important; text-decoration: no=
ne;"><font color=3D"#e35205">Over 1,000 bought</font></a></td> </tr> <tr> <=
td width=3D"70%" align=3D"left"> <span valign=3D"top" style=3D"padding-righ=
t: 5px; font-family: Helvetica, Arial, sans-serif; font-size: 16px !importa=
nt; line-height: 20px !important; text-decoration: line-through; color:#848=
484 !important; font-weight: 100;" class=3D"nameFont">$552</span> <span ali=
gn=3D"left" valign=3D"top" style=3D"font-family: Helvetica, Arial, sans-ser=
if; font-size: 16px !important; line-height: 20px !important; font-weight: =
300; text-decoration: none; color: #e35205;" class=3D"nameFont">$129.99</sp=
an> </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"top" s=
tyle=3D"font-family: Helvetica, Arial, sans-serif; font-size: 13px; color: =
#e35205; text-decoration: none; font-weight: 500 !important;">Sale Ends 11/=
14</td> <td width=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top"=
 style=3D"font-family: Helvetica, Arial, sans-serif; font-size: 13px !impor=
tant; line-height: 17px !important; font-weight: normal; font-weight: 600; =
color: #0185c6 !important; text-decoration: none; text-align:right; white-s=
pace: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-samsung-galaxy-s=
5-16gb-4g-lte-smartphone-1?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&use=
r=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=
=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Db=
ody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca7215=
87e9_0_20161112" target=3D"_blank" style=3D"text-decoration:none;"><font co=
lor=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </table> </td> </tr> <=
tr> <td style=3D"width: 10px; background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp=
;&nbsp;</td> </tr> </table> </td> </tr> </table> </a> <!--[if (gte mso 9)|(=
IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--=
[if (gte mso 9)|(IE)]> </tr> </table> <![endif]--> </tr> <tr> <td valign=3D=
"top" align=3D"left" width=3D"100%" style=3D"width: 600px;" class=3D"inner_=
container"> <!--[if (gte mso 9)|(IE)]> <table width=3D"600" align=3D"center=
" cellpadding=3D"0" cellspacing=3D"0" border=3D"0"> <tr> <![endif]--> <!--[=
if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https://www.groupon.com/=
deals/gg-best-of-chi-flat-irons?p=3D12&utm_source=3Dcrm_im&utm_medium=3Dema=
il&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&=
date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=
=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca=
721587e9_0_20161112" target=3D"_blank" style=3D"text-decoration:none;"> <ta=
ble cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spa=
cing:0; font-family: Helvetica, Arial, sans-serif; color:#000000; font-weig=
ht: 100; background: #ffffff; width:290px;" valign=3D"top" class=3D"inner_c=
ontainer"align=3D'left'> <tr> <td style=3D"width:290px;" align=3D"center" v=
align=3D"top"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: =
0 none; border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:=
#000000; font-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td vali=
gn=3D"top" align=3D"center" width=3D"290" style=3D"width:290px;" class=3D"i=
nner_container"><a href=3D"https://www.groupon.com/deals/gg-best-of-chi-fla=
t-irons?p=3D12&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf=
574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79=
c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dimage&d=3DGo=
ods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" styl=
e=3D"display: block; border: none;" target=3D"_blank"><img src=3D"https://i=
mg.grouponcdn.com/deal/2R52WFKT1vQ5bhyuBuvT5qmUi3FN/2R-2048x1229/v1/c300x18=
2.jpg" width=3D"290" style=3D"display: block; border: none; width: 290px;" =
class=3D"secondary-100" alt=3D"Best of CHI Irons and Hair Treatments" /></a=
></td> </tr> <tr> <td style=3D"padding:16px;"> <table cellpadding=3D"0" cel=
lspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Helv=
etica, Arial, sans-serif; color:#000000; font-weight: 100; background: #f2f=
2f2; width:100%;"> <tr> <td colspan=3D"2" class=3D"nameFont" style=3D"font-=
size: 14px !important; line-height: 18px !important; color:#000000 !importa=
nt; text-decoration: none; color: #333333 !important; width:100%;" align=3D=
"left" valign=3D"top"> CHI Irons and Hair Treatments </td> </tr> <tr> <td c=
lass=3D"nameFont" align=3D"left" valign=3D"top"><a href=3D"https://www.grou=
pon.com/deals/gg-best-of-chi-flat-irons?p=3D2&utm_source=3Dcrm_im&utm_mediu=
m=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561=
ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&t=
x=3D0&s=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-deals&utm_campaign=3Db5ac89a=
0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_blank" style=3D"font-s=
ize: 14px !important; line-height: 18px !important; color:#000000 !importan=
t; text-decoration: none;"><font color=3D"#e35205">Over 400 bought</font></=
a></td> </tr> <tr> <td width=3D"70%" align=3D"left"> <span valign=3D"top" s=
tyle=3D"padding-right: 5px; font-family: Helvetica, Arial, sans-serif; font=
-size: 16px !important; line-height: 20px !important; text-decoration: line=
-through; color:#848484 !important; font-weight: 100;" class=3D"nameFont">$=
14.99</span> <span align=3D"left" valign=3D"top" style=3D"font-family: Helv=
etica, Arial, sans-serif; font-size: 16px !important; line-height: 20px !im=
portant; font-weight: 300; text-decoration: none; color: #e35205;" class=3D=
"nameFont">$11.99</span> </td> </tr> <tr> <td class=3D"nameFont" align=3D"l=
eft" valign=3D"top" style=3D"font-family: Helvetica, Arial, sans-serif; fon=
t-size: 13px; color: #e35205; text-decoration: none; font-weight: 500 !impo=
rtant;">Sale Ends 11/12</td> <td width=3D"30%" class=3D"nameFont" align=3D"=
right" valign=3D"top" style=3D"font-family: Helvetica, Arial, sans-serif; f=
ont-size: 13px !important; line-height: 17px !important; font-weight: norma=
l; font-weight: 600; color: #0185c6 !important; text-decoration: none; text=
-align:right; white-space: nowrap;"><a href=3D"https://www.groupon.com/deal=
s/gg-best-of-chi-flat-irons?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&us=
er=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=
=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Db=
ody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca7215=
87e9_0_20161112" target=3D"_blank" style=3D"text-decoration:none;"><font co=
lor=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </table> </td> </tr> <=
tr> <td style=3D"width: 10px; background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp=
;&nbsp;</td> </tr> </table> </td> </tr> </table> </a> <!--[if (gte mso 9)|(=
IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a hr=
ef=3D"https://www.groupon.com/deals/gg-roku-4-streaming-player-4k-uhd?p=3D1=
3&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070=
ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11=
e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_c=
ampaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_blank=
" style=3D"text-decoration:none;"> <table cellpadding=3D"0" cellspacing=3D"=
0" style=3D"border: 0 none; border-spacing:0; font-family: Helvetica, Arial=
, sans-serif; color:#000000; font-weight: 100; background: #ffffff; width:2=
90px;" valign=3D"top" class=3D"inner_container"align=3D'right'> <tr> <td st=
yle=3D"width:290px;" align=3D"center" valign=3D"top"> <table cellpadding=3D=
"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-famil=
y: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; backgroun=
d: #f2f2f2; width:100%;"> <tr> <td valign=3D"top" align=3D"center" width=3D=
"290" style=3D"width:290px;" class=3D"inner_container"><a href=3D"https://w=
ww.groupon.com/deals/gg-roku-4-streaming-player-4k-uhd?p=3D13&utm_source=3D=
crm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c=
2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-0025906=
9d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Db5ac89=
a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" style=3D"display: block; border:=
 none;" target=3D"_blank"><img src=3D"https://img.grouponcdn.com/deal/3RHhh=
xsG3TjBZyK6N6WE1vCREwz9/3R-1000x600/v1/c300x182.jpg" width=3D"290" style=3D=
"display: block; border: none; width: 290px;" class=3D"secondary-100" alt=
=3D"Roku 4 Streaming Player 4K UHD" /></a></td> </tr> <tr> <td style=3D"pad=
ding:16px;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 =
none; border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#0=
00000; font-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td colspa=
n=3D"2" class=3D"nameFont" style=3D"font-size: 14px !important; line-height=
: 18px !important; color:#000000 !important; text-decoration: none; color: =
#333333 !important; width:100%;" align=3D"left" valign=3D"top"> Roku 4 Stre=
aming Player 4K UHD </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" =
valign=3D"top"><a href=3D"https://www.groupon.com/deals/gg-roku-4-streaming=
-player-4k-uhd?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8=
bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=
=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton=
&d=3DMindstorm-Hero-3-deals&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca7215=
87e9_0_20161112" target=3D"_blank" style=3D"font-size: 14px !important; lin=
e-height: 18px !important; color:#000000 !important; text-decoration: none;=
"><font color=3D"#e35205">Over 750 bought</font></a></td> </tr> <tr> <td wi=
dth=3D"70%" align=3D"left"> <span valign=3D"top" style=3D"padding-right: 5p=
x; font-family: Helvetica, Arial, sans-serif; font-size: 16px !important; l=
ine-height: 20px !important; text-decoration: line-through; color:#848484 !=
important; font-weight: 100;" class=3D"nameFont">$129.99</span> <span align=
=3D"left" valign=3D"top" style=3D"font-family: Helvetica, Arial, sans-serif=
; font-size: 16px !important; line-height: 20px !important; font-weight: 30=
0; text-decoration: none; color: #e35205;" class=3D"nameFont">$89.99</span>=
 </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"top" styl=
e=3D"font-family: Helvetica, Arial, sans-serif; font-size: 13px; color: #e3=
5205; text-decoration: none; font-weight: 500 !important;">Sale Ends 11/12<=
/td> <td width=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" st=
yle=3D"font-family: Helvetica, Arial, sans-serif; font-size: 13px !importan=
t; line-height: 17px !important; font-weight: normal; font-weight: 600; col=
or: #0185c6 !important; text-decoration: none; text-align:right; white-spac=
e: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-roku-4-streaming-pl=
ayer-4k-uhd?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf0=
3cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3D=
f79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=
=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112"=
 target=3D"_blank" style=3D"text-decoration:none;"><font color=3D"#0185c6">=
View&nbsp;Deal</font></a></td> </tr> </table> </td> </tr> <tr> <td style=3D=
"width: 10px; background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> </t=
r> </table> </td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![e=
ndif]--> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|=
(IE)]> </tr> </table> <![endif]--> </tr> <tr> <td valign=3D"top" align=3D"l=
eft" width=3D"100%" style=3D"width: 600px;" class=3D"inner_container"> <!--=
[if (gte mso 9)|(IE)]> <table width=3D"600" align=3D"center" cellpadding=3D=
"0" cellspacing=3D"0" border=3D"0"> <tr> <![endif]--> <!--[if (gte mso 9)|(=
IE)]> <td> <![endif]--> <a href=3D"https://www.groupon.com/deals/gg-verdi-c=
harged-up-hardside-carry-on?p=3D14&utm_source=3Dcrm_im&utm_medium=3Demail&u=
ser=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=
=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Db=
ody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca7215=
87e9_0_20161112" target=3D"_blank" style=3D"text-decoration:none;"> <table =
cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing=
:0; font-family: Helvetica, Arial, sans-serif; color:#000000; font-weight: =
100; background: #ffffff; width:290px;" valign=3D"top" class=3D"inner_conta=
iner"align=3D'left'> <tr> <td style=3D"width:290px;" align=3D"center" valig=
n=3D"top"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 no=
ne; border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#000=
000; font-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td valign=
=3D"top" align=3D"center" width=3D"290" style=3D"width:290px;" class=3D"inn=
er_container"><a href=3D"https://www.groupon.com/deals/gg-verdi-charged-up-=
hardside-carry-on?p=3D14&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bf=
d7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D2016111=
2&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dim=
age&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_2016=
1112" style=3D"display: block; border: none;" target=3D"_blank"><img src=3D=
"https://img.grouponcdn.com/deal/2x3GMBx1Xk2pbNjo3GChJ5oPu9RD/2x-1400x840/v=
1/c300x182.jpg" width=3D"290" style=3D"display: block; border: none; width:=
 290px;" class=3D"secondary-100" alt=3D"Verdi 22" Hardside Spinner Carry-on=
 Luggage" /></a></td> </tr> <tr> <td style=3D"padding:16px;"> <table cellpa=
dding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; fo=
nt-family: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; b=
ackground: #f2f2f2; width:100%;"> <tr> <td colspan=3D"2" class=3D"nameFont"=
 style=3D"font-size: 14px !important; line-height: 18px !important; color:#=
000000 !important; text-decoration: none; color: #333333 !important; width:=
100%;" align=3D"left" valign=3D"top"> Verdi 22" Hardside Carry-on </td> </t=
r> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"top"><a href=3D"htt=
ps://www.groupon.com/deals/gg-verdi-charged-up-hardside-carry-on?p=3D2&utm_=
source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8=
f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c=
0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-dea=
ls&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" target=
=3D"_blank" style=3D"font-size: 14px !important; line-height: 18px !importa=
nt; color:#000000 !important; text-decoration: none;"><font color=3D"#e3520=
5">Over 1,000 bought</font></a></td> </tr> <tr> <td width=3D"70%" align=3D"=
left"> <span valign=3D"top" style=3D"padding-right: 5px; font-family: Helve=
tica, Arial, sans-serif; font-size: 16px !important; line-height: 20px !imp=
ortant; text-decoration: line-through; color:#848484 !important; font-weigh=
t: 100;" class=3D"nameFont">$179.99</span> <span align=3D"left" valign=3D"t=
op" style=3D"font-family: Helvetica, Arial, sans-serif; font-size: 16px !im=
portant; line-height: 20px !important; font-weight: 300; text-decoration: n=
one; color: #e35205;" class=3D"nameFont">$29.99</span> </td> </tr> <tr> <td=
 class=3D"nameFont" align=3D"left" valign=3D"top" style=3D"font-family: Hel=
vetica, Arial, sans-serif; font-size: 13px; color: #e35205; text-decoration=
: none; font-weight: 500 !important;">Sale Ends 11/13</td> <td width=3D"30%=
" class=3D"nameFont" align=3D"right" valign=3D"top" style=3D"font-family: H=
elvetica, Arial, sans-serif; font-size: 13px !important; line-height: 17px =
!important; font-weight: normal; font-weight: 600; color: #0185c6 !importan=
t; text-decoration: none; text-align:right; white-space: nowrap;"><a href=
=3D"https://www.groupon.com/deals/gg-verdi-charged-up-hardside-carry-on?p=
=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822=
070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539=
-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&ut=
m_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_bl=
ank" style=3D"text-decoration:none;"><font color=3D"#0185c6">View&nbsp;Deal=
</font></a></td> </tr> </table> </td> </tr> <tr> <td style=3D"width: 10px; =
background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> </tr> </table> </=
td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[=
if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https://www.groupon.com/=
deals/gg-rachael-ray-cucina-hard-enamel-nonstick-cookware-set-2?p=3D15&utm_=
source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8=
f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c=
0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaig=
n=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_blank" styl=
e=3D"text-decoration:none;"> <table cellpadding=3D"0" cellspacing=3D"0" sty=
le=3D"border: 0 none; border-spacing:0; font-family: Helvetica, Arial, sans=
-serif; color:#000000; font-weight: 100; background: #ffffff; width:290px;"=
 valign=3D"top" class=3D"inner_container"align=3D'right'> <tr> <td style=3D=
"width:290px;" align=3D"center" valign=3D"top"> <table cellpadding=3D"0" ce=
llspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Hel=
vetica, Arial, sans-serif; color:#000000; font-weight: 100; background: #f2=
f2f2; width:100%;"> <tr> <td valign=3D"top" align=3D"center" width=3D"290" =
style=3D"width:290px;" class=3D"inner_container"><a href=3D"https://www.gro=
upon.com/deals/gg-rachael-ray-cucina-hard-enamel-nonstick-cookware-set-2?p=
=3D15&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c82=
2070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-253=
9-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dimage&d=3DGoods-PN&ut=
m_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" style=3D"disp=
lay: block; border: none;" target=3D"_blank"><img src=3D"https://img.groupo=
ncdn.com/item_master/54LC2D6gpTevGqG5RFhjThTWwpN/54-5511x3674/v1/c300x182.j=
pg" width=3D"290" style=3D"display: block; border: none; width: 290px;" cla=
ss=3D"secondary-100" alt=3D"Rachael Ray Cucina Hard Enamel Nonstick Cookwar=
e Set (12-Piece)" /></a></td> </tr> <tr> <td style=3D"padding:16px;"> <tabl=
e cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spaci=
ng:0; font-family: Helvetica, Arial, sans-serif; color:#000000; font-weight=
: 100; background: #f2f2f2; width:100%;"> <tr> <td colspan=3D"2" class=3D"n=
ameFont" style=3D"font-size: 14px !important; line-height: 18px !important;=
 color:#000000 !important; text-decoration: none; color: #333333 !important=
; width:100%;" align=3D"left" valign=3D"top"> Rachael Ray Cookware (12-Pc.)=
 </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"top"><a h=
ref=3D"https://www.groupon.com/deals/gg-rachael-ray-cucina-hard-enamel-nons=
tick-cookware-set-2?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8b=
fd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D201611=
12&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Db=
utton&d=3DMindstorm-Hero-3-deals&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dc=
a721587e9_0_20161112" target=3D"_blank" style=3D"font-size: 14px !important=
; line-height: 18px !important; color:#000000 !important; text-decoration: =
none;"><font color=3D"#e35205">Over 400 bought</font></a></td> </tr> <tr> <=
td width=3D"70%" align=3D"left"> <span valign=3D"top" style=3D"padding-righ=
t: 5px; font-family: Helvetica, Arial, sans-serif; font-size: 16px !importa=
nt; line-height: 20px !important; text-decoration: line-through; color:#848=
484 !important; font-weight: 100;" class=3D"nameFont">$299.98</span> <span =
align=3D"left" valign=3D"top" style=3D"font-family: Helvetica, Arial, sans-=
serif; font-size: 16px !important; line-height: 20px !important; font-weigh=
t: 300; text-decoration: none; color: #e35205;" class=3D"nameFont">$99.99</=
span> </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"top"=
 style=3D"font-family: Helvetica, Arial, sans-serif; font-size: 13px; color=
: #e35205; text-decoration: none; font-weight: 500 !important;">Sale Ends 1=
1/13</td> <td width=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"to=
p" style=3D"font-family: Helvetica, Arial, sans-serif; font-size: 13px !imp=
ortant; line-height: 17px !important; font-weight: normal; font-weight: 600=
; color: #0185c6 !important; text-decoration: none; text-align:right; white=
-space: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-rachael-ray-cu=
cina-hard-enamel-nonstick-cookware-set-2?p=3D2&utm_source=3Dcrm_im&utm_medi=
um=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf38656=
1ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&=
tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b=
0f0-7dca721587e9_0_20161112" target=3D"_blank" style=3D"text-decoration:non=
e;"><font color=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </table> <=
/td> </tr> <tr> <td style=3D"width: 10px; background: #ffffff;">&nbsp;&nbsp=
;&nbsp;&nbsp;&nbsp;</td> </tr> </table> </td> </tr> </table> </a> <!--[if (=
gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </td> <![en=
dif]--> <!--[if (gte mso 9)|(IE)]> </tr> </table> <![endif]--> </tr> <tr> <=
td valign=3D"top" align=3D"left" width=3D"100%" style=3D"width: 600px;" cla=
ss=3D"inner_container"> <!--[if (gte mso 9)|(IE)]> <table width=3D"600" ali=
gn=3D"center" cellpadding=3D"0" cellspacing=3D"0" border=3D"0"> <tr> <![end=
if]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https://www.=
groupon.com/deals/gg-wexley-home-17m-fairy-lights?p=3D16&utm_source=3Dcrm_i=
m&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac=
134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe=
&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e=
1ee-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_blank" style=3D"text-deco=
ration:none;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: =
0 none; border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:=
#000000; font-weight: 100; background: #ffffff; width:290px;" valign=3D"top=
" class=3D"inner_container"align=3D'left'> <tr> <td style=3D"width:290px;" =
align=3D"center" valign=3D"top"> <table cellpadding=3D"0" cellspacing=3D"0"=
 style=3D"border: 0 none; border-spacing:0; font-family: Helvetica, Arial, =
sans-serif; color:#000000; font-weight: 100; background: #f2f2f2; width:100=
%;"> <tr> <td valign=3D"top" align=3D"center" width=3D"290" style=3D"width:=
290px;" class=3D"inner_container"><a href=3D"https://www.groupon.com/deals/=
gg-wexley-home-17m-fairy-lights?p=3D16&utm_source=3Dcrm_im&utm_medium=3Dema=
il&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&=
date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=
=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca7=
21587e9_0_20161112" style=3D"display: block; border: none;" target=3D"_blan=
k"><img src=3D"https://img.grouponcdn.com/deal/3gCQvCTnQKmACRZ4bdP2DVvtS9jK=
/3g-1400x840/v1/c300x182.jpg" width=3D"290" style=3D"display: block; border=
: none; width: 290px;" class=3D"secondary-100" alt=3D"Wexley Home Solar-Pow=
ered 100-LED White Fairy Lights" /></a></td> </tr> <tr> <td style=3D"paddin=
g:16px;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 non=
e; border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#0000=
00; font-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td colspan=
=3D"2" class=3D"nameFont" style=3D"font-size: 14px !important; line-height:=
 18px !important; color:#000000 !important; text-decoration: none; color: #=
333333 !important; width:100%;" align=3D"left" valign=3D"top"> Wexley Home =
White Fairy Lights </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" v=
align=3D"top"><a href=3D"https://www.groupon.com/deals/gg-wexley-home-17m-f=
airy-lights?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf0=
3cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3D=
f79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=
=3DMindstorm-Hero-3-deals&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587=
e9_0_20161112" target=3D"_blank" style=3D"font-size: 14px !important; line-=
height: 18px !important; color:#000000 !important; text-decoration: none;">=
<font color=3D"#e35205">Over 25,000 bought</font></a></td> </tr> <tr> <td w=
idth=3D"70%" align=3D"left"> <span valign=3D"top" style=3D"padding-right: 5=
px; font-family: Helvetica, Arial, sans-serif; font-size: 16px !important; =
line-height: 20px !important; text-decoration: line-through; color:#848484 =
!important; font-weight: 100;" class=3D"nameFont">$29.99</span> <span align=
=3D"left" valign=3D"top" style=3D"font-family: Helvetica, Arial, sans-serif=
; font-size: 16px !important; line-height: 20px !important; font-weight: 30=
0; text-decoration: none; color: #e35205;" class=3D"nameFont">$8.99</span> =
</td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"top" style=
=3D"font-family: Helvetica, Arial, sans-serif; font-size: 13px; color: #e35=
205; text-decoration: none; font-weight: 500 !important;">Sale Ends 11/13</=
td> <td width=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" sty=
le=3D"font-family: Helvetica, Arial, sans-serif; font-size: 13px !important=
; line-height: 17px !important; font-weight: normal; font-weight: 600; colo=
r: #0185c6 !important; text-decoration: none; text-align:right; white-space=
: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-wexley-home-17m-fair=
y-lights?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf=
574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79=
c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DG=
oods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" tar=
get=3D"_blank" style=3D"text-decoration:none;"><font color=3D"#0185c6">View=
&nbsp;Deal</font></a></td> </tr> </table> </td> </tr> <tr> <td style=3D"wid=
th: 10px; background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> </tr> <=
/table> </td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif=
]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https://www.gr=
oupon.com/deals/gg-pyle-widescreen-led-projector-with-1080p-full-hd-support=
-3?p=3D17&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf57433=
7c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c=
-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-=
PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" target=
=3D"_blank" style=3D"text-decoration:none;"> <table cellpadding=3D"0" cells=
pacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Helvet=
ica, Arial, sans-serif; color:#000000; font-weight: 100; background: #fffff=
f; width:290px;" valign=3D"top" class=3D"inner_container"align=3D'right'> <=
tr> <td style=3D"width:290px;" align=3D"center" valign=3D"top"> <table cell=
padding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; =
font-family: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100;=
 background: #f2f2f2; width:100%;"> <tr> <td valign=3D"top" align=3D"center=
" width=3D"290" style=3D"width:290px;" class=3D"inner_container"><a href=3D=
"https://www.groupon.com/deals/gg-pyle-widescreen-led-projector-with-1080p-=
full-hd-support-3?p=3D17&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bf=
d7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D2016111=
2&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dim=
age&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_2016=
1112" style=3D"display: block; border: none;" target=3D"_blank"><img src=3D=
"https://img.grouponcdn.com/deal/99hAwyewAYyjb1JNJMWo/KS-1090x654/v1/c300x1=
82.jpg" width=3D"290" style=3D"display: block; border: none; width: 290px;"=
 class=3D"secondary-100" alt=3D"Pyle Widescreen LED Projector with 1080p Fu=
ll HD Support" /></a></td> </tr> <tr> <td style=3D"padding:16px;"> <table c=
ellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:=
0; font-family: Helvetica, Arial, sans-serif; color:#000000; font-weight: 1=
00; background: #f2f2f2; width:100%;"> <tr> <td colspan=3D"2" class=3D"name=
Font" style=3D"font-size: 14px !important; line-height: 18px !important; co=
lor:#000000 !important; text-decoration: none; color: #333333 !important; w=
idth:100%;" align=3D"left" valign=3D"top"> Pyle Widescreen LED Projector </=
td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"top"><a href=
=3D"https://www.groupon.com/deals/gg-pyle-widescreen-led-projector-with-108=
0p-full-hd-support-3?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8=
bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161=
112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3D=
button&d=3DMindstorm-Hero-3-deals&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7d=
ca721587e9_0_20161112" target=3D"_blank" style=3D"font-size: 14px !importan=
t; line-height: 18px !important; color:#000000 !important; text-decoration:=
 none;"><font color=3D"#e35205">Over 5,000 bought</font></a></td> </tr> <tr=
> <td width=3D"70%" align=3D"left"> <span valign=3D"top" style=3D"padding-r=
ight: 5px; font-family: Helvetica, Arial, sans-serif; font-size: 16px !impo=
rtant; line-height: 20px !important; text-decoration: line-through; color:#=
848484 !important; font-weight: 100;" class=3D"nameFont">$319.99</span> <sp=
an align=3D"left" valign=3D"top" style=3D"font-family: Helvetica, Arial, sa=
ns-serif; font-size: 16px !important; line-height: 20px !important; font-we=
ight: 300; text-decoration: none; color: #e35205;" class=3D"nameFont">$169.=
99</span> </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"=
top" style=3D"font-family: Helvetica, Arial, sans-serif; font-size: 13px; c=
olor: #e35205; text-decoration: none; font-weight: 500 !important;">Sale En=
ds 11/12</td> <td width=3D"30%" class=3D"nameFont" align=3D"right" valign=
=3D"top" style=3D"font-family: Helvetica, Arial, sans-serif; font-size: 13p=
x !important; line-height: 17px !important; font-weight: normal; font-weigh=
t: 600; color: #0185c6 !important; text-decoration: none; text-align:right;=
 white-space: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-pyle-wid=
escreen-led-projector-with-1080p-full-hd-support-3?p=3D2&utm_source=3Dcrm_i=
m&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac=
134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe=
&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e=
1ee-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_blank" style=3D"text-deco=
ration:none;"><font color=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> =
</table> </td> </tr> <tr> <td style=3D"width: 10px; background: #ffffff;">&=
nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> </tr> </table> </td> </tr> </table> </a>=
 <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> <=
/td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </tr> </table> <![endif]--> </=
tr> <tr> <td valign=3D"top" align=3D"left" width=3D"100%" style=3D"width: 6=
00px;" class=3D"inner_container"> <!--[if (gte mso 9)|(IE)]> <table width=
=3D"600" align=3D"center" cellpadding=3D"0" cellspacing=3D"0" border=3D"0">=
 <tr> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"=
https://www.groupon.com/deals/gg-olive-street-heavyweight-adjustable-fleece=
-cover-up?p=3D18&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03=
cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df=
79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=
=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112"=
 target=3D"_blank" style=3D"text-decoration:none;"> <table cellpadding=3D"0=
" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-family:=
 Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; background:=
 #ffffff; width:290px;" valign=3D"top" class=3D"inner_container"align=3D'le=
ft'> <tr> <td style=3D"width:290px;" align=3D"center" valign=3D"top"> <tabl=
e cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spaci=
ng:0; font-family: Helvetica, Arial, sans-serif; color:#000000; font-weight=
: 100; background: #f2f2f2; width:100%;"> <tr> <td valign=3D"top" align=3D"=
center" width=3D"290" style=3D"width:290px;" class=3D"inner_container"><a h=
ref=3D"https://www.groupon.com/deals/gg-olive-street-heavyweight-adjustable=
-fleece-cover-up?p=3D18&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd=
7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112=
&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dima=
ge&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161=
112" style=3D"display: block; border: none;" target=3D"_blank"><img src=3D"=
https://img.grouponcdn.com/deal/2q11z8BEJ8HFMYP93ZRna3SMFcrH/2q-1400x840/v1=
/c300x182.jpg" width=3D"290" style=3D"display: block; border: none; width: =
290px;" class=3D"secondary-100" alt=3D"Heavyweight Adjustable Fleece Cover-=
Up " /></a></td> </tr> <tr> <td style=3D"padding:16px;"> <table cellpadding=
=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-fa=
mily: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; backgr=
ound: #f2f2f2; width:100%;"> <tr> <td colspan=3D"2" class=3D"nameFont" styl=
e=3D"font-size: 14px !important; line-height: 18px !important; color:#00000=
0 !important; text-decoration: none; color: #333333 !important; width:100%;=
" align=3D"left" valign=3D"top"> Adjustable Fleece Cover-Up </td> </tr> <tr=
> <td class=3D"nameFont" align=3D"left" valign=3D"top"><a href=3D"https://w=
ww.groupon.com/deals/gg-olive-street-heavyweight-adjustable-fleece-cover-up=
?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c8=
22070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-25=
39-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DMindstorm=
-Hero-3-deals&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_2016111=
2" target=3D"_blank" style=3D"font-size: 14px !important; line-height: 18px=
 !important; color:#000000 !important; text-decoration: none;"><font color=
=3D"#e35205">Over 1,000 bought</font></a></td> </tr> <tr> <td width=3D"70%"=
 align=3D"left"> <span valign=3D"top" style=3D"padding-right: 5px; font-fam=
ily: Helvetica, Arial, sans-serif; font-size: 16px !important; line-height:=
 20px !important; text-decoration: line-through; color:#848484 !important; =
font-weight: 100;" class=3D"nameFont">$39.99</span> <span align=3D"left" va=
lign=3D"top" style=3D"font-family: Helvetica, Arial, sans-serif; font-size:=
 16px !important; line-height: 20px !important; font-weight: 300; text-deco=
ration: none; color: #e35205;" class=3D"nameFont">$6.99</span> </td> </tr> =
<tr> <td class=3D"nameFont" align=3D"left" valign=3D"top" style=3D"font-fam=
ily: Helvetica, Arial, sans-serif; font-size: 13px; color: #e35205; text-de=
coration: none; font-weight: 500 !important;">Sale Ends 11/13</td> <td widt=
h=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" style=3D"font-f=
amily: Helvetica, Arial, sans-serif; font-size: 13px !important; line-heigh=
t: 17px !important; font-weight: normal; font-weight: 600; color: #0185c6 !=
important; text-decoration: none; text-align:right; white-space: nowrap;"><=
a href=3D"https://www.groupon.com/deals/gg-olive-street-heavyweight-adjusta=
ble-fleece-cover-up?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8b=
fd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D201611=
12&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Db=
utton&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20=
161112" target=3D"_blank" style=3D"text-decoration:none;"><font color=3D"#0=
185c6">View&nbsp;Deal</font></a></td> </tr> </table> </td> </tr> <tr> <td s=
tyle=3D"width: 10px; background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</=
td> </tr> </table> </td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </t=
d> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"htt=
ps://www.groupon.com/deals/gg-world-tech-toys-tool-swat-cash-register-bbq-g=
rill-kitchen-play?p=3D19&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bf=
d7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D2016111=
2&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbu=
tton&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_201=
61112" target=3D"_blank" style=3D"text-decoration:none;"> <table cellpaddin=
g=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-f=
amily: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; backg=
round: #ffffff; width:290px;" valign=3D"top" class=3D"inner_container"align=
=3D'right'> <tr> <td style=3D"width:290px;" align=3D"center" valign=3D"top"=
> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; borde=
r-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#000000; font=
-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td valign=3D"top" al=
ign=3D"center" width=3D"290" style=3D"width:290px;" class=3D"inner_containe=
r"><a href=3D"https://www.groupon.com/deals/gg-world-tech-toys-tool-swat-ca=
sh-register-bbq-grill-kitchen-play?p=3D19&utm_source=3Dcrm_im&utm_medium=3D=
email&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8c=
d2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D=
0&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7d=
ca721587e9_0_20161112" style=3D"display: block; border: none;" target=3D"_b=
lank"><img src=3D"https://img.grouponcdn.com/deal/2nLuRPHnLh6k5tcEytBr391HS=
ChJ/2n-1500x900/v1/c300x182.jpg" width=3D"290" style=3D"display: block; bor=
der: none; width: 290px;" class=3D"secondary-100" alt=3D"World Tech Toys Ki=
ds' Playsets" /></a></td> </tr> <tr> <td style=3D"padding:16px;"> <table ce=
llpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0=
; font-family: Helvetica, Arial, sans-serif; color:#000000; font-weight: 10=
0; background: #f2f2f2; width:100%;"> <tr> <td colspan=3D"2" class=3D"nameF=
ont" style=3D"font-size: 14px !important; line-height: 18px !important; col=
or:#000000 !important; text-decoration: none; color: #333333 !important; wi=
dth:100%;" align=3D"left" valign=3D"top"> World Tech Toys Kids' Playsets </=
td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"top"><a href=
=3D"https://www.groupon.com/deals/gg-world-tech-toys-tool-swat-cash-registe=
r-bbq-grill-kitchen-play?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=
=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D=
20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody=
&c=3Dbutton&d=3DMindstorm-Hero-3-deals&utm_campaign=3Db5ac89a0-e1ee-4fec-b0=
f0-7dca721587e9_0_20161112" target=3D"_blank" style=3D"font-size: 14px !imp=
ortant; line-height: 18px !important; color:#000000 !important; text-decora=
tion: none;"><font color=3D"#e35205">Over 1,000 bought</font></a></td> </tr=
> <tr> <td width=3D"70%" align=3D"left"> <span valign=3D"top" style=3D"padd=
ing-right: 5px; font-family: Helvetica, Arial, sans-serif; font-size: 16px =
!important; line-height: 20px !important; text-decoration: line-through; co=
lor:#848484 !important; font-weight: 100;" class=3D"nameFont">$89.99</span>=
 <span align=3D"left" valign=3D"top" style=3D"font-family: Helvetica, Arial=
, sans-serif; font-size: 16px !important; line-height: 20px !important; fon=
t-weight: 300; text-decoration: none; color: #e35205;" class=3D"nameFont">$=
27.99</span> </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=
=3D"top" style=3D"font-family: Helvetica, Arial, sans-serif; font-size: 13p=
x; color: #e35205; text-decoration: none; font-weight: 500 !important;">Sal=
e Ends 11/12</td> <td width=3D"30%" class=3D"nameFont" align=3D"right" vali=
gn=3D"top" style=3D"font-family: Helvetica, Arial, sans-serif; font-size: 1=
3px !important; line-height: 17px !important; font-weight: normal; font-wei=
ght: 600; color: #0185c6 !important; text-decoration: none; text-align:righ=
t; white-space: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-world-=
tech-toys-tool-swat-cash-register-bbq-grill-kitchen-play?p=3D2&utm_source=
=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fb=
f5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-0025=
9069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Db5=
ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_blank" style=3D"t=
ext-decoration:none;"><font color=3D"#0185c6">View&nbsp;Deal</font></a></td=
> </tr> </table> </td> </tr> <tr> <td style=3D"width: 10px; background: #ff=
ffff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> </tr> </table> </td> </tr> </tab=
le> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|=
(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </tr> </table> <![endi=
f]--> </tr> <tr> <td valign=3D"top" align=3D"left" width=3D"100%" style=3D"=
width: 600px;" class=3D"inner_container"> <!--[if (gte mso 9)|(IE)]> <table=
 width=3D"600" align=3D"center" cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0"> <tr> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a h=
ref=3D"https://www.groupon.com/deals/gg-ladder-with-wall-rack?p=3D20&utm_so=
urce=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f8=
06fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-=
00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=
=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_blank" style=
=3D"text-decoration:none;"> <table cellpadding=3D"0" cellspacing=3D"0" styl=
e=3D"border: 0 none; border-spacing:0; font-family: Helvetica, Arial, sans-=
serif; color:#000000; font-weight: 100; background: #ffffff; width:290px;" =
valign=3D"top" class=3D"inner_container"align=3D'left'> <tr> <td style=3D"w=
idth:290px;" align=3D"center" valign=3D"top"> <table cellpadding=3D"0" cell=
spacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Helve=
tica, Arial, sans-serif; color:#000000; font-weight: 100; background: #f2f2=
f2; width:100%;"> <tr> <td valign=3D"top" align=3D"center" width=3D"290" st=
yle=3D"width:290px;" class=3D"inner_container"><a href=3D"https://www.group=
on.com/deals/gg-ladder-with-wall-rack?p=3D20&utm_source=3Dcrm_im&utm_medium=
=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561e=
d8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=
=3D0&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0=
-7dca721587e9_0_20161112" style=3D"display: block; border: none;" target=3D=
"_blank"><img src=3D"https://img.grouponcdn.com/deal/3Kf9cdH8UqKvauQv3BYbmu=
UkjdJ9/3K-960x582/v1/c300x182.jpg" width=3D"290" style=3D"display: block; b=
order: none; width: 290px;" class=3D"secondary-100" alt=3D"Little Giant Alt=
a-One 17' Ladder with Wall Rack" /></a></td> </tr> <tr> <td style=3D"paddin=
g:16px;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 non=
e; border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#0000=
00; font-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td colspan=
=3D"2" class=3D"nameFont" style=3D"font-size: 14px !important; line-height:=
 18px !important; color:#000000 !important; text-decoration: none; color: #=
333333 !important; width:100%;" align=3D"left" valign=3D"top"> Little Giant=
 17' Ladder </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=
=3D"top"><a href=3D"https://www.groupon.com/deals/gg-ladder-with-wall-rack?=
p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c82=
2070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-253=
9-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DMindstorm-=
Hero-3-deals&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112=
" target=3D"_blank" style=3D"font-size: 14px !important; line-height: 18px =
!important; color:#000000 !important; text-decoration: none;"><font color=
=3D"#e35205">Ending soon!</font></a></td> </tr> <tr> <td width=3D"70%" alig=
n=3D"left"> <span valign=3D"top" style=3D"padding-right: 5px; font-family: =
Helvetica, Arial, sans-serif; font-size: 16px !important; line-height: 20px=
 !important; text-decoration: line-through; color:#848484 !important; font-=
weight: 100;" class=3D"nameFont">$349.99</span> <span align=3D"left" valign=
=3D"top" style=3D"font-family: Helvetica, Arial, sans-serif; font-size: 16p=
x !important; line-height: 20px !important; font-weight: 300; text-decorati=
on: none; color: #e35205;" class=3D"nameFont">$164.99</span> </td> </tr> <t=
r> <td class=3D"nameFont" align=3D"left" valign=3D"top" style=3D"font-famil=
y: Helvetica, Arial, sans-serif; font-size: 13px; color: #e35205; text-deco=
ration: none; font-weight: 500 !important;">Sale Ends 11/13</td> <td width=
=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" style=3D"font-fa=
mily: Helvetica, Arial, sans-serif; font-size: 13px !important; line-height=
: 17px !important; font-weight: normal; font-weight: 600; color: #0185c6 !i=
mportant; text-decoration: none; text-align:right; white-space: nowrap;"><a=
 href=3D"https://www.groupon.com/deals/gg-ladder-with-wall-rack?p=3D2&utm_s=
ource=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f=
806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0=
-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=
=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_blank" style=
=3D"text-decoration:none;"><font color=3D"#0185c6">View&nbsp;Deal</font></a=
></td> </tr> </table> </td> </tr> <tr> <td style=3D"width: 10px; background=
: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> </tr> </table> </td> </tr> =
</table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte ms=
o 9)|(IE)]> <td> <![endif]--> <a href=3D"https://www.groupon.com/deals/gg-n=
caa-tailgate-toss?p=3D21&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bf=
d7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D2016111=
2&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbu=
tton&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_201=
61112" target=3D"_blank" style=3D"text-decoration:none;"> <table cellpaddin=
g=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-f=
amily: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; backg=
round: #ffffff; width:290px;" valign=3D"top" class=3D"inner_container"align=
=3D'right'> <tr> <td style=3D"width:290px;" align=3D"center" valign=3D"top"=
> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; borde=
r-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#000000; font=
-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td valign=3D"top" al=
ign=3D"center" width=3D"290" style=3D"width:290px;" class=3D"inner_containe=
r"><a href=3D"https://www.groupon.com/deals/gg-ncaa-tailgate-toss?p=3D21&ut=
m_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1e=
d8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-8=
2c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campai=
gn=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" style=3D"display: blo=
ck; border: none;" target=3D"_blank"><img src=3D"https://img.grouponcdn.com=
/deal/3LYDUFT73R2oXLtA6HA1HARiqAaQ/3L-900x540/v1/c300x182.jpg" width=3D"290=
" style=3D"display: block; border: none; width: 290px;" class=3D"secondary-=
100" alt=3D"NCAA Tailgate Toss Set with Matching Bags" /></a></td> </tr> <t=
r> <td style=3D"padding:16px;"> <table cellpadding=3D"0" cellspacing=3D"0" =
style=3D"border: 0 none; border-spacing:0; font-family: Helvetica, Arial, s=
ans-serif; color:#000000; font-weight: 100; background: #f2f2f2; width:100%=
;"> <tr> <td colspan=3D"2" class=3D"nameFont" style=3D"font-size: 14px !imp=
ortant; line-height: 18px !important; color:#000000 !important; text-decora=
tion: none; color: #333333 !important; width:100%;" align=3D"left" valign=
=3D"top"> NCAA Tailgate Toss Set </td> </tr> <tr> <td class=3D"nameFont" al=
ign=3D"left" valign=3D"top"><a href=3D"https://www.groupon.com/deals/gg-nca=
a-tailgate-toss?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c=
8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&u=
u=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutto=
n&d=3DMindstorm-Hero-3-deals&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721=
587e9_0_20161112" target=3D"_blank" style=3D"font-size: 14px !important; li=
ne-height: 18px !important; color:#000000 !important; text-decoration: none=
;"><font color=3D"#e35205">Over 600 bought</font></a></td> </tr> <tr> <td w=
idth=3D"70%" align=3D"left"> <span valign=3D"top" style=3D"padding-right: 5=
px; font-family: Helvetica, Arial, sans-serif; font-size: 16px !important; =
line-height: 20px !important; text-decoration: line-through; color:#848484 =
!important; font-weight: 100;" class=3D"nameFont">$129.99</span> <span alig=
n=3D"left" valign=3D"top" style=3D"font-family: Helvetica, Arial, sans-seri=
f; font-size: 16px !important; line-height: 20px !important; font-weight: 3=
00; text-decoration: none; color: #e35205;" class=3D"nameFont">$69.99</span=
> </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"top" sty=
le=3D"font-family: Helvetica, Arial, sans-serif; font-size: 13px; color: #e=
35205; text-decoration: none; font-weight: 500 !important;">Sale Ends 11/13=
</td> <td width=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" s=
tyle=3D"font-family: Helvetica, Arial, sans-serif; font-size: 13px !importa=
nt; line-height: 17px !important; font-weight: normal; font-weight: 600; co=
lor: #0185c6 !important; text-decoration: none; text-align:right; white-spa=
ce: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-ncaa-tailgate-toss=
?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c8=
22070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-25=
39-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&=
utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_=
blank" style=3D"text-decoration:none;"><font color=3D"#0185c6">View&nbsp;De=
al</font></a></td> </tr> </table> </td> </tr> <tr> <td style=3D"width: 10px=
; background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> </tr> </table> =
</td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!-=
-[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </tr>=
 </table> <![endif]--> </tr> <tr> <td valign=3D"top" align=3D"left" width=
=3D"100%" style=3D"width: 600px;" class=3D"inner_container"> <!--[if (gte m=
so 9)|(IE)]> <table width=3D"600" align=3D"center" cellpadding=3D"0" cellsp=
acing=3D"0" border=3D"0"> <tr> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td>=
 <![endif]--> <a href=3D"https://www.groupon.com/deals/gg-dolce-gabbana-lig=
ht-blue-eau-de-toilette-for-women-or-men?p=3D22&utm_source=3Dcrm_im&utm_med=
ium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf3865=
61ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS=
&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-=
b0f0-7dca721587e9_0_20161112" target=3D"_blank" style=3D"text-decoration:no=
ne;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; b=
order-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#000000; =
font-weight: 100; background: #ffffff; width:290px;" valign=3D"top" class=
=3D"inner_container"align=3D'left'> <tr> <td style=3D"width:290px;" align=
=3D"center" valign=3D"top"> <table cellpadding=3D"0" cellspacing=3D"0" styl=
e=3D"border: 0 none; border-spacing:0; font-family: Helvetica, Arial, sans-=
serif; color:#000000; font-weight: 100; background: #f2f2f2; width:100%;"> =
<tr> <td valign=3D"top" align=3D"center" width=3D"290" style=3D"width:290px=
;" class=3D"inner_container"><a href=3D"https://www.groupon.com/deals/gg-do=
lce-gabbana-light-blue-eau-de-toilette-for-women-or-men?p=3D22&utm_source=
=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fb=
f5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-0025=
9069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Db5a=
c89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" style=3D"display: block; bord=
er: none;" target=3D"_blank"><img src=3D"https://img.grouponcdn.com/deal/GC=
rV2BKQTrZaVmLiBwRBD8zQLT1/GC-1400x840/v1/c300x182.jpg" width=3D"290" style=
=3D"display: block; border: none; width: 290px;" class=3D"secondary-100" al=
t=3D"Dolce & Gabbana Light Blue Eau de Toilettes (Multiple Sizes)" /></a></=
td> </tr> <tr> <td style=3D"padding:16px;"> <table cellpadding=3D"0" cellsp=
acing=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Helveti=
ca, Arial, sans-serif; color:#000000; font-weight: 100; background: #f2f2f2=
; width:100%;"> <tr> <td colspan=3D"2" class=3D"nameFont" style=3D"font-siz=
e: 14px !important; line-height: 18px !important; color:#000000 !important;=
 text-decoration: none; color: #333333 !important; width:100%;" align=3D"le=
ft" valign=3D"top"> Dolce & Gabbana Light Blue </td> </tr> <tr> <td class=
=3D"nameFont" align=3D"left" valign=3D"top"><a href=3D"https://www.groupon.=
com/deals/gg-dolce-gabbana-light-blue-eau-de-toilette-for-women-or-men?p=3D=
2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070=
ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11=
e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DMindstorm-Hero=
-3-deals&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" ta=
rget=3D"_blank" style=3D"font-size: 14px !important; line-height: 18px !imp=
ortant; color:#000000 !important; text-decoration: none;"><font color=3D"#e=
35205">Over 1,000 bought</font></a></td> </tr> <tr> <td width=3D"70%" align=
=3D"left"> <span valign=3D"top" style=3D"padding-right: 5px; font-family: H=
elvetica, Arial, sans-serif; font-size: 16px !important; line-height: 20px =
!important; text-decoration: line-through; color:#848484 !important; font-w=
eight: 100;" class=3D"nameFont">$55</span> <span align=3D"left" valign=3D"t=
op" style=3D"font-family: Helvetica, Arial, sans-serif; font-size: 16px !im=
portant; line-height: 20px !important; font-weight: 300; text-decoration: n=
one; color: #e35205;" class=3D"nameFont">$24.99</span> </td> </tr> <tr> <td=
 class=3D"nameFont" align=3D"left" valign=3D"top" style=3D"font-family: Hel=
vetica, Arial, sans-serif; font-size: 13px; color: #e35205; text-decoration=
: none; font-weight: 500 !important;">Sale Ends 11/14</td> <td width=3D"30%=
" class=3D"nameFont" align=3D"right" valign=3D"top" style=3D"font-family: H=
elvetica, Arial, sans-serif; font-size: 13px !important; line-height: 17px =
!important; font-weight: normal; font-weight: 600; color: #0185c6 !importan=
t; text-decoration: none; text-align:right; white-space: nowrap;"><a href=
=3D"https://www.groupon.com/deals/gg-dolce-gabbana-light-blue-eau-de-toilet=
te-for-women-or-men?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8b=
fd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D201611=
12&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Db=
utton&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20=
161112" target=3D"_blank" style=3D"text-decoration:none;"><font color=3D"#0=
185c6">View&nbsp;Deal</font></a></td> </tr> </table> </td> </tr> <tr> <td s=
tyle=3D"width: 10px; background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</=
td> </tr> </table> </td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </t=
d> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"htt=
ps://www.groupon.com/deals/gg-wexley-home-glass-food-storage?p=3D23&utm_sou=
rce=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f80=
6fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-0=
0259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=
=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_blank" style=
=3D"text-decoration:none;"> <table cellpadding=3D"0" cellspacing=3D"0" styl=
e=3D"border: 0 none; border-spacing:0; font-family: Helvetica, Arial, sans-=
serif; color:#000000; font-weight: 100; background: #ffffff; width:290px;" =
valign=3D"top" class=3D"inner_container"align=3D'right'> <tr> <td style=3D"=
width:290px;" align=3D"center" valign=3D"top"> <table cellpadding=3D"0" cel=
lspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Helv=
etica, Arial, sans-serif; color:#000000; font-weight: 100; background: #f2f=
2f2; width:100%;"> <tr> <td valign=3D"top" align=3D"center" width=3D"290" s=
tyle=3D"width:290px;" class=3D"inner_container"><a href=3D"https://www.grou=
pon.com/deals/gg-wexley-home-glass-food-storage?p=3D23&utm_source=3Dcrm_im&=
utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac13=
4cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&C=
ID=3DUS&tx=3D0&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee=
-4fec-b0f0-7dca721587e9_0_20161112" style=3D"display: block; border: none;"=
 target=3D"_blank"><img src=3D"https://img.grouponcdn.com/deal/3Uz9im7Tq6Hk=
RrUQkZg59P3vZYgD/3U-960x576/v1/c300x182.jpg" width=3D"290" style=3D"display=
: block; border: none; width: 290px;" class=3D"secondary-100" alt=3D"Wexley=
 Glass Food-Storage Container Set (8-, 10-, 14-, or 20-Piece)" /></a></td> =
</tr> <tr> <td style=3D"padding:16px;"> <table cellpadding=3D"0" cellspacin=
g=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Helvetica, =
Arial, sans-serif; color:#000000; font-weight: 100; background: #f2f2f2; wi=
dth:100%;"> <tr> <td colspan=3D"2" class=3D"nameFont" style=3D"font-size: 1=
4px !important; line-height: 18px !important; color:#000000 !important; tex=
t-decoration: none; color: #333333 !important; width:100%;" align=3D"left" =
valign=3D"top"> Wexley Food-Storage Glassware </td> </tr> <tr> <td class=3D=
"nameFont" align=3D"left" valign=3D"top"><a href=3D"https://www.groupon.com=
/deals/gg-wexley-home-glass-food-storage?p=3D2&utm_source=3Dcrm_im&utm_medi=
um=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf38656=
1ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&=
tx=3D0&s=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-deals&utm_campaign=3Db5ac89=
a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_blank" style=3D"font-=
size: 14px !important; line-height: 18px !important; color:#000000 !importa=
nt; text-decoration: none;"><font color=3D"#e35205">Ending soon!</font></a>=
</td> </tr> <tr> <td width=3D"70%" align=3D"left"> <span valign=3D"top" sty=
le=3D"padding-right: 5px; font-family: Helvetica, Arial, sans-serif; font-s=
ize: 16px !important; line-height: 20px !important; text-decoration: line-t=
hrough; color:#848484 !important; font-weight: 100;" class=3D"nameFont">$34=
.99</span> <span align=3D"left" valign=3D"top" style=3D"font-family: Helvet=
ica, Arial, sans-serif; font-size: 16px !important; line-height: 20px !impo=
rtant; font-weight: 300; text-decoration: none; color: #e35205;" class=3D"n=
ameFont">$12.99</span> </td> </tr> <tr> <td class=3D"nameFont" align=3D"lef=
t" valign=3D"top" style=3D"font-family: Helvetica, Arial, sans-serif; font-=
size: 13px; color: #e35205; text-decoration: none; font-weight: 500 !import=
ant;">Sale Ends 11/13</td> <td width=3D"30%" class=3D"nameFont" align=3D"ri=
ght" valign=3D"top" style=3D"font-family: Helvetica, Arial, sans-serif; fon=
t-size: 13px !important; line-height: 17px !important; font-weight: normal;=
 font-weight: 600; color: #0185c6 !important; text-decoration: none; text-a=
lign:right; white-space: nowrap;"><a href=3D"https://www.groupon.com/deals/=
gg-wexley-home-glass-food-storage?p=3D2&utm_source=3Dcrm_im&utm_medium=3Dem=
ail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2=
&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&=
s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dc=
a721587e9_0_20161112" target=3D"_blank" style=3D"text-decoration:none;"><fo=
nt color=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </table> </td> </=
tr> <tr> <td style=3D"width: 10px; background: #ffffff;">&nbsp;&nbsp;&nbsp;=
&nbsp;&nbsp;</td> </tr> </table> </td> </tr> </table> </a> <!--[if (gte mso=
 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </td> <![endif]-->=
 <!--[if (gte mso 9)|(IE)]> </tr> </table> <![endif]--> </tr> </table> <tab=
le cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spac=
ing:0; font-family: Helvetica, Arial, sans-serif; color:#000000; font-weigh=
t: 100; width: 600px;" align=3D"center" class=3D"inner_container"> <tr> <td=
 style=3D"padding: 30px;" align=3D"center"> <table cellpadding=3D"0" cellsp=
acing=3D"0" style=3D"font-family: Arial, Helvetica, sans-serif; font-size:1=
4px !important; line-height:19px !important; color:#333; width:200px;" alig=
n=3D"center"> <tr> <td height=3D"45" bgcolor=3D"#3ebddc" background=3D"http=
s://s3.grouponcdn.com/email/images/prom_night/global_buttons/pn-btn-gradien=
t-blue.gif" background-repeat=3D"repeat-x" style=3D"height:45px; text-align=
:center;"><a href=3D"https://www.groupon.com/goods?utm_source=3Dcrm_im&utm_=
medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf3=
86561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=
=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods&utm_campaign=3Db5ac89a0-e1ee-4fe=
c-b0f0-7dca721587e9_0_20161112" style=3D"padding: 10px 0 10px 0; color:#fff=
fff; font-size:16px; font-weight: 500; text-decoration:none;">VIEW&nbsp;ALL=
&nbsp;GOODS</a></td> </tr> </table> </td> </tr> </table> </td> </tr> </tabl=
e> </td> </tr> </table> <table cellpadding=3D"0" cellspacing=3D"0" style=3D=
"border: 0 none; border-spacing:0; font-family: Helvetica, Arial, sans-seri=
f; color:#000000; font-weight: 100; width: 100%; background: #ececec; paddi=
ng-top: 10px;" align=3D"center"> <tr> <td> </td> </tr> </table> <table cell=
padding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; =
font-family: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100;=
 width: 100%; background: #ececec;" align=3D"center"> <tr> <td>&nbsp;</td> =
</tr> </table> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"font-fam=
ily: Arial, Helvetica, sans-serif; font-size:14px !important; line-height:1=
9px !important; color:#333; width: 100%; background: #ffffff;" align=3D"cen=
ter"> <tr> <td align=3D"center"> <table cellpadding=3D"0" cellspacing=3D"0"=
 style=3D"font-family: Arial, Helvetica, sans-serif; font-size:14px !import=
ant; line-height:19px !important; color:#333; width: 600px;" align=3D"cente=
r" class=3D"inner_container"> <tr> <td align=3D"center" style=3D"padding: 3=
0px 10px 0 10px; font-size: 12px !important; line-height: 22px !important; =
color:#000000 !important; text-decoration: none;"> To feature your business=
 on Groupon, <a href=3D"https://www.groupon.com/merchant/get-started?utm_so=
urce=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f8=
06fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-=
00259069d5fe&CID=3DUS&tx=3D0&s=3D&c=3Dlink&d=3DGrouponMerchant&utm_campaign=
=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_blank" style=
=3D"color:#0185C6; text-decoration:none;" title=3D"Groupon Merchant">get st=
arted</a> at Groupon Merchant. <br/><br/>You are receiving this email becau=
se kyle@kylefisher.com is signed up to receive Groupon communications. To a=
djust your settings or to unsubscribe, please <a href=3D"https://www.groupo=
n.com/subscription_center/manage/consumer/f79c234c-2539-11e2-82c0-00259069d=
5fe?cmplistId=3Dchannel:goods&utm_source=3Dcrm_im&utm_medium=3Demail&user=
=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D=
20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dfoot=
er&c=3Dlink&d=3Dchannel_unsub&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca72=
1587e9_0_20161112" style=3D"color:#0185C6; text-decoration:none;" target=3D=
"_blank">click here</a>. <br /><br />Delivered by <a href=3D"http://www.gro=
upon.com?utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337=
c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-=
2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dfooter&c=3Dlink&d=3Dhome&ut=
m_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" target=3D"_bl=
ank" style=3D'color:#0185C6; text-decoration:none;'>Groupon</a> <a href=3D"=
http://www.groupon.com" style=3D"color:#333; text-decoration:none;">600 W. =
Chicago Avenue, Suite 400, Chicago, IL 60654, USA</a></td> </tr> <tr> <td a=
lign=3D"center" style=3D"padding: 5px 10px 50px 10px; font-size: 12px !impo=
rtant; line-height: 22px !important; color:#000000 !important; text-decorat=
ion: none;"><a href=3D"http://www.groupon.com/customer_support?utm_source=
=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fb=
f5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-0025=
9069d5fe&CID=3DUS&tx=3D0&s=3Dfooter&c=3Dlink&d=3Dcontact-us&utm_campaign=3D=
b5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" style=3D"color:#0185C6; te=
xt-decoration:none;" target=3D"_blank">Contact Us</a> | <a href=3D"https://=
www.groupon.com/faq?utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8b=
f03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=
=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dfooter&c=3Dlink=
&d=3DFAQ&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e9_0_20161112" st=
yle=3D"color:#0185C6; text-decoration:none;" target=3D"_blank">FAQ</a> | <a=
 href=3D"https://www.groupon.com/privacy?utm_source=3Dcrm_im&utm_medium=3De=
mail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd=
2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0=
&s=3Dfooter&c=3Dlink&d=3Dprivacy_statement&utm_campaign=3Db5ac89a0-e1ee-4fe=
c-b0f0-7dca721587e9_0_20161112" style=3D"color:#0185C6; text-decoration:non=
e;" target=3D"_blank">Privacy Statement</a></td> </tr> </table> </td> </tr>=
 </table> <img src =3D "http://www.groupon.com/analytic/track.gif?p=3D2&utm=
_domain=3Dkylefisher.com&utm_campaign=3Db5ac89a0-e1ee-4fec-b0f0-7dca721587e=
9_0_20161112&deals=3Db1004410-12d2-11e6-aa3b-00259060b5da,3c66cdc8-75f0-11e=
6-a53e-00259069d7cc,b296c5fc-631c-11e6-9644-00259069d868,0bfed708-686b-11e6=
-9851-00259069d868,4535e218-83fb-11e6-856e-002590604002,51506417-cb99-458d-=
978d-ec03486fbb9d,3e2d14f4-7f2f-11e5-868e-002590980a5a,e9d59326-6a5c-11e6-a=
a0d-00259069d7cc,f2e9ec40-7057-11e6-89e3-00259069d868,35c8d4b9-4864-4bec-55=
88-ab3b7cdb6029,76fa84a4-6adb-11e6-84bb-00259069d7cc,43efa2a6-6291-49ee-a1a=
a-b62a12656eda,78591936-9007-11e6-870d-00259069d868,665ec228-4389-11e6-a5e2=
-00259069d868,454e2e74-29ef-11e6-be37-00259069d868,d65be1f8-3abe-4ea1-8bc8-=
ae7123699f1b,2a629bbe-a410-11e5-bf99-00259098486a,bc44a02c-1e94-4a33-bd24-0=
64e21d93a21,503c69bc-8b61-11e6-89fc-00259069d868,57ed4854-7c23-11e6-9cd7-00=
259069d868,c01baab2-73da-4159-b198-b07ca81000cb,01d12c81-7de6-4538-9c50-4c6=
a3f8d876a,d882f950-ca28-45dc-802a-9e2613981798&channel_deals=3Dnull&utm_sou=
rce=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f80=
6fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-0=
0259069d5fe&CID=3DUS&tx=3D0" height=3D"1" width=3D"1" style=3D"display: non=
e !important;" /> </body> </html>

