From no-reply@mail.instagram.com Fri Nov 11 09:46:38 2016
Received: from 69-171-232-148.outmail.facebook.com ([69.171.232.148]:10726 helo=mx-out.facebook.com)
	by ecbiz209.inmotionhosting.com with esmtps (TLSv1:DHE-RSA-AES256-SHA:256)
	(Exim 4.87)
	(envelope-from <no-reply@mail.instagram.com>)
	id 1c5D6D-001S4s-Q0
	for kyle@kylefisher.com; Fri, 11 Nov 2016 09:46:37 -0500
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=mail.instagram.com;
	s=s1024-2013-q3; t=1478804629;
	bh=F/buHsycI2U7vNhbDgLMVMN8BiB2SKNCgflWd8zUT1g=;
	h=Date:To:Subject:From:MIME-Version:Content-Type;
	b=rB4rx3ODbE5Hq5kk6zuqI5kMV5tuzlXu2SMwMfmyflAA7SxF5PiLw5E4gemiIdzxO
	 fG7pUF7RlYg9SvRTldFVYLefBiVHd/wH0mQUoyfOtgN67CruBBxjbzkWcfMzDjDOVT
	 gS/8LEKne1Ow7wxTf5byGyQLNEO3Nz5zLBqcTFgU=
Received: from facebook.com (+AYynMYYmp0fhqIR1JDOiJOWVGtVocYls7oS7EbmVflJwp42hmq9EaJxRvxjL89k 10.17.112.27)
 by facebook.com with Thrift id 69d10efea77811e6944b0002c9254464-141fca50;
 Thu, 10 Nov 2016 11:03:49 -0800
X-Facebook: from 2401:db00:11:2048:face:0:3b:0 ([MTI3LjAuMC4x]) 
	by api.facebook.com with HTTP (ZuckMail);
Date: Thu, 10 Nov 2016 11:03:49 -0800
To: kyle@kylefisher.com
Subject: Help with your account
X-Priority: 3
X-Mailer: ZuckMail [version 1.00]
From: "Instagram" <no-reply@mail.instagram.com>
Reply-to: Instagram <no-reply@mail.instagram.com>
Errors-To: no-reply@mail.instagram.com
X-Facebook-Notify: ig_login_email; mailid=HMjQ0MjM2NzM5Omt5bGVAa3lsZWZpc2hlci5jb206OTkx
List-Unsubscribe: <https://www.facebook.com/o.php?k=AS0Cvg8IGxYaNbib&e=kyle%40kylefisher.com&mid=HMjQ0MjM2NzM5Omt5bGVAa3lsZWZpc2hlci5jb206OTkx>
X-FACEBOOK-PRIORITY: 0
X-Auto-Response-Suppress: All
Message-ID: <afeb4315b16d2a7491e27a36fe5ea709@api.facebook.com>
MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset="UTF-8"

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional =
//EN"><html><head><title>Facebook</title><meta http-equiv=3D"Content-Type" =
content=3D"text/html; charset=3Dutf-8" /><style>@media all and (max-width: =
480px){*[class].ib_t{min-width:100% =
!important}*[class].ib_row{display:block =
!important}*[class].ib_ext{display:block !important;padding:10px 0 5px =
0;vertical-align:top !important;width:100% =
!important}*[class].ib_img,*[class].ib_mid{vertical-align:top =
!important}*[class].mb_blk{display:block =
!important;padding-bottom:10px;width:100% =
!important}*[class].mb_hide{display:none =
!important}*[class].mb_inl{display:inline !important}}.mb_text h1,.mb_text =
h2,.mb_text h3,.mb_text h4,.mb_text h5,.mb_text =
h6{line-height:normal}.mb_work_text =
h1{font-size:18px;line-height:normal;margin-top:4px}.mb_work_text =
h2,.mb_work_text =
h3{font-size:16px;line-height:normal;margin-top:4px}.mb_work_text =
h4,.mb_work_text h5,.mb_work_text =
h6{font-size:14px;line-height:normal}.mb_work_text =
a{color:#1270e9}.mb_work_text p{margin-top:4px}</style></head><body =
style=3D"margin:0;padding:0;" dir=3D"ltr" bgcolor=3D"#ffffff"><table =
cellspacing=3D"0" cellpadding=3D"0" width=3D"100%;" id=3D"email_table" =
border=3D"0" style=3D"border-collapse:collapse;"><tr><td =
id=3D"email_content" style=3D"font-family:Helvetica Neue,Helvetica,Lucida =
Grande,tahoma,verdana,arial,sans-serif;background:#ffffff;"><table =
cellspacing=3D"0" cellpadding=3D"0" width=3D"100%" =
style=3D"border-collapse:collapse;"><tr style=3D""><td height=3D"20" =
style=3D"line-height:20px;" colspan=3D"3">&nbsp;</td></tr><tr><td =
height=3D"1" colspan=3D"3" style=3D"line-height:1px;"></td></tr><tr><td =
style=3D""><table cellspacing=3D"0" cellpadding=3D"0" width=3D"100%" =
style=3D"border-collapse:collapse;border:solid 1px white;margin:0 auto 5px =
auto;padding:3px 0;text-align:center;html_width:100%;width:430px;"><tr><td =
width=3D"15px" style=3D"width:15px;"></td><td =
style=3D"line-height:0px;width:400px;padding:0 0 15px 0;"><table =
cellspacing=3D"0" cellpadding=3D"0" =
style=3D"border-collapse:collapse;"><tr><td =
style=3D"width:100%;text-align:left;height:33px;"><img height=3D"33" =
src=3D"https://static.xx.fbcdn.net/rsrc.php/v3/yr/r/jxR-EPx51R9.png" =
style=3D"border:0;" /></td></tr></table></td><td width=3D"15px" =
style=3D"width:15px;"></td></tr><tr><td width=3D"15px" =
style=3D"width:15px;"></td><td style=3D"border-top:solid 1px =
#c8c8c8;"></td><td width=3D"15px" =
style=3D"width:15px;"></td></tr></table></td></tr><tr><td =
style=3D""><table cellspacing=3D"0" cellpadding=3D"0" width=3D"430" =
style=3D"border-collapse:collapse;margin:0 auto 0 auto;"><tr><td =
style=3D""><table cellspacing=3D"0" cellpadding=3D"0" width=3D"430px" =
style=3D"border-collapse:collapse;margin:0 auto 0 auto;width:430px;"><td =
width=3D"15" =
style=3D"display:block;width:15px;">&nbsp;&nbsp;&nbsp;</td><tr =
style=3D""><td style=3D""><table cellspacing=3D"0" cellpadding=3D"0" =
width=3D"100%" style=3D"border-collapse:collapse;"><tr><td =
style=3D""><table cellspacing=3D"0" cellpadding=3D"0" =
style=3D"border-collapse:collapse;"><tr><td width=3D"20" =
style=3D"display:block;width:20px;">&nbsp;&nbsp;&nbsp;</td><td =
style=3D""><table cellspacing=3D"0" cellpadding=3D"0" =
style=3D"border-collapse:collapse;"><tr><td style=3D""><p =
style=3D"padding:0;margin:10px 0 10px 0;color:#565a5c;font-size:18px;">Hi =
mystikyle,</p><p style=3D"padding:0;margin:10px 0 10px =
0;color:#565a5c;font-size:18px;">Sorry to hear you&#039;re having trouble =
logging into Instagram. We can help you get straight back into your =
account.</p></td></tr><tr style=3D""><td height=3D"20" =
style=3D"line-height:20px;" colspan=3D"1">&nbsp;</td></tr><tr><td =
style=3D""><a href=3D"https://www.instagram.com/_n/emaillogin?token=3DTUsx=
N3&amp;uid=3D4bp7sd" style=3D"color:#3b5998;text-decoration:none;display:b=
lock;width:370px;"><table cellspacing=3D"0" cellpadding=3D"0" =
width=3D"390" style=3D"border-collapse:collapse;"><tr><td =
style=3D"border-collapse:collapse;border-radius:3px;text-align:center;disp=
lay:block;border:solid 1px #009fdf;padding:10px 16px 14px 16px;margin:0 =
2px 0 auto;min-width:80px;background-color:#47A2EA;"><a =
href=3D"https://www.instagram.com/_n/emaillogin?token=3DTUsxN3&amp;uid=3D4=
bp7sd" =
style=3D"color:#3b5998;text-decoration:none;display:block;"><center><font =
size=3D"3"><span style=3D"font-family:Helvetica Neue,Helvetica,Roboto,Aria=
l,sans-serif;white-space:nowrap;font-weight:bold;vertical-align:middle;col=
or:#fdfdfd;font-size:16px;line-height:16px;">Log&nbsp;Me&nbsp;In</span></f=
ont></center></a></td></tr></table></a></td></tr></table></td><td =
width=3D"20" style=3D"display:block;width:20px;">&nbsp;&nbsp;&nbsp;</td></=
tr></table></td></tr></table></td></tr><td width=3D"15" =
style=3D"display:block;width:15px;">&nbsp;&nbsp;&nbsp;</td><tr><td =
style=3D""><table cellspacing=3D"0" cellpadding=3D"0" width=3D"100%" =
style=3D"border-collapse:collapse;"><tr><td style=3D""><table =
cellspacing=3D"0" cellpadding=3D"0" =
style=3D"border-collapse:collapse;"><tr><td width=3D"20" =
style=3D"display:block;width:20px;">&nbsp;&nbsp;&nbsp;</td><td =
style=3D""><table cellspacing=3D"0" cellpadding=3D"0" =
style=3D"border-collapse:collapse;"><tr><td style=3D"padding:0;margin:10px =
0 10px 0;color:#565a5c;font-size:16px;">You can also <a =
href=3D"https://instagram.com/accounts/password/reset/confirm/4bp7sd/4gw-3=
0f9d519c81f821ab41c9e9a9f43f0c4/" =
style=3D"color:#3b5998;text-decoration:none;">reset your Instagram =
password here</a>.</td></tr></table></td><td width=3D"20" =
style=3D"display:block;width:20px;">&nbsp;&nbsp;&nbsp;</td></tr></table></=
td></tr></table></td></tr></table></td></tr></table></td></tr><tr><td =
style=3D""><table cellspacing=3D"0" cellpadding=3D"0" width=3D"430px" =
style=3D"border-collapse:collapse;margin:0 auto 0 auto;width:430px;"><tr =
style=3D""><td height=3D"30" style=3D"line-height:30px;" =
colspan=3D"3">&nbsp;</td></tr><tr><td width=3D"20" =
style=3D"display:block;width:20px;">&nbsp;&nbsp;&nbsp;</td><td =
style=3D""><div style=3D"color:#abadae;font-size:12px;margin:0 auto 5px =
auto;">=C2=A9 Instagram, 1 Hacker Way, Menlo Park, CA 94022</div><div =
style=3D"color:#abadae;font-size:12px;margin:0 auto 5px auto;">This =
message was sent to <a style=3D"color:#abadae;text-decoration:underline;">=
kyle&#064;kylefisher.com</a> and intended for mystikyle. Not you? <a =
href=3D"https://instagram.com/accounts/remove/report_wrong_email/4bp7sd/4g=
w-0e4147694d553c585e342dee374d0118/XxdUZrGH/a3lsZUBreWxlZmlzaGVyLmNvbQ/" =
style=3D"color:#abadae;text-decoration:underline;">Let us know.</a><br =
/></div></td><td width=3D"20" style=3D"display:block;width:20px;">&nbsp;&n=
bsp;&nbsp;</td></tr></table></td></tr><tr style=3D""><td height=3D"20" =
style=3D"line-height:20px;" colspan=3D"3">&nbsp;</td></tr></table><span =
style=3D""><img src=3D"https://www.facebook.com/email_open_log_pic.php?mid=
=3DHMjQ0MjM2NzM5Omt5bGVAa3lsZWZpc2hlci5jb206OTkx" =
style=3D"border:0;width:1px;height:1px;" =
/></span></td></tr></table></body></html>


