From 20161113105557d2b47a3a292148098ac5c2177050p0na@bounces.amazon.com Sun Nov 13 05:55:58 2016
Received: from a13-8.smtp-out.amazonses.com ([54.240.13.8]:50267)
	by ecbiz209.inmotionhosting.com with esmtp (Exim 4.87)
	(envelope-from <20161113105557d2b47a3a292148098ac5c2177050p0na@bounces.amazon.com>)
	id 1c5sS6-001RNJ-J2
	for kyle@kylefisher.com; Sun, 13 Nov 2016 05:55:58 -0500
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/simple;
	s=jvxsykglqiaiibkijmhy37vqxh4mzqr6; d=amazon.com; t=1479034558;
	h=From:Reply-To:To:Message-ID:Subject:MIME-Version:Content-Type:Date;
	bh=Cks9czY8m/pxK9j6T8vhDzBtAB3Ga7V73HzuToH5w5Y=;
	b=tPgZ8U8MzOAI6bdq1hc+8N39iUTxBtuADBTv3SJEcsNK08CiPrOE0wYR3NkRdJwa
	sb0tZ/an3zB8oepFrfhbxbINaD8fkF2kJwFU09w0mu97W4QouJaqPxkMga4lCZ1Qi9r
	60aIXaI0pGxXwEyL/QpmJMKAWZv3DzoV76dgAXBQ=
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/simple;
	s=6gbrjpgwjskckoa6a5zn6fwqkn67xbtw; d=amazonses.com; t=1479034558;
	h=From:Reply-To:To:Message-ID:Subject:MIME-Version:Content-Type:Date:Feedback-ID;
	bh=Cks9czY8m/pxK9j6T8vhDzBtAB3Ga7V73HzuToH5w5Y=;
	b=reg6ldE/gM58hMQg+uZVehZOxhEkuGn4retvZbzLrBy/wvPSOlJZJDD+/e7XST5L
	oBZqUzEFfsJIsddtPjsfOC9ipaHRY0dH+hfAlEXqoYii5wkx+A7XYNz53nn32MSQFXN
	je3S0tYJesGXTb6KypJlgBaW39ZlHyrVFcYxFZn4=
From: "Amazon.com" <ship-confirm@amazon.com>
Reply-To: ship-confirm@amazon.com
To: kyle@kylefisher.com
Message-ID: <010001585d545829-719379d5-a510-41ca-8e9b-4016e2c9cb53-000000@email.amazonses.com>
Subject: Your Amazon.com order of "iCasso - 2 in 1 Wooden..." has shipped!
MIME-Version: 1.0
Content-Type: multipart/alternative; 
	boundary="----=_Part_9636008_919664584.1479034558489"
X-AMAZON-MAIL-RELAY-TYPE: notification
Bounces-to: 20161113105557d2b47a3a292148098ac5c2177050p0na@bounces.amazon.com
X-AMAZON-METADATA: CA=C1YHUQ71QV9WK2-CU=A2SCO4VBODRW03-RI=ALAJWFVSEIPA7
X-Original-MessageID: <urn.rtn.msg.20161113105557d2b47a3a292148098ac5c2177050p0na@1479034558491.rtn-svc-na-1a-d284bab0.us-east-1.amazon.com>
Date: Sun, 13 Nov 2016 10:55:58 +0000
X-SES-Outgoing: 2016.11.13-54.240.13.8
Feedback-ID: 1.us-east-1.ZHcGJK6s+x+i9lRHKog4RW3tECwWIf1xzTYCZyUaiec=:AmazonSES

------=_Part_9636008_919664584.1479034558489
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit

Amazon.com Shipping Confirmation
http://www.amazon.com/ref=TE_SIMP_g

--------------------------------------------------------------------
Hello kyle fisher,

"iCasso - 2 in 1 Wooden..." has shipped.

Details
Order #109-1970879-5671431

Arriving:
    Monday, November 14

Track your package at:
	https://www.amazon.com/gp/css/shiptrack/view.html/ref=TE_SIMP_typ?ie=UTF8&addressID=jpjptunumn&latestArrivalDate=1479182400&orderID=109-1970879-5671431&shipmentDate=1479034487&orderingShipmentId=931863037919&packageId=1

Shipped to:
    Kyle A. Fisher
    316 MCADOO AVE...

		
====================================================================

    Total Before Tax: $21.99 
    Shipment Total: $21.99

====================================================================

View or manage your order in Your Orders:
https://www.amazon.com/gp/css/order-details?orderId=109-1970879-5671431&eoid=1%3A1%3AGKufm8DvY6ov%2BFw%2F%2FVplDlDCOfowwGe3Wu934JBcnuHmfLzNIXkHPjQWItp0hC5JJ9NCs7Wt0LYPIFYaJokE%2F0SLj%2FgEr2UCxKw6n1GpZ%2FW2QXuZj2Bk8R505hBOxn2lqYbToSiwEdPCviuUt8GMVRtc0lyjQGVKspPbTTaT9APRO9tCoD5yFeat9isKsw0nGzyHtoT3UKbU4A%2BoqJbGWDyslD6NUH7Y9uooNHnX22VzCmIjLNc1NwdSIp6WwG9f%2FvOjPiLQ%2BAOdJZYLjYGSO30mNelBzEUdlOxFLF2NNxdGpLB5qNar7hGeciVLas%2BcfwmacAtRoGnu8Yo8TOinLQ%3D%3D&ref_=TE_SIMP_od

We hope to see you again soon.<br/>
Amazon.com

--------------------------------------------------------------------
Unless otherwise noted, items sold by Amazon.com LLC are subject to sales tax in select states in accordance with the applicable laws of that state. If your order contains one or more items from a seller other than Amazon.com LLC, it may be subject to state and local sales tax, depending upon the sellers business policies and the location of their operations. For more tax and seller information, visit: http://www.amazon.com/gp/help/customer/display.html?ie=UTF8&nodeId=200962600 

Your invoice can be accessed here:
https://www.amazon.com/gp/css/summary/print.html?orderID=109-1970879-5671431&ref_=TE_SIMP_inv

This email was sent from a notification-only address that cannot accept incoming email. Please do not reply to this message.               
------=_Part_9636008_919664584.1479034558489
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<html xmlns=3D"http://www.w3.org/1999/xhtml">
 <head>=20
  <meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3DUTF-8" =
/>=20
  <style type=3D"text/css">
body {
=09margin:0;
    color:#333;
}

a {
=09text-decoration:none;
=09color:#006699;
}

p {
=09margin:0px;
}

img {
=09border:0;
    margin:0;
}

/* container */
#container {
=09width:540px;
=09margin:0 auto;
}

#content {
=09width:500px;
    margin:0 20px;
}

/* header */
#header {
=09border-bottom:1px solid #eaeaea;
    padding-top:10px;
    padding-left:0px;
    padding-right:0px;
    padding-bottom:10px;
}

#logo {
}

#title {
}

#title p{
=09font-size:20px;
=09font-family: "arial", "sans-serif";
}

#amazonLogo{
=09width:107px;
    height:31px;
}

/* Greeting Summary */
#greetingSummary {
    padding-left:0px;
    padding-right:0px;
    padding-top:9px;
    padding-bottom:18px;
}

#greetingSummary p {
    font-size:14px;
=09font-family: "arial", "sans-serif";
}

#greetingSummary .greeting{
=09font-size:18px;
    line-height:30px;
    color:#cc6600;
}

/* critical info */
#criticalInfo {
    border-top:3px solid #cbcfd4;
    background-color:#f6f7f8;
}

#criticalInfo_left{
    padding-left:18px;
    padding-right:9px;
    padding-top:11px;
    padding-bottom:14px;
}

#criticalInfo_right{
    padding-left:9px;
    padding-right:18px;
    padding-top:11px;
    padding-bottom:14px;
}

#criticalInfo p {
    font-size:14px;
=09font-family: "arial", "sans-serif";
    font-weight:bold;
}

#criticalInfo .label {
=09color:#666;=09
    font-weight:normal;
}

#criticalInfo .info {
    font-weight:normal;
}

#criticalInfo .important {
=09color:#009900;
}

#criticalInfo .subtotals {
=09font-size:12px;
=09font-family: "arial", "sans-serif";
    font-weight:normal;
}

#criticalInfo a {
=09font-weight:normal;
}

#criticalInfo_bottom {
=09padding-left:0px;
    padding-top:9px;
    padding-bottom:9px;
}

#criticalInfo_bottom p {
=09font-size:11px;
=09font-family: "arial", "sans-serif";
}

/* content tables */
#costBreakdown {
=09width:100%;
}

/* cost breakdown */
#costBreakdown td {
=09vertical-align: top;
=09width:100%;
=09text-align:left;
=09font-family: "arial";
}

#costBreakdown .price {
=09font-size:12px;
=09text-align:right;
}

#costBreakdown .text {
=09font-size:12px;
}

#costBreakdown .total {
=09font-size:14px;
=09font-weight:bold;
}

/* closing */
#closing {
    padding-left:0;
    padding-top:9px;
    padding-bottom:9px;
=09border-bottom:1px solid #eaeaea;
}

#closing p {
    font-size:14px;
=09font-family: "arial", "sans-serif";
}

#closing .signature {
=09font-size:14px;=09
=09font-weight:bold;
}

/* marketingContent */
#marketingContent {
=09border-bottom:1px solid #eaeaea;
}

/* footer */
#footer {
=09padding-top:9px;
}

#footer p {
=09color:#666;
=09font-size:10px;
    line-height:16px;
    padding-bottom:10px;
=09font-family: "arial", "sans-serif";

}
</style>=20
  <style type=3D"text/css">
    /* RESET STYLES */
    body { width:100% !important; height:100% !important; margin:0; padding=
:0; }
    table { margin:0 auto !important; }
    table, table td { border-collapse:collapse !important; }
    table th { margin:0 !important; padding:0 !important; font-weight:norma=
l; }
    img { border:0; height:auto; line-height:100%; outline:none; text-decor=
ation:none; }
    a img { border:0 none; }

    * {-webkit-text-size-adjust: none; }

    /* CLIENT-SPECIFIC STYLES */
    body, table, td, a {  -webkit-text-size-adjust:100%; -ms-text-size-adju=
st:100%; }
    /* Prevent WebKit and Windows mobile changing default text sizes */
    .ReadMsgBody { width:100%; } .ExternalClass { width:100%; }
    /* Force Hotmail to display emails at full width */
    .ExternalClass { width:100%; }
    /* Force Hotmail to display normal line spacing */
    .ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass f=
ont, .ExternalClass td, .ExternalClass div { line-height: 100%; }
    /* Force Hotmail to display normal line spacing */
    table, td { mso-table-lspace:0pt; mso-table-rspace:0pt; }
    /* Remove spacing between tables in Outlook 2007 and up */
    img { display:block; -ms-interpolation-mode:bicubic; }
    /* Allow smoother rendering of resized image in Internet Explorer */

    /* PAGE STYLES */
    h1 {display:block; font-size:26px; font-style:normal; font-weight:norma=
l; line-height:100%;}
    h2 {display:block; font-size:20px; font-style:normal; font-weight:norma=
l; line-height:120%;}
    h3 {display:block; font-size:16px; font-style:normal; font-weight:norma=
l; line-height:110%;}
    h4 {display:block; font-size:18px; font-style:italic; font-weight:norma=
l; line-height:100%;}

    /* iOS BLUE LINKS */
    .appleBody a { color:#68440a; text-decoration: none; }
    .appleFooter a { color:#999999; text-decoration: none; }

    /* A nice and clean way to target phone numbers you want clickable and =
avoid a mobile phone from linking other numbers that look like, but are not=
 phone numbers.  Use these two blocks of code to "unstyle" any numbers that=
 may be linked.  The second block gives you a class to apply with a span ta=
g to the numbers you would like linked and styled.
    Inspired by Campaign Monitor's article on using phone numbers in email:=
 http://www.campaignmonitor.com/blog/post/3571/using-phone-numbers-in-html-=
email/.
    */

    .a[href^=3D"tel"], a[href^=3D"sms"] {text-decoration:none!important;col=
or:#606060!important;pointer-events:none!important;cursor:default!important=
;}
    .mobile_link a[href^=3D"tel"], .mobile_link a[href^=3D"sms"] {text-deco=
ration:none!important;color:#606060!important;pointer-events:auto!important=
;cursor:default!important;}

    @media only screen and (max-width: 680px){
        *[class].deviceWidth { width:100% !important; }
        *[class].container { width:90% !important; }
        *[class].width_75 { width:75% !important; }
        *[class].maxwidth200 { max-width:200px !important; }
        *[class].full { width:100% !important; }
    }

    @media only screen and (max-width: 620px){
        *[class].farm { display:none !important; }
        *[class].height140 { height:140px !important; }
        *[class].full { width:100% !important; }
    }

    @media screen and (max-width: 480px){

        /* general classes */
        *[class].hide { display:none !important; }
        *[class].tdwrap { display:inline-block !important; }
        *[class].block_wrap { display:block !important; padding:0 !importan=
t; margin:0 !important;}
        *[class].block { display:block !important; }
        *[class].valignbottom { vertical-align:bottom !important; }
        *[class].valigncenter { vertical-align:middle !important; }
        *[class].rel { position:relative !important; }
        *[class].abs { position:absolute !important; }
        *[class].show { display:block !important; width:auto !important; ov=
erflow:visible !important; float:none !important; max-height:inherit !impor=
tant; line-height:inherit !important; }
        img[class=3D"img-max"] { width:100% !important; height:auto !import=
ant; }

        *[class].bgHero { background-image: url('') !important; }

        *[class].bgefefef { background-color:#efefef !important; }

        *[class].marginr66 { margin-right:66px !Important; }
        *[class].marginl0 { margin-left:0px !Important; }
        *[class].marginl66 { margin-left:66px !Important; }
        *[class].aligncenter { text-align:center !important; }
        *[class].alignleft { text-align:left !important; }
        *[class].font10{ font-size:10px !important; }
        *[class].font11{ font-size:11px !important; line-height:11px !impor=
tant; }
        *[class].font12{ font-size:12px !important; }
        *[class].font13{ font-size:13px !important; }
        *[class].font14{ font-size:14px !important; }
        *[class].font16{ font-size:16px !important; }
        *[class].font20{ font-size:20px !important; }
        *[class].font21{ font-size:21px !important; }
        *[class].lineh16{ line-height:16px !important; }
        *[class].line16{ font-size:16px !important; }
        *[class].line17{ font-size:17px !important; }

        /*widths*/
        *[class].full { width:100% !important; }
        *[class].deviceWidth { width:320px !important; }
        *[class].width100 { width:100px !important; }
        *[class].width300 { width:300px !important; }
        *[class].width320 { width:320px !important; }
        *[class].width_50 { width:50% !important; }
        *[class].width_90 { width:90% !important; }

        /*heights*/
        *[class].hauto { height:auto !important; }
        *[class].height0 { height:0px !important; }

        /*padding*/
        *[class].paddingt10 { padding-top:10px !important; }
        *[class].paddingr0 {padding-right:0px !important; }
        *[class].paddingr10 {padding-right:10px !important; }
        *[class].paddingr20 {padding-right:20px !important; }
        *[class].paddingb5 { padding-bottom:5px !important; }
        *[class].paddingb10 { padding-bottom:10px !important; }
        *[class].paddingb20 { padding-bottom:20px !important; }
        *[class].paddingl0 {padding-left:0px !important; }
        *[class].paddingl10 {padding-left:10px !important; }
        *[class].paddingl20 {padding-left:20px !important; }
        *[class].paddinglr60 {padding-left:60px !important; padding-right:6=
0px !important; }

        /*floats*/
        *[class].fl { float:left !important;    }
        *[class].fr { float:right !important; }
        *[class].wrap { float:block !important; }
        *[class].clear { clear:both !important; }

    }
    @media screen and (device-width: 768px) and (device-height: 1024px) {
        body {min-width: 701px !important;}
    }
</style>=20
  <!--[if gte mso 9]>
<xml>
    <o:OfficeDocumentSettings>
    <o:AllowPNG/>
    <o:PixelsPerInch>96</o:PixelsPerInch>
    </o:OfficeDocumentSettings>
</xml>

<style type=3D"text/css">
    .mm15 { padding:0px !important; margin-left:15px !important; margin-rig=
ht:15px !important; }
    .ml10 { padding:0px !important; margin-left:10px !important; }
    .mr10 { padding:0px !important; margin-right:10px !important; }
</style>
<![endif]-->=20
  <title>Shipping Confirmation</title>=20
 </head>=20
 <body style=3D"width: 100% !important; height: 100% !important; margin: 0;=
 padding: 0; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%"><i=
mg width=3D"1" height=3D"1" src=3D"https://www.amazon.com/gp/r.html?C=3D3JN=
G5JOTKOGN0&K=3DA2SCO4VBODRW03&R=3D3VYJV73QQALTF&T=3DO&U=3Dhttps%3A%2F%2Fima=
ges-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2Fnav%2Ftransp.gif&A=3D1RZYM=
1ABGWJG2ARMGOQCC9JMVLMA&H=3DJKSB8AGOE5VZXZW8R0AWWSSZM64A&ref_=3Dpe_385040_1=
21528360_opens" />=20
  <table align=3D"center" cellspacing=3D"0" id=3D"container" cellpadding=3D=
"0" style=3D"margin: 0 auto !important; border-collapse: collapse !importan=
t; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-ls=
pace: 0pt; mso-table-rspace: 0pt">=20
   <tbody style=3D"-webkit-text-size-adjust: none">
    <tr style=3D"-webkit-text-size-adjust: none">
     <td style=3D"border-collapse: collapse !important; -webkit-text-size-a=
djust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-r=
space: 0pt">=20
      <table cellspacing=3D"0" id=3D"content" cellpadding=3D"0" style=3D"ma=
rgin: 0 auto !important; border-collapse: collapse !important; -webkit-text=
-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-=
table-rspace: 0pt">=20
       <tbody style=3D"-webkit-text-size-adjust: none">
        <tr style=3D"-webkit-text-size-adjust: none">=20
         <td id=3D"header" style=3D"border-collapse: collapse !important; -=
webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace=
: 0pt; mso-table-rspace: 0pt">=20
          <table cellspacing=3D"0" cellpadding=3D"0" style=3D"margin: 0 aut=
o !important; border-collapse: collapse !important; -webkit-text-size-adjus=
t: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspac=
e: 0pt">=20
           <tbody style=3D"-webkit-text-size-adjust: none">
            <tr style=3D"-webkit-text-size-adjust: none">=20
             <td width=3D"250" id=3D"logo" style=3D"border-collapse: collap=
se !important; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; =
mso-table-lspace: 0pt; mso-table-rspace: 0pt"> <a href=3D"https://www.amazo=
n.com/gp/r.html?C=3D3JNG5JOTKOGN0&K=3DA2SCO4VBODRW03&R=3D3VYJV73QQALTF&T=3D=
C&U=3Dhttps%3A%2F%2Fwww.amazon.com%2Fref%3Dpe_385040_121528360_TE_SIMP_&A=
=3DFCTXCEQWLATMR5UCGLJHWMIWANWA&H=3D4PYMCWOAKYQWKVO7J57FRDP7WSOA&ref_=3Dpe_=
385040_121528360_TE_SIMP_" title=3D"Visit Amazon.com" style=3D"-webkit-text=
-size-adjust: 100%; -ms-text-size-adjust: 100%"><img id=3D"amazonLogo" alt=
=3D"Amazon" src=3D"http://g-ecx.images-amazon.com/images/G/01/x-locale/cs/t=
e/logo.png" style=3D"border: 0 none; height: auto; line-height: 100%; outli=
ne: none; text-decoration: none; display: block; -ms-interpolation-mode: bi=
cubic; -webkit-text-size-adjust: none" /></a> </td>=20
             <td width=3D"250" id=3D"title" valign=3D"top" align=3D"right" =
style=3D"border-collapse: collapse !important; -webkit-text-size-adjust: 10=
0%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0p=
t"> <p style=3D"-webkit-text-size-adjust: none">Shipping Confirmation</p> <=
/td>=20
            </tr>=20
           </tbody>
          </table> </td>=20
        </tr>=20
        <tr style=3D"-webkit-text-size-adjust: none">=20
         <td id=3D"greetingSummary" style=3D"border-collapse: collapse !imp=
ortant; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-tab=
le-lspace: 0pt; mso-table-rspace: 0pt"> <p style=3D"-webkit-text-size-adjus=
t: none"> <span class=3D"greeting" style=3D"-webkit-text-size-adjust: none"=
>Hello kyle fisher,</span><br style=3D"-webkit-text-size-adjust: none" /><b=
r style=3D"-webkit-text-size-adjust: none" /> <a href=3D"https://www.amazon=
.com/gp/r.html?C=3D3JNG5JOTKOGN0&K=3DA2SCO4VBODRW03&R=3D3VYJV73QQALTF&T=3DC=
&U=3Dhttps%3A%2F%2Fwww.amazon.com%2Fgp%2Fcss%2Forder-details%3ForderId%3D10=
9-1970879-5671431%26eoid%3D1%253A1%253AGKufm8DvY6ov%252BFw%252F%252FVplDlDC=
OfowwGe3Wu934JBcnuHmfLzNIXkHPjQWItp0hC5JJ9NCs7Wt0LYPIFYaJokE%252F0SLj%252Fg=
Er2UCxKw6n1GpZ%252FW2QXuZj2Bk8R505hBOxn2lqYbToSiwEdPCviuUt8GMVRtc0lyjQGVKsp=
PbTTaT9APRO9tCoD5yFeat9isKsw0nGzyHtoT3UKbU4A%252BoqJbGWDyslD6NUH7Y9uooNHnX2=
2VzCmIjLNc1NwdSIp6WwG9f%252FvOjPiLQ%252BAOdJZYLjYGSO30mNelBzEUdlOxFLF2NNxdG=
pLB5qNar7hGeciVLas%252BcfwmacAtRoGnu8Yo8TOinLQ%253D%253D%26ref_%3Dpe_385040=
_121528360_TE_SIMP_od&A=3DPC66XT6XJXAGBAX5MOR7D1GPF0SA&H=3DDAATP8AJXLFXRDFE=
CCH7OQ0NUZAA&ref_=3Dpe_385040_121528360_TE_SIMP_od" style=3D"-webkit-text-s=
ize-adjust: 100%; -ms-text-size-adjust: 100%">&quot;iCasso - 2 in 1 Wooden.=
..&quot;</a> has shipped. </p> </td>=20
        </tr>=20
        <tr style=3D"-webkit-text-size-adjust: none">=20
         <td style=3D"border-collapse: collapse !important; -webkit-text-si=
ze-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-tab=
le-rspace: 0pt"> <p style=3D"padding-left: 0px; padding-right: 0px; padding=
-top: 0px; padding-bottom: 0px; font: 18px Arial, sans-serif; color: rgb(20=
4, 102, 0); border-bottom: 1px solid rgb(234, 234, 234); -webkit-text-size-=
adjust: none"> Details </p> <p style=3D"font: 14px Arial, sans-serif; color=
: rgb(102, 102, 102); padding-bottom: 5px; padding-top: 5px; -webkit-text-s=
ize-adjust: none"> Order <a href=3D"https://www.amazon.com/gp/r.html?C=3D3J=
NG5JOTKOGN0&K=3DA2SCO4VBODRW03&R=3D3VYJV73QQALTF&T=3DC&U=3Dhttps%3A%2F%2Fww=
w.amazon.com%2Fgp%2Fcss%2Forder-details%3ForderId%3D109-1970879-5671431%26e=
oid%3D1%253A1%253AGKufm8DvY6ov%252BFw%252F%252FVplDlDCOfowwGe3Wu934JBcnuHmf=
LzNIXkHPjQWItp0hC5JJ9NCs7Wt0LYPIFYaJokE%252F0SLj%252FgEr2UCxKw6n1GpZ%252FW2=
QXuZj2Bk8R505hBOxn2lqYbToSiwEdPCviuUt8GMVRtc0lyjQGVKspPbTTaT9APRO9tCoD5yFea=
t9isKsw0nGzyHtoT3UKbU4A%252BoqJbGWDyslD6NUH7Y9uooNHnX22VzCmIjLNc1NwdSIp6WwG=
9f%252FvOjPiLQ%252BAOdJZYLjYGSO30mNelBzEUdlOxFLF2NNxdGpLB5qNar7hGeciVLas%25=
2BcfwmacAtRoGnu8Yo8TOinLQ%253D%253D%26ref_%3Dpe_385040_121528360_TE_SIMP_od=
&A=3DPC66XT6XJXAGBAX5MOR7D1GPF0SA&H=3DDAATP8AJXLFXRDFECCH7OQ0NUZAA&ref_=3Dp=
e_385040_121528360_TE_SIMP_od" style=3D"-webkit-text-size-adjust: 100%; -ms=
-text-size-adjust: 100%">#109-1970879-5671431</a> </p> </td>=20
        </tr>=20
        <tr style=3D"-webkit-text-size-adjust: none">=20
         <td id=3D"criticalInfo" style=3D"border-collapse: collapse !import=
ant; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-=
lspace: 0pt; mso-table-rspace: 0pt">=20
          <table cellspacing=3D"0" cellpadding=3D"0" style=3D"margin: 0 aut=
o !important; border-collapse: collapse !important; -webkit-text-size-adjus=
t: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspac=
e: 0pt">=20
           <tbody style=3D"-webkit-text-size-adjust: none">
            <tr style=3D"-webkit-text-size-adjust: none">=20
             <td width=3D"223" valign=3D"top" id=3D"criticalInfo_left" styl=
e=3D"border-collapse: collapse !important; -webkit-text-size-adjust: 100%; =
-ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt"> =
<p style=3D"-webkit-text-size-adjust: none"> <span class=3D"label" style=3D=
"-webkit-text-size-adjust: none">Arriving:</span><br style=3D"-webkit-text-=
size-adjust: none" /> <span class=3D"important" style=3D"-webkit-text-size-=
adjust: none"> Monday, November 14 </span> </p> <br style=3D"-webkit-text-s=
ize-adjust: none" /> <p style=3D"-webkit-text-size-adjust: none"> <a href=
=3D"https://www.amazon.com/gp/r.html?C=3D3JNG5JOTKOGN0&K=3DA2SCO4VBODRW03&R=
=3D3VYJV73QQALTF&T=3DC&U=3Dhttps%3A%2F%2Fwww.amazon.com%2Fgp%2Fcss%2Fshiptr=
ack%2Fview.html%2Fref%3Dpe_385040_121528360_TE_SIMP_typ%3Fie%3DUTF8%26addre=
ssID%3Djpjptunumn%26latestArrivalDate%3D1479182400%26orderID%3D109-1970879-=
5671431%26shipmentDate%3D1479034487%26orderingShipmentId%3D931863037919%26p=
ackageId%3D1&A=3DBKEQSVO1HTAXZYZD3QNVQBBI1SWA&H=3DFHK0ZAPO41TRJ8RFNRFUJHKX1=
JEA&ref_=3Dpe_385040_121528360_TE_SIMP_typ" style=3D"-webkit-text-size-adju=
st: 100%; -ms-text-size-adjust: 100%"> <img alt=3D"Track your package" id=
=3D"trackYourPackage" src=3D"http://g-ec2.images-amazon.com/images/G/01/x-l=
ocale/cs/te/TrackYourPackage._V320689763_.png" style=3D"border: 0 none; hei=
ght: auto; line-height: 100%; outline: none; text-decoration: none; display=
: block; -ms-interpolation-mode: bicubic; -webkit-text-size-adjust: none" /=
> </a> </p> <br style=3D"-webkit-text-size-adjust: none" /> <p style=3D"-we=
bkit-text-size-adjust: none"> <a href=3D"https://www.amazon.com/gp/r.html?C=
=3D3JNG5JOTKOGN0&K=3DA2SCO4VBODRW03&R=3D3VYJV73QQALTF&T=3DC&U=3Dhttps%3A%2F=
%2Fwww.amazon.com%2Fgp%2Fcss%2Forder-details%3ForderId%3D109-1970879-567143=
1%26eoid%3D1%253A1%253AGKufm8DvY6ov%252BFw%252F%252FVplDlDCOfowwGe3Wu934JBc=
nuHmfLzNIXkHPjQWItp0hC5JJ9NCs7Wt0LYPIFYaJokE%252F0SLj%252FgEr2UCxKw6n1GpZ%2=
52FW2QXuZj2Bk8R505hBOxn2lqYbToSiwEdPCviuUt8GMVRtc0lyjQGVKspPbTTaT9APRO9tCoD=
5yFeat9isKsw0nGzyHtoT3UKbU4A%252BoqJbGWDyslD6NUH7Y9uooNHnX22VzCmIjLNc1NwdSI=
p6WwG9f%252FvOjPiLQ%252BAOdJZYLjYGSO30mNelBzEUdlOxFLF2NNxdGpLB5qNar7hGeciVL=
as%252BcfwmacAtRoGnu8Yo8TOinLQ%253D%253D%26ref_%3Dpe_385040_121528360_TE_SI=
MP_od&A=3DPC66XT6XJXAGBAX5MOR7D1GPF0SA&H=3DDAATP8AJXLFXRDFECCH7OQ0NUZAA&ref=
_=3Dpe_385040_121528360_TE_SIMP_od" style=3D"-webkit-text-size-adjust: 100%=
; -ms-text-size-adjust: 100%"> <img alt=3D"Your Orders" id=3D"yourOrders" s=
rc=3D"http://g-ec2.images-amazon.com/images/G/01/x-locale/cs/te/OrderDetail=
s._V320688448_.png" style=3D"border: 0 none; height: auto; line-height: 100=
%; outline: none; text-decoration: none; display: block; -ms-interpolation-=
mode: bicubic; -webkit-text-size-adjust: none" /> </a> </p> </td>=20
             <td width=3D"223" valign=3D"top" id=3D"criticalInfo_right" sty=
le=3D"border-collapse: collapse !important; -webkit-text-size-adjust: 100%;=
 -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt">=
 <p style=3D"-webkit-text-size-adjust: none"> <span class=3D"label" style=
=3D"-webkit-text-size-adjust: none">Shipped to:</span><br style=3D"-webkit-=
text-size-adjust: none" /> Kyle A. Fisher<br style=3D"-webkit-text-size-adj=
ust: none" /> 316 MCADOO AVE... </p> <br style=3D"-webkit-text-size-adjust:=
 none" />=20
              <table cellspacing=3D"0" cellpadding=3D"0" id=3D"costBreakdow=
n" style=3D"margin: 0 auto !important; border-collapse: collapse !important=
; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lsp=
ace: 0pt; mso-table-rspace: 0pt">=20
               <tbody style=3D"-webkit-text-size-adjust: none">
                <tr style=3D"-webkit-text-size-adjust: none">=20
                 <td style=3D"border-collapse: collapse !important; -webkit=
-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt;=
 mso-table-rspace: 0pt">=20
                  <table id=3D"costBreakdownLeft" style=3D"margin: 0 auto !=
important; border-collapse: collapse !important; -webkit-text-size-adjust: =
100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: =
0pt">=20
                   <tbody style=3D"-webkit-text-size-adjust: none">
                    <tr style=3D"-webkit-text-size-adjust: none">=20
                     <td class=3D"text" style=3D"border-collapse: collapse =
!important; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso=
-table-lspace: 0pt; mso-table-rspace: 0pt"> Total Before Tax: </td>=20
                    </tr>=20
                    <tr style=3D"-webkit-text-size-adjust: none">=20
                     <td class=3D"total" style=3D"border-collapse: collapse=
 !important; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; ms=
o-table-lspace: 0pt; mso-table-rspace: 0pt"> Shipment Total: </td>=20
                    </tr>=20
                   </tbody>
                  </table> </td>=20
                 <td style=3D"border-collapse: collapse !important; -webkit=
-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt;=
 mso-table-rspace: 0pt">=20
                  <table id=3D"costBreakdownRight" style=3D"margin: 0 auto =
!important; border-collapse: collapse !important; -webkit-text-size-adjust:=
 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace:=
 0pt">=20
                   <tbody style=3D"-webkit-text-size-adjust: none">
                    <tr style=3D"-webkit-text-size-adjust: none">=20
                     <td class=3D"price" style=3D"border-collapse: collapse=
 !important; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; ms=
o-table-lspace: 0pt; mso-table-rspace: 0pt"> $21.99 </td>=20
                    </tr>=20
                    <tr style=3D"-webkit-text-size-adjust: none">=20
                     <td class=3D"total" style=3D"border-collapse: collapse=
 !important; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; ms=
o-table-lspace: 0pt; mso-table-rspace: 0pt"> $21.99 </td>=20
                    </tr>=20
                   </tbody>
                  </table> </td>=20
                </tr>=20
               </tbody>
              </table>=20
              <table cellspacing=3D"0" cellpadding=3D"0" style=3D"margin: 0=
 auto !important; border-collapse: collapse !important; -webkit-text-size-a=
djust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-r=
space: 0pt">
               <tbody style=3D"-webkit-text-size-adjust: none">
                <tr style=3D"-webkit-text-size-adjust: none">
                 <td style=3D"border-collapse: collapse !important; -webkit=
-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt;=
 mso-table-rspace: 0pt"> <img align=3D"left" height=3D"1" src=3D"http://g-e=
c2.images-amazon.com/images/G/01/x-locale/cs/te/MagicPixel._V319790361_.png=
" width=3D"222" style=3D"border: 0; height: auto; line-height: 100%; outlin=
e: none; text-decoration: none; display: block; -ms-interpolation-mode: bic=
ubic; -webkit-text-size-adjust: none" /> </td>
                </tr>
               </tbody>
              </table> </td>=20
            </tr>=20
           </tbody>
          </table> </td>=20
        </tr>=20
        <tr style=3D"-webkit-text-size-adjust: none">=20
         <td id=3D"criticalInfo_bottom" style=3D"border-collapse: collapse =
!important; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso=
-table-lspace: 0pt; mso-table-rspace: 0pt"> <p style=3D"-webkit-text-size-a=
djust: none"> </p> </td>=20
        </tr>=20
        <tr style=3D"-webkit-text-size-adjust: none">=20
         <td id=3D"closing" style=3D"border-collapse: collapse !important; =
-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspac=
e: 0pt; mso-table-rspace: 0pt"> <p style=3D"-webkit-text-size-adjust: none"=
>We hope to see you again soon.<br style=3D"-webkit-text-size-adjust: none"=
 /><br style=3D"-webkit-text-size-adjust: none" /> <span class=3D"signature=
" style=3D"-webkit-text-size-adjust: none">Amazon.com</span></p> </td>=20
        </tr>=20
        <tr style=3D"-webkit-text-size-adjust: none">=20
         <td id=3D"marketingContent" style=3D"border-collapse: collapse !im=
portant; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-ta=
ble-lspace: 0pt; mso-table-rspace: 0pt">=20
          <table width=3D"500" cellspacing=3D"0" cellpadding=3D"0" border=
=3D"0" align=3D"left" class=3D"deviceWidth" style=3D"vertical-align: centra=
l; background: white; margin: 0 auto !important; border-collapse: collapse =
!important; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso=
-table-lspace: 0pt; mso-table-rspace: 0pt">
           <tbody style=3D"-webkit-text-size-adjust: none">
            <tr style=3D"-webkit-text-size-adjust: none">
             <td style=3D"border-collapse: collapse !important; -webkit-tex=
t-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso=
-table-rspace: 0pt">=20
              <table width=3D"500" class=3D"devicewidth" cellspacing=3D"0" =
cellpadding=3D"0" align=3D"inherit" bgcolor=3D"#FFFFFF" style=3D"margin: 0 =
auto !important; border-collapse: collapse !important; -webkit-text-size-ad=
just: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rs=
pace: 0pt">=20
               <tbody style=3D"-webkit-text-size-adjust: none">
                <tr style=3D"-webkit-text-size-adjust: none">=20
                 <td style=3D"font-family: Arial, Sans-Serif; font-size: 18=
px; font-weight: normal; font-style: normal; text-decoration: none; color: =
rgb(204, 102, 0); text-align: left; padding: 6px 0 0 0; border-collapse: co=
llapse !important; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 10=
0%; mso-table-lspace: 0pt; mso-table-rspace: 0pt"> Customers Who Bought Ite=
ms in Your Order Also Bought </td>=20
                </tr>=20
               </tbody>
              </table> </td>
            </tr>
            <tr style=3D"-webkit-text-size-adjust: none">
             <td style=3D"border-collapse: collapse !important; -webkit-tex=
t-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso=
-table-rspace: 0pt">=20
              <table width=3D"500" cellspacing=3D"0" cellpadding=3D"0" bord=
er=3D"0" align=3D"left" class=3D"deviceWidth" style=3D"vertical-align: cent=
ral; background: white; margin: 0 auto !important; border-collapse: collaps=
e !important; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; m=
so-table-lspace: 0pt; mso-table-rspace: 0pt">=20
               <tbody style=3D"-webkit-text-size-adjust: none">
                <tr style=3D"-webkit-text-size-adjust: none">=20
                 <td width=3D"48%" bgcolor=3D"#ffffff" align=3D"left" class=
=3D"asin_2col" style=3D"vertical-align: middle; border-collapse: collapse !=
important; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-=
table-lspace: 0pt; mso-table-rspace: 0pt">=20
                  <table style=3D"margin: 0 auto !important; border-collaps=
e: collapse !important; -webkit-text-size-adjust: 100%; -ms-text-size-adjus=
t: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt">=20
                   <tbody style=3D"-webkit-text-size-adjust: none">
                    <tr style=3D"-webkit-text-size-adjust: none">=20
                     <td align=3D"center" style=3D"padding: 12px 5px 10px 5=
px; vertical-align: middle; border-collapse: collapse !important; -webkit-t=
ext-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; m=
so-table-rspace: 0pt"> <a href=3D"https://www.amazon.com/gp/r.html?C=3D3JNG=
5JOTKOGN0&K=3DA2SCO4VBODRW03&R=3D3VYJV73QQALTF&T=3DC&U=3Dhttps%3A%2F%2Fwww.=
amazon.com%2Fgp%2Fproduct%2FB00XJBDC70%2Fref%3Dpe_385040_121528360_pd_te_s_=
gr_im%2F156-5802963-0262834&A=3DLYX3AUSCP863HLZJ15DAV8A9YKEA&H=3DZB4NWRSLHK=
CH2HY6JOIHF30GBNMA&ref_=3Dpe_385040_121528360_pd_te_s_gr_im" style=3D"-webk=
it-text-size-adjust: 100%; -ms-text-size-adjust: 100%"> <img src=3D"https:/=
/images-na.ssl-images-amazon.com/images/I/61-3BxyV0RL._AC_SL500_SS80_.jpg" =
width=3D"80" height=3D"80" class=3D"pr_image_80 pr_image_desktop" alt=3D"In=
ateck 15-15.4 Inch MacBook Pro / Pro Retina Case Sleeve Cover Ultrabook Net=
book Laptop Bag - Dark Gray" border=3D"0" style=3D"border: 0 none; height: =
auto; line-height: 100%; outline: none; text-decoration: none; display: blo=
ck; -ms-interpolation-mode: bicubic; -webkit-text-size-adjust: none" /> </a=
> </td>=20
                     <td align=3D"left" style=3D"padding: 12px 5px 10px 5px=
; vertical-align: middle; border-collapse: collapse !important; -webkit-tex=
t-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso=
-table-rspace: 0pt">=20
                      <table style=3D"margin: 0 auto !important; border-col=
lapse: collapse !important; -webkit-text-size-adjust: 100%; -ms-text-size-a=
djust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt">=20
                       <tbody style=3D"-webkit-text-size-adjust: none">
                        <tr align=3D"left" style=3D"-webkit-text-size-adjus=
t: none">=20
                         <td style=3D"border-collapse: collapse !important;=
 -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspa=
ce: 0pt; mso-table-rspace: 0pt"> <a href=3D"https://www.amazon.com/gp/r.htm=
l?C=3D3JNG5JOTKOGN0&K=3DA2SCO4VBODRW03&R=3D3VYJV73QQALTF&T=3DC&U=3Dhttps%3A=
%2F%2Fwww.amazon.com%2Fgp%2Fproduct%2FB00XJBDC70%2Fref%3Dpe_385040_12152836=
0_pd_te_s_gr_ti%2F156-5802963-0262834&A=3DF758CKHW9QCQ6JE042KSKMKUEZYA&H=3D=
1UI5X62ZTPSADT8A1CK944AX8DKA&ref_=3Dpe_385040_121528360_pd_te_s_gr_ti" styl=
e=3D"font-family: Arial, Sans-Serif; text-decoration: none; color: rgb(136,=
 136, 136); font-size: 13px; font: 13px Arial, Sans-Serif; -webkit-text-siz=
e-adjust: 100%; -ms-text-size-adjust: 100%">Inateck 15-15.4 Inch MacBook Pr=
o...</a> </td>=20
                        </tr>=20
                        <tr align=3D"left" style=3D"-webkit-text-size-adjus=
t: none">=20
                         <td style=3D"border-collapse: collapse !important;=
 -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspa=
ce: 0pt; mso-table-rspace: 0pt"> <span style=3D"font-family: Arial, Sans-Se=
rif; text-decoration: none; color: rgb(136, 136, 136); font-size: 13px; ver=
tical-align: 3px; -webkit-text-size-adjust: none"> $19.99 </span> <span sty=
le=3D"vertical-align: 0px; -webkit-text-size-adjust: none"></span> </td>=20
                        </tr>=20
                       </tbody>
                      </table> </td>=20
                    </tr>=20
                   </tbody>
                  </table> </td>=20
                 <td width=3D"48%" bgcolor=3D"#ffffff" align=3D"left" class=
=3D"asin_2col" style=3D"vertical-align: middle; border-collapse: collapse !=
important; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-=
table-lspace: 0pt; mso-table-rspace: 0pt">=20
                  <table style=3D"margin: 0 auto !important; border-collaps=
e: collapse !important; -webkit-text-size-adjust: 100%; -ms-text-size-adjus=
t: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt">=20
                   <tbody style=3D"-webkit-text-size-adjust: none">
                    <tr style=3D"-webkit-text-size-adjust: none">=20
                     <td align=3D"center" style=3D"padding: 12px 5px 10px 5=
px; vertical-align: middle; border-collapse: collapse !important; -webkit-t=
ext-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; m=
so-table-rspace: 0pt"> <a href=3D"https://www.amazon.com/gp/r.html?C=3D3JNG=
5JOTKOGN0&K=3DA2SCO4VBODRW03&R=3D3VYJV73QQALTF&T=3DC&U=3Dhttps%3A%2F%2Fwww.=
amazon.com%2Fgp%2Fproduct%2FB015NSL4XK%2Fref%3Dpe_385040_121528360_pd_te_s_=
gr_im%2F156-5802963-0262834&A=3DVCPZIUOFMIZVQ2B2Z4JDYME3OKYA&H=3DKYMQNNHVCA=
9TZ4ZKTD5S5VMXJCWA&ref_=3Dpe_385040_121528360_pd_te_s_gr_im" style=3D"-webk=
it-text-size-adjust: 100%; -ms-text-size-adjust: 100%"> <img src=3D"https:/=
/images-na.ssl-images-amazon.com/images/I/51apHSSm7WL._AC_SL500_SS80_.jpg" =
width=3D"80" height=3D"80" class=3D"pr_image_80 pr_image_desktop" alt=3D"Ma=
cBook Pro 15 Sleeve, GMYLE Sleeve Felt for MacBook Pro 15 - Dark Grey &amp;=
 Brown Soft Sleeve Bag Case Cover" border=3D"0" style=3D"border: 0 none; he=
ight: auto; line-height: 100%; outline: none; text-decoration: none; displa=
y: block; -ms-interpolation-mode: bicubic; -webkit-text-size-adjust: none" =
/> </a> </td>=20
                     <td align=3D"left" style=3D"padding: 12px 5px 10px 5px=
; vertical-align: middle; border-collapse: collapse !important; -webkit-tex=
t-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso=
-table-rspace: 0pt">=20
                      <table style=3D"margin: 0 auto !important; border-col=
lapse: collapse !important; -webkit-text-size-adjust: 100%; -ms-text-size-a=
djust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt">=20
                       <tbody style=3D"-webkit-text-size-adjust: none">
                        <tr align=3D"left" style=3D"-webkit-text-size-adjus=
t: none">=20
                         <td style=3D"border-collapse: collapse !important;=
 -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspa=
ce: 0pt; mso-table-rspace: 0pt"> <a href=3D"https://www.amazon.com/gp/r.htm=
l?C=3D3JNG5JOTKOGN0&K=3DA2SCO4VBODRW03&R=3D3VYJV73QQALTF&T=3DC&U=3Dhttps%3A=
%2F%2Fwww.amazon.com%2Fgp%2Fproduct%2FB015NSL4XK%2Fref%3Dpe_385040_12152836=
0_pd_te_s_gr_ti%2F156-5802963-0262834&A=3D8VLYL8SJZCIEOWMPLCODCAXRQEIA&H=3D=
YAXN1DA6VVR4ZAY5YFWDXJAFJOWA&ref_=3Dpe_385040_121528360_pd_te_s_gr_ti" styl=
e=3D"font-family: Arial, Sans-Serif; text-decoration: none; color: rgb(136,=
 136, 136); font-size: 13px; font: 13px Arial, Sans-Serif; -webkit-text-siz=
e-adjust: 100%; -ms-text-size-adjust: 100%">MacBook Pro 15 Sleeve, GMYLE Sl=
eeve...</a> </td>=20
                        </tr>=20
                        <tr align=3D"left" style=3D"-webkit-text-size-adjus=
t: none">=20
                         <td style=3D"border-collapse: collapse !important;=
 -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspa=
ce: 0pt; mso-table-rspace: 0pt"> <span style=3D"font-family: Arial, Sans-Se=
rif; text-decoration: none; color: rgb(136, 136, 136); font-size: 13px; ver=
tical-align: 3px; -webkit-text-size-adjust: none"> $20.98 </span> <span sty=
le=3D"vertical-align: 0px; -webkit-text-size-adjust: none"></span> </td>=20
                        </tr>=20
                       </tbody>
                      </table> </td>=20
                    </tr>=20
                   </tbody>
                  </table> </td>=20
                </tr>=20
               </tbody>
              </table> </td>
            </tr>
           </tbody>
          </table> </td>=20
        </tr>=20
        <tr style=3D"-webkit-text-size-adjust: none">=20
         <td id=3D"footer" style=3D"border-collapse: collapse !important; -=
webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace=
: 0pt; mso-table-rspace: 0pt"> <p style=3D"-webkit-text-size-adjust: none">=
Unless otherwise noted, items sold by Amazon.com LLC are subject to sales t=
ax in select states in accordance with the applicable laws of that state. I=
f your order contains one or more items from a seller other than Amazon.com=
 LLC, it may be subject to state and local sales tax, depending upon the se=
llers business policies and the location of their operations. Learn more ab=
out <a href=3D"https://www.amazon.com/gp/r.html?C=3D3JNG5JOTKOGN0&K=3DA2SCO=
4VBODRW03&R=3D3VYJV73QQALTF&T=3DC&U=3Dhttp%3A%2F%2Fwww.amazon.com%2Fgp%2Fhe=
lp%2Fcustomer%2Fdisplay.html%2Fref%3Dpe_385040_121528360_TE_SIMP_tx%3Fie%3D=
UTF8%26nodeId%3D200962600&A=3DOKT8JPAHTPGFES8TTNJN5RTFTFMA&H=3DSWMQDQM6HAPT=
P2HG8XIISGPVZNWA&ref_=3Dpe_385040_121528360_TE_SIMP_tx" style=3D"-webkit-te=
xt-size-adjust: 100%; -ms-text-size-adjust: 100%">tax and seller informatio=
n</a>.</p> <p style=3D"-webkit-text-size-adjust: none"> Your invoice can be=
 accessed <a href=3D"https://www.amazon.com/gp/f.html?C=3D3JNG5JOTKOGN0&K=
=3DA2SCO4VBODRW03&R=3D3VYJV73QQALTF&T=3DC&U=3Dhttps%3A%2F%2Fwww.amazon.com%=
2Fgp%2Fcss%2Fsummary%2Fprint.html%3ForderID%3D109-1970879-5671431%26ref_%3D=
pe_385040_121528360_TE_SIMP_inv&A=3DFFMWQA6BFQE2E7WJP9KKSAHALGKA&H=3DZRRIMQ=
FBUODWGJS8NVZWEZJB28GA&ref_=3Dpe_385040_121528360_TE_SIMP_inv" style=3D"-we=
bkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%">here</a>. </p> <p =
style=3D"-webkit-text-size-adjust: none"> This email was sent from a notifi=
cation-only address that cannot accept incoming email. Please do not reply =
to this message. </p> </td>=20
        </tr>=20
       </tbody>
      </table> </td>
    </tr>=20
   </tbody>
  </table> =20
 <img width=3D"1" height=3D"1" src=3D"https://www.amazon.com/gp/r.html?C=3D=
3JNG5JOTKOGN0&K=3DA2SCO4VBODRW03&R=3D3VYJV73QQALTF&T=3DE&U=3Dhttps%3A%2F%2F=
images-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2Fnav%2Ftransp.gif&A=3DKY=
DA85ASYFEKIRQEAO95IJBGAZAA&H=3D67VSLMRGQJIPSS7AGEMVQYQDS7AA&ref_=3Dpe_38504=
0_121528360_open" /></body>
</html>
------=_Part_9636008_919664584.1479034558489--

