From d8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2@bounce.r.groupon.com Sat Nov 12 03:19:59 2016
Received: from mta106s1.r.groupon.com ([50.115.211.244]:8816)
	by ecbiz209.inmotionhosting.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <d8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2@bounce.r.groupon.com>)
	id 1c5TXa-002Qh7-Q3
	for kyle@kylefisher.com; Sat, 12 Nov 2016 03:19:59 -0500
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=r.groupon.com;
	s=s2048d20160829; t=1478938797;
	bh=Sx56qJrU51dh5xIdpdt257vBeTkHAzzm7Cz2QA9qk60=;
	h=Date:From:To:Message-ID:Subject:Content-Type;
	b=cCSfpjX45mTpyH6AHXXHELlzJPGMofdxO+IxT3iW292ahwZ17J5we9s8Nn58fYarM
	 Ui/eDssEbjVrIjNAyPFDTWGRbDyM0EDFhhTFnZxVTbnWlCm2GYK5U9IGydaIhsYgrU
	 8EII26qCZS9WtPEKxAJ0vkUuwFmQ7dA0j74YEqZgN5VxwoMO2wYIwbOMamkKoG7mOI
	 sitDZj9CHTQO//Va/++6VJo1gFVIUHgbp8Pql0qOeGcg4RDhv9bpIM8oxHwPe4sP7k
	 8ATAHwsqFWHjBOUKn/j2RefB18FUGQwZU31/wKCNB2anX1p028KhLXWFe0sQxM7ZPR
	 vVtM3qb269UaQ==
Date: Sat, 12 Nov 2016 08:19:57 +0000
From: Groupon Doorbusters <noreply@r.groupon.com>
To: kyle@kylefisher.com
Message-ID: <175351284.26429113.1478938797129.JavaMail.rocketman@push-dispatcher5>
Subject: Final Hours of 12 Days of Doorbusters
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
X-RM-UserHash: d8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2
X-RM-SendId: eb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112
X-RM-SenderScore: 0
X-RM-EmailName: crm_ils_goods_us_im_20161112_LowAffinity_Manual_10_Doorbusters
X-MSFBL: a3lsZUBreWxlZmlzaGVyLmNvbTpiYXRjaDplYjQxY2FjYy01MzZmLTRkZmEtYWI3MC1mNWFiMzA2ZWM2ZjBfMF8yMDE2MTExMjpudWxsOlVT
List-Unsubscribe: <mailto:d8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2@unsub.r.groupon.com?subject=a3lsZUBreWxlZmlzaGVyLmNvbTpiYXRjaDplYjQxY2FjYy01MzZmLTRkZmEtYWI3MC1mNWFiMzA2ZWM2ZjBfMF8yMDE2MTExMjpudWxsOlVT>
X-RPCampaign: Grouponcrmilsgoodsusim20161112LowAffinityManual10Doorbusters20161112
X-RPTags: crm_ils_goods_us_im_20161112_LowAffinity_Manual_10_Doorbusters
X-Recruiting: Interested in headers? Join us: www.groupon.com/techjobs/
List-Id: <crm_ils_goods_us_im_20161112_LowAffinity_Manual_10_Doorbusters_20161112.groupon>
X-Feedback-ID: r.groupon.com:crm_ils_goods_us_im_20161112_LowAffinity_Manual_10_Doorbusters:eb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112:groupon

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.=
w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> <html xmlns=3D"http://www.w3=
.org/1999/xhtml" xmlns:v=3D"urn:schemas-microsoft-com:vml" xmlns:o=3D"urn:s=
chemas-microsoft-com:office:office"> <head> <meta http-equiv=3D"Content-Typ=
e" content=3D"text/html; charset=3Dutf-8" /> <title>Groupon</title> <style =
type=3D"text/css"> .ExternalClass * {line-height: 100%} /* override ios min=
imum font-size*/ div, p, a, li, td { -webkit-text-size-adjust:none; } img[c=
lass=3D"100"]{ width: 100% !important; min-width: 100% !important; max-widt=
h: 100% !important; } table { font-family: 'Open Sans', Arial, sans-serif !=
important; } @media only screen and (max-width: 580px) { table[class=3D"con=
tainer"]{ margin: 0 auto !important; width: 100% !important; min-width: 100=
% !important; } td[class=3D"container"]{ width: 100% !important; min-width:=
 100% !important; float: left !important; position: relative !important; pa=
dding: 0px !important; } td[class=3D"100"]{ width: 100% !important; min-wid=
th: 100% !important; height: auto !important; float: left !important; } td[=
class=3D"mobile-hdr-logo-center"]{ padding: 25px 0 10px 0 !important; } /* =
Image Classes */ img[class=3D"100"]{ width: 100% !important; min-width: 100=
% !important; max-width: 100% !important; } /* Col Sections */ *[class=3D"c=
ollapse-left"]{ width: 100% !important; float: left !important; position: r=
elative !important; padding: 20px 0 20px 0 !important; border-bottom: 1px s=
olid #cccccc !important; } *[class=3D"collapse-right"]{ width: 100% !import=
ant; float: left !important; position: relative !important; padding: 20px 0=
 20px 0 !important; border: none !important; } *[class=3D"collapse-left-rtl=
"]{ width: 100% !important; float: left !important; position: relative !imp=
ortant; padding: 20px 0 20px 0 !important; border: none !important; } *[cla=
ss=3D"collapse-right-rtl"]{ width: 100% !important; float: left !important;=
 position: relative !important; padding: 20px 0 20px 0 !important; border-b=
ottom: 1px solid #cccccc !important; } td[class=3D"collapse-trxn"]{ width: =
100% !important; float: left !important; position: relative !important; pad=
ding: 30px 0 0 0 !important; } td[class=3D"container-33"] { min-width: 33% =
!important; } td[class=3D"col-4-mobile"]{ width: 65% !important; } td[class=
=3D"mobile-container-padding"]{ padding: 20px 10px 20px 10px !important; } =
td.ga-mobile-pad { padding: 20px 0 15px 10px !important; } /* GA Partity, W=
eekend, Live! needs to be removed */ td[class=3D"weekend-mobile-container-p=
adding"]{ padding: 0px 10px 20px 10px !important; } td[class=3D"mobile-cont=
ainer-nav-padding"]{ padding: 10px 0 10px 0 !important; } /* Goods Parity H=
eader */ td[class=3D"floatLeft-ship"]{ float: left !important; width: 100% =
!important; border: 0px none !important; text-align: left !important; paddi=
ng: 5px 0 15px 0 !important; line-height: 14px !important; font-size: 13px =
!important; } td[class=3D"floatLeft-name"]{ float: left !important; width: =
100% !important; border: 0px none !important; text-align: left !important; =
padding: 5px 0 5px 0 !important; line-height: 14px !important; font-weight:=
 bold !important; font-size: 13px !important; } /* Turn off desktop CSS */ =
td[class=3D"no-padding"]{ padding: 0px !important; } td[class=3D"no-border-=
no-padding"]{ padding: 0px !important; border: none !important; } .no-borde=
r { border: none !important; } *[class=3D"display-off"]{ display: none !imp=
ortant; } /*Goods Shipment Notification and Transaction Failed */ td[class=
=3D"shipment-col-4-mobile"]{ width: 50% !important; } /*Welcome Day 0 Redes=
ign */ *[class=3D"container-white"]{ width: 100% !important; background-col=
or: #ffffff !important; padding: 0 0 0 0 !important; } *[class=3D"textAlign=
Center"]{ text-align: center !important; } /* Buttons */ table[class=3D"but=
ton-width"]{ width: 80px !important; } td[class=3D"viewButtonMobile"]{ padd=
ing: 12px 10px 12px 10px !important; } /* Banners */ *[class=3D"mobile-bann=
er"]{ width: 100%!important; max-height: none!important; height: auto!impor=
tant; display: block!important; padding: 20px 0 0 0!important; color: #0000=
00!important; font-size: 32px!important; line-height: 24px !important; } *[=
class=3D"mobile-banner-img"]{ width: 100%!important; max-height: none!impor=
tant; height: auto!important; display:block!important; padding: 0 0 0 0!imp=
ortant; color: #000000!important; font-size: 12px!important; } *[class=3D"m=
obile-banner-img-pad"]{ width: 100%!important; max-height: none!important; =
height: auto!important; display:block!important; padding: 0 0 10px 0!import=
ant; color: #000000!important; font-size: 12px!important; } *[class=3D"2up-=
image-mobile"]{ width: 100% !important; max-height: none!important; height:=
 auto!important; display: block!important; float: left !important; } /* Use=
r Messaging Service */ *[class=3D"heading_style"]{ -webkit-text-size-adjust=
:none !important; font-size:13px !important; font-style:normal !important; =
font-variant:normal !important; font-weight:normal !important; font-family:=
Arial, Verdana, sans-serif !important; color:#cdf5ff !important; line-heigh=
t:18px !important; } /* Font Classes */ td[class=3D"mobile-font"]{ font-siz=
e: 13px !important; } span[class=3D"nameFont"]{ font-size: 18px !important;=
 line-height: 22px !important; } td[class=3D"nameFont"]{ font-size: 18px !i=
mportant; line-height: 22px !important; } td[class=3D"themeFont"]{ font-siz=
e: 30px !important; line-height: 34px !important; } td[class=3D"heroNameFon=
t"]{ font-size: 18px !important; line-height: 22px !important; } a[class=3D=
"heroNameFont"]{ text-decoration: none !important; font-size: 18px !importa=
nt; line-height: 22px !important; } *[class=3D"font-12"]{ font-size:12px !i=
mportant; } *[class=3D"font-13"]{ font-size:13px !important; } *[class=3D"f=
ont-16"]{ font-size:16px !important; } *[class=3D"font-18"]{ font-size:18px=
 !important; } img[class=3D"glive-deal-image"]{ width: 80% !important; heig=
ht: auto !important; display: block; margin:0 auto; padding: 0; } div[class=
=3D"gmailfix"] { display: none; display: none !important; } td[class=3D"mob=
ile-padding-logo"]{ padding: 0 0 0 0 !important; width: 195px !important; }=
 table[class=3D"heroButton"]{ width: 120px !important; } table[class=3D"her=
oButton"]{ width: 120px !important; } *[class=3D"mobile-padding-font"]{ pad=
ding: 0 0 0 0 !important; font-size: 10px !important; font-weight:normal !i=
mportant; } *[class=3D"mobile-padding-font-purchase"]{ padding: 0 0 0 0 !im=
portant; font-size: 9px !important; font-weight:normal !important; } td[cla=
ss=3D"header-text"]{ text-align: left !important; } td[class=3D"collapse-le=
ft-postcard"]{ width: 100% !important; float: left !important; position: re=
lative !important; padding: 20px 0 20px 0 !important; } table[class=3D"seo-=
button-width"]{ width: 158px !important; } table[class=3D"container_border"=
]{ width: 100% !important; padding: 0 0 0 0 !important; } *[class=3D"margin=
_zero_auto"]{ margin: 0 auto !important; display: block !important; } *[cla=
ss=3D"text_pad"]{ padding:7px 0 0 0 !important; } *[class=3D"display_table"=
]{ display: block !important; width:100% !important; } } </style> <link hre=
f=3D'https://fonts.googleapis.com/css?family=3DOpen+Sans:100,200,400,300,50=
0,600,700,800' rel=3D'stylesheet' type=3D'text/css' /> <!--[if mso]> <style=
> body,table tr,table td,a, span {font-family:Arial, Helvetica, sans-serif =
!important;}</style> <!--<![endif]--> </head> <body style=3D"margin:0 !impo=
rtant; padding:0 !important; background: #f2f2f2 !important;"> <img src =3D=
 "http://www.groupon.com/analytic/track.gif?p=3D1&utm_domain=3Dkylefisher.c=
om&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112&deals=3De=
4b86602-8fff-11e6-b02a-002590604002,4e681656-9ac3-11e6-904b-002590604002,65=
f812b6-2d2d-4ef3-8240-7aa13cc64f74,1dd7fefc-9145-11e6-a174-00259060b5da,861=
8b342-20fe-11e6-9a20-00259069d868,72678418-8a58-11e6-bcd0-00259060b5da,412a=
9e8a-655f-11e6-ad73-00259069d7cc,84515d72-6f9e-11e6-8848-00259060b5da,82a6e=
e0c-e159-11e5-a001-00259098451c,d709a94a-9585-11e6-a59f-002590604002,394ff1=
12-90c3-11e6-b6f6-00259069d868,c0da0158-8688-11e6-9a35-00259060b5da,b8a5d69=
4-924d-11e6-9063-00259060b5da,b705037a-6b8c-11e5-9189-002590980a98,d799a6dd=
-bce0-4ad3-9ffe-66824bdd6b67,8d79dee2-28fe-11e6-a577-002590604002&channel_d=
eals=3Dnull&utm_source=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf=
03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=
=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS" height=3D"1" width=3D"1" =
style=3D"display: none !important;" /> <table cellpadding=3D"0" cellspacing=
=3D"0" style=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans'=
, Arial, sans-serif; color:#000000; font-weight: normal; text-align: left; =
width:100%; background: #f2f2f2;" width=3D"100%" bgcolor=3D"#f2f2f2" align=
=3D"center"> <tr> <td align=3D"center"> <span style=3D"color: #f2f2f2; font=
-size: 0px !important;" height=3D"0"> </span> <table cellpadding=3D"0" cell=
spacing=3D"0" style=3D"width:670px; background: #ffffff;" width=3D"670" ali=
gn=3D"center" class=3D"container"> <tr> <td align=3D"center" style=3D"paddi=
ng: 10px 10px 0 10px;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D=
"width: 600px;" width=3D"600" align=3D"center" class=3D"container"> <tr> <t=
d style=3D"padding: 10px 0 10px 0;"> <table cellpadding=3D"0" cellspacing=
=3D"0" style=3D"width: 257px;" width=3D"257" align=3D"left" class=3D"contai=
ner"> <tr> <td align=3D"left" style=3D"width: 257px;" class=3D"mobile-paddi=
ng-logo"><a href=3D"http://www.groupon.com/goods?utm_source=3Dchannel_goods=
&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac1=
34cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&=
CID=3DUS&s=3Dheader&c=3Dimage&d=3DGroupon&utm_campaign=3Deb41cacc-536f-4dfa=
-ab70-f5ab306ec6f0_0_20161112" style=3D"font-size: 34px; color: #333333; fo=
nt-weight: normal; font-weight: 700;" target=3D"_blank"><img src=3D"http://=
s3.grouponcdn.com/email/images/prom_night/global_images/pn-groupon-logo-gre=
en.png" style=3D"display: block; border: none; width:257px;" alt=3D"GROUPON=
&reg;" title=3D"GROUPON&reg;" class=3D"100"></a> </td> </tr> </table> </td>=
 <td align=3D"right" valign=3D"middle" style=3D"padding-left:10px;" valign=
=3D"bottom"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"width: 100=
px;" width=3D"100" align=3D"right"> <tr> <td align=3D"right" style=3D"white=
-space:nowrap;"><a href=3D"http://www.facebook.com/groupon" style=3D"color:=
#0185C6; text-decoration:none;" target=3D"_blank"><img src=3D"http://s3.gro=
uponcdn.com/email/images/mindstorm/social/icon-facebook-white.png" style=3D=
"display: block; border: none; display: inline-block;" /></a>&nbsp;<a href=
=3D"http://www.twitter.com/groupon" style=3D"color:#0185C6; text-decoration=
:none;" target=3D"_blank"><img src=3D"http://s3.grouponcdn.com/email/images=
/mindstorm/social/icon-twitter-white.png" style=3D"display: block; border: =
none; display: inline-block;" />&nbsp;</a><a href=3D"http://www.pinterest.c=
om/groupon" style=3D"color:#0185C6; text-decoration:none;" target=3D"_blank=
"><img src=3D"http://s3.grouponcdn.com/email/images/mindstorm/social/icon-p=
interest-white.png" style=3D"display: block; border: none; display: inline-=
block;" /></a></td> </tr> </table> </td> </tr> <tr> <td colspan=3D"2" style=
=3D"border-top: 1px solid #cccccc;"> <table cellpadding=3D"0" cellspacing=
=3D"0" style=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans'=
, Arial, sans-serif; color:#000000; font-weight: normal; text-align: left; =
width: 100%;" align=3D"center" class=3D"container"> <tr> <td style=3D"paddi=
ng: 10px 0 10px 0;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"bo=
rder: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, sans-seri=
f; color:#000000; font-weight: normal; text-align: left; width: 100%;" alig=
n=3D"center" class=3D"container"> <tr> <td colspan=3D"2" class=3D"floatLeft=
-name" style=3D"width: 40%; font-size: 14px; color: #6d6d6d; font-weight: 5=
00;" align=3D"left">For Kyle | November 12, 2016</td> </tr> </table> </td> =
</tr> </table> </td> </tr> </table> </td> </tr> </table> </td> </tr> </tabl=
e> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"width: 100%; backgro=
und: #f2f2f2" align=3D"center"> <tr> <td align=3D"center"> <table cellpaddi=
ng=3D"0" cellspacing=3D"0" style=3D"width: 670px; background: #ffffff;" bgc=
olor=3D"#ffffff" align=3D"center" class=3D"container"> <tr> <td align=3D"ce=
nter"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"width: 600px; mi=
n-width:600px; background: #ffffff;" bgcolor=3D"#ffffff" align=3D"center" c=
lass=3D"container"> <tr> <td align=3D"center" style=3D"padding: 5px 0 40px =
0;" class=3D"mobile-container-padding"> <table cellpadding=3D"0" cellspacin=
g=3D"0" style=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans=
', Arial, sans-serif; color:#000000; font-weight: normal; text-align: left;=
 width: 100%; background-color: #ffffff;" align=3D"center"> <tr> <td style=
=3D"padding: 0px; display:none; font-size:0; max-height:0; line-height:0; m=
so-hide: all;" class=3D"mobile-banner"><a href=3D"https://www.groupon.com/o=
ccasion/doorbusters?p=3D1&utm_source=3Dchannel_goods&utm_medium=3Demail&use=
r=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=
=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=
=3Dbanner&d=3Ddynamic-banner-0&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab3=
06ec6f0_0_20161112" style=3D"color:#0185C6; text-decoration:none;" target=
=3D"_blank"> <img src=3D"https://img.grouponcdn.com/deal/3MXbyXq1MZnHTfUU2j=
88VEbDB2m2/3M-460x307.jpg" style=3D"padding:0px; display:none; font-size:0;=
 max-height:0; line-height:0; mso-hide: all;" class=3D"mobile-banner-img" a=
lt=3D"Groupon" /></a> </td> </tr> </table> <table cellpadding=3D"0" cellspa=
cing=3D"0" style=3D"border: 0 none; border-spacing: 0; font-family: 'Open S=
ans', Arial, sans-serif; color:#000000; font-weight: normal; text-align: le=
ft; width: 100%; min-width:290px; background-color: #ffffff;" align=3D"cent=
er" class=3D"display-off"> <tr> <td align=3D"center" style=3D"padding: 20px=
 0 0 0; min-width:290px;"><a href=3D"https://www.groupon.com/occasion/doorb=
usters?p=3D1&utm_source=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8b=
f03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=
=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbanner&d=3Ddy=
namic-banner-0&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_201611=
12" style=3D"color:#0185C6; text-decoration:none;" target=3D"_blank"> <img =
src=3D"https://img.grouponcdn.com/deal/nv37fzH2qX1z2wNKiJSCiekpo4u/nv-600x4=
00.jpg" style=3D"display: block; border: none; min-width:290px;" alt=3D"Gro=
upon" /></a> </td> </tr> </table> <table cellpadding=3D"0" cellspacing=3D"0=
" border=3D"0" style=3D"border: 0 none; border-spacing: 0; font-family: 'Op=
en Sans', Arial, sans-serif; color:#000000; font-weight: normal; text-align=
: left; width:600px; min-width:600px; background: #FFFFFF;" align=3D"center=
" class=3D"container"> <tr> <td align=3D"left" width=3D"100%" style=3D"widt=
h: 600px; min-width:600px;" class=3D"100"> <table cellpadding=3D"0" cellspa=
cing=3D"0" border=3D"0" style=3D"border: 0 none; border-spacing: 0; font-fa=
mily: 'Open Sans', Arial, sans-serif; color:#000000; font-weight: normal; t=
ext-align: left; width: 600px; min-width:600px;" class=3D"container"> <tr> =
<td valign=3D"top" align=3D"left" width=3D"100%" style=3D"width: 600px; min=
-width:600px;" class=3D"100"> <!--[if (gte mso 9)|(IE)]> <table width=3D"60=
0" align=3D"center" cellpadding=3D"0" cellspacing=3D"0" border=3D"0"> <tr> =
<![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https:=
//www.groupon.com/deals/gg-elite-or-mini-orion-24ghz-45ch-hd-rc-camera-dron=
es?p=3D2&utm_source=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03c=
f574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df7=
9c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-P=
N&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" target=3D=
"_blank" style=3D"color: #000000; font-size: 14px !important; line-height: =
18px !important; color:#000000 !important; text-decoration: none;"> <table =
valign=3D"top" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"bo=
rder: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, sans-seri=
f; color:#000000; font-weight: normal; text-align: left; width:290px; mso-t=
able-lspace:0;mso-table-rspace:0;" width=3D"290" align=3D'left' class=3D"co=
ntainer"> <tr> <td valign=3D"top" width=3D"100%" style=3D"mso-table-lspace:=
0;mso-table-rspace:0; width:100%; padding:20px 0 0 0;"> <table cellpadding=
=3D"0" cellspacing=3D"0" border=3D"0" style=3D"width:100%;" width=3D"100%">=
 <tr> <td valign=3D"top" align=3D"center" width=3D"290" style=3D"width:290p=
x;" class=3D"container"><a href=3D"https://www.groupon.com/deals/gg-elite-o=
r-mini-orion-24ghz-45ch-hd-rc-camera-drones?p=3D2&utm_source=3Dchannel_good=
s&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac=
134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe=
&CID=3DUS&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Deb41cacc-536f-4dfa=
-ab70-f5ab306ec6f0_0_20161112" style=3D"display: block; border: none;" targ=
et=3D"_blank"><img src=3D"https://img.grouponcdn.com/deal/tFU1bWsqoKWzoaSqm=
ReRYZjHMja/tF-960x576/v1/t300x182.jpg" width=3D"290" style=3D"display: bloc=
k; border: none; width: 290px;" class=3D"100" alt=3D"Elite Orion or Mini Or=
ion 2.4GHz 4.5CH HD RC Camera Drone" /></a></td> </tr> <tr> <td> <table cel=
lpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"width:100%; backgrou=
nd: #f2f2f2;" width=3D"100%"> <tr> <td class=3D"nameFont" style=3D"padding:=
 16px 16px 0 16px; font-size: 14px !important; line-height: 18px !important=
; color:#000000 !important; text-decoration: none; color: #000000;" align=
=3D"left"> Orion or Mini Orion Camera Drone </td> </tr> <tr> <td style=3D"b=
ackground: #f2f2f2;" valign=3D"top"><a href=3D"https://www.groupon.com/deal=
s/gg-elite-or-mini-orion-24ghz-45ch-hd-rc-camera-drones?p=3D2&utm_source=3D=
channel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f8=
06fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-=
00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-deals&utm_ca=
mpaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" target=3D"_blank"=
 style=3D"font-size: 14px !important; line-height: 18px !important; color:#=
000000 !important; text-decoration: none;">&nbsp;</a></td> </tr> <tr> <td v=
align=3D"top" style=3D"width:290px; min-width:290px; padding-bottom:16px;" =
class=3D"100"> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" styl=
e=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, sa=
ns-serif; color:#000000; font-weight: normal; text-align: left; background:=
 #f2f2f2; width:290px;" valign=3D"top" width=3D"290" class=3D"container"> <=
tr> <td style=3D"padding: 3px 0 0 16px;" align=3D"left"> <span style=3D"pad=
ding: 0 5px 0 0; padding-right: 5px; font-size: 16px; line-height: 20px; te=
xt-decoration: line-through; color:#848484; font-weight: 100;"> $179.99 </s=
pan> <span style=3D"font-size: 16px; line-height: 20px; font-weight: bold; =
text-decoration: none; color: #e35205;"> $59.99 </span> </td> </tr> <tr> <t=
d class=3D"nameFont" align=3D"left" valign=3D"top" style=3D"padding: 0px 0p=
x 0px 16px; font-family: Helvetica, Arial, sans-serif; font-size: 13px; col=
or: #e35205; text-decoration: none; font-weight: 500 !important;">Sale Ends=
 11/12</td> <td width=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"=
top" style=3D"font-family: Helvetica, Arial, sans-serif; padding: 0 16px 0 =
0; font-size: 13px !important; line-height: 17px !important; font-weight: n=
ormal; font-weight: 600; color: #0185c6 !important; text-decoration: none; =
text-align:right; white-space: nowrap;"><a href=3D"https://www.groupon.com/=
deals/gg-elite-or-mini-orion-24ghz-45ch-hd-rc-camera-drones?p=3D2&utm_sourc=
e=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1e=
d8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-8=
2c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3De=
b41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" target=3D"_blank" style=3D"=
color:#0185c6; text-decoration:none;"><font color=3D"#0185c6">View&nbsp;Dea=
l</font></a></td> </tr> </table> </td> </tr> </table> </td> </tr> </table> =
</td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!-=
-[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https://www.groupon.co=
m/deals/gg-xbox-one-s-system-with-battlefield-1-and-cod-infinite-warfare?p=
=3D3&utm_source=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574=
337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c23=
4c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&ut=
m_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" target=3D"_bl=
ank" style=3D"color: #000000; font-size: 14px !important; line-height: 18px=
 !important; color:#000000 !important; text-decoration: none;"> <table vali=
gn=3D"top" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border=
: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; c=
olor:#000000; font-weight: normal; text-align: left; width:290px; mso-table=
-lspace:0;mso-table-rspace:0;" width=3D"290" align=3D'right' class=3D"conta=
iner"> <tr> <td valign=3D"top" width=3D"100%" style=3D"mso-table-lspace:0;m=
so-table-rspace:0; width:100%; padding:20px 0 0 0;"> <table cellpadding=3D"=
0" cellspacing=3D"0" border=3D"0" style=3D"width:100%;" width=3D"100%"> <tr=
> <td valign=3D"top" align=3D"center" width=3D"290" style=3D"width:290px;" =
class=3D"container"><a href=3D"https://www.groupon.com/deals/gg-xbox-one-s-=
system-with-battlefield-1-and-cod-infinite-warfare?p=3D3&utm_source=3Dchann=
el_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf=
5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259=
069d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Deb41cacc-53=
6f-4dfa-ab70-f5ab306ec6f0_0_20161112" style=3D"display: block; border: none=
;" target=3D"_blank"><img src=3D"https://img.grouponcdn.com/deal/Ep7w6pL7sg=
4PY5Mz9wixbzDn7pN/Ep-1500x900/v1/t300x182.jpg" width=3D"290" style=3D"displ=
ay: block; border: none; width: 290px;" class=3D"100" alt=3D"Xbox One S 500=
GB Console and Games Bundle" /></a></td> </tr> <tr> <td> <table cellpadding=
=3D"0" cellspacing=3D"0" border=3D"0" style=3D"width:100%; background: #f2f=
2f2;" width=3D"100%"> <tr> <td class=3D"nameFont" style=3D"padding: 16px 16=
px 0 16px; font-size: 14px !important; line-height: 18px !important; color:=
#000000 !important; text-decoration: none; color: #000000;" align=3D"left">=
 Xbox One S 500GB Console Bundle </td> </tr> <tr> <td style=3D"padding: 0 1=
6px 0 16px;" class=3D"nameFont" align=3D"left"><a href=3D"https://www.group=
on.com/deals/gg-xbox-one-s-system-with-battlefield-1-and-cod-infinite-warfa=
re?p=3D3&utm_source=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03c=
f574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df7=
9c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DMindsto=
rm-Hero-3-deals&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161=
112" target=3D"_blank" style=3D"font-size: 14px !important; line-height: 18=
px !important; color:#000000 !important; text-decoration: none;"><font colo=
r=3D"#e35205">Over 50 bought</font></a></td> </tr> <tr> <td valign=3D"top" =
style=3D"width:290px; min-width:290px; padding-bottom:16px;" class=3D"100">=
 <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border: 0=
 none; border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; colo=
r:#000000; font-weight: normal; text-align: left; background: #f2f2f2; widt=
h:290px;" valign=3D"top" width=3D"290" class=3D"container"> <tr> <td style=
=3D"padding: 3px 0 0 16px;" align=3D"left"> <span style=3D"padding: 0 5px 0=
 0; padding-right: 5px; font-size: 16px; line-height: 20px; text-decoration=
: line-through; color:#848484; font-weight: 100;"> $359.98 </span> <span st=
yle=3D"font-size: 16px; line-height: 20px; font-weight: bold; text-decorati=
on: none; color: #e35205;"> $299.99 </span> </td> </tr> <tr> <td class=3D"n=
ameFont" align=3D"left" valign=3D"top" style=3D"padding: 0px 0px 0px 16px; =
font-family: Helvetica, Arial, sans-serif; font-size: 13px; color: #e35205;=
 text-decoration: none; font-weight: 500 !important;">Sale Ends 11/12</td> =
<td width=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" style=
=3D"font-family: Helvetica, Arial, sans-serif; padding: 0 16px 0 0; font-si=
ze: 13px !important; line-height: 17px !important; font-weight: normal; fon=
t-weight: 600; color: #0185c6 !important; text-decoration: none; text-align=
:right; white-space: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-x=
box-one-s-system-with-battlefield-1-and-cod-infinite-warfare?p=3D3&utm_sour=
ce=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1=
ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-=
82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3D=
eb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" target=3D"_blank" style=3D=
"color:#0185c6; text-decoration:none;"><font color=3D"#0185c6">View&nbsp;De=
al</font></a></td> </tr> </table> </td> </tr> </table> </td> </tr> </table>=
 </td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!=
--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </tr=
> </table> <![endif]--> </td> </tr> <tr> <td valign=3D"top" align=3D"left" =
width=3D"100%" style=3D"width: 600px; min-width:600px;" class=3D"100"> <!--=
[if (gte mso 9)|(IE)]> <table width=3D"600" align=3D"center" cellpadding=3D=
"0" cellspacing=3D"0" border=3D"0"> <tr> <![endif]--> <!--[if (gte mso 9)|(=
IE)]> <td> <![endif]--> <a href=3D"https://www.groupon.com/deals/gg-800-thr=
ead-count-hotel-new-york-cotton-rich-sheet-set?p=3D4&utm_source=3Dchannel_g=
oods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2a=
cac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d=
5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Deb41cacc-536f-=
4dfa-ab70-f5ab306ec6f0_0_20161112" target=3D"_blank" style=3D"color: #00000=
0; font-size: 14px !important; line-height: 18px !important; color:#000000 =
!important; text-decoration: none;"> <table valign=3D"top" cellpadding=3D"0=
" cellspacing=3D"0" border=3D"0" style=3D"border: 0 none; border-spacing: 0=
; font-family: 'Open Sans', Arial, sans-serif; color:#000000; font-weight: =
normal; text-align: left; width:290px; mso-table-lspace:0;mso-table-rspace:=
0;" width=3D"290" align=3D'left' class=3D"container"> <tr> <td valign=3D"to=
p" width=3D"100%" style=3D"mso-table-lspace:0;mso-table-rspace:0; width:100=
%; padding:20px 0 0 0;"> <table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0" style=3D"width:100%;" width=3D"100%"> <tr> <td valign=3D"top" align=
=3D"center" width=3D"290" style=3D"width:290px;" class=3D"container"><a hre=
f=3D"https://www.groupon.com/deals/gg-800-thread-count-hotel-new-york-cotto=
n-rich-sheet-set?p=3D4&utm_source=3Dchannel_goods&utm_medium=3Demail&user=
=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D=
20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dim=
age&d=3DGoods-PN&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_2016=
1112" style=3D"display: block; border: none;" target=3D"_blank"><img src=3D=
"https://img.grouponcdn.com/deal/azbs554UCzeeQRmpRGmu/3J-1200x720/v1/t300x1=
82.jpg" width=3D"290" style=3D"display: block; border: none; width: 290px;"=
 class=3D"100" alt=3D"800-TC Hotel New York Cotton-Rich Sheet Set" /></a></=
td> </tr> <tr> <td> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0"=
 style=3D"width:100%; background: #f2f2f2;" width=3D"100%"> <tr> <td class=
=3D"nameFont" style=3D"padding: 16px 16px 0 16px; font-size: 14px !importan=
t; line-height: 18px !important; color:#000000 !important; text-decoration:=
 none; color: #000000;" align=3D"left"> 800-Thread Count Sheet Set </td> </=
tr> <tr> <td style=3D"padding: 0 16px 0 16px;" class=3D"nameFont" align=3D"=
left"><a href=3D"https://www.groupon.com/deals/gg-800-thread-count-hotel-ne=
w-york-cotton-rich-sheet-set?p=3D4&utm_source=3Dchannel_goods&utm_medium=3D=
email&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8c=
d2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Db=
ody&c=3Dbutton&d=3DMindstorm-Hero-3-deals&utm_campaign=3Deb41cacc-536f-4dfa=
-ab70-f5ab306ec6f0_0_20161112" target=3D"_blank" style=3D"font-size: 14px !=
important; line-height: 18px !important; color:#000000 !important; text-dec=
oration: none;"><font color=3D"#e35205">Over 5,000 bought</font></a></td> <=
/tr> <tr> <td valign=3D"top" style=3D"width:290px; min-width:290px; padding=
-bottom:16px;" class=3D"100"> <table cellpadding=3D"0" cellspacing=3D"0" bo=
rder=3D"0" style=3D"border: 0 none; border-spacing: 0; font-family: 'Open S=
ans', Arial, sans-serif; color:#000000; font-weight: normal; text-align: le=
ft; background: #f2f2f2; width:290px;" valign=3D"top" width=3D"290" class=
=3D"container"> <tr> <td style=3D"padding: 3px 0 0 16px;" align=3D"left"> <=
span style=3D"padding: 0 5px 0 0; padding-right: 5px; font-size: 16px; line=
-height: 20px; text-decoration: line-through; color:#848484; font-weight: 1=
00;"> $220 </span> <span style=3D"font-size: 16px; line-height: 20px; font-=
weight: bold; text-decoration: none; color: #e35205;"> $19.99 </span> </td>=
 </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"top" style=3D"p=
adding: 0px 0px 0px 16px; font-family: Helvetica, Arial, sans-serif; font-s=
ize: 13px; color: #e35205; text-decoration: none; font-weight: 500 !importa=
nt;">Sale Ends 11/14</td> <td width=3D"30%" class=3D"nameFont" align=3D"rig=
ht" valign=3D"top" style=3D"font-family: Helvetica, Arial, sans-serif; padd=
ing: 0 16px 0 0; font-size: 13px !important; line-height: 17px !important; =
font-weight: normal; font-weight: 600; color: #0185c6 !important; text-deco=
ration: none; text-align:right; white-space: nowrap;"><a href=3D"https://ww=
w.groupon.com/deals/gg-800-thread-count-hotel-new-york-cotton-rich-sheet-se=
t?p=3D4&utm_source=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf=
574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79=
c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN=
&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" target=3D"=
_blank" style=3D"color:#0185c6; text-decoration:none;"><font color=3D"#0185=
c6">View&nbsp;Deal</font></a></td> </tr> </table> </td> </tr> </table> </td=
> </tr> </table> </td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td>=
 <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https=
://www.groupon.com/deals/gg-morphic-m-series-mens-watch-1?p=3D5&utm_source=
=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed=
8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82=
c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Deb=
41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" target=3D"_blank" style=3D"c=
olor: #000000; font-size: 14px !important; line-height: 18px !important; co=
lor:#000000 !important; text-decoration: none;"> <table valign=3D"top" cell=
padding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border: 0 none; borde=
r-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#000000; f=
ont-weight: normal; text-align: left; width:290px; mso-table-lspace:0;mso-t=
able-rspace:0;" width=3D"290" align=3D'right' class=3D"container"> <tr> <td=
 valign=3D"top" width=3D"100%" style=3D"mso-table-lspace:0;mso-table-rspace=
:0; width:100%; padding:20px 0 0 0;"> <table cellpadding=3D"0" cellspacing=
=3D"0" border=3D"0" style=3D"width:100%;" width=3D"100%"> <tr> <td valign=
=3D"top" align=3D"center" width=3D"290" style=3D"width:290px;" class=3D"con=
tainer"><a href=3D"https://www.groupon.com/deals/gg-morphic-m-series-mens-w=
atch-1?p=3D5&utm_source=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8b=
f03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=
=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=3DGoo=
ds-PN&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" style=
=3D"display: block; border: none;" target=3D"_blank"><img src=3D"https://im=
g.grouponcdn.com/deal/23SyzvC4tMHBCuyQKUnsUq8nprEc/23-2048x1229/v1/t300x182=
.jpg" width=3D"290" style=3D"display: block; border: none; width: 290px;" c=
lass=3D"100" alt=3D"Morphic Stainless Steel Men's Watches" /></a></td> </tr=
> <tr> <td> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=
=3D"width:100%; background: #f2f2f2;" width=3D"100%"> <tr> <td class=3D"nam=
eFont" style=3D"padding: 16px 16px 0 16px; font-size: 14px !important; line=
-height: 18px !important; color:#000000 !important; text-decoration: none; =
color: #000000;" align=3D"left"> Morphic Men's Watches </td> </tr> <tr> <td=
 style=3D"background: #f2f2f2;" valign=3D"top"><a href=3D"https://www.group=
on.com/deals/gg-morphic-m-series-mens-watch-1?p=3D5&utm_source=3Dchannel_go=
ods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2ac=
ac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5=
fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-deals&utm_campaign=3De=
b41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" target=3D"_blank" style=3D"=
font-size: 14px !important; line-height: 18px !important; color:#000000 !im=
portant; text-decoration: none;">&nbsp;</a></td> </tr> <tr> <td valign=3D"t=
op" style=3D"width:290px; min-width:290px; padding-bottom:16px;" class=3D"1=
00"> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"borde=
r: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; =
color:#000000; font-weight: normal; text-align: left; background: #f2f2f2; =
width:290px;" valign=3D"top" width=3D"290" class=3D"container"> <tr> <td st=
yle=3D"padding: 3px 0 0 16px;" align=3D"left"> <span style=3D"padding: 0 5p=
x 0 0; padding-right: 5px; font-size: 16px; line-height: 20px; text-decorat=
ion: line-through; color:#848484; font-weight: 100;"> $1,000 </span> <span =
style=3D"font-size: 16px; line-height: 20px; font-weight: bold; text-decora=
tion: none; color: #e35205;"> $71.99 </span> </td> </tr> <tr> <td class=3D"=
nameFont" align=3D"left" valign=3D"top" style=3D"padding: 0px 0px 0px 16px;=
 font-family: Helvetica, Arial, sans-serif; font-size: 13px; color: #e35205=
; text-decoration: none; font-weight: 500 !important;">Sale Ends 11/14</td>=
 <td width=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" style=
=3D"font-family: Helvetica, Arial, sans-serif; padding: 0 16px 0 0; font-si=
ze: 13px !important; line-height: 17px !important; font-weight: normal; fon=
t-weight: 600; color: #0185c6 !important; text-decoration: none; text-align=
:right; white-space: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-m=
orphic-m-series-mens-watch-1?p=3D5&utm_source=3Dchannel_goods&utm_medium=3D=
email&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8c=
d2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Db=
ody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306e=
c6f0_0_20161112" target=3D"_blank" style=3D"color:#0185c6; text-decoration:=
none;"><font color=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </table=
> </td> </tr> </table> </td> </tr> </table> </td> </tr> </table> </a> <!--[=
if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </td> <=
![endif]--> <!--[if (gte mso 9)|(IE)]> </tr> </table> <![endif]--> </td> </=
tr> <tr> <td valign=3D"top" align=3D"left" width=3D"100%" style=3D"width: 6=
00px; min-width:600px;" class=3D"100"> <!--[if (gte mso 9)|(IE)]> <table wi=
dth=3D"600" align=3D"center" cellpadding=3D"0" cellspacing=3D"0" border=3D"=
0"> <tr> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=
=3D"https://www.groupon.com/deals/gg-apple-iphone-smartphone-gsm-unlocked-r=
efurbished?p=3D6&utm_source=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd=
7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112=
&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=
=3DGoods-PN&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112"=
 target=3D"_blank" style=3D"color: #000000; font-size: 14px !important; lin=
e-height: 18px !important; color:#000000 !important; text-decoration: none;=
"> <table valign=3D"top" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" s=
tyle=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial,=
 sans-serif; color:#000000; font-weight: normal; text-align: left; width:29=
0px; mso-table-lspace:0;mso-table-rspace:0;" width=3D"290" align=3D'left' c=
lass=3D"container"> <tr> <td valign=3D"top" width=3D"100%" style=3D"mso-tab=
le-lspace:0;mso-table-rspace:0; width:100%; padding:20px 0 0 0;"> <table ce=
llpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"width:100%;" width=
=3D"100%"> <tr> <td valign=3D"top" align=3D"center" width=3D"290" style=3D"=
width:290px;" class=3D"container"><a href=3D"https://www.groupon.com/deals/=
gg-apple-iphone-smartphone-gsm-unlocked-refurbished?p=3D6&utm_source=3Dchan=
nel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fb=
f5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-0025=
9069d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Deb41cacc-5=
36f-4dfa-ab70-f5ab306ec6f0_0_20161112" style=3D"display: block; border: non=
e;" target=3D"_blank"><img src=3D"https://img.grouponcdn.com/deal/3hEqth5gy=
QRGXq19D9nTNbFPvAao/3h-960x576/v1/t300x182.jpg" width=3D"290" style=3D"disp=
lay: block; border: none; width: 290px;" class=3D"100" alt=3D"Apple iPhone =
6s/6s Plus, 6/6 Plus, 5s, 5c, 5, 3gs GSM Unlocked-Refurb." /></a></td> </tr=
> <tr> <td> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=
=3D"width:100%; background: #f2f2f2;" width=3D"100%"> <tr> <td class=3D"nam=
eFont" style=3D"padding: 16px 16px 0 16px; font-size: 14px !important; line=
-height: 18px !important; color:#000000 !important; text-decoration: none; =
color: #000000;" align=3D"left"> Apple iPhone 6s/6/5s/5c/5/3gs </td> </tr> =
<tr> <td style=3D"padding: 0 16px 0 16px;" class=3D"nameFont" align=3D"left=
"><a href=3D"https://www.groupon.com/deals/gg-apple-iphone-smartphone-gsm-u=
nlocked-refurbished?p=3D6&utm_source=3Dchannel_goods&utm_medium=3Demail&use=
r=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=
=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=
=3Dbutton&d=3DMindstorm-Hero-3-deals&utm_campaign=3Deb41cacc-536f-4dfa-ab70=
-f5ab306ec6f0_0_20161112" target=3D"_blank" style=3D"font-size: 14px !impor=
tant; line-height: 18px !important; color:#000000 !important; text-decorati=
on: none;"><font color=3D"#e35205">Over 1,000 bought</font></a></td> </tr> =
<tr> <td valign=3D"top" style=3D"width:290px; min-width:290px; padding-bott=
om:16px;" class=3D"100"> <table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0" style=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans'=
, Arial, sans-serif; color:#000000; font-weight: normal; text-align: left; =
background: #f2f2f2; width:290px;" valign=3D"top" width=3D"290" class=3D"co=
ntainer"> <tr> <td style=3D"padding: 3px 0 0 16px;" align=3D"left"> <span s=
tyle=3D"padding: 0 5px 0 0; padding-right: 5px; font-size: 16px; line-heigh=
t: 20px; text-decoration: line-through; color:#848484; font-weight: 100;"> =
$99 </span> <span style=3D"font-size: 16px; line-height: 20px; font-weight:=
 bold; text-decoration: none; color: #e35205;"> $54.99 </span> </td> </tr> =
<tr> <td class=3D"nameFont" align=3D"left" valign=3D"top" style=3D"padding:=
 0px 0px 0px 16px; font-family: Helvetica, Arial, sans-serif; font-size: 13=
px; color: #e35205; text-decoration: none; font-weight: 500 !important;">Sa=
le Ends 11/14</td> <td width=3D"30%" class=3D"nameFont" align=3D"right" val=
ign=3D"top" style=3D"font-family: Helvetica, Arial, sans-serif; padding: 0 =
16px 0 0; font-size: 13px !important; line-height: 17px !important; font-we=
ight: normal; font-weight: 600; color: #0185c6 !important; text-decoration:=
 none; text-align:right; white-space: nowrap;"><a href=3D"https://www.group=
on.com/deals/gg-apple-iphone-smartphone-gsm-unlocked-refurbished?p=3D6&utm_=
source=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c82207=
0ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-1=
1e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaig=
n=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" target=3D"_blank" styl=
e=3D"color:#0185c6; text-decoration:none;"><font color=3D"#0185c6">View&nbs=
p;Deal</font></a></td> </tr> </table> </td> </tr> </table> </td> </tr> </ta=
ble> </td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--=
> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https://www.group=
on.com/deals/gg-dupont-air-filters?p=3D7&utm_source=3Dchannel_goods&utm_med=
ium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf3865=
61ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS=
&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5=
ab306ec6f0_0_20161112" target=3D"_blank" style=3D"color: #000000; font-size=
: 14px !important; line-height: 18px !important; color:#000000 !important; =
text-decoration: none;"> <table valign=3D"top" cellpadding=3D"0" cellspacin=
g=3D"0" border=3D"0" style=3D"border: 0 none; border-spacing: 0; font-famil=
y: 'Open Sans', Arial, sans-serif; color:#000000; font-weight: normal; text=
-align: left; width:290px; mso-table-lspace:0;mso-table-rspace:0;" width=3D=
"290" align=3D'right' class=3D"container"> <tr> <td valign=3D"top" width=3D=
"100%" style=3D"mso-table-lspace:0;mso-table-rspace:0; width:100%; padding:=
20px 0 0 0;"> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=
=3D"width:100%;" width=3D"100%"> <tr> <td valign=3D"top" align=3D"center" w=
idth=3D"290" style=3D"width:290px;" class=3D"container"><a href=3D"https://=
www.groupon.com/deals/gg-dupont-air-filters?p=3D7&utm_source=3Dchannel_good=
s&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac=
134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe=
&CID=3DUS&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Deb41cacc-536f-4dfa=
-ab70-f5ab306ec6f0_0_20161112" style=3D"display: block; border: none;" targ=
et=3D"_blank"><img src=3D"https://img.grouponcdn.com/deal/drCkoePh8JXm78nya=
BDP/iL-1086x652/v1/t300x182.jpg" width=3D"290" style=3D"display: block; bor=
der: none; width: 290px;" class=3D"100" alt=3D"DuPont High Allergen Care Ai=
r Filters (4-Pack)" /></a></td> </tr> <tr> <td> <table cellpadding=3D"0" ce=
llspacing=3D"0" border=3D"0" style=3D"width:100%; background: #f2f2f2;" wid=
th=3D"100%"> <tr> <td class=3D"nameFont" style=3D"padding: 16px 16px 0 16px=
; font-size: 14px !important; line-height: 18px !important; color:#000000 !=
important; text-decoration: none; color: #000000;" align=3D"left"> DuPont A=
ir Filters </td> </tr> <tr> <td style=3D"padding: 0 16px 0 16px;" class=3D"=
nameFont" align=3D"left"><a href=3D"https://www.groupon.com/deals/gg-dupont=
-air-filters?p=3D7&utm_source=3Dchannel_goods&utm_medium=3Demail&user=3Dd8b=
fd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D201611=
12&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=
=3DMindstorm-Hero-3-deals&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6=
f0_0_20161112" target=3D"_blank" style=3D"font-size: 14px !important; line-=
height: 18px !important; color:#000000 !important; text-decoration: none;">=
<font color=3D"#e35205">Over 1,000 bought</font></a></td> </tr> <tr> <td va=
lign=3D"top" style=3D"width:290px; min-width:290px; padding-bottom:16px;" c=
lass=3D"100"> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=
=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, san=
s-serif; color:#000000; font-weight: normal; text-align: left; background: =
#f2f2f2; width:290px;" valign=3D"top" width=3D"290" class=3D"container"> <t=
r> <td style=3D"padding: 3px 0 0 16px;" align=3D"left"> <span style=3D"padd=
ing: 0 5px 0 0; padding-right: 5px; font-size: 16px; line-height: 20px; tex=
t-decoration: line-through; color:#848484; font-weight: 100;"> $44 </span> =
<span style=3D"font-size: 16px; line-height: 20px; color:#53A318; font-weig=
ht: 300; text-decoration: none; font-weight: bold;"> $24.99 </span> </td> <=
/tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"top" style=3D"pad=
ding: 0px 0px 0px 16px; font-family: Helvetica, Arial, sans-serif; font-siz=
e: 13px; color: #e35205; text-decoration: none; font-weight: 500 !important=
;">&nbsp;</td> <td width=3D"30%" class=3D"nameFont" align=3D"right" valign=
=3D"top" style=3D"font-family: Arial, Helvetica, sans-serif; padding: 0 16p=
x 0 0; font-size: 13px !important; line-height: 17px !important; font-weigh=
t: normal; font-weight: 600; color: #0185c6 !important; text-decoration: no=
ne; text-align:right; white-space: nowrap;"><a href=3D"https://www.groupon.=
com/deals/gg-dupont-air-filters?p=3D7&utm_source=3Dchannel_goods&utm_medium=
=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561e=
d8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=
=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab=
306ec6f0_0_20161112" target=3D"_blank" style=3D"color:#0185c6; text-decorat=
ion:none;"><font color=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </t=
able> </td> </tr> </table> </td> </tr> </table> </td> </tr> </table> </a> <=
!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </t=
d> <![endif]--> <!--[if (gte mso 9)|(IE)]> </tr> </table> <![endif]--> </td=
> </tr> <tr> <td valign=3D"top" align=3D"left" width=3D"100%" style=3D"widt=
h: 600px; min-width:600px;" class=3D"100"> <!--[if (gte mso 9)|(IE)]> <tabl=
e width=3D"600" align=3D"center" cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0"> <tr> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a h=
ref=3D"https://www.groupon.com/deals/gg-dunfill-fir-trees?p=3D8&utm_source=
=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed=
8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82=
c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Deb=
41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" target=3D"_blank" style=3D"c=
olor: #000000; font-size: 14px !important; line-height: 18px !important; co=
lor:#000000 !important; text-decoration: none;"> <table valign=3D"top" cell=
padding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border: 0 none; borde=
r-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#000000; f=
ont-weight: normal; text-align: left; width:290px; mso-table-lspace:0;mso-t=
able-rspace:0;" width=3D"290" align=3D'left' class=3D"container"> <tr> <td =
valign=3D"top" width=3D"100%" style=3D"mso-table-lspace:0;mso-table-rspace:=
0; width:100%; padding:20px 0 0 0;"> <table cellpadding=3D"0" cellspacing=
=3D"0" border=3D"0" style=3D"width:100%;" width=3D"100%"> <tr> <td valign=
=3D"top" align=3D"center" width=3D"290" style=3D"width:290px;" class=3D"con=
tainer"><a href=3D"https://www.groupon.com/deals/gg-dunfill-fir-trees?p=3D8=
&utm_source=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c=
822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2=
539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_cam=
paign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" style=3D"display: =
block; border: none;" target=3D"_blank"><img src=3D"https://img.grouponcdn.=
com/deal/7sSYDrPqvdk5wSAP38A/1z-960x576/v1/t300x182.jpg" width=3D"290" styl=
e=3D"display: block; border: none; width: 290px;" class=3D"100" alt=3D"7.5 =
Ft. Dunhill Fir Christmas Tree with White or Multicolored Lights" /></a></t=
d> </tr> <tr> <td> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" =
style=3D"width:100%; background: #f2f2f2;" width=3D"100%"> <tr> <td class=
=3D"nameFont" style=3D"padding: 16px 16px 0 16px; font-size: 14px !importan=
t; line-height: 18px !important; color:#000000 !important; text-decoration:=
 none; color: #000000;" align=3D"left"> Dunhill Fir Christmas Tree </td> </=
tr> <tr> <td style=3D"padding: 0 16px 0 16px;" class=3D"nameFont" align=3D"=
left"><a href=3D"https://www.groupon.com/deals/gg-dunfill-fir-trees?p=3D8&u=
tm_source=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c82=
2070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-253=
9-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-=
deals&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" targe=
t=3D"_blank" style=3D"font-size: 14px !important; line-height: 18px !import=
ant; color:#000000 !important; text-decoration: none;"><font color=3D"#e352=
05">Over 50 bought</font></a></td> </tr> <tr> <td valign=3D"top" style=3D"w=
idth:290px; min-width:290px; padding-bottom:16px;" class=3D"100"> <table ce=
llpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border: 0 none; bor=
der-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#000000;=
 font-weight: normal; text-align: left; background: #f2f2f2; width:290px;" =
valign=3D"top" width=3D"290" class=3D"container"> <tr> <td style=3D"padding=
: 3px 0 0 16px;" align=3D"left"> <span style=3D"padding: 0 5px 0 0; padding=
-right: 5px; font-size: 16px; line-height: 20px; text-decoration: line-thro=
ugh; color:#848484; font-weight: 100;"> $469.99 </span> <span style=3D"font=
-size: 16px; line-height: 20px; font-weight: bold; text-decoration: none; c=
olor: #e35205;"> $179.99 </span> </td> </tr> <tr> <td class=3D"nameFont" al=
ign=3D"left" valign=3D"top" style=3D"padding: 0px 0px 0px 16px; font-family=
: Helvetica, Arial, sans-serif; font-size: 13px; color: #e35205; text-decor=
ation: none; font-weight: 500 !important;">Sale Ends 11/14</td> <td width=
=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" style=3D"font-fa=
mily: Helvetica, Arial, sans-serif; padding: 0 16px 0 0; font-size: 13px !i=
mportant; line-height: 17px !important; font-weight: normal; font-weight: 6=
00; color: #0185c6 !important; text-decoration: none; text-align:right; whi=
te-space: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-dunfill-fir-=
trees?p=3D8&utm_source=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf=
03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=
=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGo=
ods-PN&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" targ=
et=3D"_blank" style=3D"color:#0185c6; text-decoration:none;"><font color=3D=
"#0185c6">View&nbsp;Deal</font></a></td> </tr> </table> </td> </tr> </table=
> </td> </tr> </table> </td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)]>=
 </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D=
"https://www.groupon.com/deals/gg-ontek-water-resistant-bluetooth-shower-sp=
eaker-2?p=3D9&utm_source=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8=
bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=
=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGo=
ods-PN&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" targ=
et=3D"_blank" style=3D"color: #000000; font-size: 14px !important; line-hei=
ght: 18px !important; color:#000000 !important; text-decoration: none;"> <t=
able valign=3D"top" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=
=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, san=
s-serif; color:#000000; font-weight: normal; text-align: left; width:290px;=
 mso-table-lspace:0;mso-table-rspace:0;" width=3D"290" align=3D'right' clas=
s=3D"container"> <tr> <td valign=3D"top" width=3D"100%" style=3D"mso-table-=
lspace:0;mso-table-rspace:0; width:100%; padding:20px 0 0 0;"> <table cellp=
adding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"width:100%;" width=3D"=
100%"> <tr> <td valign=3D"top" align=3D"center" width=3D"290" style=3D"widt=
h:290px;" class=3D"container"><a href=3D"https://www.groupon.com/deals/gg-o=
ntek-water-resistant-bluetooth-shower-speaker-2?p=3D9&utm_source=3Dchannel_=
goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2=
acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069=
d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Deb41cacc-536f-=
4dfa-ab70-f5ab306ec6f0_0_20161112" style=3D"display: block; border: none;" =
target=3D"_blank"><img src=3D"https://img.grouponcdn.com/deal/3WrqdqWK2tYif=
umNxUd86Zdgf1f1/3W-960x576/v1/t300x182.jpg" width=3D"290" style=3D"display:=
 block; border: none; width: 290px;" class=3D"100" alt=3D"OnTek Water-Resis=
tant Bluetooth Shower Speaker with Mic and Controls" /></a></td> </tr> <tr>=
 <td> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"widt=
h:100%; background: #f2f2f2;" width=3D"100%"> <tr> <td class=3D"nameFont" s=
tyle=3D"padding: 16px 16px 0 16px; font-size: 14px !important; line-height:=
 18px !important; color:#000000 !important; text-decoration: none; color: #=
000000;" align=3D"left"> OnTek Bluetooth Shower Speaker </td> </tr> <tr> <t=
d style=3D"padding: 0 16px 0 16px;" class=3D"nameFont" align=3D"left"><a hr=
ef=3D"https://www.groupon.com/deals/gg-ontek-water-resistant-bluetooth-show=
er-speaker-2?p=3D9&utm_source=3Dchannel_goods&utm_medium=3Demail&user=3Dd8b=
fd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D201611=
12&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=
=3DMindstorm-Hero-3-deals&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6=
f0_0_20161112" target=3D"_blank" style=3D"font-size: 14px !important; line-=
height: 18px !important; color:#000000 !important; text-decoration: none;">=
<font color=3D"#e35205">Over 5,000 bought</font></a></td> </tr> <tr> <td va=
lign=3D"top" style=3D"width:290px; min-width:290px; padding-bottom:16px;" c=
lass=3D"100"> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=
=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, san=
s-serif; color:#000000; font-weight: normal; text-align: left; background: =
#f2f2f2; width:290px;" valign=3D"top" width=3D"290" class=3D"container"> <t=
r> <td style=3D"padding: 3px 0 0 16px;" align=3D"left"> <span style=3D"padd=
ing: 0 5px 0 0; padding-right: 5px; font-size: 16px; line-height: 20px; tex=
t-decoration: line-through; color:#848484; font-weight: 100;"> $49.99 </spa=
n> <span style=3D"font-size: 16px; line-height: 20px; font-weight: bold; te=
xt-decoration: none; color: #e35205;"> $7.99 </span> </td> </tr> <tr> <td c=
lass=3D"nameFont" align=3D"left" valign=3D"top" style=3D"padding: 0px 0px 0=
px 16px; font-family: Helvetica, Arial, sans-serif; font-size: 13px; color:=
 #e35205; text-decoration: none; font-weight: 500 !important;">Sale Ends 11=
/14</td> <td width=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top=
" style=3D"font-family: Helvetica, Arial, sans-serif; padding: 0 16px 0 0; =
font-size: 13px !important; line-height: 17px !important; font-weight: norm=
al; font-weight: 600; color: #0185c6 !important; text-decoration: none; tex=
t-align:right; white-space: nowrap;"><a href=3D"https://www.groupon.com/dea=
ls/gg-ontek-water-resistant-bluetooth-shower-speaker-2?p=3D9&utm_source=3Dc=
hannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f80=
6fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-0=
0259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Deb41ca=
cc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" target=3D"_blank" style=3D"color=
:#0185c6; text-decoration:none;"><font color=3D"#0185c6">View&nbsp;Deal</fo=
nt></a></td> </tr> </table> </td> </tr> </table> </td> </tr> </table> </td>=
 </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if =
(gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </tr> </ta=
ble> <![endif]--> </td> </tr> <tr> <td valign=3D"top" align=3D"left" width=
=3D"100%" style=3D"width: 600px; min-width:600px;" class=3D"100"> <!--[if (=
gte mso 9)|(IE)]> <table width=3D"600" align=3D"center" cellpadding=3D"0" c=
ellspacing=3D"0" border=3D"0"> <tr> <![endif]--> <!--[if (gte mso 9)|(IE)]>=
 <td> <![endif]--> <a href=3D"https://www.groupon.com/deals/gg-olympia-usa-=
luxe-expandable-spinner-suitcase-set?p=3D10&utm_source=3Dchannel_goods&utm_=
medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf3=
86561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=
=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Deb41cacc-536f-4dfa-ab=
70-f5ab306ec6f0_0_20161112" target=3D"_blank" style=3D"color: #000000; font=
-size: 14px !important; line-height: 18px !important; color:#000000 !import=
ant; text-decoration: none;"> <table valign=3D"top" cellpadding=3D"0" cells=
pacing=3D"0" border=3D"0" style=3D"border: 0 none; border-spacing: 0; font-=
family: 'Open Sans', Arial, sans-serif; color:#000000; font-weight: normal;=
 text-align: left; width:290px; mso-table-lspace:0;mso-table-rspace:0;" wid=
th=3D"290" align=3D'left' class=3D"container"> <tr> <td valign=3D"top" widt=
h=3D"100%" style=3D"mso-table-lspace:0;mso-table-rspace:0; width:100%; padd=
ing:20px 0 0 0;"> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" s=
tyle=3D"width:100%;" width=3D"100%"> <tr> <td valign=3D"top" align=3D"cente=
r" width=3D"290" style=3D"width:290px;" class=3D"container"><a href=3D"http=
s://www.groupon.com/deals/gg-olympia-usa-luxe-expandable-spinner-suitcase-s=
et?p=3D10&utm_source=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03=
cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df=
79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=3DGoods-P=
N&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" style=3D"=
display: block; border: none;" target=3D"_blank"><img src=3D"https://img.gr=
ouponcdn.com/deal/BAutRSgAetinmfSzstcdhmcvGPL/BA-960x576/v1/t300x182.jpg" w=
idth=3D"290" style=3D"display: block; border: none; width: 290px;" class=3D=
"100" alt=3D"Olympia USA Luxe Luggage Set (3-Piece)" /></a></td> </tr> <tr>=
 <td> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"widt=
h:100%; background: #f2f2f2;" width=3D"100%"> <tr> <td class=3D"nameFont" s=
tyle=3D"padding: 16px 16px 0 16px; font-size: 14px !important; line-height:=
 18px !important; color:#000000 !important; text-decoration: none; color: #=
000000;" align=3D"left"> Olympia USA Suitcase Set (3-Pc.) </td> </tr> <tr> =
<td style=3D"padding: 0 16px 0 16px;" class=3D"nameFont" align=3D"left"><a =
href=3D"https://www.groupon.com/deals/gg-olympia-usa-luxe-expandable-spinne=
r-suitcase-set?p=3D10&utm_source=3Dchannel_goods&utm_medium=3Demail&user=3D=
d8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D201=
61112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutto=
n&d=3DMindstorm-Hero-3-deals&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306=
ec6f0_0_20161112" target=3D"_blank" style=3D"font-size: 14px !important; li=
ne-height: 18px !important; color:#000000 !important; text-decoration: none=
;"><font color=3D"#e35205">Over 1,000 bought</font></a></td> </tr> <tr> <td=
 valign=3D"top" style=3D"width:290px; min-width:290px; padding-bottom:16px;=
" class=3D"100"> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" st=
yle=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, =
sans-serif; color:#000000; font-weight: normal; text-align: left; backgroun=
d: #f2f2f2; width:290px;" valign=3D"top" width=3D"290" class=3D"container">=
 <tr> <td style=3D"padding: 3px 0 0 16px;" align=3D"left"> <span style=3D"p=
adding: 0 5px 0 0; padding-right: 5px; font-size: 16px; line-height: 20px; =
text-decoration: line-through; color:#848484; font-weight: 100;"> $590 </sp=
an> <span style=3D"font-size: 16px; line-height: 20px; font-weight: bold; t=
ext-decoration: none; color: #e35205;"> $109.99 </span> </td> </tr> <tr> <t=
d class=3D"nameFont" align=3D"left" valign=3D"top" style=3D"padding: 0px 0p=
x 0px 16px; font-family: Helvetica, Arial, sans-serif; font-size: 13px; col=
or: #e35205; text-decoration: none; font-weight: 500 !important;">Sale Ends=
 11/12</td> <td width=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"=
top" style=3D"font-family: Helvetica, Arial, sans-serif; padding: 0 16px 0 =
0; font-size: 13px !important; line-height: 17px !important; font-weight: n=
ormal; font-weight: 600; color: #0185c6 !important; text-decoration: none; =
text-align:right; white-space: nowrap;"><a href=3D"https://www.groupon.com/=
deals/gg-olympia-usa-luxe-expandable-spinner-suitcase-set?p=3D10&utm_source=
=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed=
8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82=
c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Deb=
41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" target=3D"_blank" style=3D"c=
olor:#0185c6; text-decoration:none;"><font color=3D"#0185c6">View&nbsp;Deal=
</font></a></td> </tr> </table> </td> </tr> </table> </td> </tr> </table> <=
/td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--=
[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https://www.groupon.com=
/deals/gg-apple-macbook-pro-laptop-6?p=3D11&utm_source=3Dchannel_goods&utm_=
medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf3=
86561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=
=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Deb41cacc-536f-4dfa-ab=
70-f5ab306ec6f0_0_20161112" target=3D"_blank" style=3D"color: #000000; font=
-size: 14px !important; line-height: 18px !important; color:#000000 !import=
ant; text-decoration: none;"> <table valign=3D"top" cellpadding=3D"0" cells=
pacing=3D"0" border=3D"0" style=3D"border: 0 none; border-spacing: 0; font-=
family: 'Open Sans', Arial, sans-serif; color:#000000; font-weight: normal;=
 text-align: left; width:290px; mso-table-lspace:0;mso-table-rspace:0;" wid=
th=3D"290" align=3D'right' class=3D"container"> <tr> <td valign=3D"top" wid=
th=3D"100%" style=3D"mso-table-lspace:0;mso-table-rspace:0; width:100%; pad=
ding:20px 0 0 0;"> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" =
style=3D"width:100%;" width=3D"100%"> <tr> <td valign=3D"top" align=3D"cent=
er" width=3D"290" style=3D"width:290px;" class=3D"container"><a href=3D"htt=
ps://www.groupon.com/deals/gg-apple-macbook-pro-laptop-6?p=3D11&utm_source=
=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed=
8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82=
c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Deb4=
1cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" style=3D"display: block; bord=
er: none;" target=3D"_blank"><img src=3D"https://img.grouponcdn.com/deal/3S=
Cb5b34MPKKSMKWZLrmjBRbQdrg/3S-1000x600/v1/t300x182.jpg" width=3D"290" style=
=3D"display: block; border: none; width: 290px;" class=3D"100" alt=3D"Apple=
 MacBook Pro 13.3" Laptop (Refurbished)" /></a></td> </tr> <tr> <td> <table=
 cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"width:100%; back=
ground: #f2f2f2;" width=3D"100%"> <tr> <td class=3D"nameFont" style=3D"padd=
ing: 16px 16px 0 16px; font-size: 14px !important; line-height: 18px !impor=
tant; color:#000000 !important; text-decoration: none; color: #000000;" ali=
gn=3D"left"> Apple MacBook Pro 13.3" Laptop </td> </tr> <tr> <td style=3D"b=
ackground: #f2f2f2;" valign=3D"top"><a href=3D"https://www.groupon.com/deal=
s/gg-apple-macbook-pro-laptop-6?p=3D11&utm_source=3Dchannel_goods&utm_mediu=
m=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561=
ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=
=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-deals&utm_campaign=3Deb41cacc-536f-=
4dfa-ab70-f5ab306ec6f0_0_20161112" target=3D"_blank" style=3D"font-size: 14=
px !important; line-height: 18px !important; color:#000000 !important; text=
-decoration: none;">&nbsp;</a></td> </tr> <tr> <td valign=3D"top" style=3D"=
width:290px; min-width:290px; padding-bottom:16px;" class=3D"100"> <table c=
ellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border: 0 none; bo=
rder-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#000000=
; font-weight: normal; text-align: left; background: #f2f2f2; width:290px;"=
 valign=3D"top" width=3D"290" class=3D"container"> <tr> <td style=3D"paddin=
g: 3px 0 0 16px;" align=3D"left"> <span style=3D"padding: 0 5px 0 0; paddin=
g-right: 5px; font-size: 16px; line-height: 20px; text-decoration: line-thr=
ough; color:#848484; font-weight: 100;"> $999.99 </span> <span style=3D"fon=
t-size: 16px; line-height: 20px; font-weight: bold; text-decoration: none; =
color: #e35205;"> $749.99 </span> </td> </tr> <tr> <td class=3D"nameFont" a=
lign=3D"left" valign=3D"top" style=3D"padding: 0px 0px 0px 16px; font-famil=
y: Helvetica, Arial, sans-serif; font-size: 13px; color: #e35205; text-deco=
ration: none; font-weight: 500 !important;">Sale Ends 11/12</td> <td width=
=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" style=3D"font-fa=
mily: Helvetica, Arial, sans-serif; padding: 0 16px 0 0; font-size: 13px !i=
mportant; line-height: 17px !important; font-weight: normal; font-weight: 6=
00; color: #0185c6 !important; text-decoration: none; text-align:right; whi=
te-space: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-apple-macboo=
k-pro-laptop-6?p=3D11&utm_source=3Dchannel_goods&utm_medium=3Demail&user=3D=
d8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D201=
61112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutto=
n&d=3DGoods-PN&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_201611=
12" target=3D"_blank" style=3D"color:#0185c6; text-decoration:none;"><font =
color=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </table> </td> </tr>=
 </table> </td> </tr> </table> </td> </tr> </table> </a> <!--[if (gte mso 9=
)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <=
!--[if (gte mso 9)|(IE)]> </tr> </table> <![endif]--> </td> </tr> <tr> <td =
valign=3D"top" align=3D"left" width=3D"100%" style=3D"width: 600px; min-wid=
th:600px;" class=3D"100"> <!--[if (gte mso 9)|(IE)]> <table width=3D"600" a=
lign=3D"center" cellpadding=3D"0" cellspacing=3D"0" border=3D"0"> <tr> <![e=
ndif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https://ww=
w.groupon.com/deals/gg-sonic-fx-solo-toothbrush-w-11-brush-heads?p=3D12&utm=
_source=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c8220=
70ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-=
11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campai=
gn=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" target=3D"_blank" sty=
le=3D"color: #000000; font-size: 14px !important; line-height: 18px !import=
ant; color:#000000 !important; text-decoration: none;"> <table valign=3D"to=
p" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border: 0 none=
; border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#00=
0000; font-weight: normal; text-align: left; width:290px; mso-table-lspace:=
0;mso-table-rspace:0;" width=3D"290" align=3D'left' class=3D"container"> <t=
r> <td valign=3D"top" width=3D"100%" style=3D"mso-table-lspace:0;mso-table-=
rspace:0; width:100%; padding:20px 0 0 0;"> <table cellpadding=3D"0" cellsp=
acing=3D"0" border=3D"0" style=3D"width:100%;" width=3D"100%"> <tr> <td val=
ign=3D"top" align=3D"center" width=3D"290" style=3D"width:290px;" class=3D"=
container"><a href=3D"https://www.groupon.com/deals/gg-sonic-fx-solo-toothb=
rush-w-11-brush-heads?p=3D12&utm_source=3Dchannel_goods&utm_medium=3Demail&=
user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&dat=
e=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=
=3Dimage&d=3DGoods-PN&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0=
_20161112" style=3D"display: block; border: none;" target=3D"_blank"><img s=
rc=3D"https://img.grouponcdn.com/deal/3yU13ocMSFagAUnQvcUWGwVpbG1G/3y-1400x=
840/v1/t300x182.jpg" width=3D"290" style=3D"display: block; border: none; w=
idth: 290px;" class=3D"100" alt=3D"Sonic FX Solo Toothbrush w/ 10 Brush Hea=
ds & 1 Interdental Head" /></a></td> </tr> <tr> <td> <table cellpadding=3D"=
0" cellspacing=3D"0" border=3D"0" style=3D"width:100%; background: #f2f2f2;=
" width=3D"100%"> <tr> <td class=3D"nameFont" style=3D"padding: 16px 16px 0=
 16px; font-size: 14px !important; line-height: 18px !important; color:#000=
000 !important; text-decoration: none; color: #000000;" align=3D"left"> Son=
ic FX Solo Toothbrush Kit </td> </tr> <tr> <td style=3D"padding: 0 16px 0 1=
6px;" class=3D"nameFont" align=3D"left"><a href=3D"https://www.groupon.com/=
deals/gg-sonic-fx-solo-toothbrush-w-11-brush-heads?p=3D12&utm_source=3Dchan=
nel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fb=
f5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-0025=
9069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-deals&utm_campai=
gn=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" target=3D"_blank" sty=
le=3D"font-size: 14px !important; line-height: 18px !important; color:#0000=
00 !important; text-decoration: none;"><font color=3D"#e35205">Over 1,000 b=
ought</font></a></td> </tr> <tr> <td valign=3D"top" style=3D"width:290px; m=
in-width:290px; padding-bottom:16px;" class=3D"100"> <table cellpadding=3D"=
0" cellspacing=3D"0" border=3D"0" style=3D"border: 0 none; border-spacing: =
0; font-family: 'Open Sans', Arial, sans-serif; color:#000000; font-weight:=
 normal; text-align: left; background: #f2f2f2; width:290px;" valign=3D"top=
" width=3D"290" class=3D"container"> <tr> <td style=3D"padding: 3px 0 0 16p=
x;" align=3D"left"> <span style=3D"padding: 0 5px 0 0; padding-right: 5px; =
font-size: 16px; line-height: 20px; text-decoration: line-through; color:#8=
48484; font-weight: 100;"> $179.95 </span> <span style=3D"font-size: 16px; =
line-height: 20px; font-weight: bold; text-decoration: none; color: #e35205=
;"> $29.99 </span> </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" v=
align=3D"top" style=3D"padding: 0px 0px 0px 16px; font-family: Helvetica, A=
rial, sans-serif; font-size: 13px; color: #e35205; text-decoration: none; f=
ont-weight: 500 !important;">Sale Ends 11/12</td> <td width=3D"30%" class=
=3D"nameFont" align=3D"right" valign=3D"top" style=3D"font-family: Helvetic=
a, Arial, sans-serif; padding: 0 16px 0 0; font-size: 13px !important; line=
-height: 17px !important; font-weight: normal; font-weight: 600; color: #01=
85c6 !important; text-decoration: none; text-align:right; white-space: nowr=
ap;"><a href=3D"https://www.groupon.com/deals/gg-sonic-fx-solo-toothbrush-w=
-11-brush-heads?p=3D12&utm_source=3Dchannel_goods&utm_medium=3Demail&user=
=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D=
20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbu=
tton&d=3DGoods-PN&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_201=
61112" target=3D"_blank" style=3D"color:#0185c6; text-decoration:none;"><fo=
nt color=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </table> </td> </=
tr> </table> </td> </tr> </table> </td> </tr> </table> </a> <!--[if (gte ms=
o 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]-->=
 <a href=3D"https://www.groupon.com/deals/gg-clara-reversible-comforter-set=
-20-piece?p=3D13&utm_source=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd=
7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112=
&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=
=3DGoods-PN&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112"=
 target=3D"_blank" style=3D"color: #000000; font-size: 14px !important; lin=
e-height: 18px !important; color:#000000 !important; text-decoration: none;=
"> <table valign=3D"top" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" s=
tyle=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial,=
 sans-serif; color:#000000; font-weight: normal; text-align: left; width:29=
0px; mso-table-lspace:0;mso-table-rspace:0;" width=3D"290" align=3D'right' =
class=3D"container"> <tr> <td valign=3D"top" width=3D"100%" style=3D"mso-ta=
ble-lspace:0;mso-table-rspace:0; width:100%; padding:20px 0 0 0;"> <table c=
ellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"width:100%;" width=
=3D"100%"> <tr> <td valign=3D"top" align=3D"center" width=3D"290" style=3D"=
width:290px;" class=3D"container"><a href=3D"https://www.groupon.com/deals/=
gg-clara-reversible-comforter-set-20-piece?p=3D13&utm_source=3Dchannel_good=
s&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac=
134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe=
&CID=3DUS&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Deb41cacc-536f-4dfa=
-ab70-f5ab306ec6f0_0_20161112" style=3D"display: block; border: none;" targ=
et=3D"_blank"><img src=3D"https://img.grouponcdn.com/deal/2wj3FjwxiZ2XnfKND=
BR6koQWdrUz/2w-960x576/v1/t300x182.jpg" width=3D"290" style=3D"display: blo=
ck; border: none; width: 290px;" class=3D"100" alt=3D"Clara Bed In A Bag Re=
versible Set (20-Piece)" /></a></td> </tr> <tr> <td> <table cellpadding=3D"=
0" cellspacing=3D"0" border=3D"0" style=3D"width:100%; background: #f2f2f2;=
" width=3D"100%"> <tr> <td class=3D"nameFont" style=3D"padding: 16px 16px 0=
 16px; font-size: 14px !important; line-height: 18px !important; color:#000=
000 !important; text-decoration: none; color: #000000;" align=3D"left"> Cla=
ra Bed In A Bag Set (20-Pc.) </td> </tr> <tr> <td style=3D"background: #f2f=
2f2;" valign=3D"top"><a href=3D"https://www.groupon.com/deals/gg-clara-reve=
rsible-comforter-set-20-piece?p=3D13&utm_source=3Dchannel_goods&utm_medium=
=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561e=
d8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=
=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-deals&utm_campaign=3Deb41cacc-536f-=
4dfa-ab70-f5ab306ec6f0_0_20161112" target=3D"_blank" style=3D"font-size: 14=
px !important; line-height: 18px !important; color:#000000 !important; text=
-decoration: none;">&nbsp;</a></td> </tr> <tr> <td valign=3D"top" style=3D"=
width:290px; min-width:290px; padding-bottom:16px;" class=3D"100"> <table c=
ellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border: 0 none; bo=
rder-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#000000=
; font-weight: normal; text-align: left; background: #f2f2f2; width:290px;"=
 valign=3D"top" width=3D"290" class=3D"container"> <tr> <td style=3D"paddin=
g: 3px 0 0 16px;" align=3D"left"> <span style=3D"padding: 0 5px 0 0; paddin=
g-right: 5px; font-size: 16px; line-height: 20px; text-decoration: line-thr=
ough; color:#848484; font-weight: 100;"> $449.99 </span> <span style=3D"fon=
t-size: 16px; line-height: 20px; font-weight: bold; text-decoration: none; =
color: #e35205;"> $89.99 </span> </td> </tr> <tr> <td class=3D"nameFont" al=
ign=3D"left" valign=3D"top" style=3D"padding: 0px 0px 0px 16px; font-family=
: Helvetica, Arial, sans-serif; font-size: 13px; color: #e35205; text-decor=
ation: none; font-weight: 500 !important;">Sale Ends 11/12</td> <td width=
=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" style=3D"font-fa=
mily: Helvetica, Arial, sans-serif; padding: 0 16px 0 0; font-size: 13px !i=
mportant; line-height: 17px !important; font-weight: normal; font-weight: 6=
00; color: #0185c6 !important; text-decoration: none; text-align:right; whi=
te-space: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-clara-revers=
ible-comforter-set-20-piece?p=3D13&utm_source=3Dchannel_goods&utm_medium=3D=
email&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8c=
d2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Db=
ody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306e=
c6f0_0_20161112" target=3D"_blank" style=3D"color:#0185c6; text-decoration:=
none;"><font color=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </table=
> </td> </tr> </table> </td> </tr> </table> </td> </tr> </table> </a> <!--[=
if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </td> <=
![endif]--> <!--[if (gte mso 9)|(IE)]> </tr> </table> <![endif]--> </td> </=
tr> <tr> <td valign=3D"top" align=3D"left" width=3D"100%" style=3D"width: 6=
00px; min-width:600px;" class=3D"100"> <!--[if (gte mso 9)|(IE)]> <table wi=
dth=3D"600" align=3D"center" cellpadding=3D"0" cellspacing=3D"0" border=3D"=
0"> <tr> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=
=3D"https://www.groupon.com/deals/gg-mens-watches-collection?p=3D14&utm_sou=
rce=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee=
1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2=
-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=
=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" target=3D"_blank" style=
=3D"color: #000000; font-size: 14px !important; line-height: 18px !importan=
t; color:#000000 !important; text-decoration: none;"> <table valign=3D"top"=
 cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border: 0 none; =
border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#0000=
00; font-weight: normal; text-align: left; width:290px; mso-table-lspace:0;=
mso-table-rspace:0;" width=3D"290" align=3D'left' class=3D"container"> <tr>=
 <td valign=3D"top" width=3D"100%" style=3D"mso-table-lspace:0;mso-table-rs=
pace:0; width:100%; padding:20px 0 0 0;"> <table cellpadding=3D"0" cellspac=
ing=3D"0" border=3D"0" style=3D"width:100%;" width=3D"100%"> <tr> <td valig=
n=3D"top" align=3D"center" width=3D"290" style=3D"width:290px;" class=3D"co=
ntainer"><a href=3D"https://www.groupon.com/deals/gg-mens-watches-collectio=
n?p=3D14&utm_source=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03c=
f574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df7=
9c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=3DGoods-PN=
&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" style=3D"d=
isplay: block; border: none;" target=3D"_blank"><img src=3D"https://img.gro=
uponcdn.com/deal/2FdjdYgZCCTNHKYr3qGs2639GhCk/2F-2048x1229/v1/t300x182.jpg"=
 width=3D"290" style=3D"display: block; border: none; width: 290px;" class=
=3D"100" alt=3D"Heritor Helmsley Collection Men's Automatic Watch" /></a></=
td> </tr> <tr> <td> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0"=
 style=3D"width:100%; background: #f2f2f2;" width=3D"100%"> <tr> <td class=
=3D"nameFont" style=3D"padding: 16px 16px 0 16px; font-size: 14px !importan=
t; line-height: 18px !important; color:#000000 !important; text-decoration:=
 none; color: #000000;" align=3D"left"> Heritor Men's Automatic Watch </td>=
 </tr> <tr> <td style=3D"padding: 0 16px 0 16px;" class=3D"nameFont" align=
=3D"left"><a href=3D"https://www.groupon.com/deals/gg-mens-watches-collecti=
on?p=3D14&utm_source=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03=
cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df=
79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DMindst=
orm-Hero-3-deals&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_2016=
1112" target=3D"_blank" style=3D"font-size: 14px !important; line-height: 1=
8px !important; color:#000000 !important; text-decoration: none;"><font col=
or=3D"#e35205">Over 50 bought</font></a></td> </tr> <tr> <td valign=3D"top"=
 style=3D"width:290px; min-width:290px; padding-bottom:16px;" class=3D"100"=
> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border: =
0 none; border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; col=
or:#000000; font-weight: normal; text-align: left; background: #f2f2f2; wid=
th:290px;" valign=3D"top" width=3D"290" class=3D"container"> <tr> <td style=
=3D"padding: 3px 0 0 16px;" align=3D"left"> <span style=3D"padding: 0 5px 0=
 0; padding-right: 5px; font-size: 16px; line-height: 20px; text-decoration=
: line-through; color:#848484; font-weight: 100;"> $1,300 </span> <span sty=
le=3D"font-size: 16px; line-height: 20px; font-weight: bold; text-decoratio=
n: none; color: #e35205;"> $119.99 </span> </td> </tr> <tr> <td class=3D"na=
meFont" align=3D"left" valign=3D"top" style=3D"padding: 0px 0px 0px 16px; f=
ont-family: Helvetica, Arial, sans-serif; font-size: 13px; color: #e35205; =
text-decoration: none; font-weight: 500 !important;">Sale Ends 11/14</td> <=
td width=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" style=3D=
"font-family: Helvetica, Arial, sans-serif; padding: 0 16px 0 0; font-size:=
 13px !important; line-height: 17px !important; font-weight: normal; font-w=
eight: 600; color: #0185c6 !important; text-decoration: none; text-align:ri=
ght; white-space: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-mens=
-watches-collection?p=3D14&utm_source=3Dchannel_goods&utm_medium=3Demail&us=
er=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=
=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=
=3Dbutton&d=3DGoods-PN&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_=
0_20161112" target=3D"_blank" style=3D"color:#0185c6; text-decoration:none;=
"><font color=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </table> </t=
d> </tr> </table> </td> </tr> </table> </td> </tr> </table> </a> <!--[if (g=
te mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endi=
f]--> <a href=3D"https://www.groupon.com/deals/gg-collapsible-metal-pet-cra=
te-with-removable-tray-7?p=3D15&utm_source=3Dchannel_goods&utm_medium=3Dema=
il&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&=
date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody=
&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f=
0_0_20161112" target=3D"_blank" style=3D"color: #000000; font-size: 14px !i=
mportant; line-height: 18px !important; color:#000000 !important; text-deco=
ration: none;"> <table valign=3D"top" cellpadding=3D"0" cellspacing=3D"0" b=
order=3D"0" style=3D"border: 0 none; border-spacing: 0; font-family: 'Open =
Sans', Arial, sans-serif; color:#000000; font-weight: normal; text-align: l=
eft; width:290px; mso-table-lspace:0;mso-table-rspace:0;" width=3D"290" ali=
gn=3D'right' class=3D"container"> <tr> <td valign=3D"top" width=3D"100%" st=
yle=3D"mso-table-lspace:0;mso-table-rspace:0; width:100%; padding:20px 0 0 =
0;"> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"width=
:100%;" width=3D"100%"> <tr> <td valign=3D"top" align=3D"center" width=3D"2=
90" style=3D"width:290px;" class=3D"container"><a href=3D"https://www.group=
on.com/deals/gg-collapsible-metal-pet-crate-with-removable-tray-7?p=3D15&ut=
m_source=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822=
070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539=
-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campai=
gn=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" style=3D"display: blo=
ck; border: none;" target=3D"_blank"><img src=3D"https://img.grouponcdn.com=
/deal/7UfYmNyafsykRgRe7JKB/Ds-960x582/v1/t300x182.jpg" width=3D"290" style=
=3D"display: block; border: none; width: 290px;" class=3D"100" alt=3D"Colla=
psible Metal Pet Crate with Removable Tray" /></a></td> </tr> <tr> <td> <ta=
ble cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"width:100%; b=
ackground: #f2f2f2;" width=3D"100%"> <tr> <td class=3D"nameFont" style=3D"p=
adding: 16px 16px 0 16px; font-size: 14px !important; line-height: 18px !im=
portant; color:#000000 !important; text-decoration: none; color: #000000;" =
align=3D"left"> Collapsible Metal Pet Crate </td> </tr> <tr> <td style=3D"p=
adding: 0 16px 0 16px;" class=3D"nameFont" align=3D"left"><a href=3D"https:=
//www.groupon.com/deals/gg-collapsible-metal-pet-crate-with-removable-tray-=
7?p=3D15&utm_source=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03c=
f574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df7=
9c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DMindsto=
rm-Hero-3-deals&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161=
112" target=3D"_blank" style=3D"font-size: 14px !important; line-height: 18=
px !important; color:#000000 !important; text-decoration: none;"><font colo=
r=3D"#e35205">Over 25,000 bought</font></a></td> </tr> <tr> <td valign=3D"t=
op" style=3D"width:290px; min-width:290px; padding-bottom:16px;" class=3D"1=
00"> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"borde=
r: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; =
color:#000000; font-weight: normal; text-align: left; background: #f2f2f2; =
width:290px;" valign=3D"top" width=3D"290" class=3D"container"> <tr> <td st=
yle=3D"padding: 3px 0 0 16px;" align=3D"left"> <span style=3D"padding: 0 5p=
x 0 0; padding-right: 5px; font-size: 16px; line-height: 20px; text-decorat=
ion: line-through; color:#848484; font-weight: 100;"> $79.95 </span> <span =
style=3D"font-size: 16px; line-height: 20px; font-weight: bold; text-decora=
tion: none; color: #e35205;"> $17.99 </span> </td> </tr> <tr> <td class=3D"=
nameFont" align=3D"left" valign=3D"top" style=3D"padding: 0px 0px 0px 16px;=
 font-family: Helvetica, Arial, sans-serif; font-size: 13px; color: #e35205=
; text-decoration: none; font-weight: 500 !important;">Sale Ends 11/12</td>=
 <td width=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" style=
=3D"font-family: Helvetica, Arial, sans-serif; padding: 0 16px 0 0; font-si=
ze: 13px !important; line-height: 17px !important; font-weight: normal; fon=
t-weight: 600; color: #0185c6 !important; text-decoration: none; text-align=
:right; white-space: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-c=
ollapsible-metal-pet-crate-with-removable-tray-7?p=3D15&utm_source=3Dchanne=
l_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5=
c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-002590=
69d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Deb41cacc-53=
6f-4dfa-ab70-f5ab306ec6f0_0_20161112" target=3D"_blank" style=3D"color:#018=
5c6; text-decoration:none;"><font color=3D"#0185c6">View&nbsp;Deal</font></=
a></td> </tr> </table> </td> </tr> </table> </td> </tr> </table> </td> </tr=
> </table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte =
mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </tr> </table> =
<![endif]--> </td> </tr> <tr> <td valign=3D"top" align=3D"left" width=3D"10=
0%" style=3D"width: 600px; min-width:600px;" class=3D"100"> <!--[if (gte ms=
o 9)|(IE)]> <table width=3D"600" align=3D"center" cellpadding=3D"0" cellspa=
cing=3D"0" border=3D"0"> <tr> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> =
<![endif]--> <a href=3D"https://www.groupon.com/deals/gg-mens-moc-slippers?=
p=3D16&utm_source=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf5=
74337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c=
234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&=
utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" target=3D"_=
blank" style=3D"color: #000000; font-size: 14px !important; line-height: 18=
px !important; color:#000000 !important; text-decoration: none;"> <table va=
lign=3D"top" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"bord=
er: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif;=
 color:#000000; font-weight: normal; text-align: left; width:290px; mso-tab=
le-lspace:0;mso-table-rspace:0;" width=3D"290" align=3D'left' class=3D"cont=
ainer"> <tr> <td valign=3D"top" width=3D"100%" style=3D"mso-table-lspace:0;=
mso-table-rspace:0; width:100%; padding:20px 0 0 0;"> <table cellpadding=3D=
"0" cellspacing=3D"0" border=3D"0" style=3D"width:100%;" width=3D"100%"> <t=
r> <td valign=3D"top" align=3D"center" width=3D"290" style=3D"width:290px;"=
 class=3D"container"><a href=3D"https://www.groupon.com/deals/gg-mens-moc-s=
lippers?p=3D16&utm_source=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c=
8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&u=
u=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=3DGo=
ods-PN&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" styl=
e=3D"display: block; border: none;" target=3D"_blank"><img src=3D"https://i=
mg.grouponcdn.com/deal/2VJ5uqoqMVwx5iyGR6f47XebqE1J/2V-2048x1229/v1/t300x18=
2.jpg" width=3D"290" style=3D"display: block; border: none; width: 290px;" =
class=3D"100" alt=3D"Oak & Rush Men=E2=80=99s Moccasin Slippers | Groupon E=
xclusive " /></a></td> </tr> <tr> <td> <table cellpadding=3D"0" cellspacing=
=3D"0" border=3D"0" style=3D"width:100%; background: #f2f2f2;" width=3D"100=
%"> <tr> <td class=3D"nameFont" style=3D"padding: 16px 16px 0 16px; font-si=
ze: 14px !important; line-height: 18px !important; color:#000000 !important=
; text-decoration: none; color: #000000;" align=3D"left"> Oak & Rush Men's =
Moc Slippers </td> </tr> <tr> <td style=3D"padding: 0 16px 0 16px;" class=
=3D"nameFont" align=3D"left"><a href=3D"https://www.groupon.com/deals/gg-me=
ns-moc-slippers?p=3D16&utm_source=3Dchannel_goods&utm_medium=3Demail&user=
=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D=
20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbu=
tton&d=3DMindstorm-Hero-3-deals&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab=
306ec6f0_0_20161112" target=3D"_blank" style=3D"font-size: 14px !important;=
 line-height: 18px !important; color:#000000 !important; text-decoration: n=
one;"><font color=3D"#e35205">Over 600 bought</font></a></td> </tr> <tr> <t=
d valign=3D"top" style=3D"width:290px; min-width:290px; padding-bottom:16px=
;" class=3D"100"> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" s=
tyle=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial,=
 sans-serif; color:#000000; font-weight: normal; text-align: left; backgrou=
nd: #f2f2f2; width:290px;" valign=3D"top" width=3D"290" class=3D"container"=
> <tr> <td style=3D"padding: 3px 0 0 16px;" align=3D"left"> <span style=3D"=
padding: 0 5px 0 0; padding-right: 5px; font-size: 16px; line-height: 20px;=
 text-decoration: line-through; color:#848484; font-weight: 100;"> $44.99 <=
/span> <span style=3D"font-size: 16px; line-height: 20px; font-weight: bold=
; text-decoration: none; color: #e35205;"> $14.99 </span> </td> </tr> <tr> =
<td class=3D"nameFont" align=3D"left" valign=3D"top" style=3D"padding: 0px =
0px 0px 16px; font-family: Helvetica, Arial, sans-serif; font-size: 13px; c=
olor: #e35205; text-decoration: none; font-weight: 500 !important;">Sale En=
ds 11/13</td> <td width=3D"30%" class=3D"nameFont" align=3D"right" valign=
=3D"top" style=3D"font-family: Helvetica, Arial, sans-serif; padding: 0 16p=
x 0 0; font-size: 13px !important; line-height: 17px !important; font-weigh=
t: normal; font-weight: 600; color: #0185c6 !important; text-decoration: no=
ne; text-align:right; white-space: nowrap;"><a href=3D"https://www.groupon.=
com/deals/gg-mens-moc-slippers?p=3D16&utm_source=3Dchannel_goods&utm_medium=
=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561e=
d8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=
=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab=
306ec6f0_0_20161112" target=3D"_blank" style=3D"color:#0185c6; text-decorat=
ion:none;"><font color=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </t=
able> </td> </tr> </table> </td> </tr> </table> </td> </tr> </table> </a> <=
!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td=
> <![endif]--> <a href=3D"https://www.groupon.com/deals/gg-bluetooth-smart-=
watch-and-health-tracker?p=3D17&utm_source=3Dchannel_goods&utm_medium=3Dema=
il&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&=
date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody=
&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f=
0_0_20161112" target=3D"_blank" style=3D"color: #000000; font-size: 14px !i=
mportant; line-height: 18px !important; color:#000000 !important; text-deco=
ration: none;"> <table valign=3D"top" cellpadding=3D"0" cellspacing=3D"0" b=
order=3D"0" style=3D"border: 0 none; border-spacing: 0; font-family: 'Open =
Sans', Arial, sans-serif; color:#000000; font-weight: normal; text-align: l=
eft; width:290px; mso-table-lspace:0;mso-table-rspace:0;" width=3D"290" ali=
gn=3D'right' class=3D"container"> <tr> <td valign=3D"top" width=3D"100%" st=
yle=3D"mso-table-lspace:0;mso-table-rspace:0; width:100%; padding:20px 0 0 =
0;"> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"width=
:100%;" width=3D"100%"> <tr> <td valign=3D"top" align=3D"center" width=3D"2=
90" style=3D"width:290px;" class=3D"container"><a href=3D"https://www.group=
on.com/deals/gg-bluetooth-smart-watch-and-health-tracker?p=3D17&utm_source=
=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed=
8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82=
c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Deb4=
1cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" style=3D"display: block; bord=
er: none;" target=3D"_blank"><img src=3D"https://img.grouponcdn.com/deal/ie=
F2u2dwaUkkSSRyVRZaCBGA588/ie-1000x600/v1/t300x182.jpg" width=3D"290" style=
=3D"display: block; border: none; width: 290px;" class=3D"100" alt=3D"Bluet=
ooth Smartwatch and Health Tracker" /></a></td> </tr> <tr> <td> <table cell=
padding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"width:100%; backgroun=
d: #f2f2f2;" width=3D"100%"> <tr> <td class=3D"nameFont" style=3D"padding: =
16px 16px 0 16px; font-size: 14px !important; line-height: 18px !important;=
 color:#000000 !important; text-decoration: none; color: #000000;" align=3D=
"left"> Bluetooth Smartwatch and Tracker </td> </tr> <tr> <td style=3D"padd=
ing: 0 16px 0 16px;" class=3D"nameFont" align=3D"left"><a href=3D"https://w=
ww.groupon.com/deals/gg-bluetooth-smart-watch-and-health-tracker?p=3D17&utm=
_source=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c8220=
70ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-=
11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-de=
als&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" target=
=3D"_blank" style=3D"font-size: 14px !important; line-height: 18px !importa=
nt; color:#000000 !important; text-decoration: none;"><font color=3D"#e3520=
5">Over 1,000 bought</font></a></td> </tr> <tr> <td valign=3D"top" style=3D=
"width:290px; min-width:290px; padding-bottom:16px;" class=3D"100"> <table =
cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border: 0 none; b=
order-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#00000=
0; font-weight: normal; text-align: left; background: #f2f2f2; width:290px;=
" valign=3D"top" width=3D"290" class=3D"container"> <tr> <td style=3D"paddi=
ng: 3px 0 0 16px;" align=3D"left"> <span style=3D"padding: 0 5px 0 0; paddi=
ng-right: 5px; font-size: 16px; line-height: 20px; text-decoration: line-th=
rough; color:#848484; font-weight: 100;"> $78.99 </span> <span style=3D"fon=
t-size: 16px; line-height: 20px; font-weight: bold; text-decoration: none; =
color: #e35205;"> $17.99 </span> </td> </tr> <tr> <td class=3D"nameFont" al=
ign=3D"left" valign=3D"top" style=3D"padding: 0px 0px 0px 16px; font-family=
: Helvetica, Arial, sans-serif; font-size: 13px; color: #e35205; text-decor=
ation: none; font-weight: 500 !important;">Sale Ends 11/14</td> <td width=
=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" style=3D"font-fa=
mily: Helvetica, Arial, sans-serif; padding: 0 16px 0 0; font-size: 13px !i=
mportant; line-height: 17px !important; font-weight: normal; font-weight: 6=
00; color: #0185c6 !important; text-decoration: none; text-align:right; whi=
te-space: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-bluetooth-sm=
art-watch-and-health-tracker?p=3D17&utm_source=3Dchannel_goods&utm_medium=
=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561e=
d8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=
=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab=
306ec6f0_0_20161112" target=3D"_blank" style=3D"color:#0185c6; text-decorat=
ion:none;"><font color=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </t=
able> </td> </tr> </table> </td> </tr> </table> </td> </tr> </table> </a> <=
!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </t=
d> <![endif]--> <!--[if (gte mso 9)|(IE)]> </tr> </table> <![endif]--> </td=
> </tr> </table> </td> </tr> </table> <table cellpadding=3D"0" cellspacing=
=3D"0" style=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans'=
, Arial, sans-serif; color:#000000; font-weight: normal; text-align: left; =
width: 600px;" align=3D"center" class=3D"container"> <tr> <td style=3D"padd=
ing: 30px;" align=3D"center"> <table cellpadding=3D"0" cellspacing=3D"0" st=
yle=3D"border: 0 none; border-spacing:0; font-family: 'HelveticaNeue', 'Hel=
vetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; color:#000000;=
 text-align: left; width:200px;" align=3D"center"> <tr> <td height=3D"45" b=
gcolor=3D"#3ebddc" background=3D"http://s3.grouponcdn.com/email/images/prom=
_night/global_buttons/pn-btn-gradient-blue.gif" background-repeat=3D"repeat=
-x" style=3D"height:45px; text-align:center;"><a href=3D"http://www.groupon=
.com/goods?utm_source=3Dchannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf0=
3cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3D=
f79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods=
&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" style=3D"p=
adding: 10px; color:#ffffff; font-size:16px; font-weight: 500; text-decorat=
ion:none;">VIEW&nbsp;ALL&nbsp;GOODS</a></td> </tr> </table> </td> </tr> </t=
able> </td> </tr> </table> </td> </tr> </table> </td> </tr> </table> <table=
 cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacin=
g: 0; font-family: 'Open Sans', Arial, sans-serif; color:#000000; font-weig=
ht: normal; text-align: left; width: 100%; background: #f2f2f2;" align=3D"c=
enter" class=3D"container"> <tr> <td align=3D"center" style=3D"padding: 30p=
x 0 0 0;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"width: 600px=
; background: #f2f2f2;" align=3D"center" class=3D"container" width=3D"600">=
 <tr> <td style=3D"font-size: 16px; color: #888888; line-height: 119%; padd=
ing: 10px 10px 10px 10px;" align=3D"center">Need help? Have feedback? Feel =
free to <a href=3D"http://www.groupon.com/customer_support?utm_source=3Dcha=
nnel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806f=
bf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-002=
59069d5fe&CID=3DUS&s=3Dfooter&c=3Dlink&d=3Dsupport&utm_campaign=3Deb41cacc-=
536f-4dfa-ab70-f5ab306ec6f0_0_20161112" style=3D"color:#0185C6; text-decora=
tion:none;" target=3D"_blank">contact us</a></td> </tr> <tr> <td style=3D"f=
ont-size: 10px; color: #999999; line-height: 120%; padding: 10px 10px 0 10p=
x;" align=3D"center" class=3D"mobile-font">Delivered by Groupon Inc. 600 W.=
 Chicago Avenue, Suite 400 Chicago, IL, 60654, USA</td> </tr> <tr> <td styl=
e=3D"font-size: 10px; color: #999999; line-height: 120%; padding: 0 10px 10=
px 10px;" align=3D"center" class=3D"mobile-font">You are receiving this ema=
il because kyle@kylefisher.com is signed up to receive Groupon communicatio=
ns. To adjust how often you receive Groupon emails, including unsubscribing=
, <a href=3D"https://www.groupon.com/subscription_center/manage/consumer/f7=
9c234c-2539-11e2-82c0-00259069d5fe?cmplistId=3Dchannel:goods&utm_source=3Dc=
hannel_goods&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f80=
6fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-0=
0259069d5fe&CID=3DUS&s=3Dfooter&c=3Dlink&d=3Dunsubscribe&utm_campaign=3Deb4=
1cacc-536f-4dfa-ab70-f5ab306ec6f0_0_20161112" style=3D"color:#0185C6; text-=
decoration:none;">click here</a></td> </tr> </table> </td> </tr> </table> <=
img src =3D "http://www.groupon.com/analytic/track.gif?p=3D2&utm_domain=3Dk=
ylefisher.com&utm_campaign=3Deb41cacc-536f-4dfa-ab70-f5ab306ec6f0_0_2016111=
2&deals=3De4b86602-8fff-11e6-b02a-002590604002,4e681656-9ac3-11e6-904b-0025=
90604002,65f812b6-2d2d-4ef3-8240-7aa13cc64f74,1dd7fefc-9145-11e6-a174-00259=
060b5da,8618b342-20fe-11e6-9a20-00259069d868,72678418-8a58-11e6-bcd0-002590=
60b5da,412a9e8a-655f-11e6-ad73-00259069d7cc,84515d72-6f9e-11e6-8848-0025906=
0b5da,82a6ee0c-e159-11e5-a001-00259098451c,d709a94a-9585-11e6-a59f-00259060=
4002,394ff112-90c3-11e6-b6f6-00259069d868,c0da0158-8688-11e6-9a35-00259060b=
5da,b8a5d694-924d-11e6-9063-00259060b5da,b705037a-6b8c-11e5-9189-002590980a=
98,d799a6dd-bce0-4ad3-9ffe-66824bdd6b67,8d79dee2-28fe-11e6-a577-00259060400=
2&channel_deals=3Dnull&utm_source=3Dchannel_goods&utm_medium=3Demail&user=
=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D=
20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS" height=3D"1" w=
idth=3D"1" style=3D"display: none !important;" /> </body> </html>

