From d8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2@bounce.r.groupon.com Sat Nov 12 07:34:47 2016
Received: from mta187s1.r.groupon.com ([50.115.211.187]:23228)
	by ecbiz209.inmotionhosting.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <d8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2@bounce.r.groupon.com>)
	id 1c5XWB-001opn-9S
	for kyle@kylefisher.com; Sat, 12 Nov 2016 07:34:47 -0500
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=r.groupon.com;
	s=s2048d20160829; t=1478954086;
	bh=eLab1SxfgeEyeTuKxh0T5yUBtMl1lMSkAUVUsOgCJfo=;
	h=Date:From:To:Message-ID:Subject:Content-Type;
	b=tA/8Pum0yUgWtAVNvqOnTAPsXZJsaUsXwMvFs1QmqV++//ZcxsomlOjUSG9spX3zd
	 VHyfdXC4rRLO+LsyVETe0kfvGnJUXJSwfOm8ruyeaSAz0D706NPx284Py5vpX0j6JN
	 veGx9eJAccP/JWsNC+LdFVsf9eo3edsaHpPRJuD4nePNytZU8qupBFNWzsEwpiZwn5
	 5GAegLRkqyH0/MbgLY7X8FVHRIKU1zolXb12Z/5zdDLHjne+XmEghWwIYoPtaAw/yZ
	 /t7mgRB0EabHLERnDJGQu+dPTfsnBpyenwvFFYb/PtUhP7UFpwAhw2E44x5mIgNXMr
	 UATQz5XyCYS5w==
Date: Sat, 12 Nov 2016 12:34:46 +0000
From: Groupon Experiences <noreply@r.groupon.com>
To: kyle@kylefisher.com
Message-ID: <1183262748.15526707.1478954086420.JavaMail.rocketman@push-dispatcher1>
Subject: Holiday Fun: The More the Merrier
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
X-RM-UserHash: d8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2
X-RM-SendId: d76ff3d1-4581-4e7a-9e69-9fbfac744940_0_20161112_treatment1
X-RM-SenderScore: 0
X-RM-EmailName: channel-occasions_us_im_20161112_Gatheringg_allElse_v2_treatment1
X-MSFBL: a3lsZUBreWxlZmlzaGVyLmNvbTpiYXRjaDpkNzZmZjNkMS00NTgxLTRlN2EtOWU2OS05ZmJmYWM3NDQ5NDBfMF8yMDE2MTExMl90cmVhdG1lbnQxOm51bGw6VVM=
List-Unsubscribe: <mailto:d8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2@unsub.r.groupon.com?subject=a3lsZUBreWxlZmlzaGVyLmNvbTpiYXRjaDpkNzZmZjNkMS00NTgxLTRlN2EtOWU2OS05ZmJmYWM3NDQ5NDBfMF8yMDE2MTExMl90cmVhdG1lbnQxOm51bGw6VVM=>
X-RPCampaign: Grouponchanneloccasionsusim20161112GatheringgallElsev2treatment120161112
X-RPTags: channel-occasions_us_im_20161112_Gatheringg_allElse_v2_treatment1
X-Recruiting: Interested in headers? Join us: www.groupon.com/techjobs/
List-Id: <channel-occasions_us_im_20161112_Gatheringg_allElse_v2_treatment1_20161112.groupon>
X-Feedback-ID: r.groupon.com:channel-occasions_us_im_20161112_Gatheringg_allElse_v2_treatment1:d76ff3d1-4581-4e7a-9e69-9fbfac744940_0_20161112_treatment1:groupon

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.=
w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> <html xmlns=3D"http://www.w3=
.org/1999/xhtml" xmlns:v=3D"urn:schemas-microsoft-com:vml" xmlns:o=3D"urn:s=
chemas-microsoft-com:office:office"> <head> <meta http-equiv=3D"Content-Typ=
e" content=3D"text/html; charset=3Dutf-8" /> <title>Groupon</title> <style =
type=3D"text/css"> .ExternalClass * {line-height: 100%} /* override ios min=
imum font-size*/ div, p, a, li, td { -webkit-text-size-adjust:none; } img[c=
lass=3D"100"]{ width: 100% !important; min-width: 100% !important; max-widt=
h: 100% !important; } table { font-family: 'Open Sans', Arial, sans-serif !=
important; } @media only screen and (max-width: 580px) { table[class=3D"con=
tainer"]{ margin: 0 auto !important; width: 100% !important; min-width: 100=
% !important; } td[class=3D"container"]{ width: 100% !important; min-width:=
 100% !important; float: left !important; position: relative !important; pa=
dding: 0px !important; } td[class=3D"100"]{ width: 100% !important; min-wid=
th: 100% !important; height: auto !important; float: left !important; } td[=
class=3D"mobile-hdr-logo-center"]{ padding: 25px 0 10px 0 !important; } /* =
Image Classes */ img[class=3D"100"]{ width: 100% !important; min-width: 100=
% !important; max-width: 100% !important; } /* Col Sections */ *[class=3D"c=
ollapse-left"]{ width: 100% !important; float: left !important; position: r=
elative !important; padding: 20px 0 20px 0 !important; border-bottom: 1px s=
olid #cccccc !important; } *[class=3D"collapse-right"]{ width: 100% !import=
ant; float: left !important; position: relative !important; padding: 20px 0=
 20px 0 !important; border: none !important; } *[class=3D"collapse-left-rtl=
"]{ width: 100% !important; float: left !important; position: relative !imp=
ortant; padding: 20px 0 20px 0 !important; border: none !important; } *[cla=
ss=3D"collapse-right-rtl"]{ width: 100% !important; float: left !important;=
 position: relative !important; padding: 20px 0 20px 0 !important; border-b=
ottom: 1px solid #cccccc !important; } td[class=3D"collapse-trxn"]{ width: =
100% !important; float: left !important; position: relative !important; pad=
ding: 30px 0 0 0 !important; } td[class=3D"container-33"] { min-width: 33% =
!important; } td[class=3D"col-4-mobile"]{ width: 65% !important; } td[class=
=3D"mobile-container-padding"]{ padding: 20px 10px 20px 10px !important; } =
td.ga-mobile-pad { padding: 20px 0 15px 10px !important; } /* GA Partity, W=
eekend, Live! needs to be removed */ td[class=3D"weekend-mobile-container-p=
adding"]{ padding: 0px 10px 20px 10px !important; } td[class=3D"mobile-cont=
ainer-nav-padding"]{ padding: 10px 0 10px 0 !important; } /* Goods Parity H=
eader */ td[class=3D"floatLeft-ship"]{ float: left !important; width: 100% =
!important; border: 0px none !important; text-align: left !important; paddi=
ng: 5px 0 15px 0 !important; line-height: 14px !important; font-size: 13px =
!important; } td[class=3D"floatLeft-name"]{ float: left !important; width: =
100% !important; border: 0px none !important; text-align: left !important; =
padding: 5px 0 5px 0 !important; line-height: 14px !important; font-weight:=
 bold !important; font-size: 13px !important; } /* Turn off desktop CSS */ =
td[class=3D"no-padding"]{ padding: 0px !important; } td[class=3D"no-border-=
no-padding"]{ padding: 0px !important; border: none !important; } .no-borde=
r { border: none !important; } *[class=3D"display-off"]{ display: none !imp=
ortant; } /*Goods Shipment Notification and Transaction Failed */ td[class=
=3D"shipment-col-4-mobile"]{ width: 50% !important; } /*Welcome Day 0 Redes=
ign */ *[class=3D"container-white"]{ width: 100% !important; background-col=
or: #ffffff !important; padding: 0 0 0 0 !important; } *[class=3D"textAlign=
Center"]{ text-align: center !important; } /* Buttons */ table[class=3D"but=
ton-width"]{ width: 80px !important; } td[class=3D"viewButtonMobile"]{ padd=
ing: 12px 10px 12px 10px !important; } /* Banners */ *[class=3D"mobile-bann=
er"]{ width: 100%!important; max-height: none!important; height: auto!impor=
tant; display: block!important; padding: 20px 0 0 0!important; color: #0000=
00!important; font-size: 32px!important; line-height: 24px !important; } *[=
class=3D"mobile-banner-img"]{ width: 100%!important; max-height: none!impor=
tant; height: auto!important; display:block!important; padding: 0 0 0 0!imp=
ortant; color: #000000!important; font-size: 12px!important; } *[class=3D"m=
obile-banner-img-pad"]{ width: 100%!important; max-height: none!important; =
height: auto!important; display:block!important; padding: 0 0 10px 0!import=
ant; color: #000000!important; font-size: 12px!important; } *[class=3D"2up-=
image-mobile"]{ width: 100% !important; max-height: none!important; height:=
 auto!important; display: block!important; float: left !important; } /* Use=
r Messaging Service */ *[class=3D"heading_style"]{ -webkit-text-size-adjust=
:none !important; font-size:13px !important; font-style:normal !important; =
font-variant:normal !important; font-weight:normal !important; font-family:=
Arial, Verdana, sans-serif !important; color:#cdf5ff !important; line-heigh=
t:18px !important; } /* Font Classes */ td[class=3D"mobile-font"]{ font-siz=
e: 13px !important; } span[class=3D"nameFont"]{ font-size: 18px !important;=
 line-height: 22px !important; } td[class=3D"nameFont"]{ font-size: 18px !i=
mportant; line-height: 22px !important; } td[class=3D"themeFont"]{ font-siz=
e: 30px !important; line-height: 34px !important; } td[class=3D"heroNameFon=
t"]{ font-size: 18px !important; line-height: 22px !important; } a[class=3D=
"heroNameFont"]{ text-decoration: none !important; font-size: 18px !importa=
nt; line-height: 22px !important; } *[class=3D"font-12"]{ font-size:12px !i=
mportant; } *[class=3D"font-13"]{ font-size:13px !important; } *[class=3D"f=
ont-16"]{ font-size:16px !important; } *[class=3D"font-18"]{ font-size:18px=
 !important; } img[class=3D"glive-deal-image"]{ width: 80% !important; heig=
ht: auto !important; display: block; margin:0 auto; padding: 0; } div[class=
=3D"gmailfix"] { display: none; display: none !important; } td[class=3D"col=
lapse-left-postcard"]{ width: 100% !important; float: left !important; posi=
tion: relative !important; padding: 20px 0 20px 0 !important; } table[class=
=3D"seo-button-width"]{ width: 158px !important; } table[class=3D"container=
_border"]{ width: 100% !important; padding: 0 0 0 0 !important; } *[class=
=3D"margin_zero_auto"]{ margin: 0 auto !important; display: block !importan=
t; } *[class=3D"text_pad"]{ padding:7px 0 0 0 !important; } *[class=3D"disp=
lay_table"]{ display: block !important; width:100% !important; } } </style>=
 <link href=3D'https://fonts.googleapis.com/css?family=3DOpen+Sans:100,200,=
400,300,500,600,700,800' rel=3D'stylesheet' type=3D'text/css' /> </head> <b=
ody style=3D"margin:0 !important; padding:0 !important; background: #f2f2f2=
 !important;"> <img src =3D "http://www.groupon.com/analytic/track.gif?p=3D=
1&utm_domain=3Dkylefisher.com&utm_campaign=3Dd76ff3d1-4581-4e7a-9e69-9fbfac=
744940_0_20161112_treatment1&deals=3D02777df3-32b8-49f9-a217-47d385dc5f67,a=
74c3827-2320-45f0-9e48-ddee9421f99a,c8a49923-291e-43f0-915a-e32770631efb,fb=
6aba04-3788-47ca-b7d6-5709eb63106e,93b6ad1f-5e68-40e5-92dd-2847fed1fa3b,f11=
3e090-4141-4999-af8b-fb5d2844a148,50e83380-3525-4a46-9bea-a90339396ff1,6e80=
ad7e-1f40-4006-bd61-f4ded6e4a155,d5adecca-0720-4f09-9277-76aed0bb03c6,e3ae8=
29f-7c77-4c5d-a809-9dca74b5094f,48f554d9-49e4-4dba-91bf-e45eae37b7a8,e13588=
82-a6e9-4eeb-afec-d3f0ef40792e,c88a2f9a-688a-4a26-8c40-07d038c8d97f,37bb931=
b-983a-4c49-bc68-2e839616062f,2d9a16ca-9e31-4689-ad9e-dd0f8e7e426b,bad5fcd2=
-57cd-f575-5c3f-0cba6bfa49e4&channel_deals=3Dnull&utm_source=3Dchannel_occa=
sions_area51&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f80=
6fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-0=
0259069d5fe&CID=3DUS" height=3D"1" width=3D"1" style=3D"display: none !impo=
rtant;" /> <span style=3D"color: #ffffff; font-size: 0px;" height=3D"0"> </=
span> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; b=
order-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#00000=
0; font-weight: normal; text-align: left; width: 100%; background: #f2f2f2;=
" align=3D"center"> <tr> <td align=3D"center" style=3D"padding: 20px 0 15px=
 0;" class=3D"mobile-hdr-logo-center"><a href=3D"http://www.groupon.com/?ut=
m_source=3Dchannel_occasions_area51&utm_medium=3Demail&user=3Dd8bfd7c8bf03c=
f574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df7=
9c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dheader&c=3Dimage&d=3DGroupo=
n&utm_campaign=3Dd76ff3d1-4581-4e7a-9e69-9fbfac744940_0_20161112_treatment1=
" style=3D"font-size: 34px; color: #333333; font-weight: normal; color:#fff=
fff; font-weight: 700;" target=3D"_blank"><img src=3D"http://s3.grouponcdn.=
com/email/images/prom_night/global_images/hdr-logo-GRPN-green.png" style=3D=
"display: block; border: none; width: 151px;" width=3D"151" alt=3D"GROUPON&=
reg;" title=3D"GROUPON&reg;" /></a></td> </tr> </table> <table cellpadding=
=3D"0" cellspacing=3D"0" style=3D"width: 100%; background: #f2f2f2" align=
=3D"center"> <tr> <td align=3D"center"> <table cellpadding=3D"0" cellspacin=
g=3D"0" style=3D"width: 670px; background: #ffffff;" bgcolor=3D"#ffffff" al=
ign=3D"center" class=3D"container"> <tr> <td align=3D"center"> <table cellp=
adding=3D"0" cellspacing=3D"0" style=3D"width: 600px; min-width:600px; back=
ground: #ffffff;" bgcolor=3D"#ffffff" align=3D"center" class=3D"container">=
 <tr> <td align=3D"center" style=3D"padding: 5px 0 40px 0;" class=3D"mobile=
-container-padding"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"bo=
rder: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, sans-seri=
f; color:#000000; font-weight: normal; text-align: left; width: 100%; backg=
round-color: #ffffff;" align=3D"center"> <tr> <td style=3D"padding: 0px; di=
splay:none; font-size:0; max-height:0; line-height:0; mso-hide: all;" class=
=3D"mobile-banner"><a href=3D"https://www.groupon.com/occasion/gathering-th=
ings-to-do?p=3D1&utm_source=3Dchannel_occasions_area51&utm_medium=3Demail&u=
ser=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=
=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=
=3Dbanner&d=3Ddynamic-banner-0&utm_campaign=3Dd76ff3d1-4581-4e7a-9e69-9fbfa=
c744940_0_20161112_treatment1" style=3D"color:#0185C6; text-decoration:none=
;" target=3D"_blank"> <img src=3D"https://img.grouponcdn.com/deal/JEKjXrjTD=
yY5gaQmo2tydbYF2UX/JE-460x120" style=3D"padding:0px; display:none; font-siz=
e:0; max-height:0; line-height:0; mso-hide: all;" class=3D"mobile-banner-im=
g" alt=3D"The Gang's All Cheer" /></a> </td> </tr> </table> <table cellpadd=
ing=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing: 0; fon=
t-family: 'Open Sans', Arial, sans-serif; color:#000000; font-weight: norma=
l; text-align: left; width: 100%; min-width:290px; background-color: #fffff=
f;" align=3D"center" class=3D"display-off"> <tr> <td align=3D"center" style=
=3D"padding: 20px 0 0 0; min-width:290px;"><a href=3D"https://www.groupon.c=
om/occasion/gathering-things-to-do?p=3D1&utm_source=3Dchannel_occasions_are=
a51&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2ac=
ac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5=
fe&CID=3DUS&s=3Dbody&c=3Dbanner&d=3Ddynamic-banner-0&utm_campaign=3Dd76ff3d=
1-4581-4e7a-9e69-9fbfac744940_0_20161112_treatment1" style=3D"color:#0185C6=
; text-decoration:none;" target=3D"_blank"> <img src=3D"https://img.groupon=
cdn.com/deal/VXFkV1KRcSKjnxouPfEoznL1YGW/VX-600x100" style=3D"display: bloc=
k; border: none; min-width:290px;" alt=3D"The Gang's All Cheer" /></a> </td=
> </tr> </table> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"width:=
 600px; min-width:600px;" width=3D"600" align=3D"center" class=3D"container=
"> <tr> <td align=3D"center" style=3D"width:600px; min-width:600px;" width=
=3D"600" class=3D"container"> <table cellpadding=3D"0" cellspacing=3D"0" st=
yle =3D "border: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial=
, sans-serif; color:#000000; font-weight: normal; text-align: left; width: =
600px;" align=3D "center" class=3D"container"> <tr> <td align=3D"left"> <ta=
ble cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spa=
cing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#000000; font-w=
eight: normal; text-align: left; width:290px; background: #ffffff;" class=
=3D"container" align=3D'left'> <tr> <td style=3D"padding: 20px 0 0 0;" alig=
n=3D'left'> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 n=
one; border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:=
#000000; font-weight: normal; text-align: left; width: 100%;"> <tr> <td val=
ign=3D"top" colspan=3D"2"><a href=3D"https://www.groupon.com/deals/sesame-p=
lace-103?p=3D2&utm_source=3Dchannel_occasions_area51&utm_medium=3Demail&use=
r=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=
=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=
=3Dimage&d=3Ddeal-page&utm_campaign=3Dd76ff3d1-4581-4e7a-9e69-9fbfac744940_=
0_20161112_treatment1" target=3D"_blank" style=3D"color:#0185C6; text-decor=
ation:none;"><img src=3D"https://img.grouponcdn.com/deal/oLtrqfoXZiKF9EQHWb=
cUEM64du9/oL-2048x1229/v1/t300x182.jpg" style=3D"display: block; border: no=
ne; width: 290px;" width=3D"290" alt=3D"A Very Furry Christmas" title=3D"A =
Very Furry Christmas" class=3D"100"></a></td> </tr> <tr> <td align=3D"left"=
 style=3D"font-size: 16px; color: #333333; font-weight: normal; padding: 20=
px 0 0 0;"colspan=3D"2">A Very Furry Christmas</td> </tr> <tr> <td align=3D=
"left" style=3D"font-size: 13px; color: #999999; font-weight: normal; paddi=
ng: 5px 0 0 0;"colspan=3D"2">Sesame Place</td> </tr> <tr> <td style=3D"padd=
ing: 3px 0 0 0;" align=3D"left"> <span style=3D"padding: 0 5px 0 0; padding=
-right: 5px; font-size: 16px; line-height: 20px; text-decoration: line-thro=
ugh; color:#848484; font-weight: 100;"> $34.24 </span> <span style=3D"font-=
size: 16px; line-height: 20px; color:#53A318; font-weight: 300; text-decora=
tion: none; font-weight: bold;"> $21 </span> </td> </tr> </table> </td> </t=
r> </table> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 n=
one; border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:=
#000000; font-weight: normal; text-align: left; width:290px; background: #f=
fffff;" class=3D"container" align=3D'right'> <tr> <td style=3D"padding: 20p=
x 0 0 0;" align=3D'right'> <table cellpadding=3D"0" cellspacing=3D"0" style=
=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, san=
s-serif; color:#000000; font-weight: normal; text-align: left; width: 100%;=
"> <tr> <td valign=3D"top" colspan=3D"2"><a href=3D"https://www.groupon.com=
/deals/gl-the-calamari-sisters-winter-sausage-fest-2?p=3D3&utm_source=3Dcha=
nnel_occasions_area51&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070=
ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11=
e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=3Ddeal-page&utm_campaign=
=3Dd76ff3d1-4581-4e7a-9e69-9fbfac744940_0_20161112_treatment1" target=3D"_b=
lank" style=3D"color:#0185C6; text-decoration:none;"><img src=3D"https://im=
g.grouponcdn.com/deal/2Nh5UWwvULZa1XPygXRByJV1Y8CV/2N-1000x600/v1/t300x182.=
jpg" style=3D"display: block; border: none; width: 290px;" width=3D"290" al=
t=3D"Comedy: Calamari Sisters" title=3D"Comedy: Calamari Sisters" class=3D"=
100"></a></td> </tr> <tr> <td align=3D"left" style=3D"font-size: 16px; colo=
r: #333333; font-weight: normal; padding: 20px 0 0 0;"colspan=3D"2">Comedy:=
 Calamari Sisters</td> </tr> <tr> <td align=3D"left" style=3D"font-size: 13=
px; color: #999999; font-weight: normal; padding: 5px 0 0 0;"colspan=3D"2">=
The Calamari Sisters' Winter Sausag</td> </tr> <tr> <td align=3D"left" styl=
e=3D"font-size: 13px; color: #999999; font-weight: normal;" colspan=3D"2">P=
enn's Landing Playhouse </td> </tr> <tr> <td style=3D"padding: 3px 0 0 0;" =
align=3D"left"> <span style=3D"padding: 0 5px 0 0; padding-right: 5px; font=
-size: 16px; line-height: 20px; text-decoration: line-through; color:#84848=
4; font-weight: 100;"> $71 </span> <span style=3D"font-size: 16px; line-hei=
ght: 20px; color:#53A318; font-weight: 300; text-decoration: none; font-wei=
ght: bold;"> $49 </span> </td> </tr> </table> </td> </tr> </table> </td> </=
tr> <tr> <td align=3D"left"> <table cellpadding=3D"0" cellspacing=3D"0" sty=
le=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, s=
ans-serif; color:#000000; font-weight: normal; text-align: left; width:290p=
x; background: #ffffff;" class=3D"container" align=3D'left'> <tr> <td style=
=3D"padding: 20px 0 0 0;" align=3D'left'> <table cellpadding=3D"0" cellspac=
ing=3D"0" style=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sa=
ns', Arial, sans-serif; color:#000000; font-weight: normal; text-align: lef=
t; width: 100%;"> <tr> <td valign=3D"top" colspan=3D"2"><a href=3D"https://=
www.groupon.com/deals/gl-bret-michaels-the-party-starts-now-tour-at-electri=
c-factory-2?p=3D4&utm_source=3Dchannel_occasions_area51&utm_medium=3Demail&=
user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&dat=
e=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=
=3Dimage&d=3Ddeal-page&utm_campaign=3Dd76ff3d1-4581-4e7a-9e69-9fbfac744940_=
0_20161112_treatment1" target=3D"_blank" style=3D"color:#0185C6; text-decor=
ation:none;"><img src=3D"https://img.grouponcdn.com/deal/USZJsqfDVW8jAYbFuj=
px2PPhgjj/US-700x420/v1/t300x182.jpg" style=3D"display: block; border: none=
; width: 290px;" width=3D"290" alt=3D"Bret Michaels" title=3D"Bret Michaels=
" class=3D"100"></a></td> </tr> <tr> <td align=3D"left" style=3D"font-size:=
 16px; color: #333333; font-weight: normal; padding: 20px 0 0 0;"colspan=3D=
"2">Bret Michaels</td> </tr> <tr> <td align=3D"left" style=3D"font-size: 13=
px; color: #999999; font-weight: normal; padding: 5px 0 0 0;"colspan=3D"2">=
Bret Michaels</td> </tr> <tr> <td align=3D"left" style=3D"font-size: 13px; =
color: #999999; font-weight: normal;" colspan=3D"2">The Electric Factory</t=
d> </tr> <tr> <td style=3D"padding: 3px 0 0 0;" align=3D"left"> <span style=
=3D"padding: 0 5px 0 0; padding-right: 5px; font-size: 16px; line-height: 2=
0px; text-decoration: line-through; color:#848484; font-weight: 100;"> $56.=
85 </span> <span style=3D"font-size: 16px; line-height: 20px; color:#53A318=
; font-weight: 300; text-decoration: none; font-weight: bold;"> $29 </span>=
 </td> </tr> </table> </td> </tr> </table> <table cellpadding=3D"0" cellspa=
cing=3D"0" style=3D"border: 0 none; border-spacing: 0; font-family: 'Open S=
ans', Arial, sans-serif; color:#000000; font-weight: normal; text-align: le=
ft; width:290px; background: #ffffff;" class=3D"container" align=3D'right'>=
 <tr> <td style=3D"padding: 20px 0 0 0;" align=3D'right'> <table cellpaddin=
g=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing: 0; font-=
family: 'Open Sans', Arial, sans-serif; color:#000000; font-weight: normal;=
 text-align: left; width: 100%;"> <tr> <td valign=3D"top" colspan=3D"2"><a =
href=3D"https://www.groupon.com/deals/studio-movie-grill-119?p=3D5&utm_sour=
ce=3Dchannel_occasions_area51&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf57433=
7c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c=
-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=3Ddeal-page&utm_=
campaign=3Dd76ff3d1-4581-4e7a-9e69-9fbfac744940_0_20161112_treatment1" targ=
et=3D"_blank" style=3D"color:#0185C6; text-decoration:none;"><img src=3D"ht=
tps://img.grouponcdn.com/deal/dGcxGLL8T4je3ZfvtbJU/tn-700x420/v1/t300x182.j=
pg" style=3D"display: block; border: none; width: 290px;" width=3D"290" alt=
=3D"Tickets to Newest Movies" title=3D"Tickets to Newest Movies" class=3D"1=
00"></a></td> </tr> <tr> <td align=3D"left" style=3D"font-size: 16px; color=
: #333333; font-weight: normal; padding: 20px 0 0 0;"colspan=3D"2">Tickets =
to Newest Movies</td> </tr> <tr> <td align=3D"left" style=3D"font-size: 13p=
x; color: #999999; font-weight: normal; padding: 5px 0 0 0;"colspan=3D"2">S=
tudio Movie Grill</td> </tr> <tr> <td align=3D"left" style=3D"font-size: 13=
px; color: #999999; font-weight: normal;" colspan=3D"2">Upper Darby</td> </=
tr> <tr> <td style=3D"padding: 3px 0 0 0;" align=3D"left"> <span style=3D"p=
adding: 0 5px 0 0; padding-right: 5px; font-size: 16px; line-height: 20px; =
text-decoration: line-through; color:#848484; font-weight: 100;"> $10.50 </=
span> <span style=3D"font-size: 16px; line-height: 20px; color:#53A318; fon=
t-weight: 300; text-decoration: none; font-weight: bold;"> $5 </span> </td>=
 </tr> </table> </td> </tr> </table> </td> </tr> <tr> <td align=3D"left"> <=
table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-s=
pacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#000000; font=
-weight: normal; text-align: left; width:290px; background: #ffffff;" class=
=3D"container" align=3D'left'> <tr> <td style=3D"padding: 20px 0 0 0;" alig=
n=3D'left'> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 n=
one; border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:=
#000000; font-weight: normal; text-align: left; width: 100%;"> <tr> <td val=
ign=3D"top" colspan=3D"2"><a href=3D"https://www.groupon.com/deals/elmwood-=
park-zoo-10?p=3D6&utm_source=3Dchannel_occasions_area51&utm_medium=3Demail&=
user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&dat=
e=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=
=3Dimage&d=3Ddeal-page&utm_campaign=3Dd76ff3d1-4581-4e7a-9e69-9fbfac744940_=
0_20161112_treatment1" target=3D"_blank" style=3D"color:#0185C6; text-decor=
ation:none;"><img src=3D"https://img.grouponcdn.com/deal/4SxdEGocwmDEPzwCb1=
yqMuDde2AC/4S-2048x1228/v1/t300x182.jpg" style=3D"display: block; border: n=
one; width: 290px;" width=3D"290" alt=3D"Family Zoo Memberships" title=3D"F=
amily Zoo Memberships" class=3D"100"></a></td> </tr> <tr> <td align=3D"left=
" style=3D"font-size: 16px; color: #333333; font-weight: normal; padding: 2=
0px 0 0 0;"colspan=3D"2">Family Zoo Memberships</td> </tr> <tr> <td align=
=3D"left" style=3D"font-size: 13px; color: #999999; font-weight: normal; pa=
dding: 5px 0 0 0;"colspan=3D"2">Elmwood Park Zoo</td> </tr> <tr> <td style=
=3D"padding: 3px 0 0 0;" align=3D"left"> <span style=3D"padding: 0 5px 0 0;=
 padding-right: 5px; font-size: 16px; line-height: 20px; text-decoration: l=
ine-through; color:#848484; font-weight: 100;"> $129.95 </span> <span style=
=3D"font-size: 16px; line-height: 20px; color:#53A318; font-weight: 300; te=
xt-decoration: none; font-weight: bold;"> $59 </span> </td> </tr> </table> =
</td> </tr> </table> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"bo=
rder: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, sans-seri=
f; color:#000000; font-weight: normal; text-align: left; width:290px; backg=
round: #ffffff;" class=3D"container" align=3D'right'> <tr> <td style=3D"pad=
ding: 20px 0 0 0;" align=3D'right'> <table cellpadding=3D"0" cellspacing=3D=
"0" style=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans', A=
rial, sans-serif; color:#000000; font-weight: normal; text-align: left; wid=
th: 100%;"> <tr> <td valign=3D"top" colspan=3D"2"><a href=3D"https://www.gr=
oupon.com/deals/gl-bre-presents-a-country-christmas-home-free-at-keswick-th=
eatre-1?p=3D7&utm_source=3Dchannel_occasions_area51&utm_medium=3Demail&user=
=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D=
20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dim=
age&d=3Ddeal-page&utm_campaign=3Dd76ff3d1-4581-4e7a-9e69-9fbfac744940_0_201=
61112_treatment1" target=3D"_blank" style=3D"color:#0185C6; text-decoration=
:none;"><img src=3D"https://img.grouponcdn.com/deal/4MGL65YqiHtpnqPYx8xkR6o=
nYpi3/4M-1502x901/v1/t300x182.jpg" style=3D"display: block; border: none; w=
idth: 290px;" width=3D"290" alt=3D"Christmas Concert: Home Free" title=3D"C=
hristmas Concert: Home Free" class=3D"100"></a></td> </tr> <tr> <td align=
=3D"left" style=3D"font-size: 16px; color: #333333; font-weight: normal; pa=
dding: 20px 0 0 0;"colspan=3D"2">Christmas Concert: Home Free</td> </tr> <t=
r> <td align=3D"left" style=3D"font-size: 13px; color: #999999; font-weight=
: normal; padding: 5px 0 0 0;"colspan=3D"2">Home Free: A Country Christmas<=
/td> </tr> <tr> <td align=3D"left" style=3D"font-size: 13px; color: #999999=
; font-weight: normal;" colspan=3D"2">Keswick Theatre</td> </tr> <tr> <td s=
tyle=3D"padding: 3px 0 0 0;" align=3D"left"> <span style=3D"padding: 0 5px =
0 0; padding-right: 5px; font-size: 16px; line-height: 20px; text-decoratio=
n: line-through; color:#848484; font-weight: 100;"> $50.50 </span> <span st=
yle=3D"font-size: 16px; line-height: 20px; color:#53A318; font-weight: 300;=
 text-decoration: none; font-weight: bold;"> $20 </span> </td> </tr> </tabl=
e> </td> </tr> </table> </td> </tr> <tr> <td align=3D"left"> <table cellpad=
ding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing: 0; fo=
nt-family: 'Open Sans', Arial, sans-serif; color:#000000; font-weight: norm=
al; text-align: left; width:290px; background: #ffffff;" class=3D"container=
" align=3D'left'> <tr> <td style=3D"padding: 20px 0 0 0;" align=3D'left'> <=
table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-s=
pacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#000000; font=
-weight: normal; text-align: left; width: 100%;"> <tr> <td valign=3D"top" c=
olspan=3D"2"><a href=3D"https://www.groupon.com/deals/gl-the-nutcracker-145=
?p=3D8&utm_source=3Dchannel_occasions_area51&utm_medium=3Demail&user=3Dd8bf=
d7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D2016111=
2&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=
=3Ddeal-page&utm_campaign=3Dd76ff3d1-4581-4e7a-9e69-9fbfac744940_0_20161112=
_treatment1" target=3D"_blank" style=3D"color:#0185C6; text-decoration:none=
;"><img src=3D"https://img.grouponcdn.com/deal/2kbjaaPtntfw6NsN8WtE19mB9Hn3=
/2k-2048x1229/v1/t300x182.jpg" style=3D"display: block; border: none; width=
: 290px;" width=3D"290" alt=3D"Ballet: The Nutcracker" title=3D"Ballet: The=
 Nutcracker" class=3D"100"></a></td> </tr> <tr> <td align=3D"left" style=3D=
"font-size: 16px; color: #333333; font-weight: normal; padding: 20px 0 0 0;=
"colspan=3D"2">Ballet: The Nutcracker</td> </tr> <tr> <td align=3D"left" st=
yle=3D"font-size: 13px; color: #999999; font-weight: normal; padding: 5px 0=
 0 0;"colspan=3D"2">"The Nutcracker"</td> </tr> <tr> <td align=3D"left" sty=
le=3D"font-size: 13px; color: #999999; font-weight: normal;" colspan=3D"2">=
Central Bucks South High School Auditorium</td> </tr> <tr> <td style=3D"pad=
ding: 3px 0 0 0;" align=3D"left"> <span style=3D"padding: 0 5px 0 0; paddin=
g-right: 5px; font-size: 16px; line-height: 20px; text-decoration: line-thr=
ough; color:#848484; font-weight: 100;"> $35 </span> <span style=3D"font-si=
ze: 16px; line-height: 20px; color:#53A318; font-weight: 300; text-decorati=
on: none; font-weight: bold;"> $20 </span> </td> </tr> </table> </td> </tr>=
 </table> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 non=
e; border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#0=
00000; font-weight: normal; text-align: left; width:290px; background: #fff=
fff;" class=3D"container" align=3D'right'> <tr> <td style=3D"padding: 20px =
0 0 0;" align=3D'right'> <table cellpadding=3D"0" cellspacing=3D"0" style=
=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, san=
s-serif; color:#000000; font-weight: normal; text-align: left; width: 100%;=
"> <tr> <td valign=3D"top" colspan=3D"2"><a href=3D"https://www.groupon.com=
/deals/gl-the-west-chester-craft-beer-restaurant-stroll-at-multiple-locatio=
ns-on-11-19?p=3D9&utm_source=3Dchannel_occasions_area51&utm_medium=3Demail&=
user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&dat=
e=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=
=3Dimage&d=3Ddeal-page&utm_campaign=3Dd76ff3d1-4581-4e7a-9e69-9fbfac744940_=
0_20161112_treatment1" target=3D"_blank" style=3D"color:#0185C6; text-decor=
ation:none;"><img src=3D"https://img.grouponcdn.com/iam/gVgPgehCV3M7LLwhEZg=
g/EV-2542x1526/v1/t300x182.jpg" style=3D"display: block; border: none; widt=
h: 290px;" width=3D"290" alt=3D"Craft Beer & Restaurant Stroll" title=3D"Cr=
aft Beer & Restaurant Stroll" class=3D"100"></a></td> </tr> <tr> <td align=
=3D"left" style=3D"font-size: 16px; color: #333333; font-weight: normal; pa=
dding: 20px 0 0 0;"colspan=3D"2">Craft Beer & Restaurant Stroll</td> </tr> =
<tr> <td align=3D"left" style=3D"font-size: 13px; color: #999999; font-weig=
ht: normal; padding: 5px 0 0 0;"colspan=3D"2">The West Chester Craft Beer &=
 Resta</td> </tr> <tr> <td align=3D"left" style=3D"font-size: 13px; color: =
#999999; font-weight: normal;" colspan=3D"2">Multiple Locations</td> </tr> =
<tr> <td style=3D"padding: 3px 0 0 0;" align=3D"left"> <span style=3D"paddi=
ng: 0 5px 0 0; padding-right: 5px; font-size: 16px; line-height: 20px; text=
-decoration: line-through; color:#848484; font-weight: 100;"> $17 </span> <=
span style=3D"font-size: 16px; line-height: 20px; color:#53A318; font-weigh=
t: 300; text-decoration: none; font-weight: bold;"> $9 </span> </td> </tr> =
</table> </td> </tr> </table> </td> </tr> </table> </td> </tr> </table> <ta=
ble cellpadding=3D"0" cellspacing=3D"0" style=3D"width: 600px; min-width:60=
0px;" width=3D"600" align=3D"center" class=3D"container"> <tr> <td align=3D=
"center" style=3D"width:600px; min-width:600px;" width=3D"600" class=3D"con=
tainer"> <table cellpadding=3D"0" cellspacing=3D"0" style =3D "border: 0 no=
ne; border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#=
000000; font-weight: normal; text-align: left; width: 600px;" align=3D "cen=
ter" class=3D"container"> <tr> <td align=3D"left"> <table cellpadding=3D"0"=
 cellspacing=3D"0" style=3D"border: 0 none; border-spacing: 0; font-family:=
 'Open Sans', Arial, sans-serif; color:#000000; font-weight: normal; text-a=
lign: left; width:290px; background: #ffffff;" class=3D"container" align=3D=
'left'> <tr> <td style=3D"padding: 20px 0 0 0;" align=3D'left'> <table cell=
padding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing: 0;=
 font-family: 'Open Sans', Arial, sans-serif; color:#000000; font-weight: n=
ormal; text-align: left; width: 100%;"> <tr> <td valign=3D"top" colspan=3D"=
2"><a href=3D"https://www.groupon.com/deals/whisper-creek-golf-club?p=3D11&=
utm_source=3Dchannel_occasions_area51&utm_medium=3Demail&user=3Dd8bfd7c8bf0=
3cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3D=
f79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=3Ddeal-p=
age&utm_campaign=3Dd76ff3d1-4581-4e7a-9e69-9fbfac744940_0_20161112_treatmen=
t1" target=3D"_blank" style=3D"color:#0185C6; text-decoration:none;"><img s=
rc=3D"https://img.grouponcdn.com/deal/3LHLjvahKFmif4jdH8icvxoYB2i1/3L-700x4=
20/v1/t300x182.jpg" style=3D"display: block; border: none; width: 290px;" w=
idth=3D"290" alt=3D"Whisper Creek Golf Club" title=3D"Whisper Creek Golf Cl=
ub" class=3D"100"></a></td> </tr> <tr> <td align=3D"left" style=3D"font-siz=
e: 16px; color: #333333; font-weight: normal; padding: 20px 0 0 0;"colspan=
=3D"2">Whisper Creek Golf Club</td> </tr> <tr> <td align=3D"left" style=3D"=
font-size: 13px; color: #999999; font-weight: normal; padding: 5px 0 0 0;"c=
olspan=3D"2">Whisper Creek Golf Club</td> </tr> <tr> <td align=3D"left" sty=
le=3D"font-size: 13px; color: #999999; font-weight: normal;" colspan=3D"2">=
Huntley </td> </tr> <tr> <td style=3D"padding: 3px 0 0 0;" align=3D"left"> =
<span style=3D"padding: 0 5px 0 0; padding-right: 5px; font-size: 16px; lin=
e-height: 20px; text-decoration: line-through; color:#848484; font-weight: =
100;"> $159 </span> <span style=3D"font-size: 16px; line-height: 20px; font=
-weight: bold; text-decoration: none; color: #e35205;"> $53 </span> </td> <=
/tr> <tr> <td colspan=3D"2" style=3D"font-size: 14px; text-decoration: none=
; color: #e35205; font-weight: normal;">Sale Ends 11/12</td> </tr> </table>=
 </td> </tr> </table> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"b=
order: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, sans-ser=
if; color:#000000; font-weight: normal; text-align: left; width:290px; back=
ground: #ffffff;" class=3D"container" align=3D'right'> <tr> <td style=3D"pa=
dding: 20px 0 0 0;" align=3D'right'> <table cellpadding=3D"0" cellspacing=
=3D"0" style=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans'=
, Arial, sans-serif; color:#000000; font-weight: normal; text-align: left; =
width: 100%;"> <tr> <td valign=3D"top" colspan=3D"2"><a href=3D"https://www=
.groupon.com/deals/fine-artisan-events-4?p=3D12&utm_source=3Dchannel_occasi=
ons_area51&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806f=
bf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-002=
59069d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=3Ddeal-page&utm_campaign=3Dd76ff3d1=
-4581-4e7a-9e69-9fbfac744940_0_20161112_treatment1" target=3D"_blank" style=
=3D"color:#0185C6; text-decoration:none;"><img src=3D"https://img.grouponcd=
n.com/deal/cXywHRdUH7fKqhrLd594g9QBKnB/cX-904x543/v1/t300x182.jpg" style=3D=
"display: block; border: none; width: 290px;" width=3D"290" alt=3D"Artisan =
Chocolate Show" title=3D"Artisan Chocolate Show" class=3D"100"></a></td> </=
tr> <tr> <td align=3D"left" style=3D"font-size: 16px; color: #333333; font-=
weight: normal; padding: 20px 0 0 0;"colspan=3D"2">Artisan Chocolate Show</=
td> </tr> <tr> <td align=3D"left" style=3D"font-size: 13px; color: #999999;=
 font-weight: normal; padding: 5px 0 0 0;"colspan=3D"2">Fine Artisan Events=
</td> </tr> <tr> <td align=3D"left" style=3D"font-size: 13px; color: #99999=
9; font-weight: normal;" colspan=3D"2">West Loop</td> </tr> <tr> <td style=
=3D"padding: 3px 0 0 0;" align=3D"left"> <span style=3D"padding: 0 5px 0 0;=
 padding-right: 5px; font-size: 16px; line-height: 20px; text-decoration: l=
ine-through; color:#848484; font-weight: 100;"> $40 </span> <span style=3D"=
font-size: 16px; line-height: 20px; color:#53A318; font-weight: 300; text-d=
ecoration: none; font-weight: bold;"> $29 </span> </td> </tr> </table> </td=
> </tr> </table> </td> </tr> <tr> <td align=3D"left"> <table cellpadding=3D=
"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing: 0; font-fami=
ly: 'Open Sans', Arial, sans-serif; color:#000000; font-weight: normal; tex=
t-align: left; width:290px; background: #ffffff;" class=3D"container" align=
=3D'left'> <tr> <td style=3D"padding: 20px 0 0 0;" align=3D'left'> <table c=
ellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:=
 0; font-family: 'Open Sans', Arial, sans-serif; color:#000000; font-weight=
: normal; text-align: left; width: 100%;"> <tr> <td valign=3D"top" colspan=
=3D"2"><a href=3D"https://www.groupon.com/deals/highland-park-field-house-2=
-4?p=3D13&utm_source=3Dchannel_occasions_area51&utm_medium=3Demail&user=3Dd=
8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D2016=
1112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dimage&=
d=3Ddeal-page&utm_campaign=3Dd76ff3d1-4581-4e7a-9e69-9fbfac744940_0_2016111=
2_treatment1" target=3D"_blank" style=3D"color:#0185C6; text-decoration:non=
e;"><img src=3D"https://img.grouponcdn.com/deal/jKG2P84rQuLeNdCb7TPY/uM-128=
0x720/v1/t300x182.jpg" style=3D"display: block; border: none; width: 290px;=
" width=3D"290" alt=3D"Driving-Range Practice" title=3D"Driving-Range Pract=
ice" class=3D"100"></a></td> </tr> <tr> <td align=3D"left" style=3D"font-si=
ze: 16px; color: #333333; font-weight: normal; padding: 20px 0 0 0;"colspan=
=3D"2">Driving-Range Practice</td> </tr> <tr> <td align=3D"left" style=3D"f=
ont-size: 13px; color: #999999; font-weight: normal; padding: 5px 0 0 0;"co=
lspan=3D"2">Highland Park Field House</td> </tr> <tr> <td style=3D"padding:=
 3px 0 0 0;" align=3D"left"> <span style=3D"padding: 0 5px 0 0; padding-rig=
ht: 5px; font-size: 16px; line-height: 20px; text-decoration: line-through;=
 color:#848484; font-weight: 100;"> $20 </span> <span style=3D"font-size: 1=
6px; line-height: 20px; color:#53A318; font-weight: 300; text-decoration: n=
one; font-weight: bold;"> $10 </span> </td> </tr> </table> </td> </tr> </ta=
ble> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; bo=
rder-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#000000=
; font-weight: normal; text-align: left; width:290px; background: #ffffff;"=
 class=3D"container" align=3D'right'> <tr> <td style=3D"padding: 20px 0 0 0=
;" align=3D'right'> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"bor=
der: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif=
; color:#000000; font-weight: normal; text-align: left; width: 100%;"> <tr>=
 <td valign=3D"top" colspan=3D"2"><a href=3D"https://www.groupon.com/deals/=
blue-nose-brewery?p=3D14&utm_source=3Dchannel_occasions_area51&utm_medium=
=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561e=
d8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=
=3Dbody&c=3Dimage&d=3Ddeal-page&utm_campaign=3Dd76ff3d1-4581-4e7a-9e69-9fbf=
ac744940_0_20161112_treatment1" target=3D"_blank" style=3D"color:#0185C6; t=
ext-decoration:none;"><img src=3D"https://img.grouponcdn.com/deal/kDvFfi3zu=
M2ggZ8Prvro/A4-3264x1958/v1/t300x182.jpg" style=3D"display: block; border: =
none; width: 290px;" width=3D"290" alt=3D"Brewery Tour, Flights & Crowlers"=
 title=3D"Brewery Tour, Flights & Crowlers" class=3D"100"></a></td> </tr> <=
tr> <td align=3D"left" style=3D"font-size: 16px; color: #333333; font-weigh=
t: normal; padding: 20px 0 0 0;"colspan=3D"2">Brewery Tour, Flights & Crowl=
ers</td> </tr> <tr> <td align=3D"left" style=3D"font-size: 13px; color: #99=
9999; font-weight: normal; padding: 5px 0 0 0;"colspan=3D"2">Blue Nose Brew=
ery</td> </tr> <tr> <td align=3D"left" style=3D"font-size: 13px; color: #99=
9999; font-weight: normal;" colspan=3D"2">Hodgkins</td> </tr> <tr> <td styl=
e=3D"padding: 3px 0 0 0;" align=3D"left"> <span style=3D"padding: 0 5px 0 0=
; padding-right: 5px; font-size: 16px; line-height: 20px; text-decoration: =
line-through; color:#848484; font-weight: 100;"> $54 </span> <span style=3D=
"font-size: 16px; line-height: 20px; font-weight: bold; text-decoration: no=
ne; color: #e35205;"> $26 </span> </td> </tr> <tr> <td colspan=3D"2" style=
=3D"font-size: 14px; text-decoration: none; color: #e35205; font-weight: no=
rmal;">Sale Ends 11/12</td> </tr> </table> </td> </tr> </table> </td> </tr>=
 <tr> <td align=3D"left"> <table cellpadding=3D"0" cellspacing=3D"0" style=
=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, san=
s-serif; color:#000000; font-weight: normal; text-align: left; width:290px;=
 background: #ffffff;" class=3D"container" align=3D'left'> <tr> <td style=
=3D"padding: 20px 0 0 0;" align=3D'left'> <table cellpadding=3D"0" cellspac=
ing=3D"0" style=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sa=
ns', Arial, sans-serif; color:#000000; font-weight: normal; text-align: lef=
t; width: 100%;"> <tr> <td valign=3D"top" colspan=3D"2"><a href=3D"https://=
www.groupon.com/deals/gl-official-fan-package-368?p=3D15&utm_source=3Dchann=
el_occasions_area51&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee=
1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2=
-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=3Ddeal-page&utm_campaign=
=3Dd76ff3d1-4581-4e7a-9e69-9fbfac744940_0_20161112_treatment1" target=3D"_b=
lank" style=3D"color:#0185C6; text-decoration:none;"><img src=3D"https://im=
g.grouponcdn.com/deal/c6tvkqnKubggPhPve7Bk/eP-2048x1229/v1/t300x182.jpg" st=
yle=3D"display: block; border: none; width: 290px;" width=3D"290" alt=3D"Ch=
icago Bulls Games" title=3D"Chicago Bulls Games" class=3D"100"></a></td> </=
tr> <tr> <td align=3D"left" style=3D"font-size: 16px; color: #333333; font-=
weight: normal; padding: 20px 0 0 0;"colspan=3D"2">Chicago Bulls Games</td>=
 </tr> <tr> <td align=3D"left" style=3D"font-size: 13px; color: #999999; fo=
nt-weight: normal; padding: 5px 0 0 0;"colspan=3D"2">Official Fan Package</=
td> </tr> <tr> <td align=3D"left" style=3D"font-size: 13px; color: #999999;=
 font-weight: normal;" colspan=3D"2">United Center</td> </tr> <tr> <td styl=
e=3D"padding: 3px 0 0 0;" align=3D"left"> <span style=3D"padding: 0 5px 0 0=
; padding-right: 5px; font-size: 16px; line-height: 20px; text-decoration: =
line-through; color:#848484; font-weight: 100;"> $181 </span> <span style=
=3D"font-size: 16px; line-height: 20px; color:#53A318; font-weight: 300; te=
xt-decoration: none; font-weight: bold;"> $69 </span> </td> </tr> </table> =
</td> </tr> </table> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"bo=
rder: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, sans-seri=
f; color:#000000; font-weight: normal; text-align: left; width:290px; backg=
round: #ffffff;" class=3D"container" align=3D'right'> <tr> <td style=3D"pad=
ding: 20px 0 0 0;" align=3D'right'> <table cellpadding=3D"0" cellspacing=3D=
"0" style=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans', A=
rial, sans-serif; color:#000000; font-weight: normal; text-align: left; wid=
th: 100%;"> <tr> <td valign=3D"top" colspan=3D"2"><a href=3D"https://www.gr=
oupon.com/deals/aerial-adventures-lake-geneva-9?p=3D16&utm_source=3Dchannel=
_occasions_area51&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1e=
d8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-8=
2c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=3Ddeal-page&utm_campaign=3Dd=
76ff3d1-4581-4e7a-9e69-9fbfac744940_0_20161112_treatment1" target=3D"_blank=
" style=3D"color:#0185C6; text-decoration:none;"><img src=3D"https://img.gr=
ouponcdn.com/deal/bP3JrsTfgR3WEEHFdfP9vs/IMAGE_Aerial-Adventures-Lake-Genev=
a-2859x1736/v1/t300x182.jpg" style=3D"display: block; border: none; width: =
290px;" width=3D"290" alt=3D"Adventure Package with Ziplining" title=3D"Adv=
enture Package with Ziplining" class=3D"100"></a></td> </tr> <tr> <td align=
=3D"left" style=3D"font-size: 16px; color: #333333; font-weight: normal; pa=
dding: 20px 0 0 0;"colspan=3D"2">Adventure Package with Ziplining</td> </tr=
> <tr> <td align=3D"left" style=3D"font-size: 13px; color: #999999; font-we=
ight: normal; padding: 5px 0 0 0;"colspan=3D"2">Aerial Adventures Lake Gene=
va</td> </tr> <tr> <td align=3D"left" style=3D"font-size: 13px; color: #999=
999; font-weight: normal;" colspan=3D"2">Lake Geneva</td> </tr> <tr> <td st=
yle=3D"padding: 3px 0 0 0;" align=3D"left"> <span style=3D"padding: 0 5px 0=
 0; padding-right: 5px; font-size: 16px; line-height: 20px; text-decoration=
: line-through; color:#848484; font-weight: 100;"> $69 </span> <span style=
=3D"font-size: 16px; line-height: 20px; color:#53A318; font-weight: 300; te=
xt-decoration: none; font-weight: bold;"> $49 </span> </td> </tr> </table> =
</td> </tr> </table> </td> </tr> <tr> <td align=3D"left"> <table cellpaddin=
g=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing: 0; font-=
family: 'Open Sans', Arial, sans-serif; color:#000000; font-weight: normal;=
 text-align: left; width:290px; background: #ffffff;" class=3D"container" a=
lign=3D'left'> <tr> <td style=3D"padding: 20px 0 0 0;" align=3D'left'> <tab=
le cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spac=
ing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#000000; font-we=
ight: normal; text-align: left; width: 100%;"> <tr> <td valign=3D"top" cols=
pan=3D"2"><a href=3D"https://www.groupon.com/deals/chicago-helicopter-exper=
ience-2?p=3D17&utm_source=3Dchannel_occasions_area51&utm_medium=3Demail&use=
r=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=
=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=
=3Dimage&d=3Ddeal-page&utm_campaign=3Dd76ff3d1-4581-4e7a-9e69-9fbfac744940_=
0_20161112_treatment1" target=3D"_blank" style=3D"color:#0185C6; text-decor=
ation:none;"><img src=3D"https://img.grouponcdn.com/deal/92QdU1CxwsXheTpvWZ=
Ab/e4-700x420/v1/t300x182.jpg" style=3D"display: block; border: none; width=
: 290px;" width=3D"290" alt=3D"Helicopter Tour for Two" title=3D"Helicopter=
 Tour for Two" class=3D"100"></a></td> </tr> <tr> <td align=3D"left" style=
=3D"font-size: 16px; color: #333333; font-weight: normal; padding: 20px 0 0=
 0;"colspan=3D"2">Helicopter Tour for Two</td> </tr> <tr> <td align=3D"left=
" style=3D"font-size: 13px; color: #999999; font-weight: normal; padding: 5=
px 0 0 0;"colspan=3D"2">Chicago Helicopter Experience</td> </tr> <tr> <td a=
lign=3D"left" style=3D"font-size: 13px; color: #999999; font-weight: normal=
;" colspan=3D"2">South Side</td> </tr> <tr> <td style=3D"padding: 3px 0 0 0=
;" align=3D"left"> <span style=3D"padding: 0 5px 0 0; padding-right: 5px; f=
ont-size: 16px; line-height: 20px; text-decoration: line-through; color:#84=
8484; font-weight: 100;"> $296 </span> <span style=3D"font-size: 16px; line=
-height: 20px; color:#53A318; font-weight: 300; text-decoration: none; font=
-weight: bold;"> $275 </span> </td> </tr> </table> </td> </tr> </table> <ta=
ble cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spa=
cing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#000000; font-w=
eight: normal; text-align: left; width:290px; background: #ffffff;" class=
=3D"container" align=3D'right'> <tr> <td style=3D"padding: 20px 0 0 0;" ali=
gn=3D'right'> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0=
 none; border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; colo=
r:#000000; font-weight: normal; text-align: left; width: 100%;"> <tr> <td v=
align=3D"top" colspan=3D"2"><a href=3D"https://www.groupon.com/deals/the-mu=
rder-mystery-co-26-chicago?p=3D18&utm_source=3Dchannel_occasions_area51&utm=
_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf=
386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=
=3DUS&s=3Dbody&c=3Dimage&d=3Ddeal-page&utm_campaign=3Dd76ff3d1-4581-4e7a-9e=
69-9fbfac744940_0_20161112_treatment1" target=3D"_blank" style=3D"color:#01=
85C6; text-decoration:none;"><img src=3D"https://img.grouponcdn.com/deal/2P=
muk6aeAW35sym7DBU6u41KFpjk/2P-700x420/v1/t300x182.jpg" style=3D"display: bl=
ock; border: none; width: 290px;" width=3D"290" alt=3D"Murder-Mystery Dinne=
r" title=3D"Murder-Mystery Dinner" class=3D"100"></a></td> </tr> <tr> <td a=
lign=3D"left" style=3D"font-size: 16px; color: #333333; font-weight: normal=
; padding: 20px 0 0 0;"colspan=3D"2">Murder-Mystery Dinner</td> </tr> <tr> =
<td align=3D"left" style=3D"font-size: 13px; color: #999999; font-weight: n=
ormal; padding: 5px 0 0 0;"colspan=3D"2">The Murder Mystery Co.</td> </tr> =
<tr> <td align=3D"left" style=3D"font-size: 13px; color: #999999; font-weig=
ht: normal;" colspan=3D"2">Chicago</td> </tr> <tr> <td style=3D"padding: 3p=
x 0 0 0;" align=3D"left"> <span style=3D"padding: 0 5px 0 0; padding-right:=
 5px; font-size: 16px; line-height: 20px; text-decoration: line-through; co=
lor:#848484; font-weight: 100;"> $60 </span> <span style=3D"font-size: 16px=
; line-height: 20px; font-weight: bold; text-decoration: none; color: #e352=
05;"> $27 </span> </td> </tr> <tr> <td colspan=3D"2" style=3D"font-size: 14=
px; text-decoration: none; color: #e35205; font-weight: normal;">Sale Ends =
11/12</td> </tr> </table> </td> </tr> </table> </td> </tr> </table> </td> <=
/tr> </table> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0=
 none; border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; colo=
r:#000000; font-weight: normal; text-align: left; width: 100%; background-c=
olor: #ffffff;" align=3D"center"> <tr> <td style=3D"padding: 0px; display:n=
one; font-size:0; max-height:0; line-height:0; mso-hide: all;" class=3D"mob=
ile-banner"><a href=3D"https://www.groupon.com/deals/studio-movie-grill-119=
?p=3D20&utm_source=3Dchannel_occasions_area51&utm_medium=3Demail&user=3Dd8b=
fd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D201611=
12&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbanner&d=
=3Ddynamic-banner-3&utm_campaign=3Dd76ff3d1-4581-4e7a-9e69-9fbfac744940_0_2=
0161112_treatment1" style=3D"color:#0185C6; text-decoration:none;" target=
=3D"_blank"> <img src=3D"https://img.grouponcdn.com/deal/47twizEzz5RQNfFsnF=
G9B33vUJw3/47-460x120" style=3D"padding:0px; display:none; font-size:0; max=
-height:0; line-height:0; mso-hide: all;" class=3D"mobile-banner-img" alt=
=3D"Studio Movie Grill" /></a> </td> </tr> </table> <table cellpadding=3D"0=
" cellspacing=3D"0" style=3D"border: 0 none; border-spacing: 0; font-family=
: 'Open Sans', Arial, sans-serif; color:#000000; font-weight: normal; text-=
align: left; width: 100%; min-width:290px; background-color: #ffffff;" alig=
n=3D"center" class=3D"display-off"> <tr> <td align=3D"center" style=3D"padd=
ing: 20px 0 0 0; min-width:290px;"><a href=3D"https://www.groupon.com/deals=
/studio-movie-grill-119?p=3D20&utm_source=3Dchannel_occasions_area51&utm_me=
dium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386=
561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DU=
S&s=3Dbody&c=3Dbanner&d=3Ddynamic-banner-3&utm_campaign=3Dd76ff3d1-4581-4e7=
a-9e69-9fbfac744940_0_20161112_treatment1" style=3D"color:#0185C6; text-dec=
oration:none;" target=3D"_blank"> <img src=3D"https://img.grouponcdn.com/de=
al/2ZCqnPPKDyiDH6umkiz3wJLB9WcA/2Z-600x100" style=3D"display: block; border=
: none; min-width:290px;" alt=3D"Studio Movie Grill" /></a> </td> </tr> </t=
able> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; b=
order-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#00000=
0; font-weight: normal; text-align: left; width:600px;" class=3D"container"=
 align=3D"center"> <tr> <td style=3D"font-size: 22px; color: #333333; font-=
weight: normal; padding: 20px 0 0 0;" align=3D'left'>Check Out More Top Thi=
ngs To Do</td> </tr> </table> <table cellpadding=3D"0" cellspacing=3D"0" st=
yle=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, =
sans-serif; color:#000000; font-weight: normal; text-align: left; width: 10=
0%; min-width:600px;" width=3D"100%" class=3D"container" align=3D"center"> =
<tr> <td valign=3D"top" align=3D"left" style=3D"padding:10px 0 0 0;"> <tabl=
e cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spaci=
ng: 0; font-family: 'Open Sans', Arial, sans-serif; color:#000000; font-wei=
ght: normal; text-align: left; width: 100%;" width=3D"100%" class=3D"contai=
ner" align=3D"center"> <tr> <td valign=3D"top" align=3D"left"> <table cellp=
adding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing: 0; =
font-family: 'Open Sans', Arial, sans-serif; color:#000000; font-weight: no=
rmal; text-align: left; width: 200px;" width=3D"200" class=3D"container" al=
ign=3D"left"> <tr> <td style=3D"padding:0px; display:none; font-size:0; max=
-height:0; line-height:0; mso-hide: all;" class=3D"mobile-banner-img"> <a h=
ref=3D"https://www.groupon.com/browse/?category=3Dthings-to-do&category2=3D=
kids-activities&p=3D21&utm_source=3Dchannel_occasions_area51&utm_medium=3De=
mail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd=
2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbo=
dy&c=3Dbanner&d=3Ddeal-page&utm_campaign=3Dd76ff3d1-4581-4e7a-9e69-9fbfac74=
4940_0_20161112_treatment1" target=3D"_blank" style=3D"color:#0185C6; text-=
decoration:none;"><img src=3D"https://img.grouponcdn.com/deal/3A79jWe4JMH69=
rrfrrknaWeJXPkF/3A-190x190" style=3D"padding:0px; display:none; font-size:0=
; max-height:0; line-height:0; mso-hide: all;" class=3D"mobile-banner-img" =
alt=3D"Family Fun" /></a> </td> </tr> <tr> <td style=3D"width:200px;" class=
=3D"display-off"> <a href=3D"https://www.groupon.com/browse/?category=3Dthi=
ngs-to-do&category2=3Dkids-activities&p=3D21&utm_source=3Dchannel_occasions=
_area51&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5=
c2acac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-002590=
69d5fe&CID=3DUS&s=3Dbody&c=3Dbanner&d=3Ddeal-page&utm_campaign=3Dd76ff3d1-4=
581-4e7a-9e69-9fbfac744940_0_20161112_treatment1" target=3D"_blank" style=
=3D"color:#0185C6; text-decoration:none;"><img src=3D"https://img.grouponcd=
n.com/deal/3A79jWe4JMH69rrfrrknaWeJXPkF/3A-190x190" style=3D"display: block=
; border: none; width:200px;" width=3D"200" class=3D"100" alt=3D"Family Fun=
" /></a> </td> </tr> </table> <!--[if (gte mso 9)|(IE)]> </td> <td> <![endi=
f]--> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; b=
order-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#00000=
0; font-weight: normal; text-align: left; width: 200px;" width=3D"200" clas=
s=3D"container" align=3D"left"> <tr> <td style=3D"padding:0px; display:none=
; font-size:0; max-height:0; line-height:0; mso-hide: all;" class=3D"mobile=
-banner-img"> <a href=3D"https://www.groupon.com/occasion/things-to-do-for-=
dates-or-groups?p=3D22&utm_source=3Dchannel_occasions_area51&utm_medium=3De=
mail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd=
2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbo=
dy&c=3Dbanner&d=3Ddeal-page&utm_campaign=3Dd76ff3d1-4581-4e7a-9e69-9fbfac74=
4940_0_20161112_treatment1" target=3D"_blank" style=3D"color:#0185C6; text-=
decoration:none;"><img src=3D"https://img.grouponcdn.com/deal/3cJbdWj5z6vXQ=
NkVSwoPbvPLSuJM/3c-190x190" style=3D"padding:0px; display:none; font-size:0=
; max-height:0; line-height:0; mso-hide: all;" class=3D"mobile-banner-img" =
alt=3D"Date Night" /></a> </td> </tr> <tr> <td style=3D"width:200px;" class=
=3D"display-off"> <a href=3D"https://www.groupon.com/occasion/things-to-do-=
for-dates-or-groups?p=3D22&utm_source=3Dchannel_occasions_area51&utm_medium=
=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561e=
d8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=
=3Dbody&c=3Dbanner&d=3Ddeal-page&utm_campaign=3Dd76ff3d1-4581-4e7a-9e69-9fb=
fac744940_0_20161112_treatment1" target=3D"_blank" style=3D"color:#0185C6; =
text-decoration:none;"><img src=3D"https://img.grouponcdn.com/deal/3cJbdWj5=
z6vXQNkVSwoPbvPLSuJM/3c-190x190" style=3D"display: block; border: none; wid=
th:200px;" width=3D"200" class=3D"100" alt=3D"Date Night" /></a> </td> </tr=
> </table> <!--[if (gte mso 9)|(IE)]> </td> <td> <![endif]--> <table cellpa=
dding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing: 0; f=
ont-family: 'Open Sans', Arial, sans-serif; color:#000000; font-weight: nor=
mal; text-align: left; width: 200px;" width=3D"200" class=3D"container" ali=
gn=3D"left"> <tr> <td style=3D"padding:0px; display:none; font-size:0; max-=
height:0; line-height:0; mso-hide: all;" class=3D"mobile-banner-img"> <a hr=
ef=3D"https://www.groupon.com/occasion/things-to-do-for-29-and-under?p=3D23=
&utm_source=3Dchannel_occasions_area51&utm_medium=3Demail&user=3Dd8bfd7c8bf=
03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161112&uu=
=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbanner&d=3Dde=
al-page&utm_campaign=3Dd76ff3d1-4581-4e7a-9e69-9fbfac744940_0_20161112_trea=
tment1" target=3D"_blank" style=3D"color:#0185C6; text-decoration:none;"><i=
mg src=3D"https://img.grouponcdn.com/deal/2fp8tYNrfoGf2Y6pY9H9ZhfKZBd1/2f-1=
90x190" style=3D"padding:0px; display:none; font-size:0; max-height:0; line=
-height:0; mso-hide: all;" class=3D"mobile-banner-img" alt=3D"$29 and Under=
" /></a> </td> </tr> <tr> <td style=3D"width:200px;" class=3D"display-off">=
 <a href=3D"https://www.groupon.com/occasion/things-to-do-for-29-and-under?=
p=3D23&utm_source=3Dchannel_occasions_area51&utm_medium=3Demail&user=3Dd8bf=
d7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D2016111=
2&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbanner&d=
=3Ddeal-page&utm_campaign=3Dd76ff3d1-4581-4e7a-9e69-9fbfac744940_0_20161112=
_treatment1" target=3D"_blank" style=3D"color:#0185C6; text-decoration:none=
;"><img src=3D"https://img.grouponcdn.com/deal/2fp8tYNrfoGf2Y6pY9H9ZhfKZBd1=
/2f-190x190" style=3D"display: block; border: none; width:200px;" width=3D"=
200" class=3D"100" alt=3D"$29 and Under" /></a> </td> </tr> </table> </td> =
</tr> </table> </td> </tr> </table> </td> </tr> </table> </td> </tr> </tabl=
e> </td> </tr> </table> <table cellpadding=3D"0" cellspacing=3D"0" style=3D=
"border: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, sans-s=
erif; color:#000000; font-weight: normal; text-align: left; width: 100%; ba=
ckground: #f2f2f2;" align=3D"center" class=3D"container"> <tr> <td align=3D=
"center" style=3D"padding: 30px 0 0 0;"> <table cellpadding=3D"0" cellspaci=
ng=3D"0" style=3D"width: 600px; background: #f2f2f2;" align=3D"center" clas=
s=3D"container" width=3D"600"> <tr> <td style=3D"font-size: 16px; color: #8=
88888; line-height: 119%; padding: 10px 10px 10px 10px;" align=3D"center">N=
eed help? Have feedback? Feel free to <a href=3D"http://www.groupon.com/cus=
tomer_support?utm_source=3Dchannel_occasions_area51&utm_medium=3Demail&user=
=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D=
20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dfooter&c=3D=
link&d=3Dsupport&utm_campaign=3Dd76ff3d1-4581-4e7a-9e69-9fbfac744940_0_2016=
1112_treatment1" style=3D"color:#0185C6; text-decoration:none;" target=3D"_=
blank">contact us</a></td> </tr> <tr> <td style=3D"font-size: 10px; color: =
#999999; line-height: 120%; padding: 10px 10px 0 10px;" align=3D"center" cl=
ass=3D"mobile-font">Delivered by Groupon Inc. 600 W. Chicago Avenue, Suite =
400 Chicago, IL, 60654, USA</td> </tr> <tr> <td style=3D"font-size: 10px; c=
olor: #999999; line-height: 120%; padding: 0 10px 10px 10px;" align=3D"cent=
er" class=3D"mobile-font">You are receiving this email because kyle@kylefis=
her.com is signed up to receive Groupon communications. To adjust how often=
 you receive Groupon emails, including unsubscribing, <a href=3D"https://ww=
w.groupon.com/subscription_center/manage/consumer/f79c234c-2539-11e2-82c0-0=
0259069d5fe?cmplistId=3Dchannel:occasions&utm_source=3Dchannel_occasions_ar=
ea51&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2a=
cac134cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d=
5fe&CID=3DUS&s=3Dfooter&c=3Dlink&d=3Dunsubscribe&utm_campaign=3Dd76ff3d1-45=
81-4e7a-9e69-9fbfac744940_0_20161112_treatment1" style=3D"color:#0185C6; te=
xt-decoration:none;">click here</a></td> </tr> </table> </td> </tr> </table=
> <img src =3D "http://www.groupon.com/analytic/track.gif?p=3D2&utm_domain=
=3Dkylefisher.com&utm_campaign=3Dd76ff3d1-4581-4e7a-9e69-9fbfac744940_0_201=
61112_treatment1&deals=3D02777df3-32b8-49f9-a217-47d385dc5f67,a74c3827-2320=
-45f0-9e48-ddee9421f99a,c8a49923-291e-43f0-915a-e32770631efb,fb6aba04-3788-=
47ca-b7d6-5709eb63106e,93b6ad1f-5e68-40e5-92dd-2847fed1fa3b,f113e090-4141-4=
999-af8b-fb5d2844a148,50e83380-3525-4a46-9bea-a90339396ff1,6e80ad7e-1f40-40=
06-bd61-f4ded6e4a155,d5adecca-0720-4f09-9277-76aed0bb03c6,e3ae829f-7c77-4c5=
d-a809-9dca74b5094f,48f554d9-49e4-4dba-91bf-e45eae37b7a8,e1358882-a6e9-4eeb=
-afec-d3f0ef40792e,c88a2f9a-688a-4a26-8c40-07d038c8d97f,37bb931b-983a-4c49-=
bc68-2e839616062f,2d9a16ca-9e31-4689-ad9e-dd0f8e7e426b,bad5fcd2-57cd-f575-5=
c3f-0cba6bfa49e4&channel_deals=3Dnull&utm_source=3Dchannel_occasions_area51=
&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac1=
34cf386561ed8cd2&date=3D20161112&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&=
CID=3DUS" height=3D"1" width=3D"1" style=3D"display: none !important;" /> <=
/body> </html>

