From mailnull@amazon.com Sun Nov 13 05:57:00 2016
Received: from [72.21.217.134] (port=12352 helo=autoresponder.amazon.com)
	by ecbiz209.inmotionhosting.com with esmtps (TLSv1:DHE-RSA-AES256-SHA:256)
	(Exim 4.87)
	(envelope-from <mailnull@amazon.com>)
	id 1c5sT6-001SDR-Kg
	for kyle@kylefisher.com; Sun, 13 Nov 2016 05:57:00 -0500
Received: from email-autorespond-25001.iad12.amazon.com (localhost.localdomain [127.0.0.1])
	by autoresponder.amazon.com (8.13.8/8.13.8) with ESMTP id uADAv1gF031541
	for <kyle@kylefisher.com>; Sun, 13 Nov 2016 10:57:01 GMT
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=amazon.com;
	s=amazon201209; t=1479034621;
	bh=O7QLbwq3v9ixQECdVuz0KHLhJUQ0hUh0PsiWDkl1Wxw=;
	h=Date:Subject:In-Reply-To:To:From;
	b=Ke6e+rMrrvub9afoJDCXKPnu3s7dqSriP+wwdK0JiIrJKYMNrEDKLiCTNaR6uTGP/
	 QUgTcxZIJCiqmsN9RxvdbiS9XMXVU9iOwgN403JNIacj/RRmXjtUJE5nvp2RO2vX41
	 1C/ACHbJvet5GYGPkhDX8iSYLOjA2b3OEuV0Ono4=
Received: (from mailnull@localhost)
	by email-autorespond-25001.iad12.amazon.com (8.13.8/8.13.8/Submit) id uADAv1vF031539;
	Sun, 13 Nov 2016 10:57:01 GMT
Date: Sun, 13 Nov 2016 10:57:01 GMT
Subject: Re: Your Amazon.com Order
In-Reply-To: <E1c5sS6-001RNW-MB@ecbiz209.inmotionhosting.com>
Message-ID: <auto-reply-31506-1479034620@email-autorespond-25001.iad12.amazon.com>
To: kyle@kylefisher.com
X-Amazon-Auto-Reply: true
From: ship-confirm@amazon.com

Greetings from Amazon.com. 

We're sorry. You replied to a confirmation-only address that cannot
accept incoming e-mail. But that's OK--this automated response will
direct you to the right place at Amazon.com to answer your question or
help you make changes to your order.

To track recent shipments, get updated delivery estimates, or make
changes to any unshipped orders, just log in to Your Account at:

http://www.amazon.com/wheres-my-stuff 

If you need to return an item from your order, visit our online
Returns Center at:

http://www.amazon.com/returns/ 

For answers to questions about our shipping rates, returns policy, and
how to use any of our services, visit:

http://www.amazon.com/help/ 

We hope our online resources meet all your needs. If you've explored
the above links but find you still need to get in touch with us,
please use the e-mail form in our online Help department. 

Thanks for shopping at Amazon.com.


Sincerely, 
Amazon.com Customer Service
http://www.amazon.com/

P.S. You received this message because Amazon.com received
the following message from you:

Date: Sun, 13 Nov 2016 05:55:58 -0500
From: kyle@kylefisher.com
To: ship-confirm@amazon.com
Subject: Your email requires verification verify#NLpIMWUST8FKuF8fWvmam-1479034558)

The message you sent requires that you verify that you 
are a real live human being and not a spam source.


To complete this verification, simply reply to this message and leave
the subject line intact or click the link below:

http://www.kylefisher.com/cgi-sys/bxd.cgi?a=kyle@kylefisher.com&id=NLpIMWUST8FKuF8fWvmam-1479034558

The headers of the message sent from your address are shown below:

From 20161113105557d2b47a3a292148098ac5c2177050p0na@bounces.amazon.com Sun Nov 13 05:55:58 2016
Received: from a13-8.smtp-out.amazonses.com ([54.240.13.8]:50267)
	by ecbiz209.inmotionhosting.com with esmtp (Exim 4.87)
	(envelope-from <20161113105557d2b47a3a292148098ac5c2177050p0na@bounces.amazon.com>)
	id 1c5sS6-001RNJ-J2
	for kyle@kylefisher.com; Sun, 13 Nov 2016 05:55:58 -0500
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/simple;
	s=jvxsykglqiaiibkijmhy37vqxh4mzqr6; d=amazon.com; t=1479034558;
	h=From:Reply-To:To:Message-ID:Subject:MIME-Version:Content-Type:Date;
	bh=Cks9czY8m/pxK9j6T8vhDzBtAB3Ga7V73HzuToH5w5Y=;
	b=tPgZ8U8MzOAI6bdq1hc+8N39iUTxBtuADBTv3SJEcsNK08CiPrOE0wYR3NkRdJwa
	sb0tZ/an3zB8oepFrfhbxbINaD8fkF2kJwFU09w0mu97W4QouJaqPxkMga4lCZ1Qi9r
	60aIXaI0pGxXwEyL/QpmJMKAWZv3DzoV76dgAXBQ=
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/simple;
	s=6gbrjpgwjskckoa6a5zn6fwqkn67xbtw; d=amazonses.com; t=1479034558;
	h=From:Reply-To:To:Message-ID:Subject:MIME-Version:Content-Type:Date:Feedback-ID;
	bh=Cks9czY8m/pxK9j6T8vhDzBtAB3Ga7V73HzuToH5w5Y=;
	b=reg6ldE/gM58hMQg+uZVehZOxhEkuGn4retvZbzLrBy/wvPSOlJZJDD+/e7XST5L
	oBZqUzEFfsJIsddtPjsfOC9ipaHRY0dH+hfAlEXqoYii5wkx+A7XYNz53nn32MSQFXN
	je3S0tYJesGXTb6KypJlgBaW39ZlHyrVFcYxFZn4=
From: "Amazon.com" <ship-confirm@amazon.com>
Reply-To: ship-confirm@amazon.com
To: kyle@kylefisher.com
Message-ID: <010001585d545829-719379d5-a510-41ca-8e9b-4016e2c9cb53-000000@email.amazonses.com>
Subject: Your Amazon.com order of "iCasso - 2 in 1 Wooden..." has shipped!
MIME-Version: 1.0
Content-Type: multipart/alternative; 
	boundary="----=_Part_9636008_919664584.1479034558489"
X-AMAZON-MAIL-RELAY-TYPE: notification
Bounces-to: 20161113105557d2b47a3a292148098ac5c2177050p0na@bounces.amazon.com
X-AMAZON-METADATA: CA=C1YHUQ71QV9WK2-CU=A2SCO4VBODRW03-RI=ALAJWFVSEIPA7
X-Original-MessageID: <urn.rtn.msg.20161113105557d2b47a3a292148098ac5c2177050p0na@1479034558491.rtn-svc-na-1a-d284bab0.us-east-1.amazon.com>
Date: Sun, 13 Nov 2016 10:55:58 +0000
X-SES-Outgoing: 2016.11.13-54.240.13.8
Feedback-ID: 1.us-east-1.ZHcGJK6s+x+i9lRHKog4RW3tECwWIf1xzTYCZyUaiec=:AmazonSES


