From d8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2@bounce.r.groupon.com Fri Nov 11 11:15:51 2016
Received: from mta438s1.r.groupon.com ([50.115.211.138]:8300)
	by ecbiz209.inmotionhosting.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <d8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2@bounce.r.groupon.com>)
	id 1c5EUY-00354Q-Ma
	for kyle@kylefisher.com; Fri, 11 Nov 2016 11:15:51 -0500
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=r.groupon.com;
	s=s2048d20160829; t=1478880949;
	bh=zwlW9Ahm3NKKd4cjpKIoFXgcBoTO1VNxRCj44Ouq6qg=;
	h=Date:From:To:Message-ID:Subject:Content-Type;
	b=2a5Ige/vcI56GZ4yvz4qdeQQ8/RDYJKMzLpXCDpRxI+hmO/kVVIPxFerj96s/ExW1
	 1ZzKzPxwLZJzs6kxS2r4mkwdVptv4V2Jwx3jiO8elsNtDSdII5CMrB509+BBkj5IBS
	 81wBv5TVNgjQlG+Du9Fr+ddfxJ9io5mTsEBBwXotp/wbVSASrzs/U//ztiorTjQxnW
	 M1DD/RkNmc9w4sAQd3N/6JbPzfsiQ2UN4r4RNcxOHeO9ClhwuRGtbJYhjvSQ3lIqZL
	 lw/fiYclnpTIDla9CVEKtCDU9ZjUNxEXFrvoEW8eyWYMCbX9jjmpv6EEPS/KkfUOOY
	 MoWaenoIdbnaQ==
Date: Fri, 11 Nov 2016 16:15:49 +0000
From: Groupon Doorbusters <noreply@r.groupon.com>
To: kyle@kylefisher.com
Message-ID: <838811795.21832547.1478880949801.JavaMail.rocketman@push-dispatcher10>
Subject: Today's Doorbusters Going F>A>S>T
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
X-RM-UserHash: d8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2
X-RM-SendId: 96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111
X-RM-SenderScore: 0
X-RM-EmailName: crm_ils_goods_us_im_20161111_LowAffinity_Manual_10_Doorbusters
X-MSFBL: a3lsZUBreWxlZmlzaGVyLmNvbTpiYXRjaDo5NmZiYTViZS05YjdiLTQ5ZTYtODNlNy1iN2M3ZmI5Y2NlMzNfMF8yMDE2MTExMTpudWxsOlVT
List-Unsubscribe: <mailto:d8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2@unsub.r.groupon.com?subject=a3lsZUBreWxlZmlzaGVyLmNvbTpiYXRjaDo5NmZiYTViZS05YjdiLTQ5ZTYtODNlNy1iN2M3ZmI5Y2NlMzNfMF8yMDE2MTExMTpudWxsOlVT>
X-RPCampaign: Grouponcrmilsgoodsusim20161111LowAffinityManual10Doorbusters20161111
X-RPTags: crm_ils_goods_us_im_20161111_LowAffinity_Manual_10_Doorbusters
X-Recruiting: Interested in headers? Join us: www.groupon.com/techjobs/
List-Id: <crm_ils_goods_us_im_20161111_LowAffinity_Manual_10_Doorbusters_20161111.groupon>
X-Feedback-ID: r.groupon.com:crm_ils_goods_us_im_20161111_LowAffinity_Manual_10_Doorbusters:96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111:groupon

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.=
w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> <html xmlns=3D"http://www.w3=
.org/1999/xhtml" xmlns:v=3D"urn:schemas-microsoft-com:vml" xmlns:o=3D"urn:s=
chemas-microsoft-com:office:office"> <head> <meta http-equiv=3D"Content-Typ=
e" content=3D"text/html; charset=3Dutf-8" /> <title>Groupon</title> <style =
type=3D"text/css"> .ExternalClass * {line-height: 100%} /* override ios min=
imum font-size*/ div, p, a, li, td { -webkit-text-size-adjust:none; } img[c=
lass=3D"100"]{ width: 100% !important; min-width: 100% !important; max-widt=
h: 100% !important; } table { font-family: 'Open Sans', Arial, sans-serif !=
important; } @media only screen and (max-width: 580px) { table[class=3D"con=
tainer"]{ margin: 0 auto !important; width: 100% !important; min-width: 100=
% !important; } td[class=3D"container"]{ width: 100% !important; min-width:=
 100% !important; float: left !important; position: relative !important; pa=
dding: 0px !important; } td[class=3D"100"]{ width: 100% !important; min-wid=
th: 100% !important; height: auto !important; float: left !important; } td[=
class=3D"mobile-hdr-logo-center"]{ padding: 25px 0 10px 0 !important; } /* =
Image Classes */ img[class=3D"100"]{ width: 100% !important; min-width: 100=
% !important; max-width: 100% !important; } /* Col Sections */ *[class=3D"c=
ollapse-left"]{ width: 100% !important; float: left !important; position: r=
elative !important; padding: 20px 0 20px 0 !important; border-bottom: 1px s=
olid #cccccc !important; } *[class=3D"collapse-right"]{ width: 100% !import=
ant; float: left !important; position: relative !important; padding: 20px 0=
 20px 0 !important; border: none !important; } *[class=3D"collapse-left-rtl=
"]{ width: 100% !important; float: left !important; position: relative !imp=
ortant; padding: 20px 0 20px 0 !important; border: none !important; } *[cla=
ss=3D"collapse-right-rtl"]{ width: 100% !important; float: left !important;=
 position: relative !important; padding: 20px 0 20px 0 !important; border-b=
ottom: 1px solid #cccccc !important; } td[class=3D"collapse-trxn"]{ width: =
100% !important; float: left !important; position: relative !important; pad=
ding: 30px 0 0 0 !important; } td[class=3D"container-33"] { min-width: 33% =
!important; } td[class=3D"col-4-mobile"]{ width: 65% !important; } td[class=
=3D"mobile-container-padding"]{ padding: 20px 10px 20px 10px !important; } =
td.ga-mobile-pad { padding: 20px 0 15px 10px !important; } /* GA Partity, W=
eekend, Live! needs to be removed */ td[class=3D"weekend-mobile-container-p=
adding"]{ padding: 0px 10px 20px 10px !important; } td[class=3D"mobile-cont=
ainer-nav-padding"]{ padding: 10px 0 10px 0 !important; } /* Goods Parity H=
eader */ td[class=3D"floatLeft-ship"]{ float: left !important; width: 100% =
!important; border: 0px none !important; text-align: left !important; paddi=
ng: 5px 0 15px 0 !important; line-height: 14px !important; font-size: 13px =
!important; } td[class=3D"floatLeft-name"]{ float: left !important; width: =
100% !important; border: 0px none !important; text-align: left !important; =
padding: 5px 0 5px 0 !important; line-height: 14px !important; font-weight:=
 bold !important; font-size: 13px !important; } /* Turn off desktop CSS */ =
td[class=3D"no-padding"]{ padding: 0px !important; } td[class=3D"no-border-=
no-padding"]{ padding: 0px !important; border: none !important; } .no-borde=
r { border: none !important; } *[class=3D"display-off"]{ display: none !imp=
ortant; } /*Goods Shipment Notification and Transaction Failed */ td[class=
=3D"shipment-col-4-mobile"]{ width: 50% !important; } /*Welcome Day 0 Redes=
ign */ *[class=3D"container-white"]{ width: 100% !important; background-col=
or: #ffffff !important; padding: 0 0 0 0 !important; } *[class=3D"textAlign=
Center"]{ text-align: center !important; } /* Buttons */ table[class=3D"but=
ton-width"]{ width: 80px !important; } td[class=3D"viewButtonMobile"]{ padd=
ing: 12px 10px 12px 10px !important; } /* Banners */ *[class=3D"mobile-bann=
er"]{ width: 100%!important; max-height: none!important; height: auto!impor=
tant; display: block!important; padding: 20px 0 0 0!important; color: #0000=
00!important; font-size: 32px!important; line-height: 24px !important; } *[=
class=3D"mobile-banner-img"]{ width: 100%!important; max-height: none!impor=
tant; height: auto!important; display:block!important; padding: 0 0 0 0!imp=
ortant; color: #000000!important; font-size: 12px!important; } *[class=3D"m=
obile-banner-img-pad"]{ width: 100%!important; max-height: none!important; =
height: auto!important; display:block!important; padding: 0 0 10px 0!import=
ant; color: #000000!important; font-size: 12px!important; } *[class=3D"2up-=
image-mobile"]{ width: 100% !important; max-height: none!important; height:=
 auto!important; display: block!important; float: left !important; } /* Use=
r Messaging Service */ *[class=3D"heading_style"]{ -webkit-text-size-adjust=
:none !important; font-size:13px !important; font-style:normal !important; =
font-variant:normal !important; font-weight:normal !important; font-family:=
Arial, Verdana, sans-serif !important; color:#cdf5ff !important; line-heigh=
t:18px !important; } /* Font Classes */ td[class=3D"mobile-font"]{ font-siz=
e: 13px !important; } span[class=3D"nameFont"]{ font-size: 18px !important;=
 line-height: 22px !important; } td[class=3D"nameFont"]{ font-size: 18px !i=
mportant; line-height: 22px !important; } td[class=3D"themeFont"]{ font-siz=
e: 30px !important; line-height: 34px !important; } td[class=3D"heroNameFon=
t"]{ font-size: 18px !important; line-height: 22px !important; } a[class=3D=
"heroNameFont"]{ text-decoration: none !important; font-size: 18px !importa=
nt; line-height: 22px !important; } *[class=3D"font-12"]{ font-size:12px !i=
mportant; } *[class=3D"font-13"]{ font-size:13px !important; } *[class=3D"f=
ont-16"]{ font-size:16px !important; } *[class=3D"font-18"]{ font-size:18px=
 !important; } img[class=3D"glive-deal-image"]{ width: 80% !important; heig=
ht: auto !important; display: block; margin:0 auto; padding: 0; } div[class=
=3D"gmailfix"] { display: none; display: none !important; } td[class=3D"mob=
ile-padding-logo"]{ padding: 0 0 0 0 !important; width: 195px !important; }=
 table[class=3D"heroButton"]{ width: 120px !important; } table[class=3D"her=
oButton"]{ width: 120px !important; } *[class=3D"mobile-padding-font"]{ pad=
ding: 0 0 0 0 !important; font-size: 10px !important; font-weight:normal !i=
mportant; } *[class=3D"mobile-padding-font-purchase"]{ padding: 0 0 0 0 !im=
portant; font-size: 9px !important; font-weight:normal !important; } td[cla=
ss=3D"header-text"]{ text-align: left !important; } td[class=3D"collapse-le=
ft-postcard"]{ width: 100% !important; float: left !important; position: re=
lative !important; padding: 20px 0 20px 0 !important; } table[class=3D"seo-=
button-width"]{ width: 158px !important; } table[class=3D"container_border"=
]{ width: 100% !important; padding: 0 0 0 0 !important; } *[class=3D"margin=
_zero_auto"]{ margin: 0 auto !important; display: block !important; } *[cla=
ss=3D"text_pad"]{ padding:7px 0 0 0 !important; } *[class=3D"display_table"=
]{ display: block !important; width:100% !important; } } </style> <link hre=
f=3D'https://fonts.googleapis.com/css?family=3DOpen+Sans:100,200,400,300,50=
0,600,700,800' rel=3D'stylesheet' type=3D'text/css' /> <!--[if mso]> <style=
> body,table tr,table td,a, span {font-family:Arial, Helvetica, sans-serif =
!important;}</style> <!--<![endif]--> </head> <body style=3D"margin:0 !impo=
rtant; padding:0 !important; background: #f2f2f2 !important;"> <img src =3D=
 "http://www.groupon.com/analytic/track.gif?p=3D1&utm_domain=3Dkylefisher.c=
om&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111&deals=3D4=
45d7888-960c-11e6-851f-00259069d7cc,19eddaca-8400-11e6-a980-00259069d7cc,a0=
8a7bf0-88e3-11e6-985f-00259069d868,78591936-9007-11e6-870d-00259069d868,01d=
12c81-7de6-4538-9c50-4c6a3f8d876a,6623ff4a-8bd6-11e6-aee2-00259060b5da,e9d5=
9326-6a5c-11e6-aa0d-00259069d7cc,b1f159ce-37dd-11e6-ad91-002590604002,b6d82=
863-b64e-43fa-8ab1-7a9ffabe9b43,ce9e9670-e901-4517-be39-f072faedf6ad,43efa2=
a6-6291-49ee-a1aa-b62a12656eda,703f1c64-fdef-4761-8443-a8250a946e61,08c4b6f=
6-90d5-11e6-b2a2-002590604002,503c69bc-8b61-11e6-89fc-00259069d868,a27290a8=
-97cd-11e6-9721-00259069d868,76fa84a4-6adb-11e6-84bb-00259069d7cc&channel_d=
eals=3Dnull&utm_source=3Dgg-swarovski-elements-mystery-jewelry-collection&u=
tm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134=
cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CI=
D=3DUS" height=3D"1" width=3D"1" style=3D"display: none !important;" /> <ta=
ble cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spa=
cing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#000000; font-w=
eight: normal; text-align: left; width:100%; background: #f2f2f2;" width=3D=
"100%" bgcolor=3D"#f2f2f2" align=3D"center"> <tr> <td align=3D"center"> <sp=
an style=3D"color: #f2f2f2; font-size: 0px !important;" height=3D"0"> </spa=
n> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"width:670px; backgro=
und: #ffffff;" width=3D"670" align=3D"center" class=3D"container"> <tr> <td=
 align=3D"center" style=3D"padding: 10px 10px 0 10px;"> <table cellpadding=
=3D"0" cellspacing=3D"0" style=3D"width: 600px;" width=3D"600" align=3D"cen=
ter" class=3D"container"> <tr> <td style=3D"padding: 10px 0 10px 0;"> <tabl=
e cellpadding=3D"0" cellspacing=3D"0" style=3D"width: 257px;" width=3D"257"=
 align=3D"left" class=3D"container"> <tr> <td align=3D"left" style=3D"width=
: 257px;" class=3D"mobile-padding-logo"><a href=3D"http://www.groupon.com/g=
oods?utm_source=3Dgg-swarovski-elements-mystery-jewelry-collection&utm_medi=
um=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf38656=
1ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&=
s=3Dheader&c=3Dimage&d=3DGroupon&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c=
7fb9cce33_0_20161111" style=3D"font-size: 34px; color: #333333; font-weight=
: normal; font-weight: 700;" target=3D"_blank"><img src=3D"http://s3.groupo=
ncdn.com/email/images/prom_night/global_images/pn-groupon-logo-green.png" s=
tyle=3D"display: block; border: none; width:257px;" alt=3D"GROUPON&reg;" ti=
tle=3D"GROUPON&reg;" class=3D"100"></a> </td> </tr> </table> </td> <td alig=
n=3D"right" valign=3D"middle" style=3D"padding-left:10px;" valign=3D"bottom=
"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"width: 100px;" width=
=3D"100" align=3D"right"> <tr> <td align=3D"right" style=3D"white-space:now=
rap;"><a href=3D"http://www.facebook.com/groupon" style=3D"color:#0185C6; t=
ext-decoration:none;" target=3D"_blank"><img src=3D"http://s3.grouponcdn.co=
m/email/images/mindstorm/social/icon-facebook-white.png" style=3D"display: =
block; border: none; display: inline-block;" /></a>&nbsp;<a href=3D"http://=
www.twitter.com/groupon" style=3D"color:#0185C6; text-decoration:none;" tar=
get=3D"_blank"><img src=3D"http://s3.grouponcdn.com/email/images/mindstorm/=
social/icon-twitter-white.png" style=3D"display: block; border: none; displ=
ay: inline-block;" />&nbsp;</a><a href=3D"http://www.pinterest.com/groupon"=
 style=3D"color:#0185C6; text-decoration:none;" target=3D"_blank"><img src=
=3D"http://s3.grouponcdn.com/email/images/mindstorm/social/icon-pinterest-w=
hite.png" style=3D"display: block; border: none; display: inline-block;" />=
</a></td> </tr> </table> </td> </tr> <tr> <td colspan=3D"2" style=3D"border=
-top: 1px solid #cccccc;"> <table cellpadding=3D"0" cellspacing=3D"0" style=
=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, san=
s-serif; color:#000000; font-weight: normal; text-align: left; width: 100%;=
" align=3D"center" class=3D"container"> <tr> <td style=3D"padding: 10px 0 1=
0px 0;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none=
; border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#00=
0000; font-weight: normal; text-align: left; width: 100%;" align=3D"center"=
 class=3D"container"> <tr> <td colspan=3D"2" class=3D"floatLeft-name" style=
=3D"width: 40%; font-size: 14px; color: #6d6d6d; font-weight: 500;" align=
=3D"left">For Kyle | November 11, 2016</td> </tr> </table> </td> </tr> </ta=
ble> </td> </tr> </table> </td> </tr> </table> </td> </tr> </table> <table =
cellpadding=3D"0" cellspacing=3D"0" style=3D"width: 100%; background: #f2f2=
f2" align=3D"center"> <tr> <td align=3D"center"> <table cellpadding=3D"0" c=
ellspacing=3D"0" style=3D"width: 670px; background: #ffffff;" bgcolor=3D"#f=
fffff" align=3D"center" class=3D"container"> <tr> <td align=3D"center"> <ta=
ble cellpadding=3D"0" cellspacing=3D"0" style=3D"width: 600px; min-width:60=
0px; background: #ffffff;" bgcolor=3D"#ffffff" align=3D"center" class=3D"co=
ntainer"> <tr> <td align=3D"center" style=3D"padding: 5px 0 40px 0;" class=
=3D"mobile-container-padding"> <table cellpadding=3D"0" cellspacing=3D"0" s=
tyle=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial,=
 sans-serif; color:#000000; font-weight: normal; text-align: left; width: 1=
00%; background-color: #ffffff;" align=3D"center"> <tr> <td style=3D"paddin=
g: 0px; display:none; font-size:0; max-height:0; line-height:0; mso-hide: a=
ll;" class=3D"mobile-banner"><a href=3D"https://www.groupon.com/occasion/do=
orbusters?p=3D1&utm_source=3Dgg-swarovski-elements-mystery-jewelry-collecti=
on&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2aca=
c134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5f=
e&CID=3DUS&s=3Dbody&c=3Dbanner&d=3Ddynamic-banner-0&utm_campaign=3D96fba5be=
-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" style=3D"color:#0185C6; text-decor=
ation:none;" target=3D"_blank"> <img src=3D"https://img.grouponcdn.com/deal=
/FUVU5ptQF9pDDiwyfgzhEtdx2CD/FU-460x307.jpg" style=3D"padding:0px; display:=
none; font-size:0; max-height:0; line-height:0; mso-hide: all;" class=3D"mo=
bile-banner-img" alt=3D"Groupon" /></a> </td> </tr> </table> <table cellpad=
ding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing: 0; fo=
nt-family: 'Open Sans', Arial, sans-serif; color:#000000; font-weight: norm=
al; text-align: left; width: 100%; min-width:290px; background-color: #ffff=
ff;" align=3D"center" class=3D"display-off"> <tr> <td align=3D"center" styl=
e=3D"padding: 20px 0 0 0; min-width:290px;"><a href=3D"https://www.groupon.=
com/occasion/doorbusters?p=3D1&utm_source=3Dgg-swarovski-elements-mystery-j=
ewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1e=
d8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-8=
2c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbanner&d=3Ddynamic-banner-0&utm_camp=
aign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" style=3D"color:#018=
5C6; text-decoration:none;" target=3D"_blank"> <img src=3D"https://img.grou=
poncdn.com/deal/27FfsHsiWqgeWLC1BhpfYzsqZxmo/27-600x400.jpg" style=3D"displ=
ay: block; border: none; min-width:290px;" alt=3D"Groupon" /></a> </td> </t=
r> </table> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=
=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, san=
s-serif; color:#000000; font-weight: normal; text-align: left; width:600px;=
 min-width:600px; background: #FFFFFF;" align=3D"center" class=3D"container=
"> <tr> <td align=3D"left" width=3D"100%" style=3D"width: 600px; min-width:=
600px;" class=3D"100"> <table cellpadding=3D"0" cellspacing=3D"0" border=3D=
"0" style=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans', A=
rial, sans-serif; color:#000000; font-weight: normal; text-align: left; wid=
th: 600px; min-width:600px;" class=3D"container"> <tr> <td valign=3D"top" a=
lign=3D"left" width=3D"100%" style=3D"width: 600px; min-width:600px;" class=
=3D"100"> <!--[if (gte mso 9)|(IE)]> <table width=3D"600" align=3D"center" =
cellpadding=3D"0" cellspacing=3D"0" border=3D"0"> <tr> <![endif]--> <!--[if=
 (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https://www.groupon.com/de=
als/gg-apple-ipad-2-3-4-air-or-air-2-4?p=3D2&utm_source=3Dgg-swarovski-elem=
ents-mystery-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574=
337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c23=
4c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&ut=
m_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" target=3D"_bl=
ank" style=3D"color: #000000; font-size: 14px !important; line-height: 18px=
 !important; color:#000000 !important; text-decoration: none;"> <table vali=
gn=3D"top" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border=
: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; c=
olor:#000000; font-weight: normal; text-align: left; width:290px; mso-table=
-lspace:0;mso-table-rspace:0;" width=3D"290" align=3D'left' class=3D"contai=
ner"> <tr> <td valign=3D"top" width=3D"100%" style=3D"mso-table-lspace:0;ms=
o-table-rspace:0; width:100%; padding:20px 0 0 0;"> <table cellpadding=3D"0=
" cellspacing=3D"0" border=3D"0" style=3D"width:100%;" width=3D"100%"> <tr>=
 <td valign=3D"top" align=3D"center" width=3D"290" style=3D"width:290px;" c=
lass=3D"container"><a href=3D"https://www.groupon.com/deals/gg-apple-ipad-2=
-3-4-air-or-air-2-4?p=3D2&utm_source=3Dgg-swarovski-elements-mystery-jewelr=
y-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f80=
6fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-0=
0259069d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3D96fba5b=
e-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" style=3D"display: block; border: =
none;" target=3D"_blank"><img src=3D"https://img.grouponcdn.com/deal/2YRMD6=
z4WZZ35xRZ8gxVRcXBx9hG/2Y-1000x600/v1/t300x182.jpg" width=3D"290" style=3D"=
display: block; border: none; width: 290px;" class=3D"100" alt=3D"Apple iPa=
d 2, 3, 4, Air, or Air 2 (WiFi Only) (Refurbished)" /></a></td> </tr> <tr> =
<td> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"width=
:100%; background: #f2f2f2;" width=3D"100%"> <tr> <td class=3D"nameFont" st=
yle=3D"padding: 16px 16px 0 16px; font-size: 14px !important; line-height: =
18px !important; color:#000000 !important; text-decoration: none; color: #0=
00000;" align=3D"left"> Apple iPad 2, 3, 4, Air or Air 2 </td> </tr> <tr> <=
td style=3D"background: #f2f2f2;" valign=3D"top"><a href=3D"https://www.gro=
upon.com/deals/gg-apple-ipad-2-3-4-air-or-air-2-4?p=3D2&utm_source=3Dgg-swa=
rovski-elements-mystery-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7=
c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&=
uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3D=
Mindstorm-Hero-3-deals&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_=
0_20161111" target=3D"_blank" style=3D"font-size: 14px !important; line-hei=
ght: 18px !important; color:#000000 !important; text-decoration: none;">&nb=
sp;</a></td> </tr> <tr> <td valign=3D"top" style=3D"width:290px; min-width:=
290px; padding-bottom:16px;" class=3D"100"> <table cellpadding=3D"0" cellsp=
acing=3D"0" border=3D"0" style=3D"border: 0 none; border-spacing: 0; font-f=
amily: 'Open Sans', Arial, sans-serif; color:#000000; font-weight: normal; =
text-align: left; background: #f2f2f2; width:290px;" valign=3D"top" width=
=3D"290" class=3D"container"> <tr> <td style=3D"padding: 3px 0 0 16px;" ali=
gn=3D"left"> <span style=3D"padding: 0 5px 0 0; padding-right: 5px; font-si=
ze: 16px; line-height: 20px; text-decoration: line-through; color:#848484; =
font-weight: 100;"> $249 </span> <span style=3D"font-size: 16px; line-heigh=
t: 20px; font-weight: bold; text-decoration: none; color: #e35205;"> $149.9=
9 </span> </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"=
top" style=3D"padding: 0px 0px 0px 16px; font-family: Helvetica, Arial, san=
s-serif; font-size: 13px; color: #e35205; text-decoration: none; font-weigh=
t: 500 !important;">Sale Ends 11/14</td> <td width=3D"30%" class=3D"nameFon=
t" align=3D"right" valign=3D"top" style=3D"font-family: Helvetica, Arial, s=
ans-serif; padding: 0 16px 0 0; font-size: 13px !important; line-height: 17=
px !important; font-weight: normal; font-weight: 600; color: #0185c6 !impor=
tant; text-decoration: none; text-align:right; white-space: nowrap;"><a hre=
f=3D"https://www.groupon.com/deals/gg-apple-ipad-2-3-4-air-or-air-2-4?p=3D2=
&utm_source=3Dgg-swarovski-elements-mystery-jewelry-collection&utm_medium=
=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561e=
d8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=
=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7=
fb9cce33_0_20161111" target=3D"_blank" style=3D"color:#0185c6; text-decorat=
ion:none;"><font color=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </t=
able> </td> </tr> </table> </td> </tr> </table> </td> </tr> </table> </a> <=
!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td=
> <![endif]--> <a href=3D"https://www.groupon.com/deals/gg-chic-home-sabrin=
a-pinch-pleat-comforter-and-sheet-set-10-piece-2?p=3D3&utm_source=3Dgg-swar=
ovski-elements-mystery-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c=
8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&u=
u=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DG=
oods-PN&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" tar=
get=3D"_blank" style=3D"color: #000000; font-size: 14px !important; line-he=
ight: 18px !important; color:#000000 !important; text-decoration: none;"> <=
table valign=3D"top" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=
=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, san=
s-serif; color:#000000; font-weight: normal; text-align: left; width:290px;=
 mso-table-lspace:0;mso-table-rspace:0;" width=3D"290" align=3D'right' clas=
s=3D"container"> <tr> <td valign=3D"top" width=3D"100%" style=3D"mso-table-=
lspace:0;mso-table-rspace:0; width:100%; padding:20px 0 0 0;"> <table cellp=
adding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"width:100%;" width=3D"=
100%"> <tr> <td valign=3D"top" align=3D"center" width=3D"290" style=3D"widt=
h:290px;" class=3D"container"><a href=3D"https://www.groupon.com/deals/gg-c=
hic-home-sabrina-pinch-pleat-comforter-and-sheet-set-10-piece-2?p=3D3&utm_s=
ource=3Dgg-swarovski-elements-mystery-jewelry-collection&utm_medium=3Demail=
&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&da=
te=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=
=3Dimage&d=3DGoods-PN&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0=
_20161111" style=3D"display: block; border: none;" target=3D"_blank"><img s=
rc=3D"https://img.grouponcdn.com/deal/3TWmAxHcgKhqPjg4Vtn/aD-2463x1478/v1/t=
300x182.jpg" width=3D"290" style=3D"display: block; border: none; width: 29=
0px;" class=3D"100" alt=3D"Chic Home Sabrina Pinch Pleat Comforter and Shee=
t Set (10-Piece)" /></a></td> </tr> <tr> <td> <table cellpadding=3D"0" cell=
spacing=3D"0" border=3D"0" style=3D"width:100%; background: #f2f2f2;" width=
=3D"100%"> <tr> <td class=3D"nameFont" style=3D"padding: 16px 16px 0 16px; =
font-size: 14px !important; line-height: 18px !important; color:#000000 !im=
portant; text-decoration: none; color: #000000;" align=3D"left"> Pleated Co=
mforter Set (10-Piece) </td> </tr> <tr> <td style=3D"background: #f2f2f2;" =
valign=3D"top"><a href=3D"https://www.groupon.com/deals/gg-chic-home-sabrin=
a-pinch-pleat-comforter-and-sheet-set-10-piece-2?p=3D3&utm_source=3Dgg-swar=
ovski-elements-mystery-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c=
8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&u=
u=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DM=
indstorm-Hero-3-deals&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0=
_20161111" target=3D"_blank" style=3D"font-size: 14px !important; line-heig=
ht: 18px !important; color:#000000 !important; text-decoration: none;">&nbs=
p;</a></td> </tr> <tr> <td valign=3D"top" style=3D"width:290px; min-width:2=
90px; padding-bottom:16px;" class=3D"100"> <table cellpadding=3D"0" cellspa=
cing=3D"0" border=3D"0" style=3D"border: 0 none; border-spacing: 0; font-fa=
mily: 'Open Sans', Arial, sans-serif; color:#000000; font-weight: normal; t=
ext-align: left; background: #f2f2f2; width:290px;" valign=3D"top" width=3D=
"290" class=3D"container"> <tr> <td style=3D"padding: 3px 0 0 16px;" align=
=3D"left"> <span style=3D"padding: 0 5px 0 0; padding-right: 5px; font-size=
: 16px; line-height: 20px; text-decoration: line-through; color:#848484; fo=
nt-weight: 100;"> $309.99 </span> <span style=3D"font-size: 16px; line-heig=
ht: 20px; font-weight: bold; text-decoration: none; color: #e35205;"> $69.9=
9 </span> </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"=
top" style=3D"padding: 0px 0px 0px 16px; font-family: Helvetica, Arial, san=
s-serif; font-size: 13px; color: #e35205; text-decoration: none; font-weigh=
t: 500 !important;">Sale Ends 11/12</td> <td width=3D"30%" class=3D"nameFon=
t" align=3D"right" valign=3D"top" style=3D"font-family: Helvetica, Arial, s=
ans-serif; padding: 0 16px 0 0; font-size: 13px !important; line-height: 17=
px !important; font-weight: normal; font-weight: 600; color: #0185c6 !impor=
tant; text-decoration: none; text-align:right; white-space: nowrap;"><a hre=
f=3D"https://www.groupon.com/deals/gg-chic-home-sabrina-pinch-pleat-comfort=
er-and-sheet-set-10-piece-2?p=3D3&utm_source=3Dgg-swarovski-elements-myster=
y-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070e=
e1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e=
2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=
=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" target=3D"_blank" style=
=3D"color:#0185c6; text-decoration:none;"><font color=3D"#0185c6">View&nbsp=
;Deal</font></a></td> </tr> </table> </td> </tr> </table> </td> </tr> </tab=
le> </td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]-->=
 <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> <=
/tr> </table> <![endif]--> </td> </tr> <tr> <td valign=3D"top" align=3D"lef=
t" width=3D"100%" style=3D"width: 600px; min-width:600px;" class=3D"100"> <=
!--[if (gte mso 9)|(IE)]> <table width=3D"600" align=3D"center" cellpadding=
=3D"0" cellspacing=3D"0" border=3D"0"> <tr> <![endif]--> <!--[if (gte mso 9=
)|(IE)]> <td> <![endif]--> <a href=3D"https://www.groupon.com/deals/gg-brav=
eman-mens-wool-blend-coats-w-free-scar?p=3D4&utm_source=3Dgg-swarovski-elem=
ents-mystery-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574=
337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c23=
4c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&ut=
m_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" target=3D"_bl=
ank" style=3D"color: #000000; font-size: 14px !important; line-height: 18px=
 !important; color:#000000 !important; text-decoration: none;"> <table vali=
gn=3D"top" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border=
: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; c=
olor:#000000; font-weight: normal; text-align: left; width:290px; mso-table=
-lspace:0;mso-table-rspace:0;" width=3D"290" align=3D'left' class=3D"contai=
ner"> <tr> <td valign=3D"top" width=3D"100%" style=3D"mso-table-lspace:0;ms=
o-table-rspace:0; width:100%; padding:20px 0 0 0;"> <table cellpadding=3D"0=
" cellspacing=3D"0" border=3D"0" style=3D"width:100%;" width=3D"100%"> <tr>=
 <td valign=3D"top" align=3D"center" width=3D"290" style=3D"width:290px;" c=
lass=3D"container"><a href=3D"https://www.groupon.com/deals/gg-braveman-men=
s-wool-blend-coats-w-free-scar?p=3D4&utm_source=3Dgg-swarovski-elements-mys=
tery-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c8220=
70ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-=
11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaig=
n=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" style=3D"display: bloc=
k; border: none;" target=3D"_blank"><img src=3D"https://img.grouponcdn.com/=
deal/4Z8uxyWfAcBnWGCS3fzv22dMmWzi/4Z-2048x1229/v1/t300x182.jpg" width=3D"29=
0" style=3D"display: block; border: none; width: 290px;" class=3D"100" alt=
=3D"Braveman Men's Wool Blend Coats with Free Plaid Scarf " /></a></td> </t=
r> <tr> <td> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=
=3D"width:100%; background: #f2f2f2;" width=3D"100%"> <tr> <td class=3D"nam=
eFont" style=3D"padding: 16px 16px 0 16px; font-size: 14px !important; line=
-height: 18px !important; color:#000000 !important; text-decoration: none; =
color: #000000;" align=3D"left"> Men's Wool Coat with Free Scarf </td> </tr=
> <tr> <td style=3D"padding: 0 16px 0 16px;" class=3D"nameFont" align=3D"le=
ft"><a href=3D"https://www.groupon.com/deals/gg-braveman-mens-wool-blend-co=
ats-w-free-scar?p=3D4&utm_source=3Dgg-swarovski-elements-mystery-jewelry-co=
llection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf=
5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259=
069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-deals&utm_campaig=
n=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" target=3D"_blank" styl=
e=3D"font-size: 14px !important; line-height: 18px !important; color:#00000=
0 !important; text-decoration: none;"><font color=3D"#e35205">Over 1,000 bo=
ught</font></a></td> </tr> <tr> <td valign=3D"top" style=3D"width:290px; mi=
n-width:290px; padding-bottom:16px;" class=3D"100"> <table cellpadding=3D"0=
" cellspacing=3D"0" border=3D"0" style=3D"border: 0 none; border-spacing: 0=
; font-family: 'Open Sans', Arial, sans-serif; color:#000000; font-weight: =
normal; text-align: left; background: #f2f2f2; width:290px;" valign=3D"top"=
 width=3D"290" class=3D"container"> <tr> <td style=3D"padding: 3px 0 0 16px=
;" align=3D"left"> <span style=3D"padding: 0 5px 0 0; padding-right: 5px; f=
ont-size: 16px; line-height: 20px; text-decoration: line-through; color:#84=
8484; font-weight: 100;"> $350 </span> <span style=3D"font-size: 16px; line=
-height: 20px; font-weight: bold; text-decoration: none; color: #e35205;"> =
$49.99 </span> </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valig=
n=3D"top" style=3D"padding: 0px 0px 0px 16px; font-family: Helvetica, Arial=
, sans-serif; font-size: 13px; color: #e35205; text-decoration: none; font-=
weight: 500 !important;">Sale Ends 11/14</td> <td width=3D"30%" class=3D"na=
meFont" align=3D"right" valign=3D"top" style=3D"font-family: Helvetica, Ari=
al, sans-serif; padding: 0 16px 0 0; font-size: 13px !important; line-heigh=
t: 17px !important; font-weight: normal; font-weight: 600; color: #0185c6 !=
important; text-decoration: none; text-align:right; white-space: nowrap;"><=
a href=3D"https://www.groupon.com/deals/gg-braveman-mens-wool-blend-coats-w=
-free-scar?p=3D4&utm_source=3Dgg-swarovski-elements-mystery-jewelry-collect=
ion&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2ac=
ac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5=
fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3D96fba5be-9b7b-4=
9e6-83e7-b7c7fb9cce33_0_20161111" target=3D"_blank" style=3D"color:#0185c6;=
 text-decoration:none;"><font color=3D"#0185c6">View&nbsp;Deal</font></a></=
td> </tr> </table> </td> </tr> </table> </td> </tr> </table> </td> </tr> </=
table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso =
9)|(IE)]> <td> <![endif]--> <a href=3D"https://www.groupon.com/deals/gg-rok=
u-4-streaming-player-4k-uhd?p=3D5&utm_source=3Dgg-swarovski-elements-myster=
y-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070e=
e1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e=
2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=
=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" target=3D"_blank" style=
=3D"color: #000000; font-size: 14px !important; line-height: 18px !importan=
t; color:#000000 !important; text-decoration: none;"> <table valign=3D"top"=
 cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border: 0 none; =
border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#0000=
00; font-weight: normal; text-align: left; width:290px; mso-table-lspace:0;=
mso-table-rspace:0;" width=3D"290" align=3D'right' class=3D"container"> <tr=
> <td valign=3D"top" width=3D"100%" style=3D"mso-table-lspace:0;mso-table-r=
space:0; width:100%; padding:20px 0 0 0;"> <table cellpadding=3D"0" cellspa=
cing=3D"0" border=3D"0" style=3D"width:100%;" width=3D"100%"> <tr> <td vali=
gn=3D"top" align=3D"center" width=3D"290" style=3D"width:290px;" class=3D"c=
ontainer"><a href=3D"https://www.groupon.com/deals/gg-roku-4-streaming-play=
er-4k-uhd?p=3D5&utm_source=3Dgg-swarovski-elements-mystery-jewelry-collecti=
on&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2aca=
c134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5f=
e&CID=3DUS&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3D96fba5be-9b7b-49e=
6-83e7-b7c7fb9cce33_0_20161111" style=3D"display: block; border: none;" tar=
get=3D"_blank"><img src=3D"https://img.grouponcdn.com/deal/3RHhhxsG3TjBZyK6=
N6WE1vCREwz9/3R-1000x600/v1/t300x182.jpg" width=3D"290" style=3D"display: b=
lock; border: none; width: 290px;" class=3D"100" alt=3D"Roku 4 Streaming Pl=
ayer 4K UHD" /></a></td> </tr> <tr> <td> <table cellpadding=3D"0" cellspaci=
ng=3D"0" border=3D"0" style=3D"width:100%; background: #f2f2f2;" width=3D"1=
00%"> <tr> <td class=3D"nameFont" style=3D"padding: 16px 16px 0 16px; font-=
size: 14px !important; line-height: 18px !important; color:#000000 !importa=
nt; text-decoration: none; color: #000000;" align=3D"left"> Roku 4 Streamin=
g Player 4K UHD </td> </tr> <tr> <td style=3D"padding: 0 16px 0 16px;" clas=
s=3D"nameFont" align=3D"left"><a href=3D"https://www.groupon.com/deals/gg-r=
oku-4-streaming-player-4k-uhd?p=3D5&utm_source=3Dgg-swarovski-elements-myst=
ery-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c82207=
0ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-1=
1e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-dea=
ls&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" target=
=3D"_blank" style=3D"font-size: 14px !important; line-height: 18px !importa=
nt; color:#000000 !important; text-decoration: none;"><font color=3D"#e3520=
5">Over 400 bought</font></a></td> </tr> <tr> <td valign=3D"top" style=3D"w=
idth:290px; min-width:290px; padding-bottom:16px;" class=3D"100"> <table ce=
llpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border: 0 none; bor=
der-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#000000;=
 font-weight: normal; text-align: left; background: #f2f2f2; width:290px;" =
valign=3D"top" width=3D"290" class=3D"container"> <tr> <td style=3D"padding=
: 3px 0 0 16px;" align=3D"left"> <span style=3D"padding: 0 5px 0 0; padding=
-right: 5px; font-size: 16px; line-height: 20px; text-decoration: line-thro=
ugh; color:#848484; font-weight: 100;"> $129.99 </span> <span style=3D"font=
-size: 16px; line-height: 20px; font-weight: bold; text-decoration: none; c=
olor: #e35205;"> $89.99 </span> </td> </tr> <tr> <td class=3D"nameFont" ali=
gn=3D"left" valign=3D"top" style=3D"padding: 0px 0px 0px 16px; font-family:=
 Helvetica, Arial, sans-serif; font-size: 13px; color: #e35205; text-decora=
tion: none; font-weight: 500 !important;">Sale Ends 11/12</td> <td width=3D=
"30%" class=3D"nameFont" align=3D"right" valign=3D"top" style=3D"font-famil=
y: Helvetica, Arial, sans-serif; padding: 0 16px 0 0; font-size: 13px !impo=
rtant; line-height: 17px !important; font-weight: normal; font-weight: 600;=
 color: #0185c6 !important; text-decoration: none; text-align:right; white-=
space: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-roku-4-streamin=
g-player-4k-uhd?p=3D5&utm_source=3Dgg-swarovski-elements-mystery-jewelry-co=
llection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf=
5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259=
069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3D96fba5be-9=
b7b-49e6-83e7-b7c7fb9cce33_0_20161111" target=3D"_blank" style=3D"color:#01=
85c6; text-decoration:none;"><font color=3D"#0185c6">View&nbsp;Deal</font><=
/a></td> </tr> </table> </td> </tr> </table> </td> </tr> </table> </td> </t=
r> </table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte=
 mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </tr> </table>=
 <![endif]--> </td> </tr> <tr> <td valign=3D"top" align=3D"left" width=3D"1=
00%" style=3D"width: 600px; min-width:600px;" class=3D"100"> <!--[if (gte m=
so 9)|(IE)]> <table width=3D"600" align=3D"center" cellpadding=3D"0" cellsp=
acing=3D"0" border=3D"0"> <tr> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td>=
 <![endif]--> <a href=3D"https://www.groupon.com/deals/gg-dolce-gabbana-lig=
ht-blue-eau-de-toilette-for-women-or-men?p=3D6&utm_source=3Dgg-swarovski-el=
ements-mystery-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf5=
74337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c=
234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&=
utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" target=3D"_=
blank" style=3D"color: #000000; font-size: 14px !important; line-height: 18=
px !important; color:#000000 !important; text-decoration: none;"> <table va=
lign=3D"top" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"bord=
er: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif;=
 color:#000000; font-weight: normal; text-align: left; width:290px; mso-tab=
le-lspace:0;mso-table-rspace:0;" width=3D"290" align=3D'left' class=3D"cont=
ainer"> <tr> <td valign=3D"top" width=3D"100%" style=3D"mso-table-lspace:0;=
mso-table-rspace:0; width:100%; padding:20px 0 0 0;"> <table cellpadding=3D=
"0" cellspacing=3D"0" border=3D"0" style=3D"width:100%;" width=3D"100%"> <t=
r> <td valign=3D"top" align=3D"center" width=3D"290" style=3D"width:290px;"=
 class=3D"container"><a href=3D"https://www.groupon.com/deals/gg-dolce-gabb=
ana-light-blue-eau-de-toilette-for-women-or-men?p=3D6&utm_source=3Dgg-swaro=
vski-elements-mystery-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8=
bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=
=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=3DGoo=
ds-PN&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" style=
=3D"display: block; border: none;" target=3D"_blank"><img src=3D"https://im=
g.grouponcdn.com/deal/GCrV2BKQTrZaVmLiBwRBD8zQLT1/GC-1400x840/v1/t300x182.j=
pg" width=3D"290" style=3D"display: block; border: none; width: 290px;" cla=
ss=3D"100" alt=3D"Dolce & Gabbana Light Blue Eau de Toilettes (Multiple Siz=
es)" /></a></td> </tr> <tr> <td> <table cellpadding=3D"0" cellspacing=3D"0"=
 border=3D"0" style=3D"width:100%; background: #f2f2f2;" width=3D"100%"> <t=
r> <td class=3D"nameFont" style=3D"padding: 16px 16px 0 16px; font-size: 14=
px !important; line-height: 18px !important; color:#000000 !important; text=
-decoration: none; color: #000000;" align=3D"left"> Dolce & Gabbana Light B=
lue </td> </tr> <tr> <td style=3D"padding: 0 16px 0 16px;" class=3D"nameFon=
t" align=3D"left"><a href=3D"https://www.groupon.com/deals/gg-dolce-gabbana=
-light-blue-eau-de-toilette-for-women-or-men?p=3D6&utm_source=3Dgg-swarovsk=
i-elements-mystery-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf0=
3cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3D=
f79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DMinds=
torm-Hero-3-deals&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_201=
61111" target=3D"_blank" style=3D"font-size: 14px !important; line-height: =
18px !important; color:#000000 !important; text-decoration: none;"><font co=
lor=3D"#e35205">Over 350 bought</font></a></td> </tr> <tr> <td valign=3D"to=
p" style=3D"width:290px; min-width:290px; padding-bottom:16px;" class=3D"10=
0"> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border=
: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; c=
olor:#000000; font-weight: normal; text-align: left; background: #f2f2f2; w=
idth:290px;" valign=3D"top" width=3D"290" class=3D"container"> <tr> <td sty=
le=3D"padding: 3px 0 0 16px;" align=3D"left"> <span style=3D"padding: 0 5px=
 0 0; padding-right: 5px; font-size: 16px; line-height: 20px; text-decorati=
on: line-through; color:#848484; font-weight: 100;"> $55 </span> <span styl=
e=3D"font-size: 16px; line-height: 20px; font-weight: bold; text-decoration=
: none; color: #e35205;"> $31.99 </span> </td> </tr> <tr> <td class=3D"name=
Font" align=3D"left" valign=3D"top" style=3D"padding: 0px 0px 0px 16px; fon=
t-family: Helvetica, Arial, sans-serif; font-size: 13px; color: #e35205; te=
xt-decoration: none; font-weight: 500 !important;">Sale Ends 11/14</td> <td=
 width=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" style=3D"f=
ont-family: Helvetica, Arial, sans-serif; padding: 0 16px 0 0; font-size: 1=
3px !important; line-height: 17px !important; font-weight: normal; font-wei=
ght: 600; color: #0185c6 !important; text-decoration: none; text-align:righ=
t; white-space: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-dolce-=
gabbana-light-blue-eau-de-toilette-for-women-or-men?p=3D6&utm_source=3Dgg-s=
warovski-elements-mystery-jewelry-collection&utm_medium=3Demail&user=3Dd8bf=
d7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D2016111=
1&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=
=3DGoods-PN&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111"=
 target=3D"_blank" style=3D"color:#0185c6; text-decoration:none;"><font col=
or=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </table> </td> </tr> </=
table> </td> </tr> </table> </td> </tr> </table> </a> <!--[if (gte mso 9)|(=
IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a hr=
ef=3D"https://www.groupon.com/deals/gg-shark-steam-spray-pro-w-interchangea=
ble-heads?p=3D7&utm_source=3Dgg-swarovski-elements-mystery-jewelry-collecti=
on&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2aca=
c134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5f=
e&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3D96fba5be-9b7b-49=
e6-83e7-b7c7fb9cce33_0_20161111" target=3D"_blank" style=3D"color: #000000;=
 font-size: 14px !important; line-height: 18px !important; color:#000000 !i=
mportant; text-decoration: none;"> <table valign=3D"top" cellpadding=3D"0" =
cellspacing=3D"0" border=3D"0" style=3D"border: 0 none; border-spacing: 0; =
font-family: 'Open Sans', Arial, sans-serif; color:#000000; font-weight: no=
rmal; text-align: left; width:290px; mso-table-lspace:0;mso-table-rspace:0;=
" width=3D"290" align=3D'right' class=3D"container"> <tr> <td valign=3D"top=
" width=3D"100%" style=3D"mso-table-lspace:0;mso-table-rspace:0; width:100%=
; padding:20px 0 0 0;"> <table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0" style=3D"width:100%;" width=3D"100%"> <tr> <td valign=3D"top" align=
=3D"center" width=3D"290" style=3D"width:290px;" class=3D"container"><a hre=
f=3D"https://www.groupon.com/deals/gg-shark-steam-spray-pro-w-interchangeab=
le-heads?p=3D7&utm_source=3Dgg-swarovski-elements-mystery-jewelry-collectio=
n&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac=
134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe=
&CID=3DUS&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3D96fba5be-9b7b-49e6=
-83e7-b7c7fb9cce33_0_20161111" style=3D"display: block; border: none;" targ=
et=3D"_blank"><img src=3D"https://img.grouponcdn.com/deal/3Tyd8dnQ3ECy2K61h=
tyGafV3Ptqa/3T-1400x840/v1/t300x182.jpg" width=3D"290" style=3D"display: bl=
ock; border: none; width: 290px;" class=3D"100" alt=3D"Shark Steam & Spray =
Pro Mop" /></a></td> </tr> <tr> <td> <table cellpadding=3D"0" cellspacing=
=3D"0" border=3D"0" style=3D"width:100%; background: #f2f2f2;" width=3D"100=
%"> <tr> <td class=3D"nameFont" style=3D"padding: 16px 16px 0 16px; font-si=
ze: 14px !important; line-height: 18px !important; color:#000000 !important=
; text-decoration: none; color: #000000;" align=3D"left"> Shark Steam & Spr=
ay Pro Mop </td> </tr> <tr> <td style=3D"padding: 0 16px 0 16px;" class=3D"=
nameFont" align=3D"left"><a href=3D"https://www.groupon.com/deals/gg-shark-=
steam-spray-pro-w-interchangeable-heads?p=3D7&utm_source=3Dgg-swarovski-ele=
ments-mystery-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf57=
4337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c2=
34c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DMindstorm-=
Hero-3-deals&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111=
" target=3D"_blank" style=3D"font-size: 14px !important; line-height: 18px =
!important; color:#000000 !important; text-decoration: none;"><font color=
=3D"#e35205">Over 350 bought</font></a></td> </tr> <tr> <td valign=3D"top" =
style=3D"width:290px; min-width:290px; padding-bottom:16px;" class=3D"100">=
 <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border: 0=
 none; border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; colo=
r:#000000; font-weight: normal; text-align: left; background: #f2f2f2; widt=
h:290px;" valign=3D"top" width=3D"290" class=3D"container"> <tr> <td style=
=3D"padding: 3px 0 0 16px;" align=3D"left"> <span style=3D"padding: 0 5px 0=
 0; padding-right: 5px; font-size: 16px; line-height: 20px; text-decoration=
: line-through; color:#848484; font-weight: 100;"> $189.99 </span> <span st=
yle=3D"font-size: 16px; line-height: 20px; font-weight: bold; text-decorati=
on: none; color: #e35205;"> $59.99 </span> </td> </tr> <tr> <td class=3D"na=
meFont" align=3D"left" valign=3D"top" style=3D"padding: 0px 0px 0px 16px; f=
ont-family: Helvetica, Arial, sans-serif; font-size: 13px; color: #e35205; =
text-decoration: none; font-weight: 500 !important;">Sale Ends 11/12</td> <=
td width=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" style=3D=
"font-family: Helvetica, Arial, sans-serif; padding: 0 16px 0 0; font-size:=
 13px !important; line-height: 17px !important; font-weight: normal; font-w=
eight: 600; color: #0185c6 !important; text-decoration: none; text-align:ri=
ght; white-space: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-shar=
k-steam-spray-pro-w-interchangeable-heads?p=3D7&utm_source=3Dgg-swarovski-e=
lements-mystery-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf=
574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79=
c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN=
&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" target=3D"=
_blank" style=3D"color:#0185c6; text-decoration:none;"><font color=3D"#0185=
c6">View&nbsp;Deal</font></a></td> </tr> </table> </td> </tr> </table> </td=
> </tr> </table> </td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td>=
 <![endif]--> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte ms=
o 9)|(IE)]> </tr> </table> <![endif]--> </td> </tr> <tr> <td valign=3D"top"=
 align=3D"left" width=3D"100%" style=3D"width: 600px; min-width:600px;" cla=
ss=3D"100"> <!--[if (gte mso 9)|(IE)]> <table width=3D"600" align=3D"center=
" cellpadding=3D"0" cellspacing=3D"0" border=3D"0"> <tr> <![endif]--> <!--[=
if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https://www.groupon.com/=
deals/gg-sports-camera?p=3D8&utm_source=3Dgg-swarovski-elements-mystery-jew=
elry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8=
f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c=
0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3D96f=
ba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" target=3D"_blank" style=3D"co=
lor: #000000; font-size: 14px !important; line-height: 18px !important; col=
or:#000000 !important; text-decoration: none;"> <table valign=3D"top" cellp=
adding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border: 0 none; border=
-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#000000; fo=
nt-weight: normal; text-align: left; width:290px; mso-table-lspace:0;mso-ta=
ble-rspace:0;" width=3D"290" align=3D'left' class=3D"container"> <tr> <td v=
align=3D"top" width=3D"100%" style=3D"mso-table-lspace:0;mso-table-rspace:0=
; width:100%; padding:20px 0 0 0;"> <table cellpadding=3D"0" cellspacing=3D=
"0" border=3D"0" style=3D"width:100%;" width=3D"100%"> <tr> <td valign=3D"t=
op" align=3D"center" width=3D"290" style=3D"width:290px;" class=3D"containe=
r"><a href=3D"https://www.groupon.com/deals/gg-sports-camera?p=3D8&utm_sour=
ce=3Dgg-swarovski-elements-mystery-jewelry-collection&utm_medium=3Demail&us=
er=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=
=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=
=3Dimage&d=3DGoods-PN&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0=
_20161111" style=3D"display: block; border: none;" target=3D"_blank"><img s=
rc=3D"https://img.grouponcdn.com/deal/2TgdkDS3ezYDUq31gTk3ehW2zzhZ/2T-1000x=
600/v1/t300x182.jpg" width=3D"290" style=3D"display: block; border: none; w=
idth: 290px;" class=3D"100" alt=3D"XtremePro HD 720p Sports Camera Bundle w=
ith Mounts & Accessories" /></a></td> </tr> <tr> <td> <table cellpadding=3D=
"0" cellspacing=3D"0" border=3D"0" style=3D"width:100%; background: #f2f2f2=
;" width=3D"100%"> <tr> <td class=3D"nameFont" style=3D"padding: 16px 16px =
0 16px; font-size: 14px !important; line-height: 18px !important; color:#00=
0000 !important; text-decoration: none; color: #000000;" align=3D"left"> Xt=
remePro HD 720p Sports Camera </td> </tr> <tr> <td style=3D"background: #f2=
f2f2;" valign=3D"top"><a href=3D"https://www.groupon.com/deals/gg-sports-ca=
mera?p=3D8&utm_source=3Dgg-swarovski-elements-mystery-jewelry-collection&ut=
m_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134c=
f386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=
=3DUS&s=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-deals&utm_campaign=3D96fba5b=
e-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" target=3D"_blank" style=3D"font-s=
ize: 14px !important; line-height: 18px !important; color:#000000 !importan=
t; text-decoration: none;">&nbsp;</a></td> </tr> <tr> <td valign=3D"top" st=
yle=3D"width:290px; min-width:290px; padding-bottom:16px;" class=3D"100"> <=
table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border: 0 n=
one; border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:=
#000000; font-weight: normal; text-align: left; background: #f2f2f2; width:=
290px;" valign=3D"top" width=3D"290" class=3D"container"> <tr> <td style=3D=
"padding: 3px 0 0 16px;" align=3D"left"> <span style=3D"padding: 0 5px 0 0;=
 padding-right: 5px; font-size: 16px; line-height: 20px; text-decoration: l=
ine-through; color:#848484; font-weight: 100;"> $329.99 </span> <span style=
=3D"font-size: 16px; line-height: 20px; font-weight: bold; text-decoration:=
 none; color: #e35205;"> $69.99 </span> </td> </tr> <tr> <td class=3D"nameF=
ont" align=3D"left" valign=3D"top" style=3D"padding: 0px 0px 0px 16px; font=
-family: Helvetica, Arial, sans-serif; font-size: 13px; color: #e35205; tex=
t-decoration: none; font-weight: 500 !important;">Sale Ends 11/12</td> <td =
width=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" style=3D"fo=
nt-family: Helvetica, Arial, sans-serif; padding: 0 16px 0 0; font-size: 13=
px !important; line-height: 17px !important; font-weight: normal; font-weig=
ht: 600; color: #0185c6 !important; text-decoration: none; text-align:right=
; white-space: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-sports-=
camera?p=3D8&utm_source=3Dgg-swarovski-elements-mystery-jewelry-collection&=
utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac13=
4cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&C=
ID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3D96fba5be-9b7b-49e6-=
83e7-b7c7fb9cce33_0_20161111" target=3D"_blank" style=3D"color:#0185c6; tex=
t-decoration:none;"><font color=3D"#0185c6">View&nbsp;Deal</font></a></td> =
</tr> </table> </td> </tr> </table> </td> </tr> </table> </td> </tr> </tabl=
e> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(=
IE)]> <td> <![endif]--> <a href=3D"https://www.groupon.com/deals/gg-picasso=
tiles-3d-magnetic-building-block-sets?p=3D9&utm_source=3Dgg-swarovski-eleme=
nts-mystery-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf5743=
37c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234=
c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm=
_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" target=3D"_bla=
nk" style=3D"color: #000000; font-size: 14px !important; line-height: 18px =
!important; color:#000000 !important; text-decoration: none;"> <table valig=
n=3D"top" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border:=
 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; co=
lor:#000000; font-weight: normal; text-align: left; width:290px; mso-table-=
lspace:0;mso-table-rspace:0;" width=3D"290" align=3D'right' class=3D"contai=
ner"> <tr> <td valign=3D"top" width=3D"100%" style=3D"mso-table-lspace:0;ms=
o-table-rspace:0; width:100%; padding:20px 0 0 0;"> <table cellpadding=3D"0=
" cellspacing=3D"0" border=3D"0" style=3D"width:100%;" width=3D"100%"> <tr>=
 <td valign=3D"top" align=3D"center" width=3D"290" style=3D"width:290px;" c=
lass=3D"container"><a href=3D"https://www.groupon.com/deals/gg-picassotiles=
-3d-magnetic-building-block-sets?p=3D9&utm_source=3Dgg-swarovski-elements-m=
ystery-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c82=
2070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-253=
9-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campa=
ign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" style=3D"display: bl=
ock; border: none;" target=3D"_blank"><img src=3D"https://img.grouponcdn.co=
m/deal/3PVE7E2sWCjyfL8bD393uxaMP36f/3P-1100x660/v1/t300x182.jpg" width=3D"2=
90" style=3D"display: block; border: none; width: 290px;" class=3D"100" alt=
=3D"Picasso Tiles 3D Magnetic Building Block Sets" /></a></td> </tr> <tr> <=
td> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"width:=
100%; background: #f2f2f2;" width=3D"100%"> <tr> <td class=3D"nameFont" sty=
le=3D"padding: 16px 16px 0 16px; font-size: 14px !important; line-height: 1=
8px !important; color:#000000 !important; text-decoration: none; color: #00=
0000;" align=3D"left"> Magnetic Building Block Sets </td> </tr> <tr> <td st=
yle=3D"padding: 0 16px 0 16px;" class=3D"nameFont" align=3D"left"><a href=
=3D"https://www.groupon.com/deals/gg-picassotiles-3d-magnetic-building-bloc=
k-sets?p=3D9&utm_source=3Dgg-swarovski-elements-mystery-jewelry-collection&=
utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac13=
4cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&C=
ID=3DUS&s=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-deals&utm_campaign=3D96fba=
5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" target=3D"_blank" style=3D"font=
-size: 14px !important; line-height: 18px !important; color:#000000 !import=
ant; text-decoration: none;"><font color=3D"#e35205">Over 10,000 bought</fo=
nt></a></td> </tr> <tr> <td valign=3D"top" style=3D"width:290px; min-width:=
290px; padding-bottom:16px;" class=3D"100"> <table cellpadding=3D"0" cellsp=
acing=3D"0" border=3D"0" style=3D"border: 0 none; border-spacing: 0; font-f=
amily: 'Open Sans', Arial, sans-serif; color:#000000; font-weight: normal; =
text-align: left; background: #f2f2f2; width:290px;" valign=3D"top" width=
=3D"290" class=3D"container"> <tr> <td style=3D"padding: 3px 0 0 16px;" ali=
gn=3D"left"> <span style=3D"padding: 0 5px 0 0; padding-right: 5px; font-si=
ze: 16px; line-height: 20px; text-decoration: line-through; color:#848484; =
font-weight: 100;"> $39.99 </span> <span style=3D"font-size: 16px; line-hei=
ght: 20px; font-weight: bold; text-decoration: none; color: #e35205;"> $8.9=
9 </span> </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"=
top" style=3D"padding: 0px 0px 0px 16px; font-family: Helvetica, Arial, san=
s-serif; font-size: 13px; color: #e35205; text-decoration: none; font-weigh=
t: 500 !important;">Sale Ends 11/12</td> <td width=3D"30%" class=3D"nameFon=
t" align=3D"right" valign=3D"top" style=3D"font-family: Helvetica, Arial, s=
ans-serif; padding: 0 16px 0 0; font-size: 13px !important; line-height: 17=
px !important; font-weight: normal; font-weight: 600; color: #0185c6 !impor=
tant; text-decoration: none; text-align:right; white-space: nowrap;"><a hre=
f=3D"https://www.groupon.com/deals/gg-picassotiles-3d-magnetic-building-blo=
ck-sets?p=3D9&utm_source=3Dgg-swarovski-elements-mystery-jewelry-collection=
&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac1=
34cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&=
CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3D96fba5be-9b7b-49e6=
-83e7-b7c7fb9cce33_0_20161111" target=3D"_blank" style=3D"color:#0185c6; te=
xt-decoration:none;"><font color=3D"#0185c6">View&nbsp;Deal</font></a></td>=
 </tr> </table> </td> </tr> </table> </td> </tr> </table> </td> </tr> </tab=
le> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|=
(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </tr> </table> <![endi=
f]--> </td> </tr> <tr> <td valign=3D"top" align=3D"left" width=3D"100%" sty=
le=3D"width: 600px; min-width:600px;" class=3D"100"> <!--[if (gte mso 9)|(I=
E)]> <table width=3D"600" align=3D"center" cellpadding=3D"0" cellspacing=3D=
"0" border=3D"0"> <tr> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endi=
f]--> <a href=3D"https://www.groupon.com/deals/gg-wexley-home-sherpa-comfor=
ter-set?p=3D10&utm_source=3Dgg-swarovski-elements-mystery-jewelry-collectio=
n&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac=
134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe=
&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3D96fba5be-9b7b-49e=
6-83e7-b7c7fb9cce33_0_20161111" target=3D"_blank" style=3D"color: #000000; =
font-size: 14px !important; line-height: 18px !important; color:#000000 !im=
portant; text-decoration: none;"> <table valign=3D"top" cellpadding=3D"0" c=
ellspacing=3D"0" border=3D"0" style=3D"border: 0 none; border-spacing: 0; f=
ont-family: 'Open Sans', Arial, sans-serif; color:#000000; font-weight: nor=
mal; text-align: left; width:290px; mso-table-lspace:0;mso-table-rspace:0;"=
 width=3D"290" align=3D'left' class=3D"container"> <tr> <td valign=3D"top" =
width=3D"100%" style=3D"mso-table-lspace:0;mso-table-rspace:0; width:100%; =
padding:20px 0 0 0;"> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"=
0" style=3D"width:100%;" width=3D"100%"> <tr> <td valign=3D"top" align=3D"c=
enter" width=3D"290" style=3D"width:290px;" class=3D"container"><a href=3D"=
https://www.groupon.com/deals/gg-wexley-home-sherpa-comforter-set?p=3D10&ut=
m_source=3Dgg-swarovski-elements-mystery-jewelry-collection&utm_medium=3Dem=
ail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2=
&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbod=
y&c=3Dimage&d=3DGoods-PN&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce3=
3_0_20161111" style=3D"display: block; border: none;" target=3D"_blank"><im=
g src=3D"https://img.grouponcdn.com/deal/2MGeaYwDzz8ZeNbrAtVf9dw6Evy9/2M-14=
00x840/v1/t300x182.jpg" width=3D"290" style=3D"display: block; border: none=
; width: 290px;" class=3D"100" alt=3D"Wexley Home Sherpa Comforter Set (3-P=
iece)" /></a></td> </tr> <tr> <td> <table cellpadding=3D"0" cellspacing=3D"=
0" border=3D"0" style=3D"width:100%; background: #f2f2f2;" width=3D"100%"> =
<tr> <td class=3D"nameFont" style=3D"padding: 16px 16px 0 16px; font-size: =
14px !important; line-height: 18px !important; color:#000000 !important; te=
xt-decoration: none; color: #000000;" align=3D"left"> Wexley Home Sherpa Co=
mforter Set </td> </tr> <tr> <td style=3D"padding: 0 16px 0 16px;" class=3D=
"nameFont" align=3D"left"><a href=3D"https://www.groupon.com/deals/gg-wexle=
y-home-sherpa-comforter-set?p=3D10&utm_source=3Dgg-swarovski-elements-myste=
ry-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070=
ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11=
e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-deal=
s&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" target=3D=
"_blank" style=3D"font-size: 14px !important; line-height: 18px !important;=
 color:#000000 !important; text-decoration: none;"><font color=3D"#e35205">=
Over 1,000 bought</font></a></td> </tr> <tr> <td valign=3D"top" style=3D"wi=
dth:290px; min-width:290px; padding-bottom:16px;" class=3D"100"> <table cel=
lpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border: 0 none; bord=
er-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#000000; =
font-weight: normal; text-align: left; background: #f2f2f2; width:290px;" v=
align=3D"top" width=3D"290" class=3D"container"> <tr> <td style=3D"padding:=
 3px 0 0 16px;" align=3D"left"> <span style=3D"padding: 0 5px 0 0; padding-=
right: 5px; font-size: 16px; line-height: 20px; text-decoration: line-throu=
gh; color:#848484; font-weight: 100;"> $140 </span> <span style=3D"font-siz=
e: 16px; line-height: 20px; font-weight: bold; text-decoration: none; color=
: #e35205;"> $22.99 </span> </td> </tr> <tr> <td class=3D"nameFont" align=
=3D"left" valign=3D"top" style=3D"padding: 0px 0px 0px 16px; font-family: H=
elvetica, Arial, sans-serif; font-size: 13px; color: #e35205; text-decorati=
on: none; font-weight: 500 !important;">Sale Ends 11/13</td> <td width=3D"3=
0%" class=3D"nameFont" align=3D"right" valign=3D"top" style=3D"font-family:=
 Helvetica, Arial, sans-serif; padding: 0 16px 0 0; font-size: 13px !import=
ant; line-height: 17px !important; font-weight: normal; font-weight: 600; c=
olor: #0185c6 !important; text-decoration: none; text-align:right; white-sp=
ace: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-wexley-home-sherp=
a-comforter-set?p=3D10&utm_source=3Dgg-swarovski-elements-mystery-jewelry-c=
ollection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fb=
f5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-0025=
9069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3D96fba5be-=
9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" target=3D"_blank" style=3D"color:#0=
185c6; text-decoration:none;"><font color=3D"#0185c6">View&nbsp;Deal</font>=
</a></td> </tr> </table> </td> </tr> </table> </td> </tr> </table> </td> </=
tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gt=
e mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https://www.groupon.com/deals/=
gg-form-focus-15l-hydration-backpacks-2?p=3D11&utm_source=3Dgg-swarovski-el=
ements-mystery-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf5=
74337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c=
234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&=
utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" target=3D"_=
blank" style=3D"color: #000000; font-size: 14px !important; line-height: 18=
px !important; color:#000000 !important; text-decoration: none;"> <table va=
lign=3D"top" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"bord=
er: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif;=
 color:#000000; font-weight: normal; text-align: left; width:290px; mso-tab=
le-lspace:0;mso-table-rspace:0;" width=3D"290" align=3D'right' class=3D"con=
tainer"> <tr> <td valign=3D"top" width=3D"100%" style=3D"mso-table-lspace:0=
;mso-table-rspace:0; width:100%; padding:20px 0 0 0;"> <table cellpadding=
=3D"0" cellspacing=3D"0" border=3D"0" style=3D"width:100%;" width=3D"100%">=
 <tr> <td valign=3D"top" align=3D"center" width=3D"290" style=3D"width:290p=
x;" class=3D"container"><a href=3D"https://www.groupon.com/deals/gg-form-fo=
cus-15l-hydration-backpacks-2?p=3D11&utm_source=3Dgg-swarovski-elements-mys=
tery-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c8220=
70ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-=
11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaig=
n=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" style=3D"display: bloc=
k; border: none;" target=3D"_blank"><img src=3D"https://img.grouponcdn.com/=
deal/29gs1zTDynwz7Q7GGyFLE4iNEV4S/29-960x576/v1/t300x182.jpg" width=3D"290"=
 style=3D"display: block; border: none; width: 290px;" class=3D"100" alt=3D=
"Form + Focus 1.5L Hydration Backpacks " /></a></td> </tr> <tr> <td> <table=
 cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"width:100%; back=
ground: #f2f2f2;" width=3D"100%"> <tr> <td class=3D"nameFont" style=3D"padd=
ing: 16px 16px 0 16px; font-size: 14px !important; line-height: 18px !impor=
tant; color:#000000 !important; text-decoration: none; color: #000000;" ali=
gn=3D"left"> Form + Focus Hydration Backpacks </td> </tr> <tr> <td style=3D=
"padding: 0 16px 0 16px;" class=3D"nameFont" align=3D"left"><a href=3D"http=
s://www.groupon.com/deals/gg-form-focus-15l-hydration-backpacks-2?p=3D11&ut=
m_source=3Dgg-swarovski-elements-mystery-jewelry-collection&utm_medium=3Dem=
ail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2=
&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbod=
y&c=3Dbutton&d=3DMindstorm-Hero-3-deals&utm_campaign=3D96fba5be-9b7b-49e6-8=
3e7-b7c7fb9cce33_0_20161111" target=3D"_blank" style=3D"font-size: 14px !im=
portant; line-height: 18px !important; color:#000000 !important; text-decor=
ation: none;"><font color=3D"#e35205">Over 150 bought</font></a></td> </tr>=
 <tr> <td valign=3D"top" style=3D"width:290px; min-width:290px; padding-bot=
tom:16px;" class=3D"100"> <table cellpadding=3D"0" cellspacing=3D"0" border=
=3D"0" style=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans'=
, Arial, sans-serif; color:#000000; font-weight: normal; text-align: left; =
background: #f2f2f2; width:290px;" valign=3D"top" width=3D"290" class=3D"co=
ntainer"> <tr> <td style=3D"padding: 3px 0 0 16px;" align=3D"left"> <span s=
tyle=3D"padding: 0 5px 0 0; padding-right: 5px; font-size: 16px; line-heigh=
t: 20px; text-decoration: line-through; color:#848484; font-weight: 100;"> =
$69.99 </span> <span style=3D"font-size: 16px; line-height: 20px; font-weig=
ht: bold; text-decoration: none; color: #e35205;"> $17.99 </span> </td> </t=
r> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"top" style=3D"paddi=
ng: 0px 0px 0px 16px; font-family: Helvetica, Arial, sans-serif; font-size:=
 13px; color: #e35205; text-decoration: none; font-weight: 500 !important;"=
>Sale Ends 11/13</td> <td width=3D"30%" class=3D"nameFont" align=3D"right" =
valign=3D"top" style=3D"font-family: Helvetica, Arial, sans-serif; padding:=
 0 16px 0 0; font-size: 13px !important; line-height: 17px !important; font=
-weight: normal; font-weight: 600; color: #0185c6 !important; text-decorati=
on: none; text-align:right; white-space: nowrap;"><a href=3D"https://www.gr=
oupon.com/deals/gg-form-focus-15l-hydration-backpacks-2?p=3D11&utm_source=
=3Dgg-swarovski-elements-mystery-jewelry-collection&utm_medium=3Demail&user=
=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D=
20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbu=
tton&d=3DGoods-PN&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_201=
61111" target=3D"_blank" style=3D"color:#0185c6; text-decoration:none;"><fo=
nt color=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </table> </td> </=
tr> </table> </td> </tr> </table> </td> </tr> </table> </a> <!--[if (gte ms=
o 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--=
> <!--[if (gte mso 9)|(IE)]> </tr> </table> <![endif]--> </td> </tr> <tr> <=
td valign=3D"top" align=3D"left" width=3D"100%" style=3D"width: 600px; min-=
width:600px;" class=3D"100"> <!--[if (gte mso 9)|(IE)]> <table width=3D"600=
" align=3D"center" cellpadding=3D"0" cellspacing=3D"0" border=3D"0"> <tr> <=
![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https:/=
/www.groupon.com/deals/gg-best-of-chi-flat-irons?p=3D12&utm_source=3Dgg-swa=
rovski-elements-mystery-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7=
c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&=
uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3D=
Goods-PN&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" ta=
rget=3D"_blank" style=3D"color: #000000; font-size: 14px !important; line-h=
eight: 18px !important; color:#000000 !important; text-decoration: none;"> =
<table valign=3D"top" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" styl=
e=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, sa=
ns-serif; color:#000000; font-weight: normal; text-align: left; width:290px=
; mso-table-lspace:0;mso-table-rspace:0;" width=3D"290" align=3D'left' clas=
s=3D"container"> <tr> <td valign=3D"top" width=3D"100%" style=3D"mso-table-=
lspace:0;mso-table-rspace:0; width:100%; padding:20px 0 0 0;"> <table cellp=
adding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"width:100%;" width=3D"=
100%"> <tr> <td valign=3D"top" align=3D"center" width=3D"290" style=3D"widt=
h:290px;" class=3D"container"><a href=3D"https://www.groupon.com/deals/gg-b=
est-of-chi-flat-irons?p=3D12&utm_source=3Dgg-swarovski-elements-mystery-jew=
elry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8=
f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c=
0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3D96fb=
a5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" style=3D"display: block; borde=
r: none;" target=3D"_blank"><img src=3D"https://img.grouponcdn.com/deal/2R5=
2WFKT1vQ5bhyuBuvT5qmUi3FN/2R-2048x1229/v1/t300x182.jpg" width=3D"290" style=
=3D"display: block; border: none; width: 290px;" class=3D"100" alt=3D"Best =
of CHI Irons and Hair Treatments" /></a></td> </tr> <tr> <td> <table cellpa=
dding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"width:100%; background:=
 #f2f2f2;" width=3D"100%"> <tr> <td class=3D"nameFont" style=3D"padding: 16=
px 16px 0 16px; font-size: 14px !important; line-height: 18px !important; c=
olor:#000000 !important; text-decoration: none; color: #000000;" align=3D"l=
eft"> CHI Irons and Hair Treatments </td> </tr> <tr> <td style=3D"padding: =
0 16px 0 16px;" class=3D"nameFont" align=3D"left"><a href=3D"https://www.gr=
oupon.com/deals/gg-best-of-chi-flat-irons?p=3D12&utm_source=3Dgg-swarovski-=
elements-mystery-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03c=
f574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df7=
9c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DMindsto=
rm-Hero-3-deals&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161=
111" target=3D"_blank" style=3D"font-size: 14px !important; line-height: 18=
px !important; color:#000000 !important; text-decoration: none;"><font colo=
r=3D"#e35205">Over 100 bought</font></a></td> </tr> <tr> <td valign=3D"top"=
 style=3D"width:290px; min-width:290px; padding-bottom:16px;" class=3D"100"=
> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border: =
0 none; border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; col=
or:#000000; font-weight: normal; text-align: left; background: #f2f2f2; wid=
th:290px;" valign=3D"top" width=3D"290" class=3D"container"> <tr> <td style=
=3D"padding: 3px 0 0 16px;" align=3D"left"> <span style=3D"padding: 0 5px 0=
 0; padding-right: 5px; font-size: 16px; line-height: 20px; text-decoration=
: line-through; color:#848484; font-weight: 100;"> $14.99 </span> <span sty=
le=3D"font-size: 16px; line-height: 20px; font-weight: bold; text-decoratio=
n: none; color: #e35205;"> $11.99 </span> </td> </tr> <tr> <td class=3D"nam=
eFont" align=3D"left" valign=3D"top" style=3D"padding: 0px 0px 0px 16px; fo=
nt-family: Helvetica, Arial, sans-serif; font-size: 13px; color: #e35205; t=
ext-decoration: none; font-weight: 500 !important;">Sale Ends 11/12</td> <t=
d width=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" style=3D"=
font-family: Helvetica, Arial, sans-serif; padding: 0 16px 0 0; font-size: =
13px !important; line-height: 17px !important; font-weight: normal; font-we=
ight: 600; color: #0185c6 !important; text-decoration: none; text-align:rig=
ht; white-space: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-best-=
of-chi-flat-irons?p=3D12&utm_source=3Dgg-swarovski-elements-mystery-jewelry=
-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806=
fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00=
259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3D96fba5b=
e-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" target=3D"_blank" style=3D"color:=
#0185c6; text-decoration:none;"><font color=3D"#0185c6">View&nbsp;Deal</fon=
t></a></td> </tr> </table> </td> </tr> </table> </td> </tr> </table> </td> =
</tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (=
gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https://www.groupon.com/deal=
s/gg-sabatier-air-fryer?p=3D13&utm_source=3Dgg-swarovski-elements-mystery-j=
ewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1e=
d8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-8=
2c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3D9=
6fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" target=3D"_blank" style=3D"=
color: #000000; font-size: 14px !important; line-height: 18px !important; c=
olor:#000000 !important; text-decoration: none;"> <table valign=3D"top" cel=
lpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border: 0 none; bord=
er-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#000000; =
font-weight: normal; text-align: left; width:290px; mso-table-lspace:0;mso-=
table-rspace:0;" width=3D"290" align=3D'right' class=3D"container"> <tr> <t=
d valign=3D"top" width=3D"100%" style=3D"mso-table-lspace:0;mso-table-rspac=
e:0; width:100%; padding:20px 0 0 0;"> <table cellpadding=3D"0" cellspacing=
=3D"0" border=3D"0" style=3D"width:100%;" width=3D"100%"> <tr> <td valign=
=3D"top" align=3D"center" width=3D"290" style=3D"width:290px;" class=3D"con=
tainer"><a href=3D"https://www.groupon.com/deals/gg-sabatier-air-fryer?p=3D=
13&utm_source=3Dgg-swarovski-elements-mystery-jewelry-collection&utm_medium=
=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561e=
d8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=
=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7f=
b9cce33_0_20161111" style=3D"display: block; border: none;" target=3D"_blan=
k"><img src=3D"https://img.grouponcdn.com/deal/j7tiK1v5zzsDzTgAzqdQ7fJef9K/=
j7-1800x1080/v1/t300x182.jpg" width=3D"290" style=3D"display: block; border=
: none; width: 290px;" class=3D"100" alt=3D"Momento 2.5-Liter Air Fryer " /=
></a></td> </tr> <tr> <td> <table cellpadding=3D"0" cellspacing=3D"0" borde=
r=3D"0" style=3D"width:100%; background: #f2f2f2;" width=3D"100%"> <tr> <td=
 class=3D"nameFont" style=3D"padding: 16px 16px 0 16px; font-size: 14px !im=
portant; line-height: 18px !important; color:#000000 !important; text-decor=
ation: none; color: #000000;" align=3D"left"> Momento 2.5-Liter Air Fryer <=
/td> </tr> <tr> <td style=3D"background: #f2f2f2;" valign=3D"top"><a href=
=3D"https://www.groupon.com/deals/gg-sabatier-air-fryer?p=3D13&utm_source=
=3Dgg-swarovski-elements-mystery-jewelry-collection&utm_medium=3Demail&user=
=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D=
20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbu=
tton&d=3DMindstorm-Hero-3-deals&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7=
fb9cce33_0_20161111" target=3D"_blank" style=3D"font-size: 14px !important;=
 line-height: 18px !important; color:#000000 !important; text-decoration: n=
one;">&nbsp;</a></td> </tr> <tr> <td valign=3D"top" style=3D"width:290px; m=
in-width:290px; padding-bottom:16px;" class=3D"100"> <table cellpadding=3D"=
0" cellspacing=3D"0" border=3D"0" style=3D"border: 0 none; border-spacing: =
0; font-family: 'Open Sans', Arial, sans-serif; color:#000000; font-weight:=
 normal; text-align: left; background: #f2f2f2; width:290px;" valign=3D"top=
" width=3D"290" class=3D"container"> <tr> <td style=3D"padding: 3px 0 0 16p=
x;" align=3D"left"> <span style=3D"padding: 0 5px 0 0; padding-right: 5px; =
font-size: 16px; line-height: 20px; text-decoration: line-through; color:#8=
48484; font-weight: 100;"> $129.99 </span> <span style=3D"font-size: 16px; =
line-height: 20px; font-weight: bold; text-decoration: none; color: #e35205=
;"> $59.99 </span> </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" v=
align=3D"top" style=3D"padding: 0px 0px 0px 16px; font-family: Helvetica, A=
rial, sans-serif; font-size: 13px; color: #e35205; text-decoration: none; f=
ont-weight: 500 !important;">Sale Ends 11/12</td> <td width=3D"30%" class=
=3D"nameFont" align=3D"right" valign=3D"top" style=3D"font-family: Helvetic=
a, Arial, sans-serif; padding: 0 16px 0 0; font-size: 13px !important; line=
-height: 17px !important; font-weight: normal; font-weight: 600; color: #01=
85c6 !important; text-decoration: none; text-align:right; white-space: nowr=
ap;"><a href=3D"https://www.groupon.com/deals/gg-sabatier-air-fryer?p=3D13&=
utm_source=3Dgg-swarovski-elements-mystery-jewelry-collection&utm_medium=3D=
email&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8c=
d2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Db=
ody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9c=
ce33_0_20161111" target=3D"_blank" style=3D"color:#0185c6; text-decoration:=
none;"><font color=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </table=
> </td> </tr> </table> </td> </tr> </table> </td> </tr> </table> </a> <!--[=
if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </td> <=
![endif]--> <!--[if (gte mso 9)|(IE)]> </tr> </table> <![endif]--> </td> </=
tr> <tr> <td valign=3D"top" align=3D"left" width=3D"100%" style=3D"width: 6=
00px; min-width:600px;" class=3D"100"> <!--[if (gte mso 9)|(IE)]> <table wi=
dth=3D"600" align=3D"center" cellpadding=3D"0" cellspacing=3D"0" border=3D"=
0"> <tr> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=
=3D"https://www.groupon.com/deals/gg-mens-wallets-money-clips?p=3D14&utm_so=
urce=3Dgg-swarovski-elements-mystery-jewelry-collection&utm_medium=3Demail&=
user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&dat=
e=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=
=3Dbutton&d=3DGoods-PN&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_=
0_20161111" target=3D"_blank" style=3D"color: #000000; font-size: 14px !imp=
ortant; line-height: 18px !important; color:#000000 !important; text-decora=
tion: none;"> <table valign=3D"top" cellpadding=3D"0" cellspacing=3D"0" bor=
der=3D"0" style=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sa=
ns', Arial, sans-serif; color:#000000; font-weight: normal; text-align: lef=
t; width:290px; mso-table-lspace:0;mso-table-rspace:0;" width=3D"290" align=
=3D'left' class=3D"container"> <tr> <td valign=3D"top" width=3D"100%" style=
=3D"mso-table-lspace:0;mso-table-rspace:0; width:100%; padding:20px 0 0 0;"=
> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"width:10=
0%;" width=3D"100%"> <tr> <td valign=3D"top" align=3D"center" width=3D"290"=
 style=3D"width:290px;" class=3D"container"><a href=3D"https://www.groupon.=
com/deals/gg-mens-wallets-money-clips?p=3D14&utm_source=3Dgg-swarovski-elem=
ents-mystery-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574=
337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c23=
4c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm=
_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" style=3D"displ=
ay: block; border: none;" target=3D"_blank"><img src=3D"https://img.groupon=
cdn.com/deal/2mGbuV7xPNdYi8wE9izWr3BohL8m/2m-1400x840/v1/t300x182.jpg" widt=
h=3D"290" style=3D"display: block; border: none; width: 290px;" class=3D"10=
0" alt=3D"Alpine Swiss Leather Men's Wallets & Money Clips" /></a></td> </t=
r> <tr> <td> <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=
=3D"width:100%; background: #f2f2f2;" width=3D"100%"> <tr> <td class=3D"nam=
eFont" style=3D"padding: 16px 16px 0 16px; font-size: 14px !important; line=
-height: 18px !important; color:#000000 !important; text-decoration: none; =
color: #000000;" align=3D"left"> Men's Wallets & Money Clips </td> </tr> <t=
r> <td style=3D"padding: 0 16px 0 16px;" class=3D"nameFont" align=3D"left">=
<a href=3D"https://www.groupon.com/deals/gg-mens-wallets-money-clips?p=3D14=
&utm_source=3Dgg-swarovski-elements-mystery-jewelry-collection&utm_medium=
=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561e=
d8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=
=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-deals&utm_campaign=3D96fba5be-9b7b-=
49e6-83e7-b7c7fb9cce33_0_20161111" target=3D"_blank" style=3D"font-size: 14=
px !important; line-height: 18px !important; color:#000000 !important; text=
-decoration: none;"><font color=3D"#e35205">Over 1,000 bought</font></a></t=
d> </tr> <tr> <td valign=3D"top" style=3D"width:290px; min-width:290px; pad=
ding-bottom:16px;" class=3D"100"> <table cellpadding=3D"0" cellspacing=3D"0=
" border=3D"0" style=3D"border: 0 none; border-spacing: 0; font-family: 'Op=
en Sans', Arial, sans-serif; color:#000000; font-weight: normal; text-align=
: left; background: #f2f2f2; width:290px;" valign=3D"top" width=3D"290" cla=
ss=3D"container"> <tr> <td style=3D"padding: 3px 0 0 16px;" align=3D"left">=
 <span style=3D"padding: 0 5px 0 0; padding-right: 5px; font-size: 16px; li=
ne-height: 20px; text-decoration: line-through; color:#848484; font-weight:=
 100;"> $27.50 </span> <span style=3D"font-size: 16px; line-height: 20px; f=
ont-weight: bold; text-decoration: none; color: #e35205;"> $7.99 </span> </=
td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"top" style=
=3D"padding: 0px 0px 0px 16px; font-family: Helvetica, Arial, sans-serif; f=
ont-size: 13px; color: #e35205; text-decoration: none; font-weight: 500 !im=
portant;">Sale Ends 11/12</td> <td width=3D"30%" class=3D"nameFont" align=
=3D"right" valign=3D"top" style=3D"font-family: Helvetica, Arial, sans-seri=
f; padding: 0 16px 0 0; font-size: 13px !important; line-height: 17px !impo=
rtant; font-weight: normal; font-weight: 600; color: #0185c6 !important; te=
xt-decoration: none; text-align:right; white-space: nowrap;"><a href=3D"htt=
ps://www.groupon.com/deals/gg-mens-wallets-money-clips?p=3D14&utm_source=3D=
gg-swarovski-elements-mystery-jewelry-collection&utm_medium=3Demail&user=3D=
d8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D201=
61111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutto=
n&d=3DGoods-PN&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_201611=
11" target=3D"_blank" style=3D"color:#0185c6; text-decoration:none;"><font =
color=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </table> </td> </tr>=
 </table> </td> </tr> </table> </td> </tr> </table> </a> <!--[if (gte mso 9=
)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a=
 href=3D"https://www.groupon.com/deals/gg-world-tech-toys-tool-swat-cash-re=
gister-bbq-grill-kitchen-play?p=3D15&utm_source=3Dgg-swarovski-elements-mys=
tery-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c8220=
70ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-=
11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campai=
gn=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" target=3D"_blank" sty=
le=3D"color: #000000; font-size: 14px !important; line-height: 18px !import=
ant; color:#000000 !important; text-decoration: none;"> <table valign=3D"to=
p" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border: 0 none=
; border-spacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#00=
0000; font-weight: normal; text-align: left; width:290px; mso-table-lspace:=
0;mso-table-rspace:0;" width=3D"290" align=3D'right' class=3D"container"> <=
tr> <td valign=3D"top" width=3D"100%" style=3D"mso-table-lspace:0;mso-table=
-rspace:0; width:100%; padding:20px 0 0 0;"> <table cellpadding=3D"0" cells=
pacing=3D"0" border=3D"0" style=3D"width:100%;" width=3D"100%"> <tr> <td va=
lign=3D"top" align=3D"center" width=3D"290" style=3D"width:290px;" class=3D=
"container"><a href=3D"https://www.groupon.com/deals/gg-world-tech-toys-too=
l-swat-cash-register-bbq-grill-kitchen-play?p=3D15&utm_source=3Dgg-swarovsk=
i-elements-mystery-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf0=
3cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3D=
f79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=3DGoods-=
PN&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" style=3D=
"display: block; border: none;" target=3D"_blank"><img src=3D"https://img.g=
rouponcdn.com/deal/2nLuRPHnLh6k5tcEytBr391HSChJ/2n-1500x900/v1/t300x182.jpg=
" width=3D"290" style=3D"display: block; border: none; width: 290px;" class=
=3D"100" alt=3D"World Tech Toys Kids' Playsets" /></a></td> </tr> <tr> <td>=
 <table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"width:100=
%; background: #f2f2f2;" width=3D"100%"> <tr> <td class=3D"nameFont" style=
=3D"padding: 16px 16px 0 16px; font-size: 14px !important; line-height: 18p=
x !important; color:#000000 !important; text-decoration: none; color: #0000=
00;" align=3D"left"> World Tech Toys Kids' Playsets </td> </tr> <tr> <td st=
yle=3D"padding: 0 16px 0 16px;" class=3D"nameFont" align=3D"left"><a href=
=3D"https://www.groupon.com/deals/gg-world-tech-toys-tool-swat-cash-registe=
r-bbq-grill-kitchen-play?p=3D15&utm_source=3Dgg-swarovski-elements-mystery-=
jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1=
ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-=
82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-deals&u=
tm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" target=3D"_b=
lank" style=3D"font-size: 14px !important; line-height: 18px !important; co=
lor:#000000 !important; text-decoration: none;"><font color=3D"#e35205">Ove=
r 650 bought</font></a></td> </tr> <tr> <td valign=3D"top" style=3D"width:2=
90px; min-width:290px; padding-bottom:16px;" class=3D"100"> <table cellpadd=
ing=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border: 0 none; border-sp=
acing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#000000; font-=
weight: normal; text-align: left; background: #f2f2f2; width:290px;" valign=
=3D"top" width=3D"290" class=3D"container"> <tr> <td style=3D"padding: 3px =
0 0 16px;" align=3D"left"> <span style=3D"padding: 0 5px 0 0; padding-right=
: 5px; font-size: 16px; line-height: 20px; text-decoration: line-through; c=
olor:#848484; font-weight: 100;"> $89.99 </span> <span style=3D"font-size: =
16px; line-height: 20px; font-weight: bold; text-decoration: none; color: #=
e35205;"> $27.99 </span> </td> </tr> <tr> <td class=3D"nameFont" align=3D"l=
eft" valign=3D"top" style=3D"padding: 0px 0px 0px 16px; font-family: Helvet=
ica, Arial, sans-serif; font-size: 13px; color: #e35205; text-decoration: n=
one; font-weight: 500 !important;">Sale Ends 11/12</td> <td width=3D"30%" c=
lass=3D"nameFont" align=3D"right" valign=3D"top" style=3D"font-family: Helv=
etica, Arial, sans-serif; padding: 0 16px 0 0; font-size: 13px !important; =
line-height: 17px !important; font-weight: normal; font-weight: 600; color:=
 #0185c6 !important; text-decoration: none; text-align:right; white-space: =
nowrap;"><a href=3D"https://www.groupon.com/deals/gg-world-tech-toys-tool-s=
wat-cash-register-bbq-grill-kitchen-play?p=3D15&utm_source=3Dgg-swarovski-e=
lements-mystery-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf=
574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79=
c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN=
&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" target=3D"=
_blank" style=3D"color:#0185c6; text-decoration:none;"><font color=3D"#0185=
c6">View&nbsp;Deal</font></a></td> </tr> </table> </td> </tr> </table> </td=
> </tr> </table> </td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td>=
 <![endif]--> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte ms=
o 9)|(IE)]> </tr> </table> <![endif]--> </td> </tr> <tr> <td valign=3D"top"=
 align=3D"left" width=3D"100%" style=3D"width: 600px; min-width:600px;" cla=
ss=3D"100"> <!--[if (gte mso 9)|(IE)]> <table width=3D"600" align=3D"center=
" cellpadding=3D"0" cellspacing=3D"0" border=3D"0"> <tr> <![endif]--> <!--[=
if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https://www.groupon.com/=
deals/gg-balmer-db9-mens-swiss-luxury-watch?p=3D16&utm_source=3Dgg-swarovsk=
i-elements-mystery-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf0=
3cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3D=
f79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods=
-PN&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" target=
=3D"_blank" style=3D"color: #000000; font-size: 14px !important; line-heigh=
t: 18px !important; color:#000000 !important; text-decoration: none;"> <tab=
le valign=3D"top" cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D=
"border: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, sans-s=
erif; color:#000000; font-weight: normal; text-align: left; width:290px; ms=
o-table-lspace:0;mso-table-rspace:0;" width=3D"290" align=3D'left' class=3D=
"container"> <tr> <td valign=3D"top" width=3D"100%" style=3D"mso-table-lspa=
ce:0;mso-table-rspace:0; width:100%; padding:20px 0 0 0;"> <table cellpaddi=
ng=3D"0" cellspacing=3D"0" border=3D"0" style=3D"width:100%;" width=3D"100%=
"> <tr> <td valign=3D"top" align=3D"center" width=3D"290" style=3D"width:29=
0px;" class=3D"container"><a href=3D"https://www.groupon.com/deals/gg-balme=
r-db9-mens-swiss-luxury-watch?p=3D16&utm_source=3Dgg-swarovski-elements-mys=
tery-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c8220=
70ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-=
11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaig=
n=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" style=3D"display: bloc=
k; border: none;" target=3D"_blank"><img src=3D"https://img.grouponcdn.com/=
deal/2si9oPJJU2x4ubbAiCEm6SYHziii/2s-2048x1229/v1/t300x182.jpg" width=3D"29=
0" style=3D"display: block; border: none; width: 290px;" class=3D"100" alt=
=3D"Balmer DB9 Men's Swiss Luxury Watch" /></a></td> </tr> <tr> <td> <table=
 cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"width:100%; back=
ground: #f2f2f2;" width=3D"100%"> <tr> <td class=3D"nameFont" style=3D"padd=
ing: 16px 16px 0 16px; font-size: 14px !important; line-height: 18px !impor=
tant; color:#000000 !important; text-decoration: none; color: #000000;" ali=
gn=3D"left"> Balmer Men's Swiss Luxury Watch </td> </tr> <tr> <td style=3D"=
background: #f2f2f2;" valign=3D"top"><a href=3D"https://www.groupon.com/dea=
ls/gg-balmer-db9-mens-swiss-luxury-watch?p=3D16&utm_source=3Dgg-swarovski-e=
lements-mystery-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf=
574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79=
c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DMindstor=
m-Hero-3-deals&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_201611=
11" target=3D"_blank" style=3D"font-size: 14px !important; line-height: 18p=
x !important; color:#000000 !important; text-decoration: none;">&nbsp;</a><=
/td> </tr> <tr> <td valign=3D"top" style=3D"width:290px; min-width:290px; p=
adding-bottom:16px;" class=3D"100"> <table cellpadding=3D"0" cellspacing=3D=
"0" border=3D"0" style=3D"border: 0 none; border-spacing: 0; font-family: '=
Open Sans', Arial, sans-serif; color:#000000; font-weight: normal; text-ali=
gn: left; background: #f2f2f2; width:290px;" valign=3D"top" width=3D"290" c=
lass=3D"container"> <tr> <td style=3D"padding: 3px 0 0 16px;" align=3D"left=
"> <span style=3D"padding: 0 5px 0 0; padding-right: 5px; font-size: 16px; =
line-height: 20px; text-decoration: line-through; color:#848484; font-weigh=
t: 100;"> $999 </span> <span style=3D"font-size: 16px; line-height: 20px; f=
ont-weight: bold; text-decoration: none; color: #e35205;"> $99.99 </span> <=
/td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"top" style=
=3D"padding: 0px 0px 0px 16px; font-family: Helvetica, Arial, sans-serif; f=
ont-size: 13px; color: #e35205; text-decoration: none; font-weight: 500 !im=
portant;">Sale Ends 11/14</td> <td width=3D"30%" class=3D"nameFont" align=
=3D"right" valign=3D"top" style=3D"font-family: Helvetica, Arial, sans-seri=
f; padding: 0 16px 0 0; font-size: 13px !important; line-height: 17px !impo=
rtant; font-weight: normal; font-weight: 600; color: #0185c6 !important; te=
xt-decoration: none; text-align:right; white-space: nowrap;"><a href=3D"htt=
ps://www.groupon.com/deals/gg-balmer-db9-mens-swiss-luxury-watch?p=3D16&utm=
_source=3Dgg-swarovski-elements-mystery-jewelry-collection&utm_medium=3Dema=
il&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&=
date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody=
&c=3Dbutton&d=3DGoods-PN&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce3=
3_0_20161111" target=3D"_blank" style=3D"color:#0185c6; text-decoration:non=
e;"><font color=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </table> <=
/td> </tr> </table> </td> </tr> </table> </td> </tr> </table> </a> <!--[if =
(gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![en=
dif]--> <a href=3D"https://www.groupon.com/deals/gg-samsung-galaxy-s5-16gb-=
4g-lte-smartphone-1?p=3D17&utm_source=3Dgg-swarovski-elements-mystery-jewel=
ry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f8=
06fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-=
00259069d5fe&CID=3DUS&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3D96fba=
5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" target=3D"_blank" style=3D"colo=
r: #000000; font-size: 14px !important; line-height: 18px !important; color=
:#000000 !important; text-decoration: none;"> <table valign=3D"top" cellpad=
ding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"border: 0 none; border-s=
pacing: 0; font-family: 'Open Sans', Arial, sans-serif; color:#000000; font=
-weight: normal; text-align: left; width:290px; mso-table-lspace:0;mso-tabl=
e-rspace:0;" width=3D"290" align=3D'right' class=3D"container"> <tr> <td va=
lign=3D"top" width=3D"100%" style=3D"mso-table-lspace:0;mso-table-rspace:0;=
 width:100%; padding:20px 0 0 0;"> <table cellpadding=3D"0" cellspacing=3D"=
0" border=3D"0" style=3D"width:100%;" width=3D"100%"> <tr> <td valign=3D"to=
p" align=3D"center" width=3D"290" style=3D"width:290px;" class=3D"container=
"><a href=3D"https://www.groupon.com/deals/gg-samsung-galaxy-s5-16gb-4g-lte=
-smartphone-1?p=3D17&utm_source=3Dgg-swarovski-elements-mystery-jewelry-col=
lection&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5=
c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-002590=
69d5fe&CID=3DUS&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3D96fba5be-9b7=
b-49e6-83e7-b7c7fb9cce33_0_20161111" style=3D"display: block; border: none;=
" target=3D"_blank"><img src=3D"https://img.grouponcdn.com/deal/72D2jsUVDMk=
eiPZCH7Nx/eK-700x420/v1/t300x182.jpg" width=3D"290" style=3D"display: block=
; border: none; width: 290px;" class=3D"100" alt=3D"Samsung Galaxy S5 16GB =
4G LTE Smartphone for Verizon (GSM Unlocked)" /></a></td> </tr> <tr> <td> <=
table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" style=3D"width:100%;=
 background: #f2f2f2;" width=3D"100%"> <tr> <td class=3D"nameFont" style=3D=
"padding: 16px 16px 0 16px; font-size: 14px !important; line-height: 18px !=
important; color:#000000 !important; text-decoration: none; color: #000000;=
" align=3D"left"> Samsung Galaxy S5 16GB </td> </tr> <tr> <td style=3D"padd=
ing: 0 16px 0 16px;" class=3D"nameFont" align=3D"left"><a href=3D"https://w=
ww.groupon.com/deals/gg-samsung-galaxy-s5-16gb-4g-lte-smartphone-1?p=3D17&u=
tm_source=3Dgg-swarovski-elements-mystery-jewelry-collection&utm_medium=3De=
mail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd=
2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbo=
dy&c=3Dbutton&d=3DMindstorm-Hero-3-deals&utm_campaign=3D96fba5be-9b7b-49e6-=
83e7-b7c7fb9cce33_0_20161111" target=3D"_blank" style=3D"font-size: 14px !i=
mportant; line-height: 18px !important; color:#000000 !important; text-deco=
ration: none;"><font color=3D"#e35205">Over 1,000 bought</font></a></td> </=
tr> <tr> <td valign=3D"top" style=3D"width:290px; min-width:290px; padding-=
bottom:16px;" class=3D"100"> <table cellpadding=3D"0" cellspacing=3D"0" bor=
der=3D"0" style=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sa=
ns', Arial, sans-serif; color:#000000; font-weight: normal; text-align: lef=
t; background: #f2f2f2; width:290px;" valign=3D"top" width=3D"290" class=3D=
"container"> <tr> <td style=3D"padding: 3px 0 0 16px;" align=3D"left"> <spa=
n style=3D"padding: 0 5px 0 0; padding-right: 5px; font-size: 16px; line-he=
ight: 20px; text-decoration: line-through; color:#848484; font-weight: 100;=
"> $552 </span> <span style=3D"font-size: 16px; line-height: 20px; font-wei=
ght: bold; text-decoration: none; color: #e35205;"> $129.99 </span> </td> <=
/tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"top" style=3D"pad=
ding: 0px 0px 0px 16px; font-family: Helvetica, Arial, sans-serif; font-siz=
e: 13px; color: #e35205; text-decoration: none; font-weight: 500 !important=
;">Sale Ends 11/14</td> <td width=3D"30%" class=3D"nameFont" align=3D"right=
" valign=3D"top" style=3D"font-family: Helvetica, Arial, sans-serif; paddin=
g: 0 16px 0 0; font-size: 13px !important; line-height: 17px !important; fo=
nt-weight: normal; font-weight: 600; color: #0185c6 !important; text-decora=
tion: none; text-align:right; white-space: nowrap;"><a href=3D"https://www.=
groupon.com/deals/gg-samsung-galaxy-s5-16gb-4g-lte-smartphone-1?p=3D17&utm_=
source=3Dgg-swarovski-elements-mystery-jewelry-collection&utm_medium=3Demai=
l&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&d=
ate=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dbody&=
c=3Dbutton&d=3DGoods-PN&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33=
_0_20161111" target=3D"_blank" style=3D"color:#0185c6; text-decoration:none=
;"><font color=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </table> </=
td> </tr> </table> </td> </tr> </table> </td> </tr> </table> </a> <!--[if (=
gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </td> <![en=
dif]--> <!--[if (gte mso 9)|(IE)]> </tr> </table> <![endif]--> </td> </tr> =
</table> </td> </tr> </table> <table cellpadding=3D"0" cellspacing=3D"0" st=
yle=3D"border: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, =
sans-serif; color:#000000; font-weight: normal; text-align: left; width: 60=
0px;" align=3D"center" class=3D"container"> <tr> <td style=3D"padding: 30px=
;" align=3D"center"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"bo=
rder: 0 none; border-spacing:0; font-family: 'HelveticaNeue', 'Helvetica Ne=
ue', Helvetica, Arial, 'Lucida Grande', sans-serif; color:#000000; text-ali=
gn: left; width:200px;" align=3D"center"> <tr> <td height=3D"45" bgcolor=3D=
"#3ebddc" background=3D"http://s3.grouponcdn.com/email/images/prom_night/gl=
obal_buttons/pn-btn-gradient-blue.gif" background-repeat=3D"repeat-x" style=
=3D"height:45px; text-align:center;"><a href=3D"http://www.groupon.com/good=
s?utm_source=3Dgg-swarovski-elements-mystery-jewelry-collection&utm_medium=
=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561e=
d8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=
=3Dbody&c=3Dbutton&d=3DGoods&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9=
cce33_0_20161111" style=3D"padding: 10px; color:#ffffff; font-size:16px; fo=
nt-weight: 500; text-decoration:none;">VIEW&nbsp;ALL&nbsp;GOODS</a></td> </=
tr> </table> </td> </tr> </table> </td> </tr> </table> </td> </tr> </table>=
 </td> </tr> </table> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"b=
order: 0 none; border-spacing: 0; font-family: 'Open Sans', Arial, sans-ser=
if; color:#000000; font-weight: normal; text-align: left; width: 100%; back=
ground: #f2f2f2;" align=3D"center" class=3D"container"> <tr> <td align=3D"c=
enter" style=3D"padding: 30px 0 0 0;"> <table cellpadding=3D"0" cellspacing=
=3D"0" style=3D"width: 600px; background: #f2f2f2;" align=3D"center" class=
=3D"container" width=3D"600"> <tr> <td style=3D"font-size: 16px; color: #88=
8888; line-height: 119%; padding: 10px 10px 10px 10px;" align=3D"center">Ne=
ed help? Have feedback? Feel free to <a href=3D"http://www.groupon.com/cust=
omer_support?utm_source=3Dgg-swarovski-elements-mystery-jewelry-collection&=
utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac13=
4cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&C=
ID=3DUS&s=3Dfooter&c=3Dlink&d=3Dsupport&utm_campaign=3D96fba5be-9b7b-49e6-8=
3e7-b7c7fb9cce33_0_20161111" style=3D"color:#0185C6; text-decoration:none;"=
 target=3D"_blank">contact us</a></td> </tr> <tr> <td style=3D"font-size: 1=
0px; color: #999999; line-height: 120%; padding: 10px 10px 0 10px;" align=
=3D"center" class=3D"mobile-font">Delivered by Groupon Inc. 600 W. Chicago =
Avenue, Suite 400 Chicago, IL, 60654, USA</td> </tr> <tr> <td style=3D"font=
-size: 10px; color: #999999; line-height: 120%; padding: 0 10px 10px 10px;"=
 align=3D"center" class=3D"mobile-font">You are receiving this email becaus=
e kyle@kylefisher.com is signed up to receive Groupon communications. To ad=
just how often you receive Groupon emails, including unsubscribing, <a href=
=3D"https://www.groupon.com/subscription_center/manage/consumer/f79c234c-25=
39-11e2-82c0-00259069d5fe?cmplistId=3Dchannel:goods&utm_source=3Dgg-swarovs=
ki-elements-mystery-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf=
03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=
=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&s=3Dfooter&c=3Dlink&d=3Dun=
subscribe&utm_campaign=3D96fba5be-9b7b-49e6-83e7-b7c7fb9cce33_0_20161111" s=
tyle=3D"color:#0185C6; text-decoration:none;">click here</a></td> </tr> </t=
able> </td> </tr> </table> <img src =3D "http://www.groupon.com/analytic/tr=
ack.gif?p=3D2&utm_domain=3Dkylefisher.com&utm_campaign=3D96fba5be-9b7b-49e6=
-83e7-b7c7fb9cce33_0_20161111&deals=3D445d7888-960c-11e6-851f-00259069d7cc,=
19eddaca-8400-11e6-a980-00259069d7cc,a08a7bf0-88e3-11e6-985f-00259069d868,7=
8591936-9007-11e6-870d-00259069d868,01d12c81-7de6-4538-9c50-4c6a3f8d876a,66=
23ff4a-8bd6-11e6-aee2-00259060b5da,e9d59326-6a5c-11e6-aa0d-00259069d7cc,b1f=
159ce-37dd-11e6-ad91-002590604002,b6d82863-b64e-43fa-8ab1-7a9ffabe9b43,ce9e=
9670-e901-4517-be39-f072faedf6ad,43efa2a6-6291-49ee-a1aa-b62a12656eda,703f1=
c64-fdef-4761-8443-a8250a946e61,08c4b6f6-90d5-11e6-b2a2-002590604002,503c69=
bc-8b61-11e6-89fc-00259069d868,a27290a8-97cd-11e6-9721-00259069d868,76fa84a=
4-6adb-11e6-84bb-00259069d7cc&channel_deals=3Dnull&utm_source=3Dgg-swarovsk=
i-elements-mystery-jewelry-collection&utm_medium=3Demail&user=3Dd8bfd7c8bf0=
3cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3D=
f79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS" height=3D"1" width=3D"1" sty=
le=3D"display: none !important;" /> </body> </html>

