From bounce-119_HTML-234621346-1218565-6157178-5339@bounce.email.gopro.com Fri Nov 11 18:19:33 2016
Received: from mta2.email.gopro.com ([198.245.80.1]:37188)
	by ecbiz209.inmotionhosting.com with esmtp (Exim 4.87)
	(envelope-from <bounce-119_HTML-234621346-1218565-6157178-5339@bounce.email.gopro.com>)
	id 1c5L6b-002LVC-90
	for kyle@kylefisher.com; Fri, 11 Nov 2016 18:19:33 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; s=200608; d=email.gopro.com;
 h=From:To:Subject:Date:List-Unsubscribe:MIME-Version:Reply-To:List-ID:Message-ID:Content-Type; i=GoPro@email.gopro.com;
 bh=ZG/5coB6VuFfOA2fcmnkNdvyqFk=;
 b=ZmsrcJ512EOtA/eQnOpDq94kJ33gN38Ewa7xOi7Z14SX4ERKNxPTQsP2zm1JiqdlXsU0xImi9KCd
   8r10VIyjrJcB9VmEO6GdJeCWX8phN5PqLJQiLqm0wbefgmldMKU24wsGQJvFBZEjpUos8M7LxCQO
   unU0ycEnzY4Hk+Q9ys0=
DomainKey-Signature: a=rsa-sha1; c=nofws; q=dns; s=200608; d=email.gopro.com;
 b=dNuHcx8270nXvhHajbMZ7UlQhamzEDPZc6x+wVW+MA9v2xchD2Wz0swN2VHuabt3/z4ivCQ2lgvJ
   UI15KLX7a08udsY3ai26pIHKDhr6c5r2IN0qDzo8BiMBB89oNoXc3iZY5VpTo4a1TBZgYI+qaQXJ
   6bVFiAUuJhwLgAaWAqk=;
Received: by mta2.email.gopro.com id h4p90a163hs6 for <kyle@kylefisher.com>; Fri, 11 Nov 2016 17:19:33 -0600 (envelope-from <bounce-119_HTML-234621346-1218565-6157178-5339@bounce.email.gopro.com>)
From: "GoPro" <GoPro@email.gopro.com>
To: <kyle@kylefisher.com>
Subject: Fall from the sky on the Day of the Dead
Date: Fri, 11 Nov 2016 17:19:33 -0600
List-Unsubscribe: <mailto:leave-fd5015717c0b5c392848-fe3016737162067c761076-fe931572746c017b70-fe8c12717063057a7d-ff2b1173766d@leave.email.gopro.com>
MIME-Version: 1.0
Reply-To: "GoPro" <reply-fe931572746c017b70-119_HTML-234621346-6157178-5339@email.gopro.com>
List-ID: <6157178_1218565.xt.local>
X-CSA-Complaints: whitelistcomplaints@eco.de
x-job: 6157178_1218565
Message-ID: <2ca90373-d3c6-46ae-9c91-d1155c269020@xtinp2mta1235.xt.local>
Content-Type: multipart/alternative;
	boundary="AQBlKcUomMbc=_?:"

This is a multi-part message in MIME format.

--AQBlKcUomMbc=_?:
Content-Type: text/plain;
	charset="utf-8"
Content-Transfer-Encoding: 8bit

DAY OF THE DEAD SKYDIVE

Roberta and fellow skydivers remember the ones they’ve lost in a spirited skydive dance in Cuautla, Mexico.

http://click.email.gopro.com/?qs=4e42b8eb67da428122f2064c63d96e8977dcdf8bd574935297eeefc1f1a34f3b62827c3903c89d83

Don’t forget to check out our two other awesome videos.

Wild Animal Dental Surgery with Kevin Richardson >>
http://click.email.gopro.com/?qs=4e42b8eb67da4281ce15803566e9ece4de7afe2feac21526620cfede89364749bda61b00636c54e2

THE FOURTH PHASE WITH TRAVIS RICE >>
http://click.email.gopro.com/?qs=4e42b8eb67da42814336769b00b2668ea583de8770804656e65e5586e9b83e63111fe95d001e1c5d

http://click.email.gopro.com/?qs=4e42b8eb67da4281704942d70389cbebcf5c0de08d4161e15f5aff455c06e5c6a9fc6ca9ee9c45a8 

http://click.email.gopro.com/?qs=4e42b8eb67da4281c03e0329632829cf7a1f75439b6c906e97a928ec3a8b33ea453c4e83da501ca7 

http://click.email.gopro.com/?qs=4e42b8eb67da42813c4978486be9fa07fa15595ef408916d0927ac6f3b53529bf26a522ed54d5dd4 

http://click.email.gopro.com/?qs=4e42b8eb67da4281d17c030a1b05567574934131f8526a1ae5ffbba09a578a00274e3cd5c4aec248 

http://click.email.gopro.com/?qs=4e42b8eb67da4281a792c21f916cbc5d2fb06a4608ffc4b08fb423c0340b06840f1d765e9722550e 

Email not displaying correctly? View in browser.
http://view.email.gopro.com/?qs=acf50934f1e1c413efb465fc0618b0c366d7ad20bf19519ed0a25e23910ff44990cbdfa997a6e93fec6f6ee76f43f9498f8ea8d963e2a25f74af922e396518c3671b38ca015f1564 

GoPro, HERO, Karma, Session and their respective logos are trademarks or registered trademarks of GoPro, Inc. in the United States and other countries. (c) 2016 GoPro, Inc. All rights reserved.

If you no longer wish to receive these emails, please reply to this message with "unsubscribe" in the subject line, or 
http://pages.email.gopro.com/page.aspx?qs=330c754b5e92df742b2684d9e9c81af10f9095ba96c02502602a5de14794f6acb89c8f867826a73deac100b207f1150fd1df5d2974f2cda8352eab94ea19e44a79b3ee835cfa2b9633fdee88ee18a0b66d0f1d89eaea45fcb965f54b491fd131f1f37a8e0c857a09c5212c2fc4bbec17566329c160dbb5b73a2b7b147d5eaea8da945737c7306476cd49ce3086ceb449c4e4a0ad7dcc382e85d91ef3aeb29dc3327850973093e59a4b6ffa977ff7379099bc850fc9bc9ed304d9b464e606d8d87aa99291914b5c887a735805577d35b57cc15d81ef847ff5376a73f6c148baa68f52efdb34dcfc45729203de80a73d8a8a88b2c0285d661cbfa85a9332057b2b2c86e72a483078c1d458229bbc206a8222dd77b317c94a6ee48bebccfbef77ec617677b534c767f254796f3b42976baa6eb8f42b6093d0f674b1dc5e522f69d4164791830760699a08295fa2d6ae10619e97d98f33c9ed9bf71413b6faf4354558888ddcc6bfc905c3abf21e9b5f6afa13d1b83ef78cb036ae6f8301c090db8de3eaff79aff71c00aa3e1cda9cf94c8f3b95542ec3c63f3a648cf199760b16ff86e1097760a7abc053ecb2c0850a3f99ac3544aef70a38a80d2bc12e104c1e699c7a0e752b0813a06f9ef47dca0fba90b9d718c443
8a1a14f25f6d847ba4678e 
click here. 

3000 Clearview Way, San Mateo, CA, USA 94402

——————————————————————————————————



--AQBlKcUomMbc=_?:
Content-Type: text/html;
	charset="utf-8"
Content-Transfer-Encoding: 8bit

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" dir="ltr">
<head>
<!--[if gte mso 9]><xml>
  <o:OfficeDocumentSettings>
    <o:AllowPNG/>
    <o:PixelsPerInch>96</o:PixelsPerInch>
  </o:OfficeDocumentSettings>
</xml><![endif]-->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta name="format-detection" content="telephone=no">
<meta http-equiv="X-UA-Compatible" content="IE=edge" /> 
<title>GoPro</title>
<style type="text/css">
table {
	border-collapse:collapse;
	mso-table-lspace:0pt;
	mso-table-rspace:0pt;
}
.ExternalClass {
	width:100% !important;
}
.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {
	line-height: 100%;
}
/* Image borders &amp; formatting */
		img {
	outline:none;
	text-decoration:none;
	-ms-interpolation-mode: bicubic;
	margin:0 0 0 0 !important;
}
a img {
	border:none;
	margin:0 0 0 0 !important;
}
/* Re-style iPhone automatic links (eg. phone numbers) */
		.applelinks a {
	color:#66c4f3;
	text-decoration: none;
}
		/* Hotmail symbol fix for mobile devices */
		.ExternalClass img[class^=Emoji] {
width: 10px !important;
height: 10px !important;
display: inline !important;
}
.tpl-content {
	display:inline !important;
}
		
		/* Media Query for mobile */
		
@media screen and (max-width: 570px) {
.fullTbl {
display:block;
width:100%!important;
max-width:100%!important;
}

.modTbl {
display:block;
width:100%!important;
max-width:100%!important;
margin-bottom:15px;
}

.btTbl {
width:100%!important;
max-width:100%!important;
}

.mobWidth,.mobHero {
width:100%!important;
min-width:100%!important;
height:auto!important;
}

.mobHeroImg,.mobImgScale {
width:100%!important;
}

.mobHide {
display:none!important;
height:0!important;
width:0!important;
visibility:hidden!important;
}

.title {
text-align:center!important;
padding:25px!important;
}

.title15 {
padding:15px 15px 10px!important;
}

.bodyCopy {
text-align:center!important;
padding:0 25px!important;
}

.noPad {
padding:0!important;
}

.moduleBt {
width:45%!important;
}

.btPad {
padding:0 0 30px!important;
}

.propPadone {
padding:15px 15px 0!important;
}

.socialIcon {
width:50px!important;
height:50px!important;
}

.socialPad {
padding:10px 0!important;
}

.videoTitle {
font-size:27px!important;
padding:15px!important;
}

.videoCopy {
padding:0 15px 20px!important;
}

.topBtpad {
padding:20px 0 45px!important;
}

.videoBtpad {
padding:20px 0!important;
}

.modulePadbottom {
padding:0 0 35px!important;
}

.singleBt {
padding:15px 45px!important;
}

.moduleTitle,.moduleCopy {
padding:0 15px 15px!important;
}

.bodyCopy15,.propPadtwo {
padding:0 15px!important;
}
 .moduleTitle2 {
 padding: 0 25px 5px !important;
}
 .moduleCopy2 {
 padding: 15px 35px 10px !important;
}
 .moduleCopylast {
 padding: 0 25px 40px !important;
}
.sbaPad {
	Padding-bottom: 20px;
}
.mobNoBorders {
    border-right: none !important;
    border-left: none !important;
  }
.tableAlign {
 width: 100% !important;
}
.titleLeft {
padding: 25px 25px 15px !important;
font-size: 35px !important;
line-height: 34px !important;

}
.bodyCopyLeft {
    padding: 0 25px !important;
}
.ecommimgFull {
	width: 87% !important;
}
 .titlePad {
 padding: 25px 20px 0 !important;
}
*[class=head] {
display:table-header-group !important;
width:100% !important;
}
*[class=foot] {
display:table-footer-group !important;
width:100% !important;
}
.tableAlign {
 width: 100% !important;
}
.subCopypad {
 padding: 10px 20px 15px !important;
 font-size: 14px !important;
  line-height: 16px !important;
}
.appTbl {
 width: 88% !important;
}
.googleBt {
	width: 108px !important;
	height:auto !important;
}
.appleBt {
	width: 125px !important;
	height:auto !important;
}

.tblBorder {
	border-bottom: 2px solid #cccccc;
	height:auto !important;
}

 .mobApp {
 width: 53% !important;
 height: auto !important;
}
.AppPad {
 padding: 5px 20px 0 !important;
}
 .dividerSub {
 padding: 30px 0 !important;
}
.font37 {
	
    font-size: 37px !important;
    line-height: 29px !important;
    padding: 20px 10px 0 !important;
   
}
.font29 {
	
    font-size: 29px !important;
	 padding: 0 10px 40px !important;

  
}
 .bodyCopyPlus {
 font-size: 16px !important;
 line-height: 23px !important;
 padding: 10px 20px 20px 30px !important;
}
 .titlePlus {
 font-size: 24px !important;
padding: 15px 20px 0 30px !important;
}
}
/* ----------- iPhone 6 ----------- */

/* Portrait and Landscape */
@media only screen 
  and (device-width : 375px)  
 

{ 
  
  .googleBt {
	width: 125px !important;
	height:auto !important;
}
.appleBt {
	width: 125px !important;
	height:auto !important;
}


}

/* ----------- iPhone 6+ ----------- */

/* Portrait and Landscape */
@media only screen 
  and (device-width : 414px) 


  
 { 
  
  .googleBt {
	width: 125px !important;
	height:auto !important;
}
.appleBt {
	width: 125px !important;
	height:auto !important;
}



	
}
</style>
</head><body bgcolor="#000000" style="-ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; margin: 0; padding: 0; width: 100%"><style type="text/css">
div.preheader 
{ display: none !important; } 
</style>
<div class="preheader" style="font-size: 1px; display: none !important;">Plus, awesome makeup and wardrobes</div>

<img src="http://click.email.gopro.com/open.aspx?ffcb10-fe931572746c017b70-fdf2157376660d7d7d12757d-fe8c12717063057a7d-ff6415717c-fe3016737162067c761076-ff2b1173766d" width="1" height="1">
<table width="100%" border="0" dir="ltr" style="-premailer-border: 0; -premailer-cellpadding: 0; -premailer-cellspacing: 0; border-collapse: collapse; border-spacing: 0; border: none; color: #000000; font-family: Arial, Helvetica, sans-serif" cellpadding="0" cellspacing="0" bgcolor="#000000">
  <tr>
    <td bgcolor="#000000">
      
      <table width="600" border="0" dir="ltr" align="center" class="mobWidth" style="-premailer-border: 0; -premailer-cellpadding: 0; -premailer-cellspacing: 0; border-collapse: collapse; border-spacing: 0; color: #000000; font-family: Arial, Helvetica, sans-serif; margin: 0 auto; max-width: 600px; min-width: 600px; table-layout: fixed" cellpadding="0" cellspacing="0" bgcolor="#000000">
        <tr>
       <td align="center"><table cellpadding="0" cellspacing="0" border="0" bordercolor="" width="100%" bgcolor=""><tr><td><table  width="100%" bgcolor="" border="0" bordercolor="" cellpadding="0" cellspacing="0"><tr><td style="font-family:Arial; font-size:13px"><a href="http://click.email.gopro.com/?qs=4e42b8eb67da42818792bb87ee9a45aae8886927589e8dbba56d3870ec540e75d9fa6bf72482d077"><img width="600" alt="Video of the Week" style="border: medium none; display: block; outline: none medium; color: #66c4f3; max-width: 600px !important;" class="heroImg mobHide" src="http://image.email.gopro.com/lib/fe8c12717063057a7d/m/1/VOW_111016.jpg" /> 
<!--[if !mso]><!-- --><img width="0" height="0" style="border-style: none; display: block; outline: none medium;" class="mobHero" src="http://image.email.gopro.com/lib/fe8c12717063057a7d/m/1/VOW_111016_mobile.jpg" />
<!--<![endif]--></a></td></tr></table></td></tr></table></td>
        </tr>
        
        <tr>
           <td align="center"><table cellpadding="0" cellspacing="0" border="0" bordercolor="" width="100%" bgcolor=""><tr><td><table  width="100%" bgcolor="" border="0" bordercolor="" cellpadding="0" cellspacing="0"><tr><td style="font-family:Arial; font-size:13px"><table width="79%" cellspacing="0" cellpadding="0" border="0" bgcolor="#000000" align="center" style="border-collapse: collapse; border-spacing: 0px;" class="fullTbl">
	<tbody>
		<tr>
			<td style="font-size: 34px; line-height: 36px; color: #ffffff; font-family: Arial, Helvetica, sans-serif; text-transform: uppercase; vertical-align: top; margin: 0px; text-align: left; padding: 20px 0px 15px; font-weight: bold;" class="videoTitle">Day of the Dead Skydive</td>
		</tr>
	</tbody>
</table></td></tr></table></td></tr></table></td>
        </tr>
        <tr>
          <td align="center"><table cellpadding="0" cellspacing="0" border="0" bordercolor="" width="100%" bgcolor=""><tr><td><table  width="100%" bgcolor="" border="0" bordercolor="" cellpadding="0" cellspacing="0"><tr><td style="font-family:Arial; font-size:13px"><table width="79%" cellspacing="0" cellpadding="0" border="0" bgcolor="#000000" align="center" class="fullTbl" style="border-collapse: collapse; border-spacing: 0px;">
	<tbody>
		<tr>
			<td class="videoCopy" style="text-align: left; font-size: 16px; line-height: 18px; color: #999999; font-family: Arial, Helvetica, sans-serif; vertical-align: top; padding-left: 0px; margin: 0px; padding-bottom: 30px;">
			Roberta and fellow skydivers remember the ones they’ve lost in a spirited skydive dance in Cuautla, Mexico.  
			</td>
		</tr>
	</tbody>
</table></td></tr></table></td></tr></table></td>
        </tr>
        <tr>
        	 <td align="center"><table cellpadding="0" cellspacing="0" border="0" bordercolor="" width="100%" bgcolor=""><tr><td><table  width="100%" bgcolor="" border="0" bordercolor="" cellpadding="0" cellspacing="0"><tr><td style="font-family:Arial; font-size:13px"><table width="74%" cellspacing="0" cellpadding="0" border="0" bgcolor="#000000" align="center" class="fullTbl" style="border-collapse: collapse; border-spacing: 0px;">
	<tbody>
		<tr>
			<td class="videoCopy" style="text-align: left; font-size: 17px; line-height: 19px; color: #ffffff; font-family: Arial, Helvetica, sans-serif; vertical-align: top; padding-left: 0px; margin: 0px; padding-bottom: 15px;">
			Don&rsquo;t forget to check out our two other awesome videos.
			</td>
		</tr>
	</tbody>
</table></td></tr></table></td></tr></table></td>
        </tr>
        <tr>
        	 <td align="center"><table width="600" cellspacing="0" cellpadding="0" border="0" align="center" class="mobWidth" style="border-collapse: collapse; border-spacing: 0px;">
	<tbody>
		<tr>
			<td align="center">
			<!-- LEFT IMAGE-->
			<a href="http://click.email.gopro.com/?qs=4e42b8eb67da42818c8213504a736bb9ff3188d0de30b4c585852c3917c6e899fddc88cd4a4158ba"><img width="300" alt="Video 2" style="border: medium none; display: block; outline: none medium; color: #66c4f3; max-width: 600px !important;" class="heroImg mobHide" src="http://image.email.gopro.com/lib/fe8c12717063057a7d/m/1/VOD_111016_left.jpg" /> 
			<!--[if !mso]><!-- --><img width="0" height="0" style="border-style: none; display: block; outline: none medium;" class="mobHero" src="http://image.email.gopro.com/lib/fe8c12717063057a7d/m/1/VOD_111016_left_mobile.jpg" />
			<!--<![endif]--></a>
			</td>
			<td align="center">
			<!-- RIGHT IMAGE-->
			<a href="http://click.email.gopro.com/?qs=4e42b8eb67da4281076859fb14bf5d775f23ad76f05e3552a751f659bc3e29931f60ff2012c1593d"><img width="300" alt="Video 3" style="border: medium none; display: block; outline: none medium; color: #66c4f3; max-width: 600px !important;" class="heroImg mobHide" src="http://image.email.gopro.com/lib/fe8c12717063057a7d/m/1/VOD_111016_right.jpg" /> 
			<!--[if !mso]><!-- --><img width="0" height="0" style="border-style: none; display: block; outline: none medium;" class="mobHero" src="http://image.email.gopro.com/lib/fe8c12717063057a7d/m/1/VOD_110416_right_mobile.jpg" />
			<!--<![endif]--></a>
			</td>
		</tr>
	</tbody>
</table></td>
      </tr>
      <tr>
       <td align="center"></td>
  </tr>
   <tr>
       <td align="center"><table cellpadding="0" cellspacing="0" border="0" bordercolor="" width="100%" bgcolor=""><tr><td><table  width="100%" bgcolor="" border="0" bordercolor="" cellpadding="0" cellspacing="0"><tr><td style="font-family:Arial; font-size:13px"><table width="602" cellspacing="0" cellpadding="0" border="0" bgcolor="#000000" align="center" class="mobWidth" style="border-collapse: collapse; border-spacing: 0px; border: medium none; color: #000000; font-family: Arial, Helvetica, sans-serif; margin: 0px auto; table-layout: fixed;" dir="ltr">
	<tbody>
		<tr>
			<td align="center" style="padding: 10px 20px;">
			<table width="30%" cellspacing="0" cellpadding="0" border="0" align="center" class="mobImgScale">
				<tbody>
					<tr>
						<td align="center" class="socialPad" style="padding: 10px;"><a href="http://click.email.gopro.com/?qs=4e42b8eb67da428116aaa24ab9426ef5a32abee2aa15918e4f48093c7ac60b263f82f5d92bcb9a3a"><img width="40" height="40" class="socialIcon" style="display: block; border: medium none; color: #66c4f3;" alt="Facebook" src="http://image.email.gopro.com/lib/fe8c12717063057a7d/m/1/04_MultiTopic_Media_FB-dark.jpg" /></a></td>
						<td align="center" class="socialPad" style="padding: 10px;"><a href="http://click.email.gopro.com/?qs=4e42b8eb67da4281211d9816e266c4e6f3e033665fe08e1add850a22f61093e45efa76480a4bf0ff"><img width="40" height="40" class="socialIcon" style="display: block; border: medium none; color: #66c4f3;" alt="YouTube" src="http://image.email.gopro.com/lib/fe8c12717063057a7d/m/1/04_MultiTopic_Media_YT-dark.jpg" /></a></td>
						<td align="center" class="socialPad" style="padding: 10px;"><a href="http://click.email.gopro.com/?qs=4e42b8eb67da4281c3c3777f1c3f7ebe737a97abc627b367bf1f7d0fe6b37d475b80ccd794a82119"><img width="40" height="40" class="socialIcon" style="display: block; border: medium none; color: #66c4f3;" alt="Twitter" src="http://image.email.gopro.com/lib/fe8c12717063057a7d/m/1/04_MultiTopic_Media_TW-dark.jpg" /></a></td>
						<td align="center" class="socialPad" style="padding: 10px;"><a href="http://click.email.gopro.com/?qs=4e42b8eb67da4281e2cd26224b6fe0d5298203f7206f9ad648473e9763aa95dca467f13c58bbb504"><img width="40" height="40" class="socialIcon" style="display: block; border: medium none; color: #66c4f3;" alt="Instagram" src="http://image.email.gopro.com/lib/fe8c12717063057a7d/m/1/04_MultiTopic_Media_PIN-dark.jpg" /></a></td>
						<td align="center" class="socialPad" style="padding: 10px;"><a href="http://click.email.gopro.com/?qs=4e42b8eb67da42814afd3bd259f266f5177985e7dc490e555e3804cb20abeb090859e6962929775d"><img width="40" height="40" class="socialIcon" style="display: block; border: medium none; color: #66c4f3;" alt="Pinterest" src="http://image.email.gopro.com/lib/fe8c12717063057a7d/m/1/MultiTopic_Media_PIN-dark.jpg" /></a></td>
					</tr>
				</tbody>
			</table>
			</td>
		</tr>
		<tr>
			<td class="applelinks" style="color: #666666; font-size: 9px; line-height: 15px; padding: 0px 10px 15px; text-align: center; font-family: Arial,Helvetica,sans-serif;"> Email not displaying correctly? <a style="color: #66c4f3; text-decoration: underline;" href="http://view.email.gopro.com/?qs=acf50934f1e1c413efb465fc0618b0c366d7ad20bf19519ed0a25e23910ff44990cbdfa997a6e93fec6f6ee76f43f9498f8ea8d963e2a25f74af922e396518c378c02e30334b8713">View in browser</a>.<br />
			<br />
			GoPro, HERO, Karma, Session and their respective logos are trademarks or registered trademarks of GoPro, Inc. in the United States and other countries. &copy; 2016 GoPro, Inc. All rights reserved.  
			If you no longer wish to receive these emails, please reply to this message with "unsubscribe" in the subject line, or 
<a style="color: #66c4f3; text-decoration: none;"
 href="http://pages.email.gopro.com/page.aspx?qs=330c754b5e92df742b2684d9e9c81af10f9095ba96c02502602a5de14794f6acb89c8f867826a73deac100b207f1150fd1df5d2974f2cda8352eab94ea19e44a79b3ee835cfa2b9633fdee88ee18a0b6c86ee6ab5cde066612f96cfb49a0d9c40c7f311092c671aaead7b99e266f27d0e8f3f4417fe925d0c7faa26ab1dcb537b484d79716c537c9174d7ece390cdde84f8a628506b9b095cd4aeb4256c999bcf4e1c12bb2a00aa7313b086c0a480856e2b5ecd72ee67c445e7fb3cde168fce1fa182f47159e28fce45099e34ac67f3fc2d4ba0b972fb1da0dfd479a2b21ac10e9e6e6a7ff410b03f6f586150b89d5d6391ce483653cdfbae4122f48819a31c8f8546735e803e8173ab443b8c3981d18d39dadef020394100345f60d48030651c69a22b871a2462b340358b31d330a4d4723f120d98c24c89290dd8d52aa6ac1b41a80c78ef2044c2d80ec696713f1048bbbc0159e6f2f9455e3572a05735fe57b7dfc9af873cbf0b8623aceb34c466042d9b18d46bc3e397f82dae640ddd779fed67f341878fef051171d0c3b735ef395564e4cc1b6b3bc6dcf73ee1a9b252bf5dc8ee00ff95c9afb540fd6d9ec79e8f1d82597d66ea0689b3ca469aa601ccfb28bb2c5b4d30d66137f38dfb81e4c84694
19420ab32ab0a282ff447c2a2c447">click here</a>. <br />
			<br />
			3000 Clearview Way, San Mateo, CA, USA 94402
			</td>
		</tr>
	</tbody>
</table></td></tr></table></td></tr></table></td>
  </tr>
   <tr>
       <td align="center"></td>
  </tr>
  <tr>
          <td><table width="602" align="center" class="mobHide" style="-premailer-border: 0; -premailer-cellpadding: 0; -premailer-cellspacing: 0; border-collapse: collapse; border-spacing: 0; border: none; color: #000000; font-family: Arial, Helvetica, sans-serif" cellpadding="0" cellspacing="0">
              <tr>
                <td class="dogfoodFix" style="-webkit-text-size-adjust: 100%; color: #000000 !important; line-height: 1em; visibility: hidden !important; white-space: nowrap !important"><font color="#000000">——————————————————————————————————</font></td>
              </tr>
            </table></td>
        </tr>
</table>

</td>
</tr>
</table>

</body>
</html>

--AQBlKcUomMbc=_?:--


