From d8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2@bounce.r.groupon.com Fri Nov 11 14:42:27 2016
Received: from mta330s1.r.groupon.com ([50.115.211.30]:4035)
	by ecbiz209.inmotionhosting.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <d8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2@bounce.r.groupon.com>)
	id 1c5HiV-002OKp-67
	for kyle@kylefisher.com; Fri, 11 Nov 2016 14:42:27 -0500
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=r.groupon.com;
	s=s2048d20160829; t=1478893345;
	bh=U1TLb83ZJiPUOEEh6xUNoCUX6zlICNIY8SYaSkeiGsY=;
	h=Date:From:To:Message-ID:Subject:Content-Type;
	b=XoIIgqzIAtWstXj9ZdhYLR7I2jrEIS2O/psLSm12jJ67/or71o2P9ClNCKxin2zFB
	 7OZQiY7p+krsj2AjxJGKyNwTFygIzwFZGni+q3LDs+2PoHLQBZcsP7yuxZQ12/fNf4
	 AxC+2gbPUC94bCs6Mp3KPIJFB6QqZYY6hWyc3t71sRztILNIMWnHrCsuF5xwY2pgrv
	 TefGw6AXVTyuW6z6YCDXb8qw4zKP1VqETwL7/RT2nscUhE2gveCl5wFT61hp6aGe29
	 wZg+FrG9XzK82533L3f+IE1/9y4AFv8DTLu6hKbTCjA6XMkiCCyrqnrci1vzsjxr19
	 JjBMYTl5dQTag==
Date: Fri, 11 Nov 2016 19:42:25 +0000
From: Groupon Goods <noreply@r.groupon.com>
To: kyle@kylefisher.com
Message-ID: <533524072.24784749.1478893345455.JavaMail.rocketman@push-dispatcher6>
Subject: Mystery Bras in Regular and Plus, Furhaven Orthopedic Pet Bed ,
 XtremePro HD 720p Sports Camera & More
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
X-RM-UserHash: d8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2
X-RM-SendId: de49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111
X-RM-SenderScore: 0
X-RM-EmailName: crm_discount_goods_us_im_20161111_Feynman_LowAffinity
X-MSFBL: a3lsZUBreWxlZmlzaGVyLmNvbTpiYXRjaDpkZTQ5ZWExNC00YjhlLTQzNTUtYWRjZC1jYmRmMjk2NGIzY2ZfMF8yMDE2MTExMTpudWxsOlVT
List-Unsubscribe: <mailto:d8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2@unsub.r.groupon.com?subject=a3lsZUBreWxlZmlzaGVyLmNvbTpiYXRjaDpkZTQ5ZWExNC00YjhlLTQzNTUtYWRjZC1jYmRmMjk2NGIzY2ZfMF8yMDE2MTExMTpudWxsOlVT>
X-RPCampaign: Grouponcrmdiscountgoodsusim20161111FeynmanLowAffinity20161111
X-RPTags: crm_discount_goods_us_im_20161111_Feynman_LowAffinity
X-Recruiting: Interested in headers? Join us: www.groupon.com/techjobs/
List-Id: <crm_discount_goods_us_im_20161111_Feynman_LowAffinity_20161111.groupon>
X-Feedback-ID: r.groupon.com:crm_discount_goods_us_im_20161111_Feynman_LowAffinity:de49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111:groupon

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.=
w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> <html xmlns:v=3D"urn:schemas=
-microsoft-com:vml"> <head> <meta http-equiv=3D"Content-Type" content=3D"te=
xt/html; charset=3DUTF-8"> <meta name=3D"viewport" content=3D"initial-scale=
=3D1.0"> <meta name=3D"format-detection" content=3D"telephone=3Dno"> <title=
>Groupon</title> <style type=3D"text/css"> @media only screen and (max-widt=
h: 480px){ td[class=3D"mobile-padding-container"]{ padding: 10px !important=
; } td[class=3D"mobile-padding"]{ padding: 0 0 0 0 !important; } *[class=3D=
"mobile-padding-font"]{ padding: 0 0 0 0 !important; font-size: 10px !impor=
tant; font-weight:normal !important; } *[class=3D"mobile-padding-font-purch=
ase"]{ padding: 0 0 0 0 !important; font-size: 9px !important; font-weight:=
normal !important; } *[class=3D"mobile-padding-logo"]{ padding: 0 0 0 0 !im=
portant; width: 195px !important; } td[class=3D"header-text"]{ text-align: =
left !important; } img[class=3D"188"]{ width: 144px !important; } td[class=
=3D"floatLeft"]{ float: left !important; width: 100% !important; border: 0p=
x none !important; text-align: left !important; padding: 5px 0 5px 0 !impor=
tant; line-height: 14px !important; } td[class=3D"floatLeft-ship"]{ float: =
left !important; width: 100% !important; border: 0px none !important; text-=
align: left !important; padding: 5px 0 15px 0 !important; line-height: 14px=
 !important; font-size: 13px !important; } td[class=3D"floatLeft-name"]{ fl=
oat: left !important; width: 100% !important; border: 0px none !important; =
text-align: left !important; padding: 5px 0 5px 0 !important; line-height: =
14px !important; font-weight: bold !important; font-size: 13px !important; =
} td[class=3D"floatLeftDeals"]{ float: left !important; width: 100% !import=
ant; text-align: left !important; } img[class=3D"100"]{ width: 100% !import=
ant; } td[class=3D"100"]{ width: 100% !important; } table[class=3D"containe=
r"]{ width: 100% !important; float: none !important; } td[class=3D"border-o=
ff"]{ border-left: none !important; border-right: none !important; border-t=
op: 20px solid #ffffff; } td[class=3D"188"]{ width: 48% !important; } td[cl=
ass=3D"heroPadding"]{ padding: 20px 0 0 0 !important; } table[class=3D"oute=
r_container"]{ width: 100% !important; border-spacing: 0 !important; border=
-collapse: collapse !important; padding: 0 0 0 0 !important; margin-top: 0 =
!important; margin-bottom: 0 !important; margin-left: auto !important; marg=
in-right: auto !important; } table[class=3D"inner_container"]{ width: 100% =
!important; min-width: 100% !important; margin-top: 0 !important; margin-bo=
ttom: 0 !important; margin-left: auto !important; margin-right: auto !impor=
tant; border-spacing: 0 !important; border-collapse: collapse !important; p=
adding: 0 0 0 0 !important; } td[class=3D"inner_container"]{ width: 100% !i=
mportant; margin-top: 0 !important; margin-bottom: 0 !important; margin-lef=
t: auto !important; margin-right: auto !important; background-size: 100% !i=
mportant; } img[class=3D"secondary-100"]{ min-width: 0 !important; width: 1=
00% !important; padding: 0 0 0 0 !important; margin-top: 0 !important; marg=
in-bottom: 0 !important; margin-left: auto !important; margin-right: auto !=
important; } td[class=3D"floatLeft"]{ float: left !important; width: 100% !=
important; border: 0px none !important; text-align: left !important; paddin=
g: 5px 0 5px 0 !important; line-height: 14px !important; } td[class=3D"name=
Font"]{ font-size: 18px !important; line-height: 22px !important; } span[cl=
ass=3D"nameFont"]{ font-size: 18px !important; line-height: 22px !important=
; } td[class=3D"heroNameFont"]{ font-size: 18px !important; line-height: 22=
px !important; } table[class=3D"heroButton"]{ width: 120px !important; } /*=
 Collection widget price left */ td[class=3D"align-left-widget"]{ width: 10=
0% !important; float: left; text-align: left; padding: 0 8px 3px 13px !impo=
rtant; } *[class].banner_mobile { width: 100% !important; max-height: none =
!important; height: auto !important; display:block !important; } *[class].m=
obileHidden { display:none !important; } *[class].logo_mobile { max-height:=
 none !important; height: auto !important; display: block !important; margi=
n: 0 !important; } table[class=3D"display-off"]{ display: none !important; =
} td[class=3D"display-off"]{ display: none !important; } td[class=3D"displa=
y-block"]{ display: block !important; } td[class=3D"sm-mobile-font"]{ font-=
size: 10px !important; } } /* category widget for ios 5 and smaller */ @med=
ia only screen and (min-device-width: 320px) and (max-device-width: 479px) =
{ .three-column .column { width: 95% !important; max-width: 170px !importan=
t; display: inline-block; vertical-align: top; } } /* category widget for 5=
s phones or smaller */ @media only screen and (max-device-width: 320px) { .=
three-column .column { width: 75% !important; max-width: 145px !important; =
display: inline-block; vertical-align: top; } } /* To Hide Extra Nav Cats o=
n tablets */ @media only screen and (min-device-width : 768px) and (max-dev=
ice-width : 1024px) { td[class=3D"display-off"]{ display: none !important; =
} } </style> </head> <body style=3D"margin:0 !important; padding:0 !importa=
nt;"> <div style=3D"display:none; white-space:nowrap; font:15px courier; li=
ne-height:0;"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbs=
p; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &n=
bsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; =
</div> <img src =3D "http://www.groupon.com/analytic/track.gif?p=3D1&utm_do=
main=3Dkylefisher.com&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0=
_20161111&deals=3D70a68696-955d-11e6-bff2-00259069d7cc,38de4d54-60c2-11e6-9=
2a9-00259069d868,e9d59326-6a5c-11e6-aa0d-00259069d7cc,b6d442aa-34b6-11e6-83=
13-00259069d868,9454070e-a5e2-11e6-b372-00259069d7cc,4ddf3d54-97d0-11e6-89c=
b-00259060b5da,b8671256-7b64-11e6-9eb8-00259069d7cc,445d7888-960c-11e6-851f=
-00259069d7cc,2fd44e8c-a53e-11e6-944b-002590604002,763e7eb6-97be-11e6-8b6c-=
00259060b5da,bf78fb3c-6a33-11e6-8b15-002590604002,03686c10-8ca8-11e6-8b16-0=
0259069d7cc,51506417-cb99-458d-978d-ec03486fbb9d,503c69bc-8b61-11e6-89fc-00=
259069d868,84c7c7f2-9fad-11e6-8201-00259069d7cc,930d9a8a-9b93-11e6-9822-002=
59069d7cc,597d504c-9c12-11e6-bf24-00259060b5da,29533942-8bf3-11e6-8d1e-0025=
9060b5da,9fab8d3e-3198-11e6-86a9-00259069d7cc,4aaedf7c-9f7d-11e6-a8e6-00259=
0604002,bc430798-961e-11e6-9903-002590604002,b9d91282-a072-11e6-b796-002590=
69d7cc,0e86e1c4-5b5e-11e6-876a-002590604002&channel_deals=3Dnull&utm_source=
=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fb=
f5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-0025=
9069d5fe&CID=3DUS&tx=3D0" height=3D"1" width=3D"1" style=3D"display: none !=
important;" /> <img height=3D"1" width=3D"1" src=3D"https://stags.bluekai.c=
om/site/28445?limit=3D1&phint=3Dconsumer_id=3Df79c234c-2539-11e2-82c0-00259=
069d5fe&phint=3Dsource=3Demail" style=3D"display: none !important;" /> <tab=
le cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spac=
ing:0; font-family: Helvetica, Arial, sans-serif; color:#000000; font-weigh=
t: 100; width: 100%; background: #ececec;" align=3D"center"> <tr> <td align=
=3D"center"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 =
none; border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#0=
00000; font-weight: 100; width: 700px; min-width:600px; background: #ffffff=
;" width=3D"700" align=3D"center" class=3D"inner_container"> <tr> <td style=
=3D"padding: 10px 10px 10px 10px;" align=3D"center"> <span style=3D"color: =
#ffffff; font-size: 0px !important;" height=3D"0"> </span> <table cellpaddi=
ng=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-=
family: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; widt=
h: 600px;" width=3D"600" align=3D"center" class=3D"container"> <tr> <td sty=
le=3D"padding: 10px 0 10px 0;"> <table cellpadding=3D"0" cellspacing=3D"0" =
style=3D"width: 257px;" width=3D"257" align=3D"left" class=3D"container"> <=
tr> <td class=3D"mobile-padding-logo" align=3D"left" style=3D"width: 257px;=
"><a href=3D"https://www.groupon.com/goods?utm_source=3Dcrm_im&utm_medium=
=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561e=
d8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=
=3D0&s=3Dheader&c=3Dimage&d=3DGroupon&utm_campaign=3Dde49ea14-4b8e-4355-adc=
d-cbdf2964b3cf_0_20161111" style=3D"font-size: 24px !important; line-height=
: 28px !important; color:#000000 !important; text-decoration: none; font-we=
ight: 100; font-weight: 700;" target=3D"_blank"><img src=3D"https://s3.grou=
poncdn.com/email/images/prom_night/global_images/pn-groupon-logo-green.png"=
 style=3D"display: block; border: none; width: 100%;" /></a> </td> </tr> </=
table> </td> <td align=3D"right" valign=3D"middle" style=3D"padding-left:10=
px;" valign=3D"bottom"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D=
"width: 100px;" width=3D"100" align=3D"right"> <tr> <td class=3D"mobile-pad=
ding" align=3D"right" valign=3D"middle" style=3D"vertical-align: middle;"><=
a href=3D"https://www.facebook.com/groupon" style=3D"color:#0185C6; text-de=
coration:none;" target=3D"_blank"><img src=3D"https://s3.grouponcdn.com/ema=
il/images/mindstorm/social/icon-facebook-white.png" style=3D"display: block=
; border: none; display: inline-block; width: 25px;" /></a>&nbsp;<a href=3D=
"https://www.twitter.com/groupon" style=3D"color:#0185C6; text-decoration:n=
one;" target=3D"_blank"><img src=3D"https://s3.grouponcdn.com/email/images/=
mindstorm/social/icon-twitter-white.png" style=3D"display: block; border: n=
one; display: inline-block; width: 25px;" /></a>&nbsp;<a href=3D"https://ww=
w.pinterest.com/groupon" style=3D"color:#0185C6; text-decoration:none;" tar=
get=3D"_blank"><img src=3D"https://s3.grouponcdn.com/email/images/mindstorm=
/social/icon-pinterest-white.png" style=3D"display: block; border: none; di=
splay: inline-block; width: 25px;" /></a></td> </tr> </table> </td> </tr> <=
tr> <td colspan=3D"2" style=3D"border-top: 1px solid #cccccc;"> <table cell=
padding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; =
font-family: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100;=
 width: 100%;" align=3D"center" class=3D"container"> <tr> <td style=3D"padd=
ing: 10px 0 0 0;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"bord=
er: 0 none; border-spacing:0; font-family: Helvetica, Arial, sans-serif; co=
lor:#000000; font-weight: 100; width: 100%;" align=3D"center" class=3D"cont=
ainer"> <tr> <td colspan=3D"2" class=3D"floatLeft-name" style=3D"width: 40%=
; font-size: 14px; color: #6d6d6d; font-weight: 500;" align=3D"left">For Yo=
u | November 11, 2016</td> </tr> </table> </td> </tr> </table> </td> </tr> =
</table> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none=
; border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#00000=
0; font-weight: 100; width: 100%;" align=3D"center" class=3D"outer_containe=
r"> <tr> <td align=3D"center" style=3D"padding-top: 10px;" class=3D"heroPad=
ding"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; =
border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#000000;=
 font-weight: 100; width: 600px;" align=3D"center" class=3D"inner_container=
"> <tr> <td colspan=3D"2"><a href=3D"https://www.groupon.com/deals/gg-bras-=
in-regular-and-plus-sizes?p=3D1&utm_source=3Dcrm_im&utm_medium=3Demail&user=
=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D=
20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody=
&c=3Dbutton&d=3DGoods-PN-Hero&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf29=
64b3cf_0_20161111" target=3D"_blank" style=3D"display: block; border: none;=
"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; bord=
er-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#000000; fon=
t-weight: 100; width: 600px;" align=3D"center" class=3D"inner_container"> <=
tr> <td align=3D"center" style=3D"width: 100%; border-top: 1px solid #f2f2f=
2; border-left: 1px solid #f2f2f2; border-right: 1px solid #f2f2f2;"> <img =
src=3D"https://img.grouponcdn.com/deal/4ZPhuZLonSneuujNFpSbtjkZspNt/4Z-2048=
x1229/v1/c600x320.jpg" style=3D"display: block; border: none;" class=3D"100=
" /> </td> </tr> </table> </a></td> </tr> <tr> <td align=3D"left" style=3D"=
background: #ffffff; padding: 15px 5px 15px 15px;"><a href=3D"https://www.g=
roupon.com/deals/gg-bras-in-regular-and-plus-sizes?p=3D1&utm_source=3Dcrm_i=
m&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac=
134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe=
&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN-Hero&utm_campaign=3Dde49e=
a14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" target=3D"_blank" style=3D"font=
-size: 16px !important; line-height: 20px !important; color:#000000 !import=
ant; text-decoration: none; color: #ffffff;"> <table cellpadding=3D"0" cell=
spacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Helve=
tica, Arial, sans-serif; color:#000000; font-weight: 100; width: 100%; back=
ground: #ffffff;" align=3D"center"> <tr> <td class=3D"heroNameFont" style=
=3D"font-size: 18px; line-height: 22px; text-decoration: none; color:#33333=
3;" align=3D"left"> Mystery Bras in Regular and Plus </td> </tr> <tr> <tr> =
<td style=3D"padding: 3px 0 0 0; background: #ffffff;" align=3D"left"> <tab=
le cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spac=
ing:0; font-family: Helvetica, Arial, sans-serif; color:#000000; font-weigh=
t: 100;"> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"top" style=
=3D"padding-right: 5px; padding-right: 5px; font-family: Helvetica, Arial, =
sans-serif; font-size: 16px !important; line-height: 20px !important; text-=
decoration: line-through; color:#848484 !important; font-weight: 100;"> $14=
9 </td> <td class=3D"nameFont" align=3D"left" valign=3D"top" style=3D"font-=
family: Helvetica, Arial, sans-serif; font-size: 16px !important; line-heig=
ht: 20px !important; color:#53A318 !important; font-weight: 300; text-decor=
ation: none; color: #88b74f;"> $26.99 </td> </tr> </table> </td> </tr> </ta=
ble> </a></td> <td align=3D"right" style=3D"padding: 15px 15px 15px 0; back=
ground: #ffffff;" valign=3D"middle"><a href=3D"https://www.groupon.com/deal=
s/gg-bras-in-regular-and-plus-sizes?p=3D1&utm_source=3Dcrm_im&utm_medium=3D=
email&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8c=
d2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D=
0&s=3Dbody&c=3Dlink&d=3DMindstorm-Hero-3&utm_campaign=3Dde49ea14-4b8e-4355-=
adcd-cbdf2964b3cf_0_20161111" target=3D"_blank" style=3D"font-size: 18px !i=
mportant; line-height: 22px !important; color: #000000 !important; text-dec=
oration: none;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"font-f=
amily: Arial, Helvetica, sans-serif; font-size:14px !important; line-height=
:19px !important; color:#333; width:180px; background: #ffffff;" class=3D"h=
eroButton" align=3D"right" valign=3D"bottom"> <tr> <td height=3D"45" bgcolo=
r=3D"#82B548" background=3D"https://s3.grouponcdn.com/email/images/global_b=
uttons/pn-gradient-green.jpg" background-repeat=3D"repeat-x" style=3D"heigh=
t: 45px; text-align: center;"><a href=3D"https://www.groupon.com/deals/gg-b=
ras-in-regular-and-plus-sizes?p=3D1&utm_source=3Dcrm_im&utm_medium=3Demail&=
user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&dat=
e=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3D=
body&c=3Dbutton&d=3DGoods-PN-Hero&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cb=
df2964b3cf_0_20161111" style=3D"padding: 10px 0 10px 0; color:#ffffff; font=
-size:16px; font-weight: 500; text-decoration:none;">VIEW&nbsp;DEAL</a></td=
> </tr> </table> </a></td> </tr> </table> <table cellpadding=3D"0" cellspac=
ing=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Helvetica=
, Arial, sans-serif; color:#000000; font-weight: 100; width: 100%; backgrou=
nd: #fffffff;" align=3D"center"> <tr> <td align=3D"center"> <table cellpadd=
ing=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font=
-family: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; wid=
th: 600px;" align=3D"center" class=3D"inner_container"> <tr> <td class=3D"b=
anner_mobile" align=3D"center" style=3D"padding-top:10px; display:none; fon=
t-size:0; max-height:0; line-height:0; mso-hide: all;" align=3D"center"><a =
href=3D"https://www.groupon.com/occasion/doorbusters?utm_source=3Dcrm_im&ut=
m_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134c=
f386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=
=3DUS&tx=3D0&s=3Dbody&c=3Dbanner&d=3Dmiddle-banner&utm_campaign=3Dde49ea14-=
4b8e-4355-adcd-cbdf2964b3cf_0_20161111" style=3D"color:#0185C6; text-decora=
tion:none;" target=3D"_blank"><img class=3D"banner_mobile" src=3D"https://i=
mg.grouponcdn.com/deal/31jX8pEUHSgU74aG9qYS9UztZgMa/31-460x120" style=3D"pa=
dding:0px; display:none; font-size:0; max-height:0; line-height:0; mso-hide=
: all;" border=3D"0" alt=3D"12 Days of Doorbusters" title=3D"12 Days of Doo=
rbusters" /></a></td> </tr> </table> <table class=3D"display-off" cellpaddi=
ng=3D"0" cellspacing=3D"0" style=3D"font-family: Arial, Helvetica, sans-ser=
if; font-size:14px !important; line-height:19px !important; color:#333; wid=
th: 600px;" align=3D"center"> <tr> <td align=3D"center" style=3D"padding-to=
p: 3.5%;"><a href=3D"https://www.groupon.com/occasion/doorbusters?utm_sourc=
e=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806f=
bf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-002=
59069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbanner&d=3Dmiddle-banner&utm_campaig=
n=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" style=3D"color:#0185C6=
; text-decoration:none;" target=3D"_blank"><img src=3D"https://img.grouponc=
dn.com/deal/29XeYNvy1GcJQPpvnM4p1Gczgnoc/29-600x100" style=3D"display: bloc=
k; border: none; font-size:12px; width: 100%; border-bottom: 1px solid #ccc=
ccc;" alt=3D"12 Days of Doorbusters" title=3D"https://www.groupon.com/occas=
ion/doorbusters?" /></a></td> </tr> </table> </td> </tr> </table> <table st=
yle=3D"width: 10px; background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</t=
able> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; b=
order-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#000000; =
font-weight: 100; width: 600px; background: #FFFFFF" align=3D"center" class=
=3D"inner_container"> <tr> <td valign=3D"top" align=3D"left" width=3D"100%"=
 style=3D"width: 600px;" class=3D"inner_container"> <!--[if (gte mso 9)|(IE=
)]> <table width=3D"600" align=3D"center" cellpadding=3D"0" cellspacing=3D"=
0" border=3D"0"> <tr> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif=
]--> <a href=3D"https://www.groupon.com/deals/gg-quilted-sofa-orthopedic-pe=
t-bed?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574=
337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c23=
4c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGood=
s-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" target=
=3D"_blank" style=3D"text-decoration:none;"> <table cellpadding=3D"0" cells=
pacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Helvet=
ica, Arial, sans-serif; color:#000000; font-weight: 100; background: #fffff=
f; width:290px;" valign=3D"top" class=3D"inner_container"align=3D'left'> <t=
r> <td style=3D"width:290px;" align=3D"center" valign=3D"top"> <table cellp=
adding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; f=
ont-family: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; =
background: #f2f2f2; width:100%;"> <tr> <td valign=3D"top" align=3D"center"=
 width=3D"290" style=3D"width:290px;" class=3D"inner_container"><a href=3D"=
https://www.groupon.com/deals/gg-quilted-sofa-orthopedic-pet-bed?p=3D2&utm_=
source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8=
f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c=
0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=
=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" style=3D"display: block=
; border: none;" target=3D"_blank"><img src=3D"https://img.grouponcdn.com/d=
eal/2LsmKD9sbhh7hbHxj2fgjQ9VZdsT/2L-1500x900/v1/c300x182.jpg" width=3D"290"=
 style=3D"display: block; border: none; width: 290px;" class=3D"secondary-1=
00" alt=3D"Furhaven Deluxe Quilted Sofa-Style Orthopedic Pet Bed " /></a></=
td> </tr> <tr> <td style=3D"padding:16px;"> <table cellpadding=3D"0" cellsp=
acing=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Helveti=
ca, Arial, sans-serif; color:#000000; font-weight: 100; background: #f2f2f2=
; width:100%;"> <tr> <td colspan=3D"2" class=3D"nameFont" style=3D"font-siz=
e: 14px !important; line-height: 18px !important; color:#000000 !important;=
 text-decoration: none; color: #333333 !important; width:100%;" align=3D"le=
ft" valign=3D"top"> Furhaven Orthopedic Pet Bed </td> </tr> <tr> <td class=
=3D"nameFont" align=3D"left" valign=3D"top"><a href=3D"https://www.groupon.=
com/deals/gg-quilted-sofa-orthopedic-pet-bed?p=3D2&utm_source=3Dcrm_im&utm_=
medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf3=
86561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=
=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-deals&utm_campaign=3D=
de49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" target=3D"_blank" style=3D=
"font-size: 14px !important; line-height: 18px !important; color:#000000 !i=
mportant; text-decoration: none;"><font color=3D"#e35205">Over 10,000 bough=
t</font></a></td> </tr> <tr> <td width=3D"70%" align=3D"left"> <span valign=
=3D"top" style=3D"padding-right: 5px; font-family: Helvetica, Arial, sans-s=
erif; font-size: 16px !important; line-height: 20px !important; text-decora=
tion: line-through; color:#848484 !important; font-weight: 100;" class=3D"n=
ameFont">$69.99</span> <span align=3D"left" valign=3D"top" style=3D"font-fa=
mily: Helvetica, Arial, sans-serif; font-size: 16px !important; line-height=
: 20px !important; color:#53A318 !important; font-weight: 300; text-decorat=
ion: none; color: #88b74f;" class=3D"nameFont">$19.99</span> </td> <td widt=
h=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" style=3D"font-f=
amily: Arial, Helvetica, sans-serif; font-size: 13px !important; line-heigh=
t: 17px !important; font-weight: normal; font-weight: 600; color: #0185c6 !=
important; text-decoration: none; text-align:right; white-space: nowrap;"><=
a href=3D"https://www.groupon.com/deals/gg-quilted-sofa-orthopedic-pet-bed?=
p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c82=
2070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-253=
9-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&u=
tm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" target=3D"_b=
lank" style=3D"text-decoration:none;"><font color=3D"#0185c6">View&nbsp;Dea=
l</font></a></td> </tr> </table> </td> </tr> <tr> <td style=3D"width: 10px;=
 background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> </tr> </table> <=
/td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--=
[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https://www.groupon.com=
/deals/gg-sports-camera?p=3D3&utm_source=3Dcrm_im&utm_medium=3Demail&user=
=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D=
20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody=
&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3c=
f_0_20161111" target=3D"_blank" style=3D"text-decoration:none;"> <table cel=
lpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0;=
 font-family: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100=
; background: #ffffff; width:290px;" valign=3D"top" class=3D"inner_containe=
r"align=3D'right'> <tr> <td style=3D"width:290px;" align=3D"center" valign=
=3D"top"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 non=
e; border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#0000=
00; font-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td valign=3D=
"top" align=3D"center" width=3D"290" style=3D"width:290px;" class=3D"inner_=
container"><a href=3D"https://www.groupon.com/deals/gg-sports-camera?p=3D3&=
utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee=
1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2=
-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_camp=
aign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" style=3D"display: b=
lock; border: none;" target=3D"_blank"><img src=3D"https://img.grouponcdn.c=
om/deal/2TgdkDS3ezYDUq31gTk3ehW2zzhZ/2T-1000x600/v1/c300x182.jpg" width=3D"=
290" style=3D"display: block; border: none; width: 290px;" class=3D"seconda=
ry-100" alt=3D"XtremePro HD 720p Sports Camera Bundle with Mounts & Accesso=
ries" /></a></td> </tr> <tr> <td style=3D"padding:16px;"> <table cellpaddin=
g=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-f=
amily: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; backg=
round: #f2f2f2; width:100%;"> <tr> <td colspan=3D"2" class=3D"nameFont" sty=
le=3D"font-size: 14px !important; line-height: 18px !important; color:#0000=
00 !important; text-decoration: none; color: #333333 !important; width:100%=
;" align=3D"left" valign=3D"top"> XtremePro HD 720p Sports Camera </td> </t=
r> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"top"><a href=3D"htt=
ps://www.groupon.com/deals/gg-sports-camera?p=3D2&utm_source=3Dcrm_im&utm_m=
edium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf38=
6561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3D=
US&tx=3D0&s=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-deals&utm_campaign=3Dde4=
9ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" target=3D"_blank" style=3D"fo=
nt-size: 14px !important; line-height: 18px !important; color:#000000 !impo=
rtant; text-decoration: none;"><font color=3D"#e35205">Over 200 bought</fon=
t></a></td> </tr> <tr> <td width=3D"70%" align=3D"left"> <span valign=3D"to=
p" style=3D"padding-right: 5px; font-family: Helvetica, Arial, sans-serif; =
font-size: 16px !important; line-height: 20px !important; text-decoration: =
line-through; color:#848484 !important; font-weight: 100;" class=3D"nameFon=
t">$329.99</span> <span align=3D"left" valign=3D"top" style=3D"font-family:=
 Helvetica, Arial, sans-serif; font-size: 16px !important; line-height: 20p=
x !important; font-weight: 300; text-decoration: none; color: #e35205;" cla=
ss=3D"nameFont">$69.99</span> </td> </tr> <tr> <td class=3D"nameFont" align=
=3D"left" valign=3D"top" style=3D"font-family: Helvetica, Arial, sans-serif=
; font-size: 13px; color: #e35205; text-decoration: none; font-weight: 500 =
!important;">Sale Ends 11/12</td> <td width=3D"30%" class=3D"nameFont" alig=
n=3D"right" valign=3D"top" style=3D"font-family: Helvetica, Arial, sans-ser=
if; font-size: 13px !important; line-height: 17px !important; font-weight: =
normal; font-weight: 600; color: #0185c6 !important; text-decoration: none;=
 text-align:right; white-space: nowrap;"><a href=3D"https://www.groupon.com=
/deals/gg-sports-camera?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=
=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D=
20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody=
&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3c=
f_0_20161111" target=3D"_blank" style=3D"text-decoration:none;"><font color=
=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </table> </td> </tr> <tr>=
 <td style=3D"width: 10px; background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&n=
bsp;</td> </tr> </table> </td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)=
]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if=
 (gte mso 9)|(IE)]> </tr> </table> <![endif]--> </tr> <tr> <td valign=3D"to=
p" align=3D"left" width=3D"100%" style=3D"width: 600px;" class=3D"inner_con=
tainer"> <!--[if (gte mso 9)|(IE)]> <table width=3D"600" align=3D"center" c=
ellpadding=3D"0" cellspacing=3D"0" border=3D"0"> <tr> <![endif]--> <!--[if =
(gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https://www.groupon.com/dea=
ls/gg-hp-elitebook-14-laptop-refurbished?p=3D4&utm_source=3Dcrm_im&utm_medi=
um=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf38656=
1ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&=
tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-a=
dcd-cbdf2964b3cf_0_20161111" target=3D"_blank" style=3D"text-decoration:non=
e;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; bo=
rder-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#000000; f=
ont-weight: 100; background: #ffffff; width:290px;" valign=3D"top" class=3D=
"inner_container"align=3D'left'> <tr> <td style=3D"width:290px;" align=3D"c=
enter" valign=3D"top"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"=
border: 0 none; border-spacing:0; font-family: Helvetica, Arial, sans-serif=
; color:#000000; font-weight: 100; background: #f2f2f2; width:100%;"> <tr> =
<td valign=3D"top" align=3D"center" width=3D"290" style=3D"width:290px;" cl=
ass=3D"inner_container"><a href=3D"https://www.groupon.com/deals/gg-hp-elit=
ebook-14-laptop-refurbished?p=3D4&utm_source=3Dcrm_im&utm_medium=3Demail&us=
er=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=
=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Db=
ody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b=
3cf_0_20161111" style=3D"display: block; border: none;" target=3D"_blank"><=
img src=3D"https://img.grouponcdn.com/deal/4H5VMUDUs4UGDfS2x6SXvXXdWfTt/4H-=
960x576/v1/c300x182.jpg" width=3D"290" style=3D"display: block; border: non=
e; width: 290px;" class=3D"secondary-100" alt=3D"HP EliteBook 14" Laptop (R=
efurbished)" /></a></td> </tr> <tr> <td style=3D"padding:16px;"> <table cel=
lpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0;=
 font-family: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100=
; background: #f2f2f2; width:100%;"> <tr> <td colspan=3D"2" class=3D"nameFo=
nt" style=3D"font-size: 14px !important; line-height: 18px !important; colo=
r:#000000 !important; text-decoration: none; color: #333333 !important; wid=
th:100%;" align=3D"left" valign=3D"top"> HP EliteBook 14" Laptop </td> </tr=
> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"top"><a href=3D"http=
s://www.groupon.com/deals/gg-hp-elitebook-14-laptop-refurbished?p=3D2&utm_s=
ource=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f=
806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0=
-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-deal=
s&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" target=3D=
"_blank" style=3D"font-size: 14px !important; line-height: 18px !important;=
 color:#000000 !important; text-decoration: none;"><font color=3D"#e35205">=
Over 350 bought</font></a></td> </tr> <tr> <td width=3D"70%" align=3D"left"=
> <span valign=3D"top" style=3D"padding-right: 5px; font-family: Helvetica,=
 Arial, sans-serif; font-size: 16px !important; line-height: 20px !importan=
t; text-decoration: line-through; color:#848484 !important; font-weight: 10=
0;" class=3D"nameFont">$899.99</span> <span align=3D"left" valign=3D"top" s=
tyle=3D"font-family: Helvetica, Arial, sans-serif; font-size: 16px !importa=
nt; line-height: 20px !important; color:#53A318 !important; font-weight: 30=
0; text-decoration: none; color: #88b74f;" class=3D"nameFont">$219.99</span=
> </td> <td width=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top"=
 style=3D"font-family: Arial, Helvetica, sans-serif; font-size: 13px !impor=
tant; line-height: 17px !important; font-weight: normal; font-weight: 600; =
color: #0185c6 !important; text-decoration: none; text-align:right; white-s=
pace: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-hp-elitebook-14-=
laptop-refurbished?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bf=
d7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D2016111=
1&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbu=
tton&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_201=
61111" target=3D"_blank" style=3D"text-decoration:none;"><font color=3D"#01=
85c6">View&nbsp;Deal</font></a></td> </tr> </table> </td> </tr> <tr> <td st=
yle=3D"width: 10px; background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</t=
d> </tr> </table> </td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td=
> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"http=
s://www.groupon.com/deals/gg-acoustic-guitar-with-case-strap-tuner-extra-st=
ring-set?p=3D5&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf=
574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79=
c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DG=
oods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" tar=
get=3D"_blank" style=3D"text-decoration:none;"> <table cellpadding=3D"0" ce=
llspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Hel=
vetica, Arial, sans-serif; color:#000000; font-weight: 100; background: #ff=
ffff; width:290px;" valign=3D"top" class=3D"inner_container"align=3D'right'=
> <tr> <td style=3D"width:290px;" align=3D"center" valign=3D"top"> <table c=
ellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:=
0; font-family: Helvetica, Arial, sans-serif; color:#000000; font-weight: 1=
00; background: #f2f2f2; width:100%;"> <tr> <td valign=3D"top" align=3D"cen=
ter" width=3D"290" style=3D"width:290px;" class=3D"inner_container"><a href=
=3D"https://www.groupon.com/deals/gg-acoustic-guitar-with-case-strap-tuner-=
extra-string-set?p=3D5&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7=
c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&=
uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dimag=
e&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_201611=
11" style=3D"display: block; border: none;" target=3D"_blank"><img src=3D"h=
ttps://img.grouponcdn.com/deal/2Wd9khochgKzNT2datoanUeycoep/2W-960x576/v1/c=
300x182.jpg" width=3D"290" style=3D"display: block; border: none; width: 29=
0px;" class=3D"secondary-100" alt=3D"Acoustic Guitar with Case, Strap, Tune=
r, and Extra String Set" /></a></td> </tr> <tr> <td style=3D"padding:16px;"=
> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; borde=
r-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#000000; font=
-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td colspan=3D"2" cla=
ss=3D"nameFont" style=3D"font-size: 14px !important; line-height: 18px !imp=
ortant; color:#000000 !important; text-decoration: none; color: #333333 !im=
portant; width:100%;" align=3D"left" valign=3D"top"> Acoustic-Guitar Kit </=
td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"top"><a href=
=3D"https://www.groupon.com/deals/gg-acoustic-guitar-with-case-strap-tuner-=
extra-string-set?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7=
c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&=
uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutt=
on&d=3DMindstorm-Hero-3-deals&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf29=
64b3cf_0_20161111" target=3D"_blank" style=3D"font-size: 14px !important; l=
ine-height: 18px !important; color:#000000 !important; text-decoration: non=
e;"><font color=3D"#e35205">Over 150 bought</font></a></td> </tr> <tr> <td =
width=3D"70%" align=3D"left"> <span valign=3D"top" style=3D"padding-right: =
5px; font-family: Helvetica, Arial, sans-serif; font-size: 16px !important;=
 line-height: 20px !important; text-decoration: line-through; color:#848484=
 !important; font-weight: 100;" class=3D"nameFont">$89.95</span> <span alig=
n=3D"left" valign=3D"top" style=3D"font-family: Helvetica, Arial, sans-seri=
f; font-size: 16px !important; line-height: 20px !important; color:#53A318 =
!important; font-weight: 300; text-decoration: none; color: #88b74f;" class=
=3D"nameFont">$29.99</span> </td> <td width=3D"30%" class=3D"nameFont" alig=
n=3D"right" valign=3D"top" style=3D"font-family: Arial, Helvetica, sans-ser=
if; font-size: 13px !important; line-height: 17px !important; font-weight: =
normal; font-weight: 600; color: #0185c6 !important; text-decoration: none;=
 text-align:right; white-space: nowrap;"><a href=3D"https://www.groupon.com=
/deals/gg-acoustic-guitar-with-case-strap-tuner-extra-string-set?p=3D2&utm_=
source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8=
f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c=
0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaig=
n=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" target=3D"_blank" styl=
e=3D"text-decoration:none;"><font color=3D"#0185c6">View&nbsp;Deal</font></=
a></td> </tr> </table> </td> </tr> <tr> <td style=3D"width: 10px; backgroun=
d: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> </tr> </table> </td> </tr>=
 </table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte m=
so 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </tr> </table> <=
![endif]--> </tr> <tr> <td valign=3D"top" align=3D"left" width=3D"100%" sty=
le=3D"width: 600px;" class=3D"inner_container"> <!--[if (gte mso 9)|(IE)]> =
<table width=3D"600" align=3D"center" cellpadding=3D"0" cellspacing=3D"0" b=
order=3D"0"> <tr> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]-->=
 <a href=3D"https://www.groupon.com/deals/gg-happy-holidays-graphic-tees?p=
=3D6&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822=
070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539=
-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&ut=
m_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" target=3D"_bl=
ank" style=3D"text-decoration:none;"> <table cellpadding=3D"0" cellspacing=
=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Helvetica, A=
rial, sans-serif; color:#000000; font-weight: 100; background: #ffffff; wid=
th:290px;" valign=3D"top" class=3D"inner_container"align=3D'left'> <tr> <td=
 style=3D"width:290px;" align=3D"center" valign=3D"top"> <table cellpadding=
=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-fa=
mily: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; backgr=
ound: #f2f2f2; width:100%;"> <tr> <td valign=3D"top" align=3D"center" width=
=3D"290" style=3D"width:290px;" class=3D"inner_container"><a href=3D"https:=
//www.groupon.com/deals/gg-happy-holidays-graphic-tees?p=3D6&utm_source=3Dc=
rm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2=
acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069=
d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Dde49ea1=
4-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" style=3D"display: block; border: =
none;" target=3D"_blank"><img src=3D"https://img.grouponcdn.com/deal/2t7QRY=
YcZu5a4MFsS9wpusxG6Cf4/2t-2021x1213/v1/c300x182.jpg" width=3D"290" style=3D=
"display: block; border: none; width: 290px;" class=3D"secondary-100" alt=
=3D"Men's Holiday Graphic Tees" /></a></td> </tr> <tr> <td style=3D"padding=
:16px;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none=
; border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#00000=
0; font-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td colspan=3D=
"2" class=3D"nameFont" style=3D"font-size: 14px !important; line-height: 18=
px !important; color:#000000 !important; text-decoration: none; color: #333=
333 !important; width:100%;" align=3D"left" valign=3D"top"> Men's Holiday G=
raphic Tees </td> </tr> <tr> <td width=3D"70%" align=3D"left"> <span valign=
=3D"top" style=3D"padding-right: 5px; font-family: Helvetica, Arial, sans-s=
erif; font-size: 16px !important; line-height: 20px !important; text-decora=
tion: line-through; color:#848484 !important; font-weight: 100;" class=3D"n=
ameFont">$18.99</span> <span align=3D"left" valign=3D"top" style=3D"font-fa=
mily: Helvetica, Arial, sans-serif; font-size: 16px !important; line-height=
: 20px !important; color:#53A318 !important; font-weight: 300; text-decorat=
ion: none; color: #88b74f;" class=3D"nameFont">$12.99</span> </td> <td widt=
h=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" style=3D"font-f=
amily: Arial, Helvetica, sans-serif; font-size: 13px !important; line-heigh=
t: 17px !important; font-weight: normal; font-weight: 600; color: #0185c6 !=
important; text-decoration: none; text-align:right; white-space: nowrap;"><=
a href=3D"https://www.groupon.com/deals/gg-happy-holidays-graphic-tees?p=3D=
2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070=
ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11=
e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_c=
ampaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" target=3D"_blank=
" style=3D"text-decoration:none;"><font color=3D"#0185c6">View&nbsp;Deal</f=
ont></a></td> </tr> </table> </td> </tr> <tr> <td style=3D"width: 10px; bac=
kground: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> </tr> </table> </td>=
 </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if =
(gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https://www.groupon.com/dea=
ls/gg-all-new-2016-vizio-43-48-smartcast-e-series?p=3D7&utm_source=3Dcrm_im=
&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac1=
34cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&=
CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b=
8e-4355-adcd-cbdf2964b3cf_0_20161111" target=3D"_blank" style=3D"text-decor=
ation:none;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0=
 none; border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#=
000000; font-weight: 100; background: #ffffff; width:290px;" valign=3D"top"=
 class=3D"inner_container"align=3D'right'> <tr> <td style=3D"width:290px;" =
align=3D"center" valign=3D"top"> <table cellpadding=3D"0" cellspacing=3D"0"=
 style=3D"border: 0 none; border-spacing:0; font-family: Helvetica, Arial, =
sans-serif; color:#000000; font-weight: 100; background: #f2f2f2; width:100=
%;"> <tr> <td valign=3D"top" align=3D"center" width=3D"290" style=3D"width:=
290px;" class=3D"inner_container"><a href=3D"https://www.groupon.com/deals/=
gg-all-new-2016-vizio-43-48-smartcast-e-series?p=3D7&utm_source=3Dcrm_im&ut=
m_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134c=
f386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=
=3DUS&tx=3D0&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4=
355-adcd-cbdf2964b3cf_0_20161111" style=3D"display: block; border: none;" t=
arget=3D"_blank"><img src=3D"https://img.grouponcdn.com/deal/3Ptd6ETJjayjaF=
SGdLkP73GQFUsj/3P-1400x840/v1/c300x182.jpg" width=3D"290" style=3D"display:=
 block; border: none; width: 290px;" class=3D"secondary-100" alt=3D"Vizio S=
martCast E-Series LED 4K Smart Home Theater Display-Refurbished" /></a></td=
> </tr> <tr> <td style=3D"padding:16px;"> <table cellpadding=3D"0" cellspac=
ing=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Helvetica=
, Arial, sans-serif; color:#000000; font-weight: 100; background: #f2f2f2; =
width:100%;"> <tr> <td colspan=3D"2" class=3D"nameFont" style=3D"font-size:=
 14px !important; line-height: 18px !important; color:#000000 !important; t=
ext-decoration: none; color: #333333 !important; width:100%;" align=3D"left=
" valign=3D"top"> Vizio LED 4K Ultra HD Smart TVs </td> </tr> <tr> <td clas=
s=3D"nameFont" align=3D"left" valign=3D"top"><a href=3D"https://www.groupon=
.com/deals/gg-all-new-2016-vizio-43-48-smartcast-e-series?p=3D2&utm_source=
=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fb=
f5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-0025=
9069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-deals&utm=
_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" target=3D"_bla=
nk" style=3D"font-size: 14px !important; line-height: 18px !important; colo=
r:#000000 !important; text-decoration: none;"><font color=3D"#e35205">Over =
1,000 bought</font></a></td> </tr> <tr> <td width=3D"70%" align=3D"left"> <=
span valign=3D"top" style=3D"padding-right: 5px; font-family: Helvetica, Ar=
ial, sans-serif; font-size: 16px !important; line-height: 20px !important; =
text-decoration: line-through; color:#848484 !important; font-weight: 100;"=
 class=3D"nameFont">$469.99</span> <span align=3D"left" valign=3D"top" styl=
e=3D"font-family: Helvetica, Arial, sans-serif; font-size: 16px !important;=
 line-height: 20px !important; color:#53A318 !important; font-weight: 300; =
text-decoration: none; color: #88b74f;" class=3D"nameFont">$269.99</span> <=
/td> <td width=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" st=
yle=3D"font-family: Arial, Helvetica, sans-serif; font-size: 13px !importan=
t; line-height: 17px !important; font-weight: normal; font-weight: 600; col=
or: #0185c6 !important; text-decoration: none; text-align:right; white-spac=
e: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-all-new-2016-vizio-=
43-48-smartcast-e-series?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=
=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D=
20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody=
&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3c=
f_0_20161111" target=3D"_blank" style=3D"text-decoration:none;"><font color=
=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </table> </td> </tr> <tr>=
 <td style=3D"width: 10px; background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&n=
bsp;</td> </tr> </table> </td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)=
]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if=
 (gte mso 9)|(IE)]> </tr> </table> <![endif]--> </tr> <tr> <td valign=3D"to=
p" align=3D"left" width=3D"100%" style=3D"width: 600px;" class=3D"inner_con=
tainer"> <!--[if (gte mso 9)|(IE)]> <table width=3D"600" align=3D"center" c=
ellpadding=3D"0" cellspacing=3D"0" border=3D"0"> <tr> <![endif]--> <!--[if =
(gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https://www.groupon.com/dea=
ls/gg-apple-ipad-2-3-4-air-or-air-2-4?p=3D8&utm_source=3Dcrm_im&utm_medium=
=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561e=
d8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=
=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adc=
d-cbdf2964b3cf_0_20161111" target=3D"_blank" style=3D"text-decoration:none;=
"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; bord=
er-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#000000; fon=
t-weight: 100; background: #ffffff; width:290px;" valign=3D"top" class=3D"i=
nner_container"align=3D'left'> <tr> <td style=3D"width:290px;" align=3D"cen=
ter" valign=3D"top"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"bo=
rder: 0 none; border-spacing:0; font-family: Helvetica, Arial, sans-serif; =
color:#000000; font-weight: 100; background: #f2f2f2; width:100%;"> <tr> <t=
d valign=3D"top" align=3D"center" width=3D"290" style=3D"width:290px;" clas=
s=3D"inner_container"><a href=3D"https://www.groupon.com/deals/gg-apple-ipa=
d-2-3-4-air-or-air-2-4?p=3D8&utm_source=3Dcrm_im&utm_medium=3Demail&user=3D=
d8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D201=
61111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=
=3Dimage&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0=
_20161111" style=3D"display: block; border: none;" target=3D"_blank"><img s=
rc=3D"https://img.grouponcdn.com/deal/2YRMD6z4WZZ35xRZ8gxVRcXBx9hG/2Y-1000x=
600/v1/c300x182.jpg" width=3D"290" style=3D"display: block; border: none; w=
idth: 290px;" class=3D"secondary-100" alt=3D"Apple iPad 2, 3, 4, Air, or Ai=
r 2 (WiFi Only) (Refurbished)" /></a></td> </tr> <tr> <td style=3D"padding:=
16px;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none;=
 border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#000000=
; font-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td colspan=3D"=
2" class=3D"nameFont" style=3D"font-size: 14px !important; line-height: 18p=
x !important; color:#000000 !important; text-decoration: none; color: #3333=
33 !important; width:100%;" align=3D"left" valign=3D"top"> Apple iPad 2, 3,=
 4, Air or Air 2 </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" val=
ign=3D"top"><a href=3D"https://www.groupon.com/deals/gg-apple-ipad-2-3-4-ai=
r-or-air-2-4?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf=
03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=
=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton=
&d=3DMindstorm-Hero-3-deals&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964=
b3cf_0_20161111" target=3D"_blank" style=3D"font-size: 14px !important; lin=
e-height: 18px !important; color:#000000 !important; text-decoration: none;=
"><font color=3D"#e35205">Over 150 bought</font></a></td> </tr> <tr> <td wi=
dth=3D"70%" align=3D"left"> <span valign=3D"top" style=3D"padding-right: 5p=
x; font-family: Helvetica, Arial, sans-serif; font-size: 16px !important; l=
ine-height: 20px !important; text-decoration: line-through; color:#848484 !=
important; font-weight: 100;" class=3D"nameFont">$249</span> <span align=3D=
"left" valign=3D"top" style=3D"font-family: Helvetica, Arial, sans-serif; f=
ont-size: 16px !important; line-height: 20px !important; font-weight: 300; =
text-decoration: none; color: #e35205;" class=3D"nameFont">$149.99</span> <=
/td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"top" style=
=3D"font-family: Helvetica, Arial, sans-serif; font-size: 13px; color: #e35=
205; text-decoration: none; font-weight: 500 !important;">Sale Ends 11/14</=
td> <td width=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" sty=
le=3D"font-family: Helvetica, Arial, sans-serif; font-size: 13px !important=
; line-height: 17px !important; font-weight: normal; font-weight: 600; colo=
r: #0185c6 !important; text-decoration: none; text-align:right; white-space=
: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-apple-ipad-2-3-4-air=
-or-air-2-4?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf0=
3cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3D=
f79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=
=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111"=
 target=3D"_blank" style=3D"text-decoration:none;"><font color=3D"#0185c6">=
View&nbsp;Deal</font></a></td> </tr> </table> </td> </tr> <tr> <td style=3D=
"width: 10px; background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> </t=
r> </table> </td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![e=
ndif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https://ww=
w.groupon.com/deals/gg-nfl-3d-logo-puzzle-set-200-piece?p=3D9&utm_source=3D=
crm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c=
2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-0025906=
9d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Dde49e=
a14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" target=3D"_blank" style=3D"text=
-decoration:none;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"bor=
der: 0 none; border-spacing:0; font-family: Helvetica, Arial, sans-serif; c=
olor:#000000; font-weight: 100; background: #ffffff; width:290px;" valign=
=3D"top" class=3D"inner_container"align=3D'right'> <tr> <td style=3D"width:=
290px;" align=3D"center" valign=3D"top"> <table cellpadding=3D"0" cellspaci=
ng=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Helvetica,=
 Arial, sans-serif; color:#000000; font-weight: 100; background: #f2f2f2; w=
idth:100%;"> <tr> <td valign=3D"top" align=3D"center" width=3D"290" style=
=3D"width:290px;" class=3D"inner_container"><a href=3D"https://www.groupon.=
com/deals/gg-nfl-3d-logo-puzzle-set-200-piece?p=3D9&utm_source=3Dcrm_im&utm=
_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf=
386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=
=3DUS&tx=3D0&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4=
355-adcd-cbdf2964b3cf_0_20161111" style=3D"display: block; border: none;" t=
arget=3D"_blank"><img src=3D"https://img.grouponcdn.com/deal/3o8nnR4N2jSYuk=
zKTyZLWaL5eJq/3o-3000x1801/v1/c300x182.jpg" width=3D"290" style=3D"display:=
 block; border: none; width: 290px;" class=3D"secondary-100" alt=3D"NFL 3D =
Logo Puzzle Set (200pc.)" /></a></td> </tr> <tr> <td style=3D"padding:16px;=
"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; bord=
er-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#000000; fon=
t-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td colspan=3D"2" cl=
ass=3D"nameFont" style=3D"font-size: 14px !important; line-height: 18px !im=
portant; color:#000000 !important; text-decoration: none; color: #333333 !i=
mportant; width:100%;" align=3D"left" valign=3D"top"> NFL 3D Logo Puzzle Se=
t (200pc.) </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D=
"top"><a href=3D"https://www.groupon.com/deals/gg-nfl-3d-logo-puzzle-set-20=
0-piece?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf5=
74337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c=
234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DMi=
ndstorm-Hero-3-deals&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_=
20161111" target=3D"_blank" style=3D"font-size: 14px !important; line-heigh=
t: 18px !important; color:#000000 !important; text-decoration: none;"><font=
 color=3D"#e35205">Over 100 bought</font></a></td> </tr> <tr> <td width=3D"=
70%" align=3D"left"> <span valign=3D"top" style=3D"padding-right: 5px; font=
-family: Helvetica, Arial, sans-serif; font-size: 16px !important; line-hei=
ght: 20px !important; text-decoration: line-through; color:#848484 !importa=
nt; font-weight: 100;" class=3D"nameFont">$19.99</span> <span align=3D"left=
" valign=3D"top" style=3D"font-family: Helvetica, Arial, sans-serif; font-s=
ize: 16px !important; line-height: 20px !important; color:#53A318 !importan=
t; font-weight: 300; text-decoration: none; color: #88b74f;" class=3D"nameF=
ont">$12.99</span> </td> <td width=3D"30%" class=3D"nameFont" align=3D"righ=
t" valign=3D"top" style=3D"font-family: Arial, Helvetica, sans-serif; font-=
size: 13px !important; line-height: 17px !important; font-weight: normal; f=
ont-weight: 600; color: #0185c6 !important; text-decoration: none; text-ali=
gn:right; white-space: nowrap;"><a href=3D"https://www.groupon.com/deals/gg=
-nfl-3d-logo-puzzle-set-200-piece?p=3D2&utm_source=3Dcrm_im&utm_medium=3Dem=
ail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2=
&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&=
s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbd=
f2964b3cf_0_20161111" target=3D"_blank" style=3D"text-decoration:none;"><fo=
nt color=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </table> </td> </=
tr> <tr> <td style=3D"width: 10px; background: #ffffff;">&nbsp;&nbsp;&nbsp;=
&nbsp;&nbsp;</td> </tr> </table> </td> </tr> </table> </a> <!--[if (gte mso=
 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </td> <![endif]-->=
 <!--[if (gte mso 9)|(IE)]> </tr> </table> <![endif]--> </tr> <tr> <td vali=
gn=3D"top" align=3D"left" width=3D"100%" style=3D"width: 600px;" class=3D"i=
nner_container"> <!--[if (gte mso 9)|(IE)]> <table width=3D"600" align=3D"c=
enter" cellpadding=3D"0" cellspacing=3D"0" border=3D"0"> <tr> <![endif]--> =
<!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https://www.groupon=
.com/deals/gg-godinger-insulated-stainless-steel-water-bottle?p=3D10&utm_so=
urce=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f8=
06fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-=
00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=
=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" target=3D"_blank" style=
=3D"text-decoration:none;"> <table cellpadding=3D"0" cellspacing=3D"0" styl=
e=3D"border: 0 none; border-spacing:0; font-family: Helvetica, Arial, sans-=
serif; color:#000000; font-weight: 100; background: #ffffff; width:290px;" =
valign=3D"top" class=3D"inner_container"align=3D'left'> <tr> <td style=3D"w=
idth:290px;" align=3D"center" valign=3D"top"> <table cellpadding=3D"0" cell=
spacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Helve=
tica, Arial, sans-serif; color:#000000; font-weight: 100; background: #f2f2=
f2; width:100%;"> <tr> <td valign=3D"top" align=3D"center" width=3D"290" st=
yle=3D"width:290px;" class=3D"inner_container"><a href=3D"https://www.group=
on.com/deals/gg-godinger-insulated-stainless-steel-water-bottle?p=3D10&utm_=
source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8=
f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c=
0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=
=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" style=3D"display: block=
; border: none;" target=3D"_blank"><img src=3D"https://img.grouponcdn.com/d=
eal/2x88ynJsCJ8DE5f4YBnicw8MLhjp/2x-960x576/v1/c300x182.jpg" width=3D"290" =
style=3D"display: block; border: none; width: 290px;" class=3D"secondary-10=
0" alt=3D"Godinger 24-Hour Insulated Stainless Steel Water Bottle" /></a></=
td> </tr> <tr> <td style=3D"padding:16px;"> <table cellpadding=3D"0" cellsp=
acing=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Helveti=
ca, Arial, sans-serif; color:#000000; font-weight: 100; background: #f2f2f2=
; width:100%;"> <tr> <td colspan=3D"2" class=3D"nameFont" style=3D"font-siz=
e: 14px !important; line-height: 18px !important; color:#000000 !important;=
 text-decoration: none; color: #333333 !important; width:100%;" align=3D"le=
ft" valign=3D"top"> Godinger Insulated Water Bottle </td> </tr> <tr> <td cl=
ass=3D"nameFont" align=3D"left" valign=3D"top"><a href=3D"https://www.group=
on.com/deals/gg-godinger-insulated-stainless-steel-water-bottle?p=3D2&utm_s=
ource=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f=
806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0=
-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-deal=
s&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" target=3D=
"_blank" style=3D"font-size: 14px !important; line-height: 18px !important;=
 color:#000000 !important; text-decoration: none;"><font color=3D"#e35205">=
Over 200 bought</font></a></td> </tr> <tr> <td width=3D"70%" align=3D"left"=
> <span valign=3D"top" style=3D"padding-right: 5px; font-family: Helvetica,=
 Arial, sans-serif; font-size: 16px !important; line-height: 20px !importan=
t; text-decoration: line-through; color:#848484 !important; font-weight: 10=
0;" class=3D"nameFont">$24.99</span> <span align=3D"left" valign=3D"top" st=
yle=3D"font-family: Helvetica, Arial, sans-serif; font-size: 16px !importan=
t; line-height: 20px !important; color:#53A318 !important; font-weight: 300=
; text-decoration: none; color: #88b74f;" class=3D"nameFont">$12.99</span> =
</td> <td width=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" s=
tyle=3D"font-family: Arial, Helvetica, sans-serif; font-size: 13px !importa=
nt; line-height: 17px !important; font-weight: normal; font-weight: 600; co=
lor: #0185c6 !important; text-decoration: none; text-align:right; white-spa=
ce: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-godinger-insulated=
-stainless-steel-water-bottle?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&=
user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&dat=
e=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3D=
body&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf296=
4b3cf_0_20161111" target=3D"_blank" style=3D"text-decoration:none;"><font c=
olor=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </table> </td> </tr> =
<tr> <td style=3D"width: 10px; background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbs=
p;&nbsp;</td> </tr> </table> </td> </tr> </table> </a> <!--[if (gte mso 9)|=
(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a h=
ref=3D"https://www.groupon.com/deals/gg-harman-kardon-onyx-studio-bluetooth=
-speaker-refurbished?p=3D11&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd=
8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D2016=
1111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=
=3Dbutton&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_=
0_20161111" target=3D"_blank" style=3D"text-decoration:none;"> <table cellp=
adding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; f=
ont-family: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; =
background: #ffffff; width:290px;" valign=3D"top" class=3D"inner_container"=
align=3D'right'> <tr> <td style=3D"width:290px;" align=3D"center" valign=3D=
"top"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; =
border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#000000;=
 font-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td valign=3D"to=
p" align=3D"center" width=3D"290" style=3D"width:290px;" class=3D"inner_con=
tainer"><a href=3D"https://www.groupon.com/deals/gg-harman-kardon-onyx-stud=
io-bluetooth-speaker-refurbished?p=3D11&utm_source=3Dcrm_im&utm_medium=3Dem=
ail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2=
&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&=
s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf=
2964b3cf_0_20161111" style=3D"display: block; border: none;" target=3D"_bla=
nk"><img src=3D"https://img.grouponcdn.com/deal/4Xwm9J8uysTRfRUjb3EG2TJovcN=
t/4X-960x576/v1/c300x182.jpg" width=3D"290" style=3D"display: block; border=
: none; width: 290px;" class=3D"secondary-100" alt=3D"Harman Kardon Onyx St=
udio Bluetooth Speaker (Refurbished)" /></a></td> </tr> <tr> <td style=3D"p=
adding:16px;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: =
0 none; border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:=
#000000; font-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td cols=
pan=3D"2" class=3D"nameFont" style=3D"font-size: 14px !important; line-heig=
ht: 18px !important; color:#000000 !important; text-decoration: none; color=
: #333333 !important; width:100%;" align=3D"left" valign=3D"top"> Harman Ka=
rdon Bluetooth Speaker </td> </tr> <tr> <td class=3D"nameFont" align=3D"lef=
t" valign=3D"top"><a href=3D"https://www.groupon.com/deals/gg-harman-kardon=
-onyx-studio-bluetooth-speaker-refurbished?p=3D2&utm_source=3Dcrm_im&utm_me=
dium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386=
561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DU=
S&tx=3D0&s=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-deals&utm_campaign=3Dde49=
ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" target=3D"_blank" style=3D"fon=
t-size: 14px !important; line-height: 18px !important; color:#000000 !impor=
tant; text-decoration: none;"><font color=3D"#e35205">Over 1,000 bought</fo=
nt></a></td> </tr> <tr> <td width=3D"70%" align=3D"left"> <span valign=3D"t=
op" style=3D"padding-right: 5px; font-family: Helvetica, Arial, sans-serif;=
 font-size: 16px !important; line-height: 20px !important; text-decoration:=
 line-through; color:#848484 !important; font-weight: 100;" class=3D"nameFo=
nt">$399</span> <span align=3D"left" valign=3D"top" style=3D"font-family: H=
elvetica, Arial, sans-serif; font-size: 16px !important; line-height: 20px =
!important; color:#53A318 !important; font-weight: 300; text-decoration: no=
ne; color: #88b74f;" class=3D"nameFont">$99.99</span> </td> <td width=3D"30=
%" class=3D"nameFont" align=3D"right" valign=3D"top" style=3D"font-family: =
Arial, Helvetica, sans-serif; font-size: 13px !important; line-height: 17px=
 !important; font-weight: normal; font-weight: 600; color: #0185c6 !importa=
nt; text-decoration: none; text-align:right; white-space: nowrap;"><a href=
=3D"https://www.groupon.com/deals/gg-harman-kardon-onyx-studio-bluetooth-sp=
eaker-refurbished?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd=
7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111=
&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbut=
ton&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_2016=
1111" target=3D"_blank" style=3D"text-decoration:none;"><font color=3D"#018=
5c6">View&nbsp;Deal</font></a></td> </tr> </table> </td> </tr> <tr> <td sty=
le=3D"width: 10px; background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td=
> </tr> </table> </td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td>=
 <![endif]--> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte ms=
o 9)|(IE)]> </tr> </table> <![endif]--> </tr> <tr> <td valign=3D"top" align=
=3D"left" width=3D"100%" style=3D"width: 600px;" class=3D"inner_container">=
 <!--[if (gte mso 9)|(IE)]> <table width=3D"600" align=3D"center" cellpaddi=
ng=3D"0" cellspacing=3D"0" border=3D"0"> <tr> <![endif]--> <!--[if (gte mso=
 9)|(IE)]> <td> <![endif]--> <a href=3D"https://www.groupon.com/deals/gg-ki=
ds-ride-on-cars-3?p=3D12&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bf=
d7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D2016111=
1&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbu=
tton&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_201=
61111" target=3D"_blank" style=3D"text-decoration:none;"> <table cellpaddin=
g=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-f=
amily: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; backg=
round: #ffffff; width:290px;" valign=3D"top" class=3D"inner_container"align=
=3D'left'> <tr> <td style=3D"width:290px;" align=3D"center" valign=3D"top">=
 <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border=
-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#000000; font-=
weight: 100; background: #f2f2f2; width:100%;"> <tr> <td valign=3D"top" ali=
gn=3D"center" width=3D"290" style=3D"width:290px;" class=3D"inner_container=
"><a href=3D"https://www.groupon.com/deals/gg-kids-ride-on-cars-3?p=3D12&ut=
m_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1e=
d8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-8=
2c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campai=
gn=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" style=3D"display: blo=
ck; border: none;" target=3D"_blank"><img src=3D"https://img.grouponcdn.com=
/deal/JDs4kMdxbysyrAzMNVjnWHC6uGL/JD-2048x1229/v1/c300x182.jpg" width=3D"29=
0" style=3D"display: block; border: none; width: 290px;" class=3D"secondary=
-100" alt=3D"Kids Mercedes ML-350 & SLS 6V Ride-On Cars" /></a></td> </tr> =
<tr> <td style=3D"padding:16px;"> <table cellpadding=3D"0" cellspacing=3D"0=
" style=3D"border: 0 none; border-spacing:0; font-family: Helvetica, Arial,=
 sans-serif; color:#000000; font-weight: 100; background: #f2f2f2; width:10=
0%;"> <tr> <td colspan=3D"2" class=3D"nameFont" style=3D"font-size: 14px !i=
mportant; line-height: 18px !important; color:#000000 !important; text-deco=
ration: none; color: #333333 !important; width:100%;" align=3D"left" valign=
=3D"top"> Kids Mercedes 6V Ride-On Cars </td> </tr> <tr> <td class=3D"nameF=
ont" align=3D"left" valign=3D"top"><a href=3D"https://www.groupon.com/deals=
/gg-kids-ride-on-cars-3?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=
=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D=
20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody=
&c=3Dbutton&d=3DMindstorm-Hero-3-deals&utm_campaign=3Dde49ea14-4b8e-4355-ad=
cd-cbdf2964b3cf_0_20161111" target=3D"_blank" style=3D"font-size: 14px !imp=
ortant; line-height: 18px !important; color:#000000 !important; text-decora=
tion: none;"><font color=3D"#e35205">Over 300 bought</font></a></td> </tr> =
<tr> <td width=3D"70%" align=3D"left"> <span valign=3D"top" style=3D"paddin=
g-right: 5px; font-family: Helvetica, Arial, sans-serif; font-size: 16px !i=
mportant; line-height: 20px !important; text-decoration: line-through; colo=
r:#848484 !important; font-weight: 100;" class=3D"nameFont">$249.99</span> =
<span align=3D"left" valign=3D"top" style=3D"font-family: Helvetica, Arial,=
 sans-serif; font-size: 16px !important; line-height: 20px !important; colo=
r:#53A318 !important; font-weight: 300; text-decoration: none; color: #88b7=
4f;" class=3D"nameFont">$159.99</span> </td> <td width=3D"30%" class=3D"nam=
eFont" align=3D"right" valign=3D"top" style=3D"font-family: Arial, Helvetic=
a, sans-serif; font-size: 13px !important; line-height: 17px !important; fo=
nt-weight: normal; font-weight: 600; color: #0185c6 !important; text-decora=
tion: none; text-align:right; white-space: nowrap;"><a href=3D"https://www.=
groupon.com/deals/gg-kids-ride-on-cars-3?p=3D2&utm_source=3Dcrm_im&utm_medi=
um=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf38656=
1ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&=
tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-a=
dcd-cbdf2964b3cf_0_20161111" target=3D"_blank" style=3D"text-decoration:non=
e;"><font color=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </table> <=
/td> </tr> <tr> <td style=3D"width: 10px; background: #ffffff;">&nbsp;&nbsp=
;&nbsp;&nbsp;&nbsp;</td> </tr> </table> </td> </tr> </table> </a> <!--[if (=
gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![end=
if]--> <a href=3D"https://www.groupon.com/deals/gg-j-sport-by-jambu-windham=
-cold-weather-boot?p=3D13&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8b=
fd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D201611=
11&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Db=
utton&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20=
161111" target=3D"_blank" style=3D"text-decoration:none;"> <table cellpaddi=
ng=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-=
family: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; back=
ground: #ffffff; width:290px;" valign=3D"top" class=3D"inner_container"alig=
n=3D'right'> <tr> <td style=3D"width:290px;" align=3D"center" valign=3D"top=
"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; bord=
er-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#000000; fon=
t-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td valign=3D"top" a=
lign=3D"center" width=3D"290" style=3D"width:290px;" class=3D"inner_contain=
er"><a href=3D"https://www.groupon.com/deals/gg-j-sport-by-jambu-windham-co=
ld-weather-boot?p=3D13&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7=
c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&=
uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dimag=
e&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_201611=
11" style=3D"display: block; border: none;" target=3D"_blank"><img src=3D"h=
ttps://img.grouponcdn.com/deal/3knKeiBgdhmmtdj7nGuHkd3V1WvN/3k-1500x900/v1/=
c300x182.jpg" width=3D"290" style=3D"display: block; border: none; width: 2=
90px;" class=3D"secondary-100" alt=3D"JSport by Jambu Windham Women's Boots=
" /></a></td> </tr> <tr> <td style=3D"padding:16px;"> <table cellpadding=3D=
"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-famil=
y: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; backgroun=
d: #f2f2f2; width:100%;"> <tr> <td colspan=3D"2" class=3D"nameFont" style=
=3D"font-size: 14px !important; line-height: 18px !important; color:#000000=
 !important; text-decoration: none; color: #333333 !important; width:100%;"=
 align=3D"left" valign=3D"top"> JSport by Jambu Women's Boots </td> </tr> <=
tr> <td class=3D"nameFont" align=3D"left" valign=3D"top"><a href=3D"https:/=
/www.groupon.com/deals/gg-j-sport-by-jambu-windham-cold-weather-boot?p=3D2&=
utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee=
1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2=
-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3=
-deals&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" targ=
et=3D"_blank" style=3D"font-size: 14px !important; line-height: 18px !impor=
tant; color:#000000 !important; text-decoration: none;"><font color=3D"#e35=
205">Over 600 bought</font></a></td> </tr> <tr> <td width=3D"70%" align=3D"=
left"> <span valign=3D"top" style=3D"padding-right: 5px; font-family: Helve=
tica, Arial, sans-serif; font-size: 16px !important; line-height: 20px !imp=
ortant; text-decoration: line-through; color:#848484 !important; font-weigh=
t: 100;" class=3D"nameFont">$89.95</span> <span align=3D"left" valign=3D"to=
p" style=3D"font-family: Helvetica, Arial, sans-serif; font-size: 16px !imp=
ortant; line-height: 20px !important; font-weight: 300; text-decoration: no=
ne; color: #e35205;" class=3D"nameFont">$34.99</span> </td> </tr> <tr> <td =
class=3D"nameFont" align=3D"left" valign=3D"top" style=3D"font-family: Helv=
etica, Arial, sans-serif; font-size: 13px; color: #e35205; text-decoration:=
 none; font-weight: 500 !important;">Sale Ends 11/13</td> <td width=3D"30%"=
 class=3D"nameFont" align=3D"right" valign=3D"top" style=3D"font-family: He=
lvetica, Arial, sans-serif; font-size: 13px !important; line-height: 17px !=
important; font-weight: normal; font-weight: 600; color: #0185c6 !important=
; text-decoration: none; text-align:right; white-space: nowrap;"><a href=3D=
"https://www.groupon.com/deals/gg-j-sport-by-jambu-windham-cold-weather-boo=
t?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c=
822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2=
539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN=
&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" target=3D"=
_blank" style=3D"text-decoration:none;"><font color=3D"#0185c6">View&nbsp;D=
eal</font></a></td> </tr> </table> </td> </tr> <tr> <td style=3D"width: 10p=
x; background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> </tr> </table>=
 </td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!=
--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </tr=
> </table> <![endif]--> </tr> <tr> <td valign=3D"top" align=3D"left" width=
=3D"100%" style=3D"width: 600px;" class=3D"inner_container"> <!--[if (gte m=
so 9)|(IE)]> <table width=3D"600" align=3D"center" cellpadding=3D"0" cellsp=
acing=3D"0" border=3D"0"> <tr> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td>=
 <![endif]--> <a href=3D"https://www.groupon.com/deals/gg-world-tech-toys-t=
ool-swat-cash-register-bbq-grill-kitchen-play?p=3D14&utm_source=3Dcrm_im&ut=
m_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134c=
f386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=
=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-=
4355-adcd-cbdf2964b3cf_0_20161111" target=3D"_blank" style=3D"text-decorati=
on:none;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 no=
ne; border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#000=
000; font-weight: 100; background: #ffffff; width:290px;" valign=3D"top" cl=
ass=3D"inner_container"align=3D'left'> <tr> <td style=3D"width:290px;" alig=
n=3D"center" valign=3D"top"> <table cellpadding=3D"0" cellspacing=3D"0" sty=
le=3D"border: 0 none; border-spacing:0; font-family: Helvetica, Arial, sans=
-serif; color:#000000; font-weight: 100; background: #f2f2f2; width:100%;">=
 <tr> <td valign=3D"top" align=3D"center" width=3D"290" style=3D"width:290p=
x;" class=3D"inner_container"><a href=3D"https://www.groupon.com/deals/gg-w=
orld-tech-toys-tool-swat-cash-register-bbq-grill-kitchen-play?p=3D14&utm_so=
urce=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f8=
06fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-=
00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=
=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" style=3D"display: block=
; border: none;" target=3D"_blank"><img src=3D"https://img.grouponcdn.com/d=
eal/2nLuRPHnLh6k5tcEytBr391HSChJ/2n-1500x900/v1/c300x182.jpg" width=3D"290"=
 style=3D"display: block; border: none; width: 290px;" class=3D"secondary-1=
00" alt=3D"World Tech Toys Kids' Playsets" /></a></td> </tr> <tr> <td style=
=3D"padding:16px;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"bor=
der: 0 none; border-spacing:0; font-family: Helvetica, Arial, sans-serif; c=
olor:#000000; font-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td=
 colspan=3D"2" class=3D"nameFont" style=3D"font-size: 14px !important; line=
-height: 18px !important; color:#000000 !important; text-decoration: none; =
color: #333333 !important; width:100%;" align=3D"left" valign=3D"top"> Worl=
d Tech Toys Kids' Playsets </td> </tr> <tr> <td class=3D"nameFont" align=3D=
"left" valign=3D"top"><a href=3D"https://www.groupon.com/deals/gg-world-tec=
h-toys-tool-swat-cash-register-bbq-grill-kitchen-play?p=3D2&utm_source=3Dcr=
m_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2a=
cac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d=
5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DMindstorm-Hero-3-deals&utm_camp=
aign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" target=3D"_blank" s=
tyle=3D"font-size: 14px !important; line-height: 18px !important; color:#00=
0000 !important; text-decoration: none;"><font color=3D"#e35205">Over 850 b=
ought</font></a></td> </tr> <tr> <td width=3D"70%" align=3D"left"> <span va=
lign=3D"top" style=3D"padding-right: 5px; font-family: Helvetica, Arial, sa=
ns-serif; font-size: 16px !important; line-height: 20px !important; text-de=
coration: line-through; color:#848484 !important; font-weight: 100;" class=
=3D"nameFont">$89.99</span> <span align=3D"left" valign=3D"top" style=3D"fo=
nt-family: Helvetica, Arial, sans-serif; font-size: 16px !important; line-h=
eight: 20px !important; font-weight: 300; text-decoration: none; color: #e3=
5205;" class=3D"nameFont">$27.99</span> </td> </tr> <tr> <td class=3D"nameF=
ont" align=3D"left" valign=3D"top" style=3D"font-family: Helvetica, Arial, =
sans-serif; font-size: 13px; color: #e35205; text-decoration: none; font-we=
ight: 500 !important;">Sale Ends 11/12</td> <td width=3D"30%" class=3D"name=
Font" align=3D"right" valign=3D"top" style=3D"font-family: Helvetica, Arial=
, sans-serif; font-size: 13px !important; line-height: 17px !important; fon=
t-weight: normal; font-weight: 600; color: #0185c6 !important; text-decorat=
ion: none; text-align:right; white-space: nowrap;"><a href=3D"https://www.g=
roupon.com/deals/gg-world-tech-toys-tool-swat-cash-register-bbq-grill-kitch=
en-play?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf5=
74337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c=
234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGo=
ods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" targ=
et=3D"_blank" style=3D"text-decoration:none;"><font color=3D"#0185c6">View&=
nbsp;Deal</font></a></td> </tr> </table> </td> </tr> <tr> <td style=3D"widt=
h: 10px; background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> </tr> </=
table> </td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]=
--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https://www.gro=
upon.com/deals/gg-anti-fatigue-relief-memory-foam-mats?p=3D15&utm_source=3D=
crm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c=
2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-0025906=
9d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Dde49e=
a14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" target=3D"_blank" style=3D"text=
-decoration:none;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"bor=
der: 0 none; border-spacing:0; font-family: Helvetica, Arial, sans-serif; c=
olor:#000000; font-weight: 100; background: #ffffff; width:290px;" valign=
=3D"top" class=3D"inner_container"align=3D'right'> <tr> <td style=3D"width:=
290px;" align=3D"center" valign=3D"top"> <table cellpadding=3D"0" cellspaci=
ng=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Helvetica,=
 Arial, sans-serif; color:#000000; font-weight: 100; background: #f2f2f2; w=
idth:100%;"> <tr> <td valign=3D"top" align=3D"center" width=3D"290" style=
=3D"width:290px;" class=3D"inner_container"><a href=3D"https://www.groupon.=
com/deals/gg-anti-fatigue-relief-memory-foam-mats?p=3D15&utm_source=3Dcrm_i=
m&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac=
134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe=
&CID=3DUS&tx=3D0&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b=
8e-4355-adcd-cbdf2964b3cf_0_20161111" style=3D"display: block; border: none=
;" target=3D"_blank"><img src=3D"https://img.grouponcdn.com/deal/42EYSPWYto=
4SCPbFR5Lq3wy3n54i/42-2048x1229/v1/c300x182.jpg" width=3D"290" style=3D"dis=
play: block; border: none; width: 290px;" class=3D"secondary-100" alt=3D"An=
ti-Fatigue Relief Memory Foam Kitchen Mats" /></a></td> </tr> <tr> <td styl=
e=3D"padding:16px;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"bo=
rder: 0 none; border-spacing:0; font-family: Helvetica, Arial, sans-serif; =
color:#000000; font-weight: 100; background: #f2f2f2; width:100%;"> <tr> <t=
d colspan=3D"2" class=3D"nameFont" style=3D"font-size: 14px !important; lin=
e-height: 18px !important; color:#000000 !important; text-decoration: none;=
 color: #333333 !important; width:100%;" align=3D"left" valign=3D"top"> Mem=
ory Foam Kitchen Mats </td> </tr> <tr> <td width=3D"70%" align=3D"left"> <s=
pan valign=3D"top" style=3D"padding-right: 5px; font-family: Helvetica, Ari=
al, sans-serif; font-size: 16px !important; line-height: 20px !important; t=
ext-decoration: line-through; color:#848484 !important; font-weight: 100;" =
class=3D"nameFont">$29.99</span> <span align=3D"left" valign=3D"top" style=
=3D"font-family: Helvetica, Arial, sans-serif; font-size: 16px !important; =
line-height: 20px !important; color:#53A318 !important; font-weight: 300; t=
ext-decoration: none; color: #88b74f;" class=3D"nameFont">$14.99</span> </t=
d> <td width=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" styl=
e=3D"font-family: Arial, Helvetica, sans-serif; font-size: 13px !important;=
 line-height: 17px !important; font-weight: normal; font-weight: 600; color=
: #0185c6 !important; text-decoration: none; text-align:right; white-space:=
 nowrap;"><a href=3D"https://www.groupon.com/deals/gg-anti-fatigue-relief-m=
emory-foam-mats?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c=
8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&u=
u=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutto=
n&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_201611=
11" target=3D"_blank" style=3D"text-decoration:none;"><font color=3D"#0185c=
6">View&nbsp;Deal</font></a></td> </tr> </table> </td> </tr> <tr> <td style=
=3D"width: 10px; background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> =
</tr> </table> </td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td> <=
![endif]--> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso =
9)|(IE)]> </tr> </table> <![endif]--> </tr> <tr> <td valign=3D"top" align=
=3D"left" width=3D"100%" style=3D"width: 600px;" class=3D"inner_container">=
 <!--[if (gte mso 9)|(IE)]> <table width=3D"600" align=3D"center" cellpaddi=
ng=3D"0" cellspacing=3D"0" border=3D"0"> <tr> <![endif]--> <!--[if (gte mso=
 9)|(IE)]> <td> <![endif]--> <a href=3D"https://www.groupon.com/deals/gg-cr=
ystal-filled-locket-pendants-6?p=3D16&utm_source=3Dcrm_im&utm_medium=3Demai=
l&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&d=
ate=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=
=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf=
2964b3cf_0_20161111" target=3D"_blank" style=3D"text-decoration:none;"> <ta=
ble cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spa=
cing:0; font-family: Helvetica, Arial, sans-serif; color:#000000; font-weig=
ht: 100; background: #ffffff; width:290px;" valign=3D"top" class=3D"inner_c=
ontainer"align=3D'left'> <tr> <td style=3D"width:290px;" align=3D"center" v=
align=3D"top"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: =
0 none; border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:=
#000000; font-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td vali=
gn=3D"top" align=3D"center" width=3D"290" style=3D"width:290px;" class=3D"i=
nner_container"><a href=3D"https://www.groupon.com/deals/gg-crystal-filled-=
locket-pendants-6?p=3D16&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bf=
d7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D2016111=
1&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dim=
age&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_2016=
1111" style=3D"display: block; border: none;" target=3D"_blank"><img src=3D=
"https://img.grouponcdn.com/deal/jXeSmvK9TVFW9seWjB72yXQxCQd/jX-1604x962/v1=
/c300x182.jpg" width=3D"290" style=3D"display: block; border: none; width: =
290px;" class=3D"secondary-100" alt=3D"Crystal-Filled Locket Pendants" /></=
a></td> </tr> <tr> <td style=3D"padding:16px;"> <table cellpadding=3D"0" ce=
llspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Hel=
vetica, Arial, sans-serif; color:#000000; font-weight: 100; background: #f2=
f2f2; width:100%;"> <tr> <td colspan=3D"2" class=3D"nameFont" style=3D"font=
-size: 14px !important; line-height: 18px !important; color:#000000 !import=
ant; text-decoration: none; color: #333333 !important; width:100%;" align=
=3D"left" valign=3D"top"> Crystal Filled Locket Pendants </td> </tr> <tr> <=
td width=3D"70%" align=3D"left"> <span valign=3D"top" style=3D"padding-righ=
t: 5px; font-family: Helvetica, Arial, sans-serif; font-size: 16px !importa=
nt; line-height: 20px !important; text-decoration: line-through; color:#848=
484 !important; font-weight: 100;" class=3D"nameFont">$65</span> <span alig=
n=3D"left" valign=3D"top" style=3D"font-family: Helvetica, Arial, sans-seri=
f; font-size: 16px !important; line-height: 20px !important; color:#53A318 =
!important; font-weight: 300; text-decoration: none; color: #88b74f;" class=
=3D"nameFont">$5</span> </td> <td width=3D"30%" class=3D"nameFont" align=3D=
"right" valign=3D"top" style=3D"font-family: Arial, Helvetica, sans-serif; =
font-size: 13px !important; line-height: 17px !important; font-weight: norm=
al; font-weight: 600; color: #0185c6 !important; text-decoration: none; tex=
t-align:right; white-space: nowrap;"><a href=3D"https://www.groupon.com/dea=
ls/gg-crystal-filled-locket-pendants-6?p=3D2&utm_source=3Dcrm_im&utm_medium=
=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561e=
d8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=
=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adc=
d-cbdf2964b3cf_0_20161111" target=3D"_blank" style=3D"text-decoration:none;=
"><font color=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </table> </t=
d> </tr> <tr> <td style=3D"width: 10px; background: #ffffff;">&nbsp;&nbsp;&=
nbsp;&nbsp;&nbsp;</td> </tr> </table> </td> </tr> </table> </a> <!--[if (gt=
e mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif=
]--> <a href=3D"https://www.groupon.com/deals/gg-structured-handbag-1?p=3D1=
7&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070=
ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11=
e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_c=
ampaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" target=3D"_blank=
" style=3D"text-decoration:none;"> <table cellpadding=3D"0" cellspacing=3D"=
0" style=3D"border: 0 none; border-spacing:0; font-family: Helvetica, Arial=
, sans-serif; color:#000000; font-weight: 100; background: #ffffff; width:2=
90px;" valign=3D"top" class=3D"inner_container"align=3D'right'> <tr> <td st=
yle=3D"width:290px;" align=3D"center" valign=3D"top"> <table cellpadding=3D=
"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-famil=
y: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; backgroun=
d: #f2f2f2; width:100%;"> <tr> <td valign=3D"top" align=3D"center" width=3D=
"290" style=3D"width:290px;" class=3D"inner_container"><a href=3D"https://w=
ww.groupon.com/deals/gg-structured-handbag-1?p=3D17&utm_source=3Dcrm_im&utm=
_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf=
386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=
=3DUS&tx=3D0&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4=
355-adcd-cbdf2964b3cf_0_20161111" style=3D"display: block; border: none;" t=
arget=3D"_blank"><img src=3D"https://img.grouponcdn.com/deal/Mm2x1oqBjqeta7=
uBL4BkkjGbyF7/Mm-960x582/v1/c300x182.jpg" width=3D"290" style=3D"display: b=
lock; border: none; width: 290px;" class=3D"secondary-100" alt=3D"Dasein Lo=
uie Collection Structured Handbag" /></a></td> </tr> <tr> <td style=3D"padd=
ing:16px;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 n=
one; border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#00=
0000; font-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td colspan=
=3D"2" class=3D"nameFont" style=3D"font-size: 14px !important; line-height:=
 18px !important; color:#000000 !important; text-decoration: none; color: #=
333333 !important; width:100%;" align=3D"left" valign=3D"top"> Dasein Louie=
 Structured Handbag </td> </tr> <tr> <td width=3D"70%" align=3D"left"> <spa=
n valign=3D"top" style=3D"padding-right: 5px; font-family: Helvetica, Arial=
, sans-serif; font-size: 16px !important; line-height: 20px !important; tex=
t-decoration: line-through; color:#848484 !important; font-weight: 100;" cl=
ass=3D"nameFont">$249</span> <span align=3D"left" valign=3D"top" style=3D"f=
ont-family: Helvetica, Arial, sans-serif; font-size: 16px !important; line-=
height: 20px !important; color:#53A318 !important; font-weight: 300; text-d=
ecoration: none; color: #88b74f;" class=3D"nameFont">$32.99</span> </td> <t=
d width=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" style=3D"=
font-family: Arial, Helvetica, sans-serif; font-size: 13px !important; line=
-height: 17px !important; font-weight: normal; font-weight: 600; color: #01=
85c6 !important; text-decoration: none; text-align:right; white-space: nowr=
ap;"><a href=3D"https://www.groupon.com/deals/gg-structured-handbag-1?p=3D2=
&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070e=
e1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e=
2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_ca=
mpaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" target=3D"_blank"=
 style=3D"text-decoration:none;"><font color=3D"#0185c6">View&nbsp;Deal</fo=
nt></a></td> </tr> </table> </td> </tr> <tr> <td style=3D"width: 10px; back=
ground: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> </tr> </table> </td> =
</tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (=
gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </tr> </tab=
le> <![endif]--> </tr> <tr> <td valign=3D"top" align=3D"left" width=3D"100%=
" style=3D"width: 600px;" class=3D"inner_container"> <!--[if (gte mso 9)|(I=
E)]> <table width=3D"600" align=3D"center" cellpadding=3D"0" cellspacing=3D=
"0" border=3D"0"> <tr> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endi=
f]--> <a href=3D"https://www.groupon.com/deals/gg-lg-g3-32gb-4g-lte-gsm-unl=
ocked-refurbished?p=3D18&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bf=
d7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D2016111=
1&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbu=
tton&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_201=
61111" target=3D"_blank" style=3D"text-decoration:none;"> <table cellpaddin=
g=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-f=
amily: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; backg=
round: #ffffff; width:290px;" valign=3D"top" class=3D"inner_container"align=
=3D'left'> <tr> <td style=3D"width:290px;" align=3D"center" valign=3D"top">=
 <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border=
-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#000000; font-=
weight: 100; background: #f2f2f2; width:100%;"> <tr> <td valign=3D"top" ali=
gn=3D"center" width=3D"290" style=3D"width:290px;" class=3D"inner_container=
"><a href=3D"https://www.groupon.com/deals/gg-lg-g3-32gb-4g-lte-gsm-unlocke=
d-refurbished?p=3D18&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8=
bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=
=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dimage&=
d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111=
" style=3D"display: block; border: none;" target=3D"_blank"><img src=3D"htt=
ps://img.grouponcdn.com/deal/3wfxZrhYPkbEoMHZQL5XhExyR5Cg/3w-960x576/v1/c30=
0x182.jpg" width=3D"290" style=3D"display: block; border: none; width: 290p=
x;" class=3D"secondary-100" alt=3D"LG G3 32GB 4G LTE Smartphone (GSM Unlock=
ed) (Refurbished)" /></a></td> </tr> <tr> <td style=3D"padding:16px;"> <tab=
le cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spac=
ing:0; font-family: Helvetica, Arial, sans-serif; color:#000000; font-weigh=
t: 100; background: #f2f2f2; width:100%;"> <tr> <td colspan=3D"2" class=3D"=
nameFont" style=3D"font-size: 14px !important; line-height: 18px !important=
; color:#000000 !important; text-decoration: none; color: #333333 !importan=
t; width:100%;" align=3D"left" valign=3D"top"> LG G3 32GB 4G LTE Smartphone=
 </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"top"><a h=
ref=3D"https://www.groupon.com/deals/gg-lg-g3-32gb-4g-lte-gsm-unlocked-refu=
rbished?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf5=
74337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c=
234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DMi=
ndstorm-Hero-3-deals&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_=
20161111" target=3D"_blank" style=3D"font-size: 14px !important; line-heigh=
t: 18px !important; color:#000000 !important; text-decoration: none;"><font=
 color=3D"#e35205">Over 100 bought</font></a></td> </tr> <tr> <td width=3D"=
70%" align=3D"left"> <span valign=3D"top" style=3D"padding-right: 5px; font=
-family: Helvetica, Arial, sans-serif; font-size: 16px !important; line-hei=
ght: 20px !important; text-decoration: line-through; color:#848484 !importa=
nt; font-weight: 100;" class=3D"nameFont">$499.99</span> <span align=3D"lef=
t" valign=3D"top" style=3D"font-family: Helvetica, Arial, sans-serif; font-=
size: 16px !important; line-height: 20px !important; font-weight: 300; text=
-decoration: none; color: #e35205;" class=3D"nameFont">$139.99</span> </td>=
 </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"top" style=3D"f=
ont-family: Helvetica, Arial, sans-serif; font-size: 13px; color: #e35205; =
text-decoration: none; font-weight: 500 !important;">Sale Ends 11/14</td> <=
td width=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" style=3D=
"font-family: Helvetica, Arial, sans-serif; font-size: 13px !important; lin=
e-height: 17px !important; font-weight: normal; font-weight: 600; color: #0=
185c6 !important; text-decoration: none; text-align:right; white-space: now=
rap;"><a href=3D"https://www.groupon.com/deals/gg-lg-g3-32gb-4g-lte-gsm-unl=
ocked-refurbished?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd=
7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111=
&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbut=
ton&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_2016=
1111" target=3D"_blank" style=3D"text-decoration:none;"><font color=3D"#018=
5c6">View&nbsp;Deal</font></a></td> </tr> </table> </td> </tr> <tr> <td sty=
le=3D"width: 10px; background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td=
> </tr> </table> </td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td>=
 <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https=
://www.groupon.com/deals/gg-buy-1-get-1-free-monster-test-testosterone-boos=
ter?p=3D19&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf5743=
37c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234=
c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods=
-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" target=
=3D"_blank" style=3D"text-decoration:none;"> <table cellpadding=3D"0" cells=
pacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Helvet=
ica, Arial, sans-serif; color:#000000; font-weight: 100; background: #fffff=
f; width:290px;" valign=3D"top" class=3D"inner_container"align=3D'right'> <=
tr> <td style=3D"width:290px;" align=3D"center" valign=3D"top"> <table cell=
padding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; =
font-family: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100;=
 background: #f2f2f2; width:100%;"> <tr> <td valign=3D"top" align=3D"center=
" width=3D"290" style=3D"width:290px;" class=3D"inner_container"><a href=3D=
"https://www.groupon.com/deals/gg-buy-1-get-1-free-monster-test-testosteron=
e-booster?p=3D19&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03=
cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df=
79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dimage&d=3D=
Goods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" st=
yle=3D"display: block; border: none;" target=3D"_blank"><img src=3D"https:/=
/img.grouponcdn.com/deal/35UKEkFX3e5XPuZNFrTrkxUhHNWx/35-2500x1500/v1/c300x=
182.jpg" width=3D"290" style=3D"display: block; border: none; width: 290px;=
" class=3D"secondary-100" alt=3D"Buy 1 Get 1 Free: Monster Test Testosteron=
e Booster (240-Ct.)" /></a></td> </tr> <tr> <td style=3D"padding:16px;"> <t=
able cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-sp=
acing:0; font-family: Helvetica, Arial, sans-serif; color:#000000; font-wei=
ght: 100; background: #f2f2f2; width:100%;"> <tr> <td colspan=3D"2" class=
=3D"nameFont" style=3D"font-size: 14px !important; line-height: 18px !impor=
tant; color:#000000 !important; text-decoration: none; color: #333333 !impo=
rtant; width:100%;" align=3D"left" valign=3D"top"> Monster Testosterone Boo=
ster </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"top">=
<a href=3D"https://www.groupon.com/deals/gg-buy-1-get-1-free-monster-test-t=
estosterone-booster?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8b=
fd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D201611=
11&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Db=
utton&d=3DMindstorm-Hero-3-deals&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbd=
f2964b3cf_0_20161111" target=3D"_blank" style=3D"font-size: 14px !important=
; line-height: 18px !important; color:#000000 !important; text-decoration: =
none;"><font color=3D"#e35205">Over 5,000 bought</font></a></td> </tr> <tr>=
 <td width=3D"70%" align=3D"left"> <span valign=3D"top" style=3D"padding-ri=
ght: 5px; font-family: Helvetica, Arial, sans-serif; font-size: 16px !impor=
tant; line-height: 20px !important; text-decoration: line-through; color:#8=
48484 !important; font-weight: 100;" class=3D"nameFont">$79.99</span> <span=
 align=3D"left" valign=3D"top" style=3D"font-family: Helvetica, Arial, sans=
-serif; font-size: 16px !important; line-height: 20px !important; color:#53=
A318 !important; font-weight: 300; text-decoration: none; color: #88b74f;" =
class=3D"nameFont">$17.99</span> </td> <td width=3D"30%" class=3D"nameFont"=
 align=3D"right" valign=3D"top" style=3D"font-family: Arial, Helvetica, san=
s-serif; font-size: 13px !important; line-height: 17px !important; font-wei=
ght: normal; font-weight: 600; color: #0185c6 !important; text-decoration: =
none; text-align:right; white-space: nowrap;"><a href=3D"https://www.groupo=
n.com/deals/gg-buy-1-get-1-free-monster-test-testosterone-booster?p=3D2&utm=
_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed=
8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82=
c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campai=
gn=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" target=3D"_blank" sty=
le=3D"text-decoration:none;"><font color=3D"#0185c6">View&nbsp;Deal</font><=
/a></td> </tr> </table> </td> </tr> <tr> <td style=3D"width: 10px; backgrou=
nd: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> </tr> </table> </td> </tr=
> </table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte =
mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </tr> </table> =
<![endif]--> </tr> <tr> <td valign=3D"top" align=3D"left" width=3D"100%" st=
yle=3D"width: 600px;" class=3D"inner_container"> <!--[if (gte mso 9)|(IE)]>=
 <table width=3D"600" align=3D"center" cellpadding=3D"0" cellspacing=3D"0" =
border=3D"0"> <tr> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--=
> <a href=3D"https://www.groupon.com/deals/gg-fingerless-knit-glove-2-pairs=
?p=3D20&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c=
822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2=
539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN=
&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" target=3D"=
_blank" style=3D"text-decoration:none;"> <table cellpadding=3D"0" cellspaci=
ng=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Helvetica,=
 Arial, sans-serif; color:#000000; font-weight: 100; background: #ffffff; w=
idth:290px;" valign=3D"top" class=3D"inner_container"align=3D'left'> <tr> <=
td style=3D"width:290px;" align=3D"center" valign=3D"top"> <table cellpaddi=
ng=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-=
family: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; back=
ground: #f2f2f2; width:100%;"> <tr> <td valign=3D"top" align=3D"center" wid=
th=3D"290" style=3D"width:290px;" class=3D"inner_container"><a href=3D"http=
s://www.groupon.com/deals/gg-fingerless-knit-glove-2-pairs?p=3D20&utm_sourc=
e=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806f=
bf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-002=
59069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Dde=
49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" style=3D"display: block; bor=
der: none;" target=3D"_blank"><img src=3D"https://img.grouponcdn.com/deal/3=
kgBKq5WwMQEyDDsGzF3vYy733jE/3k-1024x614/v1/c300x182.jpg" width=3D"290" styl=
e=3D"display: block; border: none; width: 290px;" class=3D"secondary-100" a=
lt=3D"Fingerless Knit Gloves (2-Pack)" /></a></td> </tr> <tr> <td style=3D"=
padding:16px;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border:=
 0 none; border-spacing:0; font-family: Helvetica, Arial, sans-serif; color=
:#000000; font-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td col=
span=3D"2" class=3D"nameFont" style=3D"font-size: 14px !important; line-hei=
ght: 18px !important; color:#000000 !important; text-decoration: none; colo=
r: #333333 !important; width:100%;" align=3D"left" valign=3D"top"> Fingerle=
ss Knit Gloves (2-Pack) </td> </tr> <tr> <td width=3D"70%" align=3D"left"> =
<span valign=3D"top" style=3D"padding-right: 5px; font-family: Helvetica, A=
rial, sans-serif; font-size: 16px !important; line-height: 20px !important;=
 text-decoration: line-through; color:#848484 !important; font-weight: 100;=
" class=3D"nameFont">$29.99</span> <span align=3D"left" valign=3D"top" styl=
e=3D"font-family: Helvetica, Arial, sans-serif; font-size: 16px !important;=
 line-height: 20px !important; color:#53A318 !important; font-weight: 300; =
text-decoration: none; color: #88b74f;" class=3D"nameFont">$10.99</span> </=
td> <td width=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" sty=
le=3D"font-family: Arial, Helvetica, sans-serif; font-size: 13px !important=
; line-height: 17px !important; font-weight: normal; font-weight: 600; colo=
r: #0185c6 !important; text-decoration: none; text-align:right; white-space=
: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-fingerless-knit-glov=
e-2-pairs?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03c=
f574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df7=
9c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3D=
Goods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" ta=
rget=3D"_blank" style=3D"text-decoration:none;"><font color=3D"#0185c6">Vie=
w&nbsp;Deal</font></a></td> </tr> </table> </td> </tr> <tr> <td style=3D"wi=
dth: 10px; background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> </tr> =
</table> </td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endi=
f]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https://www.g=
roupon.com/deals/gg-vaughn-home-theater-stand?p=3D21&utm_source=3Dcrm_im&ut=
m_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134c=
f386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=
=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-=
4355-adcd-cbdf2964b3cf_0_20161111" target=3D"_blank" style=3D"text-decorati=
on:none;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 no=
ne; border-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#000=
000; font-weight: 100; background: #ffffff; width:290px;" valign=3D"top" cl=
ass=3D"inner_container"align=3D'right'> <tr> <td style=3D"width:290px;" ali=
gn=3D"center" valign=3D"top"> <table cellpadding=3D"0" cellspacing=3D"0" st=
yle=3D"border: 0 none; border-spacing:0; font-family: Helvetica, Arial, san=
s-serif; color:#000000; font-weight: 100; background: #f2f2f2; width:100%;"=
> <tr> <td valign=3D"top" align=3D"center" width=3D"290" style=3D"width:290=
px;" class=3D"inner_container"><a href=3D"https://www.groupon.com/deals/gg-=
vaughn-home-theater-stand?p=3D21&utm_source=3Dcrm_im&utm_medium=3Demail&use=
r=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=
=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Db=
ody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b=
3cf_0_20161111" style=3D"display: block; border: none;" target=3D"_blank"><=
img src=3D"https://img.grouponcdn.com/deal/31YsLNuByyjAdXd7r1aPJnUFXugt/31-=
2048x1229/v1/c300x182.jpg" width=3D"290" style=3D"display: block; border: n=
one; width: 290px;" class=3D"secondary-100" alt=3D"Vaughn Home Theater Cons=
ole" /></a></td> </tr> <tr> <td style=3D"padding:16px;"> <table cellpadding=
=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-fa=
mily: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; backgr=
ound: #f2f2f2; width:100%;"> <tr> <td colspan=3D"2" class=3D"nameFont" styl=
e=3D"font-size: 14px !important; line-height: 18px !important; color:#00000=
0 !important; text-decoration: none; color: #333333 !important; width:100%;=
" align=3D"left" valign=3D"top"> Vaughn Home Theater Console </td> </tr> <t=
r> <td width=3D"70%" align=3D"left"> <span valign=3D"top" style=3D"padding-=
right: 5px; font-family: Helvetica, Arial, sans-serif; font-size: 16px !imp=
ortant; line-height: 20px !important; text-decoration: line-through; color:=
#848484 !important; font-weight: 100;" class=3D"nameFont">$235.09</span> <s=
pan align=3D"left" valign=3D"top" style=3D"font-family: Helvetica, Arial, s=
ans-serif; font-size: 16px !important; line-height: 20px !important; color:=
#53A318 !important; font-weight: 300; text-decoration: none; color: #88b74f=
;" class=3D"nameFont">$164.99</span> </td> <td width=3D"30%" class=3D"nameF=
ont" align=3D"right" valign=3D"top" style=3D"font-family: Arial, Helvetica,=
 sans-serif; font-size: 13px !important; line-height: 17px !important; font=
-weight: normal; font-weight: 600; color: #0185c6 !important; text-decorati=
on: none; text-align:right; white-space: nowrap;"><a href=3D"https://www.gr=
oupon.com/deals/gg-vaughn-home-theater-stand?p=3D2&utm_source=3Dcrm_im&utm_=
medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf3=
86561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=
=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-=
4355-adcd-cbdf2964b3cf_0_20161111" target=3D"_blank" style=3D"text-decorati=
on:none;"><font color=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </ta=
ble> </td> </tr> <tr> <td style=3D"width: 10px; background: #ffffff;">&nbsp=
;&nbsp;&nbsp;&nbsp;&nbsp;</td> </tr> </table> </td> </tr> </table> </a> <!-=
-[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> </td>=
 <![endif]--> <!--[if (gte mso 9)|(IE)]> </tr> </table> <![endif]--> </tr> =
<tr> <td valign=3D"top" align=3D"left" width=3D"100%" style=3D"width: 600px=
;" class=3D"inner_container"> <!--[if (gte mso 9)|(IE)]> <table width=3D"60=
0" align=3D"center" cellpadding=3D"0" cellspacing=3D"0" border=3D"0"> <tr> =
<![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=3D"https:=
//www.groupon.com/deals/gg-womens-moisture-cowl-neck-pullover-hoodie?p=3D22=
&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070e=
e1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e=
2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-PN&utm_ca=
mpaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" target=3D"_blank"=
 style=3D"text-decoration:none;"> <table cellpadding=3D"0" cellspacing=3D"0=
" style=3D"border: 0 none; border-spacing:0; font-family: Helvetica, Arial,=
 sans-serif; color:#000000; font-weight: 100; background: #ffffff; width:29=
0px;" valign=3D"top" class=3D"inner_container"align=3D'left'> <tr> <td styl=
e=3D"width:290px;" align=3D"center" valign=3D"top"> <table cellpadding=3D"0=
" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-family:=
 Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; background:=
 #f2f2f2; width:100%;"> <tr> <td valign=3D"top" align=3D"center" width=3D"2=
90" style=3D"width:290px;" class=3D"inner_container"><a href=3D"https://www=
.groupon.com/deals/gg-womens-moisture-cowl-neck-pullover-hoodie?p=3D22&utm_=
source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8=
f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c=
0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dimage&d=3DGoods-PN&utm_campaign=
=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" style=3D"display: block=
; border: none;" target=3D"_blank"><img src=3D"https://img.grouponcdn.com/d=
eal/3TFY1C82GxRjitDB4hnHxRTh6EFN/3T-1604x962/v1/c300x182.jpg" width=3D"290"=
 style=3D"display: block; border: none; width: 290px;" class=3D"secondary-1=
00" alt=3D"Women's Moisture-Wicking Active Hoodie" /></a></td> </tr> <tr> <=
td style=3D"padding:16px;"> <table cellpadding=3D"0" cellspacing=3D"0" styl=
e=3D"border: 0 none; border-spacing:0; font-family: Helvetica, Arial, sans-=
serif; color:#000000; font-weight: 100; background: #f2f2f2; width:100%;"> =
<tr> <td colspan=3D"2" class=3D"nameFont" style=3D"font-size: 14px !importa=
nt; line-height: 18px !important; color:#000000 !important; text-decoration=
: none; color: #333333 !important; width:100%;" align=3D"left" valign=3D"to=
p"> Women's Active Hoodie </td> </tr> <tr> <td width=3D"70%" align=3D"left"=
> <span valign=3D"top" style=3D"padding-right: 5px; font-family: Helvetica,=
 Arial, sans-serif; font-size: 16px !important; line-height: 20px !importan=
t; text-decoration: line-through; color:#848484 !important; font-weight: 10=
0;" class=3D"nameFont">$49.99</span> <span align=3D"left" valign=3D"top" st=
yle=3D"font-family: Helvetica, Arial, sans-serif; font-size: 16px !importan=
t; line-height: 20px !important; color:#53A318 !important; font-weight: 300=
; text-decoration: none; color: #88b74f;" class=3D"nameFont">$12.99</span> =
</td> <td width=3D"30%" class=3D"nameFont" align=3D"right" valign=3D"top" s=
tyle=3D"font-family: Arial, Helvetica, sans-serif; font-size: 13px !importa=
nt; line-height: 17px !important; font-weight: normal; font-weight: 600; co=
lor: #0185c6 !important; text-decoration: none; text-align:right; white-spa=
ce: nowrap;"><a href=3D"https://www.groupon.com/deals/gg-womens-moisture-co=
wl-neck-pullover-hoodie?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=
=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D=
20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody=
&c=3Dbutton&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3c=
f_0_20161111" target=3D"_blank" style=3D"text-decoration:none;"><font color=
=3D"#0185c6">View&nbsp;Deal</font></a></td> </tr> </table> </td> </tr> <tr>=
 <td style=3D"width: 10px; background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&n=
bsp;</td> </tr> </table> </td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)=
]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> <td> <![endif]--> <a href=
=3D"https://www.groupon.com/deals/gg-luxury-home-premium-ultra-soft-6-piece=
-bed-sheets-set?p=3D23&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7=
c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&=
uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutt=
on&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161=
111" target=3D"_blank" style=3D"text-decoration:none;"> <table cellpadding=
=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacing:0; font-fa=
mily: Helvetica, Arial, sans-serif; color:#000000; font-weight: 100; backgr=
ound: #ffffff; width:290px;" valign=3D"top" class=3D"inner_container"align=
=3D'right'> <tr> <td style=3D"width:290px;" align=3D"center" valign=3D"top"=
> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; borde=
r-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#000000; font=
-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td valign=3D"top" al=
ign=3D"center" width=3D"290" style=3D"width:290px;" class=3D"inner_containe=
r"><a href=3D"https://www.groupon.com/deals/gg-luxury-home-premium-ultra-so=
ft-6-piece-bed-sheets-set?p=3D23&utm_source=3Dcrm_im&utm_medium=3Demail&use=
r=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=
=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Db=
ody&c=3Dimage&d=3DGoods-PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b=
3cf_0_20161111" style=3D"display: block; border: none;" target=3D"_blank"><=
img src=3D"https://img.grouponcdn.com/deal/EpAWKQgG1ZWzrVta2C4KFRUoNTb/Ep-1=
000x600/v1/c300x182.jpg" width=3D"290" style=3D"display: block; border: non=
e; width: 290px;" class=3D"secondary-100" alt=3D"Microfiber Luxury Home Ult=
ra Soft Sheet Set (6-Piece)" /></a></td> </tr> <tr> <td style=3D"padding:16=
px;"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; b=
order-spacing:0; font-family: Helvetica, Arial, sans-serif; color:#000000; =
font-weight: 100; background: #f2f2f2; width:100%;"> <tr> <td colspan=3D"2"=
 class=3D"nameFont" style=3D"font-size: 14px !important; line-height: 18px =
!important; color:#000000 !important; text-decoration: none; color: #333333=
 !important; width:100%;" align=3D"left" valign=3D"top"> Microfiber Sheets =
(6-Piece) </td> </tr> <tr> <td class=3D"nameFont" align=3D"left" valign=3D"=
top"><a href=3D"https://www.groupon.com/deals/gg-luxury-home-premium-ultra-=
soft-6-piece-bed-sheets-set?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&us=
er=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=
=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Db=
ody&c=3Dbutton&d=3DMindstorm-Hero-3-deals&utm_campaign=3Dde49ea14-4b8e-4355=
-adcd-cbdf2964b3cf_0_20161111" target=3D"_blank" style=3D"font-size: 14px !=
important; line-height: 18px !important; color:#000000 !important; text-dec=
oration: none;"><font color=3D"#e35205">Over 10,000 bought</font></a></td> =
</tr> <tr> <td width=3D"70%" align=3D"left"> <span valign=3D"top" style=3D"=
padding-right: 5px; font-family: Helvetica, Arial, sans-serif; font-size: 1=
6px !important; line-height: 20px !important; text-decoration: line-through=
; color:#848484 !important; font-weight: 100;" class=3D"nameFont">$99.99</s=
pan> <span align=3D"left" valign=3D"top" style=3D"font-family: Helvetica, A=
rial, sans-serif; font-size: 16px !important; line-height: 20px !important;=
 color:#53A318 !important; font-weight: 300; text-decoration: none; color: =
#88b74f;" class=3D"nameFont">$19.99</span> </td> <td width=3D"30%" class=3D=
"nameFont" align=3D"right" valign=3D"top" style=3D"font-family: Arial, Helv=
etica, sans-serif; font-size: 13px !important; line-height: 17px !important=
; font-weight: normal; font-weight: 600; color: #0185c6 !important; text-de=
coration: none; text-align:right; white-space: nowrap;"><a href=3D"https://=
www.groupon.com/deals/gg-luxury-home-premium-ultra-soft-6-piece-bed-sheets-=
set?p=3D2&utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf57433=
7c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c=
-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutton&d=3DGoods-=
PN&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" target=
=3D"_blank" style=3D"text-decoration:none;"><font color=3D"#0185c6">View&nb=
sp;Deal</font></a></td> </tr> </table> </td> </tr> <tr> <td style=3D"width:=
 10px; background: #ffffff;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> </tr> </ta=
ble> </td> </tr> </table> </a> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--=
> <!--[if (gte mso 9)|(IE)]> </td> <![endif]--> <!--[if (gte mso 9)|(IE)]> =
</tr> </table> <![endif]--> </tr> </table> <table cellpadding=3D"0" cellspa=
cing=3D"0" style=3D"border: 0 none; border-spacing:0; font-family: Helvetic=
a, Arial, sans-serif; color:#000000; font-weight: 100; width: 600px;" align=
=3D"center" class=3D"inner_container"> <tr> <td style=3D"padding: 30px;" al=
ign=3D"center"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"font-fa=
mily: Arial, Helvetica, sans-serif; font-size:14px !important; line-height:=
19px !important; color:#333; width:200px;" align=3D"center"> <tr> <td heigh=
t=3D"45" bgcolor=3D"#3ebddc" background=3D"https://s3.grouponcdn.com/email/=
images/prom_night/global_buttons/pn-btn-gradient-blue.gif" background-repea=
t=3D"repeat-x" style=3D"height:45px; text-align:center;"><a href=3D"https:/=
/www.groupon.com/goods?utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7=
c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&=
uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dbody&c=3Dbutt=
on&d=3DGoods&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111=
" style=3D"padding: 10px 0 10px 0; color:#ffffff; font-size:16px; font-weig=
ht: 500; text-decoration:none;">VIEW&nbsp;ALL&nbsp;GOODS</a></td> </tr> </t=
able> </td> </tr> </table> </td> </tr> </table> </td> </tr> </table> <table=
 cellpadding=3D"0" cellspacing=3D"0" style=3D"border: 0 none; border-spacin=
g:0; font-family: Helvetica, Arial, sans-serif; color:#000000; font-weight:=
 100; width: 100%; background: #ececec; padding-top: 10px;" align=3D"center=
"> <tr> <td> </td> </tr> </table> <table cellpadding=3D"0" cellspacing=3D"0=
" style=3D"border: 0 none; border-spacing:0; font-family: Helvetica, Arial,=
 sans-serif; color:#000000; font-weight: 100; width: 100%; background: #ece=
cec;" align=3D"center"> <tr> <td>&nbsp;</td> </tr> </table> <table cellpadd=
ing=3D"0" cellspacing=3D"0" style=3D"font-family: Arial, Helvetica, sans-se=
rif; font-size:14px !important; line-height:19px !important; color:#333; wi=
dth: 100%; background: #ffffff;" align=3D"center"> <tr> <td align=3D"center=
"> <table cellpadding=3D"0" cellspacing=3D"0" style=3D"font-family: Arial, =
Helvetica, sans-serif; font-size:14px !important; line-height:19px !importa=
nt; color:#333; width: 600px;" align=3D"center" class=3D"inner_container"> =
<tr> <td align=3D"center" style=3D"padding: 30px 10px 0 10px; font-size: 12=
px !important; line-height: 22px !important; color:#000000 !important; text=
-decoration: none;"> To feature your business on Groupon, <a href=3D"https:=
//www.groupon.com/merchant/get-started?utm_source=3Dcrm_im&utm_medium=3Dema=
il&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&=
date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=
=3D&c=3Dlink&d=3DGrouponMerchant&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbd=
f2964b3cf_0_20161111" target=3D"_blank" style=3D"color:#0185C6; text-decora=
tion:none;" title=3D"Groupon Merchant">get started</a> at Groupon Merchant.=
 <br/><br/>You are receiving this email because kyle@kylefisher.com is sign=
ed up to receive Groupon communications. To adjust your settings or to unsu=
bscribe, please <a href=3D"https://www.groupon.com/subscription_center/mana=
ge/consumer/f79c234c-2539-11e2-82c0-00259069d5fe?cmplistId=3Dchannel:goods&=
utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee=
1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2=
-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dfooter&c=3Dlink&d=3Dchannel_unsub&ut=
m_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" style=3D"colo=
r:#0185C6; text-decoration:none;" target=3D"_blank">click here</a>. <br /><=
br />Delivered by <a href=3D"http://www.groupon.com?utm_source=3Dcrm_im&utm=
_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf=
386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=
=3DUS&tx=3D0&s=3Dfooter&c=3Dlink&d=3Dhome&utm_campaign=3Dde49ea14-4b8e-4355=
-adcd-cbdf2964b3cf_0_20161111" target=3D"_blank" style=3D'color:#0185C6; te=
xt-decoration:none;'>Groupon</a> <a href=3D"http://www.groupon.com" style=
=3D"color:#333; text-decoration:none;">600 W. Chicago Avenue, Suite 400, Ch=
icago, IL 60654, USA</a></td> </tr> <tr> <td align=3D"center" style=3D"padd=
ing: 5px 10px 50px 10px; font-size: 12px !important; line-height: 22px !imp=
ortant; color:#000000 !important; text-decoration: none;"><a href=3D"http:/=
/www.groupon.com/customer_support?utm_source=3Dcrm_im&utm_medium=3Demail&us=
er=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=
=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Df=
ooter&c=3Dlink&d=3Dcontact-us&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf29=
64b3cf_0_20161111" style=3D"color:#0185C6; text-decoration:none;" target=3D=
"_blank">Contact Us</a> | <a href=3D"https://www.groupon.com/faq?utm_source=
=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fb=
f5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c-2539-11e2-82c0-0025=
9069d5fe&CID=3DUS&tx=3D0&s=3Dfooter&c=3Dlink&d=3DFAQ&utm_campaign=3Dde49ea1=
4-4b8e-4355-adcd-cbdf2964b3cf_0_20161111" style=3D"color:#0185C6; text-deco=
ration:none;" target=3D"_blank">FAQ</a> | <a href=3D"https://www.groupon.co=
m/privacy?utm_source=3Dcrm_im&utm_medium=3Demail&user=3Dd8bfd7c8bf03cf57433=
7c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&date=3D20161111&uu=3Df79c234c=
-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0&s=3Dfooter&c=3Dlink&d=3Dprivac=
y_statement&utm_campaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111"=
 style=3D"color:#0185C6; text-decoration:none;" target=3D"_blank">Privacy S=
tatement</a></td> </tr> </table> </td> </tr> </table> <img src =3D "http://=
www.groupon.com/analytic/track.gif?p=3D2&utm_domain=3Dkylefisher.com&utm_ca=
mpaign=3Dde49ea14-4b8e-4355-adcd-cbdf2964b3cf_0_20161111&deals=3D70a68696-9=
55d-11e6-bff2-00259069d7cc,38de4d54-60c2-11e6-92a9-00259069d868,e9d59326-6a=
5c-11e6-aa0d-00259069d7cc,b6d442aa-34b6-11e6-8313-00259069d868,9454070e-a5e=
2-11e6-b372-00259069d7cc,4ddf3d54-97d0-11e6-89cb-00259060b5da,b8671256-7b64=
-11e6-9eb8-00259069d7cc,445d7888-960c-11e6-851f-00259069d7cc,2fd44e8c-a53e-=
11e6-944b-002590604002,763e7eb6-97be-11e6-8b6c-00259060b5da,bf78fb3c-6a33-1=
1e6-8b15-002590604002,03686c10-8ca8-11e6-8b16-00259069d7cc,51506417-cb99-45=
8d-978d-ec03486fbb9d,503c69bc-8b61-11e6-89fc-00259069d868,84c7c7f2-9fad-11e=
6-8201-00259069d7cc,930d9a8a-9b93-11e6-9822-00259069d7cc,597d504c-9c12-11e6=
-bf24-00259060b5da,29533942-8bf3-11e6-8d1e-00259060b5da,9fab8d3e-3198-11e6-=
86a9-00259069d7cc,4aaedf7c-9f7d-11e6-a8e6-002590604002,bc430798-961e-11e6-9=
903-002590604002,b9d91282-a072-11e6-b796-00259069d7cc,0e86e1c4-5b5e-11e6-87=
6a-002590604002&channel_deals=3Dnull&utm_source=3Dcrm_im&utm_medium=3Demail=
&user=3Dd8bfd7c8bf03cf574337c822070ee1ed8f806fbf5c2acac134cf386561ed8cd2&da=
te=3D20161111&uu=3Df79c234c-2539-11e2-82c0-00259069d5fe&CID=3DUS&tx=3D0" he=
ight=3D"1" width=3D"1" style=3D"display: none !important;" /> </body> </htm=
l>

